#!perl

package Title::Study;

use v5.10;
use strict;
use warnings;
use utf8;
use open ':std', ':encoding(UTF-8)';

our @ISA = qw(Exporter);
our @EXPORT = qw(study);

use lib '.';

use Util;

my @TAG_ORDER = qw(
  ROMAN
  MEET
  TNAME
  DESTROY
  ORIGIN
  CLUB

  ORGANIZATION 
  ZONE 
  SPONSOR 
  COUNTRY 
  NATIONALITY
  REGION 
  CITY 
  LOCALITY 
  UNIVERSITY 
  FORM 
  MOVEMENT
  CAPTAIN 
  GENDER
  AGE
  SCORING
  PERSON
  ITERATOR
  STAGE
  TIME
  MONTH
  WEEKDAY
  ORDINAL
  PARTICLE
  AMBIGUOUS
);

my $PREFIX = 'TITLE_';
our $histo_title;

my @LOCAL_SUBS =
(
  # { START => , END => , TEXT => '',
    # CORR => '' },

  { START => 70, END => 193, TEXT => '12WBO',
    CORR => '12th WBO - 2004' },
  { START => 266, END => 285, TEXT => "Champion's Cup",
    CORR => "European Champions' Cup" },
  { START => 797, END => 822, TEXT => 'European Youth Bridge Team Champ', 
    CORR => 'European U26 Open Teams' },
  { START => 1116, END => 1128, TEXT => 'Grand Prix of Poland',
    CORR => 'Grand Prix of Poland Pairs' },
  { START => 1192, END => 1205, 
    TEXT => 'Norwegian [Tt]eams* [Cc]hampionships*',
    CORR => 'Norwegian Club Teams' },
  { START => 1301, END => 1305, TEXT => 'Winter\s+Nationals*',
    CORR => 'Indian Winter Nationals' },
  { START => 1835, END => 1845, TEXT => 'ANC 2008 Open',
    CORR => 'ANC Open 2008' },
  { START => 1853, END => 1873, TEXT => 'Australian Seniors Teams',
    CORR => 'Australian National Senior Teams' },
  { START => 2426, END => 2437, TEXT => 'Australian Open Teams',
    CORR => 'Australian Open Trials' },
  { START => 2750, END => 2756, TEXT => 'Winter Open Teams',
    CORR => 'Turkish Winter Open Teams' },
  { START => 3077, END => 3078, TEXT => 'Grand Prix of Poland',
    CORR => 'Grand Prix of Poland Pairs' },
  { START => 3144, END => 3157, 
    TEXT => 'Norwegian [Tt]eams* [Cc]hampionships*',
    CORR => 'Norwegian Club Teams' },
  { START => 3242, END => 3267, TEXT => 'EUBC', 
    CORR => 'European University Team Championship' },
  { START => 3453, END => 3455, TEXT => 'Grand Prix of Poland',
    CORR => 'Grand Prix of Poland Pairs' },
  { START => 3620, END => 3631, TEXT => 'Pula', 
    CORR => 'Pula Bridge Festival' },
  { START => 3657, END => 3670, TEXT => 
    'United States Seniors Bridge Championship', 
    CORR => 'US Senior Trials' },
  { START => 3708, END => 3728, TEXT => 'CCBA Championships', 
    CORR => 'Chinese Team Championships' },
  { START => 3729, END => 3738, TEXT => 'Stara Zagora 2007 Open Teams',
    CORR => 'Stara Zagora Open Teams 2007' },
  { START => 4118, END => 4133, TEXT => 'GP of Poland\s*-?\s*BAM',
    CORR => 'Polish BAM Cup' },
  { START => 4315, END => 4318, TEXT => 'Czech Teams Champ_',
    CORR => 'Czech First League' },
  { START => 4339, END => 4346, TEXT => 'Canadian National Championships',
    CORR => 'Canadian Open Teams' },
  { START => 4339, END => 4346, TEXT => 'Canadian Championship',
    CORR => 'Canadian Open Teams' },
  { START => 4392, END => 4407, TEXT => 'Indonesia Qual Multievent',
    CORR => 'Indonesian Open Trials' },
  { START => 4441, END => 4446, TEXT => '06-07',
    CORR => '' },
  { START => 4636, END => 4678, TEXT => 'EC',
    CORR => 'European Transnational Championships' },
  { START => 5085, END => 5130, TEXT => 'Women Elite Tournament',
    CORR => 'APBF Women Elite Tournament' },
  { START => 5356, END => 5362, 
    TEXT => 'Samobor 5th Invitational Bridge Meeting',
    CORR => '5th Samobor Bridge Meeting' },
  { START => 5575, END => 5587, TEXT => 'English Camrose Trials*', 
    CORR => 'English Open Trials' },
  { START => 5732, END => 5746, 
    TEXT => 'Winter Nationals* Bridge\s+Championship',
    CORR => 'Indian Winter Nationals' },
  { START => 5767, END => 5770, TEXT => 'Istanbul Team Championships*',
    CORR => 'Istanbul Winter Teams' },
  { START => 5877, END => 5895, TEXT => 'English Lady Milne Trials*',
    CORR => 'English Women Team Trials' },
  { START => 5877, END => 5895, TEXT => 'Lady Milne Trials*',
    CORR => 'English Women Team Trials' },
  { START => 6134, END => 6137, TEXT => 'Grand Prix of Poland \(BAM\)',
    CORR => 'Polish BAM Cup' },
  { START => 6268, END => 6279, TEXT => 'Selection Senior', 
    CORR => 'French Senior Trials' },
  { START => 6372, END => 6430, TEXT => 'Euro\s+[oO]pen\s+[tT]eams', 
    CORR => 'European National Open Teams'},
  { START => 6856, END => 6975, TEXT => 'Cap Gemini', 
    CORR => 'Cap Gemini World Top Tournament' },
  { START => 7256, END => 7271, TEXT => 
    'Generali European Team Championships', 
    CORR => 'Generali European Open Teams' },
  { START => 7672, END => 7701, TEXT => 'Euro Team Championships',
    CORR => 'Generali European Open Teams' },
  { START => 7672, END => 7702, TEXT => 'European Team Championships',
    CORR => 'Generali European Open Teams' },
  { START => 7843, END => 7865, TEXT => 'ACBL 1999 Open Team Trials', 
    CORR => '1999 USA International Team Trials' },
  { START => 8123, END => 8127, TEXT => 'MONBU Kanto-Final',
    CORR => 'MONBU Kanto Teams - Final' },
  { START => 8182, END => 8185, TEXT => 'Vic Playoff',
    CORR => 'Victorian Open Teams - Playoff' },
  { START => 8186, END => 8199, TEXT => 'White House', 
    CORR => 'White House International' },
  { START => 8236, END => 8242, TEXT => 'Selection Francaise', 
    CORR => 'French Open Trials' },
  { START => 8324, END => 8331, TEXT => 'Canadian Team',
    CORR => 'Canadian Open Teams' },
  { START => 8351, END => 8353, TEXT => 'BAM Grand Prix of Poland',
    CORR => 'Grand Prix of Poland Pairs' },
  { START => 8489, END => 8503, TEXT => 'Selection Francaise', 
    CORR => 'French Open Trials' },
  { START => 8652, END => 8656, TEXT => 'Team Orange - Ireland',
    CORR => 'Friendly Match' },
  { START => 8680, END => 8688, TEXT => 'Estoril',
    CORR => 'Estoril Swiss Teams' },
  { START => 8802, END => 8807, TEXT => 'Interclub',
    CORR => 'French Cup' },
  { START => 8808, END => 8813, TEXT => 'Zone 7',
    CORR => 'South Pacific Zone 7 Championship' },
  { START => 8967, END => 8982, TEXT => 'England v Netherlands Open',
    CORR => 'Friendly Match' },
  { START => 9314, END => 9318, TEXT => 'R8',
    CORR => 'Quarterfinal' },
  { START => 9405, END => 9421, TEXT => 'Olrud Easter Pairs',
    CORR => 'Olrud Easter Swiss Pairs' },
  { START => 9423, END => 9436, TEXT => 'Olrud Easter Teams',
    CORR => 'Olrud Easter Swiss Teams' },
  { START => 9728, END => 9770, TEXT => 'Indonesian Final Premier League',
    CORR => 'Indonesian Premier League Final' },
  { START => 9866, END => 9902, TEXT => 'Netherlands - Poland',
    CORR => 'Friendly Match' },
  { START => 9951, END => 9986, TEXT => 'Lozenets', 
    CORR => 'Lozenets Bridge Festival' },
  { START => 10525, END => 10540, TEXT => 'Hindusthan Club',
    CORR => 'Hindusthan Club Teams' },
  { START => 10541, END => 10566, TEXT => 'kongresowy tu*rniej teamów',
    CORR => 'Baltic Congress - Teams' },
  { START => 10907, END => 10922, TEXT => 'GP Warszawy',
    CORR => 'Grand Prix of Poland Teams' },
  { START => 11116, END => 11159, TEXT => 'Pula',
    CORR => 'Pula Bridge Festival' },
  { START => 11160, END => 11175, TEXT => 'TNOT',
    CORR => 'World Transnational Open Teams' },
  { START => 11224, END => 11240, TEXT => "Finale de l'interclub France",
    CORR => 'French First Division' },
  { START => 11213, END => 11227, TEXT => 'Championship of Poland - Patton',
    CORR => 'Polish Patton Teams' },
  { START => 11229, END => 11247, TEXT => 'Grand Prix of Poland',
    CORR => 'Grand Prix of Poland Pairs' },
  { START => 11683, END => 11873, TEXT => 'Premier League', 
    CORR => 'English Premier League' },
  { START => 11729, END => 11764, TEXT => 'Swedish Trial', 
    CORR => 'Swedish Open Pair Trials' },
  { START => 11772, END => 11784, TEXT => 'Swedish Open Trials', 
    CORR => 'Swedish Open Pair Trials' },
  { START => 12220, END => 12270, TEXT => 'Winter\s+Nationals*',
    CORR => 'Indian Winter Nationals' },
  { START => 12222, END => 12253, TEXT => 'Grand Prix of Poland',
    CORR => 'Grand Prix of Poland Pairs' },
  { START => 12378, END => 12400, TEXT => 'National Seniors Teams',
    CORR => 'Australian National Senior Teams' },
  { START => 12395, END => 12422, TEXT => "Australian Women's Teams",
    CORR => 'Australian National Women Teams' },
  { START => 12413, END => 12423, TEXT => "Australian Seniors Teams",
    CORR => 'Australian National Senior Teams' },
  { START => 12439, END => 12492, TEXT => 'Hellenic Team Trials',
    CORR => 'Greek Open Pair Trials' },
  { START => 12520, END => 12600, TEXT => 'Hellenic Teams* Trials',
    CORR => 'Greek Open Pair Trials' },
  { START => 12739, END => 12756, TEXT => 'GP of Poland',
    CORR => 'Grand Prix of Poland Pairs' },
  { START => 12745, END => 12792, TEXT => '[YÝ]stanbul Teams',
    CORR => 'Istanbul Winter Teams' },
  { START => 12713, END => 12779, TEXT => 'Romanian National\s+Teams',
    CORR => 'Romanian Open Trials' },
  { START => 12714, END => 12792, TEXT => 'Istanbul Teams Championship',
    CORR => 'Istanbul Winter Teams' },
  { START => 12722, END => 12792, TEXT => 'Ýstanbul\s+Championship',
    CORR => 'Istanbul Winter Teams' },
  { START => 12825, END => 12862, TEXT => 'Izmir Teams',
    CORR => 'Izmir Winter Teams Cup' },
  { START => 12878, END => 12914, TEXT => 'Selection Ostende',
    CORR => 'French Open Trials' },
  { START => 12983, END => 13010, TEXT => 'Grand Prix of Poland',
    CORR => 'Grand Prix of Poland Pairs' },
  { START => 13095, END => 13105, TEXT => 'R8',
    CORR => 'Quarterfinal' },
  { START => 13234, END => 13251, TEXT => 'Danish Teams* Test',
    CORR => 'Danish Open Pairs Trials' },
  { START => 13235, END => 13242, TEXT => 'Top Individual',
    CORR => 'Polish Top Individual' },
  { START => 13239, END => 13252, TEXT => 'Olrud Easter',
    CORR => 'Olrud Easter Swiss Pairs' },
  { START => 13253, END => 13267, TEXT => 'OlrudEasterTeams',
    CORR => 'Olrud Easter Swiss Teams' },
  { START => 13270, END => 13276, TEXT => 'Selection Ostende',
    CORR => 'French Open Trials' },
  { START => 13279, END => 13297, TEXT => 'Selection Open Ostende',
    CORR => 'French Open Trials' },
  { START => 13279, END => 13297, TEXT => 'Selection Dames Ostende',
    CORR => 'French Women Trials' },
  { START => 13315, END => 13359, TEXT => 'Aust Seniors Open Trials*',
    CORR => 'Australian Senior Pairs' },
  { START => 13631, END => 13670, 
    TEXT => 'International Bridge Festival - Plovdiv',
    CORR => 'Plovdiv Bridge Festival' },
  { START => 13470, END => 13528, TEXT => 'Netherlands v Poland',
    CORR => "Friendly Match - 't Onstein" },
  { START => 13470, END => 13528, TEXT => 'Netherlands v Israel',
    CORR => "Friendly Match - 't Onstein" },
  { START => 13598, END => 13615, 
    TEXT => 'Indonesia Bridge Champs - Inter Province',
    CORR => 'Indonesian Inter-Province Championship' },
  { START => 13748, END => 13840, TEXT => 'Selection Dame Ostende',
    CORR => 'French Women Trials' },
  { START => 14213, END => 14222, TEXT => 'CBF',
    CORR => 'CBC' },
  { START => 14215, END => 14275, TEXT => 'Budimex [GM]PP',
    CORR => 'Budimex - Grand Prix of Poland Pairs' },
  { START => 14339, END => 14360, TEXT => 'Summer Nationals',
    CORR => 'Indian Summer Nationals' },
  { START => 14494, END => 15000, TEXT => 'Wronie - Summer time',
    CORR => 'Wronie Summer Teams' },
  { START => 14860, END => 14877, TEXT => 'R8',
    CORR => 'Quarterfinal' },
  { START => 15142, END => 15156, TEXT => 'Pula', 
    CORR => 'Pula Bridge Festival' },
  { START => 15435, END => 15459, 
    TEXT => 'International Bridge Festival - Stara Zagora', 
    CORR => 'Stara Zagora Bridge Festival' },
  { START => 15451, END => 15459, 
    TEXT => 'Int_ Bridge Festival - Stara Zagora', 
    CORR => 'Stara Zagora Bridge Festival' },
  { START => 15441, END => 15453, TEXT => 'Polish Championships', 
    CORR => 'Boleslawiec Festival' },
  { START => 15457, END => 15463, TEXT => 'Grand Prix of Poland',
    CORR => 'Grand Prix of Poland Pairs' },
  { START => 15603, END => 15628, TEXT => 'World Juniors Championships*', 
    CORR => 'World Series - Damiani Trophy' },
  { START => 15883, END => 15886, TEXT => 'Gran Final Argentina Damas', 
    CORR => 'Argentinian Women Trials - Final' },
  { START => 15919, END => 15966, TEXT => 'Finnish Team Trials', 
    CORR => 'Finnish Open Pair Trials' },
  { START => 16061, END => 16111, TEXT => 'Romanian National Teams',
    CORR => 'Romanian League' },
  { START => 16116, END => 16128, TEXT => 'R16',
    CORR => 'Rof16' },
  { START => 16252, END => 16304, TEXT => 'Winter\s+Nationals*',
    CORR => 'Indian Winter Nationals' },
  { START => 16307, END => 16324, TEXT => 'GP of Poland',
    CORR => 'Grand Prix of Poland Pairs' },
  { START => 16465, END => 16998, TEXT => 'Open Preferent',
    CORR => 'Open Catalunya Preferent Teams' },
  { START => 16474, END => 16480, TEXT => 'TGRs 2nd Auction Pairs',
    CORR => 'TGR Auction Pairs' },
  { START => 16588, END => 16592, TEXT => 'R20',
    CORR => 'Rof20' },
  { START => 16748, END => 16751, TEXT => '2010-2011',
    CORR => '' },
  { START => 16768, END => 16846, TEXT => 'Istanbul Teams Championship',
    CORR => 'Istanbul Winter Teams' },
  { START => 16772, END => 16834, TEXT => 'Romanian National Teams',
    CORR => 'Romanian League' },
  { START => 16936, END => 16987, TEXT => 'Danish Teams',
    CORR => 'Danish First Division' },
  { START => 17035, END => 17045, TEXT => 'Summer Nationals',
    CORR => 'Indian Summer Nationals' },
  { START => 17089, END => 17097, TEXT => 'R8',
    CORR => 'Quarterfinal' },
  { START => 17358, END => 17377, TEXT => 'Australian Seniors Trials',
    CORR => 'Australian Senior Teams' },
  { START => 17288, END => 17318, TEXT => 'Selecci[oó]n Damas',
    CORR => 'South American Women Trials' },
  { START => 17342, END => 17377, TEXT => 'Australian Senior Trials',
    CORR => 'Australian Senior Teams' },
  { START => 17345, END => 17383, TEXT => 'Netherlands - Israel',
    CORR => "Friendly Match - 't Onstein" },
  { START => 17501, END => 17508, TEXT => 'SELECTION TRIALS - BFI',
    CORR => 'Indian Open Trials' },
  { START => 17522, END => 17535, TEXT => 'sELECTION TRIALS - INDIA',
    CORR => 'Indian Open Trials' },
  { START => 18091, END => 18153, TEXT => 'Netherlands vs Iceland',
    CORR => "Friendly Match - 't Onstein" },
  { START => 18664, END => 18811, TEXT => 'Mixed Teams',
    CORR => 'European Transnational Mixed Teams' },
  { START => 18672, END => 19067, TEXT => 'EC',
    CORR => 'European Transnational Championships' },
  { START => 19100, END => 19108, TEXT => 'Grand Prix of Poland',
    CORR => 'Grand Prix of Poland Teams' },
  { START => 19179, END => 19187, TEXT => 'Interprovincial Finals',
    CORR => 'New Zealand Inter-Provincial Open Teams' },
  { START => 19454, END => 19540, 
    TEXT => 'Inter-City Bridge Championships*',
    CORR => 'Chinese Inter-City Teams' },
  { START => 19853, END => 19888, TEXT => 'Pula', 
    CORR => 'Pula Bridge Festival' },
  { START => 20025, END => 20044, TEXT => 'Polish Championships', 
    CORR => 'Boleslawiec Festival' },
  { START => 20028, END => 20061, TEXT => 'Nationale Interclubs*',
    CORR => 'French First Division' },
  { START => 20051, END => 20063, TEXT => 'Grand Prix of Poland',
    CORR => 'Grand Prix of Poland Pairs' },
  { START => 20118, END => 20186, TEXT => 'S[eé]l[eé]ction',
    CORR => 'French Open Trials' },
  { START => 20121, END => 20135, TEXT => 'Patton Teams',
     CORR => 'Mersin Bridge Festival - Patton Teams' },
  { START => 20349, END => 20394, TEXT => 'Bridge Festival',
     CORR => 'Stara Zagora Bridge Festival' },
  { START => 20920, END => 20930, TEXT => 'Romanian National Teams',
    CORR => 'Romanian League' },
  { START => 21056, END => 21126, TEXT => 'Sélection',
    CORR => 'French Open Trials' },
  { START => 21266, END => 21273, TEXT => 'Senior KO',
    CORR => 'United States Seniors Bridge Championship' },
  { START => 21344, END => 21394, TEXT => 'Winter\s+Nationals*',
    CORR => 'Indian Winter Nationals' },
  { START => 21520, END => 21553, TEXT => 'Grand Prix of Poland',
    CORR => 'Grand Prix of Poland Pairs' },
  { START => 21609, END => 21690, TEXT => 'Danish Open Team - trials 2012',
    CORR => 'Danish Team Trials 2012' },
  { START => 21647, END => 21669, TEXT => 'Lady Milne Trials',
    CORR => 'English Women Pair Trials' },
  { START => 21715, END => 21731, TEXT => "Australian Women's Teams",
    CORR => 'Australian National Women Teams' },
  { START => 21717, END => 21730, TEXT => "Australian Seniors Teams",
    CORR => 'Australian National Senior Teams' },
  { START => 21941, END => 22016, TEXT => 'Istanbul Teams',
    CORR => 'Istanbul Winter Teams' },
  { START => 21960, END => 21975, TEXT => 'GP of Poland',
    CORR => 'Grand Prix of Poland Pairs' },
  { START => 21973, END => 21016, TEXT => 'Istanbul Teams',
    CORR => 'Istanbul Winter Teams' },
  { START => 22117, END => 22135, TEXT => 'Maharashtra State Championship',
    CORR => 'Maharashtra State Pairs' },
  { START => 22228, END => 22252, TEXT => 'Zurich',
    CORR => 'Zurich Open Teams' },
  { START => 22390, END => 22404, 
    TEXT => 'Teams Tournament - Cracow Poland',
    CORR => 'Grand Prix of Poland Teams - Krakow' },
  { START => 22408, END => 22415, TEXT => 'Cracow Poland',
    CORR => 'Grand Prix of Poland Teams - Krakow' },
  { START => 22437, END => 22453, TEXT => 'Grand Prix of Poland',
    CORR => 'Grand Prix of Poland Pairs' },
  { START => 22522, END => 22532, 
    TEXT => 'Turkish 2012 Inter-Universities Bridge Champ_',
    CORR => 'Turkish Universities Championship' },
  { START => 22649, END => 22671, TEXT => 'S[eé]l[eé]ction Dame',
    CORR => "French Women Trials" },
  { START => 23249, END => 23280, TEXT => 'Romanian National Teams',
    CORR => 'Romanian League' },
  { START => 23345, END => 23360, 
    TEXT => 'Polish U-16 Championships - Pairs',
    CORR => 'Polish U16 Pairs' },
  { START => 23503, END => 23518, TEXT => 'Grand Prix of Poland',
    CORR => 'Grand Prix of Poland Pairs' },
  { START => 23594, END => 23598, TEXT => 'Grand Prix of Poland',
    CORR => 'Grand Prix of Poland Pairs' },
  { START => 23831, END => 23991, TEXT => 'Euro Teams',
    CORR => 'European National Championships' },
  { START => 23831, END => 23991, TEXT => 'Euro Team',
    CORR => 'European National Championships' },
  { START => 24125, END => 24134, TEXT => 'Grand Prix of Poland',
    CORR => 'Grand Prix of Poland Teams' },
  { START => 25295, END => 25371, TEXT => 'Pula',
    CORR => 'Pula Bridge Festival' },
  { START => 25391, END => 25410, TEXT => 'Nationale Interclub',
    CORR => 'French First Division' },
  { START => 25456, END => 25467, TEXT => 'Grand Prix of Poland',
    CORR => 'Grand Prix of Poland Pairs' },
  { START => 25936, END => 29983, 
    TEXT => 'All India National Inter\s*state & Juniors*\s+Championship',
    CORR => 'Indian Inter-State Teams' },
  { START => 25936, END => 29983, 
    TEXT => 'National Inter\s*state &\s+Juniors* Championship',
    CORR => 'Indian Inter-State Teams' },
  { START => 25970, END => 25989, TEXT => 'Gran Final Argentina',
    CORR => 'Argentinian Open Trials - Final' },
  { START => 26211, END => 26249, TEXT => 'Romanian National Teams',
    CORR => 'Romanian League' },
  { START => 26446, END => 26514, TEXT => 'Grand Prix of Poland',
    CORR => 'Grand Prix of Poland Pairs' },
  { START => 26563, END => 26616, TEXT => 'Winter\s+Nationals*',
    CORR => 'Indian Winter Nationals' },
  { START => 26753, END => 26759, TEXT => 'Summer Festival',
    CORR => 'Australian Summer Festival' },
  { START => 26849, END => 26903, TEXT => 'Lady Milne Trials',
    CORR => 'English Women Pair Trials' },
  { START => 27066, END => 27107, TEXT => 'Romanian National Teams',
    CORR => 'Romanian League' },
  { START => 27085, END => 27107, TEXT => 'Romanian National Championship',
    CORR => 'Romanian League' },
  { START => 27188, END => 27220, TEXT => 'Zurich Patton',
    CORR => 'Zurich Open Teams' },
  { START => 27188, END => 27220, TEXT => 'Zurich',
    CORR => 'Zurich Open Teams' },
  { START => 27303, END => 27307, 
    TEXT => 'Smart MAX Invitational Bridge Tournament',
    CORR => 'Indonesian Invitational Teams' },
  { START => 27419, END => 27436, TEXT => 'Grand Prix of Poland',
    CORR => 'Grand Prix of Poland Pairs' },
  { START => 27811, END => 27838, TEXT => 'Yeh Bros',
    CORR => 'Yeh Bros Cup' },
  { START => 28295, END => 28314, TEXT => 'Grand Prix of Poland',
    CORR => 'Grand Prix of Poland Pairs' },
  { START => 29034, END => 29045, TEXT => 'KO-R16',
    CORR => 'Rof16' },
  { START => 29073, END => 29083, TEXT => 'Open Pairs',
    CORR => 'European Open Pairs' },
  { START => 29185, END => 29191, TEXT => 'Grand Prix of Poland',
    CORR => 'Grand Prix of Poland Pairs' },
  { START => 29193, END => 29213, TEXT => 'Grand Prix of Poland',
    CORR => 'Grand Prix of Poland Teams' },
  { START => 29546, END => 29552, TEXT => 'Grand Prix of Poland',
    CORR => 'Grand Prix of Poland Pairs' },
  { START => 29562, END => 29604, TEXT => 'GP of Poland',
    CORR => 'Grand Prix of Poland Teams' },
  { START => 29631, END => 29633, TEXT => 'Equipos Libres',
    CORR => 'Argentinian Open teams' },
  { START => 29906, END => 29957, 
    TEXT => 'Inter\s*state & Junior Nationals',
    CORR => 'Indian Inter-State Teams' },
  { START => 30081, END => 30129, TEXT => 'Nationale Interclub',
    CORR => 'French First Division' },
  { START => 30147, END => 30160, TEXT => 'Pula',
    CORR => 'Pula Bridge Festival' },
  { START => 30474, END => 30555, TEXT => 'TNOT',
    CORR => 'World Transnational Open Teams' },
  { START => 30637, END => 30700, TEXT => 'Danmark - 1_division',
    CORR => 'Danish First Division' },
  { START => 30583, END => 30587, TEXT => 'Grand Prix of Poland - Teams',
    CORR => 'Grand Prix of Poland Teams' },
  { START => 30617, END => 30654, TEXT => 'Championship of Poland - Patton',
    CORR => 'Polish Patton Teams' },
  { START => 30673, END => 30704, TEXT => 'Grand Prix of Poland',
    CORR => 'Grand Prix of Poland Pairs' },
  { START => 30719, END => 30774, TEXT => 'Torneo di Roma - Angelini',
    CORR => 'Torneo di Roma' },
  { START => 30861, END => 30880, TEXT => 'Cavendish',
    CORR => 'Cavendish Teams' },
  { START => 31259, END => 31335, TEXT => 'Sélection Open',
    CORR => 'French Open Trials' },
  { START => 31273, END => 31748, TEXT => 'Winter Nationals',
    CORR => 'Indian Winter Nationals' },
  { START => 31904, END => 31937, TEXT => 'Denmark 1_Division 2013-2014',
    CORR => 'Denmark 1_Division' },
  { START => 31097, END => 31127, TEXT => 'Romanian National Teams',
    CORR => 'Romanian League' },
  { START => 31268, END => 31338, TEXT => "Champions' Cup",
    CORR => "European Champions' Cup" },
  { START => 31409, END => 31416, TEXT => 'Grand Prix of Poland',
    CORR => 'Grand Prix of Poland Pairs' },
  { START => 31418, END => 31435, TEXT => 'R16',
    CORR => 'Rof16' },
  { START => 31444, END => 31454, TEXT => 'R8',
    CORR => 'QF' },
  { START => 31521, END => 31604, TEXT => 'Grand Prix of Poland',
    CORR => 'Grand Prix of Poland Pairs' },
  { START => 31538, END => 31569, TEXT => 'SFB',
    CORR => 'SF' },
  { START => 31774, END => 31815, TEXT => 'USBC',
    CORR => 'United States Youth Bridge Championship' },
  { START => 32082, END => 32122, TEXT => 'Lalit Mohanka',
    CORR => 'Lalit Mohanka Memorial' },
  { START => 32120, END => 32134, TEXT => 'Grand Prix Polski',
    CORR => 'Grand Prix of Poland Pairs' },
  { START => 32071, END => 32131, TEXT => 'Lady Milne Trials',
    CORR => 'English Women Pair Trials' },
  { START => 32306, END => 32325, TEXT => 'Romanian National Teams',
    CORR => 'Romanian League' },
  { START => 32309, END => 32327, TEXT => 'Seniors Trials',
    CORR => 'Polish Senior Trials' },
  { START => 32743, END => 32746, TEXT => 'pro memoriam',
    CORR => '' },
  { START => 32882, END => 32908, TEXT => 'Australian Seniors Trials',
    CORR => 'Australian Senior Pairs' },
  { START => 32882, END => 32908, TEXT => 'Australian Seniors Trials',
    CORR => 'Australian Senior Teams' },
  { START => 32951, END => 33100, TEXT => 'Team Championship China',
    CORR => 'Chinese Women Teams' },
  { START => 32956, END => 33015, 
    TEXT => 'International Festival - Dobrich',
    CORR => 'Dobrich Bridge Festival - Teams' },
  { START => 33067, END => 33142, TEXT => 'S[eé]lection Open',
    CORR => 'French Open Trials' },
  { START => 33101, END => 33120, TEXT => 'Senior World Cup',
    CORR => 'Friendly Match - Budapest' },
  { START => 33426, END => 33457, TEXT => 'Sweden vs Poland',
    CORR => 'Friendly Match' },
  { START => 33848, END => 33937, TEXT => 'Norwegian [Tt]eam [Cc]hampionship',
    CORR => 'Norwegian Club Teams' },
  { START => 34365, END => 34372, TEXT => 'Grand Prix of Poland',
    CORR => 'Grand Prix of Poland Pairs' },
  { START => 34444, END => 34526, TEXT => 'ANC Interstate Teams',
    CORR => 'Australian ANC Championships' },
  { START => 34486, END => 34495, TEXT => 'Youngsters', CORR => 'U21' },
  { START => 34548, END => 34554, TEXT => 'Grand Prix of Poland', 
    CORR => 'Grand Prix of Poland Pairs' },
  { START => 35213, END => 35234, TEXT => 'Cavendish',
    CORR => 'Cavendish Teams' },
  { START => 35271, END => 35283, TEXT => "Monaco's Cavendish",
    CORR => 'Cavendish Teams - Monaco' },
  { START => 35315, END => 35394, TEXT => 'Pula',
    CORR => 'Pula Bridge Festival' },
  { START => 35459, END => 35512, 
    TEXT => 'Finale Nationale - Interclubs Division 1',
    CORR => 'French First Division' },
  { START => 35487, END => 35547, TEXT => 'Inter Province',
    CORR => 'Indonesian Inter-Province Championship' },
  { START => 35548, END => 35630, TEXT => 'Inter Club',
    CORR => 'Indonesian Inter-Club Championship' },
  { START => 35616, END => 35665, TEXT => 'Governor Cup',
    CORR => 'Indonesian Open Teams' },
  { START => 35703, END => 35709, TEXT => 'Championship of Poland - Patton',
    CORR => 'Polish Patton Teams' },
  { START => 35734, END => 35746, TEXT => 'Grand Prix of Poland', 
    CORR => 'Grand Prix of Poland Pairs' },
  { START => 35802, END => 35869, TEXT => 'Danmark 1_ division 2014-15',
    CORR => 'Danmark 1_ division' },
  { START => 36610, END => 36647, TEXT => 'Romanian National Teams',
    CORR => 'Romanian League' },
  { START => 36694, END => 36722, TEXT => 'Swiss Open Championship',
    CORR => 'Swiss Club Championship' },
  { START => 36769, END => 36809, 
    TEXT => 'Indonesian 16th University Championships',
    CORR => '16th Indonesian University Championship' },
  { START => 36820, END => 36977, 
    TEXT => 'Indonesian 11th Students Championships',
    CORR => '11th Indonesian Student Championship' },
  { START => 37010, END => 37067, TEXT => 'Winter\s+Nationals*',
    CORR => 'Indian Winter Nationals' },
  { START => 37033, END => 37069, TEXT => 'Grand Prix of Poland', 
    CORR => 'Grand Prix of Poland Pairs' },
  { START => 37086, END => 37096, 
    TEXT => '2015 Chinese Taipei Open Team Trials', 
    CORR => 'Chinese Taipei Open Trials' },
  { START => 37354, END => 37437, TEXT => 'Lady Milne Trials',
    CORR => 'English Women Pair Trials' },
  { START => 37442, END => 37466, TEXT => 'Bulgarian Group A',
    CORR => 'Bulgarian Open Teams - Group A' },
  { START => 37599, END => 37630, TEXT => 'Romanian National Teams',
    CORR => 'Romanian League' },
  { START => 37612, END => 37621, TEXT => 'Grand Prix of Poland', 
    CORR => 'Grand Prix of Poland Pairs' },
  { START => 37652, END => 37712, TEXT => 'Lalit Mohanka',
    CORR => 'Lalit Mohanka Memorial' },
  { START => 37680, END => 37707, TEXT => 'Denmark Team Training',
    CORR => 'Training Match' },
  { START => 37718, END => 37724, TEXT => 'Denmark Women Team Training',
    CORR => 'Training Match' },
  { START => 38031, END => 38033, 
    TEXT => 'Gran Final Damas Clasificatoria Sudamericano', 
    CORR => 'South American Women Trials - Final' },
  { START => 38279, END => 38338, 
    TEXT => 'International Bridge Festival\s+- Dobrich',
    CORR => 'Dobrich Bridge Festival - Teams' },
  { START => 38376, END => 38436, TEXT => 'Swedish Trials', 
    CORR => 'Swedish Open Trials' },
  { START => 38543, END => 38585, 
    TEXT => 'International Festival - Plovdiv',
    CORR => 'Plovdiv Bridge Festival' },
  { START => 38594, END => 38652, TEXT => 'Turkish Open Championship', 
    CORR => 'Turkish Open Teams Championship' },
  { START => 38594, END => 38652, TEXT => 'Turkish Open Championships', 
    CORR => 'Turkish Open Teams Championship' },
  { START => 38743, END => 38745, TEXT => 'SABC', 
    CORR => 'South American Open Pairs' },
  { START => 38762, END => 38986, TEXT => 'SABC', 
    CORR => 'South American Bridge Championship' },
  { START => 39162, END => 39309, TEXT => 'I National Bridge Tournament', 
    CORR => '1st Asenovgrad Open Teams' },
  { START => 39297, END => 39316, TEXT => 'Swiss Open', 
    CORR => 'Swiss Open Teams' },
  { START => 39501, END => 39525, TEXT => 'Lozenets Tournament Teams', 
    CORR => 'Lozenets Bridge Festival - Open Teams' },
  { START => 39501, END => 39525, TEXT => 'Lozenets Team Tournament', 
    CORR => 'Lozenets Bridge Festival - Open Teams' },
  { START => 40067, END => 40184, TEXT => 'EYBC', CORR => 'EYTC' },
  { START => 40067, END => 40184, TEXT => 'Juniors Teams', 
    CORR => 'U26 Teams' },
  { START => 40067, END => 40184, TEXT => 'Girls Teams', 
    CORR => 'U26 Women Teams' },
  { START => 40067, END => 40184, TEXT => 'Youngsters Teams', 
    CORR => 'U21 Teams' },
  { START => 40212, END => 40241, 
    TEXT => 'Avia Inter-City Championship', 
    CORR => 'Chinese Intercity Teams' },
  { START => 40702, END => 40802, TEXT => 'Inter State Championship', 
    CORR => 'Indian Inter-State Teams' },
  { START => 40702, END => 40802, TEXT => 'Inter State Nationals', 
    CORR => 'Indian Inter-State Teams' },
  { START => 40702, END => 40802, TEXT => 'Interstate Nationals', 
    CORR => 'Indian Inter-State Teams' },
  { START => 40887, END => 40920, TEXT => 'Camrose Trials CBAI', 
    CORR => 'Irish Open Trials' },
  { START => 40926, END => 40955, TEXT => 'Selection Open', 
    CORR => 'French Open Trials' },
  { START => 40982, END => 40998, TEXT => 'Grand Prix of Poland', 
    CORR => 'Grand Prix of Poland Pairs' },
  { START => 41438, END => 41463, TEXT => 'Cavendish Monaco',
    CORR => 'Cavendish Teams - Monaco' },
  { START => 41719, END => 41744, TEXT => 'National Student Championship', 
    CORR => 'Indonesian Student Championship' },
  { START => 41946, END => 42033, TEXT => 'Winter Nationals*',
    CORR => 'Indian Winter Nationals' },
  { START => 41967, END => 42044, 
    TEXT => 'Campeonato Nacional Equipas Open',
    CORR => 'Portuguese Open Teams' },
  { START => 41967, END => 42044, 
    TEXT => 'Campeonato Nacional\s+de Equipas Open',
    CORR => 'Portuguese Open Teams' },
  { START => 42091, END => 42118, TEXT => 'R16',
    CORR => 'Rof16' },
  { START => 42260, END => 42264, TEXT => 'Swiss Championship',
    CORR => 'Swiss Club Championship' },
  { START => 42370, END => 42420, TEXT => 'Grand Prix of Poland',
    CORR => 'Grand Prix of Poland Pairs' },
  { START => 42550, END => 42575, TEXT => 'Junior USBC Rona',
    CORR => 'United States Youth Bridge Championship Women U26' },
  { START => 42541, END => 42592, TEXT => 'Junior USBC U21',
    CORR => 'United States Youth Bridge Championship U21' },
  { START => 42549, END => 42592, TEXT => 'Junior USBC U26',
    CORR => 'United States Youth Bridge Championship U26' },
  { START => 42937, END => 43084, 
    TEXT => 'Indonesian U21 Selection', 
    CORR => 'Indonesian U21 Pair Trials' },
  { START => 42937, END => 43084, 
    TEXT => 'Indonesian U26 Selection', 
    CORR => 'Indonesian U26 Pair Trials' },
  { START => 43070, END => 43154, TEXT => 'Bulgaria Group A', 
    CORR => 'Bulgarian Open Teams - Group A' },
  { START => 43103, END => 43135, TEXT => 'EBU Teltscher Trophy Trials', 
    CORR => 'English Senior Trials' },
  { START => 43157, END => 43179, TEXT => 'Izmir Open Teams Championships', 
    CORR => 'Izmir Winter Teams Cup' },
  { START => 43195, END => 43235, TEXT => 'Open Playoff', 
    CORR => 'Australian Open Team Trials' },
  { START => 43288, END => 43374, 
    TEXT => 'Romanian National Teams* Championship',
    CORR => 'Romanian League' },
  { START => 43307, END => 43341, TEXT => 'Grand Prix of Poland', 
    CORR => 'Grand Prix of Poland Pairs' },
  { START => 43433, END => 43457, TEXT => 'Czech Bridge Championships*', 
    CORR => 'Czech First League' },
  { START => 43470, END => 43479, TEXT => 'Czech Team Championships*', 
    CORR => 'Czech First League' },
  { START => 43611, END => 43669, 
    TEXT => 'Indonesian Women National Selection', 
    CORR => 'Indonesian Women Pair Trials' },
  { START => 43671, END => 43753, 
    TEXT => 'Indonesian Men National Selection', 
    CORR => 'Indonesian Open Pair Trials' },
  { START => 43890, END => 43944, 
    TEXT => 'International Teams Festival - Lisbon', 
    CORR => 'Lisbon International Festival - Teams' },
  { START => 44286, END => 44315, TEXT => 'Swiss Open - Swiss Teams', 
    CORR => 'Swiss Open Teams' },
  { START => 44633, END => 44778, 
    TEXT => 'National Indonesian Championship\s*\(Inter-Club\)*', 
    CORR => 'Indonesian Inter-Club Championship' },
  { START => 44877, END => 45110, TEXT => 'SABC', 
    CORR => 'South American Bridge Championship' },
  { START => 45792, END => 45816, TEXT => 'Zagreb - Rijeka', 
    CORR => 'Zagreb' },
  { START => 46016, END => 46058, TEXT => 'USBC', CORR => 'NABC' },
  { START => 46400, END => 46478, 
    TEXT => 'Turkish Club Teams Championship - Aegean Playoffs', 
    CORR => 'Aegean Open Teams' },

  { START => 46880, END => 46920, 
    TEXT => '^WT[89]-', CORR => '' },
  { START => 46923, END => 47109, 
    TEXT => 'PON', CORR => 'Indonesian National Sports Week' },
  { START => 47008, END => 47032, 
    TEXT => '^Patton', CORR => 'Polish Patton Teams' },
  { START => 47034, END => 47083, 
    TEXT => 'Nationale Interclub', CORR => 'French First Division' },
  { START => 47035, END => 47089, 
    TEXT => 'Pokalturneringe*n*', CORR => 'Danish Cup' },
  { START => 47195, END => 47267, 
    TEXT => 'Mahasiswa', CORR => 'U31' },
  { START => 47247, END => 47270, 
    TEXT => 'Thailand Championship', 
    CORR => 'Thailand National Games' },
  { START => 47385, END => 47395, 
    TEXT => 'Pan China vs PD Times', CORR => 'China Practice' },
  { START => 47458, END => 47511, 
    TEXT => '3 National Tournament Panagyurishte',
    CORR => '3rd Panagyurishte Open Teams' },
  { START => 47560, END => 47659, 
    TEXT => 'KEJURPROP XV', CORR => '15th KEJURPROP' },
  { START => 47697, END => 47699, 
    TEXT => 'Italy Mixed Final Pairs', 
    CORR => 'Italian Mixed Pairs final' },
  { START => 47772, END => 47824, 
    TEXT => 'Inter State', 
    CORR => 'Indian Inter-State Teams' },
  { START => 47803, END => 47828, 
    TEXT => 'XV-th National Tournament Sliven',
    CORR => '15th Sliven Open Teams' },
  { START => 47972, END => 48050, 
    TEXT => 'Indonesian 18th University Championships*',
    CORR => '18th Indonesian University Teams' },
  { START => 48081, END => 48105, 
    TEXT => 'Indonesian Youth Championships', 
    CORR => 'Indonesian U26 Teams' },
  { START => 48143, END => 48185, 
    TEXT => 'National Masters', CORR => 'Indian Masters Open Teams' },
  { START => 48211, END => 48517, 
    TEXT => 'Danmark - Kvalifikation til CBI', 
    CORR => 'Danish Open Pairs Trials' },
  { START => 48287, END => 48327, 
    TEXT => 'Swiss Championships 2016-2017 A Serie Finale*', 
    CORR => 'Swiss Club Championship - Final' },
  { START => 48458, END => 48512, 
    TEXT => 'Grand Prix of Poland', CORR => 'Grand Prix of Poland Pairs' },
  { START => 48529, END => 48658, 
    TEXT => 'Winter Nationals', CORR => 'Indian Winter Nationals' },
  { START => 48538, END => 48644, 
    TEXT => 'Polish Team Championships', 
    CORR => 'Polish Open Teams' },
  { START => 48677, END => 48679, 
    TEXT => 'Juveniles Chile', CORR => 'Chilean Junior Teams' },
  { START => 48857, END => 48888, 
    TEXT => 'Copenhagen Bridge Invitational', 
    CORR => 'Copenhagen Invitational Pairs' },
  { START => 49103, END => 49153, 
    TEXT => 'Istanbul Open Teams', CORR => 'Istanbul Winter Open Teams' },
  { START => 49106, END => 49154, 
    TEXT => 'Ankara Open Teams', CORR => 'Ankara Winter Teams' },
  { START => 49159, END => 49183, 
    TEXT => 'Cavendish Monaco', CORR => 'Cavendish Teams - Monaco' },
  { START => 49185, END => 49228, TEXT => '^T-[ABCDE]1 ', CORR => '' },
  { START => 49185, END => 49244, 
    TEXT => 'Cavendish Monaco', CORR => 'Cavendish Open Pairs - Monaco' },
  { START => 49188, END => 49228, 
    TEXT => 'T-D1 ', CORR => '' },
  { START => 49286, END => 49376, 
    TEXT => 'Turkey Open Teams', CORR => 'Turkish Open Teams' },
  { START => 49381, END => 49389, 
    TEXT => 'Tournament of Twin Towns', CORR => 'Twin Towns Elblag' },
  { START => 49395, END => 49479, 
    TEXT => 'National Championship Romania', CORR => 'Romanian League' },
  { START => 49410, END => 49509, TEXT => '^M\d ', CORR => '' },
  { START => 49468, END => 49501, 
    TEXT => 'Swiss Open 2017 - Teams', CORR => 'Swiss Open Teams 2017' },
  { START => 49533, END => 49553, 
    TEXT => 'Norwegian Championship *Women Teams', 
    CORR => 'Norwegian Women Teams' },
  { START => 49680, END => 49704, 
    TEXT => 'FINALS* 1_16', CORR => 'Rof16' },
  { START => 49680, END => 49704, 
    TEXT => '1_16', CORR => 'Rof16' },
  { START => 49807, END => 49834, 
    TEXT => 'Slutspil', CORR => 'Danish First Division' },
  { START => 49866, END => 50023, 
    TEXT => 'Sélection Open', CORR => 'French Open Trials' },
  { START => 49975, END => 50058, 
    TEXT => 'Fina³ teamów Open', CORR => 'Polish Open Teams' },
  { START => 50255, END => 50365, 
    TEXT => 'Bulgarian Team Championship', 
    CORR => 'Bulgarian Open Teams' },
  { START => 50315, END => 50362, 
    TEXT => 'France Pologne', CORR => 'France Friendly' },
  { START => 50344, END => 50402, 
    TEXT => 'Italian Teams Championships', 
    CORR => 'Italian Open Teams' },
  { START => 50651, END => 50869, 
    TEXT => 'ABF Zonals', CORR => 'African Zonal Championships' },
  { START => 50692, END => 50722, TEXT => '1_16', CORR => 'Rof16' },
  { START => 50755, END => 50772, TEXT => '1_8', CORR => 'QF' },
  { START => 50798, END => 50829, TEXT => '1_4', CORR => 'SF' },
  { START => 50836, END => 50904, 
    TEXT => 'France Italie', CORR => 'France Friendly' },
  { START => 51028, END => 51238, 
    TEXT => 'BK S:t Erik Mästarserien Final', 
    CORR => 'S:t Erik Championship Series - Final' },
  { START => 51124, END => 51179, 
    TEXT => 'Swedish[_ -]Danish Juniors* Teams*', 
    CORR => 'Sweden Friendly - Juniors' },
  { START => 51232, END => 51288, 
    TEXT => 'Senior USA2', CORR => 'US Senior Trials' },
  { START => 51554, END => 51630, 
    TEXT => 'XVIII-th Bridge', CORR => '18th Bridge' },
  { START => 51741, END => 51760, 
    TEXT => 'Grand Prix of Poland', CORR => 'Grand Prix of Poland Teams' },
  { START => 51912, END => 51938,
    TEXT => 'Thailand National Team',
    CORR => 'Thailand National Games' },
  { START => 51984, END => 52013,
    TEXT => '^[AB] - Q 11th YEH BROS CUP',
    CORR => '11th YEH BROS CUP - Qualifying' },
  { START => 52017, END => 52020,
    TEXT => '^[AB] - KO1 11th YEH BROS CUP',
    CORR => '11th YEH BROS CUP - KO1' },
  { START => 52021, END => 52024,
    TEXT => '^[AB] - KO2 11th YEH BROS CUP',
    CORR => '11th YEH BROS CUP - KO2' },
  { START => 52031, END => 52032,
    TEXT => 'KO3 11th YEH BROS CUP', CORR => '11th YEH BROS CUP - KO3' },
  { START => 52037, END => 52047,
    TEXT => 'KO4 11th YEH BROS CUP', CORR => '11th YEH BROS CUP - KO4' },
  { START => 52048, END => 52051,
    TEXT => 'F 11th YEH BROS CUP', CORR => '11th YEH BROS CUP - Final' },
  { START => 52258, END => 52417,
    TEXT => 'Indonesian National Champh*ionships*', 
    CORR => 'Indonesian National Games' },
  { START => 52564, END => 52577, TEXT => ' 1_8$', CORR => ' QF' },
  { START => 52592, END => 52602, 
    TEXT => 'Mautern Teams', CORR => 'Mautern Open Teams' },
  { START => 52671, END => 53047, TEXT => '^FB[567]-', CORR => '' },
  { START => 52933, END => 52975, TEXT => '^BB(\d\d)-', CORR => '' },
  { START => 53067, END => 53109, 
    TEXT => 'Inter - State Nationals', 
    CORR => 'Indian Inter-State Teams' },
  { START => 53105, END => 53126, 
    TEXT => 'Pokalturneringe*n*', CORR => 'Danish Cup' },
  { START => 53289, END => 53327, 
    TEXT => 'Finale Nationale Interclubs D1A', 
    CORR => 'French First Division - Final' },
  { START => 53308, END => 53324, 
    TEXT => 'VILNIUS CUP GRAND PRIX of POLAND', CORR => 'Vilnius Cup' },
  { START => 53377, END => 53400, 
    TEXT => 'Pokalsemifinale', CORR => 'Danish Cup - SF' },
  { START => 53409, END => 53432, 
    TEXT => 'Dansk Pokalfinale', CORR => 'Danish Cup - Final' },
  { START => 53470, END => 53599, 
    TEXT => 'Commonwealth Games Selection Trials', 
    CORR => 'Indian Open Trials' },
  { START => 53626, END => 53635, 
    TEXT => 'Norway-Poland-Netherlands', CORR => 'Netherlands Friendly' },
  { START => 53677, END => 53699, 
    TEXT => 'IV Bridge Tournament - Panagyurishte',
    CORR => '4th Panagyurishte Open Teams' },
  { START => 53743, END => 53811, 
    TEXT => 'XVI National Tournament Sliven',
    CORR => '16th Sliven Open Teams' },
  { START => 53934, END => 53957, 
    TEXT => 'Tolani National Masters', 
    CORR => 'Indian Masters Open Teams' },
  { START => 54051, END => 54127, 
    TEXT => 'Thailand Bridge Championships', 
    CORR => 'Thailand National Games' },
  { START => 54238, END => 54286, 
    TEXT => 'Intermediate', CORR => '' },
  { START => 54574, END => 54596, TEXT => 'T. S2', CORR => '' },
  { START => 54625, END => 54724, 
    TEXT => 'Seniors Chile', CORR => 'Chilean Senior Teams' },
  { START => 54665, END => 54717, 
    TEXT => 'Grand Prix of Poland', CORR => 'Grand Prix of Poland Teams' },
  { START => 54674, END => 54686, 
    TEXT => 'State Open Teams', CORR => 'New South Wales Open Teams' },
  { START => 54750, END => 54834, 
    TEXT => '^OT[1-6]-', CORR => '' },
  { START => 54756, END => 54829, 
    TEXT => '^WT[56]-', CORR => '' },
  { START => 54846, END => 54903, 
    TEXT => 'Grand Prix of Poland', CORR => 'Grand Prix of Poland Pairs' },
  { START => 54849, END => 54906, 
    TEXT => 'CN ESPAÑA', CORR => 'Spanish Open Teams' },
  { START => 54917, END => 54943, 
    TEXT => 'Winter Nationals', CORR => 'Indian Winter Nationals' },
  { START => 55037, END => 55126, TEXT => ' Wk1$', CORR => '' },
  { START => 55139, END => 55190, 
    TEXT => 'European Open Trials', CORR => 'English Open Trials' },
  { START => 55158, END => 55245, 
    TEXT => 'CTCBA senior', CORR => 'CTCBA Senior Team' },
  { START => 55189, END => 55217, 
    TEXT => 'Halve Finale MK', CORR => 'Dutch Meesterklasse - SF' },
  { START => 55268, END => 55272, 
    TEXT => 'European Trials', CORR => 'EBU European Trials' },
  { START => 55517, END => 55535, 
    TEXT => 'Selection Open', CORR => 'French Open Trials' },
  { START => 55562, END => 55632, 
    TEXT => 'Turkiye 2018 Super Kupa', CORR => 'Turkiye Super Kupa 2018' },
  { START => 55670, END => 55718, 
    TEXT => 'Polish Grand Prix', CORR => 'Grand Prix of Poland Teams' },
  { START => 55882, END => 55919, 
    TEXT => 'SEL_ FEMM_', CORR => 'Italian Women Team Trials' },
  { START => 55925, END => 55935, 
    TEXT => 'Tournament of Twin Towns', CORR => 'Twin Towns Elblag' },
  { START => 55938, END => 55951, 
    TEXT => 'Championship of Poland', CORR => 'Polish Open Teams' },
  { START => 56052, END => 56056, 
    TEXT => 'Selection Senior', CORR => 'French Senior Trials' },
  { START => 56058, END => 56098, 
    TEXT => 'Sel_ Naz_ Femm_', CORR => 'Italian Women Team Trials' },
  { START => 56203, END => 56214, 
    TEXT => 'Swiss Open - MP Pairs', CORR => 'Swiss Open Pairs' },
  { START => 56227, END => 56240, 
    TEXT => 'Swiss Open 2018 - Teams', CORR => 'Swiss Open Teams 2018' },
  { START => 56394, END => 56468, 
    TEXT => 'Societario', CORR => 'Italian Club Championship' },
  { START => 56430, END => 56452, 
    TEXT => 'Slutspillet', CORR => 'Danish First Division' },
  { START => 56449, END => 56469, 
    TEXT => 'Estonian Teams Championship', 
    CORR => 'Estonian Open Teams' },
  { START => 56529, END => 56556, 
    TEXT => 'Greek Championship Teams', CORR => 'Greek Open Teams' },
  { START => 56656, END => 56683, 
    TEXT => 'Shree Cement', CORR => 'All India Shree Cement' },
  { START => 56690, END => 56692, 
    TEXT => 'Campeonato Nacional Equipos Libres', 
    CORR => 'Argentinian Open Teams' },
  { START => 56720, END => 56758, 
    TEXT => 'Bulgarian A Group', CORR => 'Bulgarian Open Teams' },
  { START => 56747, END => 56781, 
    TEXT => 'Italian Teams* Championships', 
    CORR => 'Italian Open Teams' },
  { START => 56931, END => 56975, 
    TEXT => 'Turkey-Bulgaria National Teams Practice -SENIOR',
    CORR => 'Turkey Practice - Seniors' },
  { START => 57046, END => 57089, 
    TEXT => 'France _ Italie', CORR => 'France Friendly' },
  { START => 57310, END => 57369, 
    TEXT => 'Hakan Peksen Marmara Kuluplerarasi Final', 
    CORR => 'Hakan Peksen Open Teams - Marmara - Final' },
  { START => 57696, END => 57730, 
    TEXT => 'XXXVI-th International', CORR => '36th International' },
  { START => 57779, END => 57806, 
    TEXT => 'Finnish IMP Championship', CORR => 'Finnish Open IMP Pairs' },
  { START => 57845, END => 57863, 
    TEXT => 'Falcon', CORR => 'Falcon Cup' },
  { START => 57891, END => 57939, 
    TEXT => 'Hong *Kong Intercity', 
    CORR => 'Hong Kong Inter-City Open Teams' },
  { START => 57898, END => 57926, 
    TEXT => 'HK Inter-*city', 
    CORR => 'Hong Kong Inter-City Open Teams' },
  { START => 58024, END => 58031, 
    TEXT => 'Turkey Youth Teams Championship', 
    CORR => 'Turkish U26 Teams' },
  { START => 58135, END => 58163, 
    TEXT => '\d_2018 Spingold', CORR => '2018 Spingold' },
  { START => 58200, END => 58205, 
    TEXT => 'Shree Cement Corporate', 
    CORR => 'Shree Cement - All India Corporate Invitational Pairs' },
  { START => 58293, END => 58326, 
    TEXT => 'Polish Team Championships', 
    CORR => 'Polish Open Teams' },
  { START => 58639, END => 58683, 
    TEXT => 'INTERSTATE NATIONAL BRIDGE CHAMPIONSHIP 2018 MYS', 
    CORR => '2018 Indian Inter-State Teams - Mysore' },
  { START => 58728, END => 58789, 
    TEXT => 'Italy Cup Over 61', CORR => 'Italian O61 Cup' },
  { START => 58769, END => 58801, 
    TEXT => '^Interclub$', CORR => 'French First Division' },
  { START => 58770, END => 58806, 
    TEXT => 'English Premier League Div 1', 
    CORR => 'English Premier League' },
  { START => 58811, END => 58860, 
    TEXT => 'NM Par', CORR => 'Norwegian Open Pairs -' },
  { START => 58662, END => 58681, 
    TEXT => 'XI°', CORR => '11th' },
  { START => 59235, END => 59247, 
    TEXT => 'Australia_New Zealand Youth Test',
    CORR => 'Australia Friendly' },
  { START => 59249, END => 59382, 
    TEXT => 'PORDA XIII West Java 2018',
    CORR => '13th PORDA West Java 2018' },
  { START => 59478, END => 59509, 
    TEXT => 'V-th Bridge Festival Panagyurishte',
    CORR => '5th Panagyurishte Open Teams' },
  { START => 59704, END => 59707, 
    TEXT => 'Premier League', CORR => 'EBU Premier League' },
  { START => 59759, END => 59767, 
    TEXT => 'Hainan Nanshan 2018 China Hainan International Br', 
    CORR => '2018 Nanshan Open Teams Cup' },
  { START => 59797, END => 59906, 
    TEXT => '2019OPO', CORR => '2019 Australian Open Trials' },
  { START => 59921, END => 59965, 
    TEXT => 'Kaylaka Pleven', CORR => 'Kaylaka Open Teams' },
  { START => 59998, END => 60043, 
    TEXT => 'Danmark - 1_division', CORR => 'Danish First Division' },
  { START => 60107, END => 60137, 
    TEXT => 'The National Team Challenge 2018-2019', 
    CORR => 'China Practice' },
  { START => 60183, END => 60263, TEXT => '^China 4th ', CORR => '4th ' },
  { START => 60183, END => 60263, TEXT => 'SanQing', CORR => 'Sanqing' },
  { START => 60328, END => 60365, 
    TEXT => 'I 2018 Reisinger FINAL 1 or 2', 
    CORR => '2018 Reisinger - FINAL - Session 1 of 2' },
  { START => 60447, END => 60818, 
    TEXT => 'Mersin Winter', CORR => 'Mersin Winter Open Teams' },
  { START => 60457, END => 60567, 
    TEXT => 'Grand Prix of Poland', CORR => 'Grand Prix of Poland Teams' },
  { START => 60480, END => 60706, 
    TEXT => '2019WSPO', CORR => '2019 Australian Playoffs' },
  { START => 60484, END => 60756, 
    TEXT => 'Indonesia 56th National *Championship', 
    CORR => '56th Indonesian National Championship Week' },
  { START => 60759, END => 60799, 
    TEXT => 'Equipos España', CORR => 'Spanish Open Teams' },
  { START => 60786, END => 60789, 
    TEXT => 'State Teams Final', 
    CORR => 'John Arkinstall State Teams Final' },
  { START => 60962, END => 61020, 
    TEXT => '46th University Games 2019', 
    CORR => '46th Thailand University Games 2019' },
  { START => 61030, END => 61071, 
    TEXT => 'Thailand 46th University Games 2019', 
    CORR => '46th Thailand University Games 2019' },
  { START => 61061, END => 61116, 
    TEXT => 'Turkey Wom.n Team Championship', 
    CORR => 'Turkish Women Teams' },
  { START => 61129, END => 61170, 
    TEXT => 'Istanbul Open Teams Championship', 
    CORR => 'Istanbul Winter Open Teams' },
  { START => 61221, END => 61253, 
    TEXT => 'Mixed Teams', CORR => 'Australian Mixed Teams' },
  { START => 61270, END => 61294, 
    TEXT => 'Lady Milne Final Trials', 
    CORR => 'Lady Milne Trials - Final' },
  { START => 61291, END => 61331, 
    TEXT => 'BBO.-2019Cavendish', CORR => 'Cavendish Teams - Monaco' },
  { START => 61334, END => 61410, 
    TEXT => 'T-.+ 2019Cavendish', 
    CORR => 'Cavendish Open Pairs - Monaco' },
  { START => 61431, END => 61439, 
    TEXT => 'Finnish team trials \(W\)', 
    CORR => 'Finnish Women Trials' },
  { START => 61446, END => 61474, 
    TEXT => 'S.lection open', CORR => 'French Open Trials' },
  { START => 61560, END => 61702, 
    TEXT => '7th Pan Arab', 
    CORR => '11th Arab Nations Championship' },
  { START => 61801, END => 68087, 
    TEXT => 'Twin Towns', CORR => 'Twin Towns Elblag' },
  { START => 61878, END => 61935, 
    TEXT => 'Danmark - Landshold ', CORR => 'Danish Open Team Trials ' },
  { START => 61907, END => 61927, 
    TEXT => 'Thailand National Selection 2019', 
    CORR => 'Thailand Open Team Trials 2019' },
  { START => 62187, END => 62191, 
    TEXT => 'APBF Youth Teams Championships*', 
    CORR => 'APBF Youth Championships' },
  { START => 62208, END => 62307, 
    TEXT => 'GPT of Poland - 4th Memory of Krzysztof Bader', 
    CORR => '4th Memory of Krzysztof Bader - GPT of Poland' },
  { START => 62482, END => 62505, 
    TEXT => 'Junior NM', CORR => 'Nordic Junior Teams' },
  { START => 62487, END => 62538, 
    TEXT => "Netherlands - England at 't Onstein tbl 2 ", 
    CORR => "Netherlands Friendly - 't Onstein" },
  { START => 62488, END => 62536, 
    TEXT => "Netherlands - England at 't Onstein", 
    CORR => "Netherlands Friendly - 't Onstein" },
  { START => 62513, END => 62520, 
    TEXT => 'Nordiske Mesterskaber Junior', 
    CORR => 'Nordic Junior Teams' },
  { START => 62630, END => 62830, 
    TEXT => 'Italian Teams Championships', CORR => 'Italian Open Teams' },
  { START => 62657, END => 62742, 
    TEXT => 'Open Turnamen FTBC University of TanjungPura', 
    CORR => 'FTBC Tanjungpura University' },
  { START => 62696, END => 62827, 
    TEXT => '^Buffett Cup', CORR => 'Buffett Individual' },
  { START => 62754, END => 62882, 
    TEXT => 'France *- *Sweden', CORR => 'France Friendly' },
  { START => 62754, END => 62857, 
    TEXT => 'Danmark - Slutspil', CORR => 'Danish First Division' },
  { START => 62904, END => 62916, 
    TEXT => 'Polish Pair Championship', CORR => 'Polish Open Pairs' },
  { START => 62995, END => 63033, 
    TEXT => 'Canadian Open Team', 
    CORR => 'Canadian National Teams Championship' },
  { START => 63000, END => 63059, 
    TEXT => 'China National Championships', 
    CORR => 'Chinese Open Teams' },
  { START => 63028, END => 63037, 
    TEXT => 'Canadian Senior Team', 
    CORR => 'Canadian Seniors Teams Championship' },
  { START => 63076, END => 63127, TEXT => '^[A-H] ', CORR => '' },
  { START => 63297, END => 63407, 
    TEXT => '^BBW[1-9] - ', CORR => '' },
  { START => 63326, END => 63472, 
    TEXT => "Netherlands - Israel at 't Onstein tbl 2", 
    CORR => "Netherlands Friendly - 't Onstein" },
  { START => 63330, END => 63469, 
    TEXT => "Netherlands - Israel at 't Onstein", 
    CORR => "Netherlands Friendly - 't Onstein" },
  { START => 64237, END => 64323, 
    TEXT => '20th BFAME', CORR => '20th BFAME Championship' },
  { START => 64339, END => 64448, 
    TEXT => 'league A club\(second station\)', 
    CORR => 'Chinese First League' },
  { START => 64930, END => 64934, 
    TEXT => 'Polish Team Championships', 
    CORR => 'Polish Open Teams' },
  { START => 65005, END => 65019, 
    TEXT => 'XLIII-th International Festival - Varna', 
    CORR => '43rd Varna Bridge Festival' },
  { START => 65163, END => 65207, 
    TEXT => 'VM Træning 2019', CORR => 'Danish Practice' },
  { START => 65216, END => 65251, 
    TEXT => 'Inter State Bridge Championship', 
    CORR => 'Indian Inter-State Teams' },
  { START => 66057, END => 66086, 
    TEXT => 'Hainan\(Sanya Nanshan\) International Bridge', 
    CORR => 'HNA Open Teams' },
  { START => 66098, END => 66135, 
    TEXT => 'DNO4 D1', CORR => 'French First Division' },
  { START => 66100, END => 66130, 
    TEXT => 'Danmark - 1_division', CORR => 'Danish First Division' },
  { START => 66172, END => 66239, 
    TEXT => 'Italy Cup Over 61', CORR => 'Italian O61 Cup' },
  { START => 66203, END => 66210, 
    TEXT => 'Bridge Great Britain', CORR => 'British Gold Cup' },
  { START => 66264, END => 66272, 
    TEXT => 'The 3th China Bridge Extre Challange Match', 
    CORR => 'China Practice' },
  { START => 66283, END => 66352, 
    TEXT => 'eleventh Pan Arab Inter Club', 
    CORR => '11th Pan Arab Inter Club' },
  { START => 66287, END => 66344, 
    TEXT => 'JiangSu', CORR => 'Jiangsu' },
  { START => 66308, END => 66348, 
    TEXT => 'Spring Nationals* Teams', 
    CORR => 'Australian Spring Open Teams' },
  { START => 66337, END => 66364, 
    TEXT => 'DNO_4 d1', CORR => 'French First Division' },
  { START => 66418, END => 66449, 
    TEXT => 'Selection France-Poland', CORR => 'French Open Trials' },
  { START => 66560, END => 66821, 
    TEXT => 'Copyright.IMSA_CN', CORR => '' },
  { START => 66587, END => 66752, 
    TEXT => '2020OPO', CORR => '2020 Australian Open Trials' },
  { START => 66565, END => 66575, 
    TEXT => "Invitational Teams Tournament \"Kaylaka Cup 2019\"", 
    CORR => '2019 Kaylaka Cup' },
  { START => 66602, END => 66665, 
    TEXT => "Open Teams Tournament \"Kaylaka Cup 2019\"", 
    CORR => '2019 Kaylaka Cup' },
  { START => 66647, END => 66777, 
    TEXT => 'GRL4 4th China Mind Games', 
    CORR => '4th China Mind Games - U26 Women' },
  { START => 66657, END => 66776, 
    TEXT => 'JNR3 4th China Mind Games', 
    CORR => '4th China Mind Games - U26 ' },
  { START => 66686, END => 66742, 
    TEXT => 'Kejurnas Mahasiswa _ Pelajar', 
    CORR => 'Indonesian University Teams ' },
  { START => 66588, END => 66888, TEXT => 'MIX[12] ', CORR => '' },
  { START => 66696, END => 66819, TEXT => 'MR1 ', CORR => '' },
  { START => 66697, END => 66821, 
    TEXT => 'MS2 ', CORR => '' },
  { START => 66775, END => 66818, 
    TEXT => 'Bolivariano', CORR => 'Bolivian Open Teams' },
  { START => 66824, END => 66888, 
    TEXT => "President's Cup 2019 Ahemedabad", 
    CORR => "2019 Ahmedabad President's Cup" },
  { START => 66847, END => 66893, 
    TEXT => 'Danmark - 1_division', CORR => 'Danish First Division' },
  { START => 66868, END => 66876, 
    TEXT => 'State Teams Final', 
    CORR => 'John Arkinstall State Teams Final' },
  { START => 66927, END => 67021, 
    TEXT => 'Stage 2', CORR => '' },
  { START => 66927, END => 67021, 
    TEXT => 'England Euro Teams Trials*', CORR => 'English Open Trials' },
  { START => 67129, END => 67403, 
    TEXT => '2020WSPO', CORR => '2020 Australian Playoffs' },
  { START => 67400, END => 67411, 
    TEXT => '61 *st Winter National', 
    CORR => '61st Indian Winter Nationals' },
  { START => 67357, END => 67410, 
    TEXT => 'Winter Nationals*', CORR => 'Indian Winter Nationals' },
  { START => 67423, END => 67481, 
    TEXT => 'Grand Prix of Poland', CORR => 'Grand Prix of Poland Teams' },
  { START => 67507, END => 67539, 
    TEXT => 'Grand Prix of Poland', CORR => 'Grand Prix of Poland Pairs' },
  { START => 67582, END => 67641, 
    TEXT => 'U26 USA[12]', CORR => 'US Junior Trials' },
  { START => 67596, END => 67642, 
    TEXT => 'U21 USA[12]', CORR => 'US Youngster Trials' },
  { START => 67650, END => 67718, 
    TEXT => 'European Open Trials*', CORR => 'English Open Trials' },
  { START => 68075, END => 68090, 
    TEXT => 'Twin Towns', CORR => 'Elblag Twin Towns Open Teams' },
  { START => 68109, END => 68192, 
    TEXT => 'France *-* *England', CORR => 'France Friendly' },
  { START => 68115, END => 68130, 
    TEXT => 'Polich Team', CORR => 'Polish Team' },
  { START => 68284, END => 68314, 
    TEXT => 'European Mixed Trials', CORR => 'English Mixed Trials' },
  { START => 68429, END => 68438, 
    TEXT => 'Sélection _4 Mixte', CORR => 'French Mixed Trials' },
  { START => 68656, END => 68700, TEXT => 'Seri 1$', CORR => '' },
  { START => 68942, END => 68945, 
    TEXT => 'SABF HEAD2HEAD', CORR => 'South African Open Teams' },
  { START => 68909, END => 68941, 
    TEXT => 'SABF', CORR => 'South African Open Teams' },
  { START => 68947, END => 68958, 
    TEXT => 'Open Trials*', CORR => 'EBU Open Trials' },
  { START => 69931, END => 69949, 
    TEXT => 'Danmark - 1_division', CORR => 'Danish First Division' },
  { START => 70030, END => 70051, 
    TEXT => 'Danmark - Slutspil', CORR => 'Danish First Division' },
  { START => 70131, END => 70135, 
    TEXT => 'NM-kvalik', CORR => 'Norwegian Open Teams - Qualifying' },
  { START => 70247, END => 70293, 
    TEXT => 'NM Par', CORR => 'Norwegian Open Pairs' },
  { START => 70590, END => 70595, 
    TEXT => 'Taiwan University & College Cup', 
    CORR => 'Taiwan University Open Cup - Final' },
  { START => 70871, END => 70895, 
    TEXT => 'NZ Interprovincials', 
    CORR => 'New Zealand Inter-Provincial Teams' },
  { START => 71112, END => 71118, 
    TEXT => 'CTCBA senior', CORR => 'CTCBA Senior Team' },
  { START => 71941, END => 71948, 
    TEXT => 'Bulgarian Federation Group A Final', 
    CORR => 'Bulgarian Open Teams - Final' },
  { START => 72015, END => 72036, 
    TEXT => '1-st', CORR => '1st' },
  { START => 72015, END => 72036, 
    TEXT => "International Bridge  Tournament BK \"ALERT\"", 
    CORR => 'Plovdiv Open Teams' },
  { START => 72619, END => 72629, 
    TEXT => 'Pokalsemifinaler*', CORR => 'Danish Cup - SF' },
  { START => 72633, END => 72649, 
    TEXT => 'Pokalturnering', CORR => 'Danish Cup' },
  { START => 72698, END => 72741, 
    TEXT => 'Grand Prix of Poland', CORR => 'Grand Prix of Poland Teams' },
  { START => 72731, END => 72741, 
    TEXT => 'Lubomino F', CORR => 'Lubomino Final' },
  { START => 72755, END => 72820, 
    TEXT => 'Bulgarian Bridge Federation A Group', 
    CORR => 'Bulgarian Open Teams' },
  { START => 72790, END => 72806, 
    TEXT => 'Open Trials', CORR => 'EBU Open Trials' },
  { START => 72877, END => 72901, 
    TEXT => 'Danmark - 1_division', CORR => 'Danish First Division' },
  { START => 72914, END => 72954, 
    TEXT => 'Italian Trials* BB 2022', 
    CORR => 'Italian Open Team Trials' },
  { START => 73005, END => 73046, 
    TEXT => 'Italian Teams* Championships', CORR => 'Italian Open Teams' },
  { START => 73020, END => 73042, 
    TEXT => 'Danmark - Klubhold', CORR => 'Danish First Division' },
  { START => 73081, END => 73101, 
    TEXT => '5-th Bridge Tournament Kaylaka Cup 2021', 
    CORR => '5th Kaylaka Cup 2021' },
  { START => 73113, END => 73153, 
    TEXT => '41-st', CORR => '41st' },
  { START => 73121, END => 73163, 
    TEXT => 'Interklub', CORR => 'Swiss Club Championship' },
  { START => 73225, END => 73253, 
    TEXT => 'Danmark - 1_division', CORR => 'Danish First Division' },
  { START => 73310, END => 73342, 
    TEXT => "Finnish Pair's Finals*", 
    CORR => 'Finnish Open Pairs - Final' },
  { START => 73404, END => 73409, 
    TEXT => 'KO F', CORR => 'KO Final' },
  { START => 73413, END => 73734, 
    TEXT => 'Grand Prix of Poland - Pairs', 
    CORR => 'Grand Prix of Poland Pairs' },
  { START => 73625, END => 73648, 
    TEXT => 'Sélection open phase 2', CORR => 'French Open Trials' },
  { START => 73665, END => 73678, 
    TEXT => 'Hungarial Trials', CORR => 'Hungarian Open Trials' },
  { START => 73511, END => 73533, 
    TEXT => 'Grand Prix of Poland', CORR => 'Grand Prix of Poland Teams' },
  { START => 73580, END => 73586, 
    TEXT => 'DF', CORR => 'SF' },
  { START => 73811, END => 73854, 
    TEXT => 'Danmark - 1_ *division', CORR => 'Danish First Division' },
  { START => 73824, END => 73846, 
    TEXT => '2-nd', CORR => '2nd' },
  { START => 73890, END => 73924, 
    TEXT => 'Grand Prix of Poland', CORR => 'Grand Prix of Poland Teams' },
  { START => 74000, END => 74049, 
    TEXT => 'Bulgarian Bridge Federation Championship', 
    CORR => 'Bulgarian Open Teams' },
  { START => 74019, END => 74053, 
    TEXT => 'Istanbul Acik', CORR => 'Istanbul Winter Open Teams' },
  { START => 74035, END => 74054, 
    TEXT => 'Playoff A Final *$', CORR => 'Final' },
  { START => 74358, END => 74375, 
    TEXT => 'Turkey Winter Open Finals Championship', 
    CORR => 'Turkish Winter Open Teams Final' },
  { START => 74429, END => 74476, 
    TEXT => 'Kadra Mikst', CORR => 'Polish Mixed Teams' },
  { START => 74446, END => 74482, 
    TEXT => 'Danmark - Slutspil', CORR => 'Danish First Division' },
  { START => 74532, END => 74608, 
    TEXT => 'kadraU20_21_2.', CORR => 'Polish U21 Pair Trials' },
  { START => 74734, END => 74805, 
    TEXT => 'Maris Sveaas T1', CORR => 'Marit Sveaas Open Pairs' },
  { START => 75185, END => 75318, 
    TEXT => '-W26$', CORR => ' - U26 Women' },
  { START => 75404, END => 75424, 
    TEXT => 'Tornament', CORR => 'Tournament' },
  { START => 76157, END => 76196, 
    TEXT => 'Danmark - Pokalslutspil', CORR => 'Danish Cup' },
  { START => 76242, END => 76265, 
    TEXT => 'English Premier League Div 1', 
    CORR => 'English Premier League' },
  { START => 76348, END => 76381, 
    TEXT => '40 years Organized Bridge Bulgaria - Open Teams', 
    CORR => 'Bulgarian Anniversary Open Teams' },
  { START => 76283, END => 76380, 
    TEXT => 'Interstate National Bridge Championship', 
    CORR => 'Indian Inter-State Teams' },
  { START => 76342, END => 76375, 
    TEXT => 'Thailand Bridge Championships', 
    CORR => 'Thailand Open Teams' },
  { START => 76434, END => 76439, TEXT => 'Grand Final', CORR => '' },
  { START => 76456, END => 76468, 
    TEXT => 'Grand Final', CORR => 'Final' },
  { START => 74626, END => 74673, 
    TEXT => 'Italian Women Teams', CORR => 'Italian Women Cup' },
  { START => 74642, END => 74659, 
    TEXT => 'Wroclaw Blue Ribbon', 
    CORR => 'Wroclaw Meeting - Open Teams' },
  { START => 76516, END => 76550, 
    TEXT => "Offene Deutsche 'Teammeisterschaft", 
    CORR => 'Offene Deutsche Teammeisterschaft' },
  { START => 76521, END => 76551, 
    TEXT => 'DNO4 D1', CORR => 'French First Division' },
  { START => 74614, END => 74616, 
    TEXT => 'Final Mästarserien', CORR => 'S:t Erik Championship Series' },
  { START => 74715, END => 74802, 
    TEXT => 'Nordic Teams Championships 2022 w', 
    CORR => 'Nordic Teams Championships 2022 Women' },
  { START => 74620, END => 74641, TEXT => '1_2 finales', CORR => 'SF' },
  { START => 74717, END => 74799, 
    TEXT => 'Nordic Teams Championships 2022 o', 
    CORR => 'Nordic Teams Championships 2022 Open' },
  { START => 75038, END => 75061, TEXT => '^Open', CORR => '' },
  { START => 75038, END => 75061, TEXT => '^Girls* ', CORR => 'Women ' },
  { START => 75510, END => 75546, 
    TEXT => 'U26O_U31O', CORR => 'U31' },
  { START => 75550, END => 75569, 
    TEXT => 'U26O', CORR => 'U26' },
  { START => 76225, END => 76254, TEXT => ' Seri 3$', CORR => '' },
  { START => 76321, END => 76327, 
    TEXT => 'Open Temas', CORR => ' Open Teams ' },
  { START => 76484, END => 76546, 
    TEXT => 'Masters Invitational Pairs', 
    CORR => 'Indian Masters Invitational Pairs' },
  { START => 76684, END => 76751, 
    TEXT => 'Italy Cup Over 63', CORR => 'Italian O63 Cup' },
  { START => 76849, END => 76893, 
    TEXT => 'TBIB Open', CORR => 'Australian Spring Open Teams' },
  { START => 76870, END => 76878, TEXT => '^1_4 de Finale', CORR => 'QF' },
  { START => 76879, END => 76884, TEXT => '^1_2 Finale', CORR => 'SF' },
  { START => 76902, END => 76906, 
    TEXT => 'Finale de Zone de la', CORR => 'Qualifying - ' },
  { START => 76870, END => 76901, TEXT => 'de Zone de', CORR => '' },
  { START => 77024, END => 77032, 
    TEXT => 'FSB Ch_ *A Semifinal', 
    CORR => 'Swiss Club Championship - SF' },
  { START => 77043, END => 77051, 
    TEXT => 'Swiss National *Championship', 
    CORR => 'Swiss Club Championship' },
  { START => 77088, END => 77273, 
    TEXT => '#', CORR => ' ' },
  { START => 77137, END => 77162, 
    TEXT => 'Pasangan_Open', CORR => 'Open Pairs' },
  { START => 77141, END => 77206, 
    TEXT => 'BALARAMPUR CHINI EAST ZONE', 
    CORR => 'BALARAMPUR CHINI West Bengal State Championship' },
  { START => 77286, END => 77343, 
    TEXT => 'Bulgaria SuperFinal', CORR => 'Bulgarian Open Cup' },
  { START => 74430, END => 74484, 
    TEXT => 'Italian Teams Championships', 
    CORR => 'Italian Open Teams' },
  { START => 77545, END => 77778, 
    TEXT => 'Winter Nationals*', CORR => 'Indian Winter Nationals' },
  { START => 77666, END => 77698, 
    TEXT => 'Winter National Bridge Tournament', 
    CORR => 'Indian Winter Nationals' },
  { START => 77714, END => 77728, 
    TEXT => 'Bulgaria Semifinal Club Team Championship', 
    CORR => 'Bulgarian Club Teams - SF' },
  { START => 77716, END => 77775, 
    TEXT => 'Grand Prix of Poland', CORR => 'Grand Prix of Poland Teams' },
  { START => 77719, END => 77777, 
    TEXT => 'EBU Lady Milne Trials', CORR => 'English Women Pair Trials' },
  { START => 77736, END => 77770, 
    TEXT => 'Bulgaria Final Club Team Championship', 
    CORR => 'Bulgarian Club Teams - Final' },
  { START => 77754, END => 77768, 
    TEXT => 'Winter Mix Pair', CORR => 'Indian Mixed Pairs' },
  { START => 77789, END => 77849, 
    TEXT => 'Teltscher Trophy 2023 Trials', 
    CORR => 'Teltscher Trophy Trials 2023' },
  { START => 77800, END => 77841, 
    TEXT => 'Grand Prix of Poland - Pairs', 
    CORR => 'Grand Prix of Poland Pairs' },
  { START => 77963, END => 77983, 
    TEXT => 'Halve Finale MK', CORR => 'Dutch Meesterklasse - SF' },
  { START => 78084, END => 78121, TEXT => ' 202$', CORR => ' 2022' },
  { START => 78092, END => 78127, 
    TEXT => 'DBV-Kadertraining in Rieneck', 
    CORR => 'Germany Practice - Rieneck' },
  { START => 78136, END => 78140, 
    TEXT => 'National Teams Challenge', CORR => 'Iceland Friendly' },
  { START => 78272, END => 78315, 
    TEXT => 'Polish National Trails', CORR => 'Polish National Trials' },
  { START => 78360, END => 78379, 
    TEXT => 'Danmark - 1_division', CORR => 'Danish First Division' },
  { START => 78384, END => 78406, 
    TEXT => 'Polish U21 Trials Final', 
    CORR => 'Polish U21 Team Trials - Final' },
  { START => 78410, END => 78437, 
    TEXT => 'Polish U21 Trials Final Pairs', 
    CORR => 'Polish U21 Pairs Trials - Final' },
  { START => 78580, END => 78589, TEXT => '1_64', CORR => 'Rof64' },
  { START => 78595, END => 78605, TEXT => '1_32', CORR => 'Rof32' },
  { START => 78609, END => 78619, TEXT => '1_16', CORR => 'Rof16' },
  { START => 78622, END => 78634, TEXT => '1_8', CORR => 'QF' },
  { START => 78652, END => 78697, 
    TEXT => 'Grand Prix of Poland', CORR => 'Grand Prix of Poland Teams' },
  { START => 78673, END => 78682, 
    TEXT => 'Þristamótið', CORR => '' },
  { START => 78684, END => 78701, 
    TEXT => 'Thristamotid', CORR => '' },
  { START => 78666, END => 78699, 
    TEXT => 'Utmanarmatchen', CORR => 'Sweden Practice' },
  { START => 78770, END => 78778, 
    TEXT => 'Zonal Libres', CORR => 'South American Zonal Open Teams' },
  { START => 78780, END => 78860, 
    TEXT => '^Transnational$', 
    CORR => 'South American Transnational Open Teams' },
  { START => 78798, END => 78840, 
    TEXT => 'Slutspil', CORR => 'Danish First Division' },
  { START => 78961, END => 79020, 
    TEXT => 'Summer Open Teams', CORR => 'Turkish Summer Open Teams' },
  { START => 78993, END => 79021, 
    TEXT => 'Summer Women Teams', CORR => 'Turkish Summer Women Teams' },
  { START => 79245, END => 79264, 
    TEXT => 'Andrzej Zurek Memorial', 
    CORR => 'Grand Prix of Poland Teams - Andrzej Zurek Memorial' },
  { START => 79285, END => 79382, 
    TEXT => 'Norwegian Clubs - Teams Championships', 
    CORR => 'Norwegian Club Teams' },
  { START => 79317, END => 79373, 
    TEXT => 'Bulgarian Federation', CORR => 'Bulgarian Open Teams' },
  { START => 79410, END => 79444, 
    TEXT => 'Preselecci.n Parejas Seleccionadas', 
    CORR => 'Argentinian Open Trials' },
  { START => 79523, END => 79615, 
    TEXT => 'Parejas Seleccionadas', CORR => 'Argentinian Open Trials' },
  { START => 79529, END => 79734, 
    TEXT => 'APBF', CORR => 'APBF Championships' },
  { START => 79747, END => 79749, 
    TEXT => 'Championship of Tanjungpura Universit', 
    CORR => 'FTBC Tanjungpura University' },
  { START => 79750, END => 79759, 
    TEXT => '^2023-23rd', CORR => '23rd' },
  { START => 79761, END => 79769, 
    TEXT => 'Thai-Chinese Bridge Friendly Match', 
    CORR => 'China Friendly' },
  { START => 79821, END => 79832, 
    TEXT => 'Ege Kulupler', CORR => 'Aegean Open Teams' },
  { START => 79890, END => 79893, 
    TEXT => 'Campeonato Nacional Equipos Mixtos', 
    CORR => 'EQUIPOS MIXTOS ARGENTINA' },
  { START => 80135, END => 80252, 
    TEXT => 'Indonesian* Open', CORR => 'Indonesian Open Teams' },
  { START => 80397, END => 80404, 
    TEXT => '1st National Brudge Tournament Chelopech',
    CORR => '1st Chelopech Open Teams' },
  { START => 80708, END => 80713, 
    TEXT => 'Pokalsemifinale', CORR => 'Danish Cup - SF' },
  { START => 80800, END => 80836, 
    TEXT => 'Danmark - Open Pairs*', CORR => 'Danish Open Pairs' },
  { START => 80860, END => 80887, 
    TEXT => 'Bulgarian Teams Championship', 
    CORR => 'Bulgarian Club Teams' },
  { START => 80899, END => 80952, 
    TEXT => 'Italy Cup Over 63', CORR => 'Italian O63 Cup' },
  { START => 80999, END => 81033, 
    TEXT => 'Danmark - 1_division', CORR => 'Danish First Division' },
  { START => 81070, END => 81111, 
    TEXT => 'Premier League Division 1', 
    CORR => 'English Premier League' },
  { START => 81245, END => 81266, 
    TEXT => 'India All Star vs World All Star Team', 
    CORR => 'India Exhibition' },
  { START => 81427, END => 81445, 
    TEXT => '-OT$', CORR => ' - Open Teams' },
  { START => 81451, END => 81457, 
    TEXT => 'KU-BEBAS', CORR => 'Open' },
  { START => 81560, END => 81574, 
    TEXT => 'Interstate National Bridge Championship', 
    CORR => 'Indian Inter-State Teams' },
  { START => 81827, END => 81866, 
    TEXT => 'Grand Prix of Poland - Pairs', 
    CORR => 'Grand Prix of Poland Pairs' },
  { START => 81981, END => 82045, 
    TEXT => 'Grand Prix of Poland', CORR => 'Grand Prix of Poland Teams' },
  { START => 82080, END => 82118, 
    TEXT => 'Winter National Bridge Championship', 
    CORR => 'Indian Winter Nationals' },
  { START => 82275, END => 82303, 
    TEXT => 'Turkish National', CORR => 'Turkish Winter Championships' },
  { START => 82312, END => 82342, 
    TEXT => 'France-Suisse', CORR => 'France Friendly' },
  { START => 82319, END => 82345, 
    TEXT => 'Reykjavík Teams', CORR => 'Iceland Express Teams' },
  { START => 82427, END => 82485, 
    TEXT => 'France - Sweden', CORR => 'France Friendly' },
  { START => 82859, END => 82860, 
    TEXT => 'Finale IMP en Lombard Topcircuit', 
    CORR => 'Lombard - Dutch Top Circuit' },
  { START => 82563, END => 82588, 
    TEXT => 'Seleccion Cali 2024 - Libres', 
    CORR => 'Argentinian Open Trials' },
  { START => 82580, END => 82590, 
    TEXT => 'Seleccion Cali 2024 - Damas', 
    CORR => 'Argentinian Women Trials' },
  { START => 82616, END => 82653, 
    TEXT => 'all india tolani open national masters* championshi*', 
    CORR => 'Indian Masters Open Teams' },
  { START => 82753, END => 82773, 
    TEXT => 'Polish IMPs Teams', CORR => 'Polish Open Teams' },
  { START => 82777, END => 82792, 
    TEXT => 'Polish Teams', CORR => 'Polish Open Teams' },
  { START => 82867, END => 82870, 
    TEXT => 'Spring Intercollegiate Championship', 
    CORR => 'Japanese Intercollege Teams' },
  { START => 83015, END => 83028, 
    TEXT => 'Grand Prix of Poland', CORR => 'Grand Prix of Poland Teams' },
  { START => 83154, END => 83193, 
    TEXT => 'SABCH', 
    CORR => 'South American Open Teams' },
  { START => 83176, END => 83206, 
    TEXT => 'Slutspil', CORR => 'Danish First Division' },
  { START => 83207, END => 83317, 
    TEXT => '2024EWTC$', CORR => ' - 2024 European Winter Teams' },
  { START => 83265, END => 83315, 
    TEXT => 'Greek Trials 2024 \(Selection\)', 
    CORR => 'Greek Open Team Trials 2024' },
  { START => 83358, END => 83402, 
    TEXT => 'Turkish Summer', CORR => 'Turkish Summer Championships' },
  { START => 83553, END => 83573, 
    TEXT => 'SELECCION OLIMPIADAS SENIOR', 
    CORR => 'Argentinian Senior Trials Olympics' },
  { START => 83562, END => 83583, 
    TEXT => 'Practice TeamNL Bridge Open - Iceland', 
    CORR => 'Netherlands Practice' },
  { START => 83618, END => 83690, 
    TEXT => 'WBT Contra Cup 2nd edition', CORR => '2nd Contra Cup' },
  { START => 83782, END => 83790, 
    TEXT => 'OOMy', CORR => 'Polish Youth Olympics' },
  { START => 83592, END => 83624, 
    TEXT => 'Bodo', CORR => 'Bodø' },
  { START => 83886, END => 83902, 
    TEXT => 'Portuguese Championship 2024 - Teams', 
    CORR => 'Portuguese Open Teams - 2024' },
  { START => 84097, END => 84121, 
    TEXT => '^Ege$', CORR => 'Aegean Open Teams' },
  { START => 84137, END => 84215, 
    TEXT => 'U26W', CORR => 'U26 Women' },
  { START => 84169, END => 84254, 
    TEXT => 'U23W', CORR => 'U23 Women' },
  { START => 84257, END => 84284, 
    TEXT => 'U31Pairs', CORR => 'U31 Pairs' },
  { START => 84257, END => 84286, 
    TEXT => '^[A-E]\d+-', CORR => '' },
  { START => 84258, END => 84285, 
    TEXT => 'U26Pairs', CORR => 'U26 Pairs' },
  { START => 84279, END => 84286, 
    TEXT => 'U26WPairs', CORR => 'U26 Women Pairs' },
  { START => 84404, END => 84408, 
    TEXT => 'Polish Teams Championships', CORR => 'Polish Open Teams' },
  { START => 84446, END => 84518, 
    TEXT => 'Geen*ly Automobile Inter-city Bridge', 
    CORR => 'Geely Automobile Chinese Inter-City Teams' },
  { START => 84568, END => 84572, 
    TEXT => 'Grand Prix of Poland', CORR => 'Grand Prix of Poland Teams' },
  { START => 84595, END => 84611, 
    TEXT => 'Interstate Championship', 
    CORR => 'Indian Inter-State Teams' },
  { START => 84646, END => 84725, 
    TEXT => 'BK Istanbul', CORR => 'Istanbul Sports' },
  { START => 84648, END => 84665, 
    TEXT => 'Pokalsemifinale', CORR => 'Danish Cup - SF' },
  { START => 84790, END => 84822, 
    TEXT => 'Nationale Interclubs', CORR => 'French First Division' },
  { START => 84967, END => 85055, 
    TEXT => '7th SEABF & 40th ABCC', 
    CORR => '40th ASEAN Club Championship' },
  { START => 84991, END => 85058, 
    TEXT => "Italian Men's Teams Championships",
    CORR => 'Italian Open Teams' },
  { START => 85046, END => 85061, 
    TEXT => 'Grand Prix of Poland', CORR => 'Grand Prix of Poland Teams' },
  { START => 85135, END => 85155, 
    TEXT => 'Danmark - 1_ division', CORR => 'Danish First Division' },
  { START => 85267, END => 85437, 
    TEXT => 'Buenos Aires-O$', CORR => 'Buenos Aires - Open' },
  { START => 85267, END => 85437, 
    TEXT => 'Buenos Aires-S$', CORR => 'Buenos Aires - Seniors' },
  { START => 85267, END => 85514, 
    TEXT => 'Buenos Aires-W$', CORR => 'Buenos Aires - Women' },
  { START => 85444, END => 85511, 
    TEXT => 'Italian Mixed Championships', 
    CORR => 'Italian Mixed Teams' },
  { START => 85478, END => 85514, 
    TEXT => 'Danmark - 1_division', CORR => 'Danish First Division' },
  { START => 85585, END => 85634, 
    TEXT => 'Bulgarian Team Championship', 
    CORR => 'Bulgarian Club Teams' },
  { START => 85590, END => 85671, 
    TEXT => '2025OTPO', CORR => '2024 Australian Open Trials' },
  { START => 85746, END => 85790, 
    TEXT => 'NZ Regional Championships', 
    CORR => 'New Zealand Inter-Provincial Teams' },
  { START => 85799, END => 85966, 
    TEXT => 'SABF State Teams Final', 
    CORR => 'South Australia Open Teams - Final' },
  { START => 85871, END => 86000, 
    TEXT => '2025MTPO', CORR => '2024 Australian Mixed Trials' },
  { START => 86029, END => 86083, 
    TEXT => 'Grand Prix of Poland', CORR => 'Grand Prix of Poland Pairs' },
  { START => 86107, END => 86127, 
    TEXT => 'Grand Prix of Poland', CORR => 'Grand Prix of Poland Teams' },
);

my @LOCAL_SUBS_INTERPOL =
(
  { START => 49428, END => 49491, 
    TEXT => '2016-2017 (\d+) af 11$', 
    CORR => '2016-2017 - Round $1 of 11' },
  { START => 56247, END => 56266, TEXT => '1_(\d+)$', CORR => 'Rof$1' },
  { START => 61333, END => 61361, TEXT => '1_(\d+)$', CORR => 'Rof$1' },
  { START => 64658, END => 64667, TEXT => '1_(\d+)$', CORR => 'Rof$1' },
  { START => 78194, END => 78837, 
    TEXT => 'Bundesliga 2023 (\d)_9', 
    CORR => 'Bundesliga 2023 - Round $1 of 9' },
  { START => 79729, END => 79734, 
    TEXT => '(\d)_3\)', CORR => 'Segment $1 of 3)' },
  { START => 81332, END => 81381, 
    TEXT => 'Interklub 2023 (\d)-2', 
    CORR => 'Swiss Club Championship - Match $1 of 2' },
  { START => 82213, END => 82230, 
    TEXT => 'Bundesliga 2024 (\d)_9', 
    CORR => 'Bundesliga 2024 - Round $1 of 9' },
  { START => 82606, END => 82638, 
    TEXT => 'Bundesliga 2024 (\d)_9', 
    CORR => 'Bundesliga 2024 - Round $1 of 9' },
  { START => 82848, END => 82859, 
    TEXT => 'Bundesliga 2024 (\d)_9', 
    CORR => 'Bundesliga 2024 - Round $1 of 9' },
  { START => 82926, END => 82951, TEXT => '1_(\d+)$', CORR => 'Rof$1' },
);


sub local_substitutions
{
  my ($text, $bbono) = @_;

  for my $entry (@LOCAL_SUBS)
  {
    if ($bbono >= $entry->{START} && $bbono <= $entry->{END})
    {
      $text =~ s/$entry->{TEXT}/$entry->{CORR}/i;
    }
  }

  for my $entry (@LOCAL_SUBS_INTERPOL)
  {
    if ($bbono >= $entry->{START} && $bbono <= $entry->{END})
    {
      $text =~ s/$entry->{TEXT}/linterpol($1, $2, $entry->{CORR})/ie;
    }
  }
  return $text;
}


sub linterpol
{
  my ($m1, $m2, $corr) = @_;
  $corr =~ s/\$1/$m1/;
  return $corr =~ s/\$2/$m2/r;
}


sub title_specific_inline
{
  my ($text) = @_;

  if ($text =~ /1[\/_](\d)\s+final/i)
  {
    # 1/4 final(e), 1/2 final(e).
    my $n = $1;
    warn "Haven't learned this yet: $text" unless $n == 2 || $n == 4;
    $text =~ s/1\/4 finale*/quarterfinal/;
    $text =~ s/1\/2 finale*/semifinal/;
  }

  # Years: '9x, '0x, '1x.
  $text =~ s/'(9\d)/19$1/g;
  $text =~ s/'(0\d)/20$1/g;
  $text =~ s/'(1\d)/20$1/g;

  # Remove nameless teams.
  $text =~ s/#\d+\s+vs*\s+#*\d+//;
  $text =~ s/tm\s+\d+\s+vs\s+tm\s+\d+//i;
  $text =~ s/team\s+\d+\s+vs\s+team\s+\d+//i;
  $text =~ s/- \d+ v \d+//i;

  # Add some spacing.
  $text =~ s/^(\d+)th([a-z])/$1th $2/i; # 8th|letter
  $text =~ s/^([01]\d)([A-SU-Z])/20$1 $2/; # Year. Avoid th
  $text =~ s/\b([1-9])([A-D])\b/$1 $2/gi; # 1|A
  $text =~ s/\b(\d)of(\d)\b/$1 of $2/g; # 1|of|2

  $text =~ s/\bDN[0O]_4\b/French First Division/g; # DN0_4, DNO_4
  
  # n_n (n of n), n&n (n to n).
  if ($text =~ /(\d+)[_&](\d+)/ && $1 <= $2 && $1 < 1990)
  {
    $text =~ s/(\d+)_(\d+)/$1 of $2/;
    $text =~ s/(\d+)&(\d+)/$1 to $2/;
  }

  # A hodge-podge, mostly of spacing.
  $text =~ s/pokal([a-z])/pokal $1/i; # pokal|a
  $text =~ s/(d[ae]nmark) - pokal/$1 Pokal/i;
  $text =~ s/-th\b/th/g; # 4-th
  $text =~ s/(\d) th\b/$1th/g; # 4 th
  $text =~ s/2 nd\b/2nd/g; #  2nd
  $text =~ s/\bUSA[12]/USA/g; # USA1
  $text =~ s/\bUSA 2\b/USA/g; # USA 2
  $text =~ s/II-nd/2nd/g; # II-nd
  $text =~ s/\b(\d\d) _$/Rof$1/g; # Line ending on 16 _
  $text =~ s/\bF([12])\b/Final $1/g; # F1

  return $text;
}


sub study_value
{
  my ($whole, $value, $pos, $chain, $unknown_value_flag) = @_;

  return if singleton_non_tag_matches($value, $pos, $chain,
    $main::histo_title, $PREFIX);

  return if singleton_tag_matches($whole, \@TAG_ORDER, $pos, $value, 
    0, $chain, $main::histo_title, $PREFIX);

  append_token($chain, 'UNKNOWN', '', $value, $value, 
    $pos, $main::histo_title, $PREFIX);

  print "SSS value $value \n";
  $$unknown_value_flag = 1;
}


sub study_component
{
  my ($whole, $value, $chain, $token_no, $unsolved_flag) = @_;

  # Split on trailing digits.
  my $digits = '';
  if ($value =~ /^(.*[a-z])(\d+)$/i &&
      $1 ne 'U' && $1 ne 'D')
  {
    ($value, $digits) = ($1, $2);
  }

  study_value($whole, $value, $token_no, $chain, $unsolved_flag);

  if ($digits ne '')
  {
    # Add the digits if they exist.
    singleton_numeral($digits, $token_no, $chain, 
      $main::histo_title, $PREFIX);
  }
}


sub study
{
  my ($whole, $bbono, $text, $chain, $unknowns) = @_;

  return if $text eq '';

  $text = local_substitutions($text, $bbono);
  my $stext = split_on_capitals($text);
  my $ntext = title_specific_inline($stext);

  my @tags = (0);
  my @values = ();
  my @texts = ();
  split_on_dates($ntext, \@tags, \@values, \@texts, 0);
  split_on_multi($whole, \@TAG_ORDER, 0, \@tags, \@values, \@texts);

  # Split on separators.
  my $sep = qr/[\s+\-\+\._:;&@"\/\(\)\|]/;

  my $token_no = 0;
  my $unsolved_flag = 0;

  for my $i (0 .. $#values)
  {
    if ($tags[$i] ne '0')
    {
      # We had a multi-word hit.
      append_token($chain, 'SINGLETON', $tags[$i], $values[$i], 
        $texts[$i], \$token_no, $main::histo_title, $PREFIX);
    }
    else
    {
      my @a = grep { $_ ne '' } split(/$sep/, $values[$i]);
      foreach my $value (@a)
      {
        study_component($whole, $value, $chain, \$token_no, 
          \$unsolved_flag);
      }
    }
  }

  if ($unsolved_flag)
  {
    $$unknowns++;
    print "SSS $bbono: $text\n" if $chain->last() > 0;
    print "\n";
  }
}


1;
