#!perl

use strict;
use warnings;
use v5.10;
use utf8;
use open ':std', ':encoding(UTF-8)';

package Title::Tname;

our @ISA = qw(Exporter);
our @EXPORT = qw(set_hashes);

use lib '.';
use TeamBBO;

my @MULTI_WORDS =
(
  'ABPF Championships',
  'All-China Games',
  'Altman Swiss Pairs',
  'Anatolian Spring Teams',
  'Aoda Cup',
  'ArboNed Team Cup',
  'Argentinian Flags Day Championship',
  'Australian Open Teams',
  'Australian Seniors Pairs',
  'Australian Seniors Teams',
  "Australian Women's Teams",
  'Australian Youth',
  'ARIS Cup',
  'ASEAN Club Championship',
  'Asia Cup',
  'Asian University Championship',
  'Australian National Open Teams',
  'Balikcioglu Teams Championship',
  'Baltic Bowl',
  'Baltic Cup',
  'Baltic Teams Cup',
  'Baze Senior Knock-out',
  'Bergen Grand Tournament',
  'Bermuda Bowl',
  'Bermuda Triangle Cup',
  'Bobby Evans Seniors Teams',
  'British Gold Cup',
  'Buffett Cup',
  'Canadian Bridge Championship',
  'Canadian National Teams Championship',
  'Canadian Seniors Teams Championship',
  'Canadian Women Teams Championship',
  'Carrousel Cup',
  'Cavendish Pairs',
  'Cavendish Teams',
  'Central American Zonal Championships',
  "Champions' Cup",
  'Channel Trophy',
  'Cherven Briag National Tournament',
  'Chilean Championship',
  'China Elite Tournament',
  'China Friend City Senior Team Tournament',
  'Chung Hua Cup',
  'Codan Cup',
  'Collegiate Bowl',
  'Commonwealth Nations Bridge Championships',
  'Computer World Championship',
  'Copa de Plata',
  'Copa de Oro',
  'Copa Zanalda',
  'Corn Cairdis',
  'Cross Strait Invitational',
  'Czech Championship',
  'Czech Team Championship',
  'Czech First League',
  "d'Orsi",
  'Damiani Cup',
  'Danish Club Teams',
  'Danish Junior Teams',
  'Danish Mixed Pairs',
  'Danish Open',
  'Danish Pairs Championship',
  'Danish Teams Championship',
  'Dongming Knock-out Teams',
  'Dr. Heinz von Rotteck Pokal',
  'Dutch Meesterklasse',
  'Egyptian League',
  'European Bridge Teams Championship',
  'European Open Bridge Championship',
  "European Champions' Cup",
  'European Championship',
  'European Small Federation Games',
  'European University Bridge Championship',
  'European Winter Games',
  'European Youth Bridge Championship',
  'European Youth Bridge Pairs Championship',
  'European Youth Bridge Teams Championship',
  'EUSA Games',
  'Farmen Invitational',
  'Filbyter Cup',
  'Finnish Cup',
  'Finnish Pairs Championship',
  'Finnish Teams Championship',
  'Forbo Krommenie Teams',
  'Forbo Nations Cup',
  'Forest Trophy',
  'Fortuna Cup',
  'FOSS Grand Tournament',
  'French Cup',
  'FullBridge International Teams',
  'Garden Cities',
  'Gardermoen Airport Hotel Cup',
  'Gelibolu Peace Cup',
  'German Club Cup',
  'German Team Championship',
  'German Team Trophy',
  'German Women Pairs',
  'Goksu-Yalikavak Pairs',
  'Golden Jubilee',
  'Grand National Open Teams',
  'Grand Prix of Poland',
  'Grand Prix of Prague',
  'Greek Open Teams',
  "Gro's Supercup",
  'Guangdong Club Championship',
  'Hainan Air Cup',
  'Haskovski Mineralni Bani',
  'Hecht Cup',
  'Hellenic Team Trials',
  'Hellenic Team Championship',
  'Higson Cup',
  'High-Tech Zone Workers Invitational',
  'Hong Kong Inter-City',
  'Icelandair Open',
  'Icelandair Team Championship',
  'Icelandic Cup',
  'Icelandic Teams',
  'IMSA Cup',
  'IMSA Elite Mind Games',
  'Indonesian League',
  'Indonesian National Games',
  'IOC Grand Prix',
  'Istanbul Winter Teams',
  'Italian Team Championship',
  'Italy Cup',
  "Jessheim New Year's Cup",
  'JPD Cup',
  'Junior Camrose',
  'Kalani Trophy',
  "Kepri Governor's Cup",
  'Kings and Queens Blaine Howe Teams',
  'König Ludwig Cup',
  'Krakow Spring',
  'Lady Milne Trophy',
  'Lederer Memorial Trophy',
  "Linda Stern Women's Teams",
  'Lüleburgaz Liberation Cup',
  'Maccabi Games',
  'McConnell Cup',
  'Mohan Sicka Trophy',
  'Mondial de Deauville',
  'Mountain Sea Cup',
  'Nations Cup',
  'NN Cup',
  'Nordic Championship',
  'Nordic Team Championship',
  'Nordic Junior Championship',
  'Nordic Junior Team Championship',
  'Nordic Cup',
  'Nordic Race',
  'North American Bridge Championship',
  'Northern Greece Regional Championship',
  'Northern Territory Gold Teams',
  'Northern Territory Gold Swiss Pairs',
  'Norwegian Club Teams',
  'Norwegian Swiss Teams',
  'NTU Cup',
  'Olrud Easter Mixed Pairs',
  'Olrud Easter Pairs',
  'Olrud Easter Swiss Teams',
  'Olrud Easter Teams',
  'Open Catalunya Preferent',
  'Pakistan Day Bridge Championship',
  'Palace Cup',
  'Pan Arab Inter-Club Championship',
  'Pan China Construction Tournament',
  'Park Hotell Swiss Teams',
  'Patton de Monaco',
  'Pärnu Summer Invitational Pairs',
  'Pärnu Summer Open Teams',
  'Peggy Bayer',
  'Pesta Sukan',
  'Petit Grand Prix van Driene',
  'Plock District League',
  'Poddar National Masters',
  'Polish Boys Championship',
  'Polish Girls Championship',
  'Polish Premier League',
  'Polish Youngster Teams',
  'Pomerania Cup',
  'Portuguese Open Teams',
  'Prince Henrik Trophy',
  'Prince Takamatsu Cup',
  'Puutalo Open',
  'PYC Royale',
  'Riga Invites to Jurmala',
  'Riau Governor Cup',
  'Roberto Taunay Cup',
  'Romanian League',
  'Rondane Cup',
  'Rottneros Nordic Cup',
  'Ruia Gold Cup',
  'Ruia Silver Cup',
  'Ruia Trophy',
  'Ruter 7 Open',
  'S:t Erik Championship Series',
  'Sao Paulo State Championship',
  'Sarundajang Cup',
  'Scottish Cup',
  'Semen Padang Cup',
  'Senior Camrose',
  'Serbian Cup',
  'Serbian Premier League',
  'Serbian Team Championship',
  'Shenhua Cup',
  'Shield of Thoisy',
  'Sigismund Bell Krakow',
  'Silver Jubilee',
  'Slava Cup',
  'Smirnov Cup',
  'South African Championship',
  'South American Bridge Championships',
  'South Zone Championship',
  'Southeast Asian Games',
  'Spanish Teams Championship',
  'Spring Fours',
  'Spring of Cracow',
  'Spring Nationals',
  'Staszic Pairs Cup',
  'Stena Line Cup',
  'Stern-Cornell Trophy',
  'Summer Monsoon League',
  'Summer Nationals',
  'Swiss Championship',
  'Swiss Cup',
  'Takamatsu Cup',
  'Taiwan University Cup',
  'Taiwanese Teams',
  'Teltscher Trophy',
  'The Hague Bridge Experience',
  'Thrace Cup League',
  'Tianjin Binhai Cup',
  'TGR Auction',
  'TGR Auction Pairs',
  'TGR Auction Teams',
  'TGR Super League',
  'Tolani Gold Trophy',
  'Tolani Grand Prix',
  'Tolani Silver Cup',
  'Torneo di Rastignano',
  'Torneo di Roma',
  'Towns Cup',
  'Transnational Open Teams',
  'Trondheim Cup',
  'United States Bridge Championship',
  'United States Juniors Bridge Championship',
  'United States Seniors Bridge Championship',
  'United States Women Bridge Championship',
  'Vanderbilt Fantasy Challenge',
  'Venice Cup',
  'Victor Champion Cup',
  'Victorian Pennant',
  'Vilnius Club Pairs',
  'Vinoble Cup',
  'VV Cup',
  'Watermark Bridge Classic',
  'White House Juniors',
  'White House Top 12',
  'White House Top 16',
  'White House Top Circuit',
  'Whitelaw Cup',
  'Winter Nationals',
  'Winter Championships',
  'Winter Open Teams',
  'Winter Women Teams',
  'World Bridge Series',
  'World Masters Individual',
  'World Men Elite Tournament',
  'World Mind Games',
  'World Team Championships',
  'World Team Olympiad',
  'World Top Tournament',
  'World Transnational Teams',
  'World University Championship',
  'World Youth Congress',
  'World Youth Open Bridge Championship',
  'World Youth Teams Championship',
  'World Youth Bridge Congress',
  'World Youth Bridge Teams Championship',
  'World Women Elite Tournament',
  'Xinyuan Cup',
  'Yeh Bros Cup',
  'Young Chelsea Knock-out',
  'Zhejiang Huamen Cup',
  'Zimmermann Cup'
);

my %MULTI_TYPOS =
(
  'Anatolian Spring Teams' => ['anatolia spring teams'],
  'ArboNed Team Cup' => ['arbo ned team cup', 'arbo ned teams cup'],
  'ASEAN Club Championship' => ["asean bridge club c'ship",
    'asean bridge club championship', "asean bridge c'ship",
    'asean bridge club', 'asean bridge club championships',
    'asean bridge cship', 'asean bridge championship',
    'asean bridge club open championships',
    'asean bridg club championship', 'asean bridge championships',
    'asean club championships', "aseam bridge club c'ship"],
  'Asian University Championship' => [
    'asian university bridge championship'],
  'Australian Open Teams' => ['aust open'],
  'Australian Seniors Pairs' => ['aust seniors pairs'],,
  'Australian Seniors Teams' => ['aust seniors open', 'sen australian',
    'aust senriors open'],
  "Australian Women's Teams" => ["aust women's team",
    'aust womens team'],
  'Australian Youth' => ['aust youth'],
  'Baze Senior Knock-out' => ['baze senior ko', 'baze sr_ ko',
    'base sr ko', 'baze sr_ ko', 'baze sr ko'],
  'Bergen Grand Tournament' => ['bergen open', 'bergen stor',
    'bergen storturnering', 'bergen grand tournamnet'],
  'Bermuda Triangle Cup' => ['bermuda triangle teams cup'],
  'Bobby Evans Seniors Teams' => ["bobby evans senior's teams",
    'bobby evans senior teams'],
  'British Gold Cup' => ['gold cup', 'british gold'],
  'Buffett Cup' => ['buffet cup', 'bufett cup'],
  Camrose => ['camrose trophy'],
  'Cavendish Teams' => ['cavendish tms', 'cavendish team'],
  'Central American Zonal Championships' => ["cacbf zonal ch'ships"],
  "Champions' Cup" => ['champions cup', "champion's cup", 'chamions cup', 
    'champs cup', 'champion cup', "champion'scup"],
  'Channel Trophy' => ['channel trpohy'],
  'Cherven Briag National Tournament' => [
    'national tournament cherven briag', 'cherven briag'],
  'Chilean Championship' => ['torneo nacional de chile'],
  'China Elite Tournament' => ['china elite inivitational tournament',
    'china bridge elite tournament'],
  'Czech Championship' => ['czech bridge championship',
    'czech bridge championships'],
  'Czech First League' => ['czech bridge league', 'czech bridge league'],
  'Czech Team Championship' => ['czech team championships',
    'czech teams champ_'],
  'Czech First League' => ['czech 1st league', 'czech bridge league'],
  'Collegiate Bowl' => ['collegiate championship',
    'collegiate championships', 'collegiate champs'],
  'Computer World Championship' => ['computer bridge championship',
    'computer bridge', 'computer world bridge championships'],
  "d'Orsi" => ["d'orsi senior bowl", "d´orsi", 'senior world cup',
    'seniors bowl', 'senior bowl'],
  'Danish Club Teams' => ['danish club team', 'dm klubhold',
    'dm i klubhold', 'dm i knubhold', 'dm i klub hold'],
  'Danish Mixed Pairs' => ['dm mix par'],
  'Danish Pairs Championship' => ['danish championship - open pairs',
    'danish open pairs championship', 'danish open pairs championships',
    'danish championship open pairs'],
  'Danish Teams Championship' => ['danish team champions',
    'danish team championships', 'danish team championship',
    'danish open team', 'danish open teams', 'danish teams',
    'dm hold', 'dmi i klubhold'],
  'Dongming Knock-out Teams' => ['dong ming knockout teams',
    'dong ming knockour teams'],
  'Dr. Heinz von Rotteck Pokal' => ['dr_-heinz-von-rotteck-pokal',
    'v_-rotteck-pokal'],
  'Dutch Meesterklasse' => ['dutch mk'],
  'Egyptian League' => ['egy_league', 'egy-league'],
  'European Bridge Teams Championship' => ['european b.t.ch.',
    'european b_t_ch_', 'e_b_l_ team championships',
    'e_b_l_ teams championship', 'e_b_l team championship',
    'e_b_l_ team champioships'],
  'European Championship' => ['eur champ', 'eur cham', 'champ eur',
    'eur cha'],
  'European Open Bridge Championship' => ['eobc'],
  'European Small Federation Games' => ['ebl small federation trophy',
    'ebl small federations trophy', 'games of small federations',
    'european small federations games', 'small federation games',
    'small federations games', 'small ffederations games',
    'small federation cup', 'european small feds games',
    'small ffederations games'],
  'European Youth Bridge Pairs Championship' => [
    'european youth pairs'],
  'Finnish Pairs Championship' => ['finnish pair championship',
    'finnish pair championships', 'finnish pairs champs',
    'finnish pairs'],
  'Finnish Teams Championship' => ['finnish teams championships',
    'finnish teams', 'finnish team championships'],
  'Forbo Krommenie Teams' => ['forbo-krommonie tourname',
    'forbo-krommenie tournament', 'forbo-krommenietournament',
    'forbo-krommenie international bridge event',
    'international forbo krommenie bridge event',
    'forbo-krommenie tourname'],
  'Forbo Nations Cup' => ['Forbo Teams'],
  'Forest Trophy' => ['forest bridge trophy'],
  'FOSS Grand Tournament' => ['foss grand tourney',
    'foss grand tourament', 'foss grand tournement', 'foos grnad tourn'],
  'French Cup' => ['coupe de france'],
  'FullBridge International Teams' => ['internacional equipos full bridge',
    'internacional full bridge', 'internactional de equipos full bridge'],
  'German Club Cup' => ['german cup', 'vereinspokal'],
  'German Team Championship' => ['deutsche teammeisterschaft'],
  'German Team Trophy' => ['german bridge team trophy',
    'dbv-pokal'],
  'German Women Pairs' => ['damen-paar'],
  'Golden Jubilee' => ['golden jubily'],
  'Grand Prix of Poland' => ['grand prix polski', 'gp of poland',
    'grnd prix of poland', 'grand priix polski'],
  'Grand Prix of Prague' => ['gp prague'],
  'Greek Open Teams' => ['greek open nationa team',
    'greek natioanal teams', 'greek open team championship', 
    'greek open team'],
  "Gro's Supercup" => ["gro's super-cup", 'grocup', 'gros supercup'],
  'Guangdong Club Championship' => ['guang dong club championship',
    'guang dong club bridge championship'],
  'Hellenic Team Championship' => ['hellenic teams championship'],
  'Hong Kong Inter-City' => ['hong kong iner-city'],
  'Icelandair Open' => ['icelandari open'],
  'Icelandic Cup' => ['bikarkeppni bsí'],
  'Icelandic Teams' => ['icelandic teamhampionship'],
  'Indonesian League' => ['indonesian bridge league',
    'indonesia bridge league'],
  'Indonesian National Games' => ['indonesian games',
    'indonesian nasional games'],
  'IOC Grand Prix' => ['ioc grandprix'],
  'Istanbul Winter Teams' => ['istanbul kis dortlu takimlar',
    'istanbul kis dortlu takim'],
  'Italian Team Championship' => ['camp.it.squadre',
    'camp.it. squadre'],
  "Jessheim New Year's Cup" => ['jessheim new years cup',
    'jesshiem new years cup'],
  'Junior Camrose' => ['juniior camrose'],
  'Kalani Trophy' => ['kalani bridge championship'],
  "Kepri Governor's Cup" => ['kepri governor cup', 'kepri cup',
    'kepri governors cup', 'gubernur kepri cup', 'guvernor kepri cup',
    'governor kepri cup'],
  'König Ludwig Cup' => ['koenig ludwig nationen cup'],
  'Krakow Spring' => ['krakowska wiosna'],
  'Lady Milne Trophy' => ['lady milne', 'lady mile'],
  'Lederer Memorial Trophy' => ['lederer memorial'],
  "Linda Stern Women's Teams" => ['linda stern womens teams'],
  'Lüleburgaz Liberation Cup' => ['luleburgaz kurtulus kupasi'],
  'Maccabi Games' => ['maccabi-games'],
  'McConnell Cup' => ['mc connell'],
  'Mohan Sicka Trophy' => ['mohan sicka'],
  'Mondial de Deauville' => ['mondial deauville',
    'mondial barrière deauville', 'mondial barriere deauville',
    'barriere championship deauville', 'mondial de deauille',
    'montial de deauville', 'mondial barrière de deauville'],
  'NN Cup' => ['nn-cup'],
  'Nordic Championship' => ['nordic championships',
    'nordic bridge championship', 'nordic bridge championships'],
  'Nordic Junior Team Championship' => [
    'nordic junior teams championship',
    'nordic junior teams championships'],
  'Nordic Team Championship' => ['nordic bridge team championship'],
  'Northern Greece Regional Championship' => [
    'n_ greece regional championship'],
  'Northern Territory Gold Teams' => ['nt gold teams'],
  'Northern Territory Gold Swiss Pairs' => ['nt gold swiss pairs',
    'nt gold swis pairs'],
  'Norwegian Club Teams' => ['norwegian clubteams championship',
    'norwegian ch ship teams', 'norwegian clubteams ch_ship',
    'norwegian clubteam championship', 'norw premier league'],
  'Norwegian Swiss Teams' => ['nm-monrad-lag', 'nor swiss teams',
    'norwegian swiss team championship'],
  'Olrud Easter Swiss Teams' => ['olrudpaasken monrad lag',
    'olrud paasken monrad lag',
    'olrud swiss teams', 'olrud easter swiss event',
    'olrud easter swiss team'],
  'Olrud Easter Teams' => ['olrudpaasken teams',
    'olrud estern teamevent', 'olrud estern team-event',
    'olrud easter team-event'],
  'Open Catalunya Preferent' => ['open catalunya equips',
    'open cataluña preferent'],
  'Pan Arab Inter-Club Championship' => ['pan arab championship',
    'pan arab inter_club', 'pan arab interclub', 'pan arab inerclub',
    'pan arab inter-club', 'pan arab inter club', 'pan arab iner club'],
  'Pan China Construction Tournament' => [
    'pan china construction tourname'],
  'Patton de Monaco' => ["monaco's patton", 'patton international monaco',
    'patton international monte-carlo',
    'patton international monte carlo', 'patton monte carlo'],
  'Pärnu Summer Invitational Pairs' => [
    'pärnu summer_ invitational pairs_', 
    'parnu summer tournament_ invitatoinal pairs'],
  'Petit Grand Prix van Driene' => ['petit grand prix',
    'grand prix van driene'],
  'Plock District League' => ['plockiej ligi okregowej'],
  'Poddar National Masters' => ['poddar national master',
    'poddar nationals masters', 'podder national masters'],
  'Polish Boys Championship' => ['polish championship boys'],
  'Polish Girls Championship' => ['polish championship girls'],
  'Polish Premier League' => ['polish premiere league',
    'polish league', 'polish premier leuge'],
  'Polish Youngster Teams' => ['kadry juniorów m³odszych'],
  'Pomerania Cup' => ['rozgrywek pucharowych pwzbs'],
  'Portuguese Open Teams' => ['equipas open pt'],
  'PYC Royale' => ['pyc hindu gymkhana royale'],
  'Riga Invites to Jurmala' => ['riga invites', 'latvia invites'],
  'Romanian League' => ['cn echipe', 'c_n_ echipe', 'cn ecgipe'],
  'Rottneros Nordic Cup' => ['rottneros cup'],
  'Ruia Gold Cup' => ['ruia gold'],
  'Ruter 7 Open' => ['ruter7 elitetournament'],
  'Sao Paulo State Championship' => ['s o paulo cup', 'sao paulo champ',
    'sao paulo championship', 'sao paulo champ', 'sao paulo cup',
    'sao paulo state cup', 'são paulo cup', 
    'são paulo state championship'],
  'Sarundajang Cup' => ['the sarundajang cup'],
  'Scottish Cup' => ['scot cup', 'scot cuo'],
  'Senior Camrose' => ['seniors camrose'],
  'Serbian Cup' => ['cup of serbia', 'kub srbije'],
  'Serbian Premier League' => ['serbian premier leaugue',
    'serbian league'],
  'Serbian Team Championship' => ['serbia teams championship',
    'serbian tam championship', 'serbian teams championship',
    'serbianteam championship'],
  'Shenhua Cup' => ['shen hua cup'],
  'Silver Jubilee' => ['siver jubliee'],
  'Slava Cup' => ['cup slava'],
  'South African Championship' => ['south african nationals'],
  'South American Bridge Championships' => ['sabc'],
  'South Zone Championship' => ['southzone championship'],
  'Southeast Asian Games' => ['sea games'],
  'Spanish Teams Championship' => ['campeonato de españa por equipos'],
  'Spring Fours' => ['spring 4s', 'spring foursomes', 'schapirosfs'],
  'Spring Nationals' => ['spring nat', 'spring national', 'spring nats',
    'sping national'],
  'Staszic Pairs Cup' => ['otp puchar grodu staszica'],
  'Summer Monsoon League' => ['summer monsoon'],
  'Summer Nationals' => ['summer national'],
  'Swiss Cup' => ['coupe suisse'],
  'Swiss Championship' => ['champion suisse', 'championnat suisse'],
  'Taiwanese Teams' => ['taiwanese teal'],
  'Teltscher Trophy' => ['teltcher trophy', 'telscher trophy'],
  'TGR Auction Pairs' => ['tgr auction pair', "tgr's auction pairs",
    'tgrs auction pair', 'tgrs auction pairs'],
  'TGR Auction Teams' => ['tgrs auction teams'],
  'TGR Super League' => ["tgr's super league", "tgr's super legue",
    'tgrs league', 'tgrs 2nd auction pairs'],
  'The Hague Bridge Experience' => ['the hague bride experience',
    'teh hague bridge experience'],
  'Thrace Cup League' => ['trakya kulupler ligi'],
  'Tianjin Binhai Cup' => ['tianjin bin hai cup'],
  'Tolani Gold Trophy' => ['dr_tolani gold troph',
    'tolani summer nationals gold', 'tolani summer nationald gold',
    'tolani gold summer nationals', 'tolani gold summar nationals',
    'tolani gold summer national'. 'dr_tolanigoldcup',
    'dr_tolani gold summer nationals'],
  'Tolani Grand Prix' => ['tolani gp', 'tolani grand pix'],
  'Tolani Silver Cup' => ['dr tolani summer nationals silver',
    'dr_tolani open summer nationals silver',
    'dr_tolani silver cup summer national',
    'dr_tolani sliver cup summer nationals'],
  'Torneo di Roma' => ['tornei di roma'],
  'United States Bridge Championship' => ['us bridge championship',
    'u_s_b_c'],
  'United States Women Bridge Championship' => [
    "us women's bridge championship", "us women's bridge championhip"],
  Vanderbilt => ['vanderbilt teams', 'vanderbilt ko teams'],
  'Venice Cup' => ['<venive <cup'],
  'Victorian Pennant' => ['vic pennant'],
  'Vinoble Cup' => ['vinoble open'],
  Wagar => ['wagar teams', "wagar women's", "wagar women's ko"],
  'White House Juniors' => ['whiteouse juniors', 'the white hous juniors',
    'qhite house juniors'],
  'White House Top 12' => ['modalfa top 12'],
  'White House Top 16' => ['white house int. teams top 16',
    'white house int_ teams top 16'],
  'White House Top Circuit' => ['melchemie top circuit',
    'ing bank top circuit', 'ng bank top circuit', 
    'white house topcircuit', 'witte huis topcircuit',
    'the white house topcircuit'],
  'Winter Championships' => ['winter championship',
    'winter championsship'],
  'Winter Nationals' => ['winter national'],
  'Winter Open Teams' => ['winter teams', 'winter team'],
  'World Masters Individual' => ['masters individual',
    'world masters'],
  'World Mind Games' => ['world mind game', 'word mind games', 'wmsg',
    'mind sports games', 'sawmg', 'wmg'],
  'World Team Olympiad' => ['world bridge team olympiad',
    'world bridge olympiad', 'bridge olympiad'],
  'World University Championship' => [
    'world university bridge championship',
    'world university bridge championships',
    'univ_ world champs'],
  'World Youth Congress' => ['youth world bridge congress'],
  'World Youth Teams Championship' => ['world youth team championships'],
  'Yeh Bros Cup' => ['yehbros cup'],
  'Young Chelsea Knock-out' => ['yc ko']
);

my @SINGLE_WORDS = qw(
  Bundesliga
  Camrose Cavendish
  Reisinger
  Rosenblum
  Spingold
  Vadsøturneringen Vanderbilt
  Wagar
);

my %SINGLE_TYPOS =
(
  'ABPF Championships' => ['pabfc'],
  'ASEAN Club Championship' => ['abcc'],
  'Australian National Open Teams' => ['anot'],
  'Bermuda Bowl' => ['bb'],
  "Buffett Cup" => ['buffett', 'buffet'],
  Camrose => ['camroae', 'ccmrose'],
  'Canadian Bridge Championship' => ['cbc'],
  'Canadian National Teams Championship' => ['cntc'],
  'Canadian Seniors Teams Championship' => ['cstc'],
  'Canadian Women Teams Championship' => ['cwtc'],
  Cavendish => ['cavendiish', 'caavendish', 'cavemdish', 'cavendiosh',
    'cavendsh', 'cavvendish', 'avendish', 'cav'],
  'Collegiate Bowl' => ['collegiate', 'collegiates'],
  'Commonwealth Nations Bridge Championships' => ['cnbc'],
  "d'Orsi" => ['dorsi', 'sb', 'dosb'],
  'Dutch Meesterklasse' => ['meesterklasse'],
  'European Bridge Teams Championship' => ['ebtc'],
  "European Champions' Cup" => ['ecc'],
  'European Championship' => ['ec'],
  'European Small Federation Games' => ['esfg'],
  'European University Bridge Championship' => ['eubc'],
  'European Winter Games' => ['ewg'],
  'European Youth Bridge Championship' => ['eybc'],
  'European Youth Bridge Pairs Championship' => ['eybpc', 'eypc'],
  'European Youth Bridge Teams Championship' => ['eytc'],
  'German Team Championship' => ['teammeisterschaft'],
  'Grand National Open Teams' => ['gnot'],
  'Grand Prix of Poland' => ['gpp'],
  'Junior Camrose' => ['juniorcamrose', 'juniorcmrose'],
  'Lederer Memorial Trophy' => ['lederer', 'ledered'],
  "Linda Stern Women's Teams" => ['lswt'],
  'Maccabi Games' => ['maccabiah'],
  'McConnell Cup' => ['mcconnell'],
  'North American Bridge Championship' => ['nabc'],
  'NTU Cup' => ['ntucup'],
  'Olrud Easter Teams' => ['olrudeasterteams'],
  'Peggy Bayer' => ['peggybayer'],
  Qualifying => ['qualification', 'qualifications', 'qualif',
    'qualifier'],
  Reisinger => ['reisiger', 'resisinger'],
  'Rondane Cup' => ['rondanecupen'],
  'Ruia Trophy' => ['ruia'],
  'Southeast Asian Games' => ['seagames'],
  'Summer Nationals' => ['summernationals'],
  'Takamatsu Cup' => ['takamatsu'],
  'Teltscher Trophy' => ['teltschertrophy', 'teltscher'],
  'Tolani Grand Prix' => ['tolanigrandprix'],
  'Transnational Open Teams' => ['tnt', 'tnot'],
  'United States Bridge Championship' => ['usbc'],
  'United States Juniors Bridge Championship' => ['usjbc'],
  'United States Seniors Bridge Championship' => ['ussbc'],
  'United States Women Bridge Championship' => ['uswbc', 'uswbf', 'uswc'],
  Vanderbilt => ['vanderbuilt', 'vanderebilt', 'vandebilt'],
  'Venice Cup' => ['vc'],
  'Victor Champion Cup' => ['vcc'],
  'Victorian Pennant' => ['pennant'],
  'Vilnius Club Pairs' => ['vbk'],
  'Winter Nationals' => ['winternationals'],
  'World Bridge Series' => ['wbs'],
  'World Team Championships' => ['wbtc'],
  'World Team Olympiad' => ['olympiad', 'olympiads'],
  'World University Championship' => ['wuc'],
  'World Youth Bridge Team Championship' => ['wybtc'],
  'World Youth Open Bridge Championship' => ['wyobc', 'wboyc'],
  'World Youth Teams Championship' => ['wytc', 'world youth teams'],
  'Young Chelsea Knock-out' => ['ycko'],
  'Zimmermann Cup' => ['zc']
);


sub set_hashes
{
  my ($method, $key) = @_;

  $method->(\@MULTI_WORDS, \%MULTI_TYPOS,
    \@SINGLE_WORDS, \%SINGLE_TYPOS, $key);
}

1;
