#!perl

use strict;
use warnings;
use v5.10;
use utf8;
use open ':std', ':encoding(UTF-8)';

package Title::Tname;

our @ISA = qw(Exporter);
our @EXPORT = qw(set_hashes);

use lib '.';
use TeamBBO;

my @MULTI_WORDS =
(
  'Altman Swiss Pairs',
  'ASEAN Club Championship',
  'Asia Cup',
  'Australian National Open Teams',
  'Baltic Bowl',
  'Baltic Cup',
  'Baze Senior Knock-out',
  'Bergen Grand Tournament',
  'Bermuda Bowl',
  'Bermuda Triangle Cup',
  'Bobby Evans Seniors Teams',
  'British Gold Cup',
  'Buffett Cup',
  'Canadian National Teams Championship',
  'Canadian Seniors Teams Championship',
  'Canadian Women Teams Championship',
  "Champions' Cup",
  'Channel Trophy',
  'Codan Cup',
  'Collegiate Bowl',
  'Commonwealth Nations Bridge Championships',
  'Computer World Championship',
  "d'Orsi",
  'Egyptian League',
  'European Bridge Teams Championship',
  'European Open Bridge Championship',
  "European Champions' Cup",
  'European Small Federation Games',
  'European Youth Bridge Pairs Championship',
  'EUSA Games',
  'Filbyter Cup',
  'German Club Cup',
  'German Team Championship',
  'German Team Trophy',
  'Golden Jubilee',
  'Grand Prix of Poland',
  'Higson Cup',
  'IMSA Elite Mind Games',
  'Italy Cup',
  'Junior Camrose',
  "Kepri Governor's Cup",
  'Lady Milne Trophy',
  'Lederer Memorial Trophy',
  "Linda Stern Women's Teams",
  'Maccabi Games',
  'McConnell Cup',
  'Nations Cup',
  'Nordic Championship',
  'Palace Cup',
  'Pan Arab Inter-Club Championship',
  'Peggy Bayer',
  'Pesta Sukan',
  'Prince Henrik Trophy',
  'Rondane Cup',
  'Ruia Gold Cup',
  'Sao Paulo State Championship',
  'Sarundajang Cup',
  'Scottish Cup',
  'Senior Camrose',
  'Silver Jubilee',
  'Slava Cup',
  'South American Bridge Championships',
  'South Zone Championship',
  'Southeast Asian Games',
  'Spring Fours',
  'Spring of Cracow',
  'Spring Nationals',
  'Summer Monsoon League',
  'Swiss Cup',
  'Teltscher Trophy',
  'Tornei di Roma',
  'Transnational Open Teams',
  'United States Bridge Championship',
  'United States Seniors Bridge Championship',
  'United States Women Bridge Championship',
  'Vanderbilt Fantasy Challenge',
  'Venice Cup',
  'Victor Champion Cup',
  'Victorian Pennant',
  'Vinoble Cup',
  'World Bridge Series',
  'World Masters Individual',
  'World Men Elite Tournament',
  'World Mind Games',
  'World Team Championships',
  'World Team Olympiad',
  'World Top Tournament',
  'World University Championship',
  'World Youth Open Bridge Championship',
  'World Youth Teams Championship',
  'World Youth Bridge Teams Championship',
  'World Women Elite Tournament'
);

my %MULTI_TYPOS =
(
  'ASEAN Club Championship' => ["asean bridge club c'ship",
    'asean bridge club championship', "asean bridge c'ship",
    'asean bridge club', 'asean bridge club championships',
    'asean bridge cship', 'asean bridge championship',
    'asean bridge club open championships',
    'asean bridg club championship', 'asean bridge championships',
    'asean club championships'],
  'Baze Senior Knock-out' => ['baze senior ko', 'baze sr_ ko',
    'base sr ko', 'baze sr_ ko'],
  'Bergen Grand Tournament' => ['bergen open', 'bergen stor',
    'bergen storturnering'],
  'Bermuda Triangle Cup' => ['bermuda triangle teams cup'],
  'British Gold Cup' => ['gold cup'],
  'Buffett Cup' => ['buffet cup', 'bufett cup'],
  Camrose => ['camrose trophy'],
  "Champions' Cup" => ['champions cup', "champion's cup", 'chamions cup', 
    'champs cup', 'champion cup'],
  'Channel Trophy' => ['channel trpohy'],
  'Collegiate Bowl' => ['collegiate championship',
    'collegiate championships', 'collegiate champs'],
  'Computer World Championship' => ['computer bridge championship',
    'computer bridge', 'computer world bridge championships'],
  "d'Orsi" => ["d'orsi senior bowl", "d´orsi", 'senior world cup',
    'seniors bowl', 'senior bowl'],
  'Egyptian League' => ['egy_league', 'egy-league'],
  'European Open Bridge Championship' => ['eobc'],
  'European Small Federation Games' => ['ebl small federation trophy',
    'ebl small federations trophy', 'games of small federations',
    'european small federations games', 'small federation games',
    'small federations games', 'small ffederations games',
    'small federation cup', 'european small feds games'],
  'German Club Cup' => ['german cup'],
  'German Team Championship' => ['deutsche teammeisterschaft'],
  'German Team Trophy' => ['german bridge team trophy'],
  'Golden Jubilee' => ['golden jubily'],
  'Grand Prix of Poland' => ['grand prix polski', 'gp of poland'],
  'Junior Camrose' => ['juniior camrose'],
  "Kepri Governor's Cup" => ['kepri governor cup', 'kepri cup',
    'kepri governors cup', 'gubernur kepri cup', 'guvernor kepri cup'],
  'Lady Milne Trophy' => ['lady milne'],
  'Lederer Memorial Trophy' => ['lederer memorial'],
  "Linda Stern Women's Teams" => ['linda stern womens teams'],
  'Maccabi Games' => ['maccabi-games'],
  'McConnell Cup' => ['mc connell'],
  'Nordic Championship' => ['nordic championships',
    'nordic bridge championship', 'nordic bridge championships'],
  'Pan Arab Inter-Club Championship' => ['pan arab championship',
    'pan arab inter_club', 'pan arab interclub', 'pan arab inerclub',
    'pan arab interclub', 'pan arab inter-club'],
  'Sao Paulo State Championship' => ['s o paulo cup', 'sao paulo champ',
    'sao paulo championship', 'sao paulo champ', 'sao paulo cup',
    'sao paulo state cup', 'são paulo cup', 
    'são paulo state championship'],
  'Sarundajang Cup' => ['the sarundajang cup'],
  'Scottish Cup' => ['scot cup', 'scot cuo'],
  'Senior Camrose' => ['seniors camrose'],
  'Silver Jubilee' => ['siver jubliee'],
  'South American Bridge Championships' => ['sabc'],
  'South Zone Championship' => ['southzone championship'],
  'Southeast Asian Games' => ['sea games'],
  'Spring Fours' => ['spring 4s', 'spring foursomes', 'schapirosfs'],
  'Spring Nationals' => ['spring nat', 'spring national'],
  'Summer Monsoon League' => ['summer monsoon'],
  'Swiss Cup' => ['couple suisse'],
  'Teltscher Trophy' => ['teltcher trophy'],
  'United States Bridge Championship' => ['us bridge championship',
    'u_s_b_c'],
  Vanderbilt => ['vanderbilt teams', 'vanderbilt ko teams'],
  'Venice Cup' => ['<venive <cup'],
  'Victorian Pennant' => ['vic pennant'],
  'Vinoble Cup' => ['vinoble open'],
  Wagar => ['wagar teams', "wagar women's", "wagar women's ko"],
  'World Masters Individual' => ['masters individual',
    'world masters'],
  'World Mind Games' => ['world mind game', 'word mind games', 'wmsg',
    'mind sports games', 'sawmg', 'wmg'],
  'World Team Olympiad' => ['world bridge team olympiad',
    'world bridge olympiad', 'bridge olympiad'],
  'World University Championship' => [
    'world university bridge championship',
    'world university bridge championships',
    'univ_ world champs']
);

my @SINGLE_WORDS = qw(
  Bundesliga
  Camrose Cavendish
  Reisinger
  Rosenblum
  Spingold
  Vanderbilt
  Wagar
);

my %SINGLE_TYPOS =
(
  'ASEAN Club Championship' => ['abcc'],
  'Australian National Open Teams' => ['anot'],
  'Bermuda Bowl' => ['bb'],
  "Buffett Cup" => ['buffett', 'buffet'],
  Camrose => ['camroae', 'ccmrose'],
  'Canadian National Teams Championship' => ['cntc'],
  'Canadian Seniors Teams Championship' => ['cstc'],
  'Canadian Women Teams Championship' => ['cwtc'],
  Cavendish => ['cavendiish', 'caavendish', 'cavemdish', 'cavendiosh',
    'cavendsh', 'cavvendish', 'avendish'],
  'Collegiate Bowl' => ['collegiate', 'collegiates'],
  'Commonwealth Nations Bridge Championships' => ['cnbc'],
  "d'Orsi" => ['dorsi', 'sb', 'dosb'],
  'European Bridge Teams Championship' => ['ebtc'],
  "European Champions' Cup" => ['ecc'],
  'European Youth Bridge Pairs Championship' => ['eybpc', 'eypc'],
  'German Team Championship' => ['teammeisterschaft'],
  'Junior Camrose' => ['juniorcamrose', 'juniorcmrose'],
  'Lederer Memorial Trophy' => ['lederer', 'ledered'],
  'Maccabi Games' => ['maccabiah'],
  'McConnell Cup' => ['mcconnell'],
  'Peggy Bayer' => ['peggybayer'],
  Qualifying => ['qualification', 'qualifications', 'qualif',
    'qualifier'],
  Reisinger => ['reisiger', 'resisinger'],
  'Rondane Cup' => ['rondanecupen'],
  'Teltscher Trophy' => ['teltschertrophy'],
  'Transnational Open Teams' => ['tnt', 'tnot'],
  'United States Bridge Championship' => ['usbc'],
  'United States Seniors Bridge Championship' => ['ussbc'],
  'United States Women Bridge Championship' => ['uswbc'],
  Vanderbilt => ['vanderbuilt', 'vanderebilt', 'vandebilt'],
  'Venice Cup' => ['vc'],
  'Victor Champion Cup' => ['vcc'],
  'Victorian Pennant' => ['pennant'],
  'World Bridge Series' => ['wbs'],
  'World Team Championships' => ['wbtc'],
  'World Team Olympiad' => ['olympiad', 'olympiads'],
  'World University Championship' => ['wuc'],
  'World Youth Bridge Team Championship' => ['wybtc'],
  'World Youth Open Bridge Championship' => ['wyobc', 'wboyc'],
  'World Youth Teams Championship' => ['wytc']
);


sub set_hashes
{
  my ($method, $key) = @_;

  $method->(\@MULTI_WORDS, \%MULTI_TYPOS,
    \@SINGLE_WORDS, \%SINGLE_TYPOS, $key);
}

1;
