#!perl

use strict;
use warnings;
use v5.10;
use utf8;
use open ':std', ':encoding(UTF-8)';

package Tags::Club;

our @ISA = qw(Exporter);
our @EXPORT = qw(set_hashes);

my @MULTI_WORDS =
(
  '1. Wiesbadener BC',
  '4 Jacks',
  "'t Onstein",
  'Aachener BC',
  'ABB BK',
  'ABC Freiburg',
  'AC Pajace',
  'Acol Praha',
  'Adalar SK',
  'Adapazan Briç SK',
  'Agriculture Bridge Club',
  'Akademia Brydza',
  'Akademisk Bridgeklub',
  'Akceþme Spor',
  'Akhisar BS',
  'ALBC Nganjuk',
  'Alert Plovdiv',
  'Aliaga BSK',
  'Alta BK',
  'Altay SK',
  'Altea Bridge',
  'Altin Kayisi BSK',
  'Altinay SK',
  'Altinova SK',
  'Alunand BC',
  'Alumni Club Chennai',
  'Amed Sportif',
  'Anadolu Bridge Club',
  'Annecy BC',
  'Anka BK',
  'Ankara Kontrat',
  'Ankara RBB',
  'Ankara Sistematik',
  'Antalya BSK',
  'Antalya Tabip Odasi',
  'Antony BC',
  'Arendals BK',
  'Arkas SK',
  'Armando and Viviane Gonçalves Pereira',
  'ASA University of Tel Aviv',
  'ASB Pisa',
  'ASB Salerno',
  'ASD Reggio Emilia',
  'ASD Tennis Roma',
  'ASD Villa Fabbriche',
  'Aso Pika',
  'Associação de Bridge da Madeira',
  'Atakoy BSK',
  'Atakum Club',
  'Atasehir BK',
  'Atletik Basket',
  'ATU Bucharest',
  'Augsburg Augusta',
  'Auguri Warsaw',
  'Auram BSKD',
  'Avalanche BC',
  'AVI Club Noida',
  'Avrasya SK',
  'Aydin 1923 BBSK',
  'Aydin Idman Yurdu',
  'AZS Wratislawia',
  'Babaeski BSK',
  'Bahcesehir Club',
  'Bajnok Bridzs Egyesület',
  'Bakýrköy Briç SK',
  'Balai Pelaksanaan Jalan Nasional',
  'Balikesir BSK',
  'Ballerup BC',
  'Bangkok Bridge Club',
  'Banik Havirov',
  'BASEK BK',
  'Baþkent Sekans BSK',
  'Baragnon BC',
  'Batikent BK',
  'Batman Genclik',
  'Bayrampaþa Club',
  'Beijing Baxi Football',
  'Bergen Akademiske',
  'Blakset Klubberne',
  'BC 52 Berlin',
  'BC Alert Mannheim',
  'BC Athens',
  'BC Bamberger Reiter',
  'BC Barcelona',
  'BC Bielefeld',
  'BC Bonn',
  'BC Braila',
  'BC Brasov',
  'BC Bremen',
  'BC Brotteaux',
  'BC Burghausen',
  'BC Chelopech',
  'BC Clichy',
  'BC Courseulles',
  'BC Darmstadt Alert',
  "BC de la Côte d'Amour",
  'BC de Lille',
  'BC de Lombard',
  'BC de Zeerob',
  'BC Deauville',
  'BC Deva',
  "BC Djeun's",
  'BC Garches',
  'BC Herkules',
  'BC Iasi',
  'BC Karo 10 Böblingen',
  'BC Ketsch',
  'BC Kiel',
  'BC Leipzig',
  'BC Les Templiers',
  'BC Lozenets',
  'BC Massy',
  'BC Milano',
  'BC Modalfa',
  'BC München',
  'BC München-Ottobrunn',
  'BC Oldenburg',
  'BC Osnabrück',
  'BC Real',
  'BC Rennais',
  'BC Saarbrücken 1984',
  'BC Saint Honoré',
  'BC Schwäbisch Hall',
  'BC Star',
  'BC Stuttgart',
  'BC Sudovia',
  'BC Tofas',
  'BC Tomohon',
  'BC Trieste',
  'BC Universität Mannheim',
  'BC Varna',
  'BCN Almirall',
  'Bengkalis PT BSP',
  'BH Koru BK',
  'Bhinneka Bridge Club',
  'BI Veneto',
  'Bielski Klub Brydżowy GOK cards',
  'BK2000',
  'BK 1936',
  'BK 83 Slagelse',
  'BK Alert Täby',
  'BK Asenovgrad',
  'BK Björken',
  'BK Everfresh',
  'BK Fyris Skalman',
  'BK Grand',
  'BK Hebros',
  'BK Lavec Smile',
  'BK Lyx',
  'BK Missklikk',
  'BK Nord',
  'BK Norrøna',
  'BK Sigulda',
  'BK Smolyan',
  'BK Svanslös Skalman',
  'Blue BC',
  'Bodrum BSK',
  'Bodø BK Lyn',
  'Borivli Sports Club',
  'Bornova BSK',
  'BP Batam',
  'Brevik BK',
  'Bridge Académie Toulouse',
  'Bridge Addaura',
  'Bridge am Grün',
  'Bridge Bologna',
  'Bridge Contact Club',
  'Bridge House',
  'Bridge Turó',
  'Bridge Tunas Cahaya',
  'Bridgeclub Oog',
  'Bridgekameratene',
  'Brussels Bridge Club',
  'Bombay Gymkhana Club',
  'Bozdogan Club',
  'BSB Kurek Ihtisas',
  'BTC Dortmund',
  'BTSC Hannover',
  'Buca Sports',
  'Bucak Bel.',
  'Bridge Center of Buffalo',
  'BUKS Bytom',
  'Bursa BSK',
  'Büyük Kulüp',
  'BV Waldsolms',
  'Båsmo BK',
  'Caen BC',
  'Calcutta Bridge Club',
  'Calcutta Cricket & Football Club',
  'Camlica Sports',
  'Canakkale Tarim',
  'Canottieri Olona',
  'Çayyolu BK',
  'CB Baleal',
  'CB São Miguel',
  'Cedýt Ilica Sports',
  'Centro Desportivo Universitário do Porto',
  'Centrum Kultury i Sportu Oze',
  'Centrum Kultury i Sportu Skawina',
  'Cercle de la Cité',
  'Cercle Tourangeau',
  'Cerkezkoy SK',
  'Cerkezkoy Dinamik BSK',
  'CFT Bridge',
  'Cherno More',
  'Cimentas Club',
  'Circolo del Bridge Cannareggio',
  'Circolo del Bridge Firenze',
  'Circolo del Bridge N. Ditto Reggio Calabria',
  'Circolo del Tennis Palermo',
  'Circolo del Bridge Venezia',
  'Circolo Nautico Posillipo',
  'Círculo Português de Bridge',
  'CK Zyrardow',
  'Clube de Bridge dos Engenheiros',
  'Clube de Tiro & Sport',
  'Clube Naval São Vicente',
  'Colonial BC',
  'Corlu Avrasya',
  'Corlu Yildiz',
  'Cracovia 1906',
  'Crvena Zvezda',
  'Dabrowka WZBS',
  'Dalaman SK',
  'Datca SK',
  'DBK Dalom',
  'Debrecen DEAC',
  'Deccan Club',
  'Delhi Gymkhana Club',
  'Devrek BK',
  'Diyarbakýr Sur BSK',
  'Dombivli BC',
  'Dorost Havirov',
  'Dörtyol SK',
  'Drammen Arbeiderparti',
  'Dubai Bridge Club',
  'Dýcle Gençlýk',
  'EBC Solok',
  'Edirne GSK',
  'Ege Club',
  'EIBC Bandung',
  'EIBC Jakarta',
  'Ekol BSK',
  'El Ahly',
  'El-Karma',
  'El Rabwa Club',
  'El Shams Club',
  'Elmadag BSK',
  'Ergene GSK',
  'ESBS Elblag',
  'Eskisehir Adalar',
  'Eskisehir Baðlar',
  'Eskisehir Sports',
  'Essen 86',
  'Estonian Sports Association',
  '7 Eylül SK',
  'Fakultas Teknik Bridge Club Universitas Tanjungpura',
  'Fatih Karagümrük SK',
  'Fethiye BSK',
  'Field Club Udaipur',
  'Fjends BK',
  'Flekkefjord BK',
  'Foca Club',
  'Fosnavåg BK',
  'Fram Larvik',
  'Frankfurter TBC',
  'Friedland BC',
  'Fukien Athletic Club',
  'Førde BK',
  'Gabrial University of Indonesia',
  'Gabungan Bridge Bandung',
  'Gabungan Bridge Kota Tasikmalaya',
  'Gala Tawa Bridge Club',
  'Ganesha Bridge Club',
  'GB Cimahi',
  'Genclerbirligi SK',
  'Gereja Masehi Injili di Minahasa',
  'Geyve Sports',
  'Gjøvik og Vardal BK',
  'Goztepe Hilal SK',
  'Göktürk SK',
  'Gölcük Club',
  'Grant Thornton',
  'GSD Club',
  'Guangdong Club',
  'Gudbrandsdal BK',
  'Gümüşlük SK',
  'Haderslev BC',
  'Hamar BK',
  'Hamra Club',
  'Hanseatic Hamburg BC',
  'Harlequins BC',
  'Harplinge BK',
  'Harstad S&B',
  'Hedemora Kingen',
  'Heimdal BK',
  'Hendek Kazimiye',
  'Herning BK',
  'Hetman Bialystok',
  'Heybeliada SK',
  'Hidropaks Gebze Tayfun SK',
  'Hillerød BK',
  'Hindusthan Club',
  'Hok Studiecentrum',
  'Hornbæk BK',
  'IBM SK',
  'Icel Sports',
  'Idman Ocagi SK',
  'IKA ITS',
  'Incirli SKD',
  'Iskenderun IHS',
  'Isparta Club',
  'Istanbul Sports',
  'Izmir BSB',
  'Jaipur Club',
  'Jakarta BBG',
  'Jessheim BK',
  'Jinshuo Club',
  'Jomtien Bridge Club',
  'Jordan Club',
  'Jubilee Hills International Centre',
  'Kadikoy BSK',
  'Kadirli Akil Oyunlari Merkezi',
  'Kao Hsiung Club',
  'Kapakli Sýte',
  'Karadeniz SK',
  'Karimata BC',
  'Karlsruher BSC',
  'Karsiyaka BSK',
  'Kartal Club',
  'Kastamonu BSK',
  'KDI Moradabad',
  'KDK Kutno',
  'Kemalpasa Club',
  'Kerukunan Keluarga Kawanua',
  'King Hussein Club',
  'Kirklarelý BSK',
  'Klepp BK',
  'Klør 10 Vejle',
  'Kocaeli BSSK',
  'Kocamustafapasa SK',
  'Konak Club',
  'Konga BK',
  'Konkret Kasztelan',
  'Konnerud BK',
  'Konya BK',
  'Kontra Koszalin',
  'Kontri Bialystok',
  'Kota Club',
  'Koycegiz BSK',
  'Köln Lindenthal BC',
  'Kragerø BK',
  'Kristiansand BK',
  'KS Tecza',
  'KSB Radkov',
  'Kucukbakkalkoy SK',
  'Kucukcekmece BK',
  'Kultcamp Rieneck',
  'Kunshan Qiaoxie',
  'Küp BSK',
  'Kurtulus SK',
  'Kusadasi BSK',
  'Laksamana BSP',
  'Laodikya SK',
  'Larvik og Horten BK',
  'Lebanon Club',
  'Legia Kosice',
  'Levski Sofia',
  'Lindesbergs BS',
  'Lisbon Bridge Association',
  'Ludvikabygdens BK',
  'Luleburgaz SK',
  'Lyngdal/Farsund',
  'M le Bridge',
  'Madras Gymkhana Club',
  'Maesa Palu',
  'Major Hosgoru',
  'Majör Boğaziçi',
  'Makassar Utama',
  'Makkabi Köln',
  'Malatya BSK',
  'Malatya Yildiz Dogu',
  'Malmö BK Scania',
  'Manado Convention Center',
  'Manisa BSK',
  'Manna Bridge Club',
  'MBC Kinali',
  'MBC Mampang',
  'Mersin Club',
  'Meski Club',
  'Midt-Telemark BK',
  'Midyat Club',
  'Milan CPK Milanowek',
  'Milas Club',
  'Moss BK',
  'Mudanya GSK',
  'Muðla GSK',
  'Muratpasa Club',
  'Mustang Semarang',
  'München Sanzatu',
  'Møre og Romsdal',
  'NDC Den Hommel',
  'Nachteulen Leverkusen',
  'Nagbagan Card Club',
  'Nagari Club',
  'Namsos BK',
  'Nancy Jarville BC',
  'Narlidere Club',
  'Narvik BS',
  'Nauka Brydza',
  'Nazilli BBSK',
  'Nesodden BK',
  'Näsby BS',
  'NDBAC Nashik',
  'Nilüfer Bld. BSK',
  'Niski Bridge Club',
  'Norrorts Bridge',
  'NS-1',
  'Núcleo De Bridge Do Círculo',
  'Nuovo Bridge Insieme',
  'Nürnberg Museum',
  'Nya Bridgeskolan',
  'Nærbø BK',
  'Næstved BK',
  'Nøtterøy BK',
  'OAZA Kornik',
  'OBK Kløverknekt',
  'Ocean BC',
  'Odense BK',
  'Odisha Secretariat Recreation Club',
  'Ogndal BK',
  'One Eyed Jacks',
  'Ordu BSK',
  'Orhangazi SK',
  'Orthodoxi BC',
  'Otters Club',
  'Osir Lidzbark Warmiński',
  'PAB Michalowo',
  'Padova Bridge SS',
  'Palcan Bridge ASD',
  'Pamukkale SK',
  'Paris Bridge',
  'Paris Country Club',
  'Paris Sud',
  'Pattaya BC',
  'Pärnu BK',
  'Pazar SK',
  'Pelatda DKI',
  'Pelikaanhof All Stars',
  'Pelitli SK',
  'Pescara Bridge',
  'Pertamina BC',
  'Phoenix Oltenita',
  'Piast Mosir Sieradz',
  'Porto Club',
  'Pria/Kaum Bapa Sinode MMIM',
  'Pudong Club',
  'Rabwa Club',
  'Resegone LC',
  'Royal Air Force Club',
  'Rubbestadneset BK',
  'Ruch AZS',
  'Qadesia Club',
  'Qi Zhong Club',
  'Quantum BC',
  'RAL Poznan',
  'Payoon Bridge',
  'RBSC Polo Club',
  'Romana Bridge',
  'Royal Selangor Club',
  'Ruch SA',
  'Rumah Sakit Umum Daerah Pekanbaru',
  'Rødovre BK',
  'Salmun BC',
  'Samsun BK',
  'Sancaktar GSK',
  'Sariyer BSK',
  'SDK Tczew',
  'Seferihisar Municipality',
  'Sekolah Bridge Tonaas Wangko',
  'Semen Padang',
  'Senigallia Club',
  'Shanxi Club',
  'Shaoguan BA',
  'Sharja Club',
  'Shemokh Club',
  'Shooting Club',
  'Shou Chuang',
  'Sidoarjo BC',
  'Silicon Valley Youth Bridge',
  'Silifke SK',
  'Singsås BK',
  'Siwo Persatuan Wartawan Indonesia',
  'Sirinyer Sports',
  'SK Karo',
  'Skara BS',
  'Ski BK',
  'Slem Bric SK',
  'Smedstadens BK',
  'S:t Erik',
  'Sortland BK',
  'Söke BSK',
  'Spar K',
  'SPG Club',
  'Sport Clube Alberto Sousa',
  'Sporting Lisbon',
  'SPS Eko Rozanka',
  'SSD Angelini Bridge',
  'St Eskil',
  'Star Bridge Roma',
  'Stavanger BK',
  'Steinkjer BK',
  'Storeslemmen',
  'Storsjöbygdens BK',
  'Studentenes BK',
  'Suleymanpasa Club',
  'Suzhou Qiaoxie',
  'Sunndalsøra BK',
  'Swara Kita BS',
  'Szlem Barlinek',
  'Szlem Gdansk',
  'Sølvknekt BK',
  'Sørreisa BK',
  'Taskopru Club',
  'Täby BK',
  'TB Silesia Gliwice',
  'Tekirdað Club',
  'Tennis Club Parioli',
  'The West End Mumbai',
  'Tire BSK',
  'Top Bridge BC',
  'Torino Allegra',
  'Toulouse BC',
  'Trabzon Club',
  'Tromsø BK',
  'TSS Surabaya',
  'Tunaras SK',
  'UAE Club',
  'Ullensaker Kisa',
  'Ulusal Folklor GSKD',
  'Underberg BC',
  "Universita' del Bridge",
  'Usak SK',
  'Uzunköprü SK',
  'Van Bric SK',
  'Vasa BK',
  'Vefa SK',
  'Vestel SK',
  'Vestvågøy SK',
  'Vikersund BK',
  'Visnelik Club',
  'Wadi Degla',
  'Wawa Brydz',
  'Willingdon Sports Club',
  'Witte Huis',
  'WCG Mumbai',
  'Yalikavak SK',
  'Yarborough Fritzlar',
  'Yarimca SK',
  'Yatagan SK',
  'Yeni Pelitli SK',
  'Yenisehir BSK',
  'Yesilgiresun SK',
  'Yildirim YSK',
  'Young Chelsea Bridge Club',
  'Young Sharks',
  'Zeugma SK',
  'Zhong Jian Club',
  'Zonguldak BSK',
  'Zurich Enge',
  'Østfold og Follo',
  'Øvre Ottadalen',
  'Överum BK',
  'Åkirkeby BK',
  'Århus BK',
  'Åsane BK'
);

my %MULTI_TYPOS =
(
  'Aachener BC' => ['aachener bc 1953'],
  'ABA Mumbai' => ['aba - mumbai', 'aba-mumbai'],
  'ABB BK' => ['abb bk topbridge'],
  'Acol Praha' => ['bk praha'],
  'Adalar SK' => ['adalar spor'],
  'Adana BSB' => [
    'adana b. shr bld', 
    'adana b.seh bel',
    'adana b.s.k', 
    'adana bþbký',
    'adana bric sk', 
    'adana bsb sk', 
    'adana bsbkisk', 
    'adana buyuksehir', 
    'adana demirspor',
    'adana silem bsk',
    'adana sk'], 
  'Adapazan Briç SK' => ['ada bric'],
  'Agriculture Bridge Club' => ['a g b c'],
  'Akademisk Bridgeklub' => ['akademisk bk'],
  'Akceþme Spor' => ['akceþmespor', 'Akcesme Spor Kulubu',
    'Akçeþme Spor Kulübü'],
  'Alexandria Sporting Club' => ["alexandria sport' c", 'sporting club'],
  'Altay SK' => [
    'Altay GSK',
    'Altay GSKD', 
    'Altay SDGSK',
    'Altay SDGSKD',
    'Altay SKD',
    'Altay Sosyal GSKD'], 
  'Altin Kayisi BSK' => ['altin kayisi'],
  'Altinay SK' => ['altýnay sk'],
  'Altinova SK' => ['altinova mah. ggsk',
    'altinova spor'],
  'Alumni Club Chennai' => ['alumni club'],
  'Alunand BC' => ['alunand bridge club'],
  'Amed Sportif' => ['amed sk'],
  'Anadolu Bridge Club' => ['anadolu briç', 'anadolu bk',
    'anadolu bjk', 'anadolu bric kulubu'],
  'Anka BK' => [
    'anka bric', 
    'anka bskd'],
  'Ankara RBB' => [
    'angora bsk',
    'angora bric spor',
    'ankara bric kulubu', 
    'ankara bric spor',
    'ankara rbb club', 
    'ankara rrb club',
    'ankara ruzgari'],
  'Ankara Sistematik' => ['sistematik bk'],
  'Antakya BSK' => [
    'antakta bric',
    'antakya bskd',
    'antakya spor'],
  'Antalya BSK' => [
    'noname ant.', 
    'ant bric ihtisas sk',
    'antalya b.s.k', 
    'antalya bric ihtisa',
    'antalya bric sk',
    'antalya bric ihtis',
    'antalya bric ihtis.',
    'antalya bric klb', 
    'antalya briç ýsk', 
    'antalya brýç spor', 
    'antalya halk egit.',
    'antalya halk egt.',
    'antalya hesk', 
    'antalya sk'],
  'ASB Pisa' => ['ass.bridge pisa'],
  'ASD Reggio Emilia' => ['bridge reggio emili'],
  'ASD Villa Fabbriche' => ['villa fabbiche'],
  'Atakoy BSK' => [
    'Atakoy Bric SK', 
    'Atakoy BK', 
    'Atakoy BSKD', 
    'Ataköy BSKD',
    'Ataköy BSK'],
  'Atasehir BK' => ['atasehir bric', 'atasehýr brýç kulüb'],
  'ATU Bucharest' => ['atu bucuresti', 'atomic bucuresti',
    'atomic pom', 'atomic p.o.m'],
  'Auram BSKD' => ['auram brýc', 'auram sk'],
  'Avrasya SK' => ['Avrasya Spor', 'Avrasya Spor KB'],
  'Aydin 1923 BBSK' => [
    'aydin 1923 sk', 
    'aydin bbsk',
    'aydin bilimsel', 
    'aydin bilimsel bk', 
    'aydin bilimsel bsk', 
    'aydin buyuksehir',
    'aydinspor 1923', 
    'aydin 1912'],
  'Aydin Idman Yurdu' => ['aydin idmanyurdu sk'],
  'AZS Wratislawia' => [
    'asz wratislavia', 
    'azs wratilavia',
    'ks azs wratislavia'],
  'Babaeski BSK' => ['babaeskispor bsk'],
  'Bahcesehir Club' => [
    'Bahcesehir SK',
    'Bahçeþehýr Brýç'],
  'Bajnok Bridzs Egyesület' => ['bbe hungary', 'bbe p.s.'],
  'Bakýrköy Briç SK' => [
    'bakirkoy incirli',
    "bakirkoy ssd",
    'bakirkoy su',
    "bakirkoy su skd",
    'bakirkoy su sporlar',
    "bakirköy su sporlar",
    'bakýrköy su sporlar'],
  'Balai Pelaksanaan Jalan Nasional' => ['bpjn xi'],
  'Balikesir BSK' => ['balikesýr brýç ihti'],
  'Baþkent Sekans BSK' => [
    'baþkent sekans',
    'baskent sekans', 
    'baskent sekans bric'],
  'BASEK BK' => ['basek bric'],
  'Batikent BK' => ['batikent b.k'],
  'Batman Genclik' => ['batman gençlýk'],
  'Bayrampaþa Club' => ['Bayrampaþa ABSK'],
  'Blakset Klubberne' => ['blakset-klubberne'],
  'BC Alert Mannheim' => ['bc mannheim', 'alert mannheim'],
  'BC Athens' => ['athens bridge club'],
  'BC Bamberger Reiter' => ['bc bamberg', 'bamberger reiter',
    'bamberg cavaliers', 'bamberger germany', 'bamberger welle', 
    'bamberg riders', 'bc bamberger reite', 'bridgeclub bamberge'],
  'BC Brotteaux' => ['brotteaux bc'],
  'BC Clichy' => ['bc de clichy', 'clichy sbc'],
  "BC de la Côte d'Amour" => ["BC dela Côte d'Amou"],
  'BC de Lombard' => ['the lombard', 'de lombard', 'lombard bc'],
  'BC Darmstadt Alert' => [
    'bc alert darmstadt',
    'darmstadt alert'],
  'BC Deauville' => ['deauville bc'],
  "BC Djeun's" => ["djeun's club"],
  'BC Garches' => ['b.c de garches'],
  'BC Herkules' => ['bk herkules', 'bk hercules'],
  'BC Karo 10 Böblingen' => ['bc karo 10 böbling'],
  'BC Lozenets' => ['b lozenetz', 'bc lozenetz', 'vs lozenets'],
  'BC Milano' => ['b.c. milano', 'cbc milano', 'bc mi', 'bc. mi'],
  'BC München' => ['munchen i'],
  'BC München-Ottobrunn' => ['bc münchen-ottobru'],
  'BC Osnabrück' => ['bc osnabrück e.v.'],
  'BC Real' => ['bridge club real'],
  'BC Rennais' => ['b.c. rennais', 'b.c rennais'],
  'BC Sudovia' => ['bc sudovia inter'],
  'BC Tofas' => ['tofas skd'],
  'BC Universität Mannheim' => ['bc uni mannheim'],
  'BC Varna' => ['bc briz varna'],
  'BCN Almirall' => ['bcn-almirall', 'bcn - almirall'],
  'Bengkalis PT BSP' => ['pt bsp', 'bengkalis pt'],
  'Bergen Akademiske' => [
    'begen ak', 
    'bergen abk', 
    'bergen ak', 
    'bergen ak bk',
    'bergen akad', 
    'bergen akadem',
    'bergen akadem bk',
    'bergen akademisk',
    'bergen akademiskebk'], 
  Besiktas => ['besiktas jk'],
  'Bhinneka Bridge Club' => [
    'bhinneka bridge clu',
    'bhineka bridge club', 
    'bhineka garuda',
    'bhinneka fc', 
    'bhinneka garuda',
    'bhinneke bridge clu',
    'garuda bc',
    'garuda bridge club'],
  'BI Veneto' => ['bi-veneto'],
  'Bielski Klub Brydżowy GOK cards' => ['gok-cards bielsk',
    'gok-ard bielsk'],
  'BK 83 Slagelse' => ['bridge 83'],
  'BK Björken' => ['bk bjorken'],
  'BK Everfresh' => ['everfresh bk'],
  'BK Fyris Skalman' => ['skalman bk fyris'],
  'BK Sigulda' => ['sigulda bk'],
  'BK Svanslös Skalman' => ['bk svanslos skalman'],
  'BK Lavec Smile' => ['bk lavec - smile', 'lavec smile',
    'smile bk lavec', 'bk lavek smile', 'bk lavec', 'enjoy bk lavec'],
  'Bodrum BSK' => ['bodrum b.s.k.', 'bodrum bric kulubu', 'bodrum bc',
    'bodrum bric sk'],
  'Bodø BK Lyn' => ['bodø lyn'],
  'Bogazici BSK' => ['bogaz ici bsk', 'boðazici bsk', 'boðazýçý bsk',
    'boðazýçý s.k.', 'bogazici bsk'],
  'Bombay Gymkhana Club' => ['bombay gym', 'bomay gym'],
  'Borivli Sports Club' => [
    'borivali sports', 
    'Borivali Sports C', 
    'borivali s c',
    'borivali sc',
    'borivalli spor'],
  'Bornova BSK' => ['bornova bel. spor', 'bornova bbsk',
    'bornova bilimsel', 'bornova bbk'],
  'Bozdogan Club' => ['bozdogan bld'],
  'Bridge Académie Toulouse' => ['b.academie toulouse', 
    'bridge academie toulouse', 'bridge académie', 'bridge academie'],
  'Bridge Addaura' => [
    'bridge addaura as',
    'bridge addaura sd',
    'bridge addaura asd'],
  'Bridge am Grün' => ['bridge am gruen'],
  'Bridge House' => ['b.house', 'b. house'],
  'Bridge Turó' => ['b. turó', 'b.turó', 'b.turo'],
  'Bridgeclub Oog' => ['bc oog in al'],
  'Brussels Bridge Club' => ['b.c.o.b.', 'brussels bridge cl'],
  'Buca Sports' => ['buca belediye', 'buca spor'],
  'BUKS Bytom' => ['buks ii bytom'],
  'Bursa BSK' => ['bursa bric skd'],
  'Büyük Kulüp' => ['buyuk kulup'],
  'Caen BC' => ['caen b.c'],
  'Calcutta Bridge Club' => ['c b c'],
  'Calcutta Cricket & Football Club' => ['cc&fc', 'cc & fc', 'cc &fc',
    'calcutta bridgeclub'],
  'Canakkale Tarim' => ['canakkale tarim sp', 'ckale besiktaslilar'],
  'Çayyolu BK' => [
    'cayyolu bc',
    'cayyolu bk', 
    'cayyolu bric spor', 
    'cayyolu briç skd', 
    'cayyolu bridge club', 
    'cayyolu bsk',
    'cayyolu bskd',
    'çayyolu briç skd', 
    'çayyolu bsk'],
  'Cedýt Ilica Sports' => ['cedýt ilica spor'],
  'Centrum Kultury i Sportu Oze' => ['oze ckis'],
  'Centrum Kultury i Sportu Skawina' => ['ckis skawina', 'ckis skawia'],
  'Cercle de la Cité' => ['cercle de la cite'],
  'Cerkezkoy Dinamik BSK' => [
    'cerkezkoy bs', 
    'cerkezkoy bsk',
    'cerkezkoy dinamik',
    'çerkezköy dýnamýk s'],
  'CFT Bridge' => ['cft b'],
  'Cimentas Club' => ['cimentas sk', 'cimentas bsk'],
  'Circolo del Bridge Cannareggio' => ['c.lo cann.'],
  'Circolo del Bridge Firenze' => ['c.lo br. firenze',
    'cb firenze', 'clo bridge firenze'],
  'Circolo del Bridge N. Ditto Reggio Calabria' => ['n. ditto rc',
    'b. reggio emilia'],
  'Circolo del Bridge Venezia' => ['c.lo ve', 'bccs venezia'],
  'Circolo del Tennis Palermo' => ['c.lo tennis palermo'],
  'Circolo Nautico Posillipo' => ['c. n. posillipo', 'posillipo'],
  'Círculo Português de Bridge' => ['circulo portugues'],
  'Clube de Tiro & Sport' => ['tiro&sport'],
  'Clube Naval São Vicente' => ['clube n.s. vicente'],
  'Corlu Yildiz' => [
    'corlu bel. gsd',
    'corlu belediyesi',
    'corlu belediyesi sk',
    'corlu bld.gsd',
    'corlubelediye gsk',
    'corlubelediye sk',
    'corlubelediyesi gsk',
    'corlubelediyesi sk',
    'çorlu belediye',
    'çorlu beledýye'],
  'Crvena Zvezda' => ['zrvena zvezda'],
  'Dabrowka WZBS' => ['wzbs dabrowka'],
  'Datca SK' => ['datça sapphýre'],
  'Debrecen DEAC' => ['debrecen-deac'],
  'Delhi Gymkhana Club' => ['delhi gymkhana'],
  'Devrek BK' => ['devrek bric kulubu'],
  'Diyarbakýr Sur BSK' => ['diyarbakir bs', 'diyarbakir bsbs', 
    'dýyarbakir sur. b.b', 'diyarbakir sur sk', 'sur belediye sk',
    'sur belediye', 'diyarbakir bsb', 'd.bakir b.þ. bld.',
    'd.bakir y.þehýr bld', 'dýyarbakir b.bld.sk'],
  'Dörtyol SK' => [
    'dortyol bk', 
    'dortyol sk', 
    'dortyol bld',
    'dortyol belediye', 
    'dortyol beledyie', 
    'hatay dortyol'],
  'Drammen Arbeiderparti' => ['drammen arb'],
  'Dubai Bridge Club' => ['dubai club'],
  'Ege Club' => ['ege bilimsel', 'ege bsk'],
  'EIBC Jakarta' => ['eibc_jakarta'],
  'Ekol BSK' => [
    'ekol bric',
    'ekol bric kulubu',
    'ekol bric spor'],
  'El Ahly'  => [
    'al ahly', 
    'al ahly club',
    'al ehly', 
    'al ehly club',
    'el ahly club', 
    'el- ahly',
    'el-ahly club', 
    'el-ahly'],
  'El-Karma' => ['al-karma', 'al karma', 'karma club'],
  'Elmadag BSK' => [
    'elmadag bric spor',
    'elmadag bric kulubu',
    'elmadað brýç kulübü'],
  'Ergene GSK' => ['trakya ergene gsk', 'trakya ergene gtgsk',
    'trakya ergene'],
  'Eskisehir Adalar' => [
    'eskisehir adalarbsb', 
    'eskisehir adalarbsk'],
  'Eskisehir Baðlar' => ['eskýþehýr baðlar'],
  'Eskisehir Sports' => [
    'eskýsehýr bric k',
    'eskisehir bsk',
    'eskisehir skd',
    'eskisehýr bk'],
  'Essen 86' => ['BSC Essen 86'],
  '7 Eylül SK' => [
    '7 eylul genclik sk', 
    '7 eylul', 
    '7 eylül bsk',
    'yedi eylul sk'],
  'Fakultas Teknik Bridge Club Universitas Tanjungpura' =>
    ['ftbc untan', 'ftbc university tanjungpura'],
  'Fanfulla' => ['fanfulla lo'],
  'Fatih Karagümrük SK' => ['fatýh karagümrük s.',
    'karagumruk sk', 'karagümrük sk', 'Fatýh Karagümrük SK'],
  'Field Club Udaipur' => ['field club udaypur'],
  'Frankfurter TBC' => ['tbc frankfurt 1958'],
  'Fukien Athletic Club' => ['fukien athletic c'],
  'Gabrial University of Indonesia' => [
    'gaberial ui', 
    'gabrial ui', 
    'gabrial ui declare', 
    'gabrial ui premier', 
    'gabrial-ui', 
    'gabrial ui-y g', 
    'gabrial ui yg',
    'gabriel - ui'],
  'Gabungan Bridge Bandung' => [
    'gab bridge bandung',
    'gbb bandung',
    'gbc bandung'],
  'Gabungan Bridge Kota Tasikmalaya' => ['Gabrikotas Club'],
  'Ganesha Bridge Club' => [
    'ganesha bandung',
    'ganesha bc',
    'ganesha bridge'],
  'Genclerbirligi SK' => ['genclerbirligi bric'],
  'Gereja Masehi Injili di Minahasa' => ['pkbs gmim sulut'],
  'Göktürk SK' => ['gokturk sk'],
  'Goztepe Hilal SK' => ['goztepe hilal', 'goztepe skd'],
  'Grant Thornton' => [
    'bc grant thornton',
    'bg thornton', 
    'grant thonrton', 
    'grant thornot',
    'grant thornton endu',
    'grant thorton',
    'grant thronton',
    'grantt thornton'],
  'GSD Club' => ['GSD Briç'],
  'Guangdong Club' => [
    'guangdong ba', 
    'guangdong briagclub', 
    'guang dong briag club'],
  'Gümüşlük SK' => ['gumusluk genclik'],
  'Hanseatic Hamburg BC' => ['hanseatic bc', 'hanseatic hamburg'],
  'Heimdal BK' => ['heimdal bc'],
  'Hidropaks Gebze Tayfun SK' => ['hidropaks gebze tsk'],
  'Hok Studiecentrum' => ['hok ts', 'hoc studiecentrum'],
  'IBM SK' => ['ýbm sk'],
  'Icel Sports' => ['Ýçel Spor'],
  'Idman Ocagi SK' => ['idmanocagi sk', 'idmanocagi spor'],
  'Incirli SKD' => ['incirli sk'],
  'Iskenderun IHS' => ['iskenderun yarikaya'],
  'Isparta Club' => [
    'isparta bric ihtisa',
    'isparta bric iht. k'],
  'Istanbul Sports' => [
    'istanbul bmsk', 
    'istanbul bric sk', 
    'istanbul bsk', 
    'istanbul sk', 
    'istanbul skd', 
    'istanbul spor', 
    'ýstanbul bmsk',
    'ýstanbul briç sk',
    'ýstanbul brýc',
    'ýstanbul brýç sk',
    'ýstanbul sk'], 
  'Izmir BSB' => [
    'izmir b.b.',
    'izmir b.b.s.k',
    'izmir b.s. belediye', 
    'izmir bbsk', 
    'izmir bbgsk',
    'izmir bbsgk',
    'izmir bsbs',
    'izmir bþb', 
    'izmir bilimsel', 
    'izmir bilimsel s.k', 
    'izmir bsb/turkiye', 
    'izmir buyuksehir', 
    'izmir buyuk sehir b', 
    'ýzmýr b.b.s.k.', 
    'ýzmir b.s. belediye', 
    'ýzmir bsb', 
    'ýzmir bþb', 
    'ýzmýr býlýmsel bk', 
    'ýzmýt saraybahçe sk'],
  Jeofizik => ['jeofýzýk', 'jeofizik bsk', 'jeofizik b.k',
    'jeo hidro'],
  'Jinshuo Club' => ['jingshuo club'],
  'Jordan Club' => ['j.b.a club'],
  'Jubilee Hills International Centre' => ['jhic'],
  'Kadirli Akil Oyunlari Merkezi' => ['kaom yildizlar', 'kadirli bsk'],
  'Kapakli Sýte' => [
    'kapaklý sýte',
    'kapakli site',
    'kapakli site bsk',
    'kapakli site sk.',
    'kapakli site skd.'],
  'Karimata BC' => ['karimata bridgeclub'],
  'Karlsruher BSC' => ['karlsruher bc'],
  'Karsiyaka BSK' => [
    'karsiyaka bbsk',
    'karsiyaka bskd',
    'karsiyaka ksk',
    'karsiyaka 5li major',
    'karsiyaka besli mbs',
    'karþiyaka bsk'],
  'Kartal Club' => [
    'kartal bel', 
    'kartal belediye', 
    'kartal bld', 
    'kartal bskd'],
  'Kemalpasa Club' => [
    'kemalpasa ata',
    'kemalpasa ata gnclk',
    'kemalpasa ata gskd',
    'kemalpasa ataspor'],
  'King Hussein Club' => [
    'king huessin club',
    'king husain',
    'king husain club',
    'king hussein'],
  'Kirklarelý BSK' => [
    'kirklareli bel. sk',
    'kirklareli bld. sp',
    'kirklareli gsk'],
  'Kocaeli BSSK' => [
    'kocaelý bssk', 
    'kocaelý gençlýk sk',
    'kocaeli buyuksehir',
    'kocaeli gsk',
    'kocaeli sk'],
  'Konak Club' => ['Konak Belediyespor', 'Konak BBSK', 'Konak Belediye',
    'Konak Bld. GSK'],
  'Konya BK' => ['konya selcuk ubsk'],
  'Köln Lindenthal BC' => [
    'köln lindenthal', 
    'köln-lindenthal',
    'köln-lindenthal bc', 
    'köln-lindenthaler', 
    'köln-lindenthaler b',
    'lindenthaler bc',
    'lindenthaler bc e.v'],
  'Kristiansand BK' => ['kristianssand bk'],
  'KSB Radkov' => [
    'kcb radkov', 
    "ksb \"radkov\"",
    'radkov bc'],
  'Kultcamp Rieneck' => ['bc burg rieneck'],
  'Küp BSK' => [
    'kup b.s.k',
    'kup bric kulubu',
    'kup bric sk',
    'kup brýc',
    'kup brýç sk', 
    'kup bsk', 
    'kup sk'],
  'Kurtulus SK' => ['kurtuluþ sk'],
  'Laodikya SK' => ['laodikya bric sk'],
  'Larvik og Horten BK' => ['larvik horten'],
  'Levski Sofia' => ['levski sf'],
  'Lisbon Bridge Association' => ['Associação de Bridge de Lisboa'],
  Locomotiva => [
    'Locomotiv CFR', 
    'Locomotiva CFR', 
    'Locomotiva CRF', 
    'Loco-CFR'],
  'Ludvikabygdens BK' => ['fc ludvika'],
  'Luleburgaz SK' => [
    'luleburgaz bsk', 
    'luleburgaz kul. san', 
    'luleburgaz kul.san',
    'lüleburgaz bsk'],
  'Madras Gymkhana Club' => ['madras gymkhana', 'madras gumkhana',
    'maras gymkhana'],
  'Majör Boğaziçi' => [
    'ksk besli major bsk',
    'major b', 
    'major boagazici',
    'major bogazici',
    'majör boðaziçi', 
    'major bogazici bsk'],
  'Malatya BSK' => ['Malatya Briç SK', 'Malatya Bric SK',
    'Malatya Brýç Spor', 'Malatya SK', 'Malatya Basket',
    'Malatya BEM'],
  'Malatya Yildiz Dogu' => ['malatya yldz/dogu', 'malatya yildiz bsk'],
   Malatyagücü => ['malatya gucu', 'malatya gücü', '1932 malatya gucu',
     '1932 malatyagucu'],
  'Manisa BSK' => ['manisa bbsk', 'manisa b.s.b',
    'manýsa spor kulübü'],
   Matunga => ['matunga gym'],
  'MBC Kinali' => ['minahasa bridge club kinali'],
   'Mersin Club' => [
     'mersin b.s.k', 
     'mersin bb', 
     'mersin bbs', 
     'mersin bld', 
     'mersin bþb', 
     'mersin bsb', 
     'mersin bsb sk', 
     'mersin bsbs',
     'mersin bsk', 
     'mersin buyuksehir',
     'mersin ybsk', 
     'mersin b.b.k', 
     'mersin b.b.s', 
     'mersin b.s.b',
     'mersin b.s.b. s.k', 
     'Mersýn BBSK', 
     'Mersýn B.S.B. S.K'],
  'MBC Mampang' => ['mbc-mampang', 'mampang bc'],
  'Meski Club' => ['meski spor'],
  'Miskolc DEAC' => ['deac-miskolc'],
  Mragowia => ['mragowia si'],
  'Mudanya GSK' => ['mudanya genclik', 'mudanya ilce'],
  'Muðla GSK' => ['mugla genclik spor', 'mugla spor'],
  'Muratpasa Club' => ['Muratpasa Belediye'],
  'München Sanzatu' => ['munih sanzatu'],
  'Nachteulen Leverkusen' => ['nachteulen leverk'],
  'Nagari Club' => ['nagari bridge club', 'nagari unj'],
  'Nancy Jarville BC' => ['nancy jarville b.c'],
  'Narlidere Club' => [
    'narlidere belediye',
    'narlidere bisk',
    'narlidere ihtisas'],
  'Nazilli BBSK' => [
    'nazilli bsk',
    'nazilli skd',
    'nazýllý bsk'],
  'Nilüfer Bld. BSK' => [
    'nilifer bel',
    'nilufer bel',
    'nilufer belediye s',
    'nilufer belediye sk',
    'nilufer belediyesi',
    'nilufer beledýye',
    'nilufer bld',
    'nilufer bld. sk',
    'nilufer bsk',
    'nilüfer belediye'],
  'Niski Bridge Club' => ['niski bridz club', 'niski bridz klub'],
  'Norrorts Bridge' => ['norrorts bk'],
  'Núcleo De Bridge Do Círculo' => ['nb-cbl', 'nb cbl'],
  'Nuovo Bridge Insieme' => ['nbi roma'],
  'Nürnberg Museum' => ['BC Nürnberg Museum'],
  'OBK Kløverknekt' => ['obk kloverknekt', 'obk/kløverknekt'],
  'Odense BK' => ['odense bridgeclub', 'odense bridgeklub'],
  'One Eyed Jacks' => [
    'one-eyed',
    'one-eyed jack', 
    'one-eyed jacks', 
    'one.eyed jacks'],
  'Ordu BSK' => ['ordu bric', 'ordu bric spor',
    'ordu demirspor'],
  'Orhangazi SK' => ['orhangazi gencliksk'],
  'Otters Club' => ["otters' club", "otter's club", "otter's"],
  'Palcan Bridge ASD' => ['palcan bridge'],
  'Pamukkale SK' => ['pamuk sk', 'pamukkale bsk', 'pamukkale bric'],
  'Piast Mosir Sieradz' => ['piast sieradz'],
  Polýsgücü => ['polýs gücü s', 'polýs gücü', 'polis gucu', 'polisgucu'],
  'Pria/Kaum Bapa Sinode MMIM' => [
    'p/kb-sg',
    'p/kb sinode gmim',
    'pkb sinode gmim',
    'sinode gmim'],
  'Pudong Club' => ['pu dong club'],
  'Quantum BC' => ['bc quantum'],
  'Qi Zhong Club' => ['qi zhong'],
  'RAL Poznan' => ['ral poznañ', 'ral ponan'],
  'RBSC Polo Club' => ['polo club'],
  'Romana Bridge' => ['romana br'],
  'Rumah Sakit Umum Daerah Pekanbaru' => ['rsud pekanbaru'],
  'Samsun BK' => ['samsun bsk'],
  'Sariyer BSK' => [
    'sariyer belediye sk',
    'sariyer beledýyesi',
    'sariyer bld'],
  'Seferihisar Municipality' => [
    'seferihisar bld-ege',
    'seferihisar bld', 
    'seferihisar kizilir',
    'seferihisar ozguven',
    'seferihisar ssskd',
    'narlidere bld', 
    'narlidere bld. skd',
    'narlýdere belediye'],
  'Senigallia Club' => ['br. senigallia'],
  'Shou Chuang' => ['shou chuang club'],
  'Silifke SK' => ['silifke bld'],
  'Sirinyer Sports' => ['sirinyer spor'],
  'Siwo Persatuan Wartawan Indonesia' => ['siwo pwi sulut'],
  'Ski BK' => ['Skien BK'],
  'Slem Bric SK' => ['slem bric'],
  'Sport Clube Alberto Sousa' => ['sport clube alberto'],
  'SSD Angelini Bridge' => ['asd angelini', 'angelini bridge tea',
    's.s.d. angelini', 'angelini br', 'ssd angelini'],
  'S:t Erik' => ['bk s.t erik', 'bk st erik', 'bk st.erik', 'bk sterik',
    'st erik', 'st erýk', 'st erik', 'st:erik', 'bk st:erik'],
  'Star Bridge Roma' => ['star br. roma'],
  'Studentenes BK' => [
    'studenes bk',
    'studentenes bk tron',
    'stundentenes bk',
    'stundentes bk',
    'studentene bk',
    'studentens bk'],
  'Suleymanpasa Club' => [
    'suleymanpasa bgsk',
    'suleymanpasa bld',
    'suleymanpasa bld sp'],
  'Swara Kita BS' => ['Swara Kita B.S', 'swara kita b. sulut'],
  'Szlem Gdansk' => ['szlen gdansk', 'szkola szlem gd',
    'szkola brydza szlem', 'szkola szlem'],
  'Shanxi Club' => ['sx club'],
  "'t Onstein" => [
    'at onstein', 
    "bc't onsten", 
    "bc't onstein",
    'bc t oinstein',
    "bc t' onstein",
    "bc 't onstein",
    "bc 't ontstein",
    'bcr onstein',
    'bct onstein',
    't onstein',
    "t'onstein"],
  'Taskopru Club' => ['Taskopru Hýz'],
  'Tekirdað Club' => [
    'tekirdað belediye s', 
    'tekýrdað brýç kulüb',
    'tekirdag bk',
    'tekirdag bsk',
    'tekirdag genclik',
    'tekirdag s.pasa',
    'tekirdag s.pasa bgs',
    'tekirdag spor',
    'tekirdag ghskd',
    'tekýrdah beledýye',
    'tekýrdag beledýye',
    'tekýrdað s.paþa bgs'],
  'Tennis Club Parioli' => ['tc pariori', 'tcp rm', 'tennis rm',
    't.c.p.', 'tc parioli', 'angelini bt tcp', 't.c.p. angelini b.t',
    'angelini bt-tcp', 't.c. parioli', 'tcp rm angelini'],
  'Tonyaspor' => ['tonya spor'],
  'Top Bridge BC' => ['topbridge bc', 'top bridge', 'topbridge bk',
    'little top bridge'],
  'Torino Allegra' => ['bridge allegra', 'allegra to', 'bc allegra',
    'allegra - to', 'gs allegra', 'g.s. allegra', 'torino alegra', 
    'allegra torino', 'g.s.allegra', 'Gr.Sp.Ass. Allegra'],
  'Trabzon Club' => [
    'trabzon brýç kulübü',
    'trabzon idmanocagi sk',
    'trabzon karadeniz',
    'trabzon ýdman oca'],
  'Tunaras SK' => ['tunaras spor'],
  'Ullensaker Kisa' => ['gull/kisa'],
  'Ulusal Folklor GSKD' => ['ulusal f.a.m. gskd'],
  'Underberg BC' => ['underberg bridgeclu'],
  "Universita' del Bridge" => [
    "universita' bridge",
    "universita'  bridge",
    "universita' del bri", 
    'universita bridge',
    'università bridge'],
  'Usak SK' => ['usak bric sk'],
  'Uzunköprü SK' => ['uzunkopru sk'],
  'Vestel SK' => ['vestel spor'],
  'Visnelik Club' => [
    'viþnelik briç sk',
    'visnelik bric spor'],
  'Wadi Degla' => ['wadi degla club', 'degla club'],
  'WCG Mumbai' => ['wcg (mum)', 'wcg-mumbai'],
   'Willingdon Sports Club' => ['the willingdon sports club', 'wcg'],
  'Witte Huis' => [
    'het witte huis', 
    'het witter huis', 
    'hett witte huis', 
    'the white house',
    'white house'], 
  'Yalikavak SK' => [
    'yalikavak b.s.k', 
    'yalikavak bisk', 
    'yalikavak bld sk', 
    'yalikavak bsk', 
    'Yalikavak belediye',
    'Yalikavak Bric IHT', 
    'yalikavak ihtisas',
    'yalikavak bld'],
  'Yarimca SK' => [
    'yarimca s.k', 
    'yarimca gsk', 
    'Yarýmca SK'],
  'Yeni Pelitli SK' => ['yeni pelitli'],
  'Yesilgiresun SK' => ['yesil giresun'],
  'Yildirim YSK' => ['yildirim sgkkd', 'ysk yildirim'],
  'Young Chelsea Bridge Club' => ['young chelsea'],
  'Zeugma SK' => ['zeugma bric sk'],
  'Zonguldak BSK' => [
    'zonguldak belediye',
    'zonguldak bld'],
  'Østfold og Follo' => ['østfold/follo', 'østfold&follo',
    'ostfold og follo'],
  'Øvre Ottadalen' => ['øvre ottadal'],
  'Överum BK' => ['överrums bk', 'överums bk'],
  'Århus BK' => ['Aarhus BK', 'Århus Bridgeklub', 'Aarhus Bridgeklub']
);

my @SINGLE_WORDS = qw(
  ABK Acol AGBC 
  Benfica Besiktas Bonsist Botev BTBK
  Dragao Drienerlo
  EIBC Fanfulla Fenerbahce
  Galata Galatasaray 
  Hoppklubbene Hosgoru 
  Jeofizik Jeohidro Juniorklubben JZD
  Karlsruher Kløverknekt KPPM
  Lavec LÜKSAD
  Locomotiva
  Malatyagücü Matunga Mo Mragowia
  NBK
  Pelatnas Polýsgücü
  Qizhong
  Sekirovo Sitespor Sivasspor Slynce Solli Spezia Spojnia
  Studenterforeningen
  TGR Tonyaspor Trifolium
  Unia Uppsalabridgen
  Västeråsbridgen Vestri
  Örebridgen
  Yildirimspor
  Zmrzlina
);

my %SINGLE_TYPOS =
(
  '4 Jacks' => ['4jack'],
  'Aachener BC' => ['aachener'],
  'ABA Mumbai' => ['aba'],
  'Acol Praha' => ['acol'],
  'Adana BSB' => ['adanaspor'],
  'Adapazan Briç SK' => ['ada'],
  'Agriculture Bridge Club' => ['agbc'],
  'Akademia Brydza' => ['akademia'],
  'Akademisk Bridgeklub' => ['akademisk'],
  'Alexandria Sporting Club' => ['sporting', 'sprting'],
  'Altay SK' => ['altay'],
  'Altinay SK' => ['altýnaysk'],
  'Amed Sportif' => ['amedspor'],
  'Anadolu Bridge Club' => ['anadolu'],
  'Ankara Kontrat' => ['kontrat'],
  'Antalya BSK' => ['ankalya', 'antakyaspor'],
  'Armando and Viviane Gonçalves Pereira' => ['avgp'],
  'ASA University of Tel Aviv' => ['asa'],
  'Aso Pika' => ['asopika'],
  'Associação de Bridge da Madeira' => ['abm'],
  'Atasehir BK' => ['atabric'],
  'ATU Bucharest' => ['atu'],
  'Auguri Warsaw' => ['auguri', 'augurý'],
  'Auram BSKD' => ['auram'],
  'AVI Club Noida' => ['avi'],
  'Bakýrköy Briç SK' => ['bakirkoy'],
  'Bangkok Bridge Club' => ['bbc'],
  'Baþkent Sekans BSK' => ['sekans'],
  'BC Bamberger Reiter' => ['bamberger', 'amberger', 'bamberberg'],
  'BK Björken' => ['bjorken', 'björken'],
  'BC de Lombard' => ['lombard', 'lomard'],
  'BK Everfresh' => ['everfresh'],
  'BC Garches' => ['garches'],
  'BK Hebros' => ['hebros'],
  'BC Herkules' => ['hercules', 'herkules'],
  'BH Koru BK' => ['koru'],
  'BK Lavec Smile' => ['smile'],
  'BC Milano' => ['bcmi'],
  'BC Modalfa' => ['bcm'],
  'BC Saint Honoré' => ['bcsh'],
  'BC Tofas' => ['tofaþ', 'tofas'],
  'Bridge Addaura' => ['addaura'],
  'Bridge Tunas Cahaya' => ['btc'],
  'Bridgeclub Oog' => ['bco'],
  'Brussels Bridge Club' => ['bcob'],
  'Buca Sports' => ['bucaspor'],
  'Calcutta Bridge Club' => ['cbc'],
  'Camlica Sports' => ['camspor'],
  'Çayyolu BK' => ['cayolu'],
  'CB Baleal' => ['cbbaleal'],
  'CB São Miguel' => ['cbsm'],
  'Centro Desportivo Universitário do Porto' => ['cdup'],
  'Cercle de la Cité' => ['citè'],
  'Clube de Bridge dos Engenheiros' => ['cbe'],
  'Corlu Avrasya' => ['avrasya'],
  'Cracovia 1906' => ['cracovia'],
  'Crvena Zvezda' => ['zvezda'],
  'BC de Zeerob' => ['zeerob'],
  'Delhi Gymkhana Club' => ['dgc', 'dg'],
  'El Ahly' => ['ahly', 'alahly'],
  'El-Karma' => ['karma'],
  'ESBS Elblag' => ['esbs'],
  'Eskisehir Sports' => ['eskisehirspor'],
  'Estonian Sports Association' => ['jõud'],
  'Fakultas Teknik Bridge Club Universitas Tanjungpura' => ['ftbc'],
  'Fatih Karagümrük SK' => ['fatihkaragumruk'],
  'Gabrial University of Indonesia' => ['gabrial', 'gabriel'],
  'Gabungan Bridge Bandung' => ['gbb'],
  'Gabungan Bridge Kota Tasikmalaya' => ['gabrikotas'],
  'Ganesha Bridge Club' => ['gbc', 'ganesha'],
  'Gala Tawa Bridge Club' => ['gtbc'],
  'Ganesha Bridge Club' => ['ganesha'],
  'Genclerbirligi SK' => ['genclerbirligi', 'gencler'],
  'Geyve Sports' => ['geyvespor'],
  'Goztepe Hilal SK' => ['goztepe'],
  'Hamra Club' => ['hamra'],
  'Harlequins BC' => ['harlequins'],
  'Harstad S&B' => ['harstad'],
  'Hok Studiecentrum' => ['hok'],
  Hosgoru => ['hoþgörü'],
  'IBM SK' => ['ýbm'],
  'Isparta Club' => ['isparta'],
  'Istanbul Sports' => [
    'istanbulspor', 
    'ýbsk', 
    'ýbmsk', 
    'ýsbk',
    'istanbulskd'],
  'Jinshuo Club' => ['jinshuo'],
  'KDI Moradabad' => ['kdi'],
  'Kadirli Akil Oyunlari Merkezi' => ['kaom'],
  'Karadeniz SK' => ['karadenizspor', 'karadenýzspor'],
  'Kartal Club' => ['kartalspor'],
  'Kerukunan Keluarga Kawanua' => ['kkk'],
  'Konkret Kasztelan' => ['kasztelan'],
  'Kucukbakkalkoy SK' => ['kucukbakkalkoyspor'],
  'Kurtulus SK' => ['kurtulusspor'],
  'Lisbon Bridge Association' => ['abl'],
  Locomotiva => ['loco'],
  'Luleburgaz SK' => ['luksad'],
  'Madras Gymkhana Club' => ['mgc'],
  'Majör Boğaziçi' => ['majorbogazici'],
  'Manado Convention Center' => ['mcc'],
  Mragowia => ['mragovia', 'mrogowia', 'mrangowia', 'mr¹gowia',
    'mr¥gowia'],
  'Muðla GSK' => ['muglaspor'],
  'Nauka Brydza' => ['naukabrydzapl'],
  'Niski Bridge Club' => ['nbk'],
  'Norrorts Bridge' => ['norrort'],
  'Núcleo De Bridge Do Círculo' => ['nbcbl'],
  'Nuovo Bridge Insieme' => ['nbi'],
  'OBK Kløverknekt' => ['kløverknekt'],
  'Odisha Secretariat Recreation Club' => ['osrc'],
  'Orthodoxi BC' => ['orthodox', 'orthodoxi', 'orthozoxi'],
  'Osir Lidzbark Warmiński' => ['osirlidzbark'],
  'Otters Club' => ['otters'],
  'Pamukkale SK' => ['pamukspor'],
  'Paris Country Club' => ['pcc'],
  'Pelatda DKI' => ['pelatda'],
  'Pelitli SK' => ['pelýtlýspor'],
  'Porto Club' => ['cbp', 'cbporto'],
  'RBSC Polo Club' => ['rbsc'],
  'Royal Air Force Club' => ['rac'],
  'Ruch AZS' => ['ruch'],
  'SDK Tczew' => ['sdktczew'],
  'Seferihisar Municipality' => ['seferihisarbelediye'],
  'Sekolah Bridge Tonaas Wangko' => ['sbtw'],
  'Shanxi Club' => ['sxclub'],
  'Shooting Club' => ['shooting'],
  'Silicon Valley Youth Bridge' => ['sivy'],
  'Silifke SK' => ['silifkespor'],
  'Sirinyer Sports' => ['sirinyerspor'],
  'Smedstadens BK' => ['smedstadens'],
  'SPG Club' => ['spg'],
  Spojnia => ['Spójnia'],
  'Sport Clube Alberto Sousa' => ['scas'],
  'Studentenes BK' => ['studentenes', 'studentene'],
  'Sølvknekt BK' => ['Sølvknekt'],
  "'t Onstein" => ['onstein'],
  'Tekirdað Club' => ['tekirdagspor'],
  'Tennis Club Parioli' => ['tcp', 'rm'],
  TGR => ['tgrs'],
  'The West End Mumbai' => ['twem'],
  'Top Bridge BC' => ['topbridge'],
  'Torino Allegra' => ['bcat'],
  'Trabzon Club' => ['idmanocagispor'],
  'Tunaras SK' => ['tunaras'],
  Uppsalabridgen => ['ippsalabridgen'],
  'Vestel SK' => ['vestel'],
  'Wadi Degla' => ['degla'],
  'Wawa Brydz' => ['wawabrydz'],
  'Witte Huis' => ['whitehouse'],
  Yildirimspor => ['yildirim', 'yýldýrým',
    'yýldýrýmspor'],
  Zmrzlina => ['zmerzlina', 'zmirzlina'],
  Örebridgen => ['Örebridge', 'orebridgen']
);


sub set_hashes
{
  my ($method, $key) = @_;

  $method->(\@MULTI_WORDS, \%MULTI_TYPOS,
    \@SINGLE_WORDS, \%SINGLE_TYPOS, $key);
}

1;
