#!perl

use strict;
use warnings;
use v5.10;
use utf8;
use open ':std', ':encoding(UTF-8)';

package Tags::Fun;

our @ISA = qw(Exporter);
our @EXPORT = qw(set_hashes);

my @MULTI_WORDS =
(
  '0% Eriksson',
  '1 1/2',
  '1-2-1',
  '1 Non Blonde',
  '1 over 1',
  '10 Tricks',
  '101.yil',
  '1x2',
  '123 Jättebra',
  '16 Flights',
  '19 mayis 1919',
  '1NT',
  '2-2-1T',
  '2 ess og to konger',
  '2 Generations',
  '2 med lite mer hår',
  '2 me og 2 uten',
  '2 over 1',
  '23 Generation',
  '246.5 Meters',
  '2A+3I',
  '3 Baritona',
  '3 Frakkar',
  '3 Idiots + 1',
  '3 troll og en bukk',
  '3..2..1..Meins!',
  '33 Max',
  '4 Hjerter',
  '4 Majori',
  '4 Nat',
  '4 pataa',
  '4 Trèfles',
  '40 Årskrisa',
  '5 Ess',
  '5 kommer tillbaka',
  '50lei50bani',
  '50 med omnejd',
  '50 shades of cards',
  '54Fun',
  '55 med omnejd',
  '5G',
  '6 Notrump',
  '6 Spades',
  '60 y 20',
  '8-5-0-0',
  '88 KN',
  '88 Loreng',
  '88 Red',
  '88 Merah Senior',
  '88 Senior',

  'A Maze',
  'A Team',
  "A'ppetit",
  'A2',
  'Aar Paar',
  'Ace up Our Sleeve',
  'Aces & Deuces',
  'Ad Hoc',
  'Adams Family',
  'Advance Team',
  'After Eight',
  'AG laget',
  'Against All Odds',
  'Aina Malttia',
  'Ala vill til Himlen',
  'Albayrak67',
  'Albrekts T-Bone',
  'Alex is Beautiful',
  'All Female Panel',
  'All In',
  'All Lions',
  'All Stars',
  'All Will Be Alright',
  'Alle presidentens menn',
  'Almost Famous',
  'Almost Female Panel',
  'Almost Juniors',
  'Alt for rognan',
  'Also Changes',
  'Alster Spree',
  'Alzheimer Aces',
  'AN-124',
  'Andre boller',
  'Angel of Harlem',
  'Angels & Demons',
  'Angry Birds',
  'Ann Lill (i)Da',
  'Annas Fans',
  'Anti Revenge',
  'Anup Dhar',
  'Apa Heili',
  'Apple Pie',
  'Applied Math',
  'April 30',
  'Apollo Soyuz',
  'Apres-Bridge Champs',
  'Arctic Farmers',
  'Arctic Powerchicks',
  'As vezes',
  'Atomic Bridge',
  'Ave Magma',
  'Ave Maria mä bihang',
  'Awesome Avengers',
  'Aylan Kurdi',
  'AZS Buboslavia',

  'B1',
  'B Team',
  'Baba Blues',
  'Babes Amazones',
  'Baby K',
  'bACEd in Austria',
  'Bad Beat',
  'Bad Man',
  'Bağcı Döven',
  'Bangkok Kimono',
  'Bar-Su',
  'Bara brudar',
  'Baris hemen simdi',
  'Barny Army',
  'Baska Yok',
  'Bastion Smaku',
  'BBO Lovers',
  'Bea & Family',
  'Beer Card',
  'Bela e os Monstros',
  'Bermuda Squad',
  'Best Friends of Gun',
  'Best i baren',
  'Best of Hessen',
  'Best uten kort',
  'Bettans Busar',
  'Beautiful Yan',
  'Berre Lækkert',
  'Beverly Hillbillies',
  'Beyaz Marti',
  'Bid72',
  'B.I.G.',
  'Big Bang',
  'Big Boss',
  'Big Chef',
  'Big Guns',
  'Big L',
  'Big Makie',
  'Big Mi?',
  'Big Utao',
  'Binua Landak',
  'Bizim takim',
  'Bjuda på',
  'BK Gröna Kvistar',
  'Black Adders',
  'Black Castle',
  'Black Cats',
  'Black Gold',
  'Black Hole',
  'Black Knife',
  'Black Label',
  'Black Pit',
  'Black Sea',
  'Black Swan',
  'Black Widows',
  'Blaksets Bin',
  'Blanda drops',
  'Bleu Lights',
  'Bloody Mary',
  'Blue Bamm',
  'Blue Chip Swedes',
  'Blue Diamonds',
  'Blue Hot',
  'Blue Note',
  'Bo Gulasch',
  'Boas disipler',
  'Bob Bob',
  'Bobbos Gäng',
  'Bobler og brus',
  'Bobo Dird',
  'Bodø Glimt førr evig',
  'B.O.N.G',
  'Bona Fide',
  'Boogie Knights',
  'Boro Boss',
  'Bosse Superettan',
  'Boye B Fan Club',
  "Boys'n' Girls",
  'Brian Is Beautiful',
  'Bridge Code',
  'Bridge Fan',
  'Bridge Friends',
  'Bridge Hunters',
  'Bridge Lovers',
  'Bridge over Nations',
  'Bridge Plus',
  'Bridge View',
  'British Invasion',
  'British Lions',
  'Bros1005',
  'Brown Sugar',
  'Brødrene & co',
  'Brødrene Dal',
  'Bugih Lamo',
  'Bullgalian All Star',
  'Butterfly from HK',

  'Ca. et halvt tonn',
  "Cai's Bird",
  'Californian Aces',
  'Can Am Express',
  'Can Can',
  'Captain Blood',
  "Captain's Four",
  "Captain's Team",
  'Card Warriors',
  'Cards Against Tursan',
  'Carla en haar kids',
  'Carpe Diem',
  'Carstens Kofötter',
  'Casino Floor',
  'Casino Royal',
  'Cast Bordo',
  'Cathy & Ewa',
  'Cat Daddy',
  'Cecils venner',
  'Centrum Farmers',
  'Cha Cha Cha',
  'Chateau Latour',
  'Cherno More',
  'Czech i trzech',
  'China Development',
  'Circle the World',
  'Cim Bom Bom',
  'Cheap Tricks',
  'Club 7',
  'Coach K',
  'Coco Cat',
  'Cold Light',
  'Come Farsi',
  'Cood Life',
  'Coś na razie',
  'Counter Strike',
  'Country Boys',
  'Coup de grace',
  'Crashtest Dummies',
  'Crème de la crème',
  'Croatian Pirates',
  'Crocodylus M. M.',
  'Crush Lack',
  'Curry Eaters',
  'CU+1',
  'Czech Back',

  "D'Artagnan",
  'Daar gaan we',
  'Da Big Storm',
  'Dai Meng Yi Dao',
  'Daisy Chain',
  'Dami Plus',
  'Dandy Lion',
  'Dankjewel doe maar',
  'Daniel med vänner',
  'Danish Dynamite',
  'Danish Guns',
  'Dark Baroque',
  'Dark Blues',
  'Das Autobahn',
  'Das rote Pferd',
  'De edruelige',
  'De escalatie sensatie',
  'De kontorsanställda',
  'De uovervinnelige',
  'Dead Pig Nerds',
  'Delft Buiten',
  'Delta-Variante',
  'Den glade alke',
  'Den gyldne omvei',
  'Den maskerte hevner',
  'Denktank 7',
  'Denmark Baby',
  'Dennis Crew',
  'Der Untergang',
  'Der alte Gro',
  'Der wilde Süden',
  'Desert Warriors',
  'Desperate Bridge Wives',
  "Dera's Deckhand",
  'Det är helt självklart',
  'Det nappar på kroke',
  'Deus vult',
  "Devil's Coup",
  'DG Stalwarts',
  'Di derre',
  'Diamonds Are Forever',
  'Die Mauer',
  'Die Schönen und di',
  'Die vier vom Rhein',
  'Die wazige Passers',
  'Dinamo Bridge',
  'Dinner Club',
  'Disco Ninjas',
  'Dziwiszow Jazz',
  'Do You Fire?',
  'Doctor Vicho',
  'Don Bernardo',
  'Don Julio',
  'Don Revival',
  'Dost Atesi',
  'Double Dummy',
  'Double Jungle',
  'Double R',
  'Double U',
  'Double Yusuf',
  'Down Under',
  'Dr. Dan',
  'Dr. Romantic',
  'Dr. Worrawat',
  'Dracula 2',
  'Drag Queens',
  'Dragon Cartoon',
  'Dragon Kiddies',
  'Dragon Piggies',
  'Dream Team',
  'Dronninga med prins',
  'Duc and Sons',
  'Dutch Highlanders',
  'Dyr-e-go',
  'Dyra Englund',

  'Eager Eagles',
  'Ebenius Crew',
  'Ege2/1',
  'Eides språksjov',
  'Ein Wort noch',
  'Eiydes discipler',
  'Ekkert að frétta',
  'El Cid',
  'El Nino',
  'Elisabeths änglar',
  'Elses Fanklubb',
  'Elusive 52',
  'Ember Spirit',
  'Empty Vessels',
  'En bridgespiller ..',
  'En myra tre elefanter',
  'En passant',
  'En påse nötter',
  'Endless Highway',
  'Endless Love',
  'England Swings',
  'Enjoy the Game',
  'Eski Dostlar',
  'Essence of Chicken',
  'E.T & the Dummies',
  'Et par sama og 2 ens',
  'EU Club',
  'EU oder so',
  'Euro Step',
  'European Aces',
  'Eva og Ingeborg',
  'Evakossa pilviin',
  'Ex Fijanova +',
  'Expert Cooking',
  'Expired Youth',
  'Eye of the Tiger',

  'F1',
  'F16',
  'F-37',
  'f.d. Fröken Michiel',
  'Fab VI',
  'Fac ut gaudeam!',
  'Fairy Tale',
  'Fallega Folked',
  'Fan Art',
  'Fancy Team',
  'Fanta 4',
  "Fariña's Circus",
  'Fast and Furious',
  'Fastings disipler',
  'Father and Son',
  'FC Marcinek',
  'Feel Good',
  'Felices las 4',
  'Fem på nya äventyr',
  'FF 69',
  'Field Tambun',
  'Filips Fanclub',
  'Finnmark Flyers',
  'Finways Sappers',
  'Five Clubs Partyband',
  'Fjoll uten fisk',
  'Fjords of Norway',
  'Flatt kjedelig',
  'Flora and Friends',
  'Flying Dutchess',
  'Force 5',
  'Forever Young',
  'Four Aces',
  'Four Belles',
  'Fozzilet og Kidza',
  'Frank-Furter',
  'Freak City',
  'Free to Fly',
  'Free Trade',
  'Front Page',
  'Fryske hynder',
  'Fuglen har fløyet',
  'Full Attack',
  'Full House',
  'Full Metal Jacket',
  'Full Moon',
  'Full Spectrum',

  'Gaek Bana',
  'Gallo en la canasta',
  'Game On',
  'Game Over',
  'Gammel Oppland m/co',
  'Gan Bei',
  'Gang of Wyk',
  'Garp44',
  "Gary's Boys",
  'Gemengd succes',
  'Generation X',
  'Genialer Teamname',
  "Ghosh's IV",
  'Ghost of Red',
  'Ghost Riders',
  'Gin Tonic',
  'Ginga Style',
  'Girls and Boys',
  'Girls on Fire',
  'Gissen met Wisse',
  'Gjeddene i sivet',
  'GKS April',
  'Global Mix',
  'Glomma Raiders',
  'Glory Box',
  'Glory Mandarin',
  'Goan Curry',
  'God (gammel) årgang',
  'Godt fornøyd Olsen',
  'Gogo Fans',
  'Golden Age',
  'Golden Bombers',
  'Golden Bull',
  'Golden Girls',
  'Golden Retriever',
  'Goldy Ice',
  'Good Ball',
  'Good Fellas',
  'Good Men',
  'Good Mood',
  'Good News',
  'Good Oxygen',
  'Good Six',
  'Great God',
  'Green Eyes',
  'Green Lines',
  'Group One',
  'Gry Forever',
  'Gunnars Gunners',
  'Gutta fra nord',
  'Gutta på tur',
  'Guyub57',
  'Gyllene Prag',
  'Gøta-Hesten',

  'H.A.N.E',
  "Hagen's Heroes",
  'Hai Na Bai Chuan',
  'Hai Nan Nan Shan',
  'Half Amsterdams',
  'Han Solo',
  'Hands and Hearts',
  'Hannover Four',
  'Hansen Hurricanes',
  'Hao Ran',
  'Happy Bridge',
  'Happy Couples',
  'Happy Hour',
  'Happy Team',
  'Happy Time',
  'Hare Krishna',
  'Have Fun',
  'He for She',
  'Heads or Tails',
  'Helens Angels',
  'Heldige Olav',
  "Hell's Angels",
  'Helt elektrisk',
  'Heph Stars',
  'Her vantar blaðsíðu',
  'Her yas pozitif',
  'Hey Yo',
  'Hi Charli',
  'Hillbilly Help Suit',
  'Holmen Spesial',
  'Homo Ludens',
  'Honey Milk',
  'Hope & Pray',
  'Hopp i sang',
  'Horten-14',
  'Hot Fuzz',
  'Huckauf Ingenieure',
  'Humør på humør',
  'Hurlumhei',
  'Husk of Hares',
  'Hvalen og tjukkasene', 
  'Hvani varni',
  'Hvor er mine babes',
  'Høyland & Kjell-Vidar',
  'Håkken hårt hårr',

  'I Doctors',
  'I Win',
  'Icelandic Bar',
  'Ice Cool',
  'Ice Jacks',
  'Ice King',
  'Ides Språksjov',
  'Ihan vaan Koistinen',
  'Ikke akkurat kjedelig',
  'Il Fante di Fiori',
  'Ilhas & Aredores',
  'India All Star',
  'India Blues',
  'Indian Mavericks',
  'Indonesian National Sports Week',
  'Infinity Mix',
  'Ingen Bagge',
  'Inverted Minors',
  'Iron Bank',
  'Is og brus',
  'Isolated Menaces',
  'Istiklal Yolu',
  'Israeli Dan',
  'Itinérants du bridge',
  'Iyi Takim',

  'Ja re ja',
  'Jacobo y Federico',
  'Jaipur Jewels',
  'Jamm & Co',
  'Jane Doe',
  'Jiangsu YY',
  'Jim Team',
  'JJ Match',
  'Jorunns disipler',
  'Josef and Cards',
  'Jósef smiður',
  'Joy Division',
  'Joyjits Army',
  'Julek po Filadelfii',
  'Junioren mit Upgrade',
  'Juniorproffen co',
  'Juniors Disipler',
  'Just for Fun',
  'Just Mixed',
  'Just Play',
  'Juzz-Pete',

  'K(apitän)K(alf)',
  'K1',
  'K2',
  'K3',
  'K4',
  'K5',
  'Kansai Union',
  'Kanto Union',
  'Kapten Krok Crew',
  'Karachi Aces',
  'Karate Kids',
  "Karl's Silence",
  'Karlssons frestelse',
  'Karlstads vänner',
  'Kasimirs Dream Team',
  'Katin kontit',
  'Katt-Bridge',
  'Keep Walking',
  "Keni's Dream",
  'Key Lime Pie',
  'Kick Back',
  'King Geoffrey',
  'Kipp O`Hoi',
  'Kippe et al',
  'Kisa metraj',
  'KL 4',
  'Klara färdiga slam',
  'House Klave',
  'Klicks Dream Team',
  'Klin Kokos',
  'K(l)ukken',
  'Kløver 5',
  'K-O',
  'Koos Bros',
  'Koridor 10',
  'Kronisk kusma',
  'Kuaile Huoniao',
  'Kung Sune',
  'Kungshamns Sega Gubbar',
  'Kurt quo vadis',
  'Kusinerna från land',
  'Kuvayi Milliye',
  'Kvalen og nissene',
  'Kwang-Hwa',

  "L'Orange",
  'La Bomba',
  'La Bridgerie',
  'La Cholita',
  'La Ice',
  'La La Land',
  'LA Light',
  'La Vista',
  'Ladprao Bridge',
  'Lady Da et ses Boys',
  'Lake My Love',
  'Lakk & Lær',
  'Lalit Mohanka Youth',
  'Lame Crane',
  'Lang lunte',
  'Langt mer enn ivrig',
  'Lao Xiongdi',
  'Larsson på taket',
  'Las Camelias',
  'Last Minute',
  'Last Arrival',
  'Lawrence of Arabia',
  'L.C. is Beautiful',
  'Le Blanc',
  'Le coup de Diablo',
  'Le rouge et le noir',
  'Leichte Brise Südwest',
  'Les Allumettes',
  'Les Girafes',
  'Les Teignes',
  'Les Zähringers',
  'Lieber tod als Zweiter',
  'Light Blues',
  'Light Cast',
  'Light of the Seven',
  'Lille Skutt',
  'Lindenthal und Freunde',
  'Lisbeth og gutta',
  'Lisbeths lakeier',
  "Lise (i)DA",
  'Lite av varje',
  'Little Meck',
  'Little Top Bridge',
  'Lo=High',
  'Lodz 100%',
  'Lokomotive Franken',
  'Lope de Vega',
  'Long Dragon',
  'Los Capitanos',
  'Los Escandinavos',
  'Los Gauchos',
  'Los Mismos',
  'Losing Finesse Erf',
  'Lovende ung',
  'Lowca Dam',
  'Lucky 4',
  'Lucky Bandana',
  'Lucky Losers',
  'Lucky Seven',
  'Lucky Six',
  'Lucky Star',
  'Lucky 13',
  'Lupii Galbeni',
  'Lynx and Co',
  'Lyubimetz 13',
  'Lått løye',

  'M W',
  'M.O.',
  'M. Green',
  "M' Orange",
  'Ma-Cartoon',
  'Ma&&Mü@Ma2',
  'Madam Mimm',
  'Maddes pojkar',
  'Madera czyli chill',
  'Magic Eyes',
  'Magnus er best',
  'Malungs Buggare',
  'Mama Lauda',
  'Mama Rosa',
  'Man Harr det man har',
  'Manchester United',
  'Many Hands',
  'Maria Elena',
  'Markku ja mimmit',
  'Marvel Universe',
  'Master Minds',
  'Max 100',
  'Max-Nat',
  'Männer mit ELAN',
  'MC 953',
  'MC Toss',
  'McIntosh Funclub',
  'Medium Rare',
  'Mee Noey',
  'Meins bleibt meins',
  'Meisters Disciple',
  'Meli Melo',
  'Methods of Bridge',
  'Mickey Two Clubs',
  'Midnight Cravings',
  'Miks Et?',
  'Mind and Matter',
  'Minmin Team',
  'Minus 800',
  'Missão Impossivel',
  'Mix n Match',
  'Mix veg',
  'Mladi i nadobudni',
  'Modesty Blaise',
  'Molto Bene',
  'Monotone Memories',
  'Monty Zeebergs FC',
  'Moo York Nix',
  'Moral Power',
  'Mostly Harmless',
  'Mountain Sea',
  'Moving Forward',
  'Mr Blackout',
  'Mr Bumble',
  'Ms. Guggenheim',
  'Murphys lag',
  'Musi 88',
  'My Friends',
  'My Way',
  'Myllyn Parhaat',
  'Mystery Foursome',

  "Narcotic's What?",
  'NASA ROFL',
  'NasDem Bitung',
  'Nat-Max',
  'Nästan lammkött',
  'Nem pó',
  'Nestors trappar upp',
  'Never Claim',
  'Nevada Turkey',
  'New Amsterdam',
  'New Friends',
  'New Combination',
  'New Generation',
  'New Twins',
  'Nice and Monsters',
  'Nicolais fanclub',
  'Nilslands Crew',
  'Nilslands Slowfoxes',
  'Nilslands sväklinge',
  'Nini Nono',
  'Ninjas in Pyjamas',
  'Nissene på låven',
  'No Angry Men',
  'No Back',
  'No Fear',
  "No He Isn't",
  'No Johnny Cash',
  'No Limit',
  'No ne mimmit',
  'No Pasaran',
  'No Problem',
  'No Surprise',
  'No Trump',
  'Noe Rusk',
  'Non Problem',
  'Noname Can Can',
  'Noras Fanclub',
  'Nord og Syd',
  'Nordan Strengur',
  'Nordic Five',
  'Nordic Fours',
  'Nordisk kombination',
  'Norges navle',
  'Norrlands guld',
  'North Pole',
  'North Seasters',
  'North Star',
  'Not the Empire',
  'Nuts & Bolts',
  'Næsten Junior',

  'O Fozzil',
  'O Samba',
  'O Zone Mio',
  'O.R.G',
  'Oceans4',
  'Occupy Taksim',
  'octobridge.xyz',
  'Od Moze Do Moze',
  'odd-å-vi',
  'Odd Tore',
  'Oddskongen med rese',
  'Off the Bend',
  'Old Guys',
  'Olsen på hjørnet',
  'Oh Ya!',
  'Ohne Respekt Crew',
  'Olas race',
  'Olavs utvalgte',
  'Old Horse',
  'Old People',
  'Old-Man',
  'Olympiad Gold',
  'Om het hoekie',
  'One I S',
  'One + Khuching Tree',
  'One Hundred Eighty',
  'One More!',
  'Opp og ned',
  'Orange Dynamite',
  'Otra Vez',
  'Ottos Lotto',
  'Our Future',
  'Over stokk og stein',

  'Pac-Man',
  'Papa & Rabbits',
  'Papa and Rabids',
  'Papas & Puppies',
  'Paris Match',
  'Park Tenisowy',
  'Patchwork Dynamite',
  'Paul & Frank',
  "Paula's Angels",
  'Pay Toll',
  'Pearl of the Orient',
  'Pen Pineapple Apple Pen',
  'Pepsi-Colas',
  'Pian paras',
  'Pieni karhu',
  'Piger og drenger',
  'Pigerne på tur',
  'Piekni i Bestie',
  'Pijar',
  'Pink Blend',
  'Pink Panter',
  'Pinot Noir',
  'Plan B',
  'PO & JBGood Team',
  'Poezel en Wip',
  'Polish Dodos',
  'Poker Bear',
  'Pola-Pola',
  'Pomoze my',
  'Powerpuff Pinglorna',
  'Plejans Plöjare',
  'Pravda za Holo Bolo',
  'Prawie Reprezentacja',
  'Precision Marathon',
  'Presten gudinna',
  'Pro Max',
  'Pur Pur',
  'Pure Zagreb',
  'På alerten',

  'Q of Di',
  'Qiao Yi Dui',
  'Qual. Winners',
  'Quatro Bruxas',
  'Que Mira Bobo',
  'Queen and Knights',
  'Queen of Hearts',
  'Queens Park Rangers',
  'Qiong Zhiyou',
  'Quanzhou Development',

  'R1F3 Initials',
  'R1S5 Initials',
  'Ra Ma Ra Him',
  'RADA Czarodziejek',
  'Radio Communication',
  'Radkov Trash',
  'Randers 2.0',
  'Randers 4.0',
  'Ranger Pink',
  'Rapan & Jezus',
  'Real Maramma',
  'Red Ash',
  'Red Beach',
  'Red Cross',
  'Red Hat',
  'Red Hot',
  'Red Pork Cutlet',
  'Red Robot',
  'Red Sky',
  'Red Soles',
  'Red Zeppelin',
  'Refi i prijatelji',
  'Reidar reiser snart',
  'Renons Rimstedt',
  'Repeat Bet',
  'Reps und Wodniansky',
  'Restricted Talent',
  'Rett opp i saksa',
  'Return the VI Counties',
  'Rimstedt Minus',
  'Rimstedt Power!',
  'Rising Star',
  'River Blanco',
  'River Friend',
  'River Rojo',
  'Robin Hood',
  'Robådane på BBO',
  'Rohit Wrappers',
  'Rooftop Palma',
  'Rotseknots Ernst',
  'Royal Flush',
  'Röda små stugor',
  'Rubb og stubb',
  'Rudderless Ship',
  'R.U.F.F.',
  'Ruff Gunn',
  'Ruia Blazers',
  'Russian Bear',
  'Ruter 7',
  'Ruter 9',

  'S(h)aman',
  'Sabarian + LuBu',
  'Sail Karimata',
  'Saint Titus',
  'Salten rundt',
  'Sam23',
  'Samfund Slingers',
  'Sana Soz',
  'Sannas Änglar',
  'Saras Friends',
  'Sayin Abim',
  'Schall und Rauch',
  'Se lyhyempi korsi',
  'Sea Life',
  'Section 26',
  'Secret Shot',
  'Sektion UDV',
  'Sem Trunfo',
  'Sensus Penduduk',
  'Seths vänner',
  'Seven Eleven',
  'SHE-D',
  'Shenzhen Eagle',
  'Shiba Inu',
  'Shining Pig',
  'Shiv Shakti',
  'Shojo Tyochin',
  'Shy Ant',
  'Siderkongen og kidz',
  'Silence BC',
  'Silver Eagle',
  'Simba Felis',
  'Simple Minds',
  'Sivves straffdubbl',
  'Six Diamonds',
  'Six Samurai',
  'Six Spades',
  'Sjiraffen Erik',
  'Skönheten & odjuren',
  'Slam Dunk',
  'Slam Hunters',
  'Slow Scorpions',
  'Smoking Guns',
  'Smooth Duck',
  'Småsamen med døler',
  "Soalitt`s disipler",
  'Soaring Shou',
  'Soep van Youp',
  'Sofies verden',
  'Space Girls',
  'Space Mutants',
  'Spade Ace',
  'Spade Squad',
  'Sparkling Vintages',
  'Speedy Turtals',
  'Spiders from Mars',
  'Spider Team',
  'Spiel mir das Lied',
  'Spjett Spjong',
  'Stabby with Youngsters',
  'Stara Gara',
  'Steng Oslo nå!',
  'Still Going Turbo',
  'Still Water Runners',
  'Stone Cutters',
  'Storm Gutta',
  'Storm Riders',
  'Strawberry Fields',
  'Stærke scener',
  'Stø pluss',
  'Super Pineapples',
  'Super-Ladies-Danke',
  'Superheroes in Training',
  'Support from Holland',
  'Svag klöver',
  'Svenske og ulykke',
  'SWAT Squad',
  'Sweet Is Middle',
  'Sydän Ja Sielu',
  'Syntax Error',
  'System N K',
  'Søta bror',

  'Ta Kau',
  'Tak czy owak',
  'Take Off',
  'Tare Fare',
  'Tartu 14',
  'Tchin Tchin',
  'Tea for 2',
  'Tea Want',
  'Team Awesome',
  'Team Bo a berg',
  'Team Doc',
  'Team Mayhem',
  'Team NRK',
  'Team Paper Moon',
  'Team Vildmand',
  'Team Yoda',
  'Teddy Bear',
  'Tempo-Knektene',
  'Texan Aces',
  'Texan and Turks',
  'Texan and Yanks',
  'Teyzenýn Yerý',
  'The Four Guys',
  'The A Team',
  'The Abacus',
  'The Alliance',
  'The B Team',
  'The Baltans',
  'The Beatles',
  'The Black Ewes',
  'The Boss Is Back',
  'The Bratz',
  'The Bush',
  'The Canadians',
  'The Clown',
  'The Club Enthusiast',
  'The Colonies',
  'The Contractor',
  'The Crazies',
  'The Crucible',
  'The Daltons',
  'The Dentist',
  'The Distillers',
  'The Eagles',
  'The Fab Five',
  'The Final Cut',
  'The Fitness Boys',
  'The Flying Nudes',
  'The Frush',
  'The Good',
  'The Groovia',
  'The Hons',
  'The Items',
  'The Jets',
  'The Latin',
  'The Little Mermaid',
  'The Lions',
  'The Magic Dogs',
  'The Maltese Falcons',
  'The Marx Brothers',
  'The Metropolis',
  'The Ninjas',
  'The Other Junior Girls',
  'The Palookas',
  'The Patron',
  'The Pirates',
  'The Real Team',
  'The Reco',
  'The Red Devils',
  'The Reds',
  'The Revokers',
  'The Shadows',
  'The Sharks',
  'The Sheriff',
  'The Skilled',
  'The Stig',
  'The Stones',
  'The Stream Team',
  'The Three Stooges',
  'The Tigers',
  'The Untouchables',
  'The Vampires',
  'The Voice',
  'The Weak End',
  'The Weak Link',
  'The Werewolves',
  'The Winner',
  'The Young Mummies',
  'The Young Ones',
  'The Palookas',
  'Them and Us',
  'Thick Toast',
  'Third Eye',
  'Thompson Station',
  'Tian Guan',
  'Tiinan pojat',
  'Þorsteinn Svörfuður',
  'Thread & Needles',
  'Three Nations',
  'Thunder Strike',
  'Tre Kn og en D',
  'Tre knekter og ett S',
  'Tre och en halv män',
  'Triple 8',
  'To gamle og to gode',
  'To tette og en badehette',
  'To Win',
  'Tommys tigre',
  'Top Flight',
  'Top of the South',
  'Top Ruff',
  'Topbridge of course',
  'Tre hunkar en babe',
  'Tre rette og en vrang',
  'Tre sang',
  'Tri Polar',
  'Triple Bacon Cheese',
  'Triple Nine',
  'Troll i eske',
  'Trump No More',
  'Trzech i Czech',
  'Tut tut',
  'Twitch Chat',

  'Ueno Panda',
  'Unguru Bulan',
  'Unholy Alliance',
  'Unlimited Intellect',
  'Unstable Evolution',
  'Usaklig Deigræv',
  'Uten filter',
  'Utmanare Eriksson',
  'Utmanare Övelius',

  'Vaddo Gliders',
  'Vegetable Hotpot',
  'Vera och Marie',
  'Veras Gäng',
  'Verden rundt',
  'Verdens navle',
  'Very Mixed',
  'Vi bygger stikk!',
  'Vi fyra',
  'Vi gör som Einar',
  'Vi i femman',
  'Vi trekk oss ikke',
  'Vickys Vikings',
  'Victorious Secret',
  'Vierde van links',
  'Viking Club',
  'Viking Natural & Hi',
  "Vincent's Friends",
  'Vinir Gylfa',
  'VIP Travel',
  'Visst nappar det',
  'Vitamin',
  'Viva Plambata',
  'Volatile Company',
  'VP (b)anker IMP',

  'Waikato Bays',
  'Walking Dead',
  'Wambon Bodi',
  'War of Roses',
  'Washed Up',
  'We Are Bye',
  'We Are 6',
  "We Don't Know Yet",
  'We Meet Again Mr A.',
  'Well Done',
  'Well Fitted',
  'Well Wise',
  'West Coast',
  'What the Heck',
  "What's Up?",
  'Where Is My Mind',
  'Whisky Team',
  'White Bears',
  'Wide Deep and Bugs',
  'Wild Cats',
  'Wild Griffins',
  'Wild Horses',
  'Winter Is Coming',
  'Wrang Lead',
  'Wrecking Ball',
  'WT og Kaffeprinsessen',
  'Wuwen Xidong',
  'Würst und Weißbier',
  'www guts com',

  'X-Men',
  "Xi'an Qiaoyou",
  'Xiu Xing Dui',

  'Y.Y.Y.D.',
  'Yali Capkini',
  'Yani and Friends',
  'Yanjing Puzi',
  'Yarralumla Yabbies',
  'Yellow and Blue',
  'Yilu Pingan',
  'YOI Returns',
  'You Can Call Me Al',
  'You Must Win',
  'You Never Walk Alone',
  'Yoyo 5',
  'Young and Broke',
  'Young Guns',
  'Young Guys',
  'Young Warriors',
  'Young Driver',
  'Young Swedes',
  'Young Oldies',
  'Your name?',
  'Yu Yi Dui',
  'Yuruyen Kosk',
  'Yuyi Xizi',

  'Zaza Boys',
  'Zhejiang Development',
  'Zia and Friends',
  'Ziemlich gut',
  'Zimm Friends',
  'Zsuga Liga',

  'Øst-Vest',
  'Åmål Hulta',
);

my %MULTI_TYPOS =
(
  '0% Eriksson' => ['0 eriksson'],
  '1 Non Blonde' => ['1 noen blonde', '1 none blond', '1 none blonde'],
  '10 Tricks' => ['10 trikc'],
  '101.yil' => ['101. yil'],
  '3 Idiots + 1' => ['3 idiots +1', '3 idiots + i'],
  '4 Trèfles' => ['4 trefles 1', '4 trefles1',
    '4trèfles', '4 treffles', '4trèfle'],
  '40 Årskrisa' => ['40-Årskrisa'],
  '5 Ess' => ['5-ess'],
  '6 Notrump' => ['6 no trump'],

  "A'ppetit" => ["a'peatit", "a'ppetýt"],
  'AG laget' => ['ag-laget'],
  'Albayrak67' => ['albayrak 67'],
  'Alex is Beautiful' => ['alex is beatiful'],
  'All Stars' => ['all-stars'],
  'Alle presidentens menn' => ['alle presidentens'],
  'Ann Lill (i)Da' => ['anne lill (i)da'],
  'Applied Math' => ['aplied math'],
  'Apres-Bridge Champs' => ['apres bridge champs'],

  'Babes Amazones' => ['babes-amazones'],
  'Bağcı Döven' => ['bagci doven'],
  Baneet => ["Baneet's IV"],
  'Bangkok Kimono' => ['bangkok kimino'],
  'Baris hemen simdi' => ['Barýþ Hemen Þimdi'],
  Begijntje => ['begijnt je'],
  'Best uten kort' => ['best uden kort'],
  'Beverly Hillbillies' => ['beverly hillbillie'],
  'Bid72' => ['bid 72'],
  'Big Guns' => ['big gun'],
  'Big Makie' => ['big makie och co'],
  'BK Gröna Kvistar' => ['BK Grön Kvistar'],
  'Blaksets Bin' => ['blacksets bin', 'blaskets bin'],
  BNMR => ['b n m r'],
  'Bodø Glimt førr evig' => ['bodø glimt førr evi'],
  'Boro Boss' => ['boro-boss'],
  'Brian Is Beautiful' => ['brian is beatiful'],
  'Bros1005' => ['bros 1005'],
  'Butterfly from HK' => ['babochka s hk'],

  'Ca. et halvt tonn' => ['ca et halvt tonn'],
  'Californian Aces' => ['california aces'],
  "Captain's Four" => ['captains 4'],
  "Captain's Team" => ["capitan's team"],
  'China Development' => ['zhongguo kaidi'],
  "Colonel's Team" => ["colonel's  team"],
  'Coś na razie' => ['cos narazie'],
  'Croatian Pirates' => ['cro pirates'],
  'Curry Eaters' => ['curry  eaters'],

  'Daniel med vänner' => ['daneil med vänner'],
  'Danish Dynamite' => ['danish dynamit'],
  'De escalatie sensatie' => ['de escalatie sensat'],
  'Den gyldne omvei' => ['den gylne omvei'],
  "Dera's Deckhand" => ["deora's deckhand", "dera's deck"],
  'Desperate Bridge Wives' => ['desperate bw', 'desperate bridgewi'],
  'Det är helt självklart' => ['det är helt självkl'],
  "Devil's Coup" => ['devils coup'],
  'Diamonds Are Forever' => ['diamonds are foreve'],
  'Down Under' => ['doun under'],
  'Dr. Romantic' => ['dr.romantic'],
  'Dr. Worrawat' => ['dr.worrawat'],
  'Dragon Kiddies' => ['dragon kiddie'],
  'Dronninga med prins' => ['drnninga og pri',
    'dronninga med pri', 'dronning og prinses'],

  'Ebenius Crew' => ['ebeneius crew', "ebeneius crew'"],
  'Eiydes discipler' => ['eiydes disciple'],
  'Elses Fanklubb' => ["elze`s fanklubb"],
  'En myra tre elefanter' => ['en myra tre elefant'],
  'Et par sama og 2 ens' => ['et par sama og 2 en'],

  'Fast and Furious' => ['fast & furious'],
  'FF 69' => ['ff  69'],
  'Field Tambun' => ['field t'],
  'Five Clubs Partyband' => ['five clubspartyband'],
  "Flint's Crew" => ["flint`s crew"],
  'Flora and Friends' => ['flora && friend'],
  'Fozzilet og Kidza' => ['fossilet og kidza'],
  'Fuglen har fløyet' => ['Foglen har fløyet'],
  'Freak City' => ['freak-city'],

  'Game On' => ['game-on'],
  'Gammel Oppland m/co' => ['gammel oppland',
    'gammel opland m/co'],
  "Gary's Boys" => ['garys boys', 'gary´s boys'],
  'Good Men' => ['good man'],
  'Guyub57' => ['guyub 57'],

  "Hagen's Heroes" => ["hagen`s heroes", 'hagens heroes'],
  Hammershark => ['hammershark deluxe'],
  'Hands and Hearts' => ['hands & hearts'],
  'Hao Ran' => ['hao-ran'],
  'Heldige Olav' => ['heldige olav :)'],
  "Hell's Angels" => ['hells angels'],
  'Her vantar blaðsíðu' => ['her vantar bladsidu'],
  'Hey Yo' => ['hey yo!!'],
  'Holmenkollen' => ['h-kollen'],
  'Hope & Pray' => ['hope n prey', 'hope and prey', 'hope & prey'],
  'Hopp i sang' => ['hoppa i sang'],
  'House Klave' => ['klave houses', 'klave house', 'kleva house',
    'kleva houses'],
  'Hurlumhei' => ['hurlumhei..'],
  'Hvalen og tjukkasene' => ['hvalen og tjukkasne', 'hvalen & tjukkasene'],
  'Høyland & Kjell-Vidar' => ['høyland&kjell-vidar',
    'høyland&kjellvidar'],

  'Ice Jacks' => ['ice jack', 'ice jaks'],
  'Ikke akkurat kjedelig' => ['ikke akkurat kjedel'],
  'India Blues' => ['indian blues'],
  'Indian Mavericks' => [
    'india mavericks', 
    'indian mavricks',
    'mav prodigies', 
    'maverick all star', 
    'maverick all stars',
    'mavericks prodigies',
    'mavericks all stars', 
    'mavericks all star', 
    'the maverick',
    'the mavericks'],
  'Itinérants du bridge' => ['iti du bridge', 'itin du bridge'],
  'Iyi Takim' => ['Ýyý Takim'],

  'Jamm & Co' => ['jamm & co.', 'jamm && co.'],
  'Junioren mit Upgrade' => ['junioren mit upgra'],

  K1 => ['k01', 'k-1', 'k 1', 'k one', 'k 1 plus'],
  K2 => ['k2 rebid'],
  'Kasimirs Dream Team' => ['kasimirs dreamteam'],
  "Keni's Dream" => ["keni's", "kini's", 'p.keni'],
  'Kick Back' => ['kick-back'],
  'King Geoffrey' => ['king groffrey'],
  'Kisa metraj' => ['ksk kisa metraj'],
  'Koos Bros' => ['Koos Bro´s', "koos bro's"],
  'Kuaile Huoniao' => ['Kuaile Houniao'],
  'Kungshamns Sega Gubbar' => ['kungshamns sega gub'],
  'Kuvayi Milliye' => ['kuvai milliye'],
  'Kwang Hwa' => ['kwuang-hwua'],

  "L'Orange" => ["l' orange"],
  'La Linea med eller uten ball' => ['la linea med ell', 
    'la linea med elle'],
  'Lao Xiongdi' => ['lao xiong di', 'lao xipongdi'],
  'Lawrence of Arabia' => ['lawrence of arab'],
  'La Vista' => ['la vista team'],
  'Lakk & Lær' => ['lakk og lær', 'lek & lær', 'lokk & lur',
    'litt lakk og lær', 'lakk lær'],
  'Larsson på taket' => ['larsson pa taket'],
  'L.C. is Beautiful' => ['l.c.is beautiful'],
  'Leichte Brise Südwest' => ['leichte brise südw'],
  'Lieber tod als Zweiter' => ['lieber tod als zwe'],
  'Lindenthal und Freunde' => ['lindenthal und fre'],
  "Lise (i)DA" => ['lise da', 'lise da!', 'lise lill (i)da', 
    'lise(i)da'],
  'Lucky 13' => ['lucky13'],

  'M. Green' => ['m green'],
  'Magic Eyes' => ['majic eyes', 'm e'],
  'Man Harr det man har' => ['man harr det man ha'],
  'Manchester United' => ['man u', 'man utd'],
  'Männer mit ELAN' => ['2 männer mit elan'],
  'MC 953' => ['mc953', 'mc_953', 'mc  953'],
  'Mickey Two Clubs' => ['mickey 2c'],
  'Mind and Matter' => ['mindand matter'],
  'Missão Impossivel' => ['missão impossível'],
  'Monotone Memories' => ['monotona memories',
    'monotona memoirs'],
  'Monty Zeebergs FC' => ['monty zeebergs', 'minty zeebergs fc'],
  'Mr Blackout' => ['mr.blackout'],
  'Ms. Guggenheim' => ['ms. gugenheim'],
  'Murphys lag' => ['murpyhs lag'],
  'Mystery Foursome' => ['mystery 4some'],

  'Nice and Monsters' => ['nice monsters'],
  'Nicolais fanclub' => ['nocolais fanclub'],
  'Nilslands Slowfoxes' => ['nilsland slowfoxes', 'nilsland slowfoxers'],
  'Ninjas in Pyjamas' => ['ninjas in pijamas'],
  "No He Isn't" => ['no he isnt'],
  'No Surprise' => ['no surprice'],
  'No Trump' => ['no trumph'],
  'Nordic Five' => ['nordic 5', 'nordil five'],

  'Oh Ya!' => ['oh ya'],
  'Old-Man' => ['old man'],
  'Outsiders' => ['out siders'],

  'Pen Pineapple Apple Pen' => ['ppap (midori)'],
  'Pigerne på tur' => ['pigerne pa tur'],
  'Plan B' => ['plan b bridgeklub'],

  'Quanzhou Development' => ['quanzhou fazhan'],
  'Queen and Knights' => ["queen's & knight"],

  'Rapan & Jezus' => ['rapan and ezis'],
  'Real Maramma' => ['real maremma'],
  'Reps und Wodniansky' => ['reps und wodniansk'],
  'Return the VI Counties' => ['ret.the vi coun',
    'ret.the vi count'],
  'Saint Titus' => ['st titus', 'st. titus'],
  'Sakurai' => ['japan sakurai'],
  'Sannas Änglar' => ['sannas äangler'],
  'Sektion UDV' => ['section udv'],
  'Sem Trunfo' => ['sem trumfo'],
  'Silver Eagle' => ['silver  eagle'],
  'Sivves straffdubbl' => ['sivves straffdubbl.', 'sivves straffdbl',
     'sivves...'],
  'Six Diamonds' => ['six diamond'],
  'Six Samurai' => ['six samurais'],
  'Skönheten & odjuren' => ['skönht. och odjuren'],
  'Slam Hunters' => ['slam hunter'],
  'Sofies verden' => ['sofies world'],
  'Soep van Youp' => ['soep van yoop'],
  'Speedy Turtals' => ['spiddy turtals'],
  'Stabby with Youngsters' => ['stabby with youngst'],
  'Superheroes in Training' => ['superheroes in trai'],
  'Support from Holland' => ['support from hollan'],

  'Team NRK' => ['tram nrk', 'tm nrk'],
  'Tempo-Knektene' => ['tempo-knehtene'],
  'Texan Aces' => ['texa aces', 'texaan aces', 'texan  aces',
    'tn aces'],
  'The Four Guys' => ['the 4 guys'],
  'The Clown' => ['the_clown'],
  'The Magic Dogs' => ['the magicdogs'],
  'The Maltese Falcons' => [
    'the maltese',
    'maltesien falcon'],
  'The Other Junior Girls' => ['the other jnr girls'],
  'The Palookas' => ['the_palookas'],
  'The Weak End' => ['the weakend'],
  'Them and Us' => ['them & us'],
  'Thunder Strike' => ['tunder strike'],
  'To tette og en badehette' => ['to tette',
    'to tette og en bade'],
  'Tre knekter og ett S' => ['tre knekter og etts'],
  'Tre rette og en vrang' => ['tre rette og en vra',
    'tre rette og en'],
  'Troll i eske' => ['tre troll i eske', 'tre troll ...'],

  'Unguru Bulan' => ['unguru  bulan', 'unguru bulanu'],

  'Victorious Secret' => ['victorius secret'],

  "We Don't Know Yet" => ['we dont know yet'],
  'Wild Cats' => ['wild cat'],

  'Waikato Bays' => ['wiakato bays'],
  'What the Heck' => ['whattheheck'],
  'WT og Kaffeprinsessen' => ['wt og kaffeprinsess'],
  'Wuwen Xidong' => ['wuwenxidong', 'wuwendongxi'],

  'X-Men' => ['x men'],

  'Yellow and Blue' => ['yellow&blu'],
  'Young and Broke' => ['young&broke'],
  'You Never Walk Alone' => ['you never walk'],
  'Yuyi Xizi' => ['yuyi(xizi)'],

  'Zhejiang Development' => ['zhejiang fazhan']
);

my @SINGLE_WORDS = qw(
   2Q2K 3D 6L 10CC 7heart

   Aardvarks Aces Acetaldehyde Adventure Adventurers Agamemnon 
   Agressor Ahornet Aida Alias Alliance Alliansen Allstars 
   Alternativlos Altraists Amarillo Ambassador Andromeda Andrzejki 
   Anglian Anglers Anglophones Anubis Apaci Aperol Appellkameratene 
   Apples Apply Aquarius Arachfobia Archies Aristos Armani Arsenal 
   Asparagus Assassins Asterix Astra Astro Astronotlar Atlantic 
   Atom Auroras Austerlitz Autostrada Avalanche Avatar 

   Bachelor Badger Badminton Bager Balalaika Balkantourist
   Bamsa Banana Bananasplit Banjanas BarDeZi Barracuda Barsss 
   Baryton Battleship Beauty BeRe Berserk Besties Bingbang Binkie 
   Biscuit Blackwood Bling Blondie Blues Blueberry Blues Bobbisarna 
   Boldplay Bolero Bongiorno Boogies Boomerang Boomers Boomz Borat
   BOVE Bravehearts Brexit Bricklayer Bridgechamp Bridgeministeriet 
   Bridgenoobs Bridgestars Bridgeyes Brigada Bromigos Bronzeados
   Brother Brudarna Bubba Bubble Buddies Budgivarna Buks Bulk 
   Bulldozer Bumerangas Bunnies Búvörusamningarnir Bye

   C2H5OH Cancan Cardtossers Cargo Cartoon Casuals Caveiras Censored 
   Ceviche Challengers Changes Cheetahs Chicks Chokladmåndag Cinema 
   Claim Coaches Cogito Commandos Comrade Conejos Confucius Contact 
   Contra Coolers Corner Cornemuse Couch Counterstrike 
   Cranberry Crash Cremaster Cre8ive Crocodile Crush Cyclops
   
   Danger Dazzle Debutantes Deceptive Dekisugi Demolishers Desperados 
   Destroyers Deuces Dialect Dilettanti Doctors Doktorinn Dokunulmazlar 
   Donjulio Donvito Dracula Dragon Dragonite Dreizehn Drink Drinteam 
   Druids DuckNDales Durum Dusteforbundet Dyret

   Eagles Eastward Eliminator Emerald Engineers Enigma Enjoy 
   Espada Etik Everest Evil 

   Familia Fantasia Fantasy Fant4stic Farmen Filbyter Filosofene 
   Finest Firtinayt Fisk Flamboyant fopen Forehand Foreigner Forfot 
   Formidables Frenemies Friends Francophones Freak Frillegänget 
   Frirond Frivolt Frogs Froh Funny

   Galaxy Gehaktmolen Geetanjali Gentle Geriatrix Geysir Giants Gizmo 
   Gladpack 
   Gladyator Globetrotters GloryGlory Godfather Gogoplata Goldfish 
   Goodfellas Gosho Grand Grads Greven Gris Gruken Gryphon Guardians
   Gubbvarning Guests Gulebjorn 
   Gunsmoke Gwenchanna

   Hangarounds Haoyun Happy Haustbragur Hawks 
   Hästpojkarna Hermitage Heros HERZdame 
   HeSa Hexagon Hey Highlanders Hiiimmm Hiphiphurra Hjerterdamer 
   Hobbits Hobby Hollywood Holmenkollen Honeymoon Hopfenkönig 
   Hornets Hufflefluffs Huhu Hungael Hunhun Hurra Hurrablondina Hurricane 
   Hybrid

   Icebergs Icemany Ikarus Impact Impas Impala IMParator IMPed 
   Imponderables Inception Indi Infinity Instructor Invincible 

   Jabba Jackalls Jarntjaldid Jenterne Jeparadise Jegenspiel 
   Jernbaneverket JJJ Job Jocker JoJo Joker Journalists Jugermaister 
   Juice Jumentos Jupiter Juryn Juubilar Juveniles

   Kaktus Kalmaar Kamelåså Kamikaze Kampai Kangaroo Kanin Karo Kartalite 
   Kartel Kat Kayal Kellobello Kiminoto Kingkong Kingpin Kings Kismetli
   KISS KKKQ Knife Kohinoor
   Kompisarna Kontra Kuglana Kuhmilch 

   Lady Lalaland Lanterfanters Laplanders Lazy Lebensohl Leviathan 
   Liggeunderlaget Lion Lions Lirarna Liverbird Lucky LVBridgeBums 
   Lykkeland Løwene

   Maestros Maestroi Magi Magic Magister Magma Magnum Maharaja 
   Major MajorB Majorn 
   Majority Malambo Mamahai Marihønelaget Marres Mars Marvelous Mascot 
   Masdjävlar Maseluta Mask Masterminds Masters Matrix Matruska Maven Maxi 
   Maximus Meow Mercury Meta Microchiroptera Midas 
   Miklagard Milady Mingo Mirage Mismatch Mixarna Mjøskameratne MMMM 
   Mojito Mongos Muhabbet Muscolo Måsen

   Nanda NASA Natural Naturalists NEDBULL Nemesis Nemo Neverclaim 
   Nightingale Nimetön Noctis 

   Octopus Octopussy Okay Okra Olavsfestdagene Olrudbanden Olsenbanden 
   Onyx Opal Opera Opps Optimists Optimus Orca Osss Outsiders Overdeck 
   Overivrig 

   Pacers Pacific Paddys Pandeka Pantherasia Paradigma Partizan 
   Partypack Passifistene Patriot Patron Pegasus Pelegrinners Pentagon 
   Perestrojka Pericolo Petrapak Phatake Piekni Piglet Pikkukarhu 
   Pingüinos Pioneers Playwell Pompeiopolis Pontiac Poppeye Porcelain
   Poseidon Potlimit Potteplante Powerchicks Pragmatic Prakker 
   Preempters Pretendents Promise Proteus ProWenger Psychobilly 
   Pusten Påskevennene

   Qingyu Quaggas Quasar Quattro Queens Quintet Quinze

   Rampage Rapid Räddarna Real Reason Reklamtrion Relax Relaxation 
   Reloaded Remontada Resisposse Revokestars Rippy Riviera Rivok 
   Robocop Rollers Rovers Rozmarin Ruterdamene

   Sabres Saga Sailor Sakura Sakurai Saladmasters Salokin Sammartini
   Sapphire Saturn Saudagar Scandinavia Scarecrow Schneewittchen 
   Scientists Secure Senator Sheep Shengxing Show Shokolata Sieja 
   Sildesalgslaget Silverfox Simple Sindbad Singapole Sirius Sjøsamen 
   Skip Skitur Skylark Skywalker Slammers Slappfisker Slufsa Smash 
   Småveitjan Snapper Snipers Soho Solaris Sonata Space Spark 
   Spartans Specialist Spekkhogger Spuds Squeeze Stamina Stampede 
   Star Starmen Statusquo Stayman Stifinnern Storbonden Strategen 
   Streamline Stridsbyn Stridsvagn Stålfarfar Suburbian Sunset 
   Sunshine Sushi Svanen Syttisju Sømnakameratene Såpeopera

   Tailors Takalaiton Takeoff Takeout Talasam Talliri Tank Tannlegene 
   Taurus Tbone Tecza Tempo Tequendama Theater Theme Theseus 
   Thrash Tibetmunkene Tiburones Tigers Titanik Titans Tivoli 
   Tohundre Tolerant Tootsie Torpedo Tosca Totem Trèfles Tricksters 
   Trickstar Triton Trollene Truft Tsunami Tulip Turbo Turbofart 
   Turnips Turquoise Tusio Tutarli Tutu Tvist

   UFO Ugh Ulvene Underdogs Unexpected Ungdomslaget Upplyfting 
   Upsurt Uragan Utkantnorge Utur

   Vaffelrøre Valle Vendetta Vengadores Venteliste Vermonsters 
   Veteranerna Vibrant Victory Vietcong Viking Villmarksgutta 
   Villspikka Vilttiketju Vintage Volcanes Vulcano

   Walpurga Warriors Welovebridge Westward Wham Windrunners Winkiboy 
   Wizards 

   Xman Xtrouble XXX XXXL XXXSL XXXXXYXY

   Yakinda Yarborough Yengec

   Zadra Zambet Zebras Zero Zeus Zqueeze Zhanma Zhiguli Zombi Zoo 
   Zorro Zugzwang Zwierzak
);

my %SINGLE_TYPOS =
(
  'Aar Paar' => ['aaarpar'],
  Aardvarks => ['aardvark'],
  'Adams Family' => ['adamsfamily'],
  'Alster Spree' => ['alsterspree'],
  Altraists => ['altrastis'],
  Ambassador => ['ambassadors', 'ambassdor'],
  Andrzejki => ['adrzejki'],
  Anglers => ['anglelers'],
  'Apollo Soyuz' => ['apollosoyuz', 'apollosoyouz'],
  Appellkameratene => ['apellkameratene'],
  Aquarius => ['acquarius'],
  'Arctic Farmers' => ['farmers'],
  'As vezes' => ['asvezes'],
  Assassins => ['assasian', 'assasins'],
  'Atomic Bridge' => ['atomic'],

  Balkantourist => ['balkanturist'],
  Barracuda => ['barakuda', 'baracuda'],
  'Big Bang' => ['bigbang'],
  'Bleu Lights' => ['bleulights'],
  Boomerang => ['bumerang'],
  'Bosse Superettan' => ['bosse'],
  Buaigh => ['buaijh'],
  Bulldozer => ['buldozer', 'buldozzer'],
  Búvörusamningarnir => ['buvorusamningarnir'],

  'Cards Against Tursan' => ['cardsagainstursan'],
  'Carpe Diem' => ['carpediem', 'carpedium'],
  'Cast Bordo' => ['bordo'],
  Cheetas => ['cheetaas'],
  'China Development' => ['zgkd', 'zhongguokeda'],
  Cre8ive => ['cre8tive'],

  'Dandy Lion' => ['dandylion'],
  'Das Autobahn' => ['autobahn'],
  Dilettanti => ['dilletanti'],
  'Dream Team' => ['dreamteam'],
  Drinteam => ['drin'],
  Deuces => ['duces'],

  'England Swings' => ['englandswings'],
  'Expert Cooking' => ['expertcooking'],

  'Fan Art' => ['fanart'],
  Fant4stic => ['fant4stc'],
  Flamboyant => ['flamboyan'],
  Forehand => ['forhand'],
  Formidables => [
    'formadables', 
    'formadeble',
    'formadibles', 
    'formedables',
    'formidabble', 
    'formidabels',
    'formidable', 
    'formidales',
    'formidbles',
    'formiddable', 
    'formiddables', 
    'fromidables'],
  Frogs => ['frog'],
  'Full House' => ['fullhouse'],

  Gehaktmolen => ['gehaktmolenbeloften'],
  'Gin Tonic' => ['gintonic'],
  'Good Mood' => ['goodmood'],
  'Green Eyes' => ['greeneyes'],
  Guardians => ['guardianes'],
  Gunsmoke => ['gunnsmoke'],

  Hjerterdamer => ['hjerterdamene'],
  'Honey Milk', => ['honeymilk', 'honeybeemilk'],
  Hornets => ['hornet'],
  Hästpojkarna => ['hastpojkarna'],

  'Ice Cool' => ['icecool'],
  'Ice King' => ['iceking'],
  Imponderables => ['impoderables'],
  'India Blues' => ['indiablues'],
  'Indian Mavericks' => [
    'mavaricks',
    'maverick',
    'mavericks',
    'mavrick',
    'mevericks'],
  'Indonesian National Sports Week' => ['pon'],

  'Jamm & Co' => ['jamm'],
  Jarntjaldid => ['járntjaldið'],
  Jeparadise => ['jeparadise'],
  'Jiangsu YY' => ['jsyy'],
  'Joy Division' => ['joydivision'],
  Jupiter => ['jupitor'],

  'Kuvayi Milliye' => ['kuvaimilliye'],

  'Last Arrival' => ['lastarrival'],
  Lebensohl => ['lebenshol'],
  'Lucky Six' => ['luckysix'],

  Maharaja => ['maharaj', 'maharaaj'],
  Majorn => ['majoren'],
  'Mind and Matter' => ['mindandmatter'],
  Mismatch => ['missmatch'],
  Mjøskameratne => ['Mjöskameratene'],
  'Monotone Memories' => ['monotona'],
  Måsen => ['Måsan'],

  Natural => ['naturel'],
  Naturalists => ['nature', 'naturalistene'],

  'Occupy Taksim' => ['occupytaksim'],
  'Off the Bend' => ['offthebend'],
  Onyx => ['onix'],
  Opps => ['opsy'],
  'Otra Vez' => ['otravez'],
  'Outsiders' => ['outsider', 'outsiderne'],

  Pacific => ['pacyfic'],
  Pantherasia => ['phanterasia'],
  'Paris Match' => ['parismatch', 'parimatch'],
  Pelegrinners => ['pelegrinness', 'peligrinners'],
  Pericolo => ['periculo'],
  Pioneers => ['pioneees', 'poineers'],
  'Prawie Reprezentacja' => ['prawiereprezentacja'],
  Preempters => ['preemptors'],
  Pretendents => ['pretendentas'],

  'Quanzhou Development' => ['qzfd'],
  Quattro => ['quatro'],

  'Red Robot' => ['redrobot'],
  'Red Sky' => ['redsky'],
  'River Friend' => ['riverfriend'],

  Sammartini => ['sammarti'],
  'Sana Soz' => ['sanasoz'],
  Sapphire => ['saphire'],
  'Sayin Abim' => ['sayinabim', 'sayinabým'],
  Scientists => ['science'],
  Sildesalgslaget => ['Sidesalaglsaget'],
  Silverfox => ['silfurrefir'],
  'Spade Squad' => ['spadesquad'],
  Spartans => ['saprtans', 'spartan'],
  Squeeze => ['squeze', 'squiz'],
  Starmen => ['starman'],
  'Stone Cutters' => ['stonecutters'],
  Strategen => ['stratagen'],
  Syttisju => ['sytti'],

  'Texan Aces' => ['texanaces', 'tnaces'],
  'The Ninjas' => ['ninjas'],
  'The Pirates' => ['pirates'],
  'The Vampires' => ['vampire'],
  Theater => ['teatr'],
  Titans => ['titan'],
  'Tri Polar' => ['tripolar'],
  Tricksters => ['trcksters'],
  Turquoise => ['turkuaz'],

  Underdogs => ['underdog'],

  'Vegetable Hotpot' => ['vegetable'],
  Vilttiketju => ['viltiketju', 'villtiketju', 'vilttiketsu',
    'viltti'],

  Welovebridge =>['welovedbridge'],
  'Wild Griffins' => ['wildgriffin', 'wildgriffins'],
  'Winkiboy' => ['winkyboy'],
  Wizards => ['wizard'],

  'YOI Returns' => ['yoi'],

  'Zhejiang Development' => ['zjfz']
);


sub set_hashes
{
  my ($method, $key) = @_;

  $method->(\@MULTI_WORDS, \%MULTI_TYPOS,
    \@SINGLE_WORDS, \%SINGLE_TYPOS, $key);
}

1;
