#!perl

use strict;
use warnings;
use v5.10;
use utf8;
use open ':std', ':encoding(UTF-8)';

package Tags::Fun;

our @ISA = qw(Exporter);
our @EXPORT = qw(set_hashes);

my @MULTI_WORDS =
(
  '0% Eriksson',
  '1 1/2',
  '1-2-1',
  '1 Non Blonde',
  '1 over 1',
  '10 Tricks',
  '101.yil',
  '1x2',
  '123 Jättebra',
  '16 Flights',
  '19 mayis 1919',
  '2-2-1T',
  '2 ess og to konger',
  '2 Generations',
  '2 med lite mer hår',
  '2 me og 2 uten',
  '2 over 1',
  '23 Generation',
  '246.5 Meters',
  '2A+3I',
  '3 Baritona',
  '3 Frakkar',
  '3 Idiots + 1',
  '3 troll og en bukk',
  '3..2..1..Meins!',
  '33 Max',
  '4 Hjerter',
  '4 Majori',
  '4 Nat',
  '4 pataa',
  '4 Trèfles',
  '40 Årskrisa',
  '5 Ess',
  '5 kommer tillbaka',
  '50 med omnejd',
  '50 shades of cards',
  '55 med omnejd',
  '6 Notrump',
  '6 Spades',
  '60 y 20',
  '8-5-0-0',
  '88 KN',
  '88 Loreng',
  '88 Red',
  '88 Merah Senior',
  '88 Senior',

  'A Maze',
  'A Team',
  'A2',
  'Ace up Our Sleeve',
  'Aces & Deuces',
  'Ad Hoc',
  'Adams Family',
  'Advance Team',
  'After Eight',
  'AG laget',
  'Against All Odds',
  'Aina Malttia',
  'Ala vill til Himlen',
  'Albayrak 67',
  'Albrekts T-Bone',
  'Alex is Beautiful',
  'All Female Panel',
  'All In',
  'All Lions',
  'All Stars',
  'All Will Be Alright',
  'Alle presidentens menn',
  'Almost Famous',
  'Almost Female Panel',
  'Almost Juniors',
  'Alt for rognan',
  'Also Changes',
  'Alzheimer Aces',
  'AN-124',
  'Andre boller',
  'Angel of Harlem',
  'Angels & Demons',
  'Angry Birds',
  'Ann Lill (i)Da',
  'Annas Fans',
  'Anti Revenge',
  'Anup Dhar',
  'Apa Heili',
  'Apple Pie',
  'Applied Math',
  'April 30',
  'Apollo Soyuz',
  'Apres-Bridge Champs',
  'Arctic Farmers',
  'Arctic Powerchicks',
  'Atomic Bridge',
  'Ave Magma',
  'Ave Maria mä bihang',
  'Awesome Avengers',
  'Aylan Kurdi',
  'AZS Buboslavia',

  'B Team',
  'Baba Blues',
  'Babes Amazones',
  'Baby K',
  'bACEd in Austria',
  'Bad Beat',
  'Bad Man',
  'Bağcı Döven',
  'Bangkok Kimono',
  'Bar-Su',
  'Bara brudar',
  'Baris hemen simdi',
  'Barny Army',
  'Baska Yok',
  'Bastion Smaku',
  'BBO Lovers',
  'Bea & Family',
  'Beer Card',
  'Bela e os Monstros',
  'Bermuda Squad',
  'Best Friends of Gun',
  'Best i baren',
  'Best of Hessen',
  'Best uten kort',
  'Bettans Busar',
  'Beautiful Yan',
  'Berre Lækkert',
  'Beverly Hillbillies',
  'Beyaz Marti',
  'Bid 72',
  'B.I.G.',
  'Big Bang',
  'Big Boss',
  'Big Chef',
  'Big Guns',
  'Big L',
  'Big Makie',
  'Big Mi?',
  'Big Utao',
  'Binua Landak',
  'Bizim takim',
  'Bjuda på',
  'BK Gröna Kvistar',
  'Black Adders',
  'Black Castle',
  'Black Cats',
  'Black Gold',
  'Black Hole',
  'Black Knife',
  'Black Label',
  'Black Pit',
  'Black Sea',
  'Black Swan',
  'Black Widows',
  'Blaksets Bin',
  'Blanda drops',
  'Bleu Lights',
  'Bloody Mary',
  'Blue Bamm',
  'Blue Chip Swedes',
  'Blue Diamonds',
  'Blue Hot',
  'Blue Note',
  'Bo Gulasch',
  'Boas disipler',
  'Bob Bob',
  'Bobbos Gäng',
  'Bobler og brus',
  'Bobo Dird',
  'Bodø Glimt førr evig',
  'B.O.N.G',
  'Bona Fide',
  'Boogie Knights',
  'Boro Boss',
  'Bosse Superettan',
  'Boye B Fan Club',
  "Boys'n' Girls",
  'Brian Is Beautiful',
  'Bridge Code',
  'Bridge Fan',
  'Bridge Friends',
  'Bridge Hunters',
  'Bridge Lovers',
  'Bridge over Nations',
  'Bridge Plus',
  'British Invasion',
  'British Lions',
  'Brown Sugar',
  'Brødrene & co',
  'Brødrene Dal',
  'Bugih Lamo',
  'Bullgalian All Star',
  'Butterfly from HK',

  'Ca. et halvt tonn',
  "Cai's Bird",
  'Californian Aces',
  'Can Am Express',
  'Can Can',
  'Captain Blood',
  "Captain's Four",
  "Captain's Team",
  'Card Warriors',
  'Carla en haar kids',
  'Carpe Diem',
  'Carstens Kofötter',
  'Casino Floor',
  'Casino Royal',
  'Cast Bordo',
  'Cathy & Ewa',
  'Cat Daddy',
  'Cecils venner',
  'Cha Cha Cha',
  'Chateau Latour',
  'Cherno More',
  'Czech i trzech',
  'China Development',
  'Circle the World',
  'Cim Bom Bom',
  'Cheap Tricks',
  'Club 7',
  'Coach K',
  'Coco Cat',
  'Cold Light',
  'Come Farsi',
  'Cood Life',
  'Counter Strike',
  'Country Boys',
  'Coup de grace',
  'Crashtest Dummies',
  'Crème de la crème',
  'Croatian Pirates',
  'Crush Lack',
  'Curry Eaters',
  'CU+1',
  'Czech Back',

  "D'Artagnan",
  'Daar gaan we',
  'Da Big Storm',
  'Dai Meng Yi Dao',
  'Daisy Chain',
  'Dami Plus',
  'Dankjewel doe maar',
  'Daniel med vänner',
  'Danish Dynamite',
  'Danish Guns',
  'Dark Baroque',
  'Dark Blues',
  'Das Autobahn',
  'Das rote Pferd',
  'De edruelige',
  'De escalatie sensatie',
  'De kontorsanställda',
  'De uovervinnelige',
  'Dead Pig Nerds',
  'Delft Buiten',
  'Delta-Variante',
  'Den glade alke',
  'Den gyldne omvei',
  'Den maskerte hevner',
  'Denktank 7',
  'Denmark Baby',
  'Dennis Crew',
  'Der Untergang',
  'Der alte Gro',
  'Der wilde Süden',
  'Desert Warriors',
  'Desperate Bridge Wives',
  "Dera's Deckhand",
  'Det är helt självklart',
  'Det nappar på kroke',
  'Deus vult',
  "Devil's Coup",
  'DG Stalwarts',
  'Di derre',
  'Diamonds Are Forever',
  'Die Mauer',
  'Die Schönen und di',
  'Die vier vom Rhein',
  'Die wazige Passers',
  'Dinamo Bridge',
  'Dinner Club',
  'Disco Ninjas',
  'Dziwiszow Jazz',
  'Do You Fire?',
  'Doctor Vicho',
  'Don Bernardo',
  'Don Julio',
  'Don Revival',
  'Double Dummy',
  'Double Jungle',
  'Double R',
  'Double U',
  'Double Yusuf',
  'Down Under',
  'Dr. Dan',
  'Dr. Romantic',
  'Dr. Worrawat',
  'Dracula 2',
  'Drag Queens',
  'Dragon Cartoon',
  'Dragon Kiddies',
  'Dragon Piggies',
  'Dream Team',
  'Dronninga med prins',
  'Duc and Sons',
  'Dutch Highlanders',
  'Dyr-e-go',
  'Dyra Englund',

  'Eager Eagles',
  'Ebenius Crew',
  'Ege2/1',
  'Eides språksjov',
  'Ein Wort noch',
  'Eiydes discipler',
  'Ekkert að frétta',
  'El Cid',
  'El Nino',
  'Elisabeths änglar',
  'Elses Fanklubb',
  'Elusive 52',
  'Ember Spirit',
  'Empty Vessels',
  'En bridgespiller ..',
  'En myra tre elefanter',
  'En passant',
  'En påse nötter',
  'Endless Highway',
  'Endless Love',
  'England Swings',
  'Enjoy the Game',
  'Eski Dostlar',
  'Essence of Chicken',
  'E.T & the Dummies',
  'Et par sama og 2 ens',
  'EU Club',
  'EU oder so',
  'Euro Step',
  'European Aces',
  'Eva og Ingeborg',
  'Ex Fijanova +',
  'Expired Youth',
  'Eye of the Tiger',

  'F1',
  'F16',
  'F-37',
  'f.d. Fröken Michiel',
  'Fab VI',
  'Fac ut gaudeam!',
  'Fairy Tale',
  'Fallega Folked',
  'Fancy Team',
  'Fanta 4',
  "Fariña's Circus",
  'Fast and Furious',
  'Fastings disipler',
  'Father and Son',
  'Feel Good',
  'Felices las 4',
  'Fem på nya äventyr',
  'FF 69',
  'Field Tambun',
  'Filips Fanclub',
  'Finnmark Flyers',
  'Finways Sappers',
  'Five Clubs Partyband',
  'Fjoll uten fisk',
  'Fjords of Norway',
  'Flatt kjedelig',
  'Flora and Friends',
  'Flying Dutchess',
  'Force 5',
  'Forever Young',
  'Four Aces',
  'Four Belles',
  'Fozzilet og Kidza',
  'Frank-Furter',
  'Freak City',
  'Free to Fly',
  'Free Trade',
  'Front Page',
  'Fryske hynder',
  'Fuglen har fløyet',
  'Full Attack',
  'Full House',
  'Full Metal Jacket',
  'Full Moon',
  'Full Spectrum',

  'Gallo en la canasta',
  'Game On',
  'Game Over',
  'Gammel Oppland m/co',
  'Gan Bei',
  'Gang of Wyk',
  'Garp44',
  "Gary's Boys",
  'Gemengd succes',
  'Generation X',
  'Genialer Teamname',
  "Ghosh's IV",
  'Ghost of Red',
  'Ghost Riders',
  'Gin Tonic',
  'Ginga Style',
  'Girls and Boys',
  'Girls on Fire',
  'Gissen met Wisse',
  'Gjeddene i sivet',
  'GKS April',
  'Global Mix',
  'Glomma Raiders',
  'Glory Box',
  'Glory Mandarin',
  'Goan Curry',
  'God (gammel) årgang',
  'Godt fornøyd Olsen',
  'Gogo Fans',
  'Golden Age',
  'Golden Bombers',
  'Golden Bull',
  'Golden Girls',
  'Golden Retriever',
  'Goldy Ice',
  'Good Ball',
  'Good Fellas',
  'Good Men',
  'Good Mood',
  'Good News',
  'Good Oxygen',
  'Good Six',
  'Great God',
  'Green Eyes',
  'Green Lines',
  'Group One',
  'Gry Forever',
  'Gunnars Gunners',
  'Gutta fra nord',
  'Gutta på tur',
  'Guyub 57',
  'Gyllene Prag',
  'Gøta-Hesten',

  'H.A.N.E',
  "Hagen's Heroes",
  'Hai Na Bai Chuan',
  'Hai Nan Nan Shan',
  'Half Amsterdams',
  'Han Solo',
  'Hands and Hearts',
  'Hannover Four',
  'Hansen Hurricanes',
  'Hao Ran',
  'Happy Bridge',
  'Happy Couples',
  'Happy Hour',
  'Happy Team',
  'Happy Time',
  'Hare Krishna',
  'Have Fun',
  'He for She',
  'Heads or Tails',
  'Helens Angels',
  'Heldige Olav',
  "Hell's Angels",
  'Helt elektrisk',
  'Heph Stars',
  'Her vantar blaðsíðu',
  'Her yas pozitif',
  'Hey Yo',
  'Hi Charli',
  'Hillbilly Help Suit',
  'Holmen Spesial',
  'Homo Ludens',
  'Hope & Pray',
  'Hopp i sang',
  'Horten-14',
  'Hot Fuzz',
  'Huckauf Ingenieure',
  'Humør på humør',
  'Hurlumhei',
  'Husk of Hares',
  'Hvalen og tjukkasene', 
  'Hvor er mine babes',
  'Høyland & Kjell-Vidar',
  'Håkken hårt hårr',

  'I Doctors',
  'I Win',
  'Icelandic Bar',
  'Ice Jacks',
  'Ides Språksjov',
  'Ikke akkurat kjedelig',
  'Il Fante di Fiori',
  'Ilhas & Aredores',
  'India All Star',
  'India Blues',
  'Indian Mavericks',
  'Indonesian National Sports Week',
  'Infinity Mix',
  'Ingen Bagge',
  'Inverted Minors',
  'Iron Bank',
  'Is og brus',
  'Isolated Menaces',
  'Istiklal Yolu',
  'Israeli Dan',
  'Itinérants du bridge',
  'Iyi Takim',

  'Ja re ja',
  'Jacobo y Federico',
  'Jaipur Jewels',
  'Jamm & Co',
  'Jane Doe',
  'Jiangsu YY',
  'Jim Team',
  'JJ Match',
  'Jorunns disipler',
  'Josef and Cards',
  'Joy Division',
  'Joyjits Army',
  'Junioren mit Upgrade',
  'Juniorproffen co',
  'Juniors Disipler',
  'Just for Fun',
  'Just Mixed',
  'Just Play',
  'Juzz-Pete',

  'K(apitän)K(alf)',
  'K1',
  'K2',
  'K4',
  'K5',
  'Kansai Union',
  'Kanto Union',
  'Kapten Krok Crew',
  'Karachi Aces',
  'Karate Kids',
  "Karl's Silence",
  'Karlssons frestelse',
  'Karlstads vänner',
  'Kasimirs Dream Team',
  'Katin kontit',
  'Katt-Bridge',
  'Keep Walking',
  "Keni's Dream",
  'Key Lime Pie',
  'Kick Back',
  'King Geoffrey',
  'Kipp O`Hoi',
  'Kippe et al',
  'Kisa metraj',
  'KL 4',
  'Klara färdiga slam',
  'House Klave',
  'Klicks Dream Team',
  'Klin Kokos',
  'K(l)ukken',
  'Kløver 5',
  'K-O',
  'Koos Bros',
  'Koridor 10',
  'Kronisk kusma',
  'Kung Sune',
  'Kungshamns Sega Gubbar',
  'Kurt quo vadis',
  'Kusinerna från land',
  'Kuvayi Milliye',
  'Kvalen og nissene',

  "L'Orange",
  'La Bomba',
  'La Bridgerie',
  'La Cholita',
  'La La Land',
  'LA Light',
  'La Vista',
  'Ladprao Bridge',
  'Lady Da et ses Boys',
  'Lake My Love',
  'Lakk & Lær',
  'Lalit Mohanka Youth',
  'Lame Crane',
  'Lang lunte',
  'Langt mer enn ivrig',
  'Lao Xiongdi',
  'Larsson på taket',
  'Las Camelias',
  'Last Minute',
  'Last Arrival',
  'Lawrence of Arabia',
  'L.C. is Beautiful',
  'Le Blanc',
  'Le coup de Diablo',
  'Le rouge et le noir',
  'Leichte Brise Südwest',
  'Les Allumettes',
  'Les Girafes',
  'Les Teignes',
  'Les Zähringers',
  'Lieber tod als Zweiter',
  'Light Blues',
  'Light Cast',
  'Light of the Seven',
  'Lille Skutt',
  'Lindenthal und Freunde',
  'Lisbeth og gutta',
  'Lisbeths lakeier',
  "Lise (i)DA",
  'Lite av varje',
  'Little Meck',
  'Little Top Bridge',
  'Lodz 100%',
  'Lokomotive Franken',
  'Lope de Vega',
  'Long Dragon',
  'Los Capitanos',
  'Los Escandinavos',
  'Los Gauchos',
  'Los Mismos',
  'Lovende ung',
  'Lucky 4',
  'Lucky Bandana',
  'Lucky Losers',
  'Lucky Seven',
  'Lucky Star',
  'Lucky 13',
  'Lupii Galbeni',
  'Lynx and Co',
  'Lyubimetz 13',
  'Lått løye',

  'M W',
  'M.O.',
  'M. Green',
  "M' Orange",
  'Ma-Cartoon',
  'Ma&&Mü@Ma2',
  'Madam Mimm',
  'Maddes pojkar',
  'Madera czyli chill',
  'Magic Eyes',
  'Magnus er best',
  'Mama Lauda',
  'Mama Rosa',
  'Man Harr det man har',
  'Manchester United',
  'Many Hands',
  'Maria Elena',
  'Markku ja mimmit',
  'Marvel Universe',
  'Master Minds',
  'Max 100',
  'Max-Nat',
  'Männer mit ELAN',
  'MC 953',
  'MC Toss',
  'McIntosh Funclub',
  'Medium Rare',
  'Mee Noey',
  'Meins bleibt meins',
  'Meisters Disciple',
  'Meli Melo',
  'Methods of Bridge',
  'Mickey Two Clubs',
  'Midnight Cravings',
  'Miks Et?',
  'Mind and Matter',
  'Minmin Team',
  'Minus 800',
  'Missão Impossivel',
  'Mix n Match',
  'Mix veg',
  'Mladi i nadobudni',
  'Modesty Blaise',
  'Molto Bene',
  'Monotone Memories',
  'Monty Zeebergs FC',
  'Moo York Nix',
  'Moral Power',
  'Mostly Harmless',
  'Mountain Sea',
  'Moving Forward',
  'Mr Blackout',
  'Mr Bumble',
  'Ms. Guggenheim',
  'Murphys lag',
  'Musi 88',
  'My Friends',
  'My Way',
  'Myllyn Parhaat',
  'Mystery Foursome',

  "Narcotic's What?",
  'NASA ROFL',
  'NasDem Bitung',
  'Nat-Max',
  'Nästan lammkött',
  'Nestors trappar upp',
  'Never Claim',
  'New Amsterdam',
  'New Friends',
  'New Combination',
  'New Generation',
  'New Twins',
  'Nice and Monsters',
  'Nicolais fanclub',
  'Nilslands Crew',
  'Nilslands Slowfoxes',
  'Nilslands sväklinge',
  'Nini Nono',
  'Ninjas in Pyjamas',
  'Nissene på låven',
  'No Angry Men',
  'No Back',
  'No Fear',
  "No He Isn't",
  'No Johnny Cash',
  'No Limit',
  'No ne mimmit',
  'No Pasaran',
  'No Problem',
  'No Surprise',
  'No Trump',
  'Noe Rusk',
  'Non Problem',
  'Noname Can Can',
  'Noras Fanclub',
  'Nord og Syd',
  'Nordan Strengur',
  'Nordic Five',
  'Nordic Fours',
  'Nordisk kombination',
  'Norges navle',
  'Norrlands guld',
  'North Pole',
  'North Seasters',
  'North Star',
  'Not the Empire',
  'Nuts & Bolts',
  'Næsten Junior',

  'O Fozzil',
  'O Samba',
  'O Zone Mio',
  'O.R.G',
  'Oceans4',
  'Occupy Taksim',
  'octobridge.xyz',
  'Od Moze Do Moze',
  'odd-å-vi',
  'Odd Tore',
  'Oddskongen med rese',
  'Old Guys',
  'Olsen på hjørnet',
  'Oh Ya!',
  'Ohne Respekt Crew',
  'Olas race',
  'Olavs utvalgte',
  'Old Horse',
  'Old People',
  'Old-Man',
  'Olympiad Gold',
  'Om het hoekie',
  'One I S',
  'One + Khuching Tree',
  'One Hundred Eighty',
  'One More!',
  'Opp og ned',
  'Orange Dynamite',
  'Otra Vez',
  'Ottos Lotto',
  'Our Future',
  'Over stokk og stein',

  'Pac-Man',
  'Papa & Rabbits',
  'Papa and Rabids',
  'Papas & Puppies',
  'Paris Match',
  'Park Tenisowy',
  'Patchwork Dynamite',
  'Paul & Frank',
  "Paula's Angels",
  'Pay Toll',
  'Pearl of the Orient',
  'Pepsi-Colas',
  'Pieni karhu',
  'Piger og drenger',
  'Pigerne på tur',
  'Piekni i Bestie',
  'Pijar',
  'Pink Blend',
  'Pink Panter',
  'Pinot Noir',
  'Plan B',
  'PO & JBGood Team',
  'Poezel en Wip',
  'Polish Dodos',
  'Poker Bear',
  'Pola-Pola',
  'Pomoze my',
  'Powerpuff Pinglorna',
  'Plejans Plöjare',
  'Precision Marathon',
  'Presten gudinna',
  'Pro Max',
  'Pur Pur',
  'Pure Zagreb',
  'På alerten',

  'Q of Di',
  'Qiao Yi Dui',
  'Qual. Winners',
  'Quatro Bruxas',
  'Que Mira Bobo',
  'Queen and Knights',
  'Queen of Hearts',
  'Queens Park Rangers',
  'Qiong Zhiyou',
  'Quanzhou Development',

  'R1F3 Initials',
  'R1S5 Initials',
  'Ra Ma Ra Him',
  'Radio Communication',
  'Radkov Trash',
  'Randers 2.0',
  'Randers 4.0',
  'Ranger Pink',
  'Rapan & Jezus',
  'Real Maramma',
  'Red Ash',
  'Red Beach',
  'Red Hat',
  'Red Hot',
  'Red Pork Cutlet',
  'Red Soles',
  'Red Zeppelin',
  'Refi i prijatelji',
  'Reidar reiser snart',
  'Renons Rimstedt',
  'Repeat Bet',
  'Reps und Wodniansky',
  'Restricted Talent',
  'Rett opp i saksa',
  'Rimstedt Minus',
  'Rimstedt Power!',
  'Rising Star',
  'River Blanco',
  'River Friend',
  'River Rojo',
  'Robin Hood',
  'Robådane på BBO',
  'Rohit Wrappers',
  'Rooftop Palma',
  'Rotseknots Ernst',
  'Royal Flush',
  'Röda små stugor',
  'Rubb og stubb',
  'Rudderless Ship',
  'R.U.F.F.',
  'Ruff Gunn',
  'Ruia Blazers',
  'Russian Bear',
  'Ruter 7',
  'Ruter 9',

  'S(h)aman',
  'Sabarian + LuBu',
  'Saint Titus',
  'Salten rundt',
  'Sam23',
  'Samfund Slingers',
  'Sannas Änglar',
  'Saras Friends',
  'Sayin Abim',
  'Schall und Rauch',
  'Se lyhyempi korsi',
  'Sea Life',
  'Section 26',
  'Secret Shot',
  'Sektion UDV',
  'Sem Trunfo',
  'Sensus Penduduk',
  'Seths vänner',
  'Seven Eleven',
  'SHE-D',
  'Shenzhen Eagle',
  'Shiba Inu',
  'Shining Pig',
  'Shiv Shakti',
  'Shojo Tyochin',
  'Shy Ant',
  'Siderkongen og kidz',
  'Silence BC',
  'Silver Eagle',
  'Simba Felis',
  'Simple Minds',
  'Sivves straffdubbl',
  'Six Diamonds',
  'Six Samurai',
  'Six Spades',
  'Sjiraffen Erik',
  'Skönheten & odjuren',
  'Slam Dunk',
  'Slam Hunters',
  'Slow Scorpions',
  'Smoking Guns',
  'Smooth Duck',
  'Småsamen med døler',
  "Soalitt`s disipler",
  'Soaring Shou',
  'Soep van Youp',
  'Sofies verden',
  'Space Girls',
  'Space Mutants',
  'Spade Ace',
  'Sparkling Vintages',
  'Speedy Turtals',
  'Spiders from Mars',
  'Spider Team',
  'Spiel mir das Lied',
  'Spjett Spjong',
  'Stabby with Youngsters',
  'Stara Gara',
  'Steng Oslo nå!',
  'Still Going Turbo',
  'Still Water Runners',
  'Stone Cutters',
  'Storm Gutta',
  'Storm Riders',
  'Strawberry Fields',
  'Stærke scener',
  'Stø pluss',
  'Super Pineapples',
  'Super-Ladies-Danke',
  'Superheroes in Training',
  'Support from Holland',
  'Svag klöver',
  'Svenske og ulykke',
  'SWAT Squad',
  'Sweet Is Middle',
  'Sydän Ja Sielu',
  'Syntax Error',
  'System N K',
  'Søta bror',

  'Ta Kau',
  'Take Off',
  'Tare Fare',
  'Tartu 14',
  'Tchin Tchin',
  'Tea for 2',
  'Tea Want',
  'Team Awesome',
  'Team Bo a berg',
  'Team Doc',
  'Team Mayhem',
  'Team NRK',
  'Team Paper Moon',
  'Team Vildmand',
  'Team Yoda',
  'Teddy Bear',
  'Tempo-Knektene',
  'Texan Aces',
  'Texan and Turks',
  'Texan and Yanks',
  'Teyzenýn Yerý',
  'The Four Guys',
  'The A Team',
  'The Abacus',
  'The Alliance',
  'The B Team',
  'The Baltans',
  'The Beatles',
  'The Black Ewes',
  'The Boss Is Back',
  'The Bratz',
  'The Bush',
  'The Canadians',
  'The Clown',
  'The Club Enthusiast',
  'The Colonies',
  'The Contractor',
  'The Crazies',
  'The Crucible',
  'The Daltons',
  'The Dentist',
  'The Distillers',
  'The Eagles',
  'The Fab Five',
  'The Final Cut',
  'The Fitness Boys',
  'The Flying Nudes',
  'The Frush',
  'The Good',
  'The Groovia',
  'The Hons',
  'The Items',
  'The Jets',
  'The Latin',
  'The Little Mermaid',
  'The Lions',
  'The Magic Dogs',
  'The Maltese Falcons',
  'The Marx Brothers',
  'The Maverick',
  'The Metropolis',
  'The Ninjas',
  'The Other Junior Girls',
  'The Palookas',
  'The Patron',
  'The Pirates',
  'The Real Team',
  'The Reco',
  'The Red Devils',
  'The Reds',
  'The Revokers',
  'The Shadows',
  'The Sharks',
  'The Sheriff',
  'The Skilled',
  'The Stig',
  'The Stones',
  'The Stream Team',
  'The Three Stooges',
  'The Tigers',
  'The Untouchables',
  'The Vampires',
  'The Voice',
  'The Weak End',
  'The Weak Link',
  'The Werewolves',
  'The Winner',
  'The Young Mummies',
  'The Young Ones',
  'The Palookas',
  'Them and Us',
  'Thick Toast',
  'Third Eye',
  'Thompson Station',
  'Tian Guan',
  'Tiinan pojat',
  'Þorsteinn Svörfuður',
  'Thread & Needles',
  'Three Nations',
  'Thunder Strike',
  'Tre Kn og en D',
  'Tre knekter og ett S',
  'Tre och en halv män',
  'Triple 8',
  'To gamle og to gode',
  'To tette og en badehette',
  'To Win',
  'Tommys tigre',
  'Top Flight',
  'Top of the South',
  'Top Ruff',
  'Topbridge of course',
  'Tre hunkar en babe',
  'Tre rette og en vrang',
  'Tre sang',
  'Tri Polar',
  'Triple Bacon Cheese',
  'Triple Nine',
  'Troll i eske',
  'Trump No More',
  'Trzech i Czech',
  'Tut tut',
  'Twitch Chat',

  'Ueno Panda',
  'Unguru Bulan',
  'Unholy Alliance',
  'Unlimited Intellect',
  'Unstable Evolution',
  'Usaklig Deigræv',
  'Uten filter',
  'Utmanare Eriksson',
  'Utmanare Övelius',

  'Vaddo Gliders',
  'Vegetable Hotpot',
  'Vera och Marie',
  'Veras Gäng',
  'Verden rundt',
  'Verdens navle',
  'Very Mixed',
  'Vi bygger stikk!',
  'Vi fyra',
  'Vi gör som Einar',
  'Vi i femman',
  'Vi trekk oss ikke',
  'Vickys Vikings',
  'Victorious Secret',
  'Vierde van links',
  'Viking Club',
  'Viking Natural & Hi',
  "Vincent's Friends",
  'Vinir Gylfa',
  'Visst nappar det',
  'Vitamin',
  'Viva Plambata',
  'Volatile Company',
  'VP (b)anker IMP',

  'Waikato Bays',
  'Walking Dead',
  'Wambon Bodi',
  'War of Roses',
  'Washed Up',
  'We Are Bye',
  'We Are 6',
  "We Don't Know Yet",
  'We Meet Again Mr A.',
  'Well Done',
  'Well Fitted',
  'Well Wise',
  'West Coast',
  'What the Heck',
  "What's Up?",
  'Where Is My Mind',
  'Whisky Team',
  'White Bears',
  'Wide Deep and Bugs',
  'Wild Cats',
  'Wild Griffins',
  'Wild Horses',
  'Winter Is Coming',
  'Wrang Lead',
  'Wrecking Ball',
  'WT og Kaffeprinsessen',
  'Würst und Weißbier',
  'www guts com',

  'X-Men',
  "Xi'an Qiaoyou",
  'Xiu Xing Dui',

  'Y.Y.Y.D.',
  'Yali Capkini',
  'Yani and Friends',
  'Yanjing Puzi',
  'Yarralumla Yabbies',
  'Yellow and Blue',
  'Yilu Pingan',
  'YOI Returns',
  'You Can Call Me Al',
  'You Must Win',
  'You Never Walk Alone',
  'Yoyo 5',
  'Young and Broke',
  'Young Guns',
  'Young Guys',
  'Young Warriors',
  'Young Driver',
  'Young Swedes',
  'Young Oldies',
  'Your name?',
  'Yu Yi Dui',
  'Yuruyen Kosk',
  'Yuyi Xizi',

  'Zaza Boys',
  'Zhejiang Development',
  'Zia and Friends',
  'Ziemlich gut',
  'Zimm Friends',
  'Zsuga Liga',

  'Øst-Vest',
  'Åmål Hulta',
);

my %MULTI_TYPOS =
(
  '0% Eriksson' => ['0 eriksson'],
  '1 Non Blonde' => ['1 noen blonde', '1 none blond', '1 none blonde'],
  '10 Tricks' => ['10 trikc'],
  '101.yil' => ['101. yil'],
  '3 Idiots + 1' => ['3 idiots +1', '3 idiots + i'],
  '4 Trèfles' => ['4 trefles 1', '4 trefles1',
    '4trèfles', '4 treffles', '4trèfle'],
  '40 Årskrisa' => ['40-Årskrisa'],
  '5 Ess' => ['5-ess'],
  '6 Notrump' => ['6 no trump'],

  'AG laget' => ['ag-laget'],
  'Alex is Beautiful' => ['alex is beatiful'],
  'All Stars' => ['all-stars'],
  'Alle presidentens menn' => ['alle presidentens'],
  'Ann Lill (i)Da' => ['anne lill (i)da'],
  'Applied Math' => ['aplied math'],
  'Apres-Bridge Champs' => ['apres bridge champs'],

  'Babes Amazones' => ['babes-amazones'],
  'Bağcı Döven' => ['bagci doven'],
  Baneet => ["Baneet's IV"],
  'Bangkok Kimono' => ['bangkok kimino'],
  'Baris hemen simdi' => ['Barýþ Hemen Þimdi'],
  Begijntje => ['begijnt je'],
  'Best uten kort' => ['best uden kort'],
  'Beverly Hillbillies' => ['beverly hillbillie'],
  'Big Guns' => ['big gun'],
  'Big Makie' => ['big makie och co'],
  'BK Gröna Kvistar' => ['BK Grön Kvistar'],
  'Blaksets Bin' => ['blacksets bin', 'blaskets bin'],
  BNMR => ['b n m r'],
  'Bodø Glimt førr evig' => ['bodø glimt førr evi'],
  'Boro Boss' => ['boro-boss'],
  'Brian Is Beautiful' => ['brian is beatiful'],
  'Butterfly from HK' => ['babochka s hk'],

  'Ca. et halvt tonn' => ['ca et halvt tonn'],
  'Californian Aces' => ['california aces'],
  "Captain's Four" => ['captains 4'],
  "Captain's Team" => ["capitan's team"],
  'China Development' => ['zhongguo kaidi'],
  "Colonel's Team" => ["colonel's  team"],
  'Croatian Pirates' => ['cro pirates'],
  'Curry Eaters' => ['curry  eaters'],

  'Daniel med vänner' => ['daneil med vänner'],
  'Danish Dynamite' => ['danish dynamit'],
  'De escalatie sensatie' => ['de escalatie sensat'],
  'Den gyldne omvei' => ['den gylne omvei'],
  "Dera's Deckhand" => ["deora's deckhand", "dera's deck"],
  'Desperate Bridge Wives' => ['desperate bw', 'desperate bridgewi'],
  'Det är helt självklart' => ['det är helt självkl'],
  "Devil's Coup" => ['devils coup'],
  'Diamonds Are Forever' => ['diamonds are foreve'],
  'Down Under' => ['doun under'],
  'Dr. Romantic' => ['dr.romantic'],
  'Dr. Worrawat' => ['dr.worrawat'],
  'Dragon Kiddies' => ['dragon kiddie'],
  'Dronninga med prins' => ['drnninga og pri',
    'dronninga med pri', 'dronning og prinses'],

  'Ebenius Crew' => ['ebeneius crew', "ebeneius crew'"],
  'Eiydes discipler' => ['eiydes disciple'],
  'Elses Fanklubb' => ["elze`s fanklubb"],
  'En myra tre elefanter' => ['en myra tre elefant'],
  'Et par sama og 2 ens' => ['et par sama og 2 en'],

  'Fast and Furious' => ['fast & furious'],
  'FF 69' => ['ff  69'],
  'Field Tambun' => ['field t'],
  'Five Clubs Partyband' => ['five clubspartyband'],
  "Flint's Crew" => ["flint`s crew"],
  'Flora and Friends' => ['flora && friend'],
  'Fozzilet og Kidza' => ['fossilet og kidza'],
  'Fuglen har fløyet' => ['Foglen har fløyet'],
  'Freak City' => ['freak-city'],

  'Game On' => ['game-on'],
  "Gary's Boys" => ['garys boys', 'gary´s boys'],
  'Good Men' => ['good man'],

  "Hagen's Heroes" => ["hagen`s heroes", 'hagens heroes'],
  Hammershark => ['hammershark deluxe'],
  'Hands and Hearts' => ['hands & hearts'],
  'Hao Ran' => ['hao-ran'],
  'Heldige Olav' => ['heldige olav :)'],
  "Hell's Angels" => ['hells angels'],
  'Her vantar blaðsíðu' => ['her vantar bladsidu'],
  'Hey Yo' => ['hey yo!!'],
  'Holmenkollen' => ['h-kollen'],
  'Hope & Pray' => ['hope n prey', 'hope and prey', 'hope & prey'],
  'Hopp i sang' => ['hoppa i sang'],
  'House Klave' => ['klave houses', 'klave house', 'kleva house',
    'kleva houses'],
  'Hurlumhei' => ['hurlumhei..'],
  'Hvalen og tjukkasene' => ['hvalen og tjukkasne', 'hvalen & tjukkasene'],
  'Høyland & Kjell-Vidar' => ['høyland&kjell-vidar',
    'høyland&kjellvidar'],

  'Ice Jacks' => ['ice jack', 'ice jaks'],
  'Ikke akkurat kjedelig' => ['ikke akkurat kjedel'],
  'India Blues' => ['indian blues'],
  'Indian Mavericks' => ['india mavericks', 'indian mavricks',
    'mavericks all stars', 'mav prodigies', 'mavericks prodigies',
    'maverick all star', 'maverick all stars'],
  'Itinérants du bridge' => ['iti du bridge', 'itin du bridge'],
  'Iyi Takim' => ['Ýyý Takim'],

  'Jamm & Co' => ['jamm & co.', 'jamm && co.'],
  'Junioren mit Upgrade' => ['junioren mit upgra'],

  K1 => ['k01', 'k-1', 'k 1', 'k one', 'k 1 plus'],
  K2 => ['k2 rebid'],
  'Kasimirs Dream Team' => ['kasimirs dreamteam'],
  "Keni's Dream" => ["keni's", "kini's", 'p.keni'],
  'Kick Back' => ['kick-back'],
  'King Geoffrey' => ['king groffrey'],
  'Kisa metraj' => ['ksk kisa metraj'],
  'Koos Bros' => ['Koos Bro´s', "koos bro's"],
  'Kungshamns Sega Gubbar' => ['kungshamns sega gub'],
  'Kuvayi Milliye' => ['kuvai milliye'],

  "L'Orange" => ["l' orange"],
  'La Linea med eller uten ball' => ['la linea med ell', 
    'la linea med elle'],
  'Lao Xiongdi' => ['lao xiong di', 'lao xipongdi'],
  'Lawrence of Arabia' => ['lawrence of arab'],
  'La Vista' => ['la vista team'],
  'Lakk & Lær' => ['lakk og lær', 'lek & lær', 'lokk & lur',
    'litt lakk og lær', 'lakk lær'],
  'Larsson på taket' => ['larsson pa taket'],
  'L.C. is Beautiful' => ['l.c.is beautiful'],
  'Leichte Brise Südwest' => ['leichte brise südw'],
  'Lieber tod als Zweiter' => ['lieber tod als zwe'],
  'Lindenthal und Freunde' => ['lindenthal und fre'],
  "Lise (i)DA" => ['lise da', 'lise da!', 'lise lill (i)da', 
    'lise(i)da'],
  'Lucky 13' => ['lucky13'],

  'M. Green' => ['m green'],
  'Magic Eyes' => ['majic eyes', 'm e'],
  'Man Harr det man har' => ['man harr det man ha'],
  'Manchester United' => ['man u', 'man utd'],
  'Männer mit ELAN' => ['2 männer mit elan'],
  'MC 953' => ['mc953', 'mc_953', 'mc  953'],
  'Mickey Two Clubs' => ['mickey 2c'],
  'Mind and Matter' => ['mindand matter'],
  'Missão Impossivel' => ['missão impossível'],
  'Monotone Memories' => ['monotona memories',
    'monotona memoirs'],
  'Monty Zeebergs FC' => ['monty zeebergs', 'minty zeebergs fc'],
  'Mr Blackout' => ['mr.blackout'],
  'Ms. Guggenheim' => ['ms. gugenheim'],
  'Murphys lag' => ['murpyhs lag'],
  'Mystery Foursome' => ['mystery 4some'],

  'Nice and Monsters' => ['nice monsters'],
  'Nicolais fanclub' => ['nocolais fanclub'],
  'Nilslands Slowfoxes' => ['nilsland slowfoxes', 'nilsland slowfoxers'],
  'Ninjas in Pyjamas' => ['ninjas in pijamas'],
  "No He Isn't" => ['no he isnt'],
  'No Surprise' => ['no surprice'],
  'No Trump' => ['no trumph'],
  'Nordic Five' => ['nordic 5', 'nordil five'],

  'Oh Ya!' => ['oh ya'],
  'Old-Man' => ['old man'],
  'Outsiders' => ['out siders'],

  'Pigerne på tur' => ['pigerne pa tur'],

  'Quanzhou Development' => ['quanzhou fazhan'],
  'Queen and Knights' => ["queen's & knight"],

  'Rapan & Jezus' => ['rapan and ezis'],
  'Reps und Wodniansky' => ['reps und wodniansk'],

  'Saint Titus' => ['st titus', 'st. titus'],
  'Sakurai' => ['japan sakurai'],
  'Sannas Änglar' => ['sannas äangler'],
  'Sektion UDV' => ['section udv'],
  'Sem Trunfo' => ['sem trumfo'],
  'Silver Eagle' => ['silver  eagle'],
  'Sivves straffdubbl' => ['sivves straffdubbl.', 'sivves straffdbl',
     'sivves...'],
  'Six Diamonds' => ['six diamond'],
  'Six Samurai' => ['six samurais'],
  'Skönheten & odjuren' => ['skönht. och odjuren'],
  'Slam Hunters' => ['slam hunter'],
  'Sofies verden' => ['sofies world'],
  'Soep van Youp' => ['soep van yoop'],
  'Speedy Turtals' => ['spiddy turtals'],
  'Stabby with Youngsters' => ['stabby with youngst'],
  'Superheroes in Training' => ['superheroes in trai'],
  'Support from Holland' => ['support from hollan'],

  'Team NRK' => ['tram nrk', 'tm nrk'],
  'Tempo-Knektene' => ['tempo-knehtene'],
  'Texan Aces' => ['texa aces', 'texaan aces', 'texan  aces',
    'tn aces'],
  'The Four Guys' => ['the 4 guys'],
  'The Clown' => ['the_clown'],
  'The Magic Dogs' => ['the magicdogs'],
  'The Maltese Falcons' => [
    'the maltese',
    'maltesien falcon'],
  'The Other Junior Girls' => ['the other jnr girls'],
  'The Palookas' => ['the_palookas'],
  'The Weak End' => ['the weakend'],
  'Them and Us' => ['them & us'],
  'Thunder Strike' => ['tunder strike'],
  'To tette og en badehette' => ['to tette',
    'to tette og en bade'],
  'Tre knekter og ett S' => ['tre knekter og etts'],
  'Tre rette og en vrang' => ['tre rette og en vra',
    'tre rette og en'],
  'Troll i eske' => ['tre troll i eske', 'tre troll ...'],

  'Unguru Bulan' => ['unguru  bulan', 'unguru bulanu'],

  'Victorious Secret' => ['victorius secret'],

  "We Don't Know Yet" => ['we dont know yet'],
  'Wild Cats' => ['wild cat'],

  'Waikato Bays' => ['wiakato bays'],
  'What the Heck' => ['whattheheck'],
  'WT og Kaffeprinsessen' => ['wt og kaffeprinsess'],

  'X-Men' => ['x men'],

  'Yellow and Blue' => ['yellow&blu'],
  'Young and Broke' => ['young&broke'],
  'You Never Walk Alone' => ['you never walk'],
  'Yuyi Xizi' => ['yuyi(xizi)'],

  'Zhejiang Development' => ['zhejiang fazhan']
);

my @SINGLE_WORDS = qw(
   2Q2K 3D 6L 10CC 7heart

   Aces Adventure Agamemnon Agressor Ahornet Aida Alliance Alliansen 
   Allstars Alternativlos Amarillo Ambassador Andromeda Anglian 
   Anglers Anglophones Appellkameratene Apples Apply Aquarius 
   Arachfobia Archies Aristos Armani Asparagus Astra Astro 
   Astronotlar Atlantic Atom Autostrada Avalanche Avatar 

   Bachelor Badger Badminton Bager Banana Bananasplit BarDeZi 
   Barracuda Barsss Baryton Beauty BeRe Bingbang Binkie Blackwood 
   Bling Blondie Blues Blueberry Blues Bolero Boogies Boomz 
   BOVE Bricklayer Bridgeministeriet Brigada Brother 
   Brudarna Bubba Buddies Bulk Bulldozer Bumerangas Bunnies

   Cancan Cardtossers Cargo Cartoon Casuals Censored Challengers 
   Changes Chicks Chokladmåndag Claim Coaches Cogito Commandos 
   Comrade Contact Contra Corner Counterstrike Crash Cremaster 
   
   Danger Debutantes Deceptive Desperados Destroyers Dialect Doctors 
   Donjulio Donvito Dracula Dragon DuckNDales Dusteforbundet Dyret

   Eagles Eastward Eliminator Emerald Engineers Enigma Enjoy 
   Everest Evil 

   Fantasia Fant4stic Farmen Farmers Fenesta Filbyter Filosofene 
   Finest Fisk Forfot Formidables Frenemies Friends Francophones 
   Freak Frirond Frivolt 

   Galaxy Gehaktmolen Gentle Geriatrix Geysir Giants GloryGlory 
   Goldcat Gosho Grand Grads Gris Gruken Guests Gulebjorn Gunsmoke 
   Gwenchanna

   Hangarounds Happy Hawks Hästpojkarna HERZdame HeSa Hey 
   Hiiimmm Hjerterdamer Hobbits Hobby Hollywood Holmenkollen 
   Honeymoon Hopfenkönig Hornet Hufflefluffs Huhu Hunhun Hurra 
   Hybrid

   Ikarus Impas Imponderables Indi Instructor 

   Jernbaneverket JJJ Job Jocker JoJo Joker Journalists Jugermaister 
   Juice Jupiter Juubilar Juveniles

   Kamelåså Kamikaze Kangaroo Kanin Karo Kartalite Kartel Kat Kayal
   Kingkong Kings KISS KKKQ Kompisarna Kuglana Kuhmilch 

   Lady Laplanders Lazy Lebensohl Liggeunderlaget Lion Lions Lirarna 
   Liverbird Lucky LVBridgeBums Løwene

   Maestroi Magi Magic Magister Maharaja Major MajorB Majorn Majority 
   Mars Marvelous Masdjävlar Mask Masters Matrix Maven Maxi Mercury 
   Meta Midas Milady Mirage Mismatch Mixarna Mjøskameratne MMMM 
   Mongos Måsen

   Nanda Natural Naturalists Nemesis Neverclaim Nightingale Noctis 

   Octopussy Okay Okra Olavsfestdagene Olrudbanden Olsenbanden Onyx 
   Opal Opera Opps Optimus Osss Outsiders Overivrig 

   Pacers Pacific Pandeka Pantherasia Paradigma Partizan Patriot 
   Patron Pegasus Perestrojka Pontiac Potlimit Potteplante 
   Powerchicks Prakker Preempters Pretendents Proteus Pusten 
   Påskevennene

   Qingyu Quasar Quattro Quintet Quinze

   Rampage Rapid Real Reklamtrion Relaxation Reloaded Riviera 
   Robocop Rollers Rovers 

   Sabres Saga Sailor Sakura Sakurai Saladmasters Salokin Sammartini
   Sapphire Saturn Scandinavia Schneewittchen Scientists Secure 
   Senator Sheep Shengxing Show Silverfox Simple Sindbad Singapole 
   Sirius Sjøsamen Skip Skitur Slappfisker Slufsa Småveitjan Snapper 
   Snipers Soho Solaris Sonata Spark Spartans Specialist Spekkhogger 
   Squeeze Stampede Star Starmen Statusquo Stayman Stifinnern 
   Strategen Streamline Stålfarfar Sunset Sunshine Syttisju 
   Sømnakameratene Såpeopera

   Takeoff Tannlegene Taurus Tbone Tecza Tempo Tequendama Theme 
   Theseus Tibetmunkene Tigers Titanik Titans Tohundre Tolerant 
   Torpedo Tosca Trèfles Triton Truft Tsunami Tulip Tusio Tutu 
   Tvist

   UFO Ugh Ulvene Underdogs Unexpected Ungdomslaget Upplyfting 
   Utkantnorge 

   Vibrant Victory Vietcong Viking Villmarksgutta Vilttiketsu
   Vintage Vulcano

   Walpurga Westward Windrunners Winkiboy Wizards 

   Xman Xtrouble XXX XXXL XXXSL XXXXXYXY

   Zhanma Zombi Zorro Zugzwang 
);

my %SINGLE_TYPOS =
(
  'Adams Family' => ['adamsfamily'],
  'Albayrak 67' => ['albayrak67'],
  Ambassador => ['ambassadors', 'ambassdor'],
  Anglers => ['anglelers'],
  'Apollo Soyuz' => ['apollosoyuz', 'apollosoyouz'],
  Appellkameratene => ['apellkameratene'],
  'Atomic Bridge' => ['atomic'],

  Barracuda => ['barakuda', 'baracuda'],
  'Bid 72' => ['bid72'],
  'Bleu Lights' => ['bleulights'],
  'Bosse Superettan' => ['bosse'],
  Buaigh => ['buaijh'],
  Bulldozer => ['buldozer'],

  'China Development' => ['zgkd'],

  'England Swings' => ['englandswings'],

  Fant4stic => ['fant4stc'],
  Formidables => ['formidable', 'formidabble', 'formidabels',
    'formiddable', 'formiddables', 'formadibles', 'formadeble',
    'formadables', 'fromidables'],

  'Green Eyes' => ['greeneyes'],
  Gunsmoke => ['gunnsmoke'],
  'Guyub 57' => ['guyub57'],

  Hästpojkarna => ['hastpojkarna'],

  Imponderables => ['impoderables'],
  'India Blues' => ['indiablues'],
  'Indonesian National Sports Week' => ['pon'],

  'Jamm & Co' => ['jamm'],
  'Jiangsu YY' => ['jsyy'],
  'Joy Division' => ['joydivision'],
  Jupiter => ['jupitor'],

  'Last Arrival' => ['lastarrival'],
  Lebensohl => ['lebenshol'],

  Maharaja => ['maharaj', 'maharaaj'],
  Mismatch => ['missmatch'],
  Mjøskameratne => ['Mjöskameratene'],
  Måsen => ['Måsan'],

  Naturalists => ['nature', 'naturalistene'],

  'Occupy Taksim' => ['occupytaksim'],
  Onyx => ['onix'],
  Opps => ['opsy'],
  'Outsiders' => ['outsider'],

  Pacific => ['pacyfic'],
  Pantherasia => ['phanterasia'],
  'Paris Match' => ['parismatch', 'parimatch'],
  Preempters => ['preemptors'],
  Pretendents => ['pretendentas'],

  'Quanzhou Development' => ['qzfd'],

  'River Friend' => ['riverfriend'],

  Sammartini => ['sammarti'],
  Scientists => ['science'],
  Spartans => ['spartan'],
  Squeeze => ['squeze'],
  Starmen => ['starman'],
  'Stone Cutters' => ['stonecutters'],
  Strategen => ['stratagen'],
  Syttisju => ['sytti'],

  'Texan Aces' => ['texanaces', 'tnaces'],
  Titans => ['titan'],

  'Vegetable Hotpot' => ['vegetable'],

  'Wild Griffins' => ['wildgriffin', 'wildgriffins'],
  'Winkiboy' => ['winkyboy'],

  'YOI Returns' => ['yoi'],

  'Zhejiang Development' => ['zjfz']
);


sub set_hashes
{
  my ($method, $key) = @_;

  $method->(\@MULTI_WORDS, \%MULTI_TYPOS,
    \@SINGLE_WORDS, \%SINGLE_TYPOS, $key);
}

1;
