#!perl

use strict;
use warnings;
use v5.10;
use utf8;
use open ':std', ':encoding(UTF-8)';

package Tags::Sponsor;

our @ISA = qw(Exporter);
our @EXPORT = qw(set_hashes);

my @MULTI_WORDS =
(
  '101 Fasteignasala',
  "A-Media Sieradz",
  'Abadi Adimulia',
  'Abadi Jaya',
  'Adaro Energy',
  'Advisor Revisjon Norge',
  'Aershan Haishen',
  'Agena Development',
  'Agsar Paints',
  'AJ Diament',
  'Alfa Romeo',
  'Alfa-Compensa Gdynia',
  'Aliaga Kyme',
  'Alunand Limboto',
  'Andromeda Baroda',
  'Ant Teknik',
  'APRA Clothing',
  'Apreo Logistic Poland',
  'Asindo Prima',
  'Askim Turn og Lakk',
  'Astro A/S',
  'Atlantic Trade',
  'Atlas Profil',
  'Avia Financial',
  'Balarampur Chini',
  'Balcova Termal',
  'Baltic Express',
  'Bangkok Bank',
  'Bangur Cement',
  'Bank Indonesia',
  'Bank Mandiri',
  'Bank Nagari',
  'Bank Negara Indonesia',
  'Bank Tabungan Negara',
  'Bapenda Manado',
  'Baroda Bank',
  'Bayu Kencana',
  'Beijing Capital',
  'Beijing Cartoon',
  'Beijing Century',
  'Beijing Construction',
  'Beijing Dazhong',
  'Beijing Evertrust',
  'Beijing Huayuan',
  'Beijing Hull Technology',
  'Beijing Jinghua',
  'Beijing Lawyers',
  'Beijing Liuhe',
  'Beijing Longxin',
  'Beijing Railway Bureau',
  'Beijing ShouChuang',
  'Beijing Tianzhixing',
  'Beijing Trinergy',
  'Beijing Wan Jia',
  'BeiJing Xiaoganju',
  'BeiJing Xiaojungan',
  'Beijing Yue Ze',
  'Beijing Yindi',
  'Betri Ferðir',
  'Betri Frakkar',
  'Bokadirekt SE',
  'Bozzetto Azzurro',
  'Breki Jarðverk',
  'Bridge i Norge',
  'bridge24.pl',
  'BridgeBertheau.com',
  'Bridgefélag Reykjavíkur',
  'Bridgemagasiner.no',
  'Bridgescanner',
  'BridgeYes.com',
  'Bridge for Business',
  'Bridge for Fun',
  'Bridge Winners',
  'Brink Plast',
  'Buleleng Dewata',
  'Byle Co',
  'Bústólpi ehf',
  'Cai Fu Zheng Quan',
  'Cap Gemini',
  'Caretta International',
  'Carlo Bossi',
  'CCH Power',
  'Central Secretariat',
  'Century Insurance',
  'Chateau Rossenovo',
  'Chengdu Zhongtai',
  'Chennai Online',
  'China Evertrust',
  'China Finance',
  'China Global Times',
  'China National Petroleum Corporation',
  'China Ping An',
  'China Renshou',
  'China Resources',
  'China Trinergy',
  'Chinese Hailian',
  'Chongqing Jianke',
  'Chongqing Jinjian',
  'Chongqing Shangyou',
  'Construction Kielce',
  'Consus Carbon',
  'Consus Oil',
  'Cuebids.com',
  'Cumhuriyet OOSK',
  'Dagensbridge.dk',
  'Dalian Aoxin',
  'Dalian Dichan',
  'Dalli Cardillo',
  'Dama Kupa',
  'Darles Santerm',
  'Data Steel',
  'Dauna Winaza',
  'Delfts Brouw',
  'Delta TV',
  'Dentgroup Nisantasi',
  'Dhampur Sugar',
  'Dian Zi Cheng',
  'Diebold Nixdorf Krakow',
  'Djarum Black',
  'Djarum Bold',
  'Dobre Zegary',
  'Doga Naturale',
  'domwaluty.pl',
  'Dongfang Tairong',
  'Dragon Sports',
  'E-Service',
  'Easy Bridge',
  'ECF Holding',
  'Eden Realty Kolkata',
  'eDOT Goa',
  'Ekin Maden',
  'Eko-Al',
  'Elektromonta¯',
  'Elf Holding',
  'Eskom IT',
  'Euro Agro',
  'Electric Center',
  'Elektrik P3B',
  'Falck Medical',
  'Fanhua Jituan',
  'Fantoni Vacations',
  'Ferðaskrifstofa Vesturlands',
  'Fisk Seafood',
  'Fora Lastik',
  'Forsa Yatcilik',
  'forumbridge.pl',
  'Fossen Eiendom',
  'FX Securities',
  'Garðar & Vélar',
  'Garðs Apotek',
  'Garsu Pasaulis',
  'Geely Automobile',
  'Geo BSP',
  'Geo Kideco',
  'Geo Pertamina',
  'Geo Timah',
  'Geo Vale',
  'Geologi Banpu',
  'Geoportal Kutai Kartanegara',
  'Godfrey Phillips',
  'Gong Hang Jin Ying',
  'Guangdong Huachu Chemicals',
  'Guangxi Tianhu',
  'Guangzhou Hongmian',
  'Guangzhou Huachu Chemicals',
  'Guangzhou Mingjian',
  'Guangzhou Pearl River',
  'Guiyuang Bank',
  'Guizhou Bangda',
  'Haerbin Bingxue',
  'Hai Long',
  'Hainan Air',
  'Hainan Shichuang',
  'Hainan Window',
  'Haining Ziwei',
  'Haiyang Ruixiang',
  'Hangzhou Jinjiang',
  'HCI Indonesia',
  'Heilongjiang Tea',
  'Heng Yuan Xiang',
  'Hengsha Haijiu',
  'Hengsha Ke Ji',
  'Hengzhou Group',
  'HF Verðbréf',
  'Ho-Hsing',
  'Holzhauer IT-Service',
  'Hong Kong Vico',
  'Hong Zhu',
  'Hotel Senator',
  'Hótel Hamar',
  'Hótel Norðurljós',
  'Hotell Strand',
  'Hreint ehf',
  'Huabin Aoruijin',
  'Huangshi Qixing',
  'Hubei Bank',
  'Hubei Dongfeng',
  'Hubei Yihua',
  'Hunan Mingkai',
  'Hunan Tou Zhan',
  'Iceland Express',
  'ICSA Groups',
  'Il Bridge',
  'Inci Ayakkabi',
  'India Glycols',
  'Indian Chain',
  'Indian Medical',
  'Indian Oil',
  'Indian Overseas Bank',
  'Indian Railways',
  'Indonesian Power',
  'Info Capital',
  'ING Bank',
  'Interbud Plock',
  'Intobridge.com',
  'Íslenskur landbúnaður',
  'Iso Karhu',
  'Jain Group',
  'Jasa Marga Jakarta',
  'Jet Immo',
  'Jiang You',
  'Jiangxi Hengkang',
  'Jilin Dingyuan',
  'Jin Rong',
  'Jin Jing',
  'Jing Tie',
  'Jinsheng Development',
  'JL Car',
  'JP Morgan',
  'K.W. Tam',
  'Kale Park',
  'Karasu Mermer',
  'Kare Dam',
  'Kaushik Hyderabad',
  'Kedai Lae',
  'KH Power',
  "Kini's Bangalore",
  'Kirmizi Beyaz',
  'KIS Sigorta',
  'Kjaran ehf',
  'Klika Murcki',
  'Kollgáta Arkitektúr',
  'Kombi Tondano',
  'Konga-Väster',
  'KONKRET Chelmno',
  'konkurs.no',
  'Kosmos Delhi',
  'Krishnapatnam Port',
  'Kuncheng Group',
  'Kurt-Royce',
  'L&Y Law',
  'Lag os',
  'LAPI Laboratories',
  'Latteria TS Rzepin',
  'Lekta ehf',
  'Lianhua Keji',
  'Lianzhong Shi Jie',
  'LMI Tomohon',
  'Logi Smart',
  'Lögfræðiskrifstofa Islands',
  'Lögfræðistofa Bjarna',
  'Lu Cheng',
  'Lu Ning Coal',
  'Lupo Veloce',
  'Lv Hua',
  'Mai Zi Fu Shi',
  'Málning hf',
  'Manado Berkat',
  'Manado Cerdas',
  'Mandiri Minahasa',
  'Magma Zawiercie',
  'Magpa-Grup',
  'Maksoy-Deniz',
  'Malermester Mathisen',
  'Manzoya Casual',
  'Mayur Renergy',
  'MB-Transit',
  'Mech-Ok',
  'Meditepe Tip',
  'Mega Bara Mandiri',
  'Mega Bekasi Hypermall',
  'Mega Giant',
  'Mega-Tech',
  'Mei Kuang',
  'Meilin Qing Cheng',
  'Metropolitan Electricity Authority',
  'Mingxin Jituan',
  'Mitra Buana',
  'MONBU Japanese Ministry',
  'Moscow Sunday Times',
  'Mutiara Energy',
  'Myvatn Hotel',
  'Nanfang Dianwang',
  'Nangang Power',
  'Nanning Yalun',
  'Nescafe Gold',
  'Nest Inn',
  'Nimbusz',
  'Nong Fa Hang',
  'Nordfyns Finans',
  'Nordic Security',
  'Novi Kod',
  'Nuo Hui Jian Kang',
  'OCI Copper',
  'Odak Göz',
  'OICO Maesa',
  'Oly-Star',
  'Orbis Investment Management',
  'Org Reignwood',
  'Palma Karya Mandiri',
  'Pan China Construction',
  'Pasta z Bobra',
  'Parvomay Tomato',
  'PD Real Estate',
  'PD Times',
  'PD Transnational',
  'Penajam PU',
  'Perbankan Jatim',
  'Perusahaan Listrik Negara',
  'PGN Jakarta',
  'Pharma Plus',
  'PHE Philippines',
  'Phoenix Mills',
  'Phoenix TV',
  'Pliska XO',
  'PLN Fortuga',
  'PLN Suluttenggo',
  'Plovac Ploski',
  'Poddar Developers',
  'Poddar Housing',
  'Polarman Regnskap',
  'Ponar Unia',
  'Powszechna Kasa Oszczędności Bank Polski',
  'Prestige Development',
  'PRI Investment',
  'Pro Consul',
  'PU Bitung',
  'PU Minsel',
  'PU Sulut',
  'PT Bayu Buana Gemilang',
  'PT Bumi Siak Pusako',
  'Qianli Guangda',
  'QingLong KeJi',
  'Qingnian Qiche',
  'Quik Tea',
  'Ragn Sells',
  'Red Bull',
  'Red Cotton',
  'Rigainvites.lv',
  'Rio-Sampa',
  'Ronke Camping',
  'Rosa dei Venti',
  'RSUD Mandau',
  'Russian Sunday Times',
  'Ryan Express',
  'SAIC VW',
  'Sarla Fibers',
  'Samadhan Academy',
  'Samtronic Constanta',
  'San-Sac',
  'San Chen',
  'San Yutian',
  'Sanliurfa Tarim',
  'Sanya Haihe',
  'Sanya Jiguan',
  'Sanya Tianze',
  'SAPW Poland',
  'Sarunta Waya',
  'Sawahlunto Berkah',
  'Scania Bridgekonsul',
  'SD Associates',
  'SD Enterprises',
  'SD Traders',
  'See Fah/Thai',
  'Semangat Baru Makassar',
  'Semen Gresik',
  'Set ehf',
  'Shan Hai',
  'Shanghai Automobile',
  'Shanghai Chenyi',
  'Shanghai Financial',
  'Shanghai Gaohe',
  'Shanghai Jiahua',
  'Shanghai Jinchang',
  'Zhejiang Jingfan',
  'Shanghai Ling Mu',
  'Shanghai Media and Entertainment Group',
  'Shanghai Qiche',
  'Shanghai Qihao',
  'Shanghai Qi Zhong',
  'Shanghai Weiyu',
  'Shanghai Yitong',
  'Shanghai Zhongfu',
  'Shanxi Luning',
  'Shanxi Qinlian',
  'Shen Jiu',
  'Sheng He Wan',
  'Sheng Tao Sha',
  'Sheng Yu Tian',
  'Sheng Yuan',
  'Shenha Qiaoyou',
  'Shenzhen Electronic City',
  'Shenzhen Huabei',
  'Shenzhen Lanpu',
  'Shenzhen Nangang',
  'Shenzhen Ping An',
  'Shenzhen Qiayao',
  'Shenzhen Qiyuan',
  'Shenzhen Topone Car',
  'Shi He Dong Li',
  'Shi You',
  'Shiji Changda',
  'Shree Cement',
  'Shree Radhey',
  'Sichuan Dahe',
  'Siji Changda',
  'Sing Phil',
  'Siwik Holiday Mragowo',
  'Siwik Intertrade',
  'Skinney-Þinganes',
  'SLG Skeidar',
  'Smart Max',
  'Société Générale',
  'Sol da Caparica',
  'Sölufélag Garðyrkjumanna',
  'Son Dakika',
  'Sparisjóður Keflavik',
  'Sparisjóður Norðfjörður',
  'Sparisjóður Siglufjarðar',
  'Spasso Food',
  'Spintop Ventures',
  'SPS Construction',
  'SR Group',
  'Stanicic Software',
  'Staryi Master',
  'Statu Denizcilik',
  'Statu Gemi Kiralama',
  'Stonehill Capital',
  'Stroiprodukt Kraich',
  'Sunchime Cartoon',
  'Sunchime Fund',
  'Sung Tao',
  'Suzhou Youtong',
  'Svartisen.com',
  'SY Sheng Yutain',
  'Syabas Energy',
  'Sygnity',
  'Synergia Ilanka',
  'Synergia Lublin',
  'TAM Dabrowa',
  'Tangerang Raya',
  'Tannlege Kvaran',
  'Taste of Goa',
  'Tata Consulting Services',
  'Team Audita',
  'Team PharmaService',
  'Team Secure',
  'Techbud Elblag',
  'Telkom Groovia',
  'Telkom IndiBiz',
  'Telkom IndiHome',
  'Telkom IndiSchool',
  'Telkom Indonesia',
  'Telkom Jabar',
  'Telkom Jakarta',
  'Telkom Speedy',
  'Telkom UseeTV',
  'Telkom@wifi.id',
  'TGBC Indibiz',
  'Thai Oil',
  'TianJin JS2',
  'Tick Cad',
  'Tielu Jixie',
  'Tin Fok',
  'TJ Jabung Brt',
  'Tolani Shipping Ltd',
  'Trambak Rubber',
  'Tricon Infotech',
  'Triglav Osiguranje',
  'TTK Healthcare',
  'Turkish Power',
  'TVS Mobility',
  'TVS Tread',
  'Unia Leszno',
  'Unia Winkhaus',
  'Unia Sygnitas',
  'UTI Bank',
  'Value Media',
  'VBS Fjárfestingarbanki hf.',
  'Vidbot ehf',
  'Viego Regnskap',
  'Villa Yustina',
  'Vinex Preslav',
  'Viru Valge',
  'VVE Beheer',
  'Wenang Sintesa',
  'Worldbridgetour.com',
  'Wuhan Dongfang',
  "Xia'er Xili",
  'Xiamen Xiashun',
  'Xiao Ying',
  'Xin He Jin Tai',
  'XP Digital',
  'Yalu Group',
  'Yanjin Puzi',
  'Yeh Bros',
  'Yibin China Resources',
  'Yi Tong',
  'YJ Health',
  'YOU Singapore',
  'Yufeng Electric',
  'Yunnan Dikuang Resources',
  'Yunnan Tongya',
  'zagraj.pl',
  'Z-Tech',
  'Zhai Meng Yi Dao',
  'Zhe Da Wang Xin',
  'Zhejiang Jingfan',
  'Zhejiang Jinjian',
  'Zhejiang Xinxiang',
  'Zhenjiang Hanbang',
  'Zhenjiang Jingjiang',
  'Zhong Guo Ren Bao',
  'Zhong Liang Y LW',
  'Zhong Yuan',
  'Zhongshan Jiegao',
  'Zhongtong Jiangsu',
  'Zhu Jiang',
  'Zweryfikuj firme',
);

my %MULTI_TYPOS =
(
  "A-Media Sieradz" => ['a-media'],
  'Abadi Adimulia' => ['abadi adi mulia', 'abadi adimulya'],
  'Abadi Jaya' => ['jaya abadi granitam'],
  'Adaro Energy' => ['geo adaro'],
  'Agena Development' => ['agena dvt'],
  'Agsar Paints' => ['agsar pints'],
  'AJ Diament' => [
    'aj diamonds', 
    'a.j.diament',
    'a.j. diament',
    'diament'],
  'Alfa-Compensa Gdynia' => ['alfa gdynia'],
  'Apical' => ['apical krn', 'gbc apical'],
  'Apreo Logistic Poland' => ['apreo logistic pol', 'apreo logistic pola'],
  'Asko-Tech' => ['asco tech', 'asko tech', 'asko-tech'],
  'Atlantic Trade' => ['atlantic grupa', 'antlantic trade'],
  'Baltic Express' => ['baltic expres'],
  'Bangur Cement' => ['bangur cements', 'bangur cment', 'bangr cement'],
  'Bank Nagari' => ['bank nagari sikoci',
    'bank nagari simpeda', 'bank nagari tahari'],
  'Bank Tabungan Negara' => ['bank btn'],
  'Bapenda Manado' => ['bappenda manado'],
  'Baroda Bank' => ['baroda bang'],
  'Beidike' => ['bei di ke'],
  'Beijing Century' => ['bei jing shi ji'],
  'Beijing Construction' => ['beijing jianzhu'],
  'Beijing Huayuan' => ['beijing hua yuan', 'bj huayuan'],
  'Beijing Hull Technology' => ['beijing hull tech'],
  'Beijing Railway Bureau' => ['beijing ry. bureau'],
  'Beijing ShouChuang' => ['bj shouchuang'],
  'Beijing Trinergy' => ['beijing trinergyy'],
  'Beijing Wan Jia' => ['bei jing wan jia'],
  'Beijing Yue Ze' => ['bei jing yue ze'],
  'Betri Ferðir' => ['betri ferdir'],
  'PU Bitung' => ['bitung pu'],
  'Breki Jarðverk' => ['breki jarðverk ehf'],
  'Bridge for Business' => ['bridge for businnes'],
  'Bridge for Fun' => ['Bridge 4 Fun'],
  'bridge24.pl' => [
    'bidge24.pl', 
    'birdge24.pl', 
    'bridge 24', 
    'bridge 24pl',
    'bridge24', 
    'bridge24pl', 
    'bridge24_pl',
    'bridge24 mgr', 
    'bridge24 pla',
    'brydz.24'],
  'Bridgefélag Reykjavíkur' => ['bridgefélag Reykjav'],
  'Bridgescanner' => ['bridge scanners', 'bridgescanner 2.0',
    'bridgescanne wr', 'b-scanner'],
  'Bridge Winners' => ['bridge winner', 'bridgewinners.com'],
  'Cai Fu Zheng Quan' => ['cai fu'],
  'Caretta International' => ['caretta int'],
  'China Finance' => ['china finance ba'],
  'China Ping An' => ['zg pingan', 'zg  pingan', 'china pingan',
    'ping an'],
  'China Resources' => ['cr power', 'china res. power', 'cr enterprise',
    'cr_ power'],
  'Chateau Rossenovo' => ['chatteau rossenovo', 'chatteu rossenovo',
    'chaetou rosenovo', 'shato rosenovo', 'shato rossenovo'],
  'Chengdu Zhongtai' => ['Chengdu zt'],
  'China Global Times' => ['chinal global times', 'huan qiu Shi bao'],
  'China Trinergy' => ['chinatrinergy'],
  'CONNECTOR' => ['aj-connector', 'aj connector'],
  'Dalian Aoxin' => ['da lian ao xin'],
  'Data Steel' => ['datta steel'],
  'Delta TV' => ['delta tv programs'],
  'Dentgroup Nisantasi' => ['dentgroup nýþantaþý'],
  'Dhampur Sugar' => [
    'dampur sugar mills',
    'dhampr sugar',
    'dhampr sugar mills',
    'dhampu sugar mills',
    'dhampor sugar mills', 
    'dhampur sm', 
    'dhampur sugar mills', 
    'dhampur sugars', 
    'dhampur suger', 
    'dhampur suger mills', 
    'dhampur sgar mills', 
    'sugar mills', 
    'd s m'],
  'Diebold Nixdorf Krakow' => ['diebold nixdorf cra'],
  'Djarum Black' => ['djarum black capp', 'djarum black mild'],
  Djarum => ['djarum la', 'djarum mld'],
  'Dobre Zegary' => ['dobre_zegary', 'dobrezegary.pl'],
  'domwaluty.pl' => ['domwaluty_pl'],
  Dongfeng => ['dongfeng automobile', 'dong feng', 'dongfeng qiche',
    'dongfeng fengsheng', 'dongfeng fengshen'],
  'Easy Bridge' => ['eazy bridge'],
  EcoSoft => ['eco soft'],
  'Eden Realty Kolkata' => [
    'eden city', 
    'eden city kolkata',
    'eden realities',
    'eden reality',
    'eden reality kolkat',
    'eden realty'],
  'Eko-Al' => ['eko al', 'eko_al'],
  Elastron => ['elastron (taurus)'],
  'Elektrik P3B' => ['elektrik merapi', 'electric merapi'],
  'Eskom IT' => ['eskom warszawa', 'eskom warsaw', 'eskom+friends',
    'fundacja eskom'],
  'Falck Medical' => ['falck med'],
  'Fanhua Jituan' => ['fan hua'],
  'Fantoni Vacations' => ['fantoni vacation', 'fantoni vacatiosn'],
  'Ferðaskrifstofa Vesturlands' => ['ferðask. vesturl.',
    'ferðaskrifstofa ves'],
  'forumbridge.pl' => ['forumbridge_pl'],
  FullBridge => ['full bridge'],
  'FX Securities' => ['fx sec_'],
  'Garðar & Vélar' => ['garðar & vélar ehf.', 'garðar og vélar',
    'gardar og velar'],
  'Garðs Apotek' => ['garðs apótek', 'garðs apoótek', 'garps apótek'],
  'Geely Automobile' => ['geely auto', 'gely auto', 'chaina geely',
    'china geely', 'jili', 'china geely auto', 'jili qiche', 'ji li'],
  'Geo Timah' => ['geo tima', 'geologi timah'],
  Geologi => ['badan geologi', 'geo coal', 'geo tanito harum'],
  'Geologi Banpu' => ['geo banpu'],
  'Godfrey Phillips' => ['gofrey phillips'],
  'Gong Hang Jin Ying' => ['gonghang jinying', 'jin ying club',
    'jin ying', 'gonghang jinying'],
  'Guangdong Huachu Chemicals' => ['g.d. huach', 'guang dong hua chu'],
  'Guangzhou Huachu Chemicals' => ['gz huachu chem'],
  'Guangzhou Pearl River' => ['gz pearl river', 
    'guangzhou pearl river development'],
  'Guiyuang Bank' => ['gy yinhang'],
  'Hangzhou Jinjiang' => ['hangzhou jingjiang'],
  'Hengsha Haijiu' => ['hengsha jiuhai'],
  'Hengsha Ke Ji' => ['heng sha ke ji'],
  'Hengzhou Group' => ['hengzhou j.r.j', 'hengzhou jinrongjia',
    'hengzhou jituan'],
  'HF Verðbréf' => ['h.f. verðbréf'],
  'Holzhauer IT-Service' => ['Holzhauer IT-Servi'],
  'Hótel Hamar' => ['hotel hamar'],
  'Hótel Norðurljós' => ['hotel nordurljos'],
  Huayuan => ['hua yuan'],
  'Hubei Bank' => ['hu bei yin shang'],
  'Hubei Dongfeng' => ['hb dongfeng', 'hu bei dong feng qi'],
  'Hunan Mingkai' => ['hu nan ming kai'],
  'Hunan Tou Zhan' => ['hn  tuozhan'],
  'Il Bridge' => ['asd il bridge'],
  Lavazza => ['il bridge - lavazza'],
  'ICSA Groups' => ['icsa group'],
  'India Glycols' => [
    'india glycil', 
    'india glyclos', 
    'india glycol', 
    'india glycol ltd', 
    'india glycols ltd.',
    'indian gglyccols',
    'indian glycols'],
  'Indian Medical' => ['indian medical asso'],
  'Indian Railways' => [
    'indianrailways', 
    'indian rail', 
    'indian railway', 
    'indian railwayas', 
    'indian railyaws',
    'indian rly',
    'indians railways',
    'indin railways'], 
  'Indonesian Power' => ['indo power', 'indonesia power',
    'elektrika ind power', 'elektrika bc', 'i p'],
  'ING Bank' => ['ng bank'],
  'Íslenskur landbúnaður' => [
    'íslenskur landbúnað',
    'ísl. landbúnaður'],
  'Jasa Marga Jakarta' => ['jasa marga'],
  'Jet Immo' => ['get immo', 'get-immo'],
  'Jiangxi Hengkang' => ['jiang xi heng kang'],
  'Jinsheng Development' => ['jinsheng fazhan'],
  'K.W. Tam' => ['k w tam', 'kw tam'],
  'Kaushik Hyderabad' => ['kaushik hyd.'],
  'KH Power' => ['k h power'],
  "Kini's Bangalore" => ["kini's bengalore"],
  'Kjaran ehf' => ['kjaran golfbúnaður'],
  'KONKRET Chelmno' => ['konkret che³mno'],
  'Krishnapatnam Port' => ['krishnapatam port'],
  'Kuncheng Group' => ['kucheng group'],
  'L&Y Law' => ['l&y'],
  'Latteria TS Rzepin' => [
    'latteria tinis',
    'latteria ts rzeppin',
    'latteria t-s rzepin', 
    'latteria rzepin'],
  'Lögfræðiskrifstofa Islands' => [
    'logfraedistofa isla',
    'lögfr.íslands', 
    'lögfr.stofa íslands', 
    'lögfrst. íslands', 
    'lögfrst.íslands', 
    'logfrædistofa islan',
    'lögfræðisk. ísl.',
    'lögfræðist. ísl.', 
    'lögfræðist. íslands', 
    'lögfræðist.íslands',
    'lögfræðiskrifst. ís', 
    'lögfræðistofa ís.',
    'lögfræðistofa ísl',
    'lögfræðistofa íslan',
    'lögrfæðistofa íslan'],
  'Lögfræðistofa Bjarna' => ['lögfr.st bjarna', 'lögfr.stofa bjarna',
    'lögfr.stofa ´bjarna'],
  Macakizi => ['maca kizi'],
  'Magma Zawiercie' => ['magma  zawiercie'],
  'Magpa-Grup' => ['magma-grup'],
  'Malermester Mathisen' => ['malermester mathise',
    'malermester martins'],
  'Málning hf' => ['målning hf', 'malning hf'],
  'Manzoya Casual' => ['manzova casual'],
  'Meditepe Tip' => ['medýtepe tip', 'meditepe týp'],
  'Mega Bekasi Hypermall' => ['mega bekasi', 'mega bekasi hyperma',
    'mbh bc', 'mbh bridge com'],
  Metaforsa => ['gbc metaforsa'],
  Mitratani => ['mitra tani'],
  Modalfa => ['modalfa/umw'],
  'Mutiara Energy' => ['mutiara energy indo', 'mutiara energi indo',
    'mutiara energi p.', 'mutiara energi.p'],
  'Nanfang Dianwang' => ['nan fang dian wang', 'dian wang'],
  'Nangang Power' => ['nanguang power'],
  'Nanyuan' => ['nan-yuan'],
  'Nuo Hui Jian Kang' => ['nuohui jiankang'],
  'OCI Copper' => ['oci coppers'],
  'Odak Göz' => ['odak goz'],
  'Oly-Star' => ['oly star'],
  'PD Times' => ['p d times', 'pd shidai', 'pd  shidai', 'pd  times'],
  'Pan China Construction' => ['pan-china const', 'pan china construct'],
  'Pan China Group' => ['pan-china group'],
  'Perbankan Jatim' => ['perbankan_jatim'],
  'Pertamina' => ['pertamina ep', 'p-ep', 'pertamina ft', 
    'pertamina field', 'pertamina ge', 'pertamina indonesia', 
    'pertamina field t', 'pertamina l.', 'pertamina field tmb', 
    'pertamina ep field'],
  'Perusahaan Listrik Negara' => ['pln pusat'],
  'Phoenix TV' => ['feng huang wei shi', 'fenghuang tv'],
  'Pliska XO' => ['pliska x.o.', 'pliska x. o.',
    'pliska o. x.'],
  'PLN Fortuga' => ['pln - fortuga'],
  'Poddar Developers' => ['poddar development', 'poddar dev',
    'podder dev', 'podder developers', 'poddar devekopers',
    'poddar dovelopers'],
  'Poddar Housing' => ['poddar  housing', 'poddar hsg'],
  'POLFA' => ['polfa wzbs'],
  'Powszechna Kasa Oszczędności Bank Polski' => ['pko bp'],
  'PT Bayu Buana Gemilang' => ['pt bbg'],
  'PT Bumi Siak Pusako' => ['pt.bumi siak pusako',
    'bumi siak pusako', 'pt bsp'],
  Pufa => ['pu fa'],
  'Ragn Sells' => ['ragn-sells'],
  'Rigainvites.lv' => ['rigainvites lv'],
  'Ryan Express' => ['ryan_express'],
  'Samtronic Constanta' => ['samtronic ct'],
  'San Chen' => ['san chen fund', 'sanchen fund'],
  'Sanliurfa Tarim' => ['urfa tarim'],
  'Sanya Tianze' => ['san ya tian ze'],
  'SAPW Poland' => ['sapw-poland'],
  'Sarla Fibers' => ['sarala fibres', 'sarla fibres'],
  'SD Traders' => ['s.d.traders'],
  'See Fah/Thai' => ['seefa/thai'],
  'Semangat Baru Makassar' => ['semangat baru mks', 'semangat baru mks.',
    'semangat br', 'semangat baru', 'semangat baru mksr',
    'makassar semangat b', 'sb. sulsel'],
  'Shanghai Automobile' => ['shanghai automoblie', 'sh  qiche',
    'sh qiche', 'shanghai auto'],
  'Shanghai Changyu' => ['sh chuangyu'],
  'Shanghai Financial' => ['shanghai finance',
    'shanghai caijing'],
  'Shanghai Gaohe' => ['shanghai gaowe'],
  'Shanghai Jiahua' => ['shanghai jia hua'],
  'Shanghai Jingfan' => ['sh jingfan'],
  'Shanghai Ling Mu' => ['ling mu'],
  'Shanghai Qiche' => ['shanghai qi che'],
  'Shanghai Qihao' => ['sh qihao'],
  'Shanghai Qi Zhong' => ['shang hai qi zhong'],
  'Shanghai Zhongfu' => ['shang hai zhong fu'],
  'Shanxi Qinlian' => ['shan xi qin lian', 'shanxi qinlian',
    'qin lian club', 'qin lian'],
  'Shengheng' => ['sheng-heng'],
  'Shenzhen Huabei' => ['shen zhen hua bei g'],
  'Shenzhen Nangang' => [
    'nan gang',
    'nan gang dong li',
    'nangang dongli', 
    's.z. nangang power', 
    'shen zhen nan gang', 
    'shenzeh nangang', 
    'shenzen nangang',
    'shenzhen nagang p',
    'shenzhen nangang po'],
  'Shenzhen Ping An' => ['shen zhen ping an', 'shenzhen pingan'],
  'Shenzhen Qiyuan' => ['shen zhen qi yuan'],
  'Shenzhen Topone Car' => ['shenzhen topone', 'sz topone car'],
  'Shiji Changda' => ['chang da', 'shijichangda', 'shi ji chang da'],
  'Shree Cement' => [
    'shre cement', 
    'shree ceement',
    'shree cements', 
    'shree cemnent',
    'sree cement',
    'sree  cement',
    'sri cements'],
  'Shree Radhey' => [
    'shree radhye', 
    'shree radheya', 
    'shree radkeya', 
    'shri radhey', 
    'shri radheya',
    'sree radhye', 
    'sri radhey'],
  'Siwik Holiday Mragowo' => ['siwik holiday bt', 'siwik holiday mrag',
    'siwik mragowo'],
  'Société Générale' => ['societe generale', 'societè general'],
  'Sölufélag Garðyrkjumanna' => ['sölufélag garð'],
  'Sparisjóður Keflavik' => ['sparisjóður kef'],
  'Sparisjóður Norðfjörður' => ['sparisjóður norðfj',
    'sparisjóður norð.'],
  'Sparisjóður Siglufjarðar' => ['sparisjóður sigl',
    'sparisjóður sigluf', 'sparisjóður siglufj', 'sparisj. siglufjarð',
    'sparisj.siglufj', 'sparisj.siglufjarð',
    'sparisj.siglufjarða', 'sarpisj.siglufjarð', 'spariisj.siglufjarð'],
  'Spasso Food' => ['spassofood'],
  SportAccord => ['sport accord'],
  'SPS Construction' => ['sps cons', 'sps constraction'],
  'SY Sheng Yutain' => ['s.y. shengyutain'],
  'Syabas Energy' => ['syabas energi', 'syabas e'],
  'Synergia Lublin' => ['synergia lubin'],
  'Team PharmaService' => ['pharma service', 'pharmaservice', 
    'pharma services', 'team phlink'],
  'Telkom IndiHome' => ['telkom indiehome', 'telkom indihome mm'],
  'Telkom Indonesia' => ['telkom ind indihome', 'telkom indonesia',
    'telkom wifi.id', 'telkom wifi. id', 'telkom group'],
  'Telkom Speedy' => ['telkom speedy bpn'],
  'Tick Cad' => ['tick cad ehf'],
  Timah => ['pt_ timah limited', 'pt timah limited', 'pt_ timah ltd',
    'pt_timah','pt_ timah', 'pt timah'],
  'Tolani Shipping Ltd' => ['tolani shipping'],
  'Trambak Rubber' => ['trumpak rubber'],
  'Triglav Osiguranje' => ['triglav osig.'],
  'Unia Sygnitas' => ['unia-sygnitas'],
  'Unia Winkhaus' => ['winkhaus unia', 'winkhaus-unia',
    'ks winkhaus unia'],
  'Value Media' => ['value media team', 'synis value'],
  'Viego Regnskap' => ['viego regnskap as'],
  'VVE Beheer' => ['vve-beheer'],
  'Wenang Sintesa' => ['wenang sintesa p'],
  'Worldbridgetour.com' => ['worldtourbridge.org',
    'worldbridgetour.org', 'world bridge tour', 'wbt bridge app'],
  'Wuhan Dongfang' => ['dongfang'],
  "Xia'er Xili" => ['xia er xi li'],
  'Xiao Ying' => ['xiao ying inn'],
  'Yalu Group' => ['js yalu'],
  'Yeh Bros' => ['yeh brothers', 'yer bros', "yeh's bros", 'yehs bros',
    'yer bros', 'yeoh bros'],
  'Yibin China Resources' => ['yibin cr gas', 'yibin china resourc'],
  'Yunnan Dikuang Resources' => ['yunnan dikuang', 'yun nan'],
  'zagraj.pl' => ['zagraj pl'],
  'Zhejiang Huamen' => ['zhe jiang hua men', 'zj huamen', 'hua men'],
  'Zhejiang Jingfan' => ['zj jingfan', 'jing fan club', 'jin fan',
    'jing fan'],
  'Zhongshan Jiegao' => ['zhong shan jie gao'],
  'Zhongtong Jiangsu' => ['zhongtong js'],
  'Zweryfikuj Firme' => ['zweryfikuj firme.pl']
);

my @SINGLE_WORDS = qw(
  ABAX Abnegat Accenture Actavis Aerospace AIA Akaylar Akebono
  Aklindo Allianz Altinay Apical Apullum Aquatrans Arboned 
  Argento Arkas Arma Artotec Asindo Avia Ayýntab

  Bajaj Baykar Beibao Beidike Belisol Bnerg BridgePlus Budimex

  Cable Candyland Cempaka Changyu Chemikartel Chlodnia Chuanmei 
  Cimentas COMAL Compensa Computerland CONNECTOR CONSUS Constellation 
  Continental Copia Cosmos

  Datang Denizgucu Dermika Derofe Dianwang DISKI Djarum 
  Dongfeng Dostlar Druva

  EcoSoft Effcontrol Eimskip Eksprompt Elastron Elektrika Elektrociepl
  Energetyk Enorma Enterprise ESSO Evertrust

  Fatek Forbo Forta Frissan FullBridge Funbridge

  GAMAX GaoSuDa Gazprom Generali Geologi Genkad Gevalia Gillette Gomad 
  Gözgöz Guowang GSE

  Hana Haoxin Harke Haustak HCL HNA Honesta Hongyu Horsa Huachu Huayuan

  IBM IMAX Impress Indoarsip Intan Inteligent Interface Interkala

  Jetox Jiegao Jinfan Jinshi Junibacken

  Kadimex Kancelaria Kayseria Kideko Kilogrupp Konstanta Kunhua Kvika

  Lacznosc Laima Lavazza LCG Lianbo Likom Longjiangfu Lukomorie 
  Lyfjaver

  Macakizi Makus Malkia Melchemie Metaforsa Mireo Mitratani Modalfa 
  Morgunblaðið Multicoms Myndform

  NALCO Nanyuan Navachaitanya Navayuga Nazwa NEC Nefka Niewiem Nongken 
  Norco Nortemp NOTUS Näkösoppi

  Ozyuva

  P2TEL Paulaner Pealinn Penline Pertagas Pertamina Petroconas Pexis 
  Petro Pharon Pimara POLFA Praterm Prokom Printerikeskus Pufa Pusula

  Qiaoyou Qinjia

  Raam Radex Ráðgjöf Ravebo Relpol Ruyi Ryka

  Sagaplast Samsung Saniva Scandic Scania Sehati Sevtopolis Shengheng
  Shichuang Shimuzu Shouchuang Sifute Signity Skeljungur Skobud
  Solakoglu Solox Sparisjóður 
  SportAccord Srenniw SSDA Stalgast Stiga Stokrotka Struma Suiyi
  Synective 
  Synrey Syntex

  Tekser Telkom Termika Termoavion Termochem Timah Topeko Transearly 
  Tricon Tridaya Tryggingamiðstöðin Tsingtao Tundem Twentebelt
  Tyco Tzilis

  UMW Unibet Unicat Uras

  Velbazhd Velbujd Videocon Vinabær Virnet VÍS Visoft Vito Vyceska

  Wellknit Wellwise Wise

  Yuetao

  Zhaoeng Zhonghai Zolza
);

my %SINGLE_TYPOS =
(
  'Adaro Energy' => ['adaro'],
  'Advisor Revisjon Norge' => ['advisor'],
  'Agena Development' => ['agena'],
  'Agsar Paints' => ['agsar'],
  'Alfa-Compensa Gdynia' => ['compensa'],
  Apullum => ['aupullum'],
  'Bank Negara Indonesia' => ['bni'],
  'Bank Tabungan Negara' => ['btn'],
  'Beijing Trinergy' => ['beijingtrinergy'],
  'BridgeBertheau.com' => ['bridgebertheau', 'bridgeberteau'],
  'Bridge for Fun' => ['b4f'],
  'Carlo Bossi' => ['carlobossi'],
  'Chateau Rossenovo' => ['rossenovo', 'rosenovo'],
  'Chennai Online' => ['chennaionline'],
  'China Ping An' => ['chinapingan', 'zhongguopingan', 'pingan'],
  'China National Petroleum Corporation' => ['cnpc'],
  Cimentas => ['çimentaþ'],
  Computerland => ['computerlan'],
  CONNECTOR => ['conector'],
  'Data Steel' => ['datasteel'],
  'Dhampur Sugar' => ['dhampur', 'dsm'],
  DISKI => ['dsi', 'dsý',],
  Djarum => ['diarum'],
  Eksprompt => ['ekspromt'],
  'Elektrik P3B' => ['elektrik', 'electric'],
  Elektrika => ['elektric'],
  'Fanhua Jituan' => ['fanhua'],
  'FX Securities' => ['fxsec'],
  'Garðs Apotek' => ['garðsapótek'],
  Geologi => ['geo'],
  'Geoportal Kutai Kartanegara' => ['geokutaikartanegara',
    'geo kutai kartanegra'],
  Gevalia => ['gevalía'],
  Gillette => ['gilette'],
  'Gong Hang Jin Ying' => ['jinying'],
  Gözgöz => ['gozgoz'],
  'Guangzhou Hongmian' => ['guangzhouhongmian', 'hongmian'],
  'Guangzhou Pearl River' => ['guangzhoupearlriver', 
    'guangzhouperalriver'],
  'Heng Yuan Xiang' => ['hyx'],
  'Hong Kong Vico' => ['vico'],
  'Hong Zhu' => ['hongzhu'],
  'Indian Overseas Bank' => ['iob'],
  'Indian Railways' => ['railways'],
  Indoarsip => ['indoarship'],
  'Jasa Marga Jakarta' => ['jasamarga'],
  'Jilin Dingyuan' => ['jilindingyuan'],
  'Jin Rong' => ['jinrongjia'],
  'Kale Park' => ['kalepark'],
  'KH Power' => ['khpower'],
  'Kideko' => ['kideco'],
  'KONKRET Chelmno' => ['konkret'],
  'Kosmos Delhi' => ['kosmos'],
  'Krishnapatnam Port' => ['krishnapatnamport'],
  'Lianzhong Shi Jie' => ['lianzhongshijie'],
  'Lv Hua' => ['lvhua'],
  'Magpa-Grup' => ['magpa'],
  'Málning hf' => ['málning'],
  Metaforsa => ['metaphorsa'],
  'Meilin Qing Cheng' => ['meilinqingcheng'],
  'Mei Kuang' => ['meikuang'],
  'Metropolitan Electricity Authority' => ['mea'],
  'Mitra Buana' => ['mitrabuana'],
  'MONBU Japanese Ministry' => ['monbu'],
  Multicoms => ['multicom'],
  'Nanning Yalun' => ['nanning yalun'],
  'Nest Inn' => ['nestinn'],
  'Oly-Star' => ['olyster'],
  'Orbis Investment Management' => ['orbis'],
  'Perbankan Jatim' => ['perbankan'],
  'Poddar Developers' => ['poddar'],
  'Pro Consul' => ['proconsul', 'consul'],
  'PU Minsel' => ['minsel'],
  'Perusahaan Listrik Negara' => ['pln'],
  'Phoenix TV' => ['fenghuang'],
  'PT Bayu Buana Gemilang' => ['bbg'],
  'Rigainvites.lv' => ['rigainvites'],
  'SAIC VW' => ['saic'],
  'Samadhan Academy' => ['samadhan', 'samadgan'],
  'Samtronic Constanta' => ['samtronic'],
  'San Chen' => ['sanchen'],
  'SD Associates' => ['sdassociates'],
  'SD Enterprises' => ['sdenterprises', 'sdenterprizes'],
  'Shanghai Automobile' => ['shangqi'],
  'Shanghai Media and Entertainment Group' => ['smeg'],
  'Shenzhen Lanpu' => ['lanpu'],
  'Shenzhen Nangang' => ['nangangdongli', 'nanggang', 'nangang'],
  'Shi You' => ['shiyou'],
  'Shiji Changda' => ['changda'],
  'Shree Cement' => ['shreecement', 'shree'],
  'Sichuan Dahe' => ['sichuandahe'],
  'Siwik Holiday Mragowo' => ['siwik'],
  'Son Dakika' => ['sondakika'],
  'Sparisjóður' => ['sparisjodur'],
  'SPS Construction' => ['sps'],
  'Tata Consulting Services' => ['tcs'],
  'Team Audita' => ['teamaudita', 'audita'],
  'Timah' => ['tima'],
  'Tricon Infotech' => ['tricon'],
  Tsingtao => ['tsingthao'],
  'TTK Healthcare' => ['ttk'],
  'UTI Bank' => ['utibank'],
  'Value Media' => ['synis'],
  Velbazhd => ['velbuzhd'],
  Videocon => ['videcon'],
  'Viego Regnskap' => ['viego'],
  'Vinex Preslav' => ['vinex'],
  Wellwise => ['wellwiss'],
  'Xiamen Xiashun' => ['xiashun'],
  'Xin He Jin Tai' => ['xhjt'],
  'Yeh Bros' => ['yeh', 'yehbros'],
  'Zhejiang Huamen' => ['huamen'],
  'Zhejiang Jingfan' => ['jingfan']
);


sub set_hashes
{
  my ($method, $key) = @_;

  $method->(\@MULTI_WORDS, \%MULTI_TYPOS,
    \@SINGLE_WORDS, \%SINGLE_TYPOS, $key);
}

1;
