#!perl

use strict;
use warnings;
use v5.10;
use utf8;
use open ':std', ':encoding(UTF-8)';

package Tags::Tname;

our @ISA = qw(Exporter);
our @EXPORT = qw(set_hashes);

my @MULTI_WORDS =
(
  '0 to 1500 Spingold',
  'AfBF Zone 8 Championships',
  'APBF Championships',
  'APBF Youth Championships',
  'African Zonal Championship',
  'All-China Games',
  'All India Corporate Invitational',
  'All India Corporate Invitational Pairs',
  'All India HCL Tournament',
  'All India UTI Bank Masters Championship',
  'Altman Swiss Pairs',
  'Anatolian Club Qualifying',
  'Anatolian Fall Teams',
  'Anatolian Open Teams',
  'Anatolian Spring Teams',
  'Andrzej Wilkosz Memorial Pairs',
  'Ankara Summer Teams',
  'Antonio Chong Cup',
  'Aoda Cup',
  'ArboNed Team Cup',
  'Argentinian Copa Republica',
  'Argentinian Flags Day Championship',
  'Argentinian Mixed Teams',
  'Argentinian Open Teams',
  'Argentinian Seniors Teams',
  'ARIS Cup',
  'Arnhem Interbridge Tournament',
  'Ashok Kapur Memorial Swiss Pairs',
  'ASEAN Club Championship',
  'ASEAN Open Teams',
  'Asia Cup',
  'Asian University Championship',
  'Australian Autumn National Open Teams',
  'Australian Grand National Open Teams',
  'Australian National Open Teams',
  'Australian Open Teams',
  'Australian Open Trials',
  'Australian Seniors Pairs',
  'Australian Seniors Teams',
  'Australian Seniors Trials',
  'Australian Spring Seniors Teams',
  "Australian Spring Women's Teams",
  "Australian Women's Teams",
  "Australian Women's Trials",
  'Australian Youth',
  'Australian Youth Tri Individual',
  'Australian Youth Tri Pairs',
  'Australian Youth Tri Teams',
  'Australian Trials',
  'Australian Youth IMP Pairs',
  'Balikcioglu Teams Championship',
  'Balkan Championship',
  'Balkan Teams',
  'Baltic Bowl',
  'Baltic Cup',
  'Baltic Teams Cup',
  'Balkan Championship',
  'Bastaman Cup',
  'Baze Senior Knock-out',
  'Belgian Open Teams',
  'Bergen Grand Tournament',
  'Bermuda Bowl',
  'Bermuda Triangle Cup',
  'Beskids Slam',
  'BFAME Championship',
  'Bhabha Atomic Research Centre Open',
  'Biarritz Hiver',
  'BKBT Teams',
  'Bobby Evans Seniors Teams',
  'Bolivian Open Teams',
  'Bologna Trophy',
  'Bonn Nations Cup',
  'Brazilian Championship',
  'Brazilian Open',
  'Brazilian Seniors',
  'Brazilian Teams',
  'Brazilian Trials',
  'Brazilian Women',
  'British Gold Cup',
  'British Premier League',
  'Buffett Cup',
  'Bulgarian Open Teams Gabi',
  'Canadian Bridge Championship',
  'Canadian National Teams Championship',
  'Canadian Open Teams Championship',
  'Canadian Seniors Teams Championship',
  'Canadian Women Championship',
  'Canadian Women Teams Championship',
  'Carrousel Cup',
  'Cavendish Pairs',
  'Cavendish Teams',
  'Central American Zonal Championships',
  'Centre Island Teams',
  "Chairman's Cup",
  "Champions' Cup",
  'Channel Trophy',
  'Cherven Briag National Tournament',
  'Chilean Championship',
  'Chilean Cup',
  'Chilean Pairs',
  'Chilean Team Trials',
  'China Elite Tournament',
  'China Friend City Senior Team Tournament',
  'China First League',
  'China Hosts Europe in Rome',
  'Chinese Taipei Trials',
  'Chinese Club Championship',
  'Chung Hua Cup',
  'Cliff Wake Challenge',
  'Codan Cup',
  'Collegiate Bowl',
  'Commonwealth Nations Bridge Championships',
  'Computer World Championship',
  'Copa de Plata',
  'Copa de Oro',
  'Copa Zanalda River Plate',
  'Copenhagen Invitational Pairs',
  'Copenhagen Open Pairs',
  'Coppie Viareggio',
  'Corn Cairdis',
  'Cross Strait Invitational',
  'Czech Championship',
  'Czech Team Championship',
  'Czech First League',
  'Czech Open',
  "d'Orsi",
  'Damiani Cup',
  'Danish Club Teams',
  'Danish Cup',
  'Danish Championship',
  'Danish District Championship',
  'Danish First Division',
  'Danish Junior Teams',
  'Danish Mixed Pairs',
  'Danish Open',
  'Danish Pairs Championship',
  'Danish Teams Championship',
  'Danish Team Trials',
  'Danish Women Pairs',
  'Delhi Gymkhana Club Open',
  'Division Nationale',
  'Dongfeng Cup',
  'Dongming Knock-out Teams',
  'Dr. Heinz von Rotteck Pokal',
  'Dr. Rand Masters',
  'Dutch Knock-Out Cup',
  'Dutch Meesterklasse',
  'Dutch Women',
  'Egyptian League',
  'English Premier League',
  'English Open Trials',
  'English Senior Teams',
  'English Senior Trials',
  'English Women Trials',
  'Estonian First League',
  'Estonian Open Teams',
  'Estonian Open Trials',
  'European Bridge Teams Championship',
  'European Junior Mixed Pairs',
  'European Junior Teams Championship',
  'European Mixed Junior Pairs',
  'European Open Bridge Championship',
  "European Champions' Cup",
  'European Small Federation Games',
  'European University Bridge Championship',
  'European Winter Games',
  'European Women Championship',
  'European Youth Bridge Championship',
  'European Youth Bridge Pairs Championship',
  'European Youth Bridge Teams Championship',
  'EUSA Games',
  'Farmen Invitational',
  'Faroese Teams',
  'Fatih Kiral Cup',
  'Filbyter Cup',
  'Finnish Cup',
  'Finnish Easter Teams',
  'Finnish Pairs Championship',
  'Finnish Teams Championship',
  'Finnish Swiss Teams Championship',
  'Forbo Nations Cup',
  'Forest Trophy',
  'Fortuna Cup',
  'FOSS Grand Tournament',
  'FOSS-Tren',
  'Four Nations Cup',
  'French Cup',
  'French First Division',
  'French Intercircle',
  'French Mixed Teams',
  'French Senior Trials',
  'FullBridge International Teams',
  'Full Tilt Irish Bridge Masters',
  'FX Securities Cup',
  'Gabrial UI Cup',
  'Garden Cities',
  'Gardermoen Airport Hotel Pairs',
  'Gardermoen Airport Hotel Cup',
  'Gelibolu Peace Cup',
  'Geologi Cup',
  'German Club Cup',
  'German Open Teams',
  'German Open Trials',
  'German Team Championship',
  'German Team Trophy',
  'German Women Pairs',
  'GHTD Cup',
  'Goksu-Yalikavak Pairs',
  'Golden Jubilee',
  'Grand National Teams',
  'Grand Prix of Poland',
  'Grand Prix of Poland Pairs',
  'Grand Prix of Prague',
  'Grand Prix of Warsaw',
  'Grand Prix of Wielkopolski',
  'Greek Central Regional Championship',
  'Greek Open Teams',
  'Greek Open Trials',
  "Gro's Supercup",
  'Guangdong Club Championship',
  'Guangdong Club Invitational',
  'Guangdong Elite Tournament',
  'Guangzhou-HK-Macau Interport',
  'Haikou Fitness Day',
  'Hainan Air Cup',
  'Haskovski Mineralni Bani',
  'Hecht Cup',
  'Hellenic Mixed Pairs',
  'Hellenic Team Trials',
  'Hellenic Team Championship',
  'Hellenic Women Team Trials',
  'Higson Cup',
  'High-Tech Zone Workers Invitational',
  'Hungarian Cup',
  'Hungarian IMP Pairs',
  'Hungarian Open Teams',
  'Hungarian Senior trials',
  'HNA Open Teams',
  'Hong Kong Inter-City',
  'Icelandair Open',
  'Icelandair Team Championship',
  'Icelandic Cup',
  'Icelandic Teams',
  'IMSA Cup',
  'IMSA Elite Mind Games',
  'Indian Open Trials',
  'Indian Senior Trials',
  'Indian State Championship',
  'Indonesian Championship',
  'Indonesian Inter-Club Championship',
  'Indonesian Inter-Province Championship',
  'Indonesian Junior League Online',
  'Indonesian League',
  'Indonesian National Games',
  'Indonesian Open Teams',
  'Indonesian Student Championship',
  'Indonesian University Championship',
  'Irish Invitational Pairs',
  'Irish Open Trials',
  'Israel Juniors Championship',
  'Israel Juniors Pairs',
  'Israel Juniors Teams',
  'Israel Open Pairs',
  'Israel Open Teams',
  'Israel Schools',
  'INEA Cup',
  'IOC Grand Prix',
  'Istanbul Winter Teams',
  'Italian Championship',
  'Italian Club Championship',
  'Italian Mixed Teams',
  'Italian Team Championship',
  'Italy Cup',
  'Japanese District KO Teams',
  "Jessheim New Year's Cup",
  'John Arkinstall State Teams',
  'Jordan Spring Mixed Pairs',
  'Jordan Spring Tournament',
  'JPD Cup',
  'Junior Camrose',
  'Kalani Trophy',
  'Karnik-Vaidya Open',
  "Kepri Governor's Cup",
  'Kings and Queens Blaine Howe Teams',
  'König Ludwig Cup',
  'Krakow Spring',
  'Krishnapatnam Port National Masters',
  'Krommenie Nations Cup',
  'Lady Milne Trials',
  'Lady Milne Trophy',
  'Lalit Mohanka Memorial',
  'Lederer Memorial Trophy',
  'Leszek Kwiatkowski Memorial Teams',
  "Linda Stern Women's Teams",
  'Lokmanya Jubilee',
  'Lüleburgaz Liberation Cup',
  'Maccabi Games',
  'Madeira Open',
  'Madeira Swiss Teams',
  'Maharashtra State Championship',
  'Marit Sveaas Tournament',
  'McConnell Cup',
  'Mike Lawrence Exhibition',
  'Milan Trophy',
  "Missouri Braggin' Rights",
  'Mitra Vihar State Championship',
  'Mohan Sicka Trophy',
  'Mohanlal Bhartia Memorial Grand Prix',
  'Mondi Cup',
  'Mondial de Deauville',
  'Mountain Sea Cup',
  'MTP Cup',
  'NABC Senior Knock-Out Teams',
  'NEC Cup',
  'New South Wales State Teams',
  'New Zealand Trials',
  'NN Cup',
  'Nordic Championship',
  'Nordic Cup',
  'Nordic Junior Championship',
  'Nordic Junior Pairs',
  'Nordic Junior Team Championship',
  'Nordic Open Championship',
  'Nordic Race',
  'Nordic Team Championship',
  'Nordic Women Championship',
  'North American Bridge Championship',
  'Northern Greece Regional Championship',
  'Northern Territory Gold Teams',
  'Northern Territory Gold Swiss Pairs',
  'Norwegian Club Pairs',
  'Norwegian Club Teams',
  'Norwegian Club Cup',
  'Norwegian Corporate Championship',
  'Norwegian Mixed Pairs',
  'Norwegian Mixed Teams',
  'Norwegian Open Pairs',
  'Norwegian Open Teams',
  'Norwegian Premier League',
  'Norwegian Swiss Teams',
  'Norwegian Team Trials',
  'Norwegian Teams',
  'NTU Cup',
  'NYSA Euroregion Nations Cup',
  'Olona International Teams',
  'Olrud Easter Mixed Pairs',
  'Olrud Easter Pairs',
  'Olrud Easter Swiss Teams',
  'Olrud Easter Teams',
  'Open Catalunya Preferent',
  'Pahlawan Cup',
  'Pakistan Day Bridge Championship',
  'Palace Cup',
  'Pan Arab Inter-Club Championship',
  'Paris Youth Open Teams',
  'Park Hotell Swiss Teams',
  'Patton de Monaco',
  'Pärnu Summer Invitational Pairs',
  'Pärnu Summer Open Teams',
  'Peggy Bayer',
  'Pesta Sukan',
  'Petit Grand Prix van Driene',
  "Pigg's Peak All Africa",
  'PLN Cup',
  'Plock District League',
  'Poddar National Masters',
  'Polish BAM Teams',
  'Polish Boys Championship',
  'Polish Business League',
  'Polish Commercial Pairs',
  'Polish Girls Championship',
  'Polish Individual Championship',
  'Polish Mixed Teams',
  'Polish Open Teams',
  'Polish Open Trials',
  'Polish Women Trials',
  'Polish Pairs',
  'Polish IMP Pairs',
  'Polish Premier League',
  'Polish Second League',
  'Polish Teams',
  'Polish Top Individual',
  'Polish Youngster Teams',
  'Poznan Mixed Pairs',
  'Pomerania Cup',
  'Portuguese Grand Prix',
  'Portuguese Open Teams',
  'Portuguese Open Trials',
  'Portuguese Northern Regional Open Teams',
  'PRBA State Level Open',
  'Prince Henrik Trophy',
  'Prince Takamatsu Cup',
  'Puutalo Open',
  'PYC Hindu Gymkhana Royale',
  'PYC Hindu Gymkhana PairsRoyale',
  'R N Bagla Memorial Pairs',
  'R Ratnam Memorial',
  'Rand Cup',
  'Rector University of Brawijaya Cup',
  'Rona Cup',
  'Gianarrigo Rona Trophy',
  'Riga Invites to Jurmala',
  'Riau Governor Cup',
  'Rio de Janeiro Championship',
  'Roberto Taunay Cup',
  'Romanian League',
  'Romanian Second League',
  'Romanian Open Teams',
  'Rondane Pairs Cup',
  'Rondane Teams Cup',
  'Rosfjord Swiss Teams',
  'Rottneros Nordic Cup',
  'Ruia Gold Cup',
  'Ruia Silver Cup',
  'Ruia Trophy',
  'Ruter 7 Open',
  'S:t Erik Championship Series',
  'Salo Midsummer Juniors',
  'Samadhan Summer League',
  'Samobor Invitational Bridge Meeting',
  'Sao Paulo State Championship',
  'Sarundajang Cup',
  'Scottish Cup',
  'Scottish National League',
  'Semen Padang Cup',
  'Senior Camrose',
  'Serbian Cup',
  'Serbian Premier League',
  'Serbian Team Championship',
  'Serdika Cup',
  'Shenhua Cup',
  'Shenyang Spring',
  'Shield of Thoisy',
  'Sigismund Bell Krakow',
  'Slava Cup',
  'Slovakian Open Teams',
  'Smirnov Cup',
  'Solomon Teams',
  'South African Championship',
  'South African Teams',
  'South American Open Teams',
  'South American Senior Trials',
  'South American Seniors Teams',
  'South American Women Teams',
  'South American Trials',
  'South Zone Championship',
  'Southeast Asian Games',
  'Spanish Central Zone Teams',
  'Spanish Open Trials',
  'Spanish Senior Trials',
  'Spanish Teams Championship',
  'SPBF Championship',
  'Spring Fours',
  'Spring of Cracow',
  'Spring Nationals',
  'Star Wars',
  'Staszic Pairs Cup',
  'Stena Line Cup',
  'Stern-Cornell Trophy',
  "Sternberg Women's BAM Teams",
  'Stockholm Teams',
  'Sudamericano Transnacional',
  'Summer Monsoon League',
  'Summer Nationals',
  'Sunchime Fund Cup',
  'Suomen Cup',
  'Swedish District Championship',
  'Swedish Juniors Championship',
  'Swedish Juniors Teams',
  'Swedish Open Pairs',
  'Swedish Open Teams',
  'Swedish Open Trials',
  'Swedish Premier League',
  'Swiss Championship',
  'Swiss Club Championship',
  'Swiss Cup',
  'Swiss Open Championship',
  'Swiss Team Championship',
  'Taça Rui Pinto',
  'Takamatsu Cup',
  'Taiwan University Cup',
  'Taiwan University Cup Teachers',
  'Taiwanese Open Trials',
  'Taiwanese Teams',
  'Taiwanese Senior Trials',
  'TATA Open',
  'Teltscher Trophy',
  'TGR Auction',
  'TGR Auction Pairs',
  'TGR Auction Teams',
  'TGR Super League',
  'The Hague Bridge Experience',
  'Thrace Club Teams',
  'Thrace Cup League',
  'Tianjin Binhai Cup',
  'Tolani Gold Trophy',
  'Tolani Grand Prix',
  'Tolani Silver Cup',
  'Top Circuit',
  'Torneo di Rastignano',
  'Torneo di Roma',
  'Toscana Cup',
  'Towns Cup',
  'Transnational Open Teams',
  'Trondheim Cup',
  'Turkish Club Championship',
  'Turkish East & South-East Teams',
  'Turkish East Mediterranean Teams',
  'Turkish Mixed Team Trials',
  'Turkish Mixed Teams Championship',
  'Turkish Open Teams Championship',
  'Turkish Open Trials',
  'Turkish Teams Championship',
  'Turkish Women Teams',
  'Turkish Swiss Mixed Teams',
  'Turkish Winter Championship',
  'Turkish Winter Open Teams',
  'Turkish Winter Women Teams',
  'United States Juniors Bridge Championship',
  'United States Juniors Training',
  'United States Seniors Bridge Championship',
  'United States Women Bridge Championship',
  'US International Team Trials',
  'US Junior Trials',
  'US Senior Trials',
  'US Seniors',
  'US Women',
  'US Youngsters',
  'USBF Challenge Match',
  'Vanderbilt Fantasy Challenge',
  'Varna Titan Teams',
  'Venezuela Swiss Pairs',
  'Venice Cup',
  'Vest-Agder Regional Team Championship',
  'Victor Champion Cup',
  'Victorian Mixed Teams',
  'Victorian Open Teams',
  'Victorian Open Teams Playoff',
  'Victorian Pennant',
  'Victorian Youth',
  'Vilnius Club Pairs',
  'Vinoble Cup',
  'Vito Teams',
  'VV Cup',
  'Warsaw Online Teams',
  'Watermark Bridge Classic',
  'Wellingdon Swiss Pairs',
  'Western Mediterranean Club Teams',
  'White House Juniors',
  'White House Top 12',
  'White House Top 16',
  'Whitelaw Cup',
  'Willoughby Bridge Classic',
  'Winter Open Teams',
  'World Juniors Championship',
  'World Masters Individual',
  'World Men Elite Tournament',
  'World Open Pairs',
  'World Seniors Championships',
  'World Top Tournament',
  'World Transnational Teams',
  'World Transnational Mixed Teams',
  'World Transnational Open Teams',
  'World University Championship',
  'World Youth Congress',
  'World Youth Open Bridge Championship',
  'World Youth Teams Championship',
  'World Youth Bridge Congress',
  'World Youth Bridge Team Championship',
  'World Youth Championship',
  'World Women Elite Tournament',
  'Xinyuan Cup',
  'Yeh Bros Cup',
  'Young Chelsea Knock-out',
  'Zhejiang Huamen Cup',
  "Zia's Individual Goulash",
  'Zimmermann Cup',
  'Zulawski Cup'
);

my %MULTI_TYPOS =
(
  'AfBF Zone 8 Championships' => ['african zone 8 open teams',
    'abf zone 8 championships', 'abf championship', 'abf championships',
    'abf champoinship'],
  'African Zonal Championship' => ['zonal qualifying africa',
    'abf zonal', 'african zone championship',
    'african zonal championships'],
  'All India Corporate Invitational' => [
    'all india invitational corporate'],
  'All India Corporate Invitational Pairs' => [
    'corporate pairs', 'corporate invitational pairs'],
  'All India UTI Bank Masters Championship' => [
    'ull aindia uti bank masters championship',
    'all india uti national masters championship',
    'all india utibank masters championship'],
  'Anatolian Club Qualifying' => ['eastern anatolian qualification',
    'eastern anatolýa qualýfýcatýon',
    'turkish interclubs champ_ anatolia elections'],
  'Anatolian Fall Teams' => ['anatolian side fall teams'],
  'Anatolian Open Teams' => ['anatolian side bridge clubs open teams'],
  'Anatolian Spring Teams' => ['anatolia spring teams'],
  'Andrzej Wilkosz Memorial Pairs' => ['a_ wilkosz pro memoriam'],
  'Ankara Summer Teams' => ['ankara summer team championship'],
  'APBF Championships' => ['pabf championship', 'pabf c'],
  'ArboNed Team Cup' => ['arbo ned team cup', 'arbo ned teams cup'],
  'Argentinian Copa Republica' => ['copa republica'],
  'Argentinian Mixed Teams' => ['argentina equipos mixtos',
    'campeonato nacional equipos mixtos argentino'],
  'Argentinian Open Teams' => ['cn equipos libres argentina',
     'argentine team', 'open argentin team', 'opteamsudamargentina'],
  'Argentinian Seniors Teams' => ['clasificatoria seniors argentina',
    'clasificatoria argentina seniors sudamericano'],
  'Arnhem Interbridge Tournament' => ['interbridge tournament'],
  'ASEAN Club Championship' => ["asean bridge club c'ship",
    'asean bridge club championship', "asean bridge c'ship",
    'asean bridge club', 'asean bridge club championships',
    'asean bridge cship', 'asean bridge championship',
    'asean bridge club open championships',
    'asean bridg club championship', 'asean bridge championships',
    'asean club championships', "aseam bridge club c'ship"],
  'ASEAN Open Teams' => ['asean bridge finals'],
  'Ashok Kapur Memorial Swiss Pairs' => ['ashok kapur memorial',
    'Ashok Kapur Memrial swiss pairs',
    'Ashok Kapur Memrial  swiss pairs',
    'Ashok Kapoor Memorial  Swiss Pairs',
    'Ashok Kapur Memorial Sw2iss Pairs',
    'Ashok Kapur Memorial  Annual All India Pairs',
    'Ashok Kapur Memorial Swiss IMP Pairs'],
  'Asian University Championship' => [
    'asian university bridge championship'],
  'Australian Autumn National Open Teams' => [
    'australian autumn national open  teams',
    'autumn national open teams'],
  'Australian National Open Teams' => ['abf anot',
    'abf national open teams'],
  'Australian Grand National Open Teams' => ['abf gnot',
    'grand national open teams'],
  'Australian Open Teams' => ['aust open', 'australian open tream',
    'australian open team'],
  'Australian Open Trials' => ['abf open team trials', 'abf oprn trials',
    'australian open team trials'],
  'Australian Seniors Pairs' => ['aust seniors pairs'],,
  'Australian Seniors Teams' => ['aust seniors open', 'sen australian',
    'aust senriors open'],
  'Australian Seniors Trials' => ['australian seniors trial'],
  'Australian Spring Seniors Teams' => ['aust spring seniors teams',
    'aust spring seniors', 'australian spring seniors'],
  "Australian Spring Women's Teams" => ['australian spring womens'],
  'Australian Seniors Trials' => ['abf seniors playoff',
    'australian seniors trial'],
  'Australian Trials' => ['abf trials', 'abf team trials',
    'abf playoff', 'abf trial'],
  "Australian Women's Teams" => ["aust women's team",
    'aust womens team', 'aust women open team'],
  "Australian Women's Trials" => ["australian women's team selection",
    'australian womens team trial'],
  'Australian Youth' => ['aust youth'],
  'Australian Youth IMP Pairs' => ['aust youth butler',
    'australian youth butler'],
  'Australian Youth Tri Individual' => ['youth tri individual'],
  'Australian Youth Tri Pairs' => ['youth triathlon pairs'],
  'Balkan Championship' => ['balkan bridge ch', 
    'balkanbridge championship', 'balkan championships',
    'balkan bridge championship'],
  'Balkan Teams' => ['bolkan team championship',
    'bolkan teams championship', 'bolkan championship'],
  'Baltic Teams Cup' => ['baltic open teams cup'],
  'Baze Senior Knock-out' => ['baze senior ko', 'baze sr_ ko',
    'baze sr_ ko', 'baze sr ko'],
  'Bergen Grand Tournament' => ['bergen open',
    'bergen storturnering', 'bergen grand tournamnet',
    'bergen storturnering mester', 'bergen stor mester',
    'bst mester'],
  'Bermuda Bowl' => ['bermuda bow', 'bemruda bowl'],
  'Bermuda Triangle Cup' => ['bermuda triangle teams cup'],
  'BFAME Championship' => ['zone 4 bridge championship',
    'zone4 bridge championship', 'bfame chp', 'bfame championships'],
  'Bhabha Atomic Research Centre Open' => ['barc open'],
  'BKBT Teams' => ['bkbt match'],
  'Bobby Evans Seniors Teams' => ["bobby evans senior's teams",
    'bobby evans senior teams'],
  'Bolivian Open Teams' => ['bbolivariano open teams',
    'bolivarian tournament'],
  'Bologna Trophy' => ["trofeo citta' di bologna",
    "trofeo citta' bologna", "citta' di bologna", 
    "trofeo citta' bologna"],
  'Bonn Nations Cup' => ['nations cup germany', 'bonn cup'],
  'Brazilian Championship' => ['brazilian championships',
    'brazilian chapionship', 'open brazilian championship',
    'brazilian open championship', 'brasil champ', 
    'brazilian national championship', 'brasilian championship'],
  'Brazilian Teams' => ['brazilian team'],
  'Brazilian Seniors' => ['brazilian senior'],
  'Brazilian Women' => ['brazilian ladies'],
  'British Gold Cup' => ['gold cup', 'british gold'],
  'Buffett Cup' => ['buffet cup', 'bufett cup'],
  'Bulgarian Open Teams Gabi' => ["national bridge tournament \"gabi\"",
    "national tournament \"gabi\"", "bridge tournament \"gabi\"",
    'national tournament gabi'],
  Camrose => ['camrose trophy'],
  'Canadian National Teams Championship' => ['canadian national team'],
  'Canadian Open Teams Championship' => ['can open teams championship',
    'can open team championship', 'can_ champ open',
    'canadian champ open', 'canadian a tm', 'canadian tm a'],
  'Canadian Seniors Championship' => ['canadian senior tm'],
  'Canadian Women Championship' => ['can ladies bridge champs'],
  'Canadian Women Teams Championship' => ['can ladies team champ'],
  'Cavendish Teams' => ['cavendish tms', 'cavendish team'],
  'Central American Zonal Championships' => ["cacbf zonal ch'ships",
    'cacbf zonal championship', "cacbf zonal cha'ships",
    "cacbf zonal c'ships", 'cac final'],
  'Centre Island Teams' => ['ci teams'],
  "Chairman's Cup" => ['chairmans cup', "chariman's cup",
    "chairmans's cup", "swedish chairman's cup", 'chairmans cup'],
  "Champions' Cup" => ['champions cup', "champion's cup", 'chamions cup', 
    'champs cup', 'champion cup', "champion'scup", "champions'cup"],
  'Channel Trophy' => ['channel trpohy'],
  'Cherven Briag National Tournament' => [
    'national tournament cherven briag', 'cherven briag',
    'national tournament cgerven briag'],
  'Chilean Championship' => ['torneo nacional de chile'],
  'Chilean Cup' => ['copa aniversario'],
  'Chilean Team Trials' => ['chile open team trials',
    'chile team trials'],
  'China Elite Tournament' => ['china elite inivitational tournament',
    'china bridge elite tournament',
    'china bridge elite invitational tournament'],
  'China First League' => ['the national class a club league'],
  'Chinese Club Championship' => ['china bridge club championship',
    'club championships china'],
  'Chinese Taipei Trials' => ['chinese taipei trails',
    'chinese taipei team trial'],
  'Cliff Wake Challenge' => ['cliff wake invitational'],
  'Commonwealth Nations Bridge Championships' => [
    'commonwealth beidge championship', 
    'commonwealth nations bridge championship', 
    "commonwealth nation's bridge championship"],
  'Copenhagen Open Pairs' => ['km åben par'],
  'Czech Championship' => ['czech bridge championship',
    'czech bridge championships'],
  'Czech First League' => ['czech bridge league', 'czech bridge league',
    'czech premier league'],
  'Czech Team Championship' => ['czech team championships',
    'czech teams champ_'],
  'Czech First League' => ['czech 1st league', 'czech bridge league'],
  'Collegiate Bowl' => ['collegiate championship',
    'collegiate championships', 'collegiate champs'],
  'Computer World Championship' => ['computer bridge championship',
    'computer bridge', 'computer world bridge championships'],
  "d'Orsi" => ["d'orsi senior bowl", 'senior world cup',
    'seniors bowl', 'senior bowl'],
  'Danish Club Teams' => ['danish club team', 'dm klubhold',
    'dm i klubhold', 'dm i knubhold', 'dm i klub hold', 'danmark 1_ division',
    'danish 1st division', 'danmark 1_division', 'danish 1st division',
    'denmark 1_division'],
  'Danish Cup' => ['danmark pokal', 'danmark pokal', 'denmark pokal'],
  'Danish District Championship' => ['danish district teams championship'],
  'Danish First Division' => ['1_ division danmark',
    'denmark 1st division'],
  'Danish Junior Teams' => ['danish junior team championship', 
    'dansih junior team championship', 'junior dm'],
  'Danish Mixed Pairs' => ['dm mix par', 'danish championship mixed pairs',
    'danish mix-pair championship', 'danish mix pair championship',
    'danish national mix-pairs championship', 'danish mix pairs',
    'dm mix'],
  'Danish Pairs Championship' => ['danish open pairs championship', 
    'danish open pairs championships',
    'danish championship open pairs', 'open pairs - danish championship'],
  'Danish Teams Championship' => ['danish team champions',
    'danish team championships', 'danish team championship',
    'danish open team', 'danish open teams',
    'denmark team championship',
    'dm hold', 'dmi i klubhold', 'danish team', 'danish 1_division',
    'danish team chamionship'],
  'Danish Team Trials' => ['danish teams test', 'danish team test',
    'denmark team test'],
  'Danish Women Pairs' => ['ladies pairs - danish championship',
    'danish championship ladies pairs', 
    'danish champoinship ladies pairs'],
  'Delhi Gymkhana Club Open' => ['delhi gymkhana club open championship',
    'delhi gymkhana open championship',
    'delhi gymkhana open chmpionship'],
  'Division Nationale' => ['division natonale', 'division ntionale',
    'division natinale', 'divison nationale', 'french dn1', 'div_nat',
    'france div_ nat_ 1', 'div_ nat_', 'division nationale 1',
    'divisionnationale 1', 'nationale interclubs division 1', 'dn1',
    'nationale division 1', 'division nationale 1'],
  'Dongming Knock-out Teams' => ['dong ming knockout teams',
    'dong ming knockour teams', 'ding ming knockout teams'],
  'Dr. Heinz von Rotteck Pokal' => ['dr_-heinz-von-rotteck-pokal',
    'v_-rotteck-pokal'],
  'Dr. Rand Masters' => ['dr_ rand masters'],
  'Dutch Knock-Out Cup' => ['knock-out team cup netherlands',
    'knock out team cup netherlands'],
  'Dutch Meesterklasse' => ['dutch mk', 'dutch teams',
    'dutch club teams'],
  'Dutch Women' => ['ducth woman'],
  'Egyptian League' => ['egy_league', 'egy-league',
    'egyptian premier league'],
  'English Open Trials' => ['english open trial',
    'enlish open trials'],
  'English Premier League' => ['engish premier league',
    'english premier lge'],
  'English Senior Teams' => ['english seniors'],
  'English Senior Trials' => ['england senior trial',
    'england senior trials', 'english senior european trials',
    'englnd senior trials'],
  'English Women Trials' => ['english ladies trials'],
  'Estonian First League' => ['estonian a- league',
    'estonia a- league'],
  'Estonian Open Teams' => ['estonian team championship',
    'estonian team championships', 'estonian open teams'],
  'Estonian Open Trials' => ['estonian team trials'],
  'European Bridge Teams Championship' => ['european b.t.ch.',
    'european b_t_ch_', 'e_b_l_ team championships',
    'e_b_l_ teams championship', 'e_b_l_ team champioships', 
    'european bridge team championships', 'ebl team champs',
    'european bridge team champ',
    'europeqn teqm championships',
    'european team championships'],
  "European Champions' Cup" => ['european champs cup'],
  'European Junior Mixed Pairs' => ['eyjc mixed pairs'],
  'European Junior Teams Championship' => [
    'european junior teams championship',
    'euroepan junior teams championships'],
  'European Mixed Junior Pairs' => ['em pairs junior mix',
    'junior em mix'],
  'European Open Bridge Championship' => ['eobc',
    'euroepan open champ', 'european open champ', 'europe open champ'],
  'European Small Federation Games' => ['ebl small federation trophy',
    'ebl small federations trophy', 'games of small federations',
    'european small federations games', 'small federation games',
    'small federations games', 'small ffederations games',
    'small federation cup', 'european small feds games',
    'small f federations games', 'europian small federation games'],
  'European Women Championship' => ['eur women champ'],
  'European Youth Bridge Championship' => ['european youth championships'],
  'European Youth Bridge Pairs Championship' => [
    'european youth pairs'],
  'European Youth Bridge Teams Championship' => [
    'european youth bridge team champ'],
  'Faroese Teams' => ['faroese tc'],
  'Filbyter Cup' => ['filbyer cup'],
  'Finnish Pairs Championship' => ['finnish pair championship',
    'finnish pair championships', 'finnish pairs champs',
    'finnish pairs'],
  'Finnish Swiss Teams Championship' => [
    'finnish swiss imps championship',
    'finnish swiss imps championships',
    'finnish swiss-imps championships', 'finnish swiss-ims championships'],
  'Finnish Teams Championship' => ['finnish teams championships',
    'finnish teams', 'finnish team championships'],
  'Krommenie Nations Cup' => [
    'forbo krommenie teams',
    'forbo teams',
    'forbo-krommenie tournament',
    'forbo-krommenie international bridge event',
    'international forbo krommenie bridge event',
    'forbo-krommenie tourname'],
  'Forest Trophy' => ['forest bridge trophy'],
  'FOSS Grand Tournament' => ['foss grand tourney', 'foss grnad tourn',
    'foss grand tourament', 'foss grand tournement',
    'foss grand toruney', 'ftredriklstad and sarpsborg grand tournet',
    'foss grand torunament', 'foss grand torurnament',
    'foss grand torurney'],
  'Four Nations Cup' => ['4 nations cupn', '4 nations cup'],
  'French Cup' => ['coupe de france', 'de la coupe de france'],
  'French First Division' => [
    'division natinale open _ 4 d1',
    'division nationale', 
    'division nationale 1',
    'division nationale1_4',
    'division nationale1 _4',
    'division nationale open 1_ 4',
    'division nationale open 1 _4',
    'division nationale open 1 _ 4',
    'division nationale open_4 d1',
    'division nationale open_ 4 d1',
    'division nationale open _4 d1',
    'division nationale open _ 4 d1',
    'division nationale 1 open_4 d1', 
    'dno_4 d1',
    'dn0_4 division 1',
    'dn0_4 d1',
    'dno0_4 d1',
    'interclub d1',
    'interclubs d1', 
    'interclubs division1', 
    'interclub finale d1',
    'interclubs finale nationale division1',
    'nationale interclub d1'],
  'French Intercircle' => ['finale intercercle'],
  'French Senior Trials' => ['french seniors trials'],
  'FullBridge International Teams' => ['internacional equipos full bridge',
    'internacional full bridge'],
  'FX Securities Cup' => ['fx sec_ cup'],
  'Gabrial UI Bastaman Cup' => ['gabrial-ui cup',
    'gabrial ui cup'],
  'Geologi Cup' => ['geo cup'],
  'German Club Cup' => ['german cup', 'vereinspokal'],
  'German Open Teams' => ['offene team meisterschaft',
    'offene team meistershaft', 'german open team championships',
    'german open', 'german open team'],
  'German Team Championship' => ['deutsche teammeisterschaft'],
  'German Team Trophy' => ['german bridge team trophy',
    'dbv-pokal'],
  'German Women Pairs' => ['damen-paar'],
  'Golden Jubilee' => ['golden jubily'],
  'Grand National Teams' => ['gnt championship'],
  'Grand Prix of Poland' => ['grand prix polski', 'gp of poland',
    'grnd prix of poland', 'grand priix polski', 'gp polski',
    'grand prix plolski', 'grand prix team of poland'],
  'Grand Prix of Poland Pairs' => ['grand prix pairs of poland',
    'gran prix pairs of poland'],
  'Grand Prix of Prague' => ['gp prague', 'grand prix prague'],
  'Grand Prix of Wielkopolski' => ['gp wielkopolski',
    'grand prix of wielkopolski', 
    'grand prix of greater poland voivodeship'],
  'Grand Prix of Warsaw' => ['gp warszawy'],
  'Greek Central Regional Championship' => [
    'regional championship of central greece'],
  'Greek Open Teams' => ['greek open nationa team',
    'greek natioanal teams', 'greek open team championship', 
    'greek open team', 'grekk open national team', 'greek teams'],
  'Greek Open Trials' => ['greek trials', 'greek national team trials',
    'greek national trials'],
  "Gro's Supercup" => ["gro's super-cup", 'gros supercup'],
  'Guangdong Club Championship' => ['guang dong club championship',
    'guang dong club bridge championship'],
  'Guangdong Elite Tournament' => [
    'guangdong bridge club elites tournament',
    'guangdong bridge club  elites  tournament',
    'guangdong bridge club  elites tournament'],
  'Hellenic Mixed Pairs' => ['hellenik mixed pairs'],
  'Hellenic Team Championship' => ['hellenic teams championship'],
  'Hellenic Team Trials' => ['hellenic national team trials',
    'hellenic teams trials', 'helenic national team trials'],
  'Hellenic Women Team Trials' => ['hellenic ladies teams trials'],
  'HNA Open Teams' => ['hna cup', 'hna openteams', 'hna open team',
    "hna's hainan bridge tournament"],
  'Hong Kong Inter-City' => ['hong kong iner-city'],
  'Hungarian IMP Pairs' => ['hungarian imp'],
  'Hungarian Open Teams' => ['hungarian teams championships',
    'hungarian teams'],
  'Icelandair Open' => ['icelandari open'],
  'Icelandic Cup' => ['bikarkeppni bsí', 'icelandoc cup'],
  'Icelandic Teams' => ['icelandic teamhampionship',
    'icelandic team championship', 'icelandic team championships'],
  'Indian Open Trials' => ['indian open selection trials'],
  'Indian Senior Trials' => [
    'indian senior team selection triaals',
    'indian senior team selection trial',
    'indian senior team selection trials',
    'indian senior teams selection trials',
    'indian seniors selection trials',
    "indian seniors' team trials"],
  'Indian State Championship' => ['state level bridge championship',
    'state level bridge tournament',
    'state level bridgee championship'],
  'Indonesian Championship' => [
    'indonesia bridge championships',
    'indonesia national championships',
    'indonesian championships',
    'indonesian national championship'],
  'Indonesian Inter-Club Championship' => [
    'national indonesian championship',
    'national indonesian championship (inter-club'],
  'Indonesian Inter-Province Championship' => ['uji coba'],
  'Indonesian Junior League Online' => [
    'icba junior league online'],
  'Indonesian League' => ['indonesian bridge league',
    'indonesia bridge league', 'indonesian premier league',
    'indonesia premier league'],
  'Indonesian National Games' => ['indonesian games',
    'indonesian nasional games'],
  'Indonesian Open Teams' => ['indonesia open team'],
  'Indonesian Student Championship' => 
    ['indonesian student championships'],
  'Irish Invitational Pairs' => ['ireland invitational pairs',
    'irish invitational matchpoints'],
  'Irish Open Trials' => ['irish bridge union trials',
    'irish trials'],
  'Israel Juniors Championship' => ['israel juniors chamionship',
    'israel juniours'],
  'Israel Juniors Teams' => ['israel juniors team'],
  'Israel Open Pairs' => ['israel pairs', 'israel pairs champ'],
  'Israel Open Teams' => ['israeli open team', 'israel teams',
    'israel team of four cup', 'israel team cup',
    'israel team championship', 'israelairs champ_'],
  'Istanbul Winter Teams' => ['istanbul kis dortlu takimlar',
    'istanbul kis dortlu takim', 'istanbul winter champs',
    'istanbul kis'],
  'Italian Championship' => ['italian master'],
  'Italian Club Championship' => ['campionato italiano di societa',
    'campionato italiano di società', 'camp_ soc_ open',
    'campionato di società', 'camp.societ sportive',
    'campionati soc', 'campionato italiano intersocietario'],
  'Italian Mixed Teams' => ['italian mixed teams championships'],
  'Italian Team Championship' => ['camp.it.squadre',
    'camp.it. squadre'],
  'Italy Cup' => ['coppa italia'],
  "Jessheim New Year's Cup" => ['jessheim new years cup',
    'jesshiem new years cup', 'jessheim new years cup swiss teams'],
  'Jordan Spring Mixed Pairs' => ['jordan spring mix pairs'],
  'Junior Camrose' => ['juniior camrose'],
  'Kalani Trophy' => ['kalani bridge championship', 'kalani trohy',
    'kalani bridge champioship'],
  'Karnik-Vaidya Open' => ['karnik vaidya open',
    'karnik-vaidya annual'],
  "Kepri Governor's Cup" => ['kepri governor cup', 'kepri cup',
    'kepri governors cup', 'gubernur kepri cup', 'guvernor kepri cup',
    'governor kepri cup', 'gov bi cup', 'governor cup', 'bi cup',
    'kepri bridge championship', 'kepri international tournament',
    'kepri international bridge tournament'],
  'König Ludwig Cup' => ['koenig ludwig nationen cup'],
  'Krakow Spring' => ['krakowska wiosna'],
  'Lady Milne Trophy' => ['lady milne', 'lady mile'],
  'Lalit Mohanka Memorial' => ['lalit mohanka memorials'],
  'Lederer Memorial Trophy' => ['lederer memorial'],
  'Leszek Kwiatkowski Memorial Teams' => [
    'teams memorial of leszek kwiatkowski'],
  "Linda Stern Women's Teams" => ['linda stern womens teams'],
  'Lokmanya Jubilee' => ['lokmanya ss silver jubilee',
    'lokmanya ss siver jubliee', 'lokmanya golden jubilee'],
  'Lüleburgaz Liberation Cup' => ['luleburgaz kurtulus kupasi'],
  'Maccabi Games' => ['maccabi-games', 'europ_ maccabi games'],
  'Madeira Open' => ['madeira international open',
    'madeira teams', 'madeira open teams'],
  'Madeira Swiss Teams' => ['swiss teams madeira', 'madeira swiss'],
  'Marit Sveaas Tournament' => [
    'marit sveaas international bridge tournament',
    'marit sveaas international  bridge tournament'],
  'McConnell Cup' => ['mc connell'],
  'Mike Lawrence Exhibition' => ['m lawrence exhibiton'],
  'Milan Trophy' => ["trofeo citta' di milano", "citta' di milano"],
  "Missouri Braggin' Rights" => ['bragging rights'],
  'Mitra Vihar State Championship' => ['mitravihar centenary state level',
    'mitravihar club centenary state level',
    'mitravihar nasik centenary state level'],
  'Mohan Sicka Trophy' => ['mohan sicka'],
  'Mohanlal Bhartia Memorial Grand Prix' => [
    'bhartia memorial gran prix',
    'bhartia memorial grand prix',
    'mohanlal bharatia grand prix', 
    'mohanlal bharatia memorial grand prix',
    'mohanlal bharatiya memorial gran prix',
    'mohanlal bharia memorial',
    'mohanlal bharia memorial grand prix',
    'mohanlal bhartia grand prix',
    'mohanlal bhartia memorial gp',
    'mohanlal bhartiya grand prix',
    'mohanlal bhartiya memorial',
    'mohanlal bhartiya memorial grand prix',
    'mohanlal bhartiya memorial gran prix',
    'mohon lal bharatia grand pix',
    'mohnlal bhartia grand prix'],
  'Mondial de Deauville' => ['mondial deauville',
    'mondial barriere deauville', "barrière champion's cup",
    "barriere champion's cup", 'champion ship barriere',
    'barriere championship deauville', 'mondial de deauille',
    'montial de deauville', 'mondial barrière de deauville',
    'tournoi des champions barriere'],
  'NABC Senior Knock-Out Teams' => ['nabc senior ko teams'],
  'New South Wales State Teams' => ['nsw state teams'],
  'New Zealand Trials' => ['nz trials'],
  'NN Cup' => ['nn-cup'],
  'Nordic Championship' => ['nordic championships',
    'nordic bridge championship', 'nordic bridge championships'],
  'Nordic Junior Championship' => ['nordic championship for juniors',
    'nordic junior championships'],
  'Nordic Junior Pairs' => ['nordic junior pair championship',
    'open nordic junior pair', 'open nordic junior pairs'],
  'Nordic Junior Team Championship' => [
    'nordic junior team championships',
    'nordic junior teams championship',
    'nordic junior teams championships'],
  'Nordic Open Championship' => ['nordic championship open class'],
  'Nordic Team Championship' => ['nordic bridge team championship',
    'nordics', 'nordic team championships'],
  'Nordic Women Championship' => ['nordics (women)'],
  'Northern Greece Regional Championship' => [
    'n_ greece regional championship'],
  'Northern Territory Gold Teams' => ['nt gold teams'],
  'Northern Territory Gold Swiss Pairs' => ['nt gold swiss pairs',
    'nt gold swis pairs', 'nt gold swiss piars'],
  'Norwegian Club Cup' => ['sm norway', 'norway sm'],
  'Norwegian Club Teams' => ['norwegian clubteams championship',
    'norwegian ch ship teams', 'norwegian clubteams ch_ship',
    'norwegian clubteam championship', 'norw premier league',
    'nor club teams ch_ship', 'nor_club teams ch_ship',
    'norway km teams', 'nor club teams'],
  'Norwegian Corporate Championship' => ['norwegian corp_ championship'],
  'Norwegian Mixed Pairs' => ['nor mixed pairs ch_ship', 'nm mix pairs',
    'norwegian championship mix swiss pair'],
  'Norwegian Mixed Teams' => ['norwegian championship mix swiss teams'],
  'Norwegian Open Pairs' => ['nm monrad pairs', 'nm pairs',
    'nm swiss pairs', 'nm-pairs', 'norwegian pairs championship'],
  'Norwegian Open Teams' => ['nm open teams',
    'norwgian open teams championship'],
  'Norwegian Premier League' => ['norwegian prremier league',
    'nbf premier league'],
  'Norwegian Swiss Teams' => ['nm-monrad-lag', 'nor swiss teams',
    'norwegian swiss team championship', 'nm monrad lag', 
    'nm-monrad teams', 'nm-monrad-teams', 
    'norwegian championship swiss teams'],
  'Norwegian Team Trials' => ['nor team trials'],
  'Norwegian Teams' => ['norwegian teams ch_ship',
    'norwegian teams ch.ships', 'norewegian chship temas'],
  'NYSA Euroregion Nations Cup' => ['cup of euroregion nysa'],
  'Olona International Teams' => [
    'international olona bridge team'],
  'Olrud Easter Mixed Pairs' => ['olrud easter mixed'],
  'Olrud Easter Swiss Teams' => ['olrudpaasken monrad lag',
    'olrud paasken monrad lag', 'olrud easter tourn',
    'olrud swiss teams', 'olrud easter swiss event', 'olrud easter',
    'olrud easter swiss team', 'olrud easter tournament'],
  'Olrud Easter Teams' => ['olrudpaasken teams',
    'olrud estern teamevent', 'olrud estern team-event',
    'olrud easter team-event'],
  'Open Catalunya Preferent' => ['open catalunya equips',
    'open cataluña preferent', 'open preferent equips',
    'open preferent', 'open equips preferent'],
  'PRBA State Level Open' => ['prba open state level',
    'prba state level', 'prba statelevel'],
  'PYC Hindu Gymkhana Royale' => ['pyc royale'],
  'PYC Hindu Gymkhana PairsRoyale' => ['pyc pairs royale'],
  'Pakistan Day Bridge Championship' => ['pakistan day bridge'],
  'Pan Arab Inter-Club Championship' => ['pan arab championship',
    'pan arab inter_club', 'pan arab interclub',
    'pan arab inter-club', 'pan arab inter club', 'pan arab iner club'],
  'Patton de Monaco' => ["monaco's patton", 'patton international monaco',
    'patton international monte-carlo',
    'patton international monte carlo', 'patton monte carlo'],
  'Pärnu Summer Invitational Pairs' => [
    'pärnu summer_ invitational pairs_', 
    'parnu summer tournament_ invitatoinal pairs',
    'pärnu summer tournament_ invitational pairs_'],
  'Petit Grand Prix van Driene' => ['petit grand prix',
    'grand prix van driene'],
  'Plock District League' => ['plockiej ligi okregowej'],
  'Poddar National Masters' => ['poddar national master',
    'poddar nationals masters', 'podder national masters',
    'podder nationals masters'],
  'Polish BAM Teams' => ['bam team championship of poland'],
  'Polish Boys Championship' => ['polish championship boys'],
  'Polish Girls Championship' => ['polish championship girls'],
  'Polish IMP Pairs' => ['butler polish championship',
    'butler (imp) polish pairs championship'],
  'Polish Individual Championship' => [
    'individual championship of poland'],
  'Polish Mixed Teams' => ['Mistrzostwa Polski Teamów Mikst'],
  'Polish Open Teams' => ['polish open tems'],
  'Polish Open Trials' => ['polish trials open'],
  'Polish Pairs' => ['pairs championship od poland',
    'pairs championship of poland', 'open pairs championship of poland'],
  'Polish Premier League' => ['polish premiere league',
    'polish premier leuge', 'polish first division', 
    'polish 1st division', 'i liga'],
  'Polish Second League' => ['polish 2 league'],
  'Polish Third League' => ['polish league: division 3'],
  'Polish Teams' => ['mistrzostwa polski teamów',
    'teams championship of poland', 'championship of poland',
    'team championship of poland', 'champioship of poland'],
  'Polish Top Individual' => ['top indyvidual'],
  'Polish Women Trials' => ['polish trials women',
    'polish trials ladies'],
  'Polish Youngster Teams' => ['kadry juniorów m³odszych'],
  'Pomerania Cup' => ['rozgrywek pucharowych pwzbs'],
  'Portuguese Grand Prix' => ['portuguese grad prix',
    'portugal grand prix', 'portugal grand peix'],
  'Portuguese Open Teams' => ['equipas open pt', 'open teams pt',
    'portuguese cneo', 'portuguese teams'],
  'Portuguese Open Trials' => ['portuguese trials',
    'portuguese selection trials'],
  'Portuguese Northern Regional Open Teams' => [
    'northern regional open teams',
    'northern regional teams open'],
  'Poznan Mixed Pairs' => ['otwarte mistrzostwa poznania mixt'],
  'Prince Takamatsu Cup' => ['prince takamatsu memorial cup'],
  'R N Bagla Memorial Pairs' => ['rn bagla menorial pairs'],
  'R Ratnam Memorial' => ['r ratnam memoral championship'],
  'Riga Invites to Jurmala' => ['riga invites', 'latvia invites'],
  'Rio de Janeiro Championship' => ['rio de janeiro state final'],
  'Romanian League' => ['cn echipe', 'c_n_ echipe', 'cn ecgipe',
    'divizia a', 'romanian national teams div a', 
    'romanian national division', 'romanian national teams- div a', 
    'romanian teams-a division', 'romanian teams- a division'],
  'Romanian Open Teams' => ['romanian national team championships',
    'romanian national teams championships',
    'romanian teams'],
  'Romanian Second League' => ['cn echipe div b',
    'cn ecgipe div b'],
  'Rondane Pairs Cup' => ['rondanecupen swiss pairs'],
  'Rondane Teams Cup' => ['rondane cup teams', 'rondanecupen teams',
    'rondanecupen swiss teams'],
  'Rosfjord Swiss Teams' => ['rosfjord monrad team',
    'rosfjord monrad teams'],
  'Rottneros Nordic Cup' => ['rottneros cup'],
  'Ruia Gold Cup' => ['ruia gold', 'ruia gols'],
  'Ruia Silver Cup' => ['ruia silver'],
  'Ruter 7 Open' => ['ruter7 elitetournament'],
  'Salo Midsummer Juniors' => ['midsummer juniors'],
  'Samadhan Summer League' => ['samadhan bridge league'],
  'Sao Paulo State Championship' => ['s o paulo cup', 'sao paulo champ',
    'sao paulo championship', 'sao paulo champ', 'sao paulo cup',
    'sao paulo state cup', 'são paulo cup', 'sap paulo state championship',
    'são paulo state championship', 'sp champ', 'sao paulo state'],
  'Sarundajang Cup' => ['the sarundajang cup'],
  'Scottish Cup' => ['scot cup', 'scot cuo', 'scottish cup plate'],
  'Scottish National League' => ['scotland national league'],
  'Senior Camrose' => ['seniors camrose'],
  'Serbian Cup' => ['cup of serbia', 'cup srbije', 'kup srbije'],
  'Serbian Premier League' => ['serbian premier leaugue',
    'serbian league'],
  'Serbian Team Championship' => ['serbia teams championship',
    'serbian tam championship', 'serbian teams championship',
    'serbianteam championship', 'serbian closed team championship'],
  'Shenhua Cup' => ['shen hua cup'],
  'Slava Cup' => ['cup slava', 'salava cup'],
  'Slovakian Open Teams' => ['slovakia open teams'],
  'South African Championship' => ['south african nationals',
    'south african championships'],
  'South African Teams' => ['south african chaionships'],
  'South American Open Teams' => ['southamerican open championship',
    'south american championhip', 'south american champioship', 
    'south american bridge championships', 'south american championship'],
  'South American Seniors Teams' => ['clasificacion sudamericano seniors'],
  'South American Women Teams' => ['clasificatoria damas equipos',
    'clasificatoria equipos damas', 'sudamericano damas'],
  'South American Trials' => ['clasificatoria sudamericano',
    'clasificatorias sudamericano', 'south americal trials'],
  'South American Senior Trials' => ['seleccion sudamericano senior'],
  'South Zone Championship' => ['southzone championship',
    'souhzone championship'],
  'Southeast Asian Games' => ['sea games', 'south east asian games'],
  'Spanish Central Zone Teams' => ['zonal centro equipos',
    'equipos zonal centro'],
  'Spanish Open Trials' => ['open seleccion mundial'],
  'Spanish Senior Trials' => ['prueba de seleccion equipos senior'],
  'Spanish Teams Championship' => ['campeonato de españa por equipos',
    'campeonato espan', 'campeonato espanaonda', 'camp esp'],
  'SPBF Championship' => ['zone 7 championship', 'zone 7 championships'],
  'Spring Fours' => ['spring 4s', 'spring foursomes', 'schapirosfs'],
  'Spring Nationals' => ['spring nat', 'spring national', 'spring nats',
    'sping national', 'spring nat opens'],
  'Staszic Pairs Cup' => ['otp puchar grodu staszica'],
  "Sternberg Women's BAM Teams" => ['marsha may sternberg bam'],
  'Stockholm Teams' => ['stockholm teams cs'],
  'Sudamericano Transnacional' => ['sudamerican transnacional',
    'sudamerico transnacional'],
  'Summer Monsoon League' => ['summer monsoon', 'summer monsoon leahue'],
  'Summer Nationals' => ['summer national'],
  'Swedish District Championship' => ['swedish championships distrcit',
    'sweden distric', 'swedish districts', 'swedish disttrict',
    'swedis district', 'swesish district', 'sweden district',
    'swedish championship district', 'swesish champsionship district',
    'swedish championships district', 'swedish district championships',
    'swedish championship cistrict', 'swedish district',
    'swedish champsionship district', 'swdish district'],
  'Swedish Juniors Championship' => ['swedish juniors cs'],
  'Swedish Juniors Teams' => ['swedish juniors teams cs',
    'swedish juniors teams cs', 'swedish junior teams'],
  'Swedish Open Pairs' => ['swedish open pair', 'swedish pair'],
  'Swedish Open Teams' => ['swedish teams'],
  'Swedish Open Trials' => ['swedish trial'],
  'Swedish Premier League' => ['swedish elite series',
    'swedish elitserien'],
  'Swiss Championship' => ['champion suisse', 'championnat suisse',
    'swiss championshi', 'swiss championshio'],
  'Swiss Club Championship' => ['swisss interclubs', 'swiss interclubs',
    'swiss interclub championship', 'swiss interclub'],
  'Swiss Cup' => ['coupe suisse', 'swiss open cup', 'swiss open',
    'swiss cuo', 'switzerland open cup'],
  'Swiss Open Championship' => ['swiss open championship'],
  'Swiss Team Championship' => ['swiss team champiomshio'],
  'Taiwan University Cup' => ['taiwan university championship'],
  'Taiwan University Cup Teachers' => [
    "taiwan university cup teacher's section"],
  'Taiwanese Open Trials' => ['taiwanese trials'],
  'Taiwanese Senior Trials' => ['ctcba senior team trial'],
  'Taiwanese Teams' => ['taiwanese teal'],
  'TATA Open' => ['tata opren', 'tata sports', 'ttat open'],
  'Teltscher Trophy' => ['teltcher trophy'],
  'TGR Auction Pairs' => ["tgr's auction pairs",
    'tgrs auction pair', 'tgrs auction pairs'],
  'TGR Auction Teams' => ['tgrs auction teams'],
  'TGR Super League' => ["tgr's super league", "tgr's super legue",
    'tgrs league', 'tgrs 2nd auction pairs', 'tgrs super league',
    "tgr's league", "trg's super league"],
  'The Hague Bridge Experience' => ['the hague bride experience',
    'teh hague bridge experience'],
  'Thrace Club Teams' => ['thrace region clubs team championship',
    'türk trakya bölge kulüpler þampýyonasi ekýbý', 'trachean club teams'],
  'Thrace Cup League' => ['trakya kulupler ligi'],
  'Tianjin Binhai Cup' => ['tianjin bin hai cup'],
  'Tolani Gold Trophy' => ['dr_tolani gold troph',
    'tolani summer nationals gold', 'tolani summer nationald gold',
    'tolani gold summer nationals', 'tolani gold summar nationals',
    'tolani gold summer national', 'dr_tolanigoldcup',
    'tolani gold summer', 'dr_tolani gold cup summer nationals',
    'dr_tolani gold summer nationals', 'tolani gold summer nationals',
    'tolani gols summer nationals'],
  'Tolani Grand Prix' => ['tolani gp', 'tolani grand pix'],
  'Tolani Silver Cup' => ['dr tolani summer nationals silver',
    'tolani silver trophy',
    'dr_tolani open summer nationals silver',
    'dr_tolani silver cup summer national',
    'dr_tolani sliver cup summer nationals'],
  'Trondheim Cup' => ['trondheim cup swiss teams'],
  'Turkish Club Championship' => ['türkýye kulüplerarasi þampýyonasi',
    'türkýye klüpler arasi brýç þampýyonasi',
    'turkish club teams championship',
    'turkish inter club championships'],
  'Turkish East & South-East Teams' => [
    'turkish clubs championship east & south east el'],
  'Turkish East Mediterranean Teams' => [
    'turkish east mediterranean',
    'turkish east mediterranean club teams',
    'turkish eastern mediterranean club', 
    'turkish eastern mediterranean club teams'],
  'Turkish Mixed Teams Championship' => ['turkey mix teams ch'],
  'Turkish Open Teams Championship' => [
    'turkiye acik takimlar sampiyonasi',
    'turkish national open teams'],
  'Turkish Open Trials' => ['turkish open team selection',
    'turkish open team trials'],
  'Turkish Swiss Mixed Teams' => ['turkey swiss mixed teams'],
  'Turkish Teams Championship' => ['turkiye bric takimlar sampiyonasi'],
  'Turkish Winter Championship' => ['turkiye kis takimlar sampiyonasi',
    'turkish winter chanpionship'],
  'Turkish Winter Open Teams' => ['turkiye kis acik takimlar sampiyonasi'],
  'Turkish Winter Women Teams' => [
    'turkish winter woman team championship'],
  'Turkish Women Teams' => ['türkish ladies teams'],
  'United States Juniors Bridge Championship' => [
    'jusbc rona'],
  'United States Women Bridge Championship' => [
    "us women's bridge championship", "us women's bridge championhip",
    "united states women's bridge championship"],
  'US International Team Trials' => ['us itt'],
  'US Junior Trials' => ['usbf junior trials'],
  'US Senior Trials' => ['usbf senior trials', 'usbf seniors trials',
    'usa seniors trials', 'usa seniors team trials'],
  'US Seniors' => ['us senior'],
  'US Women' => ['us womens championships'],
  'US Youngsters' => ['u-21 us'],
  'USBF Challenge Match' => ['usbf jr/pro charity challenge match'],
  Vanderbilt => ['vanderbilt teams', 'vanderbilt ko teams'],
  'Varna Titan Teams' => ['teams titan'],
  'Venezuela Swiss Pairs' => ['venezuela parejas suizas'],
  'Venice Cup' => ['<venive <cup'],
  'Vest-Agder Regional Team Championship' => [
    'regional chship vest-agder', 'regional champship vest-agder',
    'regional chship vest-agder', 'vest-agder km lag'],
  'Victorian Open Teams' => ['victorian opean teams', 'victorian open',
    "'victorian open", 'victorian open team', 'victorian opean',
    'victoian open', 'victorian team'],
  'Victorian Pennant' => ['vic pennant'],
  'Victorian Open Teams Playoff' => ['victorian playoff'],
  'Victorian Youth' => ['victorian youth'],
  'Vinoble Cup' => ['vinoble open'],
  Wagar => ['wagar teams', "wagar women's", "wagar women's ko",
    'wagar womens ko'],
  'Warsaw Online Teams' => ['enthusiast bridge zlot', 
    'warsaw bboers champ', 'warsaw bboers championship'],
  'Watermark Bridge Classic' => ['watermark teams'],
  'Wellingdon Swiss Pairs' => ['wsc open swiss pairs championship',
    'wsc open swisspairs championship', 'wsc swiss open pairs'],
  'Western Mediterranean Club Teams' => [
    'western mediterranean clubs team championship'],
  'White House Juniors' => ['whiteouse juniors', 'the white hous juniors',
    'qhite house juniors'],
  'White House Top 12' => ['modalfa top 12', 'witte huis top 12'],
  'White House Top 16' => ['white house int. teams top 16',
    'white house int_ teams top 16',
    'white house international top 16 teams'],
  'Top Circuit' => ['melchemie top circuit',
    'ing bank top circuit', 'witte huis topcircuit'],
  'Winter Open Teams' => ['winter teams', 'winter team'],
  'World Juniors Championship' => ['world juniors championships'],
  'World Masters Individual' => ['masters individual',
    'world masters'],
  'World Open Pairs' => ['world pairs championship'],
  'World Seniors Championships' => ['world senior championship'],
  'World Transnational Teams' => ['world transnational open teams'],
  'World University Championship' => [
    'world university bridge championship',
    'world university bridge championships',
    'univ_ world champs'],
  'World Women Elite Tournament' => ['women elite tournament',
    "women's elite tournament",
    "women's bridge grand prix"],
  'World Youth Championship' => ['world youth championships'],
  'World Youth Congress' => ['youth world bridge congress',
    'worlf youth bridge congress', 'workd youth bridge congress',
    'world youht congress'],
  'World Youth Teams Championship' => ['world youth team championships',
    'world youth teams'],
  'Yeh Bros Cup' => ['yehbros cup'],
  'Young Chelsea Knock-out' => ['yc ko', 'young chelsea ko',
    'young chelsea knockout'],
  'Zulawski Cup' => ['zulawski teams']
);

my @SINGLE_WORDS = qw(
  Bundesliga
  Camrose Cavendish
  Reisinger
  Rosenblum
  Spingold
  Vadsøturneringen Vanderbilt
  Wagar
);

my %SINGLE_TYPOS =
(
  'APBF Championships' => ['pabfc', 'pabf', 'pabfs'],
  'Argentinian Open Teams' => ['cnia'],
  'ASEAN Club Championship' => ['abcc'],
  'Australian National Open Teams' => ['anot'],
  'Bermuda Bowl' => ['bb'],
  'Bobby Evans Seniors Teams' => ['best'],
  'Brazilian Championship' => ['brasilchamp'],
  "Buffett Cup" => ['buffett', 'buffet'],
  Camrose => ['camroae', 'ccmrose'],
  'Canadian Bridge Championship' => ['cbc'],
  'Canadian National Teams Championship' => ['cntc'],
  'Canadian Seniors Teams Championship' => ['cstc', 'cnst'],
  'Canadian Women Teams Championship' => ['cwtc'],
  Cavendish => ['cavendiish', 'caavendish', 'cavemdish', 'cavendiosh',
    'cavendsh', 'cavvendish', 'avendish', 'cav'],
  'Collegiate Bowl' => ['collegiate', 'collegiates'],
  'Commonwealth Nations Bridge Championships' => ['cnbc'],
  'Copenhagen Invitational Pairs' => ['cbi'],
  'Danish Championship' => ['dm'],
  'Division Nationale' => ['dn'],
  "d'Orsi" => ['sb', 'dosb'],
  'Dutch Meesterklasse' => ['meesterklasse'],
  'European Bridge Teams Championship' => ['ebtc'],
  "European Champions' Cup" => ['ecc'],
  'European Open Bridge Championship' => ['eoc'],
  'European Small Federation Games' => ['esfg', 'sfc'],
  'European University Bridge Championship' => ['eubc', 'eucb', 'euc'],
  'European Winter Games' => ['ewg'],
  'European Youth Bridge Championship' => ['eybc'],
  'European Youth Bridge Pairs Championship' => ['eybpc', 'eypc'],
  'European Youth Bridge Teams Championship' => ['eytc', 'jem'],
  'FOSS Grand Tournament' => ['foss'],
  'German Team Championship' => ['teammeisterschaft'],
  'Gianarrigo Rona Trophy' => ['rona'],
  'Grand National Open Teams' => ['gnot'],
  'Grand National Teams' => ['gnt'],
  'Grand Prix of Poland' => ['gpp', 'gppp'],
  "Gro's Supercup" => ['grocup'],
  'Icelandair Open' => ['icelandair'],
  'Junior Camrose' => ['juniorcamrose', 'juniorcmrose'],
  'Kalani Trophy' => ['kalani'],
  "Kepri Governor's Cup" => ['kepricup'],
  'Lederer Memorial Trophy' => ['lederer', 'ledered'],
  "Linda Stern Women's Teams" => ['lswt'],
  'Maccabi Games' => ['maccabiah'],
  'McConnell Cup' => ['mcconnell'],
  'North American Bridge Championship' => ['nabc'],
  'NTU Cup' => ['ntucup'],
  'Paris Youth Open Teams' => ['ypob'],
  'Peggy Bayer' => ['peggybayer'],
  'Portuguese Open Teams' => ['cneo'],
  Reisinger => ['reisiger', 'resisinger'],
  'Ruia Trophy' => ['ruia'],
  'Scottish Cup' => ['scottishcupplate'],
  'South American Open Teams' => ['sabc'],
  'Southeast Asian Games' => ['seagames'],
  'Swedish Elite Series' => ['elitserien'],
  'Takamatsu Cup' => ['takamatsu'],
  'Teltscher Trophy' => ['teltschertrophy', 'teltscher', 'telschertrophy'],
  'Tolani Grand Prix' => ['tolanigrandprix'],
  'Top Circuit' => ['topcircuit'],
  'Transnational Open Teams' => ['tnt', 'tnot'],
  'United States Juniors Bridge Championship' => ['usjbc', 'jusbc'],
  'United States Juniors Training' => ['jtp'],
  'United States Seniors Bridge Championship' => ['ussbc'],
  'United States Women Bridge Championship' => ['uswbc', 'uswbf', 'uswc',
    'us womens championships'],
  Vanderbilt => ['vanderbuilt', 'vanderebilt', 'vandebilt', 'vandy'],
  'Venice Cup' => ['vc', 'venice'],
  'Victor Champion Cup' => ['vcc'],
  'Victorian Pennant' => ['pennant'],
  'Vilnius Club Pairs' => ['vbk'],
  'White House Juniors' => ['whj'],
  'World Transnational Mixed Teams' => ['wtmt'],
  'World Transnational Open Teams' => ['wtot'],
  'World University Championship' => ['wuc'],
  'World Youth Bridge Team Championship' => ['wybtc'],
  'World Youth Open Bridge Championship' => ['wyobc', 'wboyc'],
  'World Youth Teams Championship' => ['wytc', 'world youth teams'],
  'Young Chelsea Knock-out' => ['ycko'],
  'Zimmermann Cup' => ['zc']
);


sub set_hashes
{
  my ($method, $key) = @_;

  $method->(\@MULTI_WORDS, \%MULTI_TYPOS,
    \@SINGLE_WORDS, \%SINGLE_TYPOS, $key);
}

1;
