#!perl

use strict;
use warnings;
use v5.10;
use utf8;
use open ':std', ':encoding(UTF-8)';

package Tags::Tname;

our @ISA = qw(Exporter);
our @EXPORT = qw(set_hashes);

use lib '.';
use TeamBBO;

my @MULTI_WORDS =
(
  '0-1500 Spingold',
  'AfBF Zone 8 Championships',
  'ABPF Championships',
  'African Zonal Championship',
  'All-China Games',
  'All India Corporate Invitational',
  'All India Corporate Invitational Pairs',
  'All India UTI Bank Masters Championship',
  'Altman Swiss Pairs',
  'Anatolian Club Qualifying',
  'Anatolian Fall Teams',
  'Anatolian Open Teams',
  'Anatolian Spring Teams',
  'Antonio Chong Cup',
  'Aoda Cup',
  'ArboNed Team Cup',
  'Argentinian Copa Republica',
  'Argentinian Flags Day Championship',
  'Argentinian Mixed Teams',
  'Argentinian Open Teams',
  'Argentinian Seniors Teams',
  'Australian Open Teams',
  'Australian Open Trials',
  'Australian Seniors Pairs',
  'Australian Seniors Teams',
  'Australian Seniors Trials',
  'Australian Spring Open Teams',
  'Australian Spring Seniors Teams',
  "Australian Spring Women's Teams",
  "Australian Women's Teams",
  'Australian Youth',
  'ARIS Cup',
  'ASEAN Club Championship',
  'Asia Cup',
  'Asian University Championship',
  'Australian Grand National Open Teams',
  'Australian National Open Teams',
  'Australian Trials',
  'Australian Youth IMP Pairs',
  'Balikcioglu Teams Championship',
  'Balkan Championship',
  'Balkan Teams',
  'Baltic Bowl',
  'Baltic Cup',
  'Baltic Teams Cup',
  'Balkan Championship',
  'Bastaman Cup',
  'Baze Senior Knock-out',
  'Belgian Open Teams',
  'Bergen Grand Tournament',
  'Bermuda Bowl',
  'Bermuda Triangle Cup',
  'Beskids Slam',
  'BFAME Championship',
  'Bhabha Atomic Research Centre Open',
  'Biarritz Hiver',
  'BKBT Teams',
  'Bobby Evans Seniors Teams',
  'Bolivian Open Teams',
  'Bologna Trophy',
  'Brazilian Championship',
  'Brazilian Open',
  'Brazilian Seniors',
  'Brazilian Teams',
  'Brazilian Women',
  'British Gold Cup',
  'British Premier League',
  'Buffett Cup',
  'Bulgarian Open Teams Gabi',
  'Canadian Bridge Championship',
  'Canadian National Teams Championship',
  'Canadian Open Teams Championship',
  'Canadian Seniors Teams Championship',
  'Canadian Women Championship',
  'Canadian Women Teams Championship',
  'Carrousel Cup',
  'Cavendish Pairs',
  'Cavendish Teams',
  'Central American Zonal Championships',
  'Centre Island Teams',
  "Champions' Cup",
  'Channel Trophy',
  'Cherven Briag National Tournament',
  'Chilean Championship',
  'Chilean Cup',
  'Chilean Pairs',
  'China Elite Tournament',
  'China Friend City Senior Team Tournament',
  'China First League',
  'China Hosts Europe in Rome',
  'Chung Hua Cup',
  'Cliff Wake Challenge',
  'Codan Cup',
  'Collegiate Bowl',
  'Commonwealth Nations Bridge Championships',
  'Computer World Championship',
  'Copa de Plata',
  'Copa de Oro',
  'Copa Zanalda River Plate',
  'Copenhagen Invitational Pairs',
  'Copenhagen Open Pairs',
  'Coppie Viareggio',
  'Corn Cairdis',
  'Cross Strait Invitational',
  'Czech Championship',
  'Czech Team Championship',
  'Czech First League',
  "d'Orsi",
  'Damiani Cup',
  'Danish Club Teams',
  'Danish Cup',
  'Danish Championship',
  'Danish District Championship',
  'Danish Junior Teams',
  'Danish Mixed Pairs',
  'Danish Open',
  'Danish Pairs Championship',
  'Danish Teams Championship',
  'Danish Team Trials',
  'Danish Women Pairs',
  'Dongming Knock-out Teams',
  'Dr. Heinz von Rotteck Pokal',
  'Dr. Rand Masters',
  'Dutch Meesterklasse',
  'Dutch Women',
  'Egyptian League',
  'Estonian First League',
  'European Bridge Teams Championship',
  'European Junior Mixed Pairs',
  'European Junior Teams Championship',
  'European Mixed Junior Pairs',
  'European Open Bridge Championship',
  "European Champions' Cup",
  'European Championship',
  'European Small Federation Games',
  'European University Bridge Championship',
  'European Winter Games',
  'European Women Championship',
  'European Youth Bridge Championship',
  'European Youth Bridge Pairs Championship',
  'European Youth Bridge Teams Championship',
  'EUSA Games',
  'Farmen Invitational',
  'Faroese Teams',
  'Fatih Kiral Cup',
  'Filbyter Cup',
  'Finnish Cup',
  'Finnish Easter Teams',
  'Finnish Pairs Championship',
  'Finnish Teams Championship',
  'Finnish Swiss Teams Championship',
  'Forbo Krommenie Teams',
  'Forbo Nations Cup',
  'Forest Trophy',
  'Fortuna Cup',
  'FOSS Grand Tournament',
  'FOSS-Tren',
  'French Cup',
  'French Intercircle',
  'FullBridge International Teams',
  'Full Tilt Irish Bridge Masters',
  'Garden Cities',
  'Gardermoen Airport Hotel Cup',
  'Gelibolu Peace Cup',
  'German Club Cup',
  'German Open Teams',
  'German Team Championship',
  'German Team Trophy',
  'German Women Pairs',
  'GHTD Cup',
  'Goksu-Yalikavak Pairs',
  'Golden Jubilee',
  'Grand Prix of Poland',
  'Grand Prix of Poland Pairs',
  'Grand Prix of Prague',
  'Grand Prix of Warsaw',
  'Grand Prix of Wielkopolski',
  'Greek Central Regional Championship',
  'Greek Open Teams',
  "Gro's Supercup",
  'Guangdong Club Championship',
  'Haikou Fitness Day',
  'Hainan Air Cup',
  'Haskovski Mineralni Bani',
  'Hecht Cup',
  'Hellenic Mixed Pairs',
  'Hellenic Team Trials',
  'Hellenic Team Championship',
  'Higson Cup',
  'High-Tech Zone Workers Invitational',
  'Hungarian IMP Pairs',
  'HNA Cup',
  'Hong Kong Inter-City',
  'Icelandair Open',
  'Icelandair Team Championship',
  'Icelandic Cup',
  'Icelandic Teams',
  'IMSA Cup',
  'IMSA Elite Mind Games',
  'Indonesian Inter-Province Championship',
  'Indonesian League',
  'Indonesian National Games',
  'Indonesian Student Championship',
  'Israel Juniors Championship',
  'Israel Juniors Pairs',
  'Israel Juniors Teams',
  'Israel Open Pairs',
  'Israel Open Teams',
  'Israel Schools',
  'INEA Cup',
  'IOC Grand Prix',
  'Istanbul Winter Teams',
  'Italian Championship',
  'Italian Club Championship',
  'Italian Team Championship',
  'Italy Cup',
  'Japanese District KO Teams',
  "Jessheim New Year's Cup",
  'Jordan Spring Mixed Pairs',
  'Jordan Spring Tournament',
  'Jordan Spring Women',
  'JPD Cup',
  'Junior Camrose',
  'Kalani Trophy',
  'Karnik-Vaidya Open',
  "Kepri Governor's Cup",
  'Kings and Queens Blaine Howe Teams',
  'König Ludwig Cup',
  'Krakow Spring',
  'Lady Milne Trophy',
  'Lederer Memorial Trophy',
  "Linda Stern Women's Teams",
  'Lokmanya Jubilee',
  'Lüleburgaz Liberation Cup',
  'Maccabi Games',
  'Madeira Swiss Teams',
  'McConnell Cup',
  'Milan Trophy',
  "Missouri Braggin' Rights",
  'Mitra Vihar State Championship',
  'Mohan Sicka Trophy',
  'Mondi Cup',
  'Mondial de Deauville',
  'Mountain Sea Cup',
  'MTP Cup',
  'Nations Cup',
  'NN Cup',
  'Nordic Championship',
  'Nordic Cup',
  'Nordic Junior Championship',
  'Nordic Junior Pairs',
  'Nordic Junior Team Championship',
  'Nordic Open Championship',
  'Nordic Race',
  'Nordic Swiss Teams',
  'Nordic Team Championship',
  'Nordic Women Championship',
  'North American Bridge Championship',
  'Northern Greece Regional Championship',
  'Northern Territory Gold Teams',
  'Northern Territory Gold Swiss Pairs',
  'Norwegian Club Teams',
  'Norwegian Club Cup',
  'Norwegian Corporate Championship',
  'Norwegian District Championship',
  'Norwegian Mixed Pairs',
  'Norwegian Mixed Teams',
  'Norwegian Open Pairs',
  'Norwegian Open Teams',
  'Norwegian Swiss Teams',
  'Norwegian Teams',
  'NTU Cup',
  'Olrud Easter Mixed Pairs',
  'Olrud Easter Pairs',
  'Olrud Easter Swiss Teams',
  'Olrud Easter Teams',
  'Open Catalunya Preferent',
  'Pahlawan Cup',
  'Pakistan Day Bridge Championship',
  'Palace Cup',
  'Pan Arab Inter-Club Championship',
  'Paris Youth Open Teams',
  'Park Hotell Swiss Teams',
  'Patton de Monaco',
  'Pärnu Summer Invitational Pairs',
  'Pärnu Summer Open Teams',
  'Peggy Bayer',
  'Pesta Sukan',
  'Petit Grand Prix van Driene',
  "Pigg's Peak All Africa",
  'Plock District League',
  'Poddar National Masters',
  'Polish BAM Teams',
  'Polish Boys Championship',
  'Polish Girls Championship',
  'Polish Individual Championship',
  'Polish Mixed Teams',
  'Polish Open Teams',
  'Polish Pairs',
  'Polish IMP Pairs',
  'Polish Premier League',
  'Polish Teams',
  'Polish Youngster Teams',
  'Poznan Mixed Pairs',
  'Pomerania Cup',
  'Portuguese Open Teams',
  'PRBA State Level Open',
  'Prince Henrik Trophy',
  'Prince Takamatsu Cup',
  'Puutalo Open',
  'PYC Hindu Gymkhana Royale',
  'PYC Hindu Gymkhana PairsRoyale',
  'Rand Cup',
  'Rector University of Brawijaya Cup',
  'Rona Cup',
  'Gianarrigo Rona Trophy',
  'Riga Invites to Jurmala',
  'Riau Governor Cup',
  'Roberto Taunay Cup',
  'Romanian League',
  'Rondane Cup',
  'Rosfjord Swiss Teams',
  'Rottneros Nordic Cup',
  'Ruia Gold Cup',
  'Ruia Silver Cup',
  'Ruia Trophy',
  'Ruter 7 Open',
  'S:t Erik Championship Series',
  'Samadhan Summer League',
  'Sao Paulo State Championship',
  'Sarundajang Cup',
  'Scottish Cup',
  'Semen Padang Cup',
  'Senior Camrose',
  'Serbian Cup',
  'Serbian Premier League',
  'Serbian Team Championship',
  'Shenhua Cup',
  'Shenyang Spring',
  'Shield of Thoisy',
  'Sigismund Bell Krakow',
  'Silver Jubilee',
  'Slava Cup',
  'Smirnov Cup',
  'Solomon Teams',
  'South African Championship',
  'South African Teams',
  'South American Bridge Championships',
  'South American Seniors Teams',
  'South American Women Teams',
  'South American Trials',
  'South Zone Championship',
  'Southeast Asian Games',
  'Spanish Central Zone Teams',
  'Spanish Open Trials',
  'Spanish Teams Championship',
  'SPBF Championship',
  'Spring Fours',
  'Spring of Cracow',
  'Spring Nationals',
  'Star Wars',
  'Staszic Pairs Cup',
  'Stena Line Cup',
  'Stern-Cornell Trophy',
  'Stockholm Teams',
  'Sudamericano Transnacional',
  'Summer Monsoon League',
  'Summer Nationals',
  'Suomen Cup',
  'Swedish District Championship',
  'Swedish Elite Series',
  'Swedish Juniors Championship',
  'Swedish Juniors Teams',
  'Swiss Championship',
  'Swiss Club Championship',
  'Swiss Cup',
  'Swiss Open Championship',
  'Swiss Team Championship',
  'Taça Rui Pinto',
  'Takamatsu Cup',
  'Taiwan University Cup',
  'Taiwan University Cup Teachers',
  'Taiwanese Teams',
  'TATA Open',
  'Teltscher Trophy',
  'TGR Auction',
  'TGR Auction Pairs',
  'TGR Auction Teams',
  'TGR Super League',
  'The Hague Bridge Experience',
  'Thrace Club Teams',
  'Thrace Cup League',
  'Tianjin Binhai Cup',
  'Tolani Gold Trophy',
  'Tolani Grand Prix',
  'Tolani Silver Cup',
  'Tolani Open',
  'Top Circuit',
  'Torneo di Rastignano',
  'Torneo di Roma',
  'Toscana Cup',
  'Towns Cup',
  'Transnational Open Teams',
  'Trondheim Cup',
  'Turkish Club Championship',
  'Turkish East & South-East Teams',
  'Turkish East Mediterranean Teams',
  'Turkish Open Teams Championship',
  'Turkish Teams Championship',
  'Turkish Women Teams',
  'Turkish Swiss Mixed Teams',
  'Turkish Winter Championship',
  'Turkish Winter Open Teams',
  'Turkish Winter Women Teams',
  'United States Bridge Championship',
  'United States Juniors Bridge Championship',
  'United States Juniors Training',
  'United States Seniors Bridge Championship',
  'United States Women Bridge Championship',
  'US International Team Trials',
  'US Seniors',
  'US Women',
  'US Youngsters',
  'Vanderbilt Fantasy Challenge',
  'Venezuela Swiss Pairs',
  'Venice Cup',
  'Victor Champion Cup',
  'Victorian Mixed Teams',
  'Victorian Open Teams',
  'Victorian Open Teams Playoff',
  'Victorian Pennant',
  'Victorian Youth',
  'Vilnius Club Pairs',
  'Vinoble Cup',
  'VV Cup',
  'Warsaw Online Teams',
  'Watermark Bridge Classic',
  'Wellingdon Swiss Pairs',
  'Western Mediterranean Club Teams',
  'White House Juniors',
  'White House Top 12',
  'White House Top 16',
  'Whitelaw Cup',
  'Willoughby Bridge Classic',
  'Winter Nationals',
  'Winter Championships',
  'Winter Open Teams',
  'Winter Women Teams',
  'World Bridge Series',
  'World Juniors Championship',
  'World Masters Individual',
  'World Men Elite Tournament',
  'World Mind Games',
  'World Open Pairs',
  'World Seniors Championships',
  'World Team Championships',
  'World Team Olympiad',
  'World Top Tournament',
  'World Transnational Teams',
  'World University Championship',
  'World Youth Congress',
  'World Youth Open Bridge Championship',
  'World Youth Teams Championship',
  'World Youth Bridge Congress',
  'World Youth Bridge Teams Championship',
  'World Youth Championship',
  'World Women Elite Tournament',
  'Xinyuan Cup',
  'Yeh Bros Cup',
  'Young Chelsea Knock-out',
  'Zhejiang Huamen Cup',
  "Zia's Individual Goulash",
  'Zimmermann Cup',
  'Zulawski Cup'
);

my %MULTI_TYPOS =
(
  'AfBF Zone 8 Championships' => ['african zone 8 open teams',
    'abf zone 8 championships', 'abf championship', 'abf championships',
    'abf champoinship'],
  'African Zonal Championship' => ['zonal qualifying africa',
    'abf zonal'],
  'All India Corporate Invitational' => [
    'all india invitational corporate'],
  'All India Corporate Invitational Pairs' => [
    'corporate pairs', 'corporate invitational pairs'],
  'All India UTI Bank Masters Championship' => [
    'ull aindia uti bank masters championship',
    'all india uti national masters championship',
    'all india utibank masters championship'],
  'Anatolian Club Qualifying' => ['eastern anatolian qualification',
    'eastern anatolýa qualýfýcatýon',
    'turkish interclubs champ_ anatolia elections'],
  'Anatolian Fall Teams' => ['anatolian side fall teams'],
  'Anatolian Open Teams' => ['anatolian side bridge clubs open teams'],
  'Anatolian Spring Teams' => ['anatolia spring teams'],
  'ArboNed Team Cup' => ['arbo ned team cup', 'arbo ned teams cup'],
  'Argentinian Copa Republica' => ['copa republica'],
  'Argentinian Mixed Teams' => ['argentina equipos mixtos',
    'campeonato nacional equipos mixtos argentino'],
  'Argentinian Open Teams' => ['cn equipos libres argentina',
     'argentine team', 'open argentin team', 'opteamsudamargentina'],
  'Argentinian Seniors Teams' => ['clasificatoria seniors argentina',
    'clasificatoria argentina seniors sudamericano'],
  'ASEAN Club Championship' => ["asean bridge club c'ship",
    'asean bridge club championship', "asean bridge c'ship",
    'asean bridge club', 'asean bridge club championships',
    'asean bridge cship', 'asean bridge championship',
    'asean bridge club open championships',
    'asean bridg club championship', 'asean bridge championships',
    'asean club championships', "aseam bridge club c'ship"],
  'Asian University Championship' => [
    'asian university bridge championship'],
  'Australian National Open Teams' => ['abf anot',
    'abf national open teams'],
  'Australian Grand National Open Teams' => ['abf gnot',
    'grand national open teams'],
  'Australian Open Teams' => ['aust open', 'australian open tream'],
  'Australian Seniors Pairs' => ['aust seniors pairs'],,
  'Australian Seniors Teams' => ['aust seniors open', 'sen australian',
    'aust senriors open'],
  'Australian Spring Open Teams' => ['australian spring open teams'],
  'Australian Spring Seniors Teams' => ['aust spring seniors teams',
    'aust spring seniors', 'australian spring seniors'],
  "Australian Spring Women's Teams" => ['australian spring womens'],
  'Australian Trials' => ['abf trials', 'abf team trials',
    'abf playoff', 'abf trial'],
  'Australian Open Trials' => ['abf open team trials', 'abf oprn trials'],
  'Australian Seniors Trials' => ['abf seniors playoff'],
  "Australian Women's Teams" => ["aust women's team",
    'aust womens team'],
  'Australian Youth' => ['aust youth'],
  'Australian Youth IMP Pairs' => ['aust youth butler',
    'australian youth butler'],
  'Balkan Championship' => ['balkan bridge ch', 
    'balkanbridge championship', 'balkan championships'],
  'Balkan Teams' => ['bolkan team championship',
    'bolkan teams championship', 'bolkan championship'],
  'Baltic Teams Cup' => ['baltic open teams cup'],
  'Baze Senior Knock-out' => ['baze senior ko', 'baze sr_ ko',
    'base sr ko', 'baze sr_ ko', 'baze sr ko'],
  'Belgian Open Teams' => ['belgian teals'],
  'Bergen Grand Tournament' => ['bergen open', 'bergen stor',
    'bergen storturnering', 'bergen grand tournamnet',
    'bergen storturnering mester', 'bergen stor mester',
    'bst mester'],
  'Bermuda Bowl' => ['bermuda bow', 'bemruda bowl'],
  'Bermuda Triangle Cup' => ['bermuda triangle teams cup'],
  'BFAME Championship' => ['zone 4 bridge championship',
    'zone4 bridge championship', 'bfame chp'],
  'Bhabha Atomic Research Centre Open' => ['barc open'],
  'BKBT Teams' => ['bkbt match'],
  'Bobby Evans Seniors Teams' => ["bobby evans senior's teams",
    'bobby evans senior teams'],
  'Bolivian Open Teams' => ['bbolivariano open teams'],
  'Bologna Trophy' => ["trofeo citta' di bologna",
    "trofeo citta' bologna", "citta' di bologna", "trofeo citta' bologna"],
  'Brazilian Championship' => ['brazilian championships',
    'brazilian chapionship', 'open brazilian championship',
    'brasil champ', 'brasilian championship'],
  'Brazilian Teams' => ['brazilian team'],
  'Brazilian Seniors' => ['brazilian senior'],
  'Brazilian Women' => ['brazilian ladies'],
  'British Gold Cup' => ['gold cup', 'british gold'],
  'Buffett Cup' => ['buffet cup', 'bufett cup'],
  'Bulgarian Open Teams Gabi' => ["national bridge tournament \"gabi\"",
    "national tournament \"gabi\"", "bridge tournament \"gabi\"",
    'national tournament gabi'],
  Camrose => ['camrose trophy'],
  'Canadian Open Teams Championship' => ['can open teams championship',
    'can open team championship', 'can_ champ open',
    'canadian a tm', 'canadian tm a'],
  'Canadian Seniors Championship' => ['canadian senior tm'],
  'Canadian Women Championship' => ['can ladies bridge champs'],
  'Canadian Women Teams Championship' => ['can ladies team champ'],
  'Cavendish Teams' => ['cavendish tms', 'cavendish team'],
  'Central American Zonal Championships' => ["cacbf zonal ch'ships",
    'cacbf zonal championship', "cacbf zonal cha'ships",
    "cacbf zonal c'ships", 'cac final'],
  'Centre Island Teams' => ['ci teams'],
  "Champions' Cup" => ['champions cup', "champion's cup", 'chamions cup', 
    'champs cup', 'champion cup', "champion'scup", "champions'cup"],
  'Channel Trophy' => ['channel trpohy'],
  'Cherven Briag National Tournament' => [
    'national tournament cherven briag', 'cherven briag',
    'national tournament cgerven briag'],
  'Chilean Championship' => ['torneo nacional de chile'],
  'Chilean Cup' => ['copa aniversario'],
  'China Elite Tournament' => ['china elite inivitational tournament',
    'china bridge elite tournament',
    'china bridge elite invitational tournament'],
  'China First League' => ['the national class a club league'],
  'Cliff Wake Challenge' => ['cliff wake invitational'],
  'Commonwealth Nations Bridge Championships' => [
    'commonwealth beidge championship', 
    'commonwealth nations bridge championship', 
    "commonwealth nation's bridge championship"],
  'Copenhagen Open Pairs' => ['km åben par'],
  'Czech Championship' => ['czech bridge championship',
    'czech bridge championships'],
  'Czech First League' => ['czech bridge league', 'czech bridge league'],
  'Czech Team Championship' => ['czech team championships',
    'czech teams champ_'],
  'Czech First League' => ['czech 1st league', 'czech bridge league'],
  'Collegiate Bowl' => ['collegiate championship',
    'collegiate championships', 'collegiate champs'],
  'Computer World Championship' => ['computer bridge championship',
    'computer bridge', 'computer world bridge championships'],
  "d'Orsi" => ["d'orsi senior bowl", "d´orsi", 'senior world cup',
    'seniors bowl', 'senior bowl'],
  'Danish Club Teams' => ['danish club team', 'dm klubhold',
    'dm i klubhold', 'dm i knubhold', 'dm i klub hold',
    'danish 1st division', 'danmark - 1_division', 'danmark 1_division',
    'denmark 1_division'],
  'Danish Cup' => ['danmark pokal'],
  'Danish District Championship' => ['danish district teams championship'],
  'Danish Junior Teams' => ['dansih junior teams',
    'danish junior team championship', 'dansih junior team championship',
    'junior dm'],
  'Danish Mixed Pairs' => ['dm mix par', 'danish championship mixed pairs',
    'danish mix-pair championship', 'danish mix pair championship',
    'danish national mix-pairs championship', 'danish mix pairs',
    'dm mix'],
  'Danish Pairs Championship' => ['danish championship - open pairs',
    'danish open pairs championship', 'danish open pairs championships',
    'danish championship open pairs', 'open pairs - danish championship'],
  'Danish Teams Championship' => ['danish team champions',
    'danish team championships', 'danish team championship',
    'danish open team', 'danish open teams', 'danish teams',
    'dm hold', 'dmi i klubhold', 'danish team', 'danish 1_division',
    'danish team chamionship'],
  'Danish Team Trials' => ['danish teams test', 'danish team test',
    'denmark team test'],
  'Danish Women Pairs' => ['ladies pairs - danish championship',
    'danish championship ladies pairs', 'danish champoinship ladies pairs',
    'danish champoinsihp ladies pairs'],
  'Dongming Knock-out Teams' => ['dong ming knockout teams',
    'dong ming knockour teams', 'ding ming knockout teams'],
  'Dr. Heinz von Rotteck Pokal' => ['dr_-heinz-von-rotteck-pokal',
    'v_-rotteck-pokal'],
  'Dr. Rand Masters' => ['dr_ rand masters'],
  'Dutch Meesterklasse' => ['dutch mk'],
  'Dutch Women' => ['ducth woman'],
  'Egyptian League' => ['egy_league', 'egy-league'],
  'Estonian First League' => ['estonian a- league',
    'estonia a- league'],
  'European Bridge Teams Championship' => ['european b.t.ch.',
    'european b_t_ch_', 'e_b_l_ team championships',
    'e_b_l_ teams championship', 'e_b_l team championship',
    'e_b_l_ team champioships', 'europeqn teqm championships'],
  'European Championship' => ['eur champ', 'eur cham', 'champ eur',
    'eur cha', 'eur champ eur'],
  'European Junior Mixed Pairs' => ['eyjc mixed pairs'],
  'European Junior Teams Championship' => [
    'european junior teams championship',
    'euroepan junior teams championships'],
  'European Mixed Junior Pairs' => ['em pairs junior mix',
    'junior em mix'],
  'European Open Bridge Championship' => ['eobc',
    'euroepan open champ', 'european open champ', 'europe open champ'],
  'European Small Federation Games' => ['ebl small federation trophy',
    'ebl small federations trophy', 'games of small federations',
    'european small federations games', 'small federation games',
    'small federations games', 'small ffederations games',
    'small federation cup', 'european small feds games',
    'small f federations games', 'europian small federation games'],
  'European Women Championship' => ['eur women champ'],
  'European Youth Bridge Pairs Championship' => [
    'european youth pairs'],
  'Faroese Teams' => ['faroese tc'],
  'Filbyter Cup' => ['filbyer cup'],
  'Finnish Pairs Championship' => ['finnish pair championship',
    'finnish pair championships', 'finnish pairs champs',
    'finnish pairs'],
  'Finnish Swiss Teams Championship' => [
    'finnish swiss imps championship',
    'finnish swiss imps championships',
    'finnish swiss-imps championships', 'finnish swiss-ims championships'],
  'Finnish Teams Championship' => ['finnish teams championships',
    'finnish teams', 'finnish team championships'],
  'Forbo Krommenie Teams' => ['forbo-krommonie tourname',
    'forbo-krommenie tournament', 'forbo-krommenietournament',
    'forbo-krommenie international bridge event',
    'international forbo krommenie bridge event',
    'forbo-krommenie tourname'],
  'Forbo Nations Cup' => ['Forbo Teams'],
  'Forest Trophy' => ['forest bridge trophy'],
  'FOSS Grand Tournament' => ['foss grand tourney', 'foss grnad tourn',
    'foss grand tourament', 'foss grand tournement', 'foos grnad tourn',
    'foss grand toruney', 'ftredriklstad and sarpsborg grand tournet',
    'foss grand torunament', 'foss grand torurnament',
    'foss grand torurney'],
  'French Cup' => ['coupe de france', 'de la coupe de france'],
  'French Intercircle' => ['finale intercercle'],
  'FullBridge International Teams' => ['internacional equipos full bridge',
    'internacional full bridge', 'internactional de equipos full bridge'],
  'German Club Cup' => ['german cup', 'vereinspokal'],
  'German Open Teams' => ['offene team meisterschaft'],
  'German Team Championship' => ['deutsche teammeisterschaft'],
  'German Team Trophy' => ['german bridge team trophy',
    'dbv-pokal'],
  'German Women Pairs' => ['damen-paar'],
  'Golden Jubilee' => ['golden jubily'],
  'Grand Prix of Poland' => ['grand prix polski', 'gp of poland',
    'grnd prix of poland', 'grand priix polski', 'gp polski',
    'grand prix plolski', 'grand prix team of poland'],
  'Grand Prix of Poland Pairs' => ['grand prix pairs of poland',
    'gran prix pairs of poland'],
  'Grand Prix of Prague' => ['gp prague'],
  'Grand Prix of Wielkopolski' => ['gp wielkopolski',
    'grand prix of wielkopolski', 
    'grand prix of greater poland voivodeship'],
  'Grand Prix of Warsaw' => ['gp warszawy'],
  'Greek Central Regional Championship' => [
    'regional championship of central greece'],
  'Greek Open Teams' => ['greek open nationa team',
    'greek natioanal teams', 'greek open team championship', 
    'greek open team', 'grekk open national team'],
  "Gro's Supercup" => ["gro's super-cup", 'gros supercup'],
  'Guangdong Club Championship' => ['guang dong club championship',
    'guang dong club bridge championship'],
  'Hellenic Mixed Pairs' => ['hellenik mixed pairs'],
  'Hellenic Team Championship' => ['hellenic teams championship'],
  'HNA Cup' => ['nha cup'],
  'Hong Kong Inter-City' => ['hong kong iner-city'],
  'Hungarian IMP Pairs' => ['hungarian imp'],
  'Icelandair Open' => ['icelandari open'],
  'Icelandic Cup' => ['bikarkeppni bsí'],
  'Icelandic Teams' => ['icelandic teamhampionship'],
  'Indonesian Inter-Province Championship' => ['uji coba'],
  'Indonesian League' => ['indonesian bridge league',
    'indonesia bridge league'],
  'Indonesian National Games' => ['indonesian games',
    'indonesian nasional games'],
  'IOC Grand Prix' => ['ioc grandprix'],
  'Israel Juniors Championship' => ['israel juniors chamionship',
    'israel juniours'],
  'Israel Juniors Teams' => ['israel juniors team'],
  'Israel Open Pairs' => ['israel pairs', 'israel pairs champ'],
  'Israel Open Teams' => ['israeli open team',
    'israel team of four cup', 'israel team cup',
    'israel team championship', 'israelairs champ_'],
  'Istanbul Winter Teams' => ['istanbul kis dortlu takimlar',
    'istanbul kis dortlu takim', 'istanbul winter champs',
    'istanbul kis'],
  'Italian Championship' => ['italian master'],
  'Italian Club Championship' => ['campionato italiano di societa',
    'campionato italiano di società', 'camp_ soc_ open',
    'campionato di società', 'camp.societ sportive',
    'campionati soc', 'campionato italiano intersocietario'],
  'Italian Team Championship' => ['camp.it.squadre',
    'camp.it. squadre'],
  "Jessheim New Year's Cup" => ['jessheim new years cup',
    'jesshiem new years cup', 'jessheim new years cup swiss teams'],
  'Jordan Spring Mixed Pairs' => ['jordan spring mix pairs'],
  'Jordan Spring Women' => ['jordan spring womens'],
  'Junior Camrose' => ['juniior camrose'],
  'Kalani Trophy' => ['kalani bridge championship', 'kalani trohy',
    'kalani bridge champioship'],
  'Karnik-Vaidya Open' => ['karnik vaidya open',
    'karnik-vaidya annual'],
  "Kepri Governor's Cup" => ['kepri governor cup', 'kepri cup',
    'kepri governors cup', 'gubernur kepri cup', 'guvernor kepri cup',
    'governor kepri cup', 'gov bi cup', 'governor cup', 'bi cup'],
  'König Ludwig Cup' => ['koenig ludwig nationen cup'],
  'Krakow Spring' => ['krakowska wiosna'],
  'Lady Milne Trophy' => ['lady milne', 'lady mile'],
  'Lederer Memorial Trophy' => ['lederer memorial'],
  "Linda Stern Women's Teams" => ['linda stern womens teams'],
  'Lokmanya Jubilee' => ['lokmanya ss silver jubilee',
    'lokmanya ss siver jubliee', 'lokmanya golden jubilee'],
  'Lüleburgaz Liberation Cup' => ['luleburgaz kurtulus kupasi'],
  'Maccabi Games' => ['maccabi-games', 'europ_ maccabi games'],
  'Madeira Swiss Teams' => ['swiss teams madeira', 'madeira swiss'],
  'McConnell Cup' => ['mc connell'],
  'Milan Trophy' => ["trofeo citta' di milano", "citta' di milano"],
  "Missouri Braggin' Rights" => ['bragging rights'],
  'Mitra Vihar State Championship' => ['mitravihar centenary state level',
    'mitravihar club centenary state level',
    'mitravihar nasik centenary state level'],
  'Mohan Sicka Trophy' => ['mohan sicka'],
  'Mondial de Deauville' => ['mondial deauville',
    'mondial barrière deauville', 'mondial barriere deauville',
    'barriere championship deauville', 'mondial de deauille',
    'montial de deauville', 'mondial barrière de deauville',
    'tournoi des champions barriere'],
  'NN Cup' => ['nn-cup'],
  'Nordic Championship' => ['nordic championships',
    'nordic bridge championship', 'nordic bridge championships'],
  'Nordic Junior Championship' => ['nordic championship for juniors',
    'nordic junior championships'],
  'Nordic Junior Pairs' => ['nordic junior pair championship',
    'open nordic junior pair', 'open nordic junior pairs'],
  'Nordic Junior Team Championship' => [
    'nordic junior team championships',
    'nordic junior teams championship',
    'nordic junior teams championships'],
  'Nordic Open Championship' => ['nordic championship open class'],
  'Nordic Team Championship' => ['nordic bridge team championship',
    'nordics', 'nordic team championships'],
  'Nordic Women Championship' => ['nordics (women)'],
  'Northern Greece Regional Championship' => [
    'n_ greece regional championship'],
  'Northern Territory Gold Teams' => ['nt gold teams'],
  'Northern Territory Gold Swiss Pairs' => ['nt gold swiss pairs',
    'nt gold swis pairs', 'nt gold swiss piars'],
  'Norwegian Club Cup' => ['sm norway', 'norway sm'],
  'Norwegian Club Teams' => ['norwegian clubteams championship',
    'norwegian ch ship teams', 'norwegian clubteams ch_ship',
    'norwegian clubteam championship', 'norw premier league',
    'nor club teams ch_ship', 'nor_club teams ch_ship',
    'norway km teams'],
  'Norwegian Corporate Championship' => ['norwegian corp_ championship'],
  'Norwegian District Championship' => ['norwegian district',
    'norw district', 'norwegian regional chship',
    'norway regional champship'],
  'Norwegian Mixed Pairs' => ['nor mixed pairs ch_ship', 'nm mix pairs',
    'norwegian championship mix swiss pair'],
  'Norwegian Mixed Teams' => ['norwegian championship mix swiss teams'],
  'Norwegian Open Pairs' => ['nm monrad pairs', 'nm pairs',
    'nm swiss pairs', 'nm-pairs'],
  'Norwegian Open Teams' => ['nm open teams'],
  'Norwegian Swiss Teams' => ['nm-monrad-lag', 'nor swiss teams',
    'norwegian swiss team championship', 'nm monrad lag', 
    'nm-monrad-teams', 'norwegian championship swiss teams'],
  'Norwegian Teams' => ['norwegian teams ch_ship',
    'norwegian teams ch.ships', 'norewegian chship temas'],
  'Olrud Easter Mixed Pairs' => ['olrud easter mixed'],
  'Olrud Easter Swiss Teams' => ['olrudpaasken monrad lag',
    'olrud paasken monrad lag', 'olrud easter tourn',
    'olrud swiss teams', 'olrud easter swiss event', 'olrud easter',
    'olrud easter swiss team', 'olrud easter tournament'],
  'Olrud Easter Teams' => ['olrudpaasken teams',
    'olrud estern teamevent', 'olrud estern team-event',
    'olrud easter team-event'],
  'Open Catalunya Preferent' => ['open catalunya equips',
    'open cataluña preferent', 'open preferent equips',
    'open preferent', 'open equips preferent'],
  'PRBA State Level Open' => ['prba open state level',
    'prba state level', 'prba statelevel'],
  'PYC Hindu Gymkhana Royale' => ['pyc royale'],
  'PYC Hindu Gymkhana PairsRoyale' => ['pyc pairs royale'],
  'Pan Arab Inter-Club Championship' => ['pan arab championship',
    'pan arab inter_club', 'pan arab interclub', 'pan arab inerclub',
    'pan arab inter-club', 'pan arab inter club', 'pan arab iner club'],
  'Patton de Monaco' => ["monaco's patton", 'patton international monaco',
    'patton international monte-carlo',
    'patton international monte carlo', 'patton monte carlo'],
  'Pärnu Summer Invitational Pairs' => [
    'pärnu summer_ invitational pairs_', 
    'parnu summer tournament_ invitatoinal pairs',
    'pärnu summer tournament_ invitational pairs_'],
  'Petit Grand Prix van Driene' => ['petit grand prix',
    'grand prix van driene'],
  'Plock District League' => ['plockiej ligi okregowej'],
  'Poddar National Masters' => ['poddar national master',
    'poddar nationals masters', 'podder national masters',
    'podder nationals masters'],
  'Polish BAM Teams' => ['bam team championship of poland'],
  'Polish Boys Championship' => ['polish championship boys'],
  'Polish Girls Championship' => ['polish championship girls'],
  'Polish IMP Pairs' => ['butler polish championship',
    'butler (imp) polish pairs championship'],
  'Polish Individual Championship' => [
    'individual championship of poland'],
  'Polish Mixed Teams' => ['Mistrzostwa Polski Teamów Mikst'],
  'Polish Open Teams' => ['polish open tems'],
  'Polish Pairs' => ['pairs championship od poland',
    'pairs championship of poland', 'open pairs championship of poland'],
  'Polish Premier League' => ['polish premiere league',
    'polish league', 'polish premier leuge'],
  'Polish Teams' => ['mistrzostwa polski teamów',
    'teams championship of poland', 'championship of poland',
    'team championship of poland', 'champioship of poland'],
  'Polish Youngster Teams' => ['kadry juniorów m³odszych'],
  'Pomerania Cup' => ['rozgrywek pucharowych pwzbs'],
  'Portuguese Open Teams' => ['equipas open pt', 'open teams pt',
    'portuguese cneo'],
  'Poznan Mixed Pairs' => ['otwarte mistrzostwa poznania mixt'],
  'Riga Invites to Jurmala' => ['riga invites', 'latvia invites'],
  'Romanian League' => ['cn echipe', 'c_n_ echipe', 'cn ecgipe',
    'divizia a', 'romanian teams championship - divizia a',
    'romanian national teams div a', 'romanian national division',
    'romanian national teams- div a', 'romanian teams-a division',
    'romanian teams- a division', 'romanian teams - a division'],
  'Rosfjord Swiss Teams' => ['rosfjord monrad team',
    'rosfjord monrad teams'],
  'Rottneros Nordic Cup' => ['rottneros cup'],
  'Ruia Gold Cup' => ['ruia gold'],
  'Ruter 7 Open' => ['ruter7 elitetournament'],
  'Sao Paulo State Championship' => ['s o paulo cup', 'sao paulo champ',
    'sao paulo championship', 'sao paulo champ', 'sao paulo cup',
    'sao paulo state cup', 'são paulo cup', 'sap paulo state championship',
    'são paulo state championship', 'sp champ', 'sao paulo state'],
  'Sarundajang Cup' => ['the sarundajang cup'],
  'Scottish Cup' => ['scot cup', 'scot cuo', 'scottish cup plate'],
  'Senior Camrose' => ['seniors camrose'],
  'Serbian Cup' => ['cup of serbia', 'kub srbije', 'cup srbije',
    'kup srbije'],
  'Serbian Premier League' => ['serbian premier leaugue',
    'serbian league'],
  'Serbian Team Championship' => ['serbia teams championship',
    'serbian tam championship', 'serbian teams championship',
    'serbianteam championship', 'serbian closed team championship'],
  'Shenhua Cup' => ['shen hua cup'],
  'Silver Jubilee' => ['siver jubliee'],
  'Slava Cup' => ['cup slava', 'salava cup'],
  'South African Championship' => ['south african nationals',
    'south african championships'],
  'South African Teams' => ['south african chaionships'],
  'South American Bridge Championships' => ['sabc'],
  'South American Seniors Teams' => ['clasificacion sudamericano seniors'],
  'South American Women Teams' => ['clasificatoria damas equipos',
    'clasificatoria equipos damas'],
  'South American Trials' => ['clasificatoria sudamericano',
    'clasificatorias sudamericano', 'south americal trials'],
  'South Zone Championship' => ['southzone championship',
    'souhzone championship'],
  'Southeast Asian Games' => ['sea games', 'south east asian games'],
  'Spanish Central Zone Teams' => ['zonal centro equipos',
    'equipos zonal centro'],
  'Spanish Open Trials' => ['open seleccion mundial'],
  'Spanish Teams Championship' => ['campeonato de españa por equipos',
    'campeonato espan ronda', 'campeonato espanaonda', 'camp esp ronda'],
  'SPBF Championship' => ['zone 7 championship', 'zone 7 championships'],
  'Spring Fours' => ['spring 4s', 'spring foursomes', 'schapirosfs'],
  'Spring Nationals' => ['spring nat', 'spring national', 'spring nats',
    'sping national', 'spring nat opens'],
  'Staszic Pairs Cup' => ['otp puchar grodu staszica'],
  'Stockholm Teams' => ['stockholm teams cs'],
  'Sudamericano Transnacional' => ['sudamerican transnacional',
    'sudamerico transnacional'],
  'Summer Monsoon League' => ['summer monsoon', 'summer monsoon leahue'],
  'Summer Nationals' => ['summer national'],
  'Swedish District Championship' => ['swedish championships distrcit',
    'sweden distric', 'swedish districts', 'swedish disttrict',
    'swedis district', 'swesish district', 'sweden district',
    'swedish championship district', 'swesish champsionship district',
    'swedish championships district', 'swedish district championships',
    'swedish championship cistrict', 'swedish district',
    'swedish champsionship district', 'swdish district'],
  'Swedish Elite Series' => ['swedish elitserien'],
  'Swedish Juniors Championship' => ['swedish juniors cs'],
  'Swedish Juniors Teams' => ['swedish juniors teams cs',
    'swedish juniors teams cs'],
  'Swiss Championship' => ['champion suisse', 'championnat suisse',
    'swiss championshi', 'swiss championshio'],
  'Swiss Club Championship' => ['swisss interclubs', 'swiss interclubs',
    'swiss inter clubs', 'swiss interclub championship',
    'swiss interclub'],
  'Swiss Cup' => ['coupe suisse', 'swiss open cup', 'swiss open',
    'swiss cuo'],
  'Swiss Open Championship' => ['swiss open championship'],
  'Swiss Team Championship' => ['swiss team champiomshio'],
  'Taiwan University Cup Teachers' => [
    "taiwan university cup teacher's section"],
  'Taiwanese Teams' => ['taiwanese teal'],
  'TATA Open' => ['tata opren', 'tata sports', 'ttat open'],
  'Teltscher Trophy' => ['teltcher trophy', 'telscher trophy'],
  'TGR Auction Pairs' => ['tgr auction pair', "tgr's auction pairs",
    'tgrs auction pair', 'tgrs auction pairs'],
  'TGR Auction Teams' => ['tgrs auction teams'],
  'TGR Super League' => ["tgr's super league", "tgr's super legue",
    'tgrs league', 'tgrs 2nd auction pairs', 'tgrs super league',
    "tgr's league", "trg's super league"],
  'The Hague Bridge Experience' => ['the hague bride experience',
    'teh hague bridge experience'],
  'Thrace Club Teams' => ['thrace region clubs team championship',
    'türk trakya bölge kulüpler þampýyonasi ekýbý',
    'thracean club teams', 'trachean club teams'],
  'Thrace Cup League' => ['trakya kulupler ligi'],
  'Tianjin Binhai Cup' => ['tianjin bin hai cup'],
  'Tolani Gold Trophy' => ['dr_tolani gold troph',
    'tolani summer nationals gold', 'tolani summer nationald gold',
    'tolani gold summer nationals', 'tolani gold summar nationals',
    'tolani gold summer national', 'dr_tolanigoldcup',
    'dr_tolani gold summer nationals', 'tolani gold summer nationals',
    'tolani gols summer nationals', 'dr_tolani open summer natinal',
    'dr_tolani open summer national', 'dr_tolani open summer nationals',
    'dr_ tolani open summer nationals',
    'dr_tolani open summer nationaals', 'dr tolani open summer nationals'],
  'Tolani Grand Prix' => ['tolani gp', 'tolani grand pix'],
  'Tolani Open' => ['dr_ tolani open summer nations',
    'dr_ tolani summar nationals'],
  'Tolani Silver Cup' => ['dr tolani summer nationals silver',
    'dr_tolani open summer nationals silver',
    'dr_tolani silver cup summer national',
    'dr_tolani sliver cup summer nationals'],
  'Torneo di Roma' => ['tornei di roma'],
  'Trondheim Cup' => ['trondheim cup swiss teams'],
  'Turkish Club Championship' => ['türkýye kulüplerarasi þampýyonasi',
    'türkýye klüpler arasi brýç þampýyonasi'],
  'Turkish East & South-East Teams' => [
    'turkish clubs championship east & south east el'],
  'Turkish East Mediterranean Teams' => [
    'turkish east mediterranean',
    'turkish east mediterranean club teams',
    'turkish eastern mediterranean club', 
    'turkish eastern mediterranean club teams'],
  'Turkish Open Teams Championship' => [
    'turkiye acik takimlar sampiyonasi'],
  'Turkish Swiss Mixed Teams' => ['turkey swiss mixed teams'],
  'Turkish Teams Championship' => ['turkiye bric takimlar sampiyonasi'],
  'Turkish Winter Championship' => ['turkiye kis takimlar sampiyonasi',
    'turkish winter chanpionship'],
  'Turkish Winter Open Teams' => ['turkiye kis acik takimlar sampiyonasi'],
  'Turkish Winter Women Teams' => [
    'turkish winter woman team championship'],
  'Turkish Women Teams' => ['türkish ladies teams'],
  'United States Bridge Championship' => ['us bridge championship',
    'u_s_b_c', 'united states bridge championships'],
  'United States Juniors Bridge Championship' => [
    'jusbc rona'],
  'United States Women Bridge Championship' => [
    "us women's bridge championship", "us women's bridge championhip",
    "united states women's bridge championship"],
  'US International Team Trials' => ['us itt'],
  'US Seniors' => ['us senior'],
  'US Women' => ['us womens championships'],
  'US Youngsters' => ['u-21 us'],
  Vanderbilt => ['vanderbilt teams', 'vanderbilt ko teams'],
  'Venezuela Swiss Pairs' => ['venezuela parejas suizas'],
  'Venice Cup' => ['<venive <cup'],
  'Victorian Open Teams' => ['victorian opean teams', 'victorian open',
    "'victorian open", 'victorian open team', 'victorian opean',
    'victoian open', 'victorian team'],
  'Victorian Pennant' => ['vic pennant'],
  'Victorian Open Teams Playoff' => ['victorian playoff'],
  'Victorian Youth' => ['victorian youth'],
  'Vinoble Cup' => ['vinoble open'],
  Wagar => ['wagar teams', "wagar women's", "wagar women's ko",
    'wagar womens ko'],
  'Warsaw Online Teams' => ['enthusiast bridge zlot', 
    'warsaw bboers champ', 'warsaw bboers championship'],
  'Watermark Bridge Classic' => ['watermark team', 'watermark teams'],
  'Wellingdon Swiss Pairs' => ['wsc open swiss pairs championship',
    'wsc open swisspairs championship', 'wsc swiss open pairs'],
  'Western Mediterranean Club Teams' => [
    'western mediterranean clubs team championship'],
  'White House Juniors' => ['whiteouse juniors', 'the white hous juniors',
    'qhite house juniors'],
  'White House Top 12' => ['modalfa top 12', 'witte huis top 12'],
  'White House Top 16' => ['white house int. teams top 16',
    'white house int_ teams top 16',
    'white house international top 16 teams'],
  'Top Circuit' => ['melchemie top circuit',
    'ing bank top circuit', 'ng bank top circuit', 
    'witte huis topcircuit'],
  'Winter Championships' => ['winter championship',
    'winter championsship'],
  'Winter Nationals' => ['winter national', 'wintter nationals',
    'wintrer national'],
  'Winter Open Teams' => ['winter teams', 'winter team'],
  'World Juniors Championship' => ['world juniors championships'],
  'World Masters Individual' => ['masters individual',
    'world masters'],
  'World Mind Games' => ['world mind game', 'word mind games', 'wmsg',
    'mind sports games', 'sawmg', 'wmg', 'wnsg', 'world ming games'],
  'World Open Pairs' => ['world pairs championship'],
  'World Seniors Championships' => ['world senior championship'],
  'World Team Olympiad' => ['world bridge team olympiad',
    'world bridge olympiad', 'bridge olympiad'],
  'World Transnational Teams' => ['world transnational open teams'],
  'World University Championship' => [
    'world university bridge championship',
    'world university bridge championships',
    'univ_ world champs'],
  'World Youth Championship' => ['world youth championships'],
  'World Youth Congress' => ['youth world bridge congress',
    'worlf youth bridge congress', 'workd youth bridge congress',
    'world youht congress'],
  'World Youth Teams Championship' => ['world youth team championships',
    'world youth teams'],
  'Yeh Bros Cup' => ['yehbros cup'],
  'Young Chelsea Knock-out' => ['yc ko', 'young chelsea ko',
    'young chelsea knockout'],
  'Zulawski Cup' => ['zulawski teams']
);

my @SINGLE_WORDS = qw(
  Bundesliga
  Camrose Cavendish
  Reisinger
  Rosenblum
  Spingold
  Vadsøturneringen Vanderbilt
  Wagar
);

my %SINGLE_TYPOS =
(
  'ABPF Championships' => ['pabfc'],
  'Argentinian Open Teams' => ['cnia'],
  'ASEAN Club Championship' => ['abcc'],
  'Australian National Open Teams' => ['anot'],
  'Bermuda Bowl' => ['bb'],
  'Bobby Evans Seniors Teams' => ['best'],
  'Brazilian Championship' => ['brasilchamp'],
  "Buffett Cup" => ['buffett', 'buffet'],
  Camrose => ['camroae', 'ccmrose'],
  'Canadian Bridge Championship' => ['cbc'],
  'Canadian National Teams Championship' => ['cntc'],
  'Canadian Seniors Teams Championship' => ['cstc', 'cnst'],
  'Canadian Women Teams Championship' => ['cwtc'],
  Cavendish => ['cavendiish', 'caavendish', 'cavemdish', 'cavendiosh',
    'cavendsh', 'cavvendish', 'avendish', 'cav'],
  'Collegiate Bowl' => ['collegiate', 'collegiates'],
  'Commonwealth Nations Bridge Championships' => ['cnbc'],
  'Copenhagen Invitational Pairs' => ['cbi'],
  'Danish Championship' => ['dm'],
  "d'Orsi" => ['dorsi', 'sb', 'dosb'],
  'Dutch Meesterklasse' => ['meesterklasse'],
  'European Bridge Teams Championship' => ['ebtc'],
  "European Champions' Cup" => ['ecc'],
  'European Championship' => ['ec'],
  'European Open Bridge Championship' => ['eoc'],
  'European Small Federation Games' => ['esfg', 'sfc'],
  'European University Bridge Championship' => ['eubc', 'eucb', 'euc'],
  'European Winter Games' => ['ewg'],
  'European Youth Bridge Championship' => ['eybc'],
  'European Youth Bridge Pairs Championship' => ['eybpc', 'eypc'],
  'European Youth Bridge Teams Championship' => ['eytc', 'jem'],
  'FOSS Grand Tournament' => ['foss'],
  'German Team Championship' => ['teammeisterschaft'],
  'Grand National Open Teams' => ['gnot'],
  'Grand Prix of Poland' => ['gpp', 'gppp'],
  "Gro's Supercup" => ['grocup'],
  'Icelandair Open' => ['icelandair'],
  'Junior Camrose' => ['juniorcamrose', 'juniorcmrose'],
  "Kepri Governor's Cup" => ['kepricup'],
  'Lederer Memorial Trophy' => ['lederer', 'ledered'],
  "Linda Stern Women's Teams" => ['lswt'],
  'Maccabi Games' => ['maccabiah'],
  'McConnell Cup' => ['mcconnell'],
  'North American Bridge Championship' => ['nabc'],
  'NTU Cup' => ['ntucup'],
  'Olrud Easter Teams' => ['olrudeasterteams'],
  'Paris Youth Open Teams' => ['ypob'],
  'Peggy Bayer' => ['peggybayer'],
  'Portuguese Open Teams' => ['cneo'],
  Reisinger => ['reisiger', 'resisinger'],
  'Gianarrigo Rona Trophy' => ['rona'],
  'Rondane Cup' => ['rondanecupen'],
  'Ruia Trophy' => ['ruia'],
  'Scottish Cup' => ['scottishcupplate'],
  'Southeast Asian Games' => ['seagames'],
  'Summer Nationals' => ['summernationals'],
  'Swedish Elite Series' => ['elitserien'],
  'Takamatsu Cup' => ['takamatsu'],
  'Teltscher Trophy' => ['teltschertrophy', 'teltscher', 'telschertrophy'],
  'Tolani Grand Prix' => ['tolanigrandprix'],
  'Top Circuit' => ['topcircuit'],
  'Transnational Open Teams' => ['tnt', 'tnot'],
  'United States Bridge Championship' => ['usbc'],
  'United States Juniors Bridge Championship' => ['usjbc', 'jusbc'],
  'United States Juniors Training' => ['jtp'],
  'United States Seniors Bridge Championship' => ['ussbc'],
  'United States Women Bridge Championship' => ['uswbc', 'uswbf', 'uswc'],
  Vanderbilt => ['vanderbuilt', 'vanderebilt', 'vandebilt'],
  'Venice Cup' => ['vc'],
  'Victor Champion Cup' => ['vcc'],
  'Victorian Pennant' => ['pennant'],
  'Vilnius Club Pairs' => ['vbk'],
  'White House Juniors' => ['whj'],
  'Winter Nationals' => ['winternationals'],
  'World Bridge Series' => ['wbs'],
  'World Team Championships' => ['wbtc'],
  'World Team Olympiad' => ['olympiad', 'olympiads', 'wbo'],
  'World University Championship' => ['wuc'],
  'World Youth Bridge Team Championship' => ['wybtc'],
  'World Youth Open Bridge Championship' => ['wyobc', 'wboyc'],
  'World Youth Teams Championship' => ['wytc', 'world youth teams'],
  'Young Chelsea Knock-out' => ['ycko'],
  'Zimmermann Cup' => ['zc']
);


sub set_hashes
{
  my ($method, $key) = @_;

  $method->(\@MULTI_WORDS, \%MULTI_TYPOS,
    \@SINGLE_WORDS, \%SINGLE_TYPOS, $key);
}

1;
