#!perl

use strict;
use warnings;
use v5.10;
use utf8;
use open ':std', ':encoding(UTF-8)';

package Tags::University;

our @ISA = qw(Exporter);
our @EXPORT = qw(set_hashes);

my @MULTI_WORDS =
(
  'AGH Krakow',
  'Airmadidi Senior High School',
  'Akdeniz University',
  'Anadolu University',
  'Andalas University',
  'Ankara University',
  'Antalya Halk Egitim',
  'Batusida Senior High School',
  'Bengkulu Senior High School',
  'Bilkent University',
  'Bogor Senior High School',
  'Brawijaya University',
  'Budapest University',
  'Carnegie Mellon University',
  'Chang Gung University',
  'Charles University',
  'Chien Kuo Senior High School',
  'China Central University of Business',
  'Chung Hua University',
  'Chung Hwa Medical and Pharmaceutical University',
  'Columbia University',
  'Cornell University',
  'Croatia University',
  'Diponegoro University',
  'Duta Bangsa College',
  'École Polytechnique',
  'Ege University',
  'Fu Jen Catholic University',
  'Fudan University',
  'Fuzhou University',
  'Gakushuin University',
  'Georgia Tech',
  'Guangzhou Keji', # Technology
  'Gunadarma University',
  'Harvey Mudd College',
  'Hebei Normal University',
  'Huazhong University of Science and Technology',
  'Høgskolen i Sør-Trøndelag',
  'Institut Teknologi Bandung',
  'Istanbul University',
  'ITS IKOMA',
  'ITÜ Vakfi',
  'Jember Senior High School',
  'Jiangsu Tianyi',
  'Kaisei High School',
  'Karel de Grote',
  'Kasetsart University',
  'Kediri Senior High School',
  'Kedungwaru Senior High School',
  'Kirsehir Republic Primary School',
  'Kocaeli University',
  'Koc University',
  'Kozminski University',
  'KU Leuven',
  'Kusuma Bangsa',
  'Kyoto University',
  'Lumajang Senior High School',
  'Makassar University',
  'Manado State University',
  'Marmara University',
  'Miaoli Senior High School',
  'Middle East Technical University',
  'Nahdlatul Ulama Alumni',
  'Nanchang University',
  'National Chengchi University',
  'National Chiao Tung University',
  'National Chung Cheng University',
  'National Chung Hsing University',
  'National Taiwan Normal University',
  'National Taiwan Ocean University',
  'National Taiwan University',
  'National Tsing Hua University',
  'National Yang Ming Chiao Tung University',
  'Northwestern University',
  'Osaka University',
  'Osmangazi University',
  'Paris ECE',
  'Paris-Sud University',
  'Paris Université Club',
  'Politeknik Negeri Jember',
  'Politeknik Negeri Malang',
  'Radboud University',
  'Renmin University High School',
  'Rhein-Waal University',
  'Riau University',
  'Sam Ratulangi University',
  'Selçuk University',
  'Shenyang Ligong',
  'Sekolah Tinggi Ilmu Statistik',
  'Sekolah Tinggi Teknologi',
  'Shangbu Primary School',
  'Soochow University',
  'Stanford University',
  'Sukomoro Senior High School',
  'Surabaya Senior High School',
  'Tarsus American College',
  'Telkom University',
  'Thammasat University',
  'Tianjin Normal University',
  'Tilburg University',
  'Tohoku University',
  'Tokyo University',
  'Trakya University',
  'TU Midtsjælland',
  'Tübingen University',
  'Umeå University',
  'UBC Hamburg',
  'Universitas Gadjah Mada',
  'Universitas Katolik Soegijapranata',
  'Universitas Merdeka Malang',
  'Universitas Muhammadiyah Gresik',
  'Universitas Negeri Malang',
  'Universitas Pendidikan Ganesha',
  'Universitas Riau Bridge Club',
  'Universitas Sriwijaya',
  'Universitas Sumatera Utara',
  'University of Airlangga',
  'University of Bung Hatta',
  'University of California at Berkeley',
  'University of Catania',
  'University of Chicago',
  'University of Craiova',
  'University of Gdansk',
  'University of Illinois',
  'University of Jember',
  'University of Muhammadiyah Malang',
  'University of North Carolina',
  'University of Padjajaran',
  'University of Porto',
  'University of Rijeka',
  'University of Surabaya',
  'University of Tanjungpura',
  'University of Warsaw',
  'University of Wroclaw',
  'Universität Potsdam',
  'Valahia University',
  'Warsaw University of Technology',
  'Wijaya Kusuma University',
  'Wroclaw University of Science and Technology',
  'Xuzhou Institute of Technology',
  'Yildiz Technical University',
  'Zagreb University'
);

my %MULTI_TYPOS =
(
  'Airmadidi Senior High School' => ['sman 1 airmadidi'],
  'Akdeniz University' => [
    'akdeniz uni.', 
    'akdeniz universites',
    'akdenýz üný', 
    'd.akdený'],
  'Anadolu University' => [
    'anadolu uni', 
    'anadolu univeritesi',
    'anadolu universites', 
    'anadolu unv',
    'anadolu unv. sk',
    'eskisehir anadolu u',
    'uni anadolu'],
  'Andalas University' => ['universitas andalas',
    'univ. andalas ft'],
  'Ankara University' => ['ankara uni'],
  'Batusida Senior High School' => ['sma batusida'],
  'Bengkulu Senior High School' => ['shs bengkulu'],
  'Bilkent University' => ['bilkent uni'],
  'Bogor Senior High School' => ['sma kimia bogor'],
  'Budapest University' => ['budapest uni'],
  'Carnegie Mellon University' => ['carnegie mellon'],
  'Croatia University' => ['cro uni'],
  'Diponegoro University' => ['univ. diponegoro',
    'uinv. diponegoro'],
  'Duta Bangsa College' => ['dbc jateng'],
  'École Polytechnique' => ['paris polytechnix', 'ecole polytech'],
  'Ege University' => ['ege uni'],
  'Gakushuin University' => ['gakushuin univ',
    'gakushuin.univ'],
  'Georgia Tech' => ['gt gold'],
  'Gunadurma' => ['guna darma'],
  'Harvey Mudd College' => ['harvey mudd'],
  'Hebei Normal University' => ['hebei shifan'],
  'Huazhong University of Science and Technology' => [
    'huazhong keji'],
  'Institut Teknologi Bandung' => ['uab itb'],
  'Istanbul University' => ['istanbul unv'],
  'ITÜ Vakfi' => ['itu vakfi', 'ýtü vakfi'],
  'Jember Senior High School' => ['sman 1 jember', 'sman i jember',
    'sman arjasa', 'sma nbc jember'],
  'Kaisei High School' => ['kaisei h.s.'],
  'Kediri Senior High School' => ['sman 1 kediri', 'sma kediri',
    'sma 1 kediri'],
  'Kedungwaru Senior High School' => ['sma kedungwaru'],
  'Kirsehir Republic Primary School' => ['kýrþehir cumh. ýöo'],
  'Koc University' => [
    'koc unv',
    'koç üniversitesi', 
    'koç universitesi',
    'koç ünýversýtesý', 
    'koc universitesi',
    'koç uni',
    'koc uni'],
  'Kocaeli University' => ['kocaeli üni'],
  'Kozminski University' => ['kozminski uni',
    'kozminski univ'],
  'Kyoto University' => [
    'kyo.to.u',
    'kyoto univ', 
    'kyoto.univ',
    'kyoto.unv'],
  'Langkat Senior High School' => ['sma langkat'],
  'Lumajang Senior High School' => ['sma lumajang'],
  'Magetan Senior High School' => ['sma 1 sukomoro'],
  'Marmara University' => ['Marmara Ü.M.D'],,
  'Middle East Technical University' => ['odtu yk'],
  'Nahdlatul Ulama Alumni' => ['nu alumni'],
  'Nanchang University' => ['nanchang gongcheng'],
  'National Chengchi University' => ['nccu'],
  'National Chiao Tung University' => ['nctu'],
  'National Chung Hsing University' => ['nchu'],
  'National Taiwan University' => ['abc_e', 'btu-p', 'btu-u', 
    'btu-y', 'ntu-pac'],
  'National Tsing Hua University' => ['tsinghua university'],
  'National Yang Ming Chiao Tung University' => ['nycu-c', 'nycu-d'],
  'Osaka University' => ['osaka univ', 'osaka.univ'],
  'Osmangazi University' => ['osmangazi uni'],
  'Paris-Sud University' => ['paris-sud universit'],
  'Paris Université Club' => ['bc p.u.c'],
  'Politeknik Negeri Jember' => ['poltek n jember'],
  'Politeknik Negeri Malang' => ['poli. ne. malang'],
  'Renmin University High School' => ['Ren Da Fu Zhong',
    'rsfz hu'],
  'Rhein-Waal University' => ['rhine university'],
  'Riau University' => ['universitas riau', 'uko unri'],
  'Sam Ratulangi University' => ['univ. samratulangi',
    'univ. sam ratulangi'],
  'Sekolah Tinggi Ilmu Statistik' => [
    'stis multivariant'],
  'Selçuk University' =>['selçuk uni', 'selcuk universitesi'],
  'Shangbu Primary School' => ['shangbu primary sch'],
  'Sukomoro Senior High School' => ['sman 1 sukomoro'],
  'Surabaya Senior High School' => ['shs surabaya'],
  'Tarsus American College' => [
    'tarsun bric',
    'tarsus a koleji', 
    'tarsus amer koleji',
    'tarsus american', 
    'tarsus american col', 
    'tarsus amerikan', 
    'tarsus amerikan col',
    'tarsus amerikan k', 
    'tarsus amerikan klj', 
    't.a.c'],
  'Tianjin Normal University' => ['tianjin shifan'],
  'Tohoku University' => ['tohoku univ'],
  'Tokyo University' => [
    'tokyo uniersity', 
    'tokyo univ',
    'tokyo.u', 
    'tokyo.univ'],
  'Trakya University' => [
    'trakya uni', 
    'trakya tip',
    'trakya universitesi',
    'trakya üniversitesi',
    'trakiyski briz'],
  'Tübingen University' => ['tubingen univ', 'tubingen uni'],
  'Umeå University' => ['umea uni'],
  'Universitas Gadjah Mada' => ['univ. gadjah mada',
    'univ. gajah mada'],
  'Universitas Negeri Malang' => ['univ. neg. malang'],
  'Universitas Pendidikan Ganesha' => ['ganesha uoe'],
  'University of Airlangga' => ['univ airlangga', 'airlangga unv'],
  'Brawijaya University' => ['univ brawijaya', 'university of brawijaya'],
  'University of Bung Hatta' => ['univ bung hatta', 'univ. bung hatta'],
  'University of California at Berkeley' => ['cal berkeley',
    'u calif berkeley', 'cal-berkeley', 'uc berkeley',
    'u cal berkeley'],
  'University of Catania' => ['univ of catania'],
  'University of Chicago' => ['u chicago'],
  'University of Craiova' => [
    'u craiova',
    'u. craiova',
    'univ craiova',
    'universit. craiova'], 
  'University of Gdansk' => ['uni gdansk', 'gdank univ poland',
    'gdansk univ poland'],
  'University of Illinois' => ['u of illinois', 'u illinois uc'],
  'University of Jember' => ['univ jember'],
  'University of Muhammadiyah Malang' => ['un. muh. malang'],
  'University of North Carolina' => ['u n. carolina'],
  'University of Padjajaran' => ['univ. padjajaran'],
  'University of Rijeka' => ['uni of rijeka'],
  'University of Tanjungpura' => [
    'ftbc u tanjungpura',
    'ftbc u. tanjungpura',
    'untan', 
    'univ. tanjungpura',
    'tanjungpura university'],
  'University of Warsaw' => ['uni warsaw', 'uw tg', 'azs uw ptc'],
  'University of Wroclaw' => ['uni wroclaw'],
  'Universität Potsdam' => ['uni potsdam'],
  'Warsaw University of Technology' => ['warsaw ut'],
  'Wijaya Kusuma University' => ['surabaya kusuma'],
  'Wroclaw University of Science and Technology' => 
    ['polit wroclaw', 'polite wroclaw', 'polit wr', 'politechnika wr', 
    'azs pw', 'politehnica cluj', 'poli cluj', 'poli', 'azs invit'],
  'Xuzhou Institute of Technology' => ['xuzhou iot'],
  'Yildiz Technical University' => ['yildiz sp.'],
  'Zagreb University' => [
    'inst.of chem.tech.',
    'inst.of chem.techn.'],
);

my @SINGLE_WORDS = qw(
  Brandeis
);

my %SINGLE_TYPOS =
(
  'Andalas University' => ['unand', 'agbc'],
  'Bilkent University' => ['bilkent'],
  'Brawijaya University' => ['brawijaya'],
  'Chang Gung University' => ['cgu'],
  'Chien Kuo Senior High School' => ['ckbc'],
  'China Central University of Business' => ['ccub'],
  'Chung Hua University' => ['chu'],
  'Chung Hwa Medical and Pharmaceutical University' => ['cmu'],
  'Diponegoro University' => ['undip'],
  'École Polytechnique' => ['polytech'],
  'Fu Jen Catholic University' => ['fju'],
  'Guangzhou Keji' => ['gzkj'],
  'Gunadarma University' => ['gunadarma', 'gunadharma'],
  'Høgskolen i Sør-Trøndelag' => ['hist'],
  'Institut Teknologi Bandung' => ['itb'],
  'Kasetsart University' => ['kasetsart'],
  'Koc University' => ['koc'],
  'Makassar University' => ['mu'],
  'Manado State University' => ['unima'],
  'Miaoli Senior High School' => ['cbb'],
  'Middle East Technical University' => ['odtu'],
  'National Chung Cheng University' => ['ccu'],
  'National Taiwan Normal University' => ['ntnu'],
  'National Taiwan Ocean University' => ['ntou'],
  'National Taiwan University' => ['ntu', 'btu'], 
  # Also Nanyang Tech. Uni...
  'National Tsing Hua University' => ['nthu'],
  'Northwestern University' => ['northwestern'],
  'Osmangazi University' => ['osmangazi'],
  'Politeknik Negeri Malang' => ['polinema'],
  'Radboud University' => ['radboud'],
  'Renmin University High School' => ['rdfz'],
  'Riau University' => ['unri'],
  'Sam Ratulangi University' => ['unsrat'],
  'Sekolah Tinggi Teknologi' => ['stt'],
  'Soochow University' => ['scu'],
  'Stanford University' => ['stanford'],
  'Sekolah Tinggi Ilmu Statistik' => ['stis', 'stig'],
  'Tarsus American College' => ['tac', 'tarsus'],
  'Thammasat University' => ['thammasat'],
  'Brawijaya University' => ['ub', 'brawijaya'],
  'Universitas Gadjah Mada' => ['ugm'],
  'Universitas Katolik Soegijapranata' => ['unika'],
  'Universitas Muhammadiyah Gresik' => ['unmuh'],
  'Universitas Pendidikan Ganesha' => ['undiksha'],
  'Universitas Riau Bridge Club' => ['urbc'],
  'Universitas Sriwijaya' => ['unsri'],
  'University of Tanjungpura' => ['untan'],
  'Universitas Sumatera Utara' => ['usu'],
  'University of Airlangga' => ['unair'],
  'University of California at Berkeley' => ['berkeley'],
  'University of Jember' => ['unej'],
  'University of Padjajaran' => ['unpad', 'padjadjaran'],
  'University of Porto' => ['cdup'],
  'University of Surabaya' => ['ubaya'],
  'University of Warsaw' => ['uw'],
  'Valahia University' => ['valahia'],
  'Wroclaw University of Science and Technology' => ['pwr'],
  'Yildiz Technical University' => ['ýtü']
);


sub set_hashes
{
  my ($method, $key) = @_;

  $method->(\@MULTI_WORDS, \%MULTI_TYPOS,
    \@SINGLE_WORDS, \%SINGLE_TYPOS, $key);
}

1;
