#!perl

package Email::Deletions;

use strict;
use warnings;
use v5.10;
use utf8;
use open ':std', ':encoding(UTF-8)';

use Exporter;

our @ISA = qw(Exporter);
our @EXPORT = qw($DELETIONS_HASH);

my @DELETIONS =
(
  '*_* ) @ kiss. com',
  '1 po @std.ca',
  '1100@mot.ingenting.urk',
  '111@111.111',
  '12345@.qq',
  '123stop@2/4nt.3/5suit',
  '1@2.3',
  '2/1@modern.approach',
  '2/1@playurcard.gl',
  '2/1@playurcard.per agre pl',
  '2/1@playurcard.per agreemt',
  '2/1@playurcard.ykeycard',
  '2/1@sayc.precision.wj.ns',
  '2/1gf@play your card.gl',
  '22@acacia.avenue',
  '2d&3d.ath@bbo.imps',
  '2maj@retraite.sud ouest',
  '3@14159.26535',
  '3rd palm tree on left@oasis.com',
  '3st@asvezes.com.elas',
  '50suckfor@hi.lie',
  '7@wad.t',
  '8030 @ precision..also..ok',
  '@  :) .com',
  '@ :) :) . com',
  'a.b@com',
  'a.volte,gioco@da.umano',
  'a@a.aa',
  'a@b.c',
  'aaa@aa.aa',
  'aaa@aaa.aaa',
  'aaa@bbb.ccc',
  'aaa@ss.cr',
  'aaaaa@nie.mam',
  'abc @ .com',
  'abc1979@263.nec',
  'abcd@def.online',
  'abcdefg@hijk.lmnop',
  'akqj.1098@765.432',
  'akqj.1098@7654.321',
  'akuntotribe@king.com.sz',
  'albatross@fore.put',
  'allezv@quand.mm',
  'amirom2@good.score',
  'amurang@jbot.jo',
  'andy@askme.dot',
  'anywhere@no.where',
  'aplictou@.barre',
  'appo@sorry.boom',
  'aquabulle@hautmer.oc',
  'arctic@ex.mexicogulfen',
  'ask @whois.me',
  'ask me@.comcast',
  'ask.me@if.required',
  'ask@email.emi',
  'astr.@voyager.fed',
  'ateþ@03.10.2014',
  'away@from.kom',
  'aytekin.@hotmail',
  'b@wp.p',
  'babbo@a.spass',
  'bad.attitude@let.home',
  'batco@ batco.comt',
  'bbo@experts.fun',
  'be nice@popp.su',
  'bernard@bonnehumeur.cool',
  'bestdummy@award.ok',
  'better let@.as net',
  'bibi@fricotin.jm',
  'bidlousy@playworse.twit',
  'big zero @yahoo.com',
  'billonline@billschmidt.ws',
  'birisi@hot.hot',
  'bisc@rosse.pin',
  'bob @hotmail.cm',
  'bonnehumeur@niania.hein',
  'bonsoir@tous.hi',
  'bornfree @ bridge.com',
  'boson@quark.bottom',
  'bovik@c2i.nett',
  'breakfast@tiffany.hepburn',
  'bridge&bridge@slam.rc',
  'bridge@magic.ms',
  'bridgeking @sky.com',
  'burning_spear@kingston.town',
  'bush bush@hotmail.com',
  'caeces @g.mail',
  'calimero@oeuf.dur',
  'camicidelbridgeonl. b@b',
  'can @can.com',
  'canary@yahoo.pal2',
  'carpe diem@bbo.com',
  'cemyavuz..@gmailfalan',
  'chakaay @ bridge.com',
  'cheeky@bom.bom',
  'colaps@brain.mu',
  'cold@foggy.north',
  'colorado@mens.colx.pukz',
  'constant sleeper@.yes',
  'cor@cor.mex',
  'crayon@sz.cm',
  'dammilatua@ grazie.smack',
  'dark.side@the.moon',
  'dddd @ aol.com',
  'denagne@jaas.hotmail',
  'devs43binbash@msn.live',
  'dianelamail.ca@ho',
  'diego.maratona@napoli.fc',
  'directorcovertops@cia.gov',
  'dirmou@dirmou.dirmou',
  'discrak@com.mon',
  'divirtam-se...@bridge',
  'do.not@fooled.yourself',
  'doctors@hotmail.pan',
  'don@don.don',
  'don\'t worry@be happy.com',
  'don\'t@have.one',
  'dontberude@bridge.table',
  'dorla @.com',
  'dot@dot.dot',
  'dukkwai@kaokog.grean',
  'duss man.@. quasi',
  'dz43@g.rr',
  'e-chisela@ricorda.boh',
  'e.m.preventionformation@gmail',
  'eagle@19th hole.com',
  'edjoetex@bad_man.ini.oom',
  'egmby@kwa.kwa',
  'ehehehhehe@acc.lol',
  'eiffel_bbo@net.od',
  'eiste@arnia.mpe',
  'elis@...elis',
  'end.of@the.line',
  'enjoy your life @life.com',
  'enjoy@table.now',
  'errare @humanum.est',
  'ex@bogus.dom',
  'expert is@relative.com',
  'expert@spectat.or',
  'f.@.france 2010',
  'f@ belly.go please',
  'fake0@terra.cl1d try 4 cards jacoby',
  'fb.groups@611141115596333',
  'fbear@sesame.street',
  'fff@hgh.mo',
  'fi @gama. dus elklae ba',
  'fioribosco@oklaoma.pass',
  'fishusa@lake.fish',
  'format_internet:@dos.prompt',
  'fors@le.10k',
  'frag.doch@einfach.mal',
  'francois.dell@cherie',
  'friendly@bridge.table',
  'friends:winbeerclub@freeland.star',
  'fromrussia@blow.out',
  'fuel@gasoline.oil',
  'furia@wj.2011',
  'ga@the office.org',
  'gama@neutron.space',
  'gattoromeo@dercolosseo.rm',
  'ggye_eto@ulica_ggye_eto.dom',
  'gingersnaps in oven@tx.com',
  'glass@straw.drink',
  'gnaro@sam.oyi',
  'gs @ uefa.com',
  'guatemalafeliz@.gt',
  'guess@who.i.am',
  'half@stoned.jam',
  'handsome@nighttime.wow',
  'hanneke is nooit thuis@nietthuis.com',
  'have a laugh @fun.ie',
  'henry@bbo.go.blog',
  'here i am@nowhere.com',
  'hgfgh@h.c',
  'hogsmeadehogwarts@diagon.alley.brw',
  'hoss@cartwright.ranch',
  'hv@ank.mp',
  'hx_xh@hummingbird.gm',
  'i love womans@mauri.com',
  'i love you@perfectman.com',
  'i love@ big .ziz',
  'i love@ whale.com',
  'i use.rule.of.20@opening',
  'i. love.c@ndroz',
  'i.am@not.yet',
  'i.play@with.friends',
  'i@am.lar',
  'ica @gmail.comp',
  'iespert @ balta.bbo',
  'if tomorrow never comes@carpediem.com',
  'if@you.asking',
  'ifnecessary@giganet.com.uc',
  'in vino@veritas.com',
  'info@basat.sigorta',
  'info@top-secret.cc',
  'intello@intello.net.mars',
  'inv.minor@invit.stenberg',
  'invinoveritas@pauillac.medoc',
  'it hurts@doctor.com',
  'jack_d@martell.chivas',
  'jamasc@yss.abby.bc',
  'jc.ctb@mls.nc',
  'jereno@jjkmn.txy.ney',
  'jirka.beda@seznam.z',
  'joesa@coc.vv',
  'johary@iowteleecom.nt',
  'johnny@dime.bags',
  'kartolo_main@bridge.cak',
  'keep cool@just for.fun',
  'kindness@pls.ty',
  'kiosape@tin.eger',
  'kk@bridge.va',
  'know@little.2over1',
  'kop_napkoro@gorki.ltv',
  'ksk@35 1/2.com',
  'kusch@mein.tuches',
  'l.m.@.s.f',
  'lage tuk na hole tak@hauhau.co',
  'lazzi .@.abv',
  'learner@bridgebase.online',
  'ledod.moshe@hayta.para',
  'leszek b. 20 yrs after @-ask',
  'licenza.vincere@cosa.nostra.va',
  'light@defense.bids',
  'liverpool@rbk.ncc',
  'll@.swoosh.gnou',
  'lm@us.nat.chump',
  'lol@yahoo.com, learn to be an',
  'lolol@lol.lol',
  'love & peace @.com',
  'love@bridge.play',
  'luzon@luzon.efo.damari',
  'm uta.... be nice@smile',
  'm.karadenizli@bafra-samsun',
  'ma mgorumna@vaskiriskuri.vor',
  'magnagatti@noteacher.pls',
  'marie concots @.com',
  'me and you@bbo.bridge',
  'me.addiction@bridge.bbo',
  'me.in.cellar@home',
  'men@mars.planet',
  'mgb123@interlink.net.ve',
  'miaumiau@miau.miau',
  'michaels@capp.neg x',
  'mickaels@landy.roudy',
  'mihuho@hanoi.viet',
  'mir@tour.eiffel',
  'misplay@ndmisdefense.all',
  'miss you @hotmail.com',
  'miss.defence@everydeal',
  'mistakes ok but not@silly.com',
  'miyabi@ official tv patner.com',
  'mmm@mm.m',
  'mniej@niz.zero',
  'muaie@.ihuaie',
  'nacht-squawk@game.bb0',
  'nebillerd.@com',
  'nex@glumi.ml',
  'nice. guy@sky',
  'nihilist@hedonist.komns',
  'no  @no.com',
  'no answer.not@computer',
  'no critic @ no. press.me',
  'no transfer@return lead.com',
  'no@lessons.pls',
  'none@available.yet',
  'none@nothinghere.goaway',
  'none@your.biz',
  'normally i play like@expert.com',
  'notaliban@coldmail.fin',
  'notsogood@carding.c0m/copycat',
  'novarro@novarro.novarro',
  'now everyone can fly@air asia.com',
  'number@4.om',
  'o cabaret@y.com',
  'oil@engine.camshaft',
  'ok@prec.zr',
  'ola.hello@be.nice.lol',
  'old-trafford@manchester.utd',
  'oliba@toxicplanet.info',
  'open@11,transf,stayman,blkwood,void-3pts.single-2',
  'ors@telli.cors',
  'p uta.... be nice@smile',
  'pal@met.pit',
  'pan@libero.son',
  'paopao60@libbero.carcere',
  'papa@griffins.hog',
  'papu@bps.statistics',
  'paradiso@con.me',
  'per.asper@aster.x',
  'peru@vazzafest.org(ia',
  'petak@umpet.1234',
  'philou@bouleto.21',
  'pilar@t.c',
  'pls.no.lessons@fed.up',
  'poc@kom.u',
  'poker p@s.admis',
  'poor.judgement @goingdown.com',
  'ppp@ppp.ppp',
  'prec.sayc.2/1@stdcrdg.lav',
  'president@whitehouse.gov',
  'prof_imp@proffesor.imp',
  'provis@cdickens.lit',
  'quark.bottom@boson.higgs',
  'qwertyuiop@asdfghjkl.zxcvbnm',
  'rdiederi@access.k12.wv',
  'reve@. cool',
  'roaring@to.go',
  'rootbeer@drunk.ex',
  'round table@camelot.com',
  'rt_championship@gtbc_010.cuk',
  'rue@griffin.club',
  's t.c.dr.s_@lp',
  's.b.@glenelg,s.a',
  's.c.@com.tc',
  's.snape@slytherin.hogwarts.ac',
  'salem.m@ss',
  'sb28ed@edu.dom',
  'sbocchi@latazza.team',
  'scorta@caelum.un',
  'sef.@ variante cote d\'azur',
  'self expart@bridgelove.com',
  'serious player@bbo.com',
  'seru@bezeqint.nrt',
  'shi.khan@saint.gleton',
  'shogan@hotmail.j',
  'slitherin@hogwarts.magic',
  'small@card.enf',
  'smile@don\'t worry.happy',
  'smile@ny.time',
  'so very much in love@pipit.com',
  'sometime@some.ware',
  'sorry p.npp.@grrrrrrrrrrr',
  'sourires@carpe diem.smile',
  'sp@wdo.gl',
  'srnsn@hlm.sw',
  'sss@hotmail.com van',
  'stel66@.manikin-a',
  'suckmy@sshole.pk',
  'surf@itte.her',
  'svy@bridgewater.nj',
  'swand.wan007@pop3altohiway.comoiway',
  'synpathy!@friends.rsm',
  'targeted@teammate.go',
  'td@dev.null',
  'team@bridge.ffb',
  'tendoltst@jaas.hotmail',
  'texas@norris.chu',
  'the  queen  @ hot.com',
  'theatreofdreams@old.trafford',
  'theverybest@i am hot.com',
  'think_distribution@alltimes.glp',
  'thoroughbred horse@saudi.com',
  'tibet free @ will.com',
  'tifon@.con',
  'tinlifemaster@smile.dot',
  'tj@ms.wd',
  'trabbi@go.ddr',
  'tritamaroni@stenersi.ebasta',
  'true.love@benin.co.bn',
  'try 2 play good bridge@bbo.com',
  'tulip@florist.yahoo',
  'turnip@baldrick.cunningplan',
  'vada@vialk.u',
  'val.lukasz@intex',
  'vallyrios@ritmo.pan',
  'veladose@sietebone.forse',
  'victim@you.all.are',
  'violet.violet.@ gmail.com',
  'w.earp@tombstone.ww',
  'waiting@planet.earth',
  'walletsize@global.space',
  'way.up.in.harlem@a.table.4.2',
  'weakest@player.bbo',
  'why@ pityme.com',
  'wild.animal@large-look.out',
  'winds of light@fun.live.com',
  'wj05@sayc.o/o_2/4_102',
  'wk@wp.td-ns6',
  'wonderwoman@dany.extra',
  'worldclass@dream.ok',
  'wpieriod@gru.rus',
  'www.health@safety a class',
  'www.thaynet@yahhoo',
  'x carrier pilot@aol.com',
  'x,xx@gesthem.lebensohl,multilandy',
  'xolaria@ y.com',
  'xunpd.@com',
  'xxx.@ .no',
  'xyzt@acus.sic',
  'y @hotmail.com',
  'yes@i.do',
  'yes@i.have',
  'ynwa@.annfield.lfc',
  'ynwa@liverpool. forever',
  'your friendlypartner@it only bytes.com',
  'z+p@p.x',
  'zen@kool.ctou',
  'ziya@usa.aol',
  'zo0clitor"s @y.com',
  'zzzzzzz @hotmail.com',
);

our $DELETIONS_HASH = { map { $_ => 1 } @DELETIONS };

1;
