#!perl

package Email::Domains;

use strict;
use warnings;
use v5.10;
use utf8;
use open ':std', ':encoding(UTF-8)';

use Exporter;

our @ISA = qw(Exporter);
our @EXPORT = qw(regex);

my %DOMAINS =
(
  '126.com' => 'China',
  '139.com' => 'China',
  '163.com' => 'China',
  'abv.bg' => 'Bulgaria',
  'ac.cn' => 'China',
  'ac.il' => 'Israel',
  'ac.uk' => 'United Kingdom',
  ae => 'United Arab Emirates',
  af => 'Afghanistan',
  ag => 'Antigua and Barbuda',
  'alice.it' => 'Italy',
  'aliceadsl.fr' => 'France',
  ai => 'Anguilla',
  am => 'Armenia',
  an => 'Netherlands Antilles',
  'aol.com' => '',
  ar => 'Argentina',
  as => 'American Samoa',
  at => 'Austria',
  au => 'Australia',
  'au.dk' => 'Denmark',
  'autograf.pl' => 'Poland',
  bd => 'Bangladesh',
  be => 'Belgium',
  bg => 'Bulgaria',
  bh => 'Bahrain',
  'bigpond.com' => '',
  biz => '',
  'biz.pl' => 'Poland',
  bl => '',
  'bluewin.ch' => 'Switzerland',
  bm => 'Bermuda',
  bn => 'Brunei',
  bo => 'Bolivia',
  br => 'Brazil',
  'bridgebase.com' => '',
  'btinternet.com' => 'Great Britain',
  by => 'Belarus',
  ca => 'Canada',
  'camargue.fr' => 'France',
  cat => 'Spain',
  cc => '',
  'cea.fr' => 'France',
  ch => 'Switzerland',
  cl => 'Chile',
  'club-internet.fr' => 'France',
  cn => 'China',
  co => '',
  'co.id' => 'Indonesia',
  'co.il' => 'Israel',
  'co.in' => 'India',
  'co.jp' => 'Japan',
  'co.nz' => 'New Zealand',
  'co.uk' => 'United Kingdom',
  'co.za' => 'South Africa',
  'columbia.edu' => 'United States',
  com => '',
  'comcast.net' => '',
  'com.ar' => 'Argentina',
  'com.au' => 'Australia',
  'com.bo' => 'Bolivia',
  'com.br' => 'Brazil',
  'com.cn' => 'China',
  'com.cy' => 'Cyprus',
  'com.hk' => 'Hong Kong',
  'com.pk' => 'Pakistan',
  'com.pl' => 'Poland',
  'com.tr' => 'Turkey',
  'com.tw' => 'Taiwan',
  cr => 'Costa Rica',
  cz => 'Czech Republic',
  cy => 'Cyprus',
  de => 'Germany',
  edu => '',
  'edu.cn' => 'China',
  'edu.tr' => 'Turkey',
  ee => 'Estonia',
  eg => 'Egypt',
  'elte.hu' => 'Hungary',
  es => 'Spain',
  eu => '',
  fi => 'Finland',
  fm => '',
  fo => 'Faroe Islands',
  fr => 'France',
  'free.fr' => 'France',
  'fsnet.co.uk' => 'United Kingdom',
  'gazeta.pl' => 'Poland',
  ge => 'Georgia',
  'gmail.com' => '',
  'go2.pl' => 'Poland',
  'googlemail.com' => '',
  gov => '',
  'gov.in' => 'India',
  gr => 'Greece',
  'hbs.edu' => 'United States',
  hk => 'Hong Kong',
  'hotmail.co.uk' => 'United Kingdom',
  'hotmail.com' => '',
  'hotmail.fr' => 'France',
  'hotmail.it' => 'Italy',
  hr => 'Croatia',
  hu => 'Hungary',
  id => 'Indonesia',
  ie => 'Ireland',
  il => 'Israel',
  in => 'India',
  info => '',
  'interia.pl' => 'Poland',
  is => 'Iceland',
  it => 'Italy',
  jo => 'Jordan',
  jp => 'Japan',
  kg => 'Kyrgyzstan',
  kr => 'South Korea',
  ku => 'Turkey',
  kz => 'Kazakhstan',
  la => 'Laos',
  'laposte.net' => 'France',
  lb => 'Lebanon',
  lc => 'Saint Lucia',
  li => 'Liechtenstein',
  'libero.it' => 'Italy',
  'libertysurf.fr' => 'France',
  'live.fr' => 'France',
  lk => 'Sri Lanka',
  ls => 'Lesotho',
  lt => 'Lithuania',
  lu => 'Luxembourg',
  lv => 'Latvia',
  ma => 'Morocco',
  mc => 'Monaco',
  me => 'Montenegro',
  'mindspring.com' => '',
  'mit.edu' => 'United States',
  mk => 'North Macedonia',
  'msn.com' => '',
  mu => 'Mauritius',
  mx => 'Mexico',
  'mynet.com' => 'Turkey',
  'mynet.com.tr' => 'Turkey',
  mz => 'Mozambique',
  na => 'Namibia',
  name => '',
  'ncu.edu.tw' => 'Taiwan',
  'neostrada.pl' => 'Poland',
  net => '',
  'net.cn' => 'China',
  'net.co' => '',
  'net.au' => 'Australia',
  'net.il' => 'Israel',
  'net.mx' => 'Mexico',
  'net.nz' => 'New Zealand',
  'net.pl' => 'Poland',
  'net.tr' => 'Turkey',
  'net.tw' => 'Taiwan',
  'neuf.fr' => 'France',
  ni => 'Nicaragua',
  nl => 'Netherlands',
  no => 'Norway',
  'noos.fr' => 'France',
  'ntlworld.com' => '',
  nu => '',
  'numericable.fr' => 'France',
  nz => 'New Zealand',
  'o2.pl' => 'Poland',
  'onet.pl' => 'Poland',
  'online.no' => 'Norway',
  'op.pl' => 'Poland',
  'orange.fr' => 'France',
  'orange.pl' => 'Poland',
  org => '',
  'org.tr' => 'Turkey',
  'outlook.com' => '',
  pe => 'Peru',
  pf => 'French Polynesia',
  ph => 'Philippines',
  pk => 'Pakistan',
  pl => 'Poland',
  'planet.nl' => 'Netherlands',
  'post.pl' => 'Poland',
  pt => 'Portugal',
  py => 'Paraguay',
  'qq.com' => 'China',
  'rediffmail.com' => 'India',
  ro => 'Romania',
  'rocketmail.com' => '',
  'rogers.com' => 'Canada',
  'rr.com' => '',
  rs => 'Serbia',
  ru => 'Russia',
  sa => 'Saudi Arabia',
  se => 'Sweden',
  'se.net' => 'Sweden',
  'sfr.fr' => 'France',
  sg => 'Singapore',
  si => 'Slovenia',
  'sina.cn' => 'China',
  'sina.com' => 'China',
  sk => 'Slovakia',
  sm => 'San Marino',
  'sohu.com' => 'China',
  st => '',
  su => '',
  'sympatico.ca' => 'Canada',
  'tele.dk' => 'Denmark',
  'telefonica.net' => '',
  'telia.com' => 'Sweden',
  th => 'Thailand',
  'tiscali.fr' => 'France',
  'tiscali.it' => 'Italy',
  'tlen.pl' => 'Poland',
  tn => 'Tunisia',
  'tom.com' => 'China',
  tr => 'Turkey',
  tt => 'Trinidad and Tobago',
  tv => '',
  tw => 'Taiwan',
  ua => 'Ukraine',
  uk => 'United Kingdom',
  us => 'USA',
  uy => 'Uruguay',
  'voila.fr' => 'France',
  'vp.pl' => 'Poland',
  vu => 'Vanuatu',
  'walla.com' => 'Israel',
  'wanadoo.fr' => 'France',
  'windowslive.com' => '',
  world => '',
  'wp.pl' => 'Poland',
  'yahoo.ca' => 'Canada',
  'yahoo.co.id' => 'Indonesia',
  'yahoo.co.in' => 'India',
  'yahoo.co.uk' => 'United Kingdom',
  'yahoo.com' => '',
  'yahoo.fr' => 'France',
  'yahoo.it' => 'Italy',
  'yahoo.pl' => 'Poland',
  'ymail.com' => '',
  yu => 'Yugoslavia',
  'zen.fr' => 'France',
  za => 'South Africa',
);

my $PATTERN = join '|',
  map { quotemeta } sort { length($b) <=> length($a) } keys %DOMAINS;

my $REGEX = qr/\A(.+?)([@.])($PATTERN)\z/i;


sub regex
{
  return $REGEX;
}


sub country
{
  my ($domain) = @_;
  warn "DOMAINERROR $domain" unless exists $DOMAINS{$domain};
  return $DOMAINS{$domain};
}


1;
