#!perl

package Email::Domains;

use strict;
use warnings;
use v5.10;
use utf8;
use open ':std', ':encoding(UTF-8)';

use Exporter;

our @ISA = qw(Exporter);
our @EXPORT = qw(regex);

my %DOMAINS =
(
  '126.com' => { COUNTRY => 'China', CHARSETS => [] },
  '139.com' => { COUNTRY => 'China', CHARSETS => [] },
  '163.com' => { COUNTRY => 'China', CHARSETS => [] },
  'abv.bg' => { COUNTRY => 'Bulgaria', CHARSETS => [] },
  'ac.uk' => { COUNTRY => 'United Kingdom', CHARSETS => [] },
  ae => { COUNTRY => 'United Arab Emirates', CHARSETS => [] },
  af => { COUNTRY => 'Afghanistan', CHARSETS => [] },
  ag => { COUNTRY => 'Antigua and Barbuda', CHARSETS => [] },
  'alice.it' => { COUNTRY => 'Italy', CHARSETS => [] },
  ai => { COUNTRY => 'Anguilla', CHARSETS => [] },
  am => { COUNTRY => 'Armenia', CHARSETS => [] },
  an => { COUNTRY => 'Netherlands Antilles', CHARSETS => [] },
  'aol.com' => { COUNTRY => '', CHARSETS => [] },
  ar => { COUNTRY => 'Argentina', CHARSETS => [] },
  as => { COUNTRY => 'American Samoa', CHARSETS => [] },
  at => { COUNTRY => 'Austria', CHARSETS => [] },
  au => { COUNTRY => 'Australia', CHARSETS => [] },
  bd => { COUNTRY => 'Bangladesh', CHARSETS => [] },
  be => { COUNTRY => 'Belgium', CHARSETS => [] },
  bg => { COUNTRY => 'Bulgaria', CHARSETS => [] },
  bh => { COUNTRY => 'Bahrain', CHARSETS => [] },
  'bigpond.com' => { COUNTRY => '', CHARSETS => [] },
  biz => { COUNTRY => '', CHARSETS => [] },
  bl => { COUNTRY => 'Saint Barthélemy', CHARSETS => [] },
  'bluewin.ch' => { COUNTRY => 'Switzerland', CHARSETS => [] },
  bm => { COUNTRY => 'Bermuda', CHARSETS => [] },
  bn => { COUNTRY => 'Brunei', CHARSETS => [] },
  bo => { COUNTRY => 'Bolivia', CHARSETS => [] },
  br => { COUNTRY => 'Brazil', CHARSETS => [] },
  'bridgebase.com' => { COUNTRY => '', CHARSETS => [] },
  'btinternet.com' => { COUNTRY => 'Great Britain', CHARSETS => [] },
  by => { COUNTRY => 'Belarus', CHARSETS => [] },
  ca => { COUNTRY => 'Canada', CHARSETS => [] },
  cat => { COUNTRY => 'Spain', CHARSETS => [] },
  cc => { COUNTRY => '', CHARSETS => [] },
  ch => { COUNTRY => 'Switzerland', CHARSETS => [] },
  cl => { COUNTRY => 'Chile', CHARSETS => [] },
  cn => { COUNTRY => 'China', CHARSETS => [] },
  co => { COUNTRY => '', CHARSETS => [] },
  'co.za' => { COUNTRY => 'South Africa', CHARSETS => [] },
  com => { COUNTRY => '', CHARSETS => [] },
  'comcast.net' => { COUNTRY => '', CHARSETS => [] },
  'com.tr' => { COUNTRY => 'Turkey', CHARSETS => [] },
  'com.tw' => { COUNTRY => 'Taiwan', CHARSETS => [] },
  cr => { COUNTRY => 'Costa Rica', CHARSETS => [] },
  cz => { COUNTRY => 'Czech Republic', CHARSETS => [] },
  cy => { COUNTRY => 'Cyprus', CHARSETS => [] },
  de => { COUNTRY => 'Germany', CHARSETS => [] },
  dk => { COUNTRY => 'Denmark', CHARSETS => [] },
  edu => { COUNTRY => '', CHARSETS => [] },
  ee => { COUNTRY => 'Estonia', CHARSETS => [] },
  eg => { COUNTRY => 'Egypt', CHARSETS => [] },
  es => { COUNTRY => 'Spain', CHARSETS => [] },
  eu => { COUNTRY => '', CHARSETS => [] },
  fi => { COUNTRY => 'Finland', CHARSETS => [] },
  fm => { COUNTRY => '', CHARSETS => [] },
  fo => { COUNTRY => 'Faroe Islands', CHARSETS => [] },
  fr => { COUNTRY => 'France', CHARSETS => [] },
  ge => { COUNTRY => 'Georgia', CHARSETS => [] },
  'gmail.com' => { COUNTRY => '', CHARSETS => [] },
  'googlemail.com' => { COUNTRY => '', CHARSETS => [] },
  gov => { COUNTRY => '', CHARSETS => [] },
  gr => { COUNTRY => 'Greece', CHARSETS => [] },
  hk => { COUNTRY => 'Hong Kong', CHARSETS => [] },
  'hotmail.com' => { COUNTRY => '', CHARSETS => [] },
  'hotmail.fr' => { COUNTRY => 'France', CHARSETS => [] },
  hr => { COUNTRY => 'Croatia', CHARSETS => [] },
  hu => { COUNTRY => 'Hungary', CHARSETS => [] },
  id => { COUNTRY => 'Indonesia', CHARSETS => [] },
  ie => { COUNTRY => 'Ireland', CHARSETS => [] },
  il => { COUNTRY => 'Israel', CHARSETS => [] },
  info => { COUNTRY => '', CHARSETS => [] },
  is => { COUNTRY => 'Iceland', CHARSETS => [] },
  it => { COUNTRY => 'Italy', CHARSETS => [] },
  in => { COUNTRY => 'India', CHARSETS => [] },
  jo => { COUNTRY => 'Jordan', CHARSETS => [] },
  jp => { COUNTRY => 'Japan', CHARSETS => [] },
  kg => { COUNTRY => 'Kyrgyzstan', CHARSETS => [] },
  kr => { COUNTRY => 'South Korea', CHARSETS => [] },
  ku => { COUNTRY => 'Turkey', CHARSETS => [] },
  kz => { COUNTRY => 'Kazakhstan', CHARSETS => [] },
  la => { COUNTRY => 'Laos', CHARSETS => [] },
  'laposte.net' => { COUNTRY => 'France', CHARSETS => [] },
  lb => { COUNTRY => 'Lebanon', CHARSETS => [] },
  lc => { COUNTRY => 'Saint Lucia', CHARSETS => [] },
  li => { COUNTRY => 'Liechtenstein', CHARSETS => [] },
  'libero.it' => { COUNTRY => 'Italy', CHARSETS => [] },
  lk => { COUNTRY => 'Sri Lanka', CHARSETS => [] },
  ls => { COUNTRY => 'Lesotho', CHARSETS => [] },
  lt => { COUNTRY => 'Lithuania', CHARSETS => [] },
  lu => { COUNTRY => 'Luxembourg', CHARSETS => [] },
  lv => { COUNTRY => 'Latvia', CHARSETS => [] },
  ma => { COUNTRY => 'Morocco', CHARSETS => [] },
  mc => { COUNTRY => 'Monaco', CHARSETS => [] },
  me => { COUNTRY => 'Montenegro', CHARSETS => [] },
  'mindspring.com' => { COUNTRY => '', CHARSETS => [] },
  mk => { COUNTRY => 'North Macedonia', CHARSETS => [] },
  'msn.com' => { COUNTRY => '', CHARSETS => [] },
  mu => { COUNTRY => 'Mauritius', CHARSETS => [] },
  mx => { COUNTRY => 'Mexico', CHARSETS => [] },
  'mynet.com' => { COUNTRY => 'Turkey', CHARSETS => qw(windows-1254) },
  'mynet.com.tr' => { COUNTRY => 'Turkey', CHARSETS => qw(windows-1254) },
  mz => { COUNTRY => 'Mozambique', CHARSETS => [] },
  na => { COUNTRY => 'Namibia', CHARSETS => [] },
  name => { COUNTRY => '', CHARSETS => [] },
  net => { COUNTRY => '', CHARSETS => [] },
  'net.il' => { COUNTRY => 'Israel', CHARSETS => [] },
  ni => { COUNTRY => 'Nicaragua', CHARSETS => [] },
  nl => { COUNTRY => 'Netherlands', CHARSETS => [] },
  no => { COUNTRY => 'Norway', CHARSETS => [] },
  'ntlworld.com' => { COUNTRY => '', CHARSETS => [] },
  nu => { COUNTRY => '', CHARSETS => [] },
  nz => { COUNTRY => 'New Zealand', CHARSETS => [] },
  'onet.pl' => { COUNTRY => 'Poland', CHARSETS => [] },
  'orange.fr' => { COUNTRY => 'France', CHARSETS => [] },
  'orange.pl' => { COUNTRY => 'Poland', CHARSETS => [] },
  org => { COUNTRY => '', CHARSETS => [] },
  'outlook.com' => { COUNTRY => '', CHARSETS => [] },
  pe => { COUNTRY => 'Peru', CHARSETS => [] },
  pf => { COUNTRY => 'French Polynesia', CHARSETS => [] },
  ph => { COUNTRY => 'Philippines', CHARSETS => [] },
  pk => { COUNTRY => 'Pakistan', CHARSETS => [] },
  pl => { COUNTRY => 'Poland', CHARSETS => [] },
  'planet.nl' => { COUNTRY => 'Netherlands', CHARSETS => [] },
  pt => { COUNTRY => 'Portugal', CHARSETS => [] },
  py => { COUNTRY => 'Paraguay', CHARSETS => [] },
  'qq.com' => { COUNTRY => 'China', CHARSETS => [] },
  'rediffmail.com' => { COUNTRY => 'India', CHARSETS => [] },
  ro => { COUNTRY => 'Romania', CHARSETS => [] },
  'rocketmail.com' => { COUNTRY => '', CHARSETS => [] },
  'rogers.com' => { COUNTRY => 'Canada', CHARSETS => [] },
  'rr.com' => { COUNTRY => '', CHARSETS => [] },
  rs => { COUNTRY => 'Serbia', CHARSETS => [] },
  ru => { COUNTRY => 'Russia', CHARSETS => [] },
  sa => { COUNTRY => 'Saudi Arabia', CHARSETS => [] },
  se => { COUNTRY => 'Sweden', CHARSETS => [] },
  sg => { COUNTRY => 'Singapore', CHARSETS => [] },
  si => { COUNTRY => 'Slovenia', CHARSETS => [] },
  'sina.cn' => { COUNTRY => 'China', CHARSETS => [] },
  'sina.com' => { COUNTRY => 'China', CHARSETS => [] },
  sk => { COUNTRY => 'Slovakia', CHARSETS => [] },
  sm => { COUNTRY => 'San Marino', CHARSETS => [] },
  'sohu.com' => { COUNTRY => 'China', CHARSETS => [] },
  st => { COUNTRY => 'São Tomé and Príncipe', CHARSETS => [] },
  su => { COUNTRY => '', CHARSETS => [] },
  'telefonica.net' => { COUNTRY => '', CHARSETS => [] },
  'telia.com' => { COUNTRY => 'Sweden', CHARSETS => [] },
  th => { COUNTRY => 'Thailand', CHARSETS => [] },
  'tiscali.it' => { COUNTRY => 'Italy', CHARSETS => [] },
  tn => { COUNTRY => 'Tunisia', CHARSETS => [] },
  'tom.com' => { COUNTRY => 'China', CHARSETS => [] },
  tr => { COUNTRY => 'Turkey', CHARSETS => qw(windows-1254) },
  tt => { COUNTRY => 'Trinidad and Tobago', CHARSETS => [] },
  tv => { COUNTRY => '', CHARSETS => [] },
  tw => { COUNTRY => 'Taiwan', CHARSETS => [] },
  ua => { COUNTRY => 'Ukraine', CHARSETS => [] },
  uk => { COUNTRY => 'United Kingdom', CHARSETS => [] },
  us => { COUNTRY => 'USA', CHARSETS => [] },
  uy => { COUNTRY => 'Uruguay', CHARSETS => [] },
  vu => { COUNTRY => 'Vanuatu', CHARSETS => [] },
  'walla.com' => { COUNTRY => 'Israel', CHARSETS => [] },
  'wanadoo.fr' => { COUNTRY => 'France', CHARSETS => [] },
  'windowslive.com' => { COUNTRY => '', CHARSETS => [] },
  world => { COUNTRY => '', CHARSETS => [] },
  'wp.pl' => { COUNTRY => 'Poland', CHARSETS => [] },
  'yahoo.ca' => { COUNTRY => 'Canada', CHARSETS => [] },
  'yahoo.com' => { COUNTRY => '', CHARSETS => [] },
  'yahoo.pl' => { COUNTRY => 'Poland', CHARSETS => [] },
  'ymail.com' => { COUNTRY => '', CHARSETS => [] },
  yu => { COUNTRY => 'Yugoslavia', CHARSETS => [] },
  za => { COUNTRY => 'South Africa', CHARSETS => [] },
);

my $PATTERN = join '|',
  map { quotemeta } sort { length($b) <=> length($a) } keys %DOMAINS;

my $REGEX = qr/\A(.+?[@.])($PATTERN)\z/i;


sub regex
{
  return $REGEX;
}

1;
