#!perl

package Email::Multiples;

use strict;
use warnings;
use v5.10;
use utf8;
use open ':std', ':encoding(UTF-8)';

use Exporter;

our @ISA = qw(Exporter);
our @EXPORT = qw($MULTIPLES_HASH);

my %MULTIPLES =
(
  '0272244@fudan.edu.c' => [ EMAIL => '0272244@fudan.edu.cn' ],
  '05353olgierd.rb@gmail.com' => [ EMAIL => 'olgierd.rb@gmail.com' ],
  '13875318390@163.con' => [ EMAIL => '13875318390@163.com' ],
  '2/1sapanca@hotmail.com' => [ EMAIL => 'sapanca@hotmail.com' ],
  '2/1@paragragh22.com' => [ SYSTEM => '2/1@paragragh22.com' ],
  '2/1gf@km.com' => [ SYSTEM => '2/1gf@km.com' ],
  '2didierthomazet@aol.com' => [ EMAIL => 'didierthomazet@aol.com' ],
  '3didierthomazet@aol.com' => [ EMAIL => 'didierthomazet@aol.com' ],
  '3pik@wp.pl5606' => [ EMAIL => '3pik@wp.pl' ],
  '505394947@qq.c' => [ EMAIL => '505394947@qq.com' ],
  '6egil(egil@nerheim.nu' => [ OPEN => 'Egil', EMAIL => 'egil@nerheim.nu' ],
  '798686368@.qq.com' => [ EMAIL => '798686368@qq.com' ],
  '7didierthomazet@aol.com' => [ EMAIL => 'didierthomazet@aol.com' ],
  '87362535@qq.ocm' => [ EMAIL => '87362535@qq.com' ],
  '88@yaman.com2breslau' => [ EMAIL => '88@yaman.com', CITY => 'Wroclaw', COUNTRY => 'Poland' ],
  '8didierthomazet@aol.com' => [ EMAIL => 'didierthomazet@aol.com' ],
  '_*)dan0ana@yahoo.com' => [ EMAIL => '_*)dan0ana@yahoo.com' ],
  'a.frietema@upcmail.nll' => [ EMAIL => 'a.frietema@upcmail.nl' ],
  'abe@iki.fi,livingingermany' => [ EMAIL => 'abe@iki.fi', COUNTRY => 'Germany' ],
  'addy.tex@wanadoo.dr' => [ EMAIL => 'addy.tex@wanadoo.fr' ],
  'advanced++@abv.bg' => [ LEVEL => 'Advanced', COUNTRY => 'Bulgaria' ],
  'agusia74@poczta.onet' => [ EMAIL => 'agusia74@poczta.onet.pl' ],
  'ah.vandyk@sympatico/ca' => [ EMAIL => 'ah.vandyk@sympatico.ca' ],
  'ajay(28)bridgegoth@yahoo.fi' => [ OPEN => 'Jay', EMAIL => 'bridgegoth@yahoo.fi' ],
  'al1919@hotmail.fr' => [ EMAIL => 'al1919@hotmail.fr' ],
  'al@morglia.net-bboitalia' => [ EMAIL => 'al@morglia.net', COUNTRY => 'Italy' ],
  'alam@t.palsu.oom' => [ EMAIL => 'alam@t.palsu.com' ],
  'alex------@llibero.it' => [ EMAIL => 'alex@libero.it' ],
  'ali@ali.com' => [ OPEN => 'Ali' ],
  'alie_196616@yahoo.acom' => [ EMAIL => 'alie_196616@yahoo.com' ],
  'anna@anna.com' => [ OPEN => 'Anna' ],
  'antun.matana@optinet' => [ EMAIL => 'antun.matana@optinet.hr' ],
  'ap2410@ns.sympatico.can' => [ EMAIL => 'ap2410@ns.sympatico.ca' ],
  'aquapharm@hotmail.comstars' => [ EMAIL => 'aquapharm.hotmail.com' ],
  'associazionebridgepotenza@gmail.comb&b' => [ EMAIL => 'associazionebridgepotenza@gmail.com' ],
  'atayayaz@live.comp' => [ EMAIL => 'atayazaz@live.com' ],
  'avec.jac@mennecy' => [ CITY => 'Mennecy', COUNTRY => 'France' ],
  'ayik.dagci16@gmail' => [ EMAIL => 'ayik.dagci16@gmail.com' ],
  'b.holl@hccnet.nlheyasven(kramer' => [ EMAIL => 'b.holl@hccnet.nl' ],
  'bactriam@gmail.com16794' => [ EMAIL => 'bactriam@gmail.com' ],
  'badman@jahil.oom' => [ EMAIL => 'badman@jahil.com' ],
  'beniopszczola@o2.plolsztyn' => [ EMAIL => 'beniopszczola@o2.pl', CITY => 'Olsztyn', COUNTRY => 'Poland' ],
  'bevbernie@att.nett' => [ EMAIL => 'bevbernie@att.net' ],
  'bobr5555@yahoo.comcom' => [ EMAIL => 'bobr5555@yahoo.com' ],
  'bogdan1012@hotmail.com,ilacymember' => [ EMAIL => 'bogdan1012@hotmail.com' ],
  'bohdan.pliszka@op.plcezar8052' => [ EMAIL => 'bohdan.pliszka@op.pl' ],
  'bruno uno@hotmail.it' => [ EMAIL => 'bruno@hotmail.it' ],
  'bstitch562@hotmailc.om' => [ EMAIL => 'bstitch562@hotmail.com' ],
  'bulova@nyct.netlessonsavl' => [ EMAIL => 'bulova@nyct.net', LEVEL => 'Expert' ],
  'burdigala@port.de.la.lune' => [ CITY => 'Bordeaux', COUNTRY => 'France' ],
  'c/-admin@bilbridge.com' => [ EMAIL => 'admin@bilbridge.com' ],
  'canadadan@gmail.coma' => [ EMAIL => 'canadadan@gmail.com' ],
  'cangurcan48@hotmail.comtr' => [ EMAIL => 'cangurcan48@hotmail.com.tr' ],
  'carlaaprile52@libero.itivate' => [ EMAIL => 'carlaaprile52@libero.it' ],
  'carlcsc@yahoo.comglm' => [ EMAIL => 'carlcsc@yahoo.com glm', 'LEVEL' => 'Life Master' ],
  'cat_shit@hotmail.comnazilli' => [ CITY => 'Nazilli', COUNTRY => 'Turkey' ],
  'ccdr@dgfood.gov,bd' => [ EMAIL => 'ccdr@dgfood.gov.bd' ],
  'celavitali@gmail.coml' => [ EMAIL => 'celavitali@gmail.com' ],
  'cenver@msn.comtr' => [ EMAIL => 'cenver@msn.com.tr' ],
  'chb.langer@t-online' => [ EMAIL => 'chb.langer@t-online.de' ],
  'chicciola@chiocciolo.ino' => [ EMAIL => 'chicciola@chiocciolo.info' ],
  'cilegoncity@kota.com' => [ CITY => 'Cilegon', COUNTRY => 'Indonesia' ],
  'clpirro@tin.itilacymember' => [ EMAIL => 'clpirro@tin.it' ],
  'commbruggen@hotmail.come' => [ EMAIL => 'commbruggen@hotmail.com' ],
  'cpt64@free.frbiarritz' => [ EMAIL => 'cpt64@free.fr', CITY => 'Biarritz', COUNTRY => 'France' ],
  'crossft@gmail.com-8902023' => [ EMAIL => 'crossft@gmail.com' ],
  'dan@whoknows.com' => [ OPEN => 'Dan' ],
  'daniel.raimbault@wanadoo.frd' => [ EMAIL => 'daniel.raimbault@wanadoo.fr' ],
  'danmar@adinet.com.uy(uruguay' => [ EMAIL => 'danmar@adinet.com.uy' ],
  'dazuker@zahav.net/il' => [ EMAIL => 'dazuker@zahav.net.il' ],
  'de.luten@versatel,nl' => [ EMAIL => 'de.luten@versatel.nl' ],
  'delia.carotenuto@libero-it' => [ EMAIL => 'delia.carotenuto@libero.it' ],
  'diko65@abv.bg.kostenetc' => [ EMAIL => 'diko65@abv.bg', CITY => 'Kostenets', COUNTRY => 'Bulgaria' ],
  'dogustanexper@ahmetizm.xxx' => [ LEVEL => 'Expert' ],
  'donald.caton@yahoo' => [ EMAIL => 'donald.caton@yahoo.com' ],
  'drzaferjarrar@gmail.com  p' => [ EMAIL => 'drzaferjarrar@gmail.com' ],
  'dursunyildiz101@hotmail.comwww.major' => [ EMAIL => 'dursunyildiz101@hotmail.com' ],
  'e-mailmarkmassa@yahoo.com' => [ EMAIL => 'markmassa@yahoo.com' ],
  'e-mail:tadeusz.tan@interia.pl' => [ EMAIL => 'tadeusz.tan@interia.pl' ],
  'eat@vmg2.bekasi' => [ 'CITY' => 'Bekasi', COUNTRY => 'Indonesia' ],
  'erm19@juno.come' => [ EMAIL => 'erm19@juno.com' ],
  'expert.@.com' => [ LEVEL => 'Expert' ],
  'expert\'@expert.com' => [ LEVEL => 'Expert' ],
  'fantoine:tonino947@hotmail.com' => [ OPEN => 'Antoine', EMAIL => 'tonino947@hotmail.com' ],
  'fe@ugm.yk' => [ UNIVERSITY => 'Universitas Gadjah Mada', COUNTRY => 'Indonesia' ],
  'frami.laurence@orange.frl.' => [ EMAIL => 'frami.laurence@orange.fr' ],
  'francois.louis15@fr.sfr' => [ EMAIL => 'francois.louis15@sfr.fr' ],
  'franmo@gmail.comjunior' => [ OPEN => 'Junior', EMAIL => 'franmo@gmail.com' ],
  'frederic.lacroix@web.ffbridge' => [ EMAIL => 'frederic.lacroix@web.ffbridge.fr' ],
  'g.rosca@yahoo' => [ EMAIL => 'g.rosca@yahoo.bg' ],
  'g.virchick@verizon.net(boston' => [ CITY => 'Boston', COUNTRY => 'USA', EMAIL => 'g.virchick@verizon.net' ],
  'gabrielmassut@hotmail.comm' => [ EMAIL => 'gabrielmassut@hotmail.com' ],
  'gadigadischwartz1957@gmail.c' => [ EMAIL => 'gadischwartz1957@gmail.com' ],
  'gentingisland@yahoo.my.com' => [ REGION => 'Genting Highlands', COUNTRY => 'Malaysia' ],
  'gervais.arlette@wanadoow.fr' => [ EMAIL => 'gervais.arlette@wanadoo.fr' ],
  'gezi@bravosize.comtr' => [ EMAIL => 'gezo@bravosize.com.tr' ],
  'giasmpierodionigiregione@alice.it' => [ OPEN => 'Giampiero Dionigi', COUNTRY => 'Italy' ],
  'gilberto.figatalamanca@fastweb.neti' => [ EMAIL => 'gilberto.figatalamanca@fastwebnet.it' ],
  'giorggi@sawas.arg' => [ EMAIL => 'giorggi@sawas.ar' ],
  'gjay(29)bridgegoth@yahoo.fi' => [ OPEN => 'Jay', EMAIL => 'bridgegoth@yahoo.fi' ],
  'gjs@autograf.pl7725kraków' => [ EMAIL => 'gjs@autograf.pl', CITY => 'Krakow', COUNTRY => 'Poland' ],
  'glevin5228@aol.xim' => [ EMAIL => 'glevin5228@aol.com' ],
  'gosh59@abv.bg;sofiamladost1' => [ EMAIL => 'gosh59@abv.bg', CITY => 'Sofia', COUNTRY => 'Bulgaria' ],
  'goubet.hubert@wanadoo' => [ EMAIL => 'goubet.hubert@wanadoo.fr' ],
  'grasool1337@yahoo.c0m' => [ EMAIL => 'grasool1337@yahoo.com' ],
  'grb@taigabridge.net(bilhon.dementor' => [ EMAIL => 'grb@taigabridge.net' ],
  'gsanna35@hotmail.ittolclub' => [ EMAIL => 'gsanna35@hotmail.it' ],
  'guciogg@poczta.onet' => [ EMAIL => 'guciogg@poczta.onet.pl' ],
  'guiyotambella@yahoo.com,ar' => [ EMAIL => 'guiyotambella@yahoo.com.ar' ],
  'guy@warwick.hm' => [ CITY => 'Watford', COUNTRY => 'England' ],
  'haavard7355@msn.com.lowcard3-5hight' => [ EMAIL => 'haavard7355@msn.com' ],
  'hamdysimillawi@hotmail.comm' => [ EMAIL => 'hamdysimillawi@hotmail.com' ],
  'harry@bridge.com' => [ OPEN => 'Harry' ],
  'hehe@hehe.pl.wroclaw-raj' => [ CITY => 'Wroclaw', COUNTRY => 'Poland' ],
  'hel2004.kraus@t-online.e' => [ EMAIL => 'hel2004.kraus@t-online.de' ],
  'helko05@verizon.netvate' => [ EMAIL => 'helko05@verizon.net' ],
  'hexi5@yahoo.mail' => [ EMAIL => 'hexi5@yahoo.com' ],
  'hiae1@bezeqint.netl' => [ EMAIL => 'hiae1@bezeqint.net' ],
  'hsoysuren@hotmail.com-lebenshol' => [ EMAIL => 'hsoysuren@hotmail.com' ],
  'hzbb@mindspring.comvate' => [ EMAIL => 'hzbb@mindspring.com' ],
  'improving@bridge.com' => [ LEVEL => 'Intermediate' ],
  'ina64666@yahoo.co.id' => [ EMAIL => '64666@yahoo.co.id', COUNTRY => 'Indonesia' ],
  'insolar@onet.plpid:06387' => [ EMAIL => 'insolar@onet.pl' ],
  'ireksiem1@wp.pl08144' => [ EMAIL => 'ireksiem1@wp.pl' ],
  'irelandmuriel@hotmail.com' => [ EMAIL => 'muriel@hotmail.com', COUNTRY => 'Ireland' ],
  'jagodzinski.d@wp.pl,ma,miksty' => [ EMAIL => 'jagodzinski.d@wp.pl' ],
  'jakob_k@gmx.chstkarniej1428' => [ EMAIL => 'jakob_k@gmx.ch' ],
  'jakub_mitke@wp.plpzbs3856' => [ EMAIL => 'jakub_mitke@wp.pl' ],
  'janjoris@hotmail.coml' => [ EMAIL => 'janjoris@hotmail.com' ],
  'janula36@wp.plid08518' => [ EMAIL => 'janula36@wp.pl' ],
  'jay(28)bridgegoth@yahoo.fi' => [ OPEN => 'Jay', EMAIL => 'bridgegoth@yahoo.fi' ],
  'jbm@mail.bggustomaina' => [ EMAIL => 'jbm@mail.bg' ],
  'jea@jea.comm' => [ EMAIL => 'jea@jea.com' ],
  'jean-marie.verry@orange' => [ EMAIL => 'jean-marie.verry@orange.fr' ],
  'jean.claude.tremel@wanadoo;fr' => [ EMAIL => 'jean.claude.tremel@wanadoo.fr' ],
  'jeanbaptiste.kerebel@sfr' => [ EMAIL => 'jeanbaptiste.kerebel@sfr.fr' ],
  'jemmabe@yahoo.fr(liege-belgium' => [ EMAIL => 'jemmabe@yahoo.fr', CITY => 'Liège', COUNTRY => 'Belgium' ],
  'jerzy@op.pl1234' => [ EMAIL => 'jerzy@op.pl' ],
  'jeter2827@yahoo.comtw' => [ EMAIL => 'jeter2827@yahoo.com.tw' ],
  'jglasspiegel @ol.com' => [ EMAIL => 'jglasspiegel@aol.com' ],
  'jjanovic@epm.net,com' => [ EMAIL => 'jjanovic@epm.net.com' ],
  'jjmsaa@planet.nll' => [ EMAIL => 'jjmsaa@planet.nl' ],
  'jmalawski@onet.pl11153' => [ EMAIL => 'jmalawski@onet.pl' ],
  'jochem.pingel@t-online' => [ EMAIL => 'jochem.pingel@t-online.de' ],
  'justesen@greennet.gl' => [ EMAIL => 'justesen@greennet.dk' ],
  'kaju@gmail.gom' => [ EMAIL => 'kaju@gmail.com' ],
  'kamalkumarnaguri1950@g mail . com' => [ OPEN => 'Kamal Kumar', EMAIL => 'naguri1950@gmail.com' ],
  'kbisson@usa.netbilmember' => [ EMAIL => 'kbisson@usa.net' ],
  'keith.randall@outlook.com. p' => [ EMAIL => 'keith.randall@outlook.com' ],
  'keith.randall@outlook.com.' => [ EMAIL => 'keith.randall@outlook.com' ],
  'kkayagil@hotmail.com...4wxfer' => [ EMAIL => 'kkayagil@hotmail.com' ],
  'krandall33@rogers.comp' => [ EMAIL => 'krandall33@rogers.com' ],
  'kuailpshou@sina.con' => [ EMAIL => 'kuailpshou@sina.com' ],
  'kuhnication@msn.com-sa+2dwait' => [ EMAIL => 'kuhnication@msn.com' ],
  'l.ther@hotmaol.com' => [ EMAIL => '.lther@hotmail.com' ],
  'leswood@dodo.com,au' => [ EMAIL => 'leswood@dodo.com.au' ],
  'liz//neg.dble/jac2nt/gerber@nt' => [ OPEN => 'Liz' ],
  'lizajaneb@hotmail.cm' => [ EMAIL => 'lizajaneb@hotmail.com' ],
  'lorgou_law@g.mail' => [ EMAIL => 'lorgou_law@gmail.com' ],
  'lornaperkins@comcast.ne' => [ EMAIL => 'lornaperkins@comcast.net' ],
  'louis.boisgelot@orange' => [ EMAIL => 'louis.boisgelot@orange.fr' ],
  'louis.jule@uregina,ca' => [ EMAIL => 'louis.jule@uregina.ca' ],
  'luigifilippo.tinellidigorla@fastwebnet.i' => [ OPEN => 'Luigi Filippo TINELLI', CITY => 'Milan', COUNTRY => 'Italy' ],
  'lydie.trajman@.gmail;com' => [ EMAIL => 'lydie.trajman@.gmail.com' ],
  'malensantander@hotmail.con' => [ EMAIL => 'malensantander@hotmail.com' ],
  'maluyao@gmail.comnospam' => [ EMAIL => 'maluyao@gmail.comn' ],
  'manny2d2@yahoo.coom' => [ EMAIL => 'manny2d2@yahoo.com' ],
  'marcosarazi@yahoo.cm' => [ EMAIL => 'marcosarazi@yahoo.com' ],
  'margokw@aol.comsocal' => [ EMAIL => 'margokw@aol.com', REGION => 'Southern California' ],
  'mariana@sinestrellas.com' => [ EMAIL => 'mariana@sinestrellas.com' ],
  'marie-luce.giacobetti@orange.frp' => [ EMAIL => 'marie-luce.giacobetti@orange.fr' ],
  'marilynohlson@iprimus.c' => [ EMAIL => 'marilynohlson@iprimus.com.au' ],
  'mario.taveira@hotmail-com' => [ EMAIL => 'mario.taveira@hotmail.com' ],
  'marisa.@cantabriainfinita' => [ OPEN => 'Marisa', REGION => 'Cantabria' ],
  'marsal24@wp.plpzb01845' => [ EMAIL => 'marsal24@wp.pl' ],
  'maryhall333@btinternet.comj' => [ EMAIL => 'maryhall333@btinternet.com' ],
  'mas@tortue.fr83' => [ EMAIL => 'mas@tortue.fr' ],
  'matarani11@yahoo.com(neverpass1club' => [ EMAIL => 'matarani11@yahoo.com' ],
  'mertbolver@hotmail.comfn' => [ EMAIL => 'mertbolver@hotmail.com' ],
  'mialoganann@yahoo.cm' => [ EMAIL => 'mialoganann@yahoo.com' ],
  'mietek_a49@wp.pl05562' => [ EMAIL => 'mietek_a49@wp.pl' ],
  'milan.italy@march.1963' => [ CITY => 'Milan', COUNTRY => 'Italy' ],
  'mmherron@aol.om' => [ EMAIL => 'mmherron@aol.com' ],
  'mohsen.kamel@entrag,com' => [ EMAIL => 'mohsen.kamel@entrag.com' ],
  'mohsen.kamel@entrag,org' => [ EMAIL => 'mohsen.kamel@entrag,org' ],
  'monica.connollyi@icloudri' => [ EMAIL => 'monica.connolly@icloud.com' ],
  'mselcuk.20@hotmail' => [ EMAIL => 'mselcuk.20@hotmail.com' ],
  'msn:r_segev@hotmail.com' => [ EMAIL => 'r_segev@hotmail.com' ],
  'msn:schoi00@hotmail.com' => [ EMAIL => 'schoi00@hotmail.com' ],
  'msn:yuval_yener@hotmail.com' => [ EMAIL => 'yuval_yener@hotmail.com' ],
  'msn:olzolzolz3@hotmail.com' => [ EMAIL => 'olzolzolz3@hotmail.com' ],
  'muhso_@hotmail.comsalvo31ocak3subar' => [ EMAIL => 'muhso_@hotmail.com' ],
  'musi78@abv.gd' => [ EMAIL => 'musi78@abv.bg' ],
  'mvanwaardhuizen@kpnplanet.n' => [ EMAIL => 'mvanwaardhuizen@kpnplanet.nl' ],
  'nana1321@wp.pl15227' => [ EMAIL => 'nana1321@wp.pl' ],
  'nanddperkins@aol.come' => [ EMAIL => 'nanddperkins@aol.com' ],
  'nazmul.haq@physics' => [ OPEN => 'Nazmul Haq' ],
  'nicolebouvier@neuf.f' => [ EMAIL => 'nicolebouvier@neuf.fr' ],
  'nikijan1@abv.bgu2ntpupp' => [ EMAIL => 'nikijan1@abv.bg' ],
  'noella@omantel.net.om' => [ EMAIL => 'noella@omantel.com' ],
  'notalways@exp.com' => [ LEVEL => 'Advanced' ],
  'nur..nurem@hotmail.com' => [ EMAIL => 'nurem@hotmail.com' ],
  'o.parry@t-online,de' => [ EMAIL => 'o.parry@t-online.de' ],
  'olivier@40.fr' => [ OPEN => 'Olivier', COUNTRY => 'France' ],
  'onur.tutar@hotmai' => [ EMAIL => 'onur.tutar@hotmail.com.tr' ],
  'pablo.valencia@anti.gua' => [ OPEN => 'Pablo Valencia', COUNTRY => 'Antigua and Barbuda' ],
  'pad@wanadoo.ir' => [ EMAIL => 'pad@wanadoo.fr' ],
  'pairssbc@qmail.com' => [ EMAIL => 'sbc@qmail.com' ],
  'panjang_lama@yahoo.co.iid' => [ EMAIL => 'panjang_lama@yahoo.co.id' ],
  'patrice.pauly@muret' => [ OPEN => 'Patrice Pauly', CITY => 'Muret', COUNTRY => 'France' ],
  'pbf001@aol.com3waytrans' => [ EMAIL => 'pbf001@aol.com' ],
  'philippe.choquart@orange.fe' => [ EMAIL => 'philippe.choquart@orange.fr' ],
  'piapeleg.@netvisione.ne/il' => [ EMAIL => 'piapeleg.@netvisione.net.il' ],
  'piero.randi@libero.itquinta' => [ EMAIL => 'piero.randi@libero.it' ],
  'playersinuae,ing.akem@gmail.com' => [ EMAIL => 'ing.akem@gmail.com', COUNTRY => 'United Arab Emirates' ],
  'poland@junior.bridge_capital' => [ OPEN => 'Junior', COUNTRY => 'Poland' ],
  'popavasilebebe@yahoo.comilacy' => [ EMAIL => 'popavasilebebe@yahoo.com' ],
  'posky12238@aol.cm' => [ EMAIL => 'posky12238@aol.com' ],
  'princesaestigarribia@hotmail.comtreboles' => [ CITY => 'Princesa Estigarribia', COUNTRY => 'Paraguay' ],
  'progsign@hotmail.comor' => [ EMAIL => 'progsign@hotmail.com' ],
  'r.schol.r@gmail?com' => [ EMAIL => 'r.schol.r@gmail.com' ],
  'r.smeehuijzen@xs4all' => [ EMAIL => 'r.smeehuijzen@xs4all.nl' ],
  'ramaraoj2000@yahoo.c0m' => [ EMAIL => 'ramaraoj2000@yahoo.com' ],
  'raquelita_1936@hotmail.comr' => [ EMAIL => 'raquelita_1936@hotmail.com' ],
  'realexpert,jan.gronlund3@getmail.no' => [ EMAIL => 'jan.gronlund3@getmail.no', LEVEL => 'Expert' ],
  'rechtsanwaltyetkinadar@hotmail.com' => [ EMAIL => 'yetkinadar@hotmail.com', COUNTRY => 'Germany' ],
  'rgpune@yahoo.com,iit-b95' => [ EMAIL => 'rgpune@yahoo.com', COUNTRY => 'India' ],
  'rmalda@hotmail.itb&b' => [ EMAIL => 'rmalda@hotmail.it' ],
  'robert.beudard@wanadoo' => [ EMAIL => 'robert.beudard@wanadoo.fr' ],
  'roger----@libero.it' => [ EMAIL => 'roger@libero.it' ],
  'roger.loisel34@orange.frl' => [ EMAIL => 'roger.loisel34@orange.fr' ],
  'rosario.manca@alice,it' => [ EMAIL => 'rosario.manca@alice.it' ],
  'rreggi@wp.plbydgoszcz' => [ EMAIL => 'rreggi@wp.pl', CITY => 'Bydgoszcz', COUNTRY => 'Poland' ],
  'ruthacher@hotmail.comunusualnt' => [ EMAIL => 'ruthacher@hotmail.com' ],
  'sam aka showle@aol.com' => [ OPEN => 'Sam', EMAIL => 'showle@aol.com' ],
  'sarel.king@013netnot' => [ OPEN => 'Sarel King' ],
  'sehb23@aol.com..fsf,bergen,supx' => [ EMAIL => 'sehb23@aol.com' ],
  'semrab@hotmail.comm' => [ EMAIL => 'semrab@hotmail.com' ],
  'seterahsaja@up2u.com' => [  COUNTRY => 'Indonesia' ],
  'shokot@walla.con' => [ EMAIL => 'shokot@walla.co,' ],
  'simone@lovethegame.com' => [ OPEN => 'Simone' ],
  'sirop.georgette@akeonet;com' => [ EMAIL => 'sirop.georgette@akeonet.com' ],
  'slaoun@vtr.clcheckback' => [ EMAIL => 'slaoun@vtr.cl' ],
  'sneil-glm-timm@pitt.edu' => [ OPEN => 'Neil TIMM', 'EMAIL' => '@timm@pitt.edu', LEVEL => 'Life Master' ],
  'sometimesexpert@advanced.com' => [ LEVEL => 'Advanced' ],
  'sono.amoroso@bergamo' => [ CITY => 'Bergamo', COUNTRY => 'Italy' ],
  'srruppuut.@ycom' => [ EMAIL => 'srruppuut@y.com' ],
  'st.josephkleak@yahoo.com' => [ EMAIL => 'kleak@yahoo.com', CITY => 'Manado', COUNTRY => 'Indonesia' ],
  'suemason@tigo.compy' => [ EMAIL => 'suemason@tigo.com.py' ],
  'sukrukaya52@hotmail.com2/1' => [ EMAIL => 'sukrukaya52@hotmail.com' ],
  'suney@263.net' => [ EMAIL => 'suney@263.com' ],
  'syaloomtondano.@com' => [ CITY => 'Tondano', COUNTRY => 'Indonesia' ],
  'sylvie.ekmark@gmail' => [ EMAIL => 'sylvie.ekmark@gmail.com' ],
  'szekla23@vp.plilacymember' => [ EMAIL => 'szekla@wp.pl' ],
  'szunaj31@wp.plpid-10500' => [ EMAIL => 'szunaj31@wp.pl' ],
  'tahirosmantaos_tr@yahoo.com' => [ OPEN => 'Tahir Osman', EMAIL => 'taos_tr@yahoo.com' ],
  'tetea@speedy.com,ar' => [ EMAIL => 'tetea@speedy.com.ar' ],
  'thisidisusedbymanytomake broadcasts,host tourneys-anyqueriessendtoadmin@bilbridge.com' => [ EMAIL => 'admin@bilbridge.com' ],
  'thomas.b.ekblom@gmail,com' => [ EMAIL => 'thomas.b.ekblom@gmail.com' ],
  'tonseatondano,kendis,gorontalo,.@.com' => [ CITY => 'Tondano', COUNTRY => 'Indonesia' ],
  'toulouse@villerose.com' => [ CITY => 'Toulouse', COUNTRY => 'France' ],
  'ufum@hotmail.combbotd' => [ EMAIL => 'utum@hotmail.com' ],
  'umypoppy@gmail.com.e' => [ EMAIL => 'umypoppy@gmail.com' ],
  'vayhan325@gmail.com' => [ EMAIL => 'ayhan325@gmail.com' ],
  'vasvirv@otenet.grsk.:vasmar44' => [ EMAIL => 'vasvir@otenet.gr' ],
  'vecdi.sezer@hotmail.comm' => [ EMAIL => 'vecdi.sezer@hotmail.com' ],
  'vic(vastj@wanadoo.fr' => [ EMAIL => 'vastj@wanadoo.fr' ],
  'vicsartor/vsartor77@aol.com' => [ OPEN => 'Vic Sartor', EMAIL => 'vsartor77@aol.com' ],
  'viren2512@yahoo.co,in' => [ EMAIL => 'viren2512@yahoo.co.in' ],
  'w.reszelski@o2.p05348' => [ EMAIL => 'w.reszelski@o2.pl' ],
  'w.roj@wp.pl,pid16248' => [ EMAIL => 'w.roj@wp.pl' ],
  'wake.advies@kpnmail' => [ EMAIL => 'wake.advies@kpnmail.nl' ],
  'watford@around.m25.london' => [ CITY => 'Watford', COUNTRY => 'England' ],
  'wkrzem51@wp.pl,td-ns6' => [ EMAIL => 'wkrzem51@wp.pl' ],
  'wojchr@op.plwarszawa' => [ EMAIL => 'wojchr@op.pl', CITY => 'Warsaw', COUNTRY => 'Poland' ],
  'wylly@interia.pl10821' => [ EMAIL => 'wylly@interia.pl' ],
  'xayhan325@gmail.com' => [ EMAIL => 'ayhan325@gmail.com' ],
  'xiao.bizi@163' => [ EMAIL => 'xiao.bizi@163.com' ],
  'xyshen@hotmail.c0m' => [ EMAIL => 'xyshen@hotmail.com' ],
  'yaaay@wp.pl10056' => [ EMAIL => 'yaaay@wp.pl' ],
  'yaegermbgc@aol.comleb;invmn' => [ EMAIL => 'yaegermbgc@aol.com' ],
  'yaffad@013.net.ii' => [ EMAIL => 'yaffad@013.net.il' ],
  'yaseca@hotmail.com(van' => [ EMAIL => 'yaseca@hotmail.com' ],
  'yhq3776@126.gom' => [ EMAIL => 'yhq3776@126.com' ],
  'ymfolan@yahoo.combil' => [ EMAIL => 'ymfolan@yahoo.com' ],
  'yolande watelet.@yahoo.fr' => [ EMAIL => 'yolande watelet.@yahoo.fr' ],
  'zbs001@126.c0m' => [ EMAIL => 'zbs001@126.com' ],
  'zbynieks@op.pl,cezar07936' => [ EMAIL => 'zbynieks@op.pl' ],
  'zetim@op.plpid1751' => [ EMAIL => 'zetim@op.pl' ],
  'zkrzepkowski@wp.pl4329' => [ EMAIL => 'zkrzepkowski@wp.pl' ],
  'zubyz@seznam.czmámiskypezdenda1202' => [ EMAIL => 'zubyz@seznam.cz' ],

  'mamamazi@\'walla.com' => [ EMAIL => 'mamamazi@walla.com' ],
  'xwh163@.com' => [ EMAIL => 'xwh@163.com'],
  'simcous@.abv.bg' => [ EMAIL => 'simcous@abv.bg'],
  'francodolcetta@.alice.it' => [ EMAIL => 'francodolcetta@alice.it' ],
  'roreat@.bermuda.com' => [ EMAIL => 'roreat@bermuda.com' ],
  'yves.hebert@.cgocable.ca' => [ EMAIL => 'yves.hebert@cgocable.ca' ],
  'taraca@.sbb.rs' => [ EMAIL => 'taraca@sbb.rs' ],
  'renee.chediack@.fibertel.com.ar' => [ EMAIL => 'renee.chediack@fibertel.com.ar' ],
  'jose.azzopardi@.orange.fr' => [ EMAIL => 'jose.azzopardi@orange.fr' ],
  'shronet88@.hotmail.com' => [ EMAIL => 'shronet88@hotmail.com' ],
  'nn.771@.wp.pl' => [ EMAIL => 'nn.771@wp.pl' ],
  '746903008@.qq.com' => [ EMAIL => '746903008@qq.com' ],
  '827481046qq@.com' => [ EMAIL => '827481046@qq.com' ],
  'yamit@.terra.com.br' => [ EMAIL => 'yamit@.terra.com.br' ],
  'stefan_021@.onet.eu' => [ EMAIL => 'stefan_021@onet.eu' ],
  'la39@.comhem.se' => [ EMAIL => 'la39@.comhem.se' ],
  'a.abbassi@.hotmail.fr' => [ EMAIL => 'a.abbassi@hotmail.fr' ],

);

our $MULTIPLES_HASH = \%MULTIPLES;

1;
