#!perl

package Email::Multiples;

use strict;
use warnings;
use v5.10;
use utf8;
use open ':std', ':encoding(UTF-8)';

use Exporter;

our @ISA = qw(Exporter);
our @EXPORT = qw($MULTIPLES_HASH);

my %MULTIPLES =
(
  '0272244@fudan.edu.c' => [ EMAIL => '0272244@fudan.edu.cn' ],
  '05353 olgierd.rb@gmail.com' => [ EMAIL => 'olgierd.rb@gmail.com' ],
  '13875318390@163.con' => [ EMAIL => '13875318390@163.com' ],
  '163.@com' => [ COUNTRY => 'China' ],
  '2/1 sapanca@hotmail.com' => [ EMAIL => 'sapanca@hotmail.com' ],
  '2/1@paragragh22.com' => [ SYSTEM => '2/1@paragragh22.com' ],
  '2/1gf@km.com' => [ SYSTEM => '2/1gf@km.com' ],
  '2didierthomazet@aol.com' => [ EMAIL => 'didierthomazet@aol.com' ],
  '3didierthomazet@aol.com' => [ EMAIL => 'didierthomazet@aol.com' ],
  '3pik@wp.pl 5606' => [ EMAIL => '3pik@wp.pl' ],
  '505394947@qq.c' => [ EMAIL => '505394947@qq.com' ],
  '6egil ( egil@nerheim.nu' => [ OPEN => 'Egil', EMAIL => 'egil@nerheim.nu' ],
  '798686368 @.qq.com' => [ EMAIL => '798686368@qq.com' ],
  '7didierthomazet@aol.com' => [ EMAIL => 'didierthomazet@aol.com' ],
  '87362535@qq.ocm' => [ EMAIL => '87362535@qq.com' ],
  '88 @ yaman.com2breslau' => [ EMAIL => '88@yaman.com', CITY => 'Wroclaw', COUNTRY => 'Poland' ],
  '8didierthomazet@aol.com' => [ EMAIL => 'didierthomazet@aol.com' ],
  '_*)dan0ana@yahoo.com' => [ EMAIL => '_*)dan0ana@yahoo.com' ],
  'a.frietema@upcmail.nll' => [EMAIL => 'a.frietema@upcmail.nl' ],
  'abe@iki.fi, living in germany' => [ EMAIL => 'abe@iki.fi', COUNTRY => 'Germany' ],
  'addy.tex@wanadoo.dr' => [ EMAIL => 'addy.tex@wanadoo.fr' ],
  'advanced++@abv.bg' => [ LEVEL => 'Advanced', COUNTRY => 'Bulgaria' ],
  'agusia74@poczta.onet' => [ EMAIL => 'agusia74@poczta.onet.pl' ],
  'ah.vandyk@sympatico/ca' => [ EMAIL => 'ah.vandyk@sympatico.ca' ],
  'ajay (28) bridgegoth@yahoo.fi' => [ OPEN => 'Jay', EMAIL => 'bridgegoth@yahoo.fi' ],
  'al1919 @ hotmail . fr' => [ EMAIL => 'al1919@hotmail.fr' ],
  'al@morglia.net - bbo italia' => [ EMAIL => 'al@morglia.net', COUNTRY => 'Italy' ],
  'alam@t.palsu.oom' => [ EMAIL => 'alam@t.palsu.com' ],
  'alex ------@llibero.it' => [ EMAIL => 'alex@libero.it' ],
  'ali@ali.com' => [ OPEN => 'Ali' ],
  'alie_196616@yahoo.acom' => [ EMAIL => 'alie_196616@yahoo.com' ],
  'amico @libero.son' => [ COUNTRY => 'Italy' ],
  'anna@anna.com' => [OPEN => 'Anna' ],
  'antun.matana@optinet' => [ EMAIL => 'antun.matana@optinet.hr' ],
  'ap2410@ns.sympatico.can' => [ EMAIL => 'ap2410@ns.sympatico.ca' ],
  'aquapharm@hotmail.com stars' => [ EMAIL => 'aquapharm.hotmail.com' ],
  'associazionebridgepotenza@gmail.com b&b' => [ EMAIL => 'associazionebridgepotenza@gmail.com'],
  'atayayaz@live.com p' => [ EMAIL => 'atayazaz@live.com' ],
  'au.pl@isir' => [ COUNTRY => 'France' ],
  'avec.jac@mennecy' => [ CITY => 'Mennecy', COUNTRY => 'France' ],
  'ayik.dagci16@gmail' => [ EMAIL => 'ayik.dagci16@gmail.com' ],
  'b.holl@hccnet.nl heya sven (kramer' => [ EMAIL => 'b.holl@hccnet.nl' ],
  'bactriam@gmail.com 16794' => [ EMAIL => 'bactriam@gmail.com' ],
  'badman@jahil.oom' => [ EMAIL => 'badman@jahil.com' ],
  'beniopszczola@o2.pl olsztyn' => [ EMAIL => 'beniopszczola@o2.pl', CITY => 'Olsztyn', COUNTRY => 'Poland' ],
  'bevbernie@att.nett' => [ EMAIL => 'bevbernie@att.net' ],
  'bobr5555@yahoo.comcom' => [ EMAIL => 'bobr5555@yahoo.com' ],
  'bogdan1012@hotmail.com, ilacy member' => [ EMAIL => 'bogdan1012@hotmail.com' ],
  'bohdan.pliszka@op.pl cezar8052' => [ EMAIL => 'bohdan.pliszka@op.pl' ],
  'bridgemasuksekolah@grp.comm' => [ COUNTRY => 'Indonesia' ],
  'bruno uno@hotmail.it' => [ EMAIL => 'bruno@hotmail.it' ],
  'bstitch562@hotmailc.om' => [ EMAIL => 'bstitch562@hotmail.com' ],
  'bulova@nyct.net lessons avl' => [ EMAIL => 'bulova@nyct.net', LEVEL => 'Expert' ],
  'burdigala@port.de.la.lune' => [ CITY => 'Bordeaux', COUNTRY => 'France' ],
  'c/-  admin@bilbridge.com' => [ EMAIL => 'admin@bilbridge.com' ],
  'c/- admin@bilbridge.com' => [ EMAIL => 'admin@bilbridge.com' ],
  'canadadan@gmail.coma' => [ EMAIL => 'canadadan@gmail.com' ],
  'cangurcan48@hotmail.comtr' => [ EMAIL => 'cangurcan48@hotmail.com.tr' ],
  'carlaaprile52@libero.itivate' => [ EMAIL => 'carlaaprile52@libero.it' ],
  'carlcsc@yahoo.com glm' => [ EMAIL => 'carlcsc@yahoo.com glm', 'LEVEL' => 'Life Master' ],
  'cat_shit@hotmail.com nazilli' => [ CITY => 'Nazilli', COUNTRY => 'Turkey' ],
  'ccdr@dgfood.gov,bd' => [ EMAIL => 'ccdr@dgfood.gov.bd' ],
  'celavitali@gmail.coml' => [ EMAIL => 'celavitali@gmail.com' ],
  'cenver@msn.comtr' => [ EMAIL => 'cenver@msn.com.tr' ],
  'chb.langer@t-online' => [ EMAIL => 'chb.langer@t-online.de' ],
  'chicciola@chiocciolo.ino' => [ EMAIL => 'chicciola@chiocciolo.info' ],
  'cilegon city@kota.com' => [ CITY => 'Cilegon', COUNTRY => 'Indonesia' ],
  'clpirro@tin.it ilacy member' => [ EMAIL => 'clpirro@tin.it' ],
  'commbruggen@hotmail.come' => [ EMAIL => 'commbruggen@hotmail.com' ],
  'cpt64@free.fr biarritz' => [ EMAIL => 'cpt64@free.fr', CITY => 'Biarritz', COUNTRY => 'France' ],
  'crossft@gmail.com - 8902023' => [ EMAIL => 'crossft@gmail.com' ],
  'dan@whoknows.com' => [ OPEN => 'Dan'] ,
  'daniel.raimbault@wanadoo.frd' => [ EMAIL => 'daniel.raimbault@wanadoo.fr' ],
  'danmar@adinet.com.uy (uruguay' => [ EMAIL => 'danmar@adinet.com.uy' ],
  'dazuker@zahav.net/il' => [ EMAIL => 'dazuker@zahav.net.il' ],
  'de.luten@versatel,nl' => [ EMAIL => 'de.luten@versatel.nl' ],
  'delia.carotenuto@libero-it' => [ EMAIL => 'delia.carotenuto@libero.it' ],
  'diko65@abv.bg. kostenetc' => [ EMAIL => 'diko65@abv.bg', CITY => 'Kostenets', COUNTRY => 'Bulgaria' ],
  'dogustanexper@ahmetizm.xxx' => [ LEVEL => 'Expert' ],
  'donald.caton@yahoo' => [ EMAIL => 'donald.caton@yahoo.com' ],
  'drzaferjarrar@gmail.com  p' => [ EMAIL => 'drzaferjarrar@gmail.com' ],
  'duchessofomaha@aol.comacbl' => [ COUNTRY => 'USA' ],
  'dursunyildiz101@hotmail.com www.major' => [ EMAIL => 'dursunyildiz101@hotmail.com' ],
  'e-mail mark massa @yahoo.com' => [ EMAIL => 'markmassa@yahoo.com' ],
  'e-mail:tadeusz.tan@interia.pl' => [ EMAIL => 'tadeusz.tan@interia.pl' ],
  'eat@vmg2.bekasi' => [ 'CITY' => 'Bekasi', COUNTRY => 'Indonesia' ],
  'erm19@juno.come' => [ EMAIL => 'erm19@juno.com' ],
  'expert.@.com' => [ LEVEL => 'Expert' ],
  'expert\'@expert.com' => [ LEVEL => 'Expert' ],
  'fantoine: tonino947@hotmail.com' => [ OPEN => 'Antoine', EMAIL => 'tonino947@hotmail.com' ],
  'fe@ugm.yk' => [ UNIVERSITY => 'Universitas Gadjah Mada', COUNTRY => 'Indonesia' ],
  'fjarang dibelai jablaigtbc@y.co' => [ COUNTRY => 'Indonesia' ],
  'frami.laurence@orange.frl.' => [ EMAIL => 'frami.laurence@orange.fr' ],
  'francois.louis15@fr.sfr' => [ EMAIL => 'francois.louis15@sfr.fr' ],
  'franmo@gmail.com junior' => [ OPEN => 'Junior', EMAIL => 'franmo@gmail.com' ],
  'frederic.lacroix@web.ffbridge' => [ EMAIL => 'frederic.lacroix@web.ffbridge.fr' ],
  'g.rosca@yahoo' => [ EMAIL => 'g.rosca@yahoo.bg' ],
  'g.virchick@verizon.net(boston' => [ CITY => 'Boston', COUNTRY => 'USA', EMAIL => 'g.virchick@verizon.net' ],
  'gabrielmassut@hotmail.comm' => [ EMAIL => 'gabrielmassut@hotmail.com' ],
  'gadi gadischwartz1957@gmail.c' => [ EMAIL => 'gadischwartz1957@gmail.com' ],
  'genting island@yahoo.my.com' => [ REGION => 'Genting Highlands', COUNTRY => 'Malaysia' ],
  'gervais.arlette@ wanadoow .fr' => [ EMAIL => 'gervais.arlette@wanadoo.fr' ],
  'gezi@bravosize.com tr' => [ EMAIL => 'gezo@bravosize.com.tr' ],
  'giasmpierodionigiregione @alice.it' => [ OPEN => 'Giampiero Dionigi', COUNTRY => 'Italy' ],
  'gilberto.figatalamanca@fastweb.neti' => [ EMAIL => 'gilberto.figatalamanca@fastwebnet.it' ],
  'giorggi@sawas.arg' => [ EMAIL => 'giorggi@sawas.ar' ],
  'gjay (29) bridgegoth@yahoo.fi' => [ OPEN => 'Jay', EMAIL => 'bridgegoth@yahoo.fi' ],
  'gjs@autograf.pl  7725  kraków' => [ EMAIL => 'gjs@autograf.pl', CITY => 'Krakow', COUNTRY => 'Poland' ],
  'glevin5228@aol.xim' => [ EMAIL => 'glevin5228@aol.com' ],
  'gosh59@abv.bg;sofia mladost1' => [ EMAIL => 'gosh59@abv.bg', CITY => 'Sofia', COUNTRY => 'Bulgaria' ],
  'goubet.hubert@wanadoo' => [ EMAIL => 'goubet.hubert@wanadoo.fr' ],
  'grasool1337@yahoo.c0m' => [ EMAIL => 'grasool1337@yahoo.com' ],
  'grb@taigabridge.net (bil hon. dementor' => [ EMAIL => 'grb@taigabridge.net' ],
  'gsanna35@hotmail.it tolclub' => [ EMAIL => 'gsanna35@hotmail.it' ],
  'guciogg@poczta.onet' => [ EMAIL => 'guciogg@poczta.onet.pl' ],
  'guiyotambella@yahoo.com,ar' => [ EMAIL => 'guiyotambella@yahoo.com.ar' ],
  'guy@warwick.hm' => [ CITY => 'Watford', COUNTRY => 'England' ],
  'haavard7355@msn.com. low card3-5 hight' => [ EMAIL => 'haavard7355@msn.com' ],
  'hamdysimillawi@hotmail.comm' => [ EMAIL => 'hamdysimillawi@hotmail.com' ],
  'happy_to_get_spam@not.se' => [ COUNTRY => 'Sweden' ],
  'harry@bridge.com' => [ OPEN => 'Harry'] ,
  'hehe@hehe.pl.wroclaw-raj' => [ CITY => 'Wroclaw', COUNTRY => 'Poland' ],
  'hel2004.kraus@t-online.e' => [ EMAIL => 'hel2004.kraus@t-online.de' ],
  'helko05@verizon.netvate' => [ EMAIL => 'helko05@verizon.net' ],
  'hexi5@yahoo.mail' => [ EMAIL => 'hexi5@yahoo.com' ],
  'hiae1@bezeqint.netl' => [ EMAIL => 'hiae1@bezeqint.net' ],
  'hsoysuren@hotmail.com- lebenshol' => [ EMAIL => 'hsoysuren@hotmail.com' ],
  'hzbb@mindspring.comvate' => [ EMAIL => 'hzbb@mindspring.com' ],
  'i.@tiscalinet.it' => [ COUNTRY => 'Italy' ],
  'igraia ponqkoga@gankinoto.bg' => [ COUNTRY => 'Bulgaria' ],
  'improving@bridge.com' => [ LEVEL => 'Intermediate' ],
  'ina 64666@yahoo.co.id' => [ EMAIL => '64666@yahoo.co.id', COUNTRY => 'Indonesia' ],
  'insolar@onet.pl pid:06387' => [ EMAIL => 'insolar@onet.pl' ],
  'ireksiem1@wp.pl 08144' => [ EMAIL => 'ireksiem1@wp.pl' ],
  'ireland muriel@hotmail.com' => [ EMAIL => 'muriel@hotmail.com', COUNTRY => 'Ireland' ],
  'jagodzinski.d@wp.pl, ma, miksty' => [ EMAIL => 'jagodzinski.d@wp.pl' ],
  'jakob_k@gmx.ch st karniej 1428' => [ EMAIL => 'jakob_k@gmx.ch' ],
  'jakub_mitke@wp.pl pzbs 3856' => [ EMAIL => 'jakub_mitke@wp.pl' ],
  'janjoris@hotmail.coml' => [ EMAIL => 'janjoris@hotmail.com' ],
  'janula36@wp.pl id08518' => [ EMAIL => 'janula36@wp.pl' ],
  'jay (28) bridgegoth@yahoo.fi' => [ OPEN => 'Jay', EMAIL => 'bridgegoth@yahoo.fi' ],
  'jbm@mail.bg gusto maina' => [ EMAIL => 'jbm@mail.bg' ],
  'jea@jea.comm' => [ EMAIL => 'jea@jea.com' ],
  'jean-marie.verry@orange' => [ EMAIL => 'jean-marie.verry@orange.fr' ],
  'jean.claude.tremel@wanadoo;fr' => [ EMAIL => 'jean.claude.tremel@wanadoo.fr' ],
  'jeanbaptiste.kerebel@sfr' => [ EMAIL => 'jeanbaptiste.kerebel@sfr.fr' ],
  'jemmabe@yahoo.fr (liege-belgium' => [ EMAIL => 'jemmabe@yahoo.fr', CITY => 'Liège', COUNTRY => 'Belgium' ],
  'jerzy@op.pl1234' => [ EMAIL => 'jerzy@op.pl' ],
  'jeter2827@yahoo.comtw' => [ EMAIL => 'jeter2827@yahoo.com.tw' ],
  'jglasspiegel @ol.com' => [ EMAIL => 'jglasspiegel@aol.com' ],
  'jjanovic@epm.net,com' => [ EMAIL => 'jjanovic@epm.net.com' ],
  'jjmsaa@planet.nll' => [ EMAIL => 'jjmsaa@planet.nl' ],
  'jmalawski@onet.pl 11153' => [ EMAIL => 'jmalawski@onet.pl' ],
  'jochem.pingel@t-online' => [ EMAIL => 'jochem.pingel@t-online.de' ],
  'justesen@greennet.gl' => [ EMAIL => 'justesen@greennet.dk' ],
  'kaju@gmail.gom' => [ EMAIL => 'kaju@gmail.com' ],
  'kamal kumar naguri 1950@g mail . com' => [ OPEN => 'Kamal Kumar', EMAIL => 'naguri1950@gmail.com' ],
  'kbisson@usa.net bil member' => [ EMAIL => 'kbisson@usa.net' ],
  'keith.randall@outlook.com. p' => [ EMAIL => 'keith.randall@outlook.com' ],
  'keith.randall@outlook.com.' => [ EMAIL => 'keith.randall@outlook.com' ],
  'kkayagil@hotmail.com...4wxfer' => [ EMAIL => 'kkayagil@hotmail.com' ],
  'krandall33@rogers.com  p' => [ EMAIL => 'krandall33@rogers.com' ],
  'kuailpshou@sina.con' => [ EMAIL => 'kuailpshou@sina.com' ],
  'kuhnication@msn.com-sa+ 2dwait' => [ EMAIL => 'kuhnication@msn.com' ],
  'l.ther@hotmaol .com' => [ EMAIL => '.lther@hotmail.com' ],
  'la.sulmurosale@la.bavosa' => [ COUNTRY => 'Italy' ],
  'laroche@lso.vendee' => [ COUNTRY => 'France' ],
  'leswood@dodo.com,au' => [ EMAIL => 'leswood@dodo.com.au' ],
  'liz//neg.dble/jac2nt/gerber@nt' => [ OPEN => 'Liz' ],
  'lizajaneb@hotmail.cm' => [ EMAIL => 'lizajaneb@hotmail.com' ],
  'lorgou_law@g.mail' => [ EMAIL => 'lorgou_law@gmail.com' ],
  'lornaperkins@comcast.ne' => [ EMAIL => 'lornaperkins@comcast.net' ],
  'louis.boisgelot@orange' => [ EMAIL => 'louis.boisgelot@orange.fr' ],
  'louis.jule@uregina,ca' => [ EMAIL => 'louis.jule@uregina.ca' ],
  'luigifilippo.tinellidigorla@fastwebnet.i' => [ OPEN => 'Luigi Filippo TINELLI', CITY => 'Milan', COUNTRY => 'Italy' ],
  'lydie.trajman@.gmail;com' => [ EMAIL => 'lydie.trajman@.gmail.com' ],
  'malensantander@hotmail.con' => [ EMAIL => 'malensantander@hotmail.com' ],
  'maluyao@gmail.comnospam' => [ EMAIL => 'maluyao@gmail.comn' ],
  'manny2d2@yahoo.coom' => [ EMAIL => 'manny2d2@yahoo.com' ],
  'marcosarazi@yahoo.cm' => [ EMAIL => 'marcosarazi@yahoo.com' ],
  'margokw@aol.com socal' => [ EMAIL => 'margokw@aol.com', REGION => 'Southern California' ],
  'mariana @ sin estrellas. com' => [ EMAIL => 'mariana@sinestrellas.com' ],
  'marie-luce.giacobetti@orange.frp' => [ EMAIL => 'marie-luce.giacobetti@orange.fr' ],
  'marilynohlson@iprimus.c' => [ EMAIL => 'marilynohlson@iprimus.com.au' ],
  'mario.taveira@hotmail-com' => [ EMAIL => 'mario.taveira@hotmail.com' ],
  'marisa.@ cantabria infinita' => [ OPEN => 'Marisa', REGION => 'Cantabria' ],
  'marsal24@wp.pl pzb 01845' => [ EMAIL => 'marsal24@wp.pl' ],
  'maryhall333@btinternet.comj' => [ EMAIL => 'maryhall333@btinternet.com' ],
  'mas@tortue.fr 83' => [ EMAIL => 'mas@tortue.fr' ],
  'mascleta@maica.ok' => [ COUNTRY => 'Spain' ],
  'matarani11@yahoo.com (never pass 1 club' => [ EMAIL => 'matarani11@yahoo.com' ],
  'mertbolver@hotmail.com fn' => [ EMAIL => 'mertbolver@hotmail.com' ],
  'mialoganann@yahoo.cm' => [ EMAIL => 'mialoganann@yahoo.com' ],
  'mietek_a49@wp.pl 05562' => [ EMAIL => 'mietek_a49@wp.pl' ],
  'milan.italy@march.1963' => [ CITY => 'Milan', COUNTRY => 'Italy' ],
  'milangrandemilan@2110.qui' => [ COUNTRY => 'Italy' ],
  'mmherron@aol.om' => [ EMAIL => 'mmherron@aol.com' ],
  'mohsen.kamel@entrag,com' => [ EMAIL => 'mohsen.kamel@entrag.com' ],
  'mohsen.kamel@entrag,org' => [ EMAIL => 'mohsen.kamel@entrag,org' ],
  'monica.connollyi@icloudri' => [ EMAIL => 'monica.connolly@icloud.com' ],
  'morau.con@vasteprogramme' => [ COUNTRY => 'France' ],
  'mselcuk.20@hotmail' => [ EMAIL => 'mselcuk.20@hotmail.com' ],
  'msn : r_segev@hotmail.com' => [ EMAIL => 'r_segev@hotmail.com' ],
  'msn : schoi00@hotmail.com' => [ EMAIL => 'schoi00@hotmail.com' ],
  'msn: yuval_yener@hotmail.com' => [ EMAIL => 'yuval_yener@hotmail.com' ],
  'msn:olzolzolz3@hotmail.com' => [ EMAIL => 'olzolzolz3@hotmail.com' ],
  'mti.@bg' => [ COUNTRY => 'Bulgaria' ],
  'muhso_@hotmail.com salvo31 ocak 3 subar' => [ EMAIL => 'muhso_@hotmail.com' ],
  'musi78@abv.gd' => [ EMAIL => 'musi78@abv.bg' ],
  'mvanwaardhuizen@kpnplanet.n' => [ EMAIL => 'mvanwaardhuizen@kpnplanet.nl' ],
  'n.hikmet/antalyaspor@salvo' => [ COUNTRY => 'Turkey' ],
  'nana1321@wp.pl 15227' => [ EMAIL => 'nana1321@wp.pl' ],
  'nanddperkins@aol.come' => [ EMAIL => 'nanddperkins@aol.com' ],
  'nazmul.haq@physics' => [ OPEN => 'Nazmul Haq' ],
  'neo@ jeo time.com' => [ COUNTRY => 'Indonesia' ],
  'never_repress_yourself@yahoo.fr' => [ COUNTRY => 'France' ],
  'nicolebouvier@neuf.f' => [ EMAIL => 'nicolebouvier@neuf.fr' ],
  'nikijan1@abv.bg u2nt pupp' => [ EMAIL => 'nikijan1@abv.bg' ],
  'nk@long.hideung / 012' => [ COUNTRY => 'Indonesia' ],
  'noella@omantel.net.om' => [ EMAIL => 'noella@omantel.com' ],
  'notalways@exp.com' => [ LEVEL => 'Advanced' ],
  'nur ..nurem@hotmail .com' => [ EMAIL => 'nurem@hotmail.com' ],
  'o.parry@t-online,de' => [ EMAIL => 'o.parry@t-online.de' ],
  'olivier@40.fr' => [ OPEN => 'Olivier', COUNTRY => 'France' ],
  'onur.tutar@hotmai' => [ EMAIL => 'onur.tutar@hotmail.com.tr' ],
  'pablo.valencia@anti.gua' => [ OPEN => 'Pablo Valencia', COUNTRY => 'Antigua and Barbuda' ],
  'pad@wanadoo.ir' => [ EMAIL => 'pad@wanadoo.fr' ],
  'pairs sbc@qmail.com' => [ EMAIL => 'sbc@qmail.com' ],
  'panjang_lama@yahoo.co.iid' => [ EMAIL => 'panjang_lama@yahoo.co.id' ],
  'patrice.pauly@muret' => [ OPEN => 'Patrice Pauly', CITY => 'Muret', COUNTRY => 'France' ],
  'pbf001@aol.com 3 way trans' => [ EMAIL => 'pbf001@aol.com' ],
  'philippe.choquart@orange.fe' => [ EMAIL => 'philippe.choquart@orange.fr' ],
  'piapeleg.@netvisione.ne/il' => [ EMAIL => 'piapeleg.@netvisione.net.il' ],
  'piero.randi@libero.itquinta' => [ EMAIL => 'piero.randi@libero.it' ],
  'players in uae, ing.akem@gmail.com' => [ EMAIL => 'ing.akem@gmail.com', COUNTRY => 'United Arab Emirates'],
  'poland@junior.bridge_capital' => [ OPEN => 'Junior', COUNTRY => 'Poland' ],
  'popavasilebebe@yahoo.com ilacy' => [ EMAIL => 'popavasilebebe@yahoo.com' ],
  'posky12238@aol.cm' => [ EMAIL => 'posky12238@aol.com' ],
  'princesaestigarribia@hotmail.comtreboles' => [ CITY => 'Princesa Estigarribia', COUNTRY => 'Paraguay' ],
  'pringgondani@gatut.koco' => [ COUNTRY => 'Indonesia' ],
  'progsign@hotmail.com or' => [ EMAIL => 'progsign@hotmail.com' ],
  'qualche.volta.la indovino@.it' => [ COUNTRY => 'Italy' ],
  'r.schol.r@gmail?com' => [ EMAIL => 'r.schol.r@gmail.com' ],
  'r.smeehuijzen@xs4all' => [ EMAIL => 'r.smeehuijzen@xs4all.nl' ],
  'ramaraoj2000@yahoo.c0m' => [ EMAIL => 'ramaraoj2000@yahoo.com' ],
  'raquelita_1936@hotmail.comr' => [ EMAIL => 'raquelita_1936@hotmail.com' ],
  'real expert, jan.gronlund3@getmail.no' => [ EMAIL => 'jan.gronlund3@getmail.no', LEVEL => 'Expert' ],
  'rechtsanwalt yetkinadar@hotmail.com' => [ EMAIL => 'yetkinadar@hotmail.com', COUNTRY => 'Germany'],
  'rgpune@yahoo.com,iit-b 95' => [ EMAIL => 'rgpune@yahoo.com', COUNTRY => 'India' ],
  'rmalda@hotmail.it b&b' => [ EMAIL => 'rmalda@hotmail.it' ],
  'robert.beudard@wanadoo' => [ EMAIL => 'robert.beudard@wanadoo.fr' ],
  'roger---- @libero.it' => [ EMAIL => 'roger@libero.it' ],
  'roger.loisel34@orange.frl' => [ EMAIL => 'roger.loisel34@orange.fr' ],
  'rosario.manca@alice,it' => [ EMAIL => 'rosario.manca@alice.it' ],
  'rreggi@wp.pl bydgoszcz' => [ EMAIL => 'rreggi@wp.pl', CITY => 'Bydgoszcz', COUNTRY => 'Poland' ],
  'ruthacher@hotmail.com unusual nt' => [ EMAIL => 'ruthacher@hotmail.com' ],
  'sam aka showle@aol.com' => [ OPEN => 'Sam', EMAIL => 'showle@aol.com' ],
  'sarel.king@013netnot' => [ OPEN => 'Sarel King' ],
  'sehb23@aol.com.. fsf, bergen, sup x' => [ EMAIL => 'sehb23@aol.com' ],
  'semrab@hotmail.comm' => [ EMAIL => 'semrab@hotmail.com' ],
  'seterah saja@up2u.com' => [  COUNTRY => 'Indonesia' ],
  'shokot@walla.con' => [ EMAIL => 'shokot@walla.co,' ],
  'sido@p\'titcoeurd\'amour.gmail' => [ COUNTRY => 'France' ],
  'simone@lovethegame.com' => [ OPEN => 'Simone' ],
  'sirop.georgette@akeonet;com' => [ EMAIL => 'sirop.georgette@akeonet.com' ],
  'slaoun@vtr.cl checkback' => [ EMAIL => 'slaoun@vtr.cl' ],
  'sneil-glm- timm@pitt.edu' => [ OPEN => 'Neil TIMM', 'EMAIL' => '@timm@pitt.edu', LEVEL => 'Life Master'],
  'sometimes expert@advanced.com' => [LEVEL => 'Advanced' ],
  'sono permaloso@.na' => [ COUNTRY => 'Italy' ],
  'sono.amoroso@bergamo' => [ CITY => 'Bergamo', COUNTRY => 'Italy' ],
  'sonopermaloso@.na' => [ COUNTRY => 'Italy' ],
  'srruppuut .@y com' => [ EMAIL => 'srruppuut@y.com' ],
  'st. joseph kleak @yahoo.com' => [ EMAIL => 'kleak@yahoo.com', CITY => 'Manado', COUNTRY => 'Indonesia' ],
  'suemason@tigo.com py' => [ EMAIL => 'suemason@tigo.com py' ],
  'sukrukaya52@hotmail.com 2/1' => [ EMAIL => 'sukrukaya52@hotmail.com' ],
  'suney@263.net' => [ EMAIL => 'suney@263.com' ],
  'syaloom tondano.@ com' => [ CITY => 'Tondano', COUNTRY => 'Indonesia' ],
  'sylvie.ekmark@gmail' => [ EMAIL => 'sylvie.ekmark@gmail.com' ],
  'szekla23@vp.pl ilacy member' => [ EMAIL => 'szekla@wp.pl' ],
  'szunaj31@wp.pl pid-10500' => [ EMAIL => 'szunaj31@wp.pl' ],
  'tahir osman taos_tr@yahoo.com' => [ OPEN => 'Tahir Osman', EMAIL => 'taos_tr@yahoo.com' ],
  'tetea@speedy.com,ar' => [ EMAIL => 'tetea@speedy.com.ar' ],
  'this id is used by many  to make broadcasts, host tourneys- any queries send to admin@bilbridge.com' => [ EMAIL => 'admin@bilbridge.com' ],
  'thomas.b.ekblom@gmail,com' => [ EMAIL => 'thomas.b.ekblom@gmail.com' ],
  'tonsea tondano,kendis,gorontalo,.@.com' => [ CITY => 'Tondano', COUNTRY => 'Indonesia' ],
  'toulouse @ville rose .com' => [ CITY => 'Toulouse', COUNTRY => 'France' ],
  'tufan.ter..@mynet.com' => [ COUNTRY => 'Turkey' ],
  'ufum@hotmail.com bbo td' => [ EMAIL => 'utum@hotmail.com' ],
  'umypoppy@gmail.com. e' => [ EMAIL => 'umypoppy@gmail.com' ],
  'v ayhan325@gmail.com' => [ EMAIL => 'ayhan325@gmail.com' ],
  'vasvirv@otenet.gr sk.:vasmar44' => [ EMAIL => 'vasvir@otenet.gr' ],
  'vecdi.sezer@hotmail.comm' => [ EMAIL => 'vecdi.sezer@hotmail.com' ],
  'vera_mente_@live.it' => [ COUNTRY => 'Italy' ],
  'vic (vastj@wanadoo.fr' => [ EMAIL => 'vastj@wanadoo.fr' ],
  'vic sartor/vsartor77@aol.com' => [ OPEN => 'Vic Sartor', EMAIL => 'vsartor77@aol.com' ],
  'viren2512@yahoo.co,in' => [ EMAIL => 'viren2512@yahoo.co.in' ],
  'w.reszelski@o2.p 05348' => [ EMAIL => 'w.reszelski@o2.pl' ],
  'w.roj@wp.pl,pid 16248' => [ EMAIL => 'w.roj@wp.pl' ],
  'wake.advies@kpnmail' => [ EMAIL => 'wake.advies@kpnmail.nl' ],
  'watford@around.m25.london' => [ CITY => 'Watford', COUNTRY => 'England' ],
  'wkrzem51@wp.pl,td-ns6' => [ EMAIL => 'wkrzem51@wp.pl' ],
  'wojchr@op.pl warszawa' => [ EMAIL => 'wojchr@op.pl', CITY => 'Warsaw', COUNTRY => 'Poland' ],
  'wylly@interia.pl 10821' => [ EMAIL => 'wylly@interia.pl' ],
  'x ayhan325@gmail.com' => [ EMAIL => 'ayhan325@gmail.com' ],
  'xiao.bizi@163' => [ EMAIL => 'xiao.bizi@163.com' ],
  'xyshen@hotmail.c0m' => [ EMAIL => 'xyshen@hotmail.com' ],
  'y.ww@orange' => [ COUNTRY => 'France' ],
  'yaaay@wp.pl 10056' => [ EMAIL => 'yaaay@wp.pl' ],
  'yaegermbgc@aol.com leb;inv mn' => [ EMAIL => 'yaegermbgc@aol.com' ],
  'yaffad@013.net.ii' => [ EMAIL => 'yaffad@013.net.il' ],
  'yaseca@hotmail.com ( van' => [ EMAIL => 'yaseca@hotmail.com' ],
  'yhq3776@126.gom' => [ EMAIL => 'yhq3776@126.com' ],
  'ymfolan@yahoo.com bil' => [ EMAIL => 'ymfolan@yahoo.com' ],
  'yolande watelet.@yahoo.fr' => [ EMAIL => 'yolande watelet.@yahoo.fr' ],
  'zbs001@126.c0m' => [ EMAIL => 'zbs001@126.com' ],
  'zbynieks@op.pl, cezar 07936' => [ EMAIL => 'zbynieks@op.pl' ],
  'zetim@op.pl pid 1751' => [ EMAIL => 'zetim@op.pl' ],
  'zkrzepkowski@wp.pl 4329' => [ EMAIL => 'zkrzepkowski@wp.pl' ],
  'zoesa i x @ yahoo.com' => [ EMAIL => 'zoesaix@yahoo.com' ],
  'zubyz@seznam.cz mám i skype zdenda1202' => [ EMAIL => 'zubyz@seznam.cz' ],
);

our $MULTIPLES_HASH = \%MULTIPLES;

1;
