#!perl

package Email::Privates;

use strict;
use warnings;
use v5.10;
use utf8;
use open ':std', ':encoding(UTF-8)';

use Exporter;

our @ISA = qw(Exporter);
our @EXPORT = qw($PRIVATES_HASH);

my @PRIVATES = (
  '007@yahoo.com',
  '111@hotmail.com',
  '1231323i@hotmail.com',
  '123@hotmail.com',
  '1@hotmail.com',
  '2014@yahoo.com',
  '2016@yahoo.com',
  '22@yahoo.com',
  '31@hotmail.com',
  '777@yahoo.com',
  '@aol.com',
  '@bridgebase.com',
  '@libal-glass.eu',
  '@no.spam',
  '@yahoo.com',
  '@ymail.com',
  '___@gmail.com',
  'a@2line.net',
  'a@gmail.com',
  'a@hotmail.com',
  'a@yahoo.com',
  'aaaa@gmail.com',
  'aaaaaa@hotmail.com',
  'aaaaaaa@hotmail.com',
  'aaaaaaaaaaaa@hotmail.com',
  'ab@hotmail.com',
  'abc@abc.net',
  'abc@gmail.com',
  'abc@nbip.net',
  'ac@hotmail.com',
  'adventures@cardplay.org',
  'agent007_cool@hotmail.com',
  'agent0_37@hotmail.com',
  'anywhere@anymail.com',
  'ask me@hotmail.com',
  'ask me@o2.pl',
  'ask.me@tellyou',
  'ask@fri.net',
  'ask@pga.com',
  'askme@dontaskme.com',
  'askme@gmail.com',
  'b42@yahoo.com',
  'baboun@pourmes amis.com',
  'be cool@bbo.com',
  'be happy@fun.com',
  'be nice @ crazy . com',
  'blabla@hotmail.com',
  'bruce.springsteen@no',
  'bu@gmail.com',
  'chameleon @,hotmail.com',
  'd***head@hotmail.com',
  'd@32zuba.net',
  'dont.use@com',
  'dunno@pfbr.co',
  'emial@email.com',
  'fake@hotmail.com',
  'fidelcastro@mynet.com',
  'forg@th.at',
  'g;llum@yahoo.com',
  'ggggg@gmail.com',
  'gib@yahoo.com',
  'gmail@yahoo.com',
  'guess@mail.com',
  'hate-too-slow-players@yahoo.com',
  'i.am@not',
  'ignc-@msn.com',
  'improving@bridge.com',
  'inkognito2029@hotmail.com',
  'j@verizon.net',
  'kau tanya lah@ku.com',
  'louis@f.net',
  'm@aol.com',
  'mail@gmail.com',
  'mail@mail.com',
  'me@planetearth.com',
  'me@themoon.com',
  'momo@gmail.org',
  'moon@sun.com',
  'muffin@cookies.org',
  'must@some.com',
  'myemail@address.com',
  'n@n.com',
  'never@play.org',
  'nevermind@msn.com',
  'nn@web.com',
  'nn@yahoo.com',
  'no @no.com',
  'no.email@yahoo.com',
  'no.way@dot.com',
  'no@no.no',
  'nobody@nowhere.com',
  'nochat@bbo.org',
  'noemail@yahoo.com',
  'nomail@hotmail.com',
  'nomail@yahoo.com',
  'nome.cognome@tin.it',
  'non ricordo@quale.it',
  'non@mynet.com',
  'noname@free.fr',
  'noname@gmail.com',
  'none@hotmail.com',
  'none@none.com',
  'noreply@me.de',
  'nospam@spam.com',
  'not@first_meet.com',
  'notalways@exp.com',
  'nothing@all.com',
  'nothing@nothing.com',
  'privadof@hotmail.com',
  'private.kol@hotmail.com',
  'private@Private.com',
  'private@gmail..com',
  'private@gmail.com',
  'private@hotmail.com',
  'private@no.spam',
  'private@private.com',
  'r@hotmail.com',
  's.c.@gmail.com',
  's/h@gmail.com',
  's@gmail.com',
  'secret@free.com',
  'shis1@28.net',
  'somebody@hotmail.com',
  'someone@hotmail.com',
  'spam.me@now.com',
  'spam@junkmail.com',
  't@hotmail.com',
  'ts44@q.net',
  'unknown@yahoo.com',
  'vodkalover@absolut.com',
  'wong ilang@yahoo.co',
  'www163@.com',
  'wxy@wxy.org',
  'x@gmail.com',
  'x@y.net',
  'xx@hotmail.com',
  'xxx@gmail.com',
  'xxx@hotmail.com',
  'xxx@msn.com',
  'xxx@yahoo.com',
  'xxxfff@hotmail.com',
  'xxxx@yahoo.com',
  'xxxxx@gmail.com',
  'xxxxx@hotmail.com',
  'xxxxxx@hotmail.com',
  'xxxxxxxx@gmail.com',
  'xyz@.com',
  'xyz@hotmail.com',
  'y@d.com',
  'yes.i.can@always.com',
  'yes@maybe.no',
  'yeti@rockclimbing.org',
  'your.request@will.be.considered',
  'yz@hotmail.com',
  'zz@hotmail.com',
  'zzz@fff.com',
  'zzz@hotmail.com',
);

our $PRIVATES_HASH = { map { $_ => 1 } @PRIVATES };

1;
