#!perl

package Email::Users;

use strict;
use warnings;
use v5.10;
use utf8;
use open ':std', ':encoding(UTF-8)';

use Exporter;

our @ISA = qw(Exporter);
our @EXPORT = qw($USERS_HASH);

my %USERS =
(
  'a.c.g.huiskamp' => [ USER_INITIALS => 'A. C. G.', USER_LAST => 'Huiskamp' ],
  'abou_zeid_m_h' => [ USER_INITIALS => 'M. H.', USER_LAST => 'Abou Zeid' ],
  'ahmet.aziz.oglu' => [ USER_FIRST => 'Ahmet', USER_LAST => 'Azizoglu' ],
  'aida_de_san' => [ USER_FIRST => 'Aida', USER_PARTICLES => 'de', USER_LAST => 'San' ],
  'aks.arun.kumar.srivastava' => [ USER_FIRST => 'Arun Kumar', USER_LAST => 'Srivastava' ],
  'alain.antoine.simon' => [ USER_FIRST => 'Alain Antoine', USER_LAST => 'Simon' ],
  'alex.van.reenen' => [ USER_FIRST => 'Alex', USER_PARTICLES => 'van', USER_LAST => 'Reenen' ],
  'alexander.gb.gordy' => [ USER_FIRST => 'Alexander', USER_INITIALS => 'G. B.', USER_LAST => 'Gordy' ],
  'ana_maria_gradinariu' => [ USER_FIRST => 'Ana Maria', USER_LAST => 'Gradinariu' ],
  'ana_p_f_cabral' => [ USER_FIRST => 'Ana', USER_INITIALS => 'P. F.', USER_LAST => 'Cabral' ],
  'andrea.de.marinis' => [ USER_FIRST => 'Andrea', USER_PARTICLES => 'de', USER_LAST => 'Marinis' ],
  'ann.karin.fuglestad' => [ USER_FIRST => 'Ann Karin', USER_LAST => 'Fuglestad' ],
  'annick.michel.giraud' => [ USER_FIRST => 'Michel', USER_LAST => 'Giraud' ],
  'antonio_rocha_pinto' => [ USER_FIRST => 'Antonio', USER_LAST => 'Rocha Pinto' ],
  'ari.juuti.sten.aho' => [ USER_FIRST => 'Ari Juuti', USER_LAST => 'Sten-Aho' ],
  'arp.-ahmet' => [ USER_FIRST => 'Ahmet' ],
  'arthur.r.w.hughes' => [ USER_FIRST => 'Arthur', USER_INITIALS => 'R. W.', USER_LAST => 'Hughes' ],
  'asle.schanke.grude' => [ USER_FIRST => 'Asle', USER_LAST => 'Schanke Grude' ],
  'axel_kvist_nielsen' => [ USER_FIRST => 'Axel', USER_LAST => 'Kvist Nielsen' ],
  'b.curtet.yves' => [ USER_FIRST => 'Yves', USER_INITIALS => 'B.', USER_LAST => 'Curtet' ],
  'bernt.ivar.amundsen' => [ USER_FIRST => 'Bernt Ivar', USER_LAST => 'Amundsen' ],
  'besiktas_gnc_nobre' => [ USER_UNPARSEABLE => 'besiktas_gnc_nobre' ],
  'big.john.douglas' => [ USER_FIRST => 'John', USER_LAST => 'Douglas' ],
  'bjorn.erik.eliassen' => [ USER_FIRST => 'Bjorn Erik', USER_LAST => 'Eliassen' ],
  'boris_kotlarov_sz' => [ USER_FIRST => 'Boris', USER_LAST => 'Kotlarov' ],
  'brunet.marie-jeanne' => [ USER_FIRST => 'Marie-Jeanne', USER_LAST => 'Brunet' ],
  'c.christine.miller' => [ USER_INITIALS => 'C.', USER_FIRST => 'Christine', USER_LAST => 'Miller' ],
  'c.van.der.meijden' => [ USER_INITIALS => 'C.', USER_PARTICLES => 'van der', USER_LAST => 'Meijden' ],
  'c.w.van.schouwenburg' => [ USER_INITIALS => 'C. W.', USER_PARTICLES => 'van', USER_LAST => 'Schouwenburg' ],
  'cai_sun_yang' => [ USER_FIRST => 'Sun Yang', USER_LAST => 'Cai' ],
  'carmen.barbieri.f' => [ USER_FIRST => 'Carmen', USER_LAST => 'Barbieri' ],
  'claudia.yun.he' => [ USER_FIRST => 'Claudia Yun', USER_LAST => 'He' ],
  'cornut.marie-jean' => [ USER_FIRST => 'Marie-Jean', USER_LAST => 'Cornut' ],
  'crawford.mike.sd' => [ USER_FIRST => 'Mike', USER_LAST => 'Crawford' ],
  'das.ramprasad.kol' => [ USER_FIRST => 'Ramprasad', USER_LAST => 'Das' ],
  'devarajan.s.k' => [ USER_INITIALS => 'S. K.', USER_LAST => 'Devarajan' ],
  'deyan.p.g' => [ USER_FIRST => 'Deyan' ],
  'dr.op.mutlu' => [ USER_TITLE => 'Dr.', USER_INITIALS => 'O. P.', USER_LAST => 'Mutlu' ],
  'dupont.jean_pierre' => [ USER_FIRST => 'Jean-Pierre', USER_LAST => 'Dupont' ],
  'ej.van.os' => [ USER_FIRST => 'Edie', USER_PARTICLES => 'van', USER_LAST => 'Os' ],
  'else.marie.stuen' => [ USER_FIRST => 'Else-Marie', USER_LAST => 'Stuen' ],
  'erik.ten.oever' => [ USER_FIRST => 'Erik', USER_PARTICLES => 'ten', USER_LAST => 'Oever' ],
  'erkki.juuri-oja' => [ USER_FIRST => 'Erkki', USER_LAST => 'Juuri-Oja' ],
  'eva.b.m' => [ USER_FIRST => 'Eva' ],
  'eva.francoise.morel' => [ USER_FIRST => 'Eva Francoise', USER_LAST => 'Morel' ],
  'eva.lis.thuresson' => [ USER_FIRST => 'Eva Lis', USER_LAST => 'Thuresson' ],
  'ewita.b.m' => [ USER_FIRST => 'Ewita' ],
  'f.diz.acero' => [ USER_INITIALS => 'F.', USER_LAST => 'Diz Acero' ],
  'f_van_der_loo' => [ USER_INITIALS => 'F.', USER_PARTICLES => 'van der', USER_LAST => 'Loo' ],
  'fred.de.smeth' => [ USER_FIRST => 'Fred', USER_PARTICLES => 'de', USER_LAST => 'Smeth' ],
  'fred_durst_fen' => [ USER_UNPARSEABLE => 'fred_durst_fen' ],
  'fried.lm.peter' => [ USER_FIRST => 'Fried', USER_INITIALS => 'L.M.', USER_LAST => 'Peter' ],
  'g.v.d.hoeven' => [ USER_INITIALS => 'G.', USER_PARTICLES => 'van der', USER_LAST => 'Hoeven' ],
  'gaku.takeshi-ishizuka' => [ USER_FIRST => 'Gaku', USER_LAST => 'Takeshi Ishizuka' ],
  'garzena.jean-pierre' => [ USER_FIRST => 'Jean-Pierre', USER_LAST => 'Garzena' ],
  'geir.egil.bergheim' => [ USER_FIRST => 'Geir Egil', USER_LAST => 'Bergheim' ],
  'genc_fb_hasan' => [ USER_UNPARSEABLE => 'genc_fc_hasan' ],
  'georgi._rachev' => [ USER_FIRST => 'Georgi', USER_LAST => 'Rachev' ],
  'gillet.jean-paul' => [ USER_FIRST => 'Jean-Paul', USER_LAST => 'Gillet' ],
  'gula_ih_narsis' => [ USER_UNPARSEABLE => 'gula_ih_narsis' ],
  'guy.van.middelem' => [ USER_FIRST => 'Guy', USER_PARTICLES => 'van', USER_LAST => 'Middelem' ],
  'h.peter-mayr' => [ USER_INITIALS => 'H.', USER_LAST => 'Peter-Mayr' ],
  'hans.de.groot' => [ USER_FIRST => 'Hans', USER_PARTICLES => 'de', USER_LAST => 'Groot' ],
  'hans.en.co' => [ USER_FIRST => 'Hans' ],
  'hengky_c_g' => [ USER_FIRST => 'Hengky' ],
  'henk-alie.van.dijk' => [ USER_FIRST => 'Henk Alie', USER_PARTICLES => 'van', USER_LAST => 'Dijk' ],
  'her_man_be' => [ USER_FIRST => 'Herman' ],
  'hgm.vanden.heuvel' => [ USER_INITIALS => 'H. G. M.', USER_PARTICLES => 'van den', USER_LAST => 'Heuvel' ],
  'i.ivanov.ifo' => [ USER_INITIALS => 'I.', USER_LAST => 'Ivanov' ],
  'insan_ul_ayn' => [ USER_UNPARSEABLE => 'insan_ul_ayn' ],
  'j.h.a.warmerdam' => [ USER_INITIALS => 'J. H. A.', USER_LAST => 'Warmerdam' ],
  'j.ten.dam' => [ USER_INITIALS => 'J.', USER_PARTICLES => 'ten', USER_LAST => 'Dam' ],
  'j_tom_edwards' => [ USER_INITIALS => 'J.', USER_FIRST => 'Tom', USER_LAST => 'Edwards' ],
  'jack.yc.lai' => [ USER_FIRST => 'Jack', USER_INITIALS => 'Y. C.', USER_LAST => 'Lai' ],
  'jack_kl_wong' => [ USER_FIRST => 'Jack', USER_INITIALS => 'K. L.', USER_LAST => 'Wong' ],
  'jacques.saint-ges' => [ USER_FIRST => 'Jacques', USER_LAST => 'Saint-Georges' ],
  'jan.roger.stromsvaag' => [ USER_FIRST => 'Jan Roger', USER_LAST => 'Stromsvaag' ],
  'jean-paul-fremery' => [ USER_FIRST => 'Jean-Paul', USER_LAST => 'Fremery' ],
  'jean.claude.tremel' => [ USER_FIRST => 'Jean-Claude', USER_LAST => 'Tremel' ],
  'jean.michel.moulin' => [ USER_FIRST => 'Jean Michel', USER_LAST => 'Moulin' ],
  'jiang_yu_jie' => [ USER_FIRST => 'Yu Jie', USER_LAST => 'Jiang' ],
  'jmm.van.loon' => [ USER_INITIALS => 'J. M. M.', USER_PARTICLES => 'van', USER_LAST => 'Loon' ],
  'johan.de.ridder' => [ USER_FIRST => 'Johan', USER_PARTICLES => 'de', USER_LAST => 'Ridder' ],
  'john.hansen.srd' => [ USER_FIRST => 'John', USER_LAST => 'Hansen' ],
  'joke.v.d.poel' => [ USER_FIRST => 'Joke', USER_PARTICLES => 'van der', USER_LAST => 'Poel' ],
  'joop.van.der.harst' => [ USER_FIRST => 'Joop', USER_PARTICLES => 'van der', USER_LAST => 'Harst' ],
  'jorgen.v.d.berg' => [ USER_FIRST => 'Jorgen', USER_PARTICLES => 'van den', USER_LAST => 'Berg' ],
  'jostein.e.g' => [ USER_FIRST => 'Jostein' ],
  'k_ar_thik' => [ USER_FIRST => 'Karthik' ],
  'kraht.mietek.pawlicki' => [ USER_FIRST => 'Mietek', USER_LAST => 'Pawlicki' ],
  'laurent.le.foll' => [ USER_FIRST => 'Laurent', USER_PARTICLES => 'le', USER_LAST => 'Foll' ],
  'leif.allan.hugo' => [ USER_FIRST => 'Leif' ],
  'louis.rey-du-boissieu' => [ USER_FIRST => 'Louis', USER_LAST => 'Rey-du-Boisseau' ],
  'luis.ahrens.teixeira' => [ USER_FIRST => 'Luis', USER_LAST => 'Ahrens Teixeira' ],
  'luis_fdez_mun' => [ USER_FIRST => 'Luis', USER_LAST => 'Fernandez Munoz' ],
  'm.del.polito' => [ USER_INITIALS => 'M.', USER_PARTICLES => 'del', USER_LAST => 'Polito' ],
  'm.roovers-goverde' => [ USER_INITIALS => 'M.', USER_LAST => 'Roovers-Goverde' ],
  'marcelo_na_ar' => [ USER_FIRST => 'Marcelo', USER_LAST => 'Navajas' ],
  'marjou.marie.france' => [ USER_FIRST => 'Marie France', USER_LAST => 'Marjou' ],
  'mech_koushik_roy' => [ USER_FIRST => 'Koushik', USER_LAST => 'Roy' ],
  'mehmet_ali_gunduz' => [ USER_FIRST => 'Mehmet Ali', USER_LAST => 'Gunduz' ],
  'michel.gallois.sel' => [ USER_FIRST => 'Michel', USER_LAST => 'Gallois' ],
  'mieke.van.meyel' => [ USER_FIRST => 'Mieke', USER_PARTICLES => 'van', USER_LAST => 'Meyel' ],
  'mireia.poch.p' => [ USER_FIRST => 'Mireia', USER_LAST => 'Poch' ],
  'miren.jean.marie' => [ USER_FIRST => 'Jean Marie', USER_LAST => 'Miren' ],
  'moreaux.jean-michel' => [ USER_FIRST => 'Jean-Michel', USER_LAST => 'Moreaux' ],
  'mustafa_atalar_bayraktar' => [ USER_FIRST => 'Mustafa', USER_LAST => 'Atalar Bayraktar' ],
  'nervt_mich_nicht' => [ USER_UNPARSEABLE => 'nervt_mich_nicht' ],
  'nicola.bernardi.pd' => [ USER_FIRST => 'Nicola', USER_LAST => 'Bernardi' ],
  'nicole.van-poperinghe' => [ USER_FIRST => 'Nicole', USER_PARTICLES => 'van', USER_LAST => 'Poperinghe' ],
  'ole.jorgen.olsen' => [ USER_FIRST => 'Ole Jorgen', USER_LAST => 'Olsen' ],
  'olivier.de-mourgues' => [ USER_FIRST => 'Olivier', USER_PARTICLES => 'de', USER_LAST => 'Mourgues' ],
  'orville_st.clair' => [ USER_FIRST => 'Orville', USER_LAST => 'St. Clair' ],
  'palle.holm.pedersen' => [ USER_FIRST => 'Palle', USER_LAST => 'Holm Pedersen' ],
  'pantek_amak_ang' => [ USER_UNPARSEABLE => 'pantek_amak_ang' ],
  'pantek_amak_kau' => [ USER_UNPARSEABLE => 'pantek_amak_kau' ],
  'pasquale.nigri.ice' => [ USER_FIRST => 'Pasquale', USER_LAST => 'Nigri' ],
  'pat_mary_mc' => [ USER_FIRST => 'Pat', USER_LAST => 'McCarthy' ],
  'patrice_bernard.fontaine' => [ USER_FIRST => 'Patrice Bernard', USER_LAST => 'Fontaine' ],
  'per.reidar.karlsen' => [ USER_FIRST => 'Per Reidar', USER_LAST => 'Karlsen' ],
  'philippe.ferrari.lecomm' => [ USER_FIRST => 'Philippe', USER_LAST => 'Ferrari' ],
  'pirjo.juuri-oja' => [ USER_FIRST => 'Pirjo', USER_LAST => 'Juuri-Oja' ],
  'r.schol.r' => [ USER_UNPARSEABLE => 'r.schol.r' ],
  'rem.van.hooff' => [ USER_FIRST => 'Rem', USER_PARTICLES => 'van', USER_LAST => 'Hooff' ],
  'rich_p_j' => [ USER_FIRST => 'Rich', USER_INITIALS => 'P.', USER_LAST => 'Johnson' ],
  'rinus.en.len' => [ USER_FIRST => 'Rinus' ],
  'rita.morbee-willems' => [ USER_FIRST => 'Rita', USER_LAST => 'Morbee-Williams' ],
  'robert.von-essen' => [ USER_FIRST => 'Robert', USER_PARTICLES => 'von', USER_LAST => 'Essen' ],
  'rosaria.maria-varriale' => [ USER_FIRST => 'Rosaria', USER_LAST => 'Maria Varriale' ],
  'ross.sandra.whyard' => [ USER_FIRST => 'Ross', USER_LAST => 'Whyard' ],
  'ruei.wen.chu' => [ USER_FIRST => 'Ruei Wen', USER_LAST => 'Chu' ],
  's_james_elliott' => [ USER_INITIALS => 'S.', USER_FIRST => 'James', USER_LAST => 'Elliott' ],
  'sam_low_a' => [ USER_FIRST => 'Sam' ],
  'samir.kr.chakraborty' => [ USER_FIRST => 'Samir', USER_INITIALS => 'K. R.', USER_LAST => 'Chakraborty' ],
  'serdar.ozkan.omeroglu' => [ USER_FIRST => 'Serdar Özkan', USER_LAST => 'Omeroglu' ],
  'sicilia.vacanze.pascianero' => [ USER_LAST => 'Pascianero' ],
  'sidney.liu.sh' => [ USER_FIRST => 'Sidney', USER_LAST => 'Liu' ],
  'simian.anne-marie' => [ USER_FIRST => 'Anne-Marie', USER_LAST => 'Simian' ],
  'stephen_yk_liu' => [ USER_FIRST => 'Stephen', USER_INITIALS => 'Y. K.', USER_LAST => 'Liu' ],
  'steve_de_roos' => [ USER_FIRST => 'Steve', USER_PARTICLES => 'de', USER_LAST => 'Roos' ],
  'sun_kun_luck' => [ USER_UNPARSEABLE => 'sun_kun_luck' ],
  'tedi_a_g' => [ USER_INITIALS => 'A. G.', USER_LAST => 'Tedi' ],
  'terry_king_cn' => [ USER_FIRST => 'Terry', USER_LAST => 'King' ],
  'teunis.v.o' => [ USER_FIRST => 'Teunis' ],
  'tomas.es.lindqvist' => [ USER_FIRST => 'Tomas', USER_INITIALS => 'E. S.', USER_LAST => 'Lindqvist' ],
  'tonko.ko_tonkov' => [ USER_FIRST => 'Tonko', USER_LAST => 'Tonkov' ],
  'tore.vidar.e' => [ USER_FIRST => 'Tore Vidar', USER_LAST => 'Ellefsen' ],
  'tuncay_ozkan_izmir' => [ USER_FIRST => 'Tuncay', USER_LAST => 'Özkan', EMAIL_CITY => 'Izmir' ],
  'ufuktaki_sessiz_gemi' => [ USER_UNPARSEABLE => 'ufuktaki_sessiz_gemi' ],
  'vinay.vs.kumar' => [ USER_FIRST => 'Vinay', USER_INITIALS => 'V. S.', USER_LAST => 'Kumar' ],
  'vincent_de_pagter' => [ USER_FIRST => 'Vincent', USER_PARTICLES => 'de', USER_LAST => 'Pagter' ],
  'vincenzo.la.salapcnb' => [ USER_FIRST => 'Vincenzo', USER_PARTICLES => 'la', USER_LAST => 'Sala' ],
  'wang_w_d' => [ USER_INITIALS => 'W. D', USER_LAST => 'Wang' ],
  'willy.vande.vijver' => [ USER_FIRST => 'Willy', USER_PARTICLES => 'van de', USER_LAST => 'Vijver' ],
  'www.fusc-ba' => [ USER_UNPARSEABLE => 'www.fusc-ba' ],
  'y.m-peti' => [ USER_FIRST => 'Yusuf', USER_LAST => "M'Peti" ],
  'yin_yu_lin' => [ USER_FIRST => 'Yin Yu', USER_LAST => 'Lin' ],
  'z_zahariev_vd' => [ USER_INITIALS => 'Z.', USER_LAST => 'Zahariev' ],
  'zafer_murat_oglu' => [ USER_FIRST => 'Zafer', USER_LAST => 'Muratoglu' ],
  'zatorski.piotr.pawel' => [ USER_FIRST => 'Piotr Pawel', USER_LAST => 'Zatorski' ],
);

our $USERS_HASH = \%USERS;

sub lookup
{
  my ($user) = @_;
  if (exists $USERS_HASH->{$user})
  {
    return $USERS_HASH->{$user};
  }
  else
  {
    return '';
  }
}

1;
