#!perl

use strict;
use warnings;
use v5.10;
use utf8;
use open ':std', ':encoding(UTF-8)';

package Team::Matrix;

our @ISA = qw(Exporter);
our @EXPORT = qw(set_matrix);

use lib '.';
use TeamBBO;


my %COUNTRY_TO_CITY =
(
  Argentina => ['buenos aires'],
  Australia => [
    'adelaide', 'brisbane', 'cairns', 'canberra',
    'melbourne', 'perth', 'sydney'],
  Austria => ['Vienna'],
  Belarus => ['minsk'],
  Belgium => ['antwerpen', 'brussels', 'gent', 'leuven'],
  Brazil => ['assis', 'belo horizonte', 'brasilia', 'pelotas',
    'são paulo'],
  Bulgaria => ['asenovgrad', 'balchik', 'dimitrovgrad', 'dobrich', 
  'kesten', 'kyustendil', 'la marina', 'pelotas', 'pernik', 'pleven', 
    'plovdiv', 'popovo', 'sofia', 'stara zagora', 'varna', 'vraca',
    'yambol'],
  Chile => ['paimado', 'santiago', 'temuco'],
  China => [
    'beijing', 'changzhou', 'chengdu', 'chongqing', 'dalian', 'dongguan',
    'guangzhou', 'hangzhou', 'jiamusi', 'jianshe', 'jiangsu', 'jiangyou',
    'jinchang', 'jincheng', 'jinjiang', 'jiujiang', 'kunchan', 'lanzhou',
    'liushu', 'meilin qingcheng', 'nanchang', 'nanning', 'ningbo',
    'panzhihua', 'qingdao', 'sanya', 'shanghai', 'shaoguan', 'shenyang',
    'shenzhen', 'shijiazhuang', 'suzhou', 'taicang', 'taizhou',
    'tianjin', 'wuhan', 'wuxi', 'xin zhu', 'xinyi', 'yanshi', 'ye chi', 
    'zhaoqing', 'zhong jian', 'zhongshan', 'zhuzhou', 'zigong'],
  Colombia => ['bogotá'],
  'Costa Rica' => ['heledia'],
  Croatia => ['pula', 'rijeka', 'split', 'zagreb'],
  Cyprus => ['nicosia'],
  'Czech Republic' => ['nové město', 'prague'],
  Denmark => [
    'aabenraa', 'aalborg', 'ballerup', 'copenhagen', 'esbjerg',
    'greve strand', 'haderslev', 'herning', 'hillerød', 'hornbæk', 
    'kalundborg', 'morud', 'næstved', 'odense', 'ravnkilde', 'rødovre', 
    'slagelse', 'åkirkeby', 'århus'],
  Ecuador => ['guayaquil'],
  Egypt => ['al-rabwa', 'alexandria', 'cairo', 'el-maadi'],
  England => ['altrincham', 'bath', 'canterbury', 'coventry',
    'eastbourne', 'lincoln', 'london', 'manchester', 'oxford',
    'petersfield', 'worcester'],
  Estonia => ['derpt', 'otepää', 'pärnu', 'rakvere', 'sindi', 'tallinn'],
  Finland => ['helsinki', 'lappeenranta', 'kuopio', 'vasa'],
  France => [
    'aix en provence', 'annecy', 'antony', 'bergues', 'bordeaux', 
    'caen', 'chaville', 'clichy', 'courseulles-sur-mer', 'le bouscat', 
    'lille', 'lyon', 'massy', 'montpellier', 'nancy', 'palaiseau', 
    'paris', 'reims', 'toulouse', 'val de seine'],
  Germany => ['bamberg', 'berlin', 'bielefeld', 'bonn', 'bremen',
    'burghausen', 'darmstadt', 'düsseldorf', 'essen', 'frankfurt', 
    'hamburg', 'hannover', 'karlsruhe', 'ketsch', 'kiel', 'köln', 
    'leverkusen', 'mannheim', 'munich', 'nürnberg', 'oldenburg',
    'potsdam', 'saarbrücken', 'stuttgart'],
  Greece => ['athens', 'nea moudania', 'thessaloniki'],
  Hungary => ['budapest', 'gyor', 'nagykanizsa', 'pecs', 'szeged'],
  India => [
    'ahmedabad', 'allahabad', 'ambon', 'bangalore', 'bansi', 'bhilwara', 
    'bhubaneshwar', 'bikaner', 'chennai', 'dombivli', 'kalyani', 
    'kanpur', 'kashi', 'kolkata', 'mitra vihar', 'mumbai', 'nagpur', 
    'nashik', 'pune', 'puri', 'sukma', 'udaipur'],
  Indonesia => [ 
    'airmadidi', 'balikpapan', 'banda aceh', 'bandar lampung', 'bandung',
    'banjarmasin', 'batam', 'batu', 'bekasi', 'bengkulu', 'bitung', 
    'blitar', 'bogor', 'boven digoel', 'cirebon', 'delhi', 'depok',
    'gresik', 'hatay', 'jakarta', 'jember', 'kedungwaru', 'klabat', 
    'kota bandung', 'kota bekasi', 'kota bogor', 'kota mataram', 
    'kudus', 'langkat', 'lhokseumawe', 'lumajang', 'magetan',
    'makassar', 'malang', 'manado', 'mandobo bodi', 'martapura', 
    'medan', 'moradabad', 'muara bungo', 'padang', 'palembang', 
    'palu', 'pariaman', 'pekanbaru', 'penajam', 'pontianak', 
    'samarinda', 'secunderabad', 'semarang', 'semburat jingga', 
    'serang', 'seulawah agam', 'siddha eden lakeville', 'sidoarjo', 
    'sleman', 'solok', 'sukomoro', 'surabaya', 'tanjung pinang', 
    'thane', 'thanjavur', 'tomohon', 'yogyakarta'],
  Iraq => ['baghdad'],
  Italy => [
    'bologna', 'catania', 'cuneo', 'fabbriche', 'firenze', 'genoa',
    'lucignano', 'milan', 'monticiano', 'napoli', 'padova', 'palermo', 
    'pesaro',
    'pescara', 'pisa', 'reggio emilia', 'rimini', 'rome', 
    'salerno', 'san giorgio del sannio', 'siena', 'torino', 'trieste',
    'varese'],
  Japan => ['narita', 'takayama', 'tokyo', 'yokohama'],
  Kazakhstan => ['aral'],
  Latvia => ['riga'],
  Lithuania => ['alytus', 'vilnius'],
  Malaysia => ['kuala lumpur'],
  Mexico => ['jalisco'],
  Monaco => ['monte carlo'],
  Netherlands => ['amsterdam', 'delft', 'leiden', 'maastricht', 
    'nijmegen', 'the hague', 'utrecht'],
  'New Zealand' => ['auckland', 'wellington'],
  'North Macedonia' => ['gevgelija', 'skopje'],
  Norway => [
    'arendal', 'bergen', 'bodø', 'brandbu', 'farsund', 'flekkefjord', 
    'gudbrandsdal', 'gjøvik og vardal', 'hamar', 'heimdal', 
    'huldretråkket', 'jessheim', 'kirkeby', 'kolbotn', 'kristiansand', 
    'kverndalen', 'kølabånn', 'namsos', 'narvik', 'nærbø', 'nøtterøy', 
    'ogndal', 'oslo', 'ottadalen', 'sandefjord', 'sarpsborg', 'singsås', 
    'skien', 'sortland', 'stavanger', 'steinkjer', 'sunndalsøra', 
    'sørreisa', 'trondheim', 'tromsø', 'vestfold', 'vestvågøy', 
    'vikersund', 'ørland'],
  Peru => ['ayacucho', 'lima'],
  Poland => ['chelmno', 'elblag', 'gdansk', 'gdynia', 'gorzow',
    'kalisz', 'katowice', 'kielce', 'kornik', 'krakow', 'leszno',
    'lodz', 'lowicz', 'lublin', 'olsztyn', 'poznan', 'rzeszow',
    'silesia gliwice', 'skawina', 'tarnów', 'warsaw', 'wisla',
    'wroclaw', 'zyrardow'],
  Portugal => ['cascais', 'porto'],
  Romania => ['braila', 'brasov', 'bucharest', 'cluj', 'iasi',
    'piatra neamt', 'sibiu', 'targoviste', 'timisoara'],
  Russia => ['lokotok', 'saint petersburg'],
  Serbia => ['belgrade', 'beograd', 'jagodina', 'niš', 'novi sad', 
    'pancevo', 'vrnjacka banja'],
  Singapore => ['singapore city'],
  Slovakia => ['kosice', 'michalovce'],
  Slovenia => ['ljubljana'],
  Spain => ['barcelona', 'begues', 'cuenca', 'madrid', 'marbella',
    'palma', 'sabadell'],
  South Africa => ['durban'],
  Sweden => [
    'bromölla', 'gnesta', 'harplinge', 'lerum', 'malmö', 'näsby', 
    'norrbyskär', 'norrøna', 'storsjöbygden', 'stureby', 'skara', 
    'täby', 'täfteå', 'uppsala', 'varberg', 'västervik', 'överum'],
  Switzerland => ['la chaux-de-fonds', 'nyon'],
  Taiwan => ['changhua', 'chiayi', 'hsinchu', 'keelung', 'miaoli', 
    'taichung', 'tainan', 'taipei city', 'new taipei city'],
  Thailand => ['bangkok', 'chumphon', 'pattaya', 'rayong', 'udon thani'],
  Turkmenistan => ['bereket'],
  Turkey => ['adana', 'akhisar', 'ankara', 'antalya', 'aydin', 'ayvalik', 
    'balikesir', 'bodrum', 'burdur', 'bursa', 'cerkezkoy', 'cesme', 
    'corlu', 'datca', 'denizli', 'diyarbakir', 'edirne',
    'eskisehir', 'fethiye', 'foca', 'gaziantep zeugma', 'geyve',
    'gölcük', 'iskenderun', 'istanbul', 'izmir', 'kadirli', 
    'kastamonu', 'kayseri', 'kirklarelý', 'kirsehir', 'kocaeli', 
    'konak', 'konya', 'koycegiz', 'kusadasi', 'kütahya', 'luleburgaz', 
    'malatya', 'manisa', 'mersin', 'midyat', 'milas', 'muðla', 
    'nazilli', 'orhangazi', 'sakarya', 'samsun', 'seferihisar', 'söke', 
    'tekýrdag', 'tire', 'usak', 'van', 'yatagan', 'yedi eylul'],
  Ukraine => ['kiev'],
  USA => ['amarillo', 'berkeley', 'chicago', 'evanston', 'ithaca', 
    'kansas city', 'new york city', 'st louis', 'stanford'],
  Venezuela => ['caracas']
);


my %CITY_TO_QUARTER =
(
  Ankara => ['çayyolu', 'kardelen', 'sansar'],
  Antalya => ['muratpasa'],
  Aydin => ['bozdogan'],
  Baghdad => ['akkad'],
  Balchik => ['albena'],
  Beijing => ['shihua', 'yizhuang', 'yuquan'],
  Bekasi => ['tambun'],
  Bodrum => ['gundogan', 'yalikavak'],
  Bogotá => ['tequendama'],
  Brussels => ['uccle'],
  'Buenos Aires' => ['recoleta'],
  Bursa => ['yenisehir', 'yildirim'],
  Cairo => ['maadi'],
  Cirebon => ['losari'],
  'Courseulles-sur-Mer' => ['courseulles'],
  Denizli => ['akçeşme', 'pamukkale'],
  Eskisehir => ['viþnelik'],
  Frankfurt => ['freidorf'],
  Gevgelija => ['mrzenci'],
  Guangzhou => ['zhujiang'],
  Hamar => ['ridabu'],
  Hatay => ['karaçay'],
  Istanbul => ['atakoy', 'bahce', 'bahcesehir', 'bayrampaþa',
    'bogazici', 'bormali', 'esenkent', 'fatih', 'kadikoy', 'kartal',
    'kocamustafapasa', 'kucukcekmece', 'küp', 'pasham', 'polonezkoy',
    'suralaya', 'taskopru', 'yarimada'],
  Izmir => ['balcova', 'bornova', 'buca', 'ege', 'karsiyaka',
    'konak', 'narlidere', 'sirinyer'],
  Jakarta => ['makaliwe', 'senayan'],
  Jalisco => ['perula'],
  Jember => ['arjasa'],
  Katowice => ['slaska'],
  Kayseri => ['pinarbasi'],
  Kocaeli => ['yarýmca'],
  Krakow => ['korwin'],
  Lappeenranta => ['lappee'],
  London => ['chelsea', 'chislehurst'],
  Lublin => ['sarniak'],
  Lyon => ['brotteaux'],
  Magetan => ['sukomoro'],
  Manado => ['leilem', 'manahasa'],
  Medan => ['cemara', 'simal'],
  Mersin => ['meski'],
  Monticiano => ['piloni'],
  Mumbai => ['borivli'],
  Nancy => ['jarville'],
  'Nea Moudania' => ['moudania'],
  Nicosia => ['katok'],
  Niš => ['niski'],
  'Nové Město' => ['radkov'],
  Pattaya => ['jomtien'],
  Plevel => ['kaylaka'],
  Poznan => ['wroble'],
  Pune => ['amanora'],
  Rome => ['olgiata', 'parioli'],
  Sabadell => ['sabadel'],
  Sanya => ['tianya'],
  'São Paulo' => ['unaós'],
  Semarang => ['poncol'],
  Shanghai => ['pudong', 'qiaoxie'],
  'Singapore City' => ['tengah'],
  Sofia => ['lozenets', 'serdika', 'sredec'],
  'Stara Zagora' => ['beroe'],
  Sumedang => ['wadas'],
  Tallinn => ['männiku'],
  Tekýrdag => ['suleymanpasa'],
  'The Hague' => ['buitenhof'],
  Tianjin => ['huochetou'],
  Thessaloniki => ['lemvourgeio' ],
  Toulouse => ['baragnon'],
  Varberg => ['varbergshus'],
  Varna => ['avren'],
  Warsaw => ['bieniewo', 'unia'],
  Wroclaw => ['wratislavia'],
  Wuxi => ['taihu'],
);


# Redundant.
my %COUNTRY_TO_QUARTER =
(
  Argentina => ['recoleta'],
  Belgium => ['uccle'],
  Brazil => ['unaós'],
  Bulgaria => ['albena', 'avren', 'beroe', 'kaylaka', 'lozenets',
    'serdika', 'sredec'],
  'Czech Republic' => ['radkov'],
  China => ['pudong', 'qiaoxie', 'shihua', 'taihu', 'tianya',
    'yizhuang', 'yuquan', 'zhujiang'],
  Colombia => ['tequendama'],
  Cyprus => ['katok'],
  Egypt => ['maadi'],
  England => ['chelsea', 'chislehurst'],
  Estonia => ['männiku'],
  Finland => ['lappee'],
  France => ['baragnon', 'brotteaux', 'courseulles'],
  Germany => ['freidorf'],
  Greece => ['lemvourgeio', 'moudania'],
  India => ['amanora', 'borivli'],
  Indonesia => ['arjasa', 'cemara', 'leilem', 'losari', 'makaliwe',
    'manahasa', 'poncol', 'senayan', 'simal', 'sukomoro', 'sumedang',
    'tambun', 'wadas'],
  Iraq => ['akkad'],
  Italy => ['olgiata', 'parioli', 'piloni'],
  Mexico => ['perula'],
  Netherlands => ['buitenhof'],
  'North Macedonia' => ['mrzenci'],
  Norway => ['ridabu'],
  Poland => ['bieniewo', 'korwin', 'sarniak', 'slaska', 'unia',
    'wratislavia', 'wroble'],
  Serbia => ['niski'],
  Singapore => ['tengah'],
  Spain => ['sabadel'],
  Sweden => ['varbergshus'],
  Thailand => ['jomtien'],
  Turkey => ['akçeşme', 'atakoy', 'bahce', 'bahcesehir', 'balcova',
    'bayrampaþa', 'bogazici', 'bormali', 'bornova', 'bozdogan', 'buca',
    'çayyolu', 'ege', 'esenkent', 'fatih', 'gundogan', 'kadikoy',
    'karaçay', 'kardelen', 'karsiyaka', 'kartal', 'kocamustafapasa', 
    'konak', 'kucukcekmece', 'küp', 'meski', 'muratpasa', 'narlidere',
    'pamukkale', 'pasham', 'pinarbasi', 'polonezkoy', 'sansar',
    'sirinyer', 'suleymanpasa', 'suralaya', 'taskopru', 'viþnelik',
    'yalikavak', 'yarimada', 'yarýmca', 'yenisehir', 'yildirim']
);


my %COUNTRY_TO_REGION =
(
  Australia => ['australian central territory', 'new south wales',
    'northern territory', 'queensland', 'south australia', 
    'tasmania', 'victoria', 'western australia'],
  Austria => ['oberloiben'],
  Belarus => ['druts'],
  China => ['anhui', 'fukien', 'gansu', 'guangdong', 'guangxi',
    'guizhou', 'hainan', 'haixing', 'hebei', 'hunan', 'jiangsu',
    'jilin', 'liaoning', 'pearl river', 'ren shou', 'shanxi', 
    'sichuan', 'taihu lake', 'tianya', 'tinglin', 'wujin', 'yongjia',
    'yunnan', 'zhejiang'],
  Colombia => ['tequendama'],
  Denmark => ['bornholm', 'midtsjælland', 'sydvest'],
  France => ['corsica', 'new caledonia'],
  Iceland => ['eyjafjallajokull'],
  Hungary => ['hegyvidék'],
  India => ['bihar', 'ganges', 'goa', 'gujarat', 'jharkhand',
    'karnataka', 'kerala', 'madhya pradesh', 'maharashtra', 'nagbagan', 
    'punjab', 'rajasthan', 'rajputana', 'tamil nadu', 'uttar pradesh', 
    'uttarakhand', 'west bengal'],
  Indonesia => ['bali', 'banten', 'bekasi regency', 'belitung',
    'bengkayang', 'bisma semarang', 'boeven digoel', 'bogor regency', 
    'bone bolango', 'bungo', 'central celebes', 'central java', 
    'central sulawesi', 'cianjur regency', 'east borneo', 'east jakarta', 
    'east java', 'east kalimantan', 'gabungan malaku', 'garut regency', 
    'gorontalo', 'java bali', 'karimun', 'kawanua', 'kayong',
    'kedungwaru', 'kepri', 'kepulauan riau', 'kutai kartanegara', 
    'lampung', 'lebak', 'lombok', 'lumajang', 'malaku', 'minahasa',
    'north minahasa', 'north celebes', 'north sulawesi', 
    'nusa tenggara barat', 'nusantara', 'papua', 'porong', 'sintang',
    'south celebes', 'south east celebes', 'south jakarta',
    'south kalimantan', 'south sulawesi', 'south sumatra', 'tambun',
    'west borneo', 'west java', 'west kalimantan', 'west sumatra'],
  Iraq => ['akkad'],
  Italy => ['liguria', 'val di magra'],
  Japan => ['kansai'],
  'New Zealand' => ['central districts', 'otago', 'southland', 'waikato'],
  Norway => ['agder', 'buskerud', 'haugaland', 'midt trøndelag', 
    'mjøsa', 'møre romsdal', 'nord-norge omegn', 'nordafjells', 
    'rogaland', 'rosfjord', 'salten', 'telemark', 'troms og ofoten', 
    'vest agder', 'vest finnmark', 'østfold follo'],
  Pakistan => ['sindh'],
  'Papua New Guinea' => ['western province'],
  Poland => ['lower silesia', 'silesia', 'slask'],
  Portugal => ['norte ilhas'],
  Russia => ['siberia'],
  Scotland => ['ayrshire'],
  Serbia => ['vojvodina'],
  Singapore => ['tengah'],
  'South Africa' => ['central gauteng', 'eastern cape',
    'northern gauteng'],
  'South Korea' => ['silla'],
  Sweden => ['norrland', 'norrorts', 'skåne', 'south sweden'],
  Taiwan => ['west district'],
  Thailand => ['krabi', 'nakhon nayok', 'ratchaburi', 'samut prakan', 
    'samut sakhon', 'suphan buri'],
  Turkey => ['akdeniz', 'cappadocia', 'central anatolia', 'dersým',
    'hatay', 'kinali', 'marmara', 'muallim', 'munzur', 'mysia',
    'orontes', 'taskopru', 'tigris', 'tuncelý'],
  USA => ['district of columbia', 'florida'],
  Zimbabwe => ['matopos']
);


my %CITY_TO_UNIVERSITY =
(
  Airmadidi => ['Airmadidi Senior High School'],
  Ankara => ['Ankara University', 'Bilkent University',
    'Middle East Technical University'],
  Antalya => ['Akdeniz University', 'Antalya Halk Egitim'],
  Antwerp => ['Karel de Grote'],
  Bandung => ['Telkom University'],
  Batu => ['batusida senior high school'],
  Beijing => ['Ren Da Fu Zhong', 'china central university of business'],
  Bengkulu => ['bengkulu senior high school'],
  Berkeley => ['University of California at Berkeley'],
  Bogor => ['bogor senior high school'],
  Budapest => ['Budapest University'],
  Changhua => ['Chien Kuo Senior High School'],
  'Chapel Hill' => ['University of North Carolina'],
  Chiayi => ['National Chung Cheng University'],
  Chicago => ['University of Chicago'],
  Depok => ['gunadarma university', 'gunadarma'],
  Durban => ['KwaZulu Natal'],
  Edime => ['Trakya University'],
  Eskisehir => ['Anadolu University', 'Osmangazi University'],
  Evanston => ['Northwestern University'],
  Gdansk => ['University of Gdansk'],
  Gresik => ['Universitas Muhammadiyah Gresik'],
  Hamburg => ['UBC Hamburg'],
  Hsinchu => ['Chung Hua University',
    'National Chiao Tung University',
    'National Tsing Hua University'],
  Istanbul => ['ITÜ Vakfi', 'Koc University', 
    'Yildiz Technical University'],
  Ithaca => ['Cornell University'],
  Izmir => ['Ege University'],
  Jakarta => ['Gunadurma', 'ITS IKOMA', 'Kusuma Bangsa',
    'Nahdlatul Ulama Alumni', 'Sekolah Tinggi Ilmu Statistik',
    'Sekolah Tinggi Teknologi'],
  Jember => ['University of Jember', 'Jember Senior High School'],
  Jiangsu => ['Jiangsu Tianyi'],
  Kedungwaru => ['kedungwaru senior high school'],
  Keelung => ['National Taiwan Ocean University'],
  Kirsehir => ['Kirsehir Republic Primary School'],
  Kocaeli => ['Kocaeli University'],
  Konya => ['Selçuk University'],
  Krakow => ['AGH Krakow'],
  Langkat => ['Langkat Senior High School'],
  Leuven => ['KU Leuven'],
  Lumajang => ['lumajang senior high school'],
  Makassar => ['Makassar University'],
  Malang => ['Brawijaya University'],
  Manado => ['Manado State University', 'Sam Ratulangi University'],
  Medan => ['Universitas Sumatera Utara'],
  Mersin => ['Tarsus American College'],
  Miaoli => ['Miaoli Senior High School'],
  'New Taipei City' => ['Fu Jen Catholic University'],
  'New York City' => ['Columbia University'],
  Nijmegen => ['radboud university', 'radboud'],
  Padang => ['Andalas University', 'University of Bung Hatta'],
  Paris => ['Paris ECE'],
  Palaiseau => ['École Polytechnique'],
  Palembang => ['Universitas Sriwijaya'],
  Pekanbaru => ['Riau University', 'Universitas Riau Bridge Club'],
  Pontianak => ['University of Tanjungpura'],
  Porto => ['University of Porto'],
  Potsdam => ['Universität Potsdam'],
  Rijeka => ['University of Rijeka'],
  Semarang => ['Diponegoro University'],
  Shenyang => ['Shenyang Ligong'],
  Stanford => ['Stanford University'],
  Sukomoro => ['sukomoro senior high school'],
  Surabaya => ['University of Airlangga', 'University of Surabaya',
    'Surabaya Senior High School'],
  Taichung => ['Chung Hwa Medical and Pharmaceutical University',
    'National Chung Hsing University'],
  'Taipei City' => ['National Chengchi University',
    'National Taiwan Normal University',
    'National Taiwan University',
    'Soochow University'],
  Targoviste => ['Valahia University'],
  Tyoyuan => ['Chang Gung University'],
  Umeå => ['Umeå University'],
  'Urbana-Champaign' => ['University of Illinois'],
  Waltham => ['Brandeis'],
  Warsaw => ['University of Warsaw', 'Warsaw University of Technology'],
  Wroclaw => ['University of Wroclaw',
    'Wroclaw University of Science and Technology'],
  Yogyakarta => ['Universitas Gadjah Mada'],
  Zagreb => ['Croatia University', 'Zagreb University'],
);


# TODO Are these all cities?

my %CITY_TO_CLUB =
(
  Aachen => ['Aachener'],
  Ada => ['Ada Briç SK'],
  Amsterdam => ['Trifolium'],
  Ankara => ['Ankara Kontrat', 'Ankara Sistematik', 'Baþkent Sekans BSK',
    'BH Koru BK'],
  Antalya => ['Antalya BSK', 'Antalya Tabip Odasi'],
  Augsburg => ['Augsburg Augusta'],
  Aydin => ['Aydin 1923 BBSK'],
  Bamberg => ['Bamberger Reiter'],
  Bangkok => ['Bangkok Bridge Club', 'RBSC Polo Club'],
  Barcelona => ['BCN Almirall', 'Bridge Turó'],
  Batman => ['Batman Genclik'],
  Beijing => ['Beijing Baxi Football'],
  Beirut => ['Hamra Club'],
  Belgrade => ['Crvena Zvezda'],
  Bergen => ['Bergen Akademiske', 'Åsane'],
  Berlin => ['BC 52 Berlin'],
  Bhubaneswar => ['Odisha Secretariat Recreation Club'],
  'Bielsko-Biala' => ['Bielski Klub Brydżowy GOK cards'],
  Brussels => ['Brussels Bridge Club'],
  Bucharest => ['ATU Bucharest', 'Romana'],
  Burdur => ['Bucak Bel.'],
  Bursa => ['BSB Kurek Ihtisas', 'Nilüfer Bld. BSK', 'Tofas',
    'Yildirimspor'],
  Bytom => ['BUKS Bytom'],
  Cairo => ['El Ahly', 'El Shams Club', 'Wadi Degla'],
  Cannareggio => ['Circolo del Bridge Cannareggio'],
  Cimahi => ['GB Cimahi'],
  Copenhagen => ['One Eyed Jacks'],
  Darmstadt => ['Darmstadt Alert'],
  Debrecen => ['Debrecen DEAC'],
  Delhi => ['Delhi Gymkhana Club'],
  Diyarbakir => ['Diyarbakýr Sur BSK', 'Dýcle Gençlýk'],
  Drammen => ['Drammen Arbeiderparti'],
  Enschede => ['Drienerlo'],
  Erzurum => ['Cedýt Ilica Sports'],
  Eskisehir => ['Anadolu', 'Eskisehir Adalar', 'Eskisehir Baðlar', 
    'Eskisehir Sports'],
  Essen => ['Essen 86'],
  Lodi => ['Fanfulla'],
  Firenze => ['Circolo del Bridge Firenze'],
  Fjends => ['Fjends BK'],
  Frankfurt => ['Frankfurter TBC'],
  Førde => ['Førde BK'],
  Garches => ['BC Garches'],
  Giza => ['El Rabwa Club', 'Rabwa Club'],
  Göteborg => ['BK Everfresh'],
  Groningen => ['BC de Zeerob'],
  Hamar => ['Hamar BK'],
  Hamburg => ['Hanseatic Hamburg BC'],
  Harstad => ['Harstad S&B'],
  Havirov => ['Dorost Havirov'],
  Hedmark => ['Østerdal'],
  Hyderabad => ['Deccan Club'],
  Isparta => ['Isparta Club'],
  Istanbul => ['Altinay SK', 'Atletik Basket', 'Bakýrköy Briç SK',
    'Besiktas', 'Camlica Sports', 'Fatih Karagumruk', 'Fenerbahce',
    'Galata', 'Galatasaray', 'Göktürk SK', 'Heybeliada SK', 'Hosgoru', 
    'Istanbul Sports', 'Karagümrük', 'Major Hosgoru', 'Majör Boğaziçi', 
    'Pamukspor', 'Vefa SK'],
  Izmir => ['Altay Genclik', 'Bornova BSK', 'Buca Sports',
    'Goztepe Hilal SK', 'Sirinyer Sports'],
  Jakarta => ['Jakarta BBG', 'Laksamana', 'Pelatnas',
    'Siwo Persatuan Wartawan Indonesia'],
  Kaohsiung => ['Kao Hsiung Club'],
  Karlsruhe => ['Karlsruher BSC', 'karlsruher'],
  Kolkata => ['Hindusthan Club', 'Lalit Mohanka'],
  Köln => ['Köln Lindenthal'],
  Krakow => ['Cracovia 1906'],
  'Kuala Lumpur' => ['Royal Selangor Club'],
  'La Spezia' => ['Spezia'],
  Lecco => ['Resegone LC'],
  Leverkusen => ['Nachteulen Leverkusen'],
  Lille => ['BC de Lille'],
  Lindesberg => ['Lindesbergs BS'],
  Linköping => ['Smedstadens BK'],
  Lisbon => ['Benfica', 'Núcleo De Bridge Do Círculo'],
  Lom => ['Øvre Ottadalen'],
  London => ['TGR'],
  Lüleburgaz => ['LÜKSAD'],
  Makassar => ['Makassar Utama'],
  Malatya => ['Malatya Yildiz Dogu', 'Malatyagücü'],
  Mannheim => ['Alert Mannheim', 'BC Universität Mannheim'],
  Mersin => ['Mersin Club'],
  Milan => ['BC Milano', 'Milan CPK Milanowek'],
  Minahasa => ['Gereja Masehi Injili di Minahasa'],
  'Mo i Rana' => ['Mo'],
  Moss => ['Moss BK'],
  Mragowo => ['Mragowia'],
  Mumbai => ['Matunga', 'Otters Club', 'The West End Mumbai', 
    'WCG Mumbai'],
  Nancy => ['Nancy Jarville BC'],
  Naples => ['Circolo Nautico Posillipo'],
  Norrorts => ['Norrorts Bridge'],
  Nürnberg => ['Nürnberg Museum'],
  Oltenita => ['Phoenix Oltenita'],
  Oslo => ['Hoppklubbene', 'OBK Kløverknekt', 'Solli', 'Top Bridge BC'],
  Örebro => ['Örebridgen'],
  Padang => ['Semen Padang'],
  Palermo => ['Circolo del Tennis Palermo'],
  Papua => ['Wampon Bodi Papua'],
  Parioli => ['Tennis Club Parioli'],
  Paris => ['Bridge Académie', 'Paris Sud'],
  Pescara => ['Pescara Bridge'],
  Plovdiv => ['Botev'],
  Porto => ['Dragao', 'Porto Club'],
  Poznan => ['RAL Poznan'],
  Prague => ['Acol Praha', 'Zmrzlina'],
  'Reggio Calabria' => ['Circolo del Bridge N. Ditto Reggio Calabria'],
  Rennes => ['BC Rennais'],
  Reykjavik => ['Vestri'],
  Rieneck => ['Kultcamp Rieneck'],
  Saarbrücken => ['BC Saarbrücken 1984'],
  Sakarya => ['Geyve Sports', 'Hendek Kazimiye'],
  Samsun => ['Amisos'], 
  Sarpsborg => ['Østfold og Follo'],
  'Schwäbisch Hall' => ['BC Schwäbisch Hall'],
  Shanghai => ['Qi Zhong Club', 'Qizhong'],
  Sharjah => ['Sharja Club'],
  Sivas => ['Sivasspor'],
  Ski => ['Ski BK'],
  Slagelse => ['BK 83 Slagelse'],
  Sofia => ['Bonsist'],
  Steinkjer => ['Nord Trøndelag'],
  Stockholm => ['Lavec', 'BK Lavec Smile'],
  Søborg => ['Blakset Klubberne'],
  Tekýrdag => ['Cerkezkoy Dinamik BSK', 'Kapakli Sýte', 'Tekirdað Club'],
  'Tel Aviv' => ['ASA University of Tel Aviv'],
  Tonya => ['Tonyaspor'],
  Torino => ['Torino Allegra'],
  Tours => ['Cercle Tourangeau'],
  Trondheim => ['Midt Trøndelag'],
  Umeå => ['BK Björken'],
  Uppsala => ['BK Fyris Skalman', 'Uppsalabridgen'],
  Utrecht => ['Bridgeclub Oog', 'NDC Den Hommel'],
  Van => ['Van Bric'],
  Västerås => ['ABB BK', 'Västeråsbridgen'],
  Vejle => ['Klør 10 Vejle'],
  Venice => ['Circolo del Bridge Venezia'],
  Vorden => ["'t Onstein"],
  Warsaw => ['Spojnia'],
  Wroclaw => ['Ruch AZS', 'Ruch SA'],
  Zagreb => ['Locomotiva'],
  Zürich => ['Zurich Enge'],
  Ålesund => ['Møre og Romsdal']
);


sub set_matrix
{
  my ($key) = @_;

  TeamBBO::set_matrix(\%COUNTRY_TO_REGION, 'TEAM_COUNTRY', 'TEAM_REGION');
  TeamBBO::set_matrix(\%COUNTRY_TO_CITY, 'TEAM_COUNTRY', 'TEAM_CITY');
  TeamBBO::set_matrix(\%CITY_TO_QUARTER, 'TEAM_CITY', 'TEAM_QUARTER');
}

1;

  'Site Sports',
  'Slem Bric SK',
  'SM BTC',
  'SPG Club',
  'St:Erik',
  'St:Erik Bahaj',
  'St:Erik Hella',
  'St:Erik Morot',
  'Studentenes',
  'UKS Olimpia',
  'Wan Jian Club',
  'Witte Huis',
  'Petroleum Mining Club',
  'Qingnian Qiche',
  'Quantum BC',
  'Rumah Sakit Umum Daerah',
  'Salmun BC',
  'Samadhan Academy',
  'San Sac',
  'Shemokh Club',
  'Shou Chuang',
  'Akceþme Spor',
  'Aklindo Musi 88',
  'Avalanche BC',
  'Balai Pelaksanaan Jalan Nasional',
  'BC Star',
  'Besli Major',
  'BK 1936',
  'BK Grand',
  'BK Lyx',
  'BK Nord',
  'Brans BS',
  'Bridge House',
  'Bridge Tunas Cahaya',
  'Centrum Kultury i Sportu',
  'CFT Bridge',
  'Colonial BC',
  'DBK Dalom',
  'El-Karma',
  'Fakultas Teknik Bridge Club',
  'Fire Club',
  'Gabrial UI',
  'Grant Thornton',
  'Greve Strand',
  'Herkules',
  'Hok Studiecentrum',
  'Jia Zhou Ai Qiao',
  'Jian Hua',
  'Jili Qiche',
  'Jin Fu',
  'Jin Hui',
  'Jin Mei',
  'Jing Fan',
  'JZD Liban',
  'Ke Bi Ya Club',
  'Kota Club',
  'Manna Bridge Club',
  'Mike Lawrence Club',
  'Modalfa',
  'NS-1',
  'Ocean BC',

  Acol 
  AGBC 
  Anadolu 
  Asenovec 
  Auguri 
  AVGP
  BTBK
  Gauteng
  Hercules 
  Jeofizik
  NBK
  Sakura 
