#!perl

use strict;
use warnings;
use v5.10;
use utf8;
use open ':std', ':encoding(UTF-8)';

package Swords::Competitive;

our @ISA = qw(Exporter);
our @EXPORT = qw(set_hashes);

my @MULTI_WORDS =
(
  'Balancing Double',
  'Balancing NT',
  'Competitive Double',
  'Fit Jump',
  'Flip Flop',
  'Game Try Double',
  'Good Bad NT',
  'Jump Shift',
  'Leaping Michaels',
  'Lightner Double',
  'Maximal Double',
  'Meckwell Against NT',
  'Michaels Cuebid',
  'Modified Hamilton',
  'Multi Landy',
  'Negative Double',
  'Negative Free Bid',
  'Penalty Double',
  'Pinpoint Astro',
  'Responsive Double',
  'Reverse Cappelletti',
  'Revised DONT',
  'Rosenkranz Double',
  'Sandwich NT',
  'SOS Redouble',
  'Sputnik Double',
  'Stolen Bid',
  'Strong Jump Shift',
  'Support Double',
  'System Off',
  'System On',
  'Takeout Double',
  'Unusual NT',
  'Unusual vs Unusual',
  'Weak Jump',
  'Weak Jump Shift',
  'Weak Jump Overcall',
  'Western Cuebid',
);

my %MULTI_TYPOS =
(
);

my @SINGLE_WORDS = qw(
  Brozel
  Cappelletti
  DONT
  Ghestem
  Landik
  Landy
  Lebensohl
  Michaels
  Rubensohl
  Wilkosz
  Woolsey
);

my %SINGLE_TYPOS =
(
  'Balancing Double' => [
    'balancingd',
    'balancingx',
    'balxs'],
  'Balancing NT' => [
    'ntbalancing'],
  Brozel => [
    'brosel',
    'brosell',
    'broz',
    'brozal',
    'broze',
    'brozek',
    'brozell',
    'brozelle',
    'brozer',
    'brozil',
    'brozl',
    'brozrel',
    'brozzel',
    'brozzl',
    'brozzle',
    'bruzell',
    'brz',
    'brze',
    'brzel',
    'brzi',
    'brzl'],
  Cappelletti => [
    'cap',
    'capal',
    'capalat',
    'capalati',
    'capalatti',
    'capalaty',
    'capalet',
    'capaleti',
    'capalett',
    'capalette',
    'capaletti',
    'capalettil',
    'capaletty',
    'capalety',
    'capali',
    'capaliti',
    'capalitte',
    'capalitti',
    'capalitty',
    'capality',
    'capalleti',
    'capallett',
    'capalletti',
    'capallety',
    'capalte',
    'capalti',
    'capaltti',
    'caparella',
    'caparetti',
    'capeiietti',
    'capel',
    'capela',
    'capelatti',
    'capele',
    'capeleletti',
    'capelepi',
    'capelet',
    'capeleti',
    'capeletit',
    'capelett',
    'capelette',
    'capeletti',
    'capelettie',
    'capeletty',
    'capelety',
    'capelier',
    'capeliti',
    'capelitti',
    'capelity',
    'capell',
    'capellati',
    'capelle',
    'capellelli',
    'capellet',
    'capelleti',
    'capellett',
    'capellette',
    'capelletti',
    'capellettil',
    'capelletty',
    'capellety',
    'capellieti',
    'capellite',
    'capelliti',
    'capellitti',
    'capellletti',
    'capelloto',
    'capellt',
    'capellti',
    'capellty',
    'capeloti',
    'capelt',
    'capelti',
    'capeltti',
    'capettilite',
    'capety',
    'caphlty',
    'capi',
    'capii',
    'capil',
    'capila',
    'capilati',
    'capilatti',
    'capileti',
    'capilett',
    'capiletta',
    'capilette',
    'capiletti',
    'capiletty',
    'capilety',
    'capilithi',
    'capiliti',
    'capilitti',
    'capility',
    'capill',
    'capillati',
    'capillatti',
    'capilleti',
    'capillette',
    'capilletti',
    'capillety',
    'capillit',
    'capilloti',
    'capiltetti',
    'capiltty',
    'capl',
    'caplet',
    'capleti',
    'capletti',
    'capletty',
    'capli',
    'caplieti',
    'caplity',
    'capll',
    'caplleti',
    'caplletti',
    'capllti',
    'caplltt',
    'caplt',
    'caplti',
    'capltt',
    'capltti',
    'caplty',
    'capole',
    'capolet',
    'capoleti',
    'capolett',
    'capoletti',
    'capolettist',
    'capolettit',
    'capoletty',
    'capollet',
    'capolleti',
    'capolletti',
    'capollrtti',
    'capollt',
    'capolotti',
    'capolotty',
    'caponetti',
    'caporaletti',
    'capp',
    'cappa',
    'cappailette',
    'cappal',
    'cappaleetti',
    'cappalet',
    'cappaleti',
    'cappalett',
    'cappaletti',
    'cappaletty',
    'cappalety',
    'cappalitti',
    'cappality',
    'cappall',
    'cappalle',
    'cappalleti',
    'cappalletti',
    'cappalliti',
    'cappaltti',
    'cappe',
    'cappeeti',
    'cappeiieti',
    'cappel',
    'cappelati',
    'cappelatti',
    'cappelet',
    'cappelete',
    'cappeleti',
    'cappelett',
    'cappelette',
    'cappeletti',
    'cappeletty',
    'cappelety',
    'cappelietti',
    'cappelite',
    'cappeliti',
    'cappelitte',
    'cappelitti',
    'cappelity',
    'cappell',
    'cappellati',
    'cappellatti',
    'cappelle',
    'cappeller',
    'cappelleri',
    'cappellet',
    'cappellete',
    'cappelleti',
    'cappelletilav',
    'cappellett',
    'cappellette',
    'cappellettii',
    'cappellettis',
    'cappelletty',
    'cappellety',
    'cappelli',
    'cappellini',
    'cappelliti',
    'cappellitie',
    'cappellitti',
    'cappelltti',
    'cappelrti',
    'cappelt',
    'cappelti',
    'cappeltti',
    'cappelty',
    'capperletti',
    'cappetti',
    'cappettti',
    'cappi',
    'cappil',
    'cappilati',
    'cappilatti',
    'cappilaty',
    'cappilet',
    'cappileti',
    'cappilett',
    'cappilette',
    'cappiletti',
    'cappiletty',
    'cappilety',
    'cappiliti',
    'cappilitti',
    'cappility',
    'cappillati',
    'cappille',
    'cappilleti',
    'cappilletti',
    'cappilletty',
    'cappilti',
    'cappl',
    'cappleti',
    'cappletti',
    'capplety',
    'cappli',
    'capplit',
    'cappliti',
    'capplitti',
    'cappll',
    'capplletti',
    'cappllt',
    'capplt',
    'capplti',
    'cappltt',
    'cappltti',
    'capplty',
    'cappo',
    'cappolatti',
    'cappolet',
    'cappoletti',
    'cappolettti',
    'cappolety',
    'cappolletti',
    'cappp',
    'capppeletti',
    'capprlrtti',
    'capps',
    'cappt',
    'cappti',
    'capul',
    'capulatti',
    'capulet',
    'capuleti',
    'capuletti',
    'capuletty'],
  DONT => [
    'dontnt',
    'donts',
    'dontt',
    'dontv',
    'dontvs'],
  Ghestem => [
    'geshtem',
    'gest',
    'gestam',
    'gestehm',
    'gestem',
    'gesten',
    'gestend',
    'gesth',
    'gestham',
    'gestheim',
    'gesthem',
    'gheestem',
    'gheistem',
    'ghenstem',
    'ghes',
    'ghesdem',
    'ghesht',
    'gheshtum',
    'ghest',
    'ghestam',
    'ghestan',
    'gheste',
    'ghesteem',
    'ghesteim',
    'ghestem',
    'ghestemm',
    'ghesten',
    'ghesth',
    'ghesthem',
    'ghestim',
    'ghestm',
    'ghestom',
    'gheston',
    'ghestum',
    'ghstem',
    'ghsthem',
    'ghstm',
    'ghtem',
    'gshm',
    'gsthm',
    'gstm'],
  'Competitive Double' => [
    'compx'],
  'Fit Jump' => [
    'fitjump',
    'fitjumps'],
  'Flip Flop' => [
    'flipflop'],
  'Game Try Double' => [
    'gametrydoubles'],
  'Good Bad NT' => [
    'goodbad',
    'goodbadnt',
    'ntgoodbad'],
  'Jump Shift' => [
    'jumpshift',
    'jumpshifts'],
  Landik => [
    'landick'],
  Landy => [
    'landi',
    'landyy',
    'lnd',
    'lndi',
    'lndy'],
  'Leaping Michaels' => [
    'leapingmichaels',
    'leapm',
    'leapmik',
    'lpgmicls'],
  Lebensohl => [
    'leb',
    'lebanhsol',
    'lebanshol',
    'lebansohl',
    'lebansol',
    'lebanthal',
    'lebb',
    'lebben',
    'lebbensohl',
    'lebe',
    'lebebs',
    'lebebshol',
    'lebebsohl',
    'lebeensol',
    'lebehn',
    'lebehnsohl',
    'lebehnsol',
    'lebehnson',
    'lebehsohl',
    'lebehsol',
    'lebel',
    'lebelhson',
    'lebelshol',
    'lebelshon',
    'lebelsoh',
    'lebelsohl',
    'lebelsohn',
    'lebelsol',
    'lebelson',
    'leben',
    'lebenbesohl',
    'lebenbsohl',
    'lebenbsol',
    'lebenchl',
    'lebenchol',
    'lebenh',
    'lebenhl',
    'lebenhol',
    'lebenhsohl',
    'lebenhsol',
    'lebenl',
    'lebenol',
    'lebenoshl',
    'lebenosohl',
    'lebens',
    'lebensahl',
    'lebensal',
    'lebenschi',
    'lebenschol',
    'lebenscholl',
    'lebensh',
    'lebenshall',
    'lebenshl',
    'lebensho',
    'lebenshoal',
    'lebenshol',
    'lebenshola',
    'lebenshold',
    'lebenshole',
    'lebensholh',
    'lebensholl',
    'lebenshon',
    'lebenshool',
    'lebensl',
    'lebenslohl',
    'lebensn',
    'lebensnol',
    'lebenso',
    'lebensobl',
    'lebensod',
    'lebensoh',
    'lebensohi',
    'lebensohjl',
    'lebensohla',
    'lebensohle',
    'lebensohlem',
    'lebensohln',
    'lebensohls',
    'lebensohn',
    'lebensol',
    'lebensola',
    'lebensolblw',
    'lebensold',
    'lebensolh',
    'lebensoll',
    'lebensolll',
    'lebenson',
    'lebensonhl',
    'lebensonn',
    'lebensool',
    'lebensoul',
    'lebenssohl',
    'lebensthol',
    'lebenthal',
    'lebenthol',
    'lebenxhol',
    'lebenz',
    'lebenzohl',
    'lebenzol',
    'lebesh',
    'lebeshl',
    'lebeshol',
    'lebesohl',
    'lebesohle',
    'lebesol',
    'lebesoll',
    'lebh',
    'lebhansol',
    'lebhecholl',
    'lebhen',
    'lebhens',
    'lebhenshol',
    'lebhensohl',
    'lebhensol',
    'lebhl',
    'lebhnsl',
    'lebhs',
    'lebhsl',
    'lebinshol',
    'lebinsohl',
    'lebinsol',
    'lebl',
    'lebn',
    'lebnesol',
    'lebns',
    'lebnsh',
    'lebnshl',
    'lebnshll',
    'lebnshol',
    'lebnsl',
    'lebnsohl',
    'lebnsol',
    'lebnsoll',
    'lebnzl',
    'lebolshol',
    'lebonchl',
    'lebonsal',
    'lebonsh',
    'lebonshol',
    'lebonso',
    'lebonsoh',
    'lebonsohl',
    'lebonsol',
    'lebonson',
    'lebs',
    'lebsh',
    'lebshl',
    'lebshll',
    'lebshol',
    'lebsholl',
    'lebsl',
    'lebsohl',
    'lebsol',
    'lebsolh',
    'lebson',
    'lebsonsol',
    'lebsor'],
  'Lightner Double' => [
    'lighx'],
  'Maximal Double' => [
    'maximalx',
    'maxmlx',
    'maxx'],
  'Meckwell Against NT' => [
    'meckwell'],
  Michaels => [
    'mchls',
    'mechels',
    'mhcels',
    'mhcls',
    'miachels',
    'mic',
    'micaels',
    'micahels',
    'micals',
    'micchaels',
    'miccue',
    'mich',
    'michacls',
    'michaeals',
    'michaeels',
    'michaeis',
    'michaeks',
    'michael',
    'michaeles',
    'michaells',
    'michaels',
    'michal',
    'michales',
    'michals',
    'michc',
    'miche',
    'michea',
    'micheaels',
    'micheal',
    'micheales',
    'michealis',
    'micheals',
    'michedals',
    'micheles',
    'michellls',
    'michells',
    'michels',
    'michles',
    'michls',
    'michs',
    'mick',
    'mickp',
    'mickael',
    'mickaels',
    'mickeals',
    'mickels',
    'mickls',
    'micks',
    'micls',
    'micprec',
    'mics',
    'miichaels',
    'mikecue',
    'mikels',
    'mikles',
    'mikls',
    'mkls'],
  'Michaels Cuebid' => [
    'cbmich',
    'cbmichaelsa',
    'mchaelq',
    'mchcb',
    'mchcue',
    'mchlqbid',
    'mchq',
    'mckcb',
    'mcueb',
    'mcuebid',
    'miccb',
    'miccubib',
    'miccubid',
    'miccue',
    'michaelcb',
    'michaelcueb',
    'michaelcuebidprecise',
    'michaelqbid',
    'michaelsc',
    'michaelscb',
    'michaelscue',
    'michaelsq',
    'michaelsque',
    'michaelsquebid',
    'michcb',
    'michcu',
    'michcue',
    'michcuebd',
    'michcuebid',
    'michealcqbid',
    'michealqbid',
    'micheleb',
    'michkqubit',
    'michlscue',
    'michpré',
    'michq',
    'michqbid',
    'michscb',
    'michsuperprec',
    'mickaelcubid',
    'mickaelscb',
    'mickcb',
    'micknp',
    'mickpré',
    'mickpréc',
    'mickprec',
    'mickq',
    'mickqbid',
    'micq',
    'micqbid',
    'micqp',
    'mikcb',
    'mikanp',
    'mikecbids',
    'mikeq',
    'mikpréc',
    'miq',
    'mkcuebid',
    'mprécisé'],
  'Modified Hamilton' => [
    'modham'],
  'Multi Landy' => [
    'mulandy',
    'multiandy',
    'multil',
    'multilady',
    'multilan',
    'multiland',
    'multilandi',
    'multilandy',
    'multildy',
    'multilendi',
    'multilendy',
    'multilndy',
    'multirandy',
    'multla',
    'multlan',
    'multland',
    'multlandi',
    'multlandy',
    'multyl',
    'multylan',
    'multyland',
    'multylandy',
    'multylen',
    'multylendy'],
  'Negative Double' => [
    'negatdbl',
    'negatiefx',
    'negatifdbl',
    'negatifx',
    'negatinex',
    'negativdoub',
    'negativex',
    'negativexx',
    'negativkontra',
    'negativkontras',
    'negativx',
    'negatix',
    'negatvedbl',
    'negatvedoubles',
    'negatvex',
    'negdabl',
    'negdb',
    'negdbi',
    'negdbl',
    'negdble',
    'negdbles',
    'negdbleup',
    'negdbls',
    'negdbt',
    'negdl',
    'negdlb',
    'negdlbs',
    'negdob',
    'negdobl',
    'negdoub',
    'negdouble',
    'negdoubles',
    'negatived',
    'negativedb',
    'negativedbl',
    'negetivedbl',
    'neggdbl',
    'negsx',
    'negtivedbl',
    'negtx',
    'negx',
    'negxs',
    'negxx',
    'negxxs',
    'negxxx',
    'negatived',
    'negativedb',
    'negativedbl',
    'negatvx',
    'negatx',
    'negax',
    'ngc',
    'ngd',
    'ngdb',
    'ngdbl',
    'ngdl',
    'ngdobl',
    'ngfdbl',
    'ngtdbl',
    'ngtfdbl',
    'ngtifdb',
    'ngtvdbl',
    'ngtvdblt',
    'ngtwx',
    'ngtx',
    'ngx'],
  'Negative Free Bid' => [
    'negativefreebids',
    'negfb',
    'negfreebid',
    'negfreebids'],
  'Penalty Double' => [
    'penaltyx'],
  'Pinpoint Astro' => [
    'pinpointastro'],
  'Responsive Double' => [
    'respdb',
    'respdbl',
    'responsivex',
    'respronf',
    'respx',
    'respx\'s',
    'resx'],
  'Reverse Cappelletti' => [
    'modcapp',
    'revcapp'],
  'Revised DONT' => [
    'revdont'],
  'Rosenkranz Double' => [
    'rosenkrantzx',
    'rozenkranzx',
    'rozex',
    'rozx'],
  Rubensohl => [
    'ruben',
    'rubenxfer'],
  'Sandwich NT' => [
    'sandn',
    'sandnt',
    'sandwichnt',
    'sandwnt',
    'sdwhnt',
    'sndnt',
    'sndwchnt',
    'sndwcht',
    'sndwhnt',
    'sndwnt'],
  'SOS Redouble' => [
    'sosxx'],
  'Sputnik Double' => [
    'controsputnik',
    'sputnikx',
    'sputnix',
    'spux'],
  'Stolen Bid' => [
    'stlnbd',
    'stlnbid',
    'stlnbidx',
    'stobid',
    'stolbidx',
    'stolenb',
    'stolenbid',
    'stolenbids',
    'stolenbidx',
    'stolenstep',
    'stolenx',
    'stolnx',
    'xonstlnbids'],
  'Strong Jump Shift' => [
    'strgjs',
    'strjs',
    'strongjs',
    'strjumpshift'],
  'Support Double' => [
    'spptx',
    'spprtx',
    'sppx',
    'sptx',
    'supd',
    'supdb',
    'supdbl',
    'supdbls',
    'supdbs',
    'supdl',
    'supdoub',
    'supdoubbel',
    'supdub',
    'suportdb',
    'suportdbl',
    'suportx',
    'suportxx',
    'suposedb',
    'suppd',
    'suppdbl',
    'suppdble',
    'suppdbls',
    'suppdouble',
    'suppdrd',
    'suppertx',
    'supportd',
    'supportdbl',
    'supportdob',
    'supportdouble',
    'supportdoubles',
    'supportx',
    'supportxandxx',
    'supportxx',
    'supprtx',
    'suppsx',
    'supptkontra',
    'suppttx',
    'supptx',
    'supptxx',
    'suppx',
    'suppxrx',
    'suppxs',
    'suppxx',
    'suppxxx',
    'suprtdbl',
    'suprtx',
    'suprx',
    'suprxxx',
    'suptdbl',
    'suptdou',
    'suptx',
    'supx',
    'supxandxx',
    'supxs',
    'supxx',
    'supxxx',
    'supporx'],
  'System Off' => [
    'sysoff'],
  'System On' => [
    'syson',
    'syston',
    'systson'],
  'Takeout Double' => [
    'infdbl',
    'infox',
    'takeoudbl',
    'takeoutdb',
    'takeoutdoubles',
    'takeoutx',
    'takeoutxx'],
  'Unusual NT' => [
    'ntmiinors',
    'ntu',
    'ntun',
    'ntunus',
    'unconvnt',
    'unn',
    'unnt',
    'unont',
    'unsa',
    'unslnt',
    'unsnt',
    'unsualnt',
    'unsunt',
    'unsusalnt',
    'unualnt',
    'unujnt',
    'unujualnt',
    'unujusalnt',
    'ununt',
    'unusalnt',
    'unusaulnt',
    'unuslnt',
    'unusn',
    'unusnt',
    'unusual',
    'unusualn',
    'unusualnotrump',
    'unusualnt',
    'unusualntovercall',
    'unusualsa',
    'unusulnt',
    'unusunt',
    'unvun',
    'usnusnt',
    'usualnt',
    'usunt',
    'uunt',
    'uusnt'],
  'Unusual vs Unusual' => [
    'unvsun',
    'uvsu'],
  'Weak Jump' => [
    'saltideb',
    'weakj',
    'weakjump',
    'weakjumps',
    'wkjincomp',
    'wkjump',
    'wkjumps',
    'wjumps'],
  'Weak Jump Overcall' => [
    'weakjo',
    'weakjumpo',
    'weakjumpovercall',
    'weakjumpovercl',
    'wjo',
    'wjoc',
    'wkjo'],
  'Weak Jump Shift' => [
    'weakjs',
    'weakjshift',
    'weakjshiftsalways',
    'weakjumpshift',
    'wjsalways',
    'wjsm',
    'wkjmpsft',
    'wkjmpsh',
    'wkjmpshft',
    'wkjmpshift',
    'wkjs',
    'wkjshift',
    'wkjumpsh',
    'wkjumpshift',
    'wkjumpshif'],
  'Western Cuebid' => [
    'westcue',
    'westerncue',
    'westernq',
    'westerq',
    'westq',
    'weternq',
    'wqb',
    'wstnq',
    'wstq',
    'wstrnqbids'],
  Woolsey => [
    'wlsy'],
);


sub set_hashes
{
  my ($method, $key) = @_;

  $method->(\@MULTI_WORDS, \%MULTI_TYPOS,
    \@SINGLE_WORDS, \%SINGLE_TYPOS, $key);
}

1;
