#!perl

use strict;
use warnings;
use v5.10;
use utf8;
use open ':std', ':encoding(UTF-8)';

package Swords::Constructive;

our @ISA = qw(Exporter);
our @EXPORT = qw(set_hashes);

my @MULTI_WORDS =
(
  '2D Waiting',
  'Checkback Stayman',
  'Control Bid',
  'Forcing NT',
  'Inverted Minors',
  'Kokish Game Try',
  'Limit Raise',
  'New Minor Forcing',
  'Jacoby 2NT',
  'Jacoby Transfers',
  'Reverse Drury',
  'Slow Arrival',
  'Serious 3NT',
  'South African Texas',
  'Super Accepts',
  'Texas Transfers',
  'Trial Bid',
  'Wolff Signoff',
  'XY NT',
  'XYZ NT',
);

my %MULTI_TYPOS =
(
);

my @SINGLE_WORDS = qw(
  Baron
  Crodo
  Drury
  Flannery
  Gerber
  Minisplinter
  Namyats
  Ogust
  Puppet
  Roudinesco
  Smolen
  Splinter
  Stenberg
  Walsh
);

my %SINGLE_TYPOS =
(
  '2D Waiting' => [
    'waitpreferans',
    'waitaork'],
  'Checkback Stayman' => [
    'chbckst',
    'chbst',
    'chkbkst',
    'chkbackstymn',
    'chkbaksa',
    'chkbstaym',
    'chkbs',
    'checkbackst',
    'checkbackstay',
    'checkbackstayman'],
  Crodo => [
    'cro',
    'crod',
    'crodo'],
  Drury => [
    'drru',
    'drrury',
    'drruy',
    'drry',
    'drrys',
    'drryy',
    'dru',
    'druary',
    'drudry',
    'drudy',
    'druery',
    'druey',
    'druhry',
    'druly',
    'drur',
    'drurel',
    'drurey',
    'drureyfittey',
    'druri',
    'drurie',
    'druriy',
    'drurry',
    'drurty',
    'druru',
    'drurury',
    'druruy',
    'druryfit',
    'druryfitte',
    'druryfitté',
    'druryi',
    'druryr',
    'drurys',
    'druryy',
    'druty',
    'druury',
    'druuy',
    'druwry',
    'druy',
    'druyru',
    'druyy',
    'dryr',
    'dryry'],
  Flannery => [
    'flan',
    'flanarry',
    'flanary',
    'flanely',
    'flaner',
    'flaneri',
    'flanerry',
    'flanery',
    'flann',
    'flannary',
    'flanne',
    'flanner',
    'flannert',
    'flanneryr',
    'flanneryy',
    'flanney',
    'flannnery',
    'flannnnery',
    'flannry',
    'flanr',
    'flanry',
    'flany',
    'flrannery',
    'flry'],
  'Control Bid' => [
    'ctrlbids'],
  'Forcing NT' => [
    'font',
    'forcent',
    'forcgnt',
    'forcingnt',
    'forcinnt',
    'forcnt',
    'fornt',
    'forsingnt',
    'forsnt',
    'frcgnt',
    'frcnt',
    'frnt',
    'frsnt',
    'ntf',
    'ntfc',
    'ntforc',
    'ntforce',
    'ntforcing' ],
  Gerber => [
    'garbar',
    'garber',
    'gbr',
    'gerb',
    'gerba',
    'gerbar',
    'gerbe',
    'gerbeer',
    'gerber',
    'gerberafternt',
    'gerberaftnt',
    'gerbere',
    'gerberg',
    'gerberh',
    'gerberl',
    'gerberm',
    'gerbern',
    'gerbernt',
    'gerberovernt',
    'gerberr',
    'gerbers',
    'gerbor',
    'gerbr',
    'gerbre',
    'gerbrkc',
    'gervber',
    'gerver',
    'grb',
    'grbe',
    'grber',
    'grbr'],
  'Inverted Minors' => [
    'inm',
    'inverm',
    'invertdm',
    'invertedm',
    'invertedmin',
    'invertedminors',
    'invertem',
    'invertm',
    'invertminor',
    'invertminör',
    'invertmýn',
    'invitmin',
    'invm',
    'invmi',
    'invmimor',
    'invmin',
    'invmino',
    'invminor',
    'invminorraises',
    'invminors',
    'invminr',
    'invminrs',
    'invmins',
    'invmn',
    'invmnr',
    'invmnrs',
    'invmns',
    'invmr',
    'invmrs',
    'invmýn',
    'invörtm',
    'invrm',
    'invrtdm',
    'invrtdminrs',
    'invrtdmnrs',
    'invrtm',
    'invtdminor',
    'invtdminors',
    'invtdmnr',
    'invtminor',
    'meninv',
    'minvmin',
    'ninvmin',
    'ynvmi'],
  'Jacoby 2NT' => [
    'jabnt',
    'jacbyn',
    'jacnt',
    'jacobyn',
    'jacobynt',
    'jacont',
    'jakobynt',
    'jakont',
    'jbynt',
    'jcbnt',
    'jcbtr',
    'ntja',
    'ntjac',
    'ntjacob',
    'ntjacoby'],
  'Jacoby Transfers' => [
    'jacbtnsf',
    'jacbtr',
    'jacbytf',
    'jacbytr',
    'jacbytrns',
    'jacobit',
    'jacbt',
    'jacobitransfer',
    'jacobitransferbid',
    'jacobjt',
    'jacobstr',
    'jacobstransfer',
    'jacobt',
    'jacobtr',
    'jacobtransf',
    'jacobtx',
    'jacobyransfers',
    'jacobyt',
    'jacobytfers',
    'jacobytr',
    'jacobytran',
    'jacobytrans',
    'jacobytransf',
    'jacobytransfer',
    'jacobytransfers',
    'jacobytrf',
    'jacobytrns',
    'jacobytrnsfrs',
    'jacobytrs',
    'jacobytrsf',
    'jacobytrsfr',
    'jacobyttransfer',
    'jacobyxfer',
    'jacobyxfr',
    'jacombytrasfer',
    'jacotr',
    'jact',
    'jacta',
    'jactfr',
    'jactr',
    'jactran',
    'jactrans',
    'jactransf',
    'jactransfer',
    'jactransfers',
    'jactransfrs',
    'jactrf',
    'jactrfs',
    'jactrnnt',
    'jactrns',
    'jactrs',
    'jactrsf',
    'jactrsfer',
    'jactrsfr',
    'jactsfr',
    'jactxr',
    'jacxfer',
    'jacxfers',
    'jacxfx',
    'jcbtrans',
    'jcbytr',
    'jcbytrf',
    'jcbytrnsf'],
  Minisplinter => [
    'minispl'],
  Ogust => [
    'ogu',
    'ogus',
    'ogusr',
    'ogust',
    'ogut',
    'ougst',
    'ougu',
    'ougust',
    'ougyst',
    'ugust'],
  Puppet => [
    'ppt',
    'pup',
    'pupat',
    'pupe',
    'puped',
    'pupeet',
    'pupet',
    'pupets',
    'pupett',
    'pupette',
    'puphit',
    'pupi',
    'pupici',
    'pupit',
    'pupp',
    'puppat',
    'puppe',
    'pupped',
    'puppent',
    'pupper',
    'puppert',
    'puppetbid',
    'puppete',
    'puppeth',
    'puppetl',
    'puppeto',
    'puppeton',
    'puppets',
    'puppett',
    'puppetto',
    'puppis',
    'puppit',
    'puppnt',
    'pupppet',
    'pupprt',
    'puppst',
    'puppt',
    'pupput',
    'pupt',
    'puput'],
  Roudinesco => [
    'roud',
    'rouddi',
    'roudi',
    'roudii',
    'roudinescu',
    'roudj',
    'roudy'],
  Smolen => [
    'sml',
    'smlen',
    'smll',
    'smlln',
    'smln',
    'smloen',
    'smlolen',
    'smlon',
    'smn',
    'smo',
    'smoelen',
    'smol',
    'smolan',
    'smole',
    'smoleen',
    'smolem',
    'smolen',
    'smolene',
    'smolenl',
    'smolenm',
    'smoleno',
    'smolens',
    'smoleon',
    'smolian',
    'smolien',
    'smolin',
    'smoll',
    'smolle',
    'smollen',
    'smoln',
    'smoloen',
    'smolon',
    'smolun',
    'smomlen',
    'smon',
    'smonel'],
  Splinter => [
    'spl',
    'spleeder',
    'spleinters',
    'splent',
    'splenter',
    'spli',
    'splid',
    'splider',
    'splihter',
    'spliinter',
    'splimter',
    'splimters',
    'splin',
    'splinder',
    'splinders',
    'spliner',
    'spliners',
    'splinfer',
    'splingt',
    'splinnter',
    'splinpter',
    'splinr',
    'splinrt',
    'splinrts',
    'splint',
    'splintaire',
    'splinte',
    'splinter',
    'splintera',
    'splinterbid',
    'splinterbids',
    'splinterl',
    'splinters',
    'splintersers',
    'splintery',
    'splintes',
    'splinthe',
    'splintir',
    'splintle',
    'splintner',
    'splintor',
    'splintors',
    'splintr',
    'splintrs',
    'splints',
    'splintt',
    'splintter',
    'splintters',
    'splionters',
    'splir',
    'split',
    'spliter',
    'spliters',
    'splitnter',
    'splitr',
    'spllinter',
    'spllnt',
    'spllnter',
    'spllnters',
    'spln',
    'splniter',
    'splnr',
    'splnt',
    'splnter',
    'splnters',
    'splntr',
    'splntrs',
    'splntrt',
    'splnts',
    'splointer',
    'splr',
    'spls',
    'splt',
    'splter',
    'splters',
    'spltnr',
    'spltr',
    'spltrbid',
    'spltrs',
    'splts',
    'splynter',
    'spnter',
    'spntr'],
  'Kokish Game Try' => [
    'kokishgt'],
  'Limit Raise' => [
    'limitraise',
    'limraise',
    'limraises',
    'limrs',
    'limrse',
    'limtrase',
    'lmtr',
    'lmtras'],
  'New Minor Forcing' => [
    'newm',
    'newmf',
    'newmi',
    'newmin',
    'newminf',
    'newminforc',
    'newminfrc',
    'newminoor',
    'newminor',
    'newminorf',
    'newminorfor',
    'newminorforcing',
    'newminr',
    'newmnfor',
    'newmnr',
    'nm',
    'nmf',
    'nmfc',
    'nmfg',
    'nmfo',
    'nmforc',
    'nmforce',
    'nmforcing',
    'nmforsing',
    'nmfr',
    'nmgf',
    'nmi',
    'nmin',
    'nminor',
    'nmo',
    'nmr',
    'nmrf',
    'nmsf'],
  'Reverse Drury' => [
    'rdru',
    'rdrury',
    'rdruy',
    'rdry',
    'rvdr',
    'rvdru',
    'revd',
    'revdr',
    'revdrry',
    'revdru',
    'revdrur',
    'revdrury',
    'revdruy',
    'revdry',
    'revdury',
    'reverdrury',
    'reversedrury',
    'rewdrury',
    'rvd',
    'rvdrury',
    'rvrsdrury',
    'rvsdrury'],
  'Serious 3NT' => [
    'serious3nt'],
  'South African Texas' => [
    'africantexas'],
  'Texas Transfers' => [
    'teaxas',
    'teaxs',
    'tex',
    'texa',
    'texac',
    'texas',
    'texascfx',
    'texases',
    'texaskonvention',
    'texass',
    'texastr',
    'texastrans',
    'texastransf',
    'texastransfer',
    'texastransfers',
    'texastransfert',
    'texastrf',
    'texastrfs',
    'texastrns',
    'texasx',
    'texasxfer',
    'texasxfers',
    'texasy',
    'texax',
    'texay',
    'texes',
    'texs',
    'texsa',
    'texsaa',
    'texsas',
    'texsastr',
    'texsax',
    'texss',
    'textas',
    'textor',
    'textr',
    'textrans',
    'textrf',
    'textrs',
    'texttrf',
    'texx',
    'texxas',
    'texxfer',
    'texxfers',
    'texy',
    'txas',
    'txastran',
    'txrs',
    'txs',
    'txsas',
    'txstrsf',
    'txt',
    'txtf',
    'txtfr',
    'txtr',
    'txtran',
    'txtrans',
    'txtransf',
    'txtrf',
    'txtrfr',
    'txtrfrs',
    'txtrfs',
    'txtrns',
    'txtrs',
    'txtrsf',
    'txtrx',
    'txtsf',
    'txtsfr',
    'txtx',
    'txxfer',
    'txxfrs'],
  'Trial Bid' => [
    'trialbid'],
  'Wolff Signoff' => [
    'wolfsig'],
  'XY NT' => [
    'xynt'],
  'XYZ NT' => [
    'xyznt'],
);


sub set_hashes
{
  my ($method, $key) = @_;

  $method->(\@MULTI_WORDS, \%MULTI_TYPOS,
    \@SINGLE_WORDS, \%SINGLE_TYPOS, $key);
}

1;
