#!perl

use strict;
use warnings;
use v5.10;
use utf8;
use open ':std', ':encoding(UTF-8)';

package Swords::Stayman;

our @ISA = qw(Exporter);
our @EXPORT = qw(set_hashes);

my @MULTI_WORDS =
(
  'Minor Suit Stayman',
  'Nonforcing Stayman',
  'Puppet Stayman',
);

my %MULTI_TYPOS =
(
);

my @SINGLE_WORDS = qw(
  Stayman
);

my %SINGLE_TYPOS =
(
  'Minor Suit Stayman' => [
    'minorstayman',
    'mss'],
  'Nonforcing Stayman' => [
    'garbst',
    'garbstayman',
    'grbgstym',
    'nfstay',
    'nonfsty',
    'weakstay'],
  'Puppet Stayman' => [
    'puppetst',
    'puppetstay',
    'puppetstayman',
    'puppetstyman',
    'puppstay',
    'puppstaym',
    'puppstayman',
    'puppstym',
    'puppstymn',
    'pups',
    'pupst',
    'pupsta',
    'pupstay',
    'pupstaym',
    'pupstm',
    'pupsty',
    'pupstym'],
  Stayman => [
    'básicstayman',
    'sayman',
    'sman',
    'staaman',
    'staeman',
    'staemen',
    'staeyman',
    'staim',
    'staimain',
    'staimam',
    'staimamn',
    'staiman',
    'staimann',
    'staimant',
    'staimar',
    'staimen',
    'staiment',
    'staimman',
    'staimon',
    'staimsn',
    'stainman',
    'stajman',
    'stajmann',
    'stam',
    'stama',
    'staman',
    'stamann',
    'stamen',
    'stament',
    'stamin',
    'stamn',
    'stamon',
    'stamyen',
    'stamyman',
    'stanman',
    'stanmen',
    'stanyman',
    'statman',
    'statmen',
    'statmn',
    'stay',
    'stayam',
    'stayaman',
    'stayan',
    'stayeman',
    'stayen',
    'stayerman',
    'stayhman',
    'stayiman',
    'staylan',
    'staym',
    'stayma',
    'staymaan',
    'staymab',
    'staymae',
    'staymaen',
    'staymah',
    'staymain',
    'staymam',
    'staymanc',
    'staymand',
    'staymani',
    'staymanic',
    'staymanm',
    'staymann',
    'staymannn',
    'staymanon',
    'staymanor',
    'staymanr',
    'staymans',
    'staymant',
    'staymar',
    'staymasn',
    'staymat',
    'staymay',
    'staymayn',
    'stayme',
    'staymed',
    'staymem',
    'staymen',
    'staymend',
    'staymens',
    'stayment',
    'staymin',
    'staymman',
    'staymn',
    'staymna',
    'staymon',
    'staymond',
    'staymrn',
    'staymsn',
    'staymt',
    'staymwns',
    'staymzan',
    'staymzn',
    'stayn',
    'staynabm',
    'staynam',
    'staynan',
    'staynm',
    'staynman',
    'staynmann',
    'staynmar',
    'staynmen',
    'stayuman',
    'steaman',
    'stehman',
    'steim',
    'steima',
    'steiman',
    'steimann',
    'steimany',
    'steimen',
    'steimn',
    'steinm',
    'steinman',
    'stemain',
    'steman',
    'stemann',
    'stemen',
    'stemn',
    'steym',
    'steyma',
    'steymain',
    'steymam',
    'steyman',
    'steymann',
    'steymans',
    'steymem',
    'steymen',
    'steyment',
    'steymin',
    'steymman',
    'steymn',
    'steymnt',
    'steynman',
    'stf',
    'stm',
    'stma',
    'stman',
    'stmann',
    'stmans',
    'stmen',
    'stmm',
    'stmn',
    'stmyn',
    'strayman',
    'straymann',
    'sty',
    'styam',
    'styaman',
    'styamn',
    'styayman',
    'styeiman',
    'styeman',
    'styhmn',
    'styim',
    'styjm',
    'stym',
    'styma',
    'stymam',
    'styman',
    'stymani',
    'stymanl',
    'stymanmod',
    'stymann',
    'stymas',
    'stymen',
    'stymenn',
    'styment',
    'stymin',
    'stymm',
    'stymmn',
    'stymn',
    'stymnj',
    'stymns',
    'stymnt',
    'stymnx',
    'stymt',
    'styn',
    'stynan',
    'stynm',
    'stytman',
    'syman'],
);


sub set_hashes
{
  my ($method, $key) = @_;

  $method->(\@MULTI_WORDS, \%MULTI_TYPOS,
    \@SINGLE_WORDS, \%SINGLE_TYPOS, $key);
}

1;
