#!perl

package Caps::Fragments;

use v5.10;
use strict;
use warnings;
use utf8;
use open ':std', ':encoding(UTF-8)';

use Exporter;

our @ISA = qw(Exporter);
our @EXPORT = qw(match);

my %FRAGMENTS =
(
  andTex => [ CATEGORY => 'MISC', VALUE => 'Texas'],
  cardSang => [ CATEGORY => 'LENGTHS', VALUE => 'cards',
    CATEGORY => 'DENOMINATIONS', VALUE => 'notrump'],
  cayC => [ CATEGORY => 'BASES', VALUE => 'SAYC'],
  clFm => [ CATEGORY => 'DENOMINATIONS', VALUE => 'clubs',
    CATEGORY => 'MISC', VALUE => 'Game Forcing'],
  clFG => [ CATEGORY => 'DENOMINATIONS', VALUE => 'clubs',
    CATEGORY => 'MISC', VALUE => 'Game Forcing'],
  cmNt => [ CATEGORY => 'RANKS', VALUE => 'Card Major',
    CATEGORY => 'DENOMINATIONS', VALUE => 'notrump'],
  convantionsRKCB => [ CATEGORY => 'KEYCARD', VALUE => 'RKCB'],
  gameF => [ CATEGORY => 'MISC', VALUE => 'Game Forcing'],
  gameFS => [ CATEGORY => 'MISC', VALUE => 'Game Forcing'],
  maintenantTOULOUSE => [ CATEGORY => 'CITY', VALUE => 'Toulouse'],
  indyTexas => [ CATEGORY => 'MISC', VALUE => 'Texas'],
  mancH => [ CATEGORY => 'MISC', VALUE => 'Game Forcing'],
  mockingbirdStavanger => [ CATEGORY => 'CITY', VALUE => 'Stavanger'],
  newZealand => [ CATEGORY => 'COUNTRY', VALUE => 'New Zealand'],
  ntBlackwood => [ CATEGORY => 'DENOMINATIONS', VALUE => 'notrump',
    CATEGORY => 'BLACKWOOD', VALUE => 'Blackwood'],
  ntJord => [ CATEGORY => 'DENOMINATIONS', VALUE => 'notrump',
    CATEGORY => 'MISC', VALUE => 'Jordan'],
  poinConvenient => [ CATEGORY => 'MISC', VALUE => 'Points',
    CATEGORY => 'MISC', VALUE => 'Convenient'],
  ptNT => [ CATEGORY => 'DENOMINATIONS', VALUE => 'notrump'],
  ptsOR => [ CATEGORY => 'MISC', VALUE => 'Points',
    CATEGORY => 'WORD', VALUE => 'or'],
  relayBL => [ CATEGORY => 'BLACKWOOD', VALUE => 'Blackwood'],
  saBwood => [ CATEGORY => 'DENOMINATIONS', VALUE => 'notrump',
    CATEGORY => 'BLACKWOOD', VALUE => 'Blackwood'],
  saRKB => [ CATEGORY => 'DENOMINATIONS', VALUE => 'notrump',
    CATEGORY => 'Keycard', VALUE => 'RKCB'],
  sayaCourtesy => [ CATEGORY => 'BASES', VALUE => 'SAYC'],
  spaNISH => [ CATEGORY => 'COUNTRY', VALUE => 'Spain'],
  strongNTweak => [ CATEGORY => 'OPENINGS', VALUE => 'Strong NT',
    CATEGORY => 'STRENGTHS', VALUE => 'weak'],
  strBLackw => [ CATEGORY => 'STRENGTHS', VALUE => 'strong',
    CATEGORY => 'BLACKWOOD', VALUE => 'Blackwood'],
  strBLKW => [ CATEGORY => 'STRENGTHS', VALUE => 'strong',
    CATEGORY => 'BLACKWOOD', VALUE => 'Blackwood'],
  suitF => [ CATEGORY => 'MISC', VALUE => 'Suit Forcing'],
  suitFG => [ CATEGORY => 'MISC', VALUE => 'Suit Game Forcing'],
  suitG => [ CATEGORY => 'MISC', VALUE => 'Suit Game Forcing'],
  suitGF => [ CATEGORY => 'MISC', VALUE => 'Suit Game Forcing'],
  "suppX's" => [ CATEGORY => 'COMPETITIVE', VALUE => 'Support Double'],
  thstF => [ CATEGORY => 'RANKS', VALUE => 'Ordinal Indicator',
    CATEGORY => 'MISC', VALUE => 'Suit Forcing'],
  thsuitF => [ CATEGORY => 'RANKS', VALUE => 'Ordinal Indicator',
    CATEGORY => 'MISC', VALUE => 'Suit Forcing'],
  thsutGF => [ CATEGORY => 'RANKS', VALUE => 'Ordinal Indicator',
    CATEGORY => 'MISC', VALUE => 'Suit Game Forcing'],
  thC => [ CATEGORY => 'RANKS', VALUE => 'Ordinal Indicator',
    CATEGORY => 'MISC', VALUE => 'Suit'],
  thCforc => [ CATEGORY => 'RANKS', VALUE => 'Ordinal Indicator',
    CATEGORY => 'MISC', VALUE => 'Suit Forcing'],
  thCol => [ CATEGORY => 'RANKS', VALUE => 'Ordinal Indicator',
    CATEGORY => 'MISC', VALUE => 'Suit'],
  thCF => [ CATEGORY => 'RANKS', VALUE => 'Ordinal Indicator',
    CATEGORY => 'MISC', VALUE => 'Suit Forcing'],
  thF => [ CATEGORY => 'RANKS', VALUE => 'Ordinal Indicator',
    CATEGORY => 'MISC', VALUE => 'Suit Forcing'],
  'thF!' => [ CATEGORY => 'RANKS', VALUE => 'Ordinal Indicator',
    CATEGORY => 'MISC', VALUE => 'Suit Forcing'],
  thForcing => [ CATEGORY => 'RANKS', VALUE => 'Ordinal Indicator',
    CATEGORY => 'MISC', VALUE => 'Suit Forcing'],
  thFG => [ CATEGORY => 'RANKS', VALUE => 'Ordinal Indicator',
    CATEGORY => 'MISC', VALUE => 'Suit Game Forcing'],
  thGF => [ CATEGORY => 'RANKS', VALUE => 'Ordinal Indicator',
    CATEGORY => 'MISC', VALUE => 'Suit Game Forcing'],
  thS => [ CATEGORY => 'RANKS', VALUE => 'Ordinal Indicator',
    CATEGORY => 'MISC', VALUE => 'Suit'],
  thSf => [ CATEGORY => 'RANKS', VALUE => 'Ordinal Indicator',
    CATEGORY => 'MISC', VALUE => 'Suit Forcing'],
  thStGF => [ CATEGORY => 'RANKS', VALUE => 'Ordinal Indicator',
    CATEGORY => 'MISC', VALUE => 'Suit Game Forcing'],
  thSForce => [ CATEGORY => 'RANKS', VALUE => 'Ordinal Indicator',
    CATEGORY => 'MISC', VALUE => 'Suit Forcing'],
  thSF => [ CATEGORY => 'RANKS', VALUE => 'Ordinal Indicator',
    CATEGORY => 'MISC', VALUE => 'Suit Forcing'],
  thSFG => [ CATEGORY => 'RANKS', VALUE => 'Ordinal Indicator',
    CATEGORY => 'MISC', VALUE => 'Suit Game Forcing'],
  thSuitF => [ CATEGORY => 'RANKS', VALUE => 'Ordinal Indicator',
    CATEGORY => 'MISC', VALUE => 'Suit Forcing'],
  thSuitGF => [ CATEGORY => 'RANKS', VALUE => 'Ordinal Indicator', CATEGORY => 'MISC', VALUE => 'Suit Forcing'],
  thSuitGameForce => [ CATEGORY => 'RANKS', VALUE => 'Ordinal Indicator',
    CATEGORY => 'MISC', VALUE => 'Suit Game Forcing'],
  thSGF => [ CATEGORY => 'RANKS', VALUE => 'Ordinal Indicator',
    CATEGORY => 'MISC', VALUE => 'Suit Game Forcing'],
  waitingTransfers => [ CATEGORY => 'MISC', VALUE => 'Waiting',
    CATEGORY => 'MISC', VALUE => 'Transfer'],
  weakRK => [ CATEGORY => 'STRENGTHS', VALUE => 'weak',
    CATEGORY => 'KEYCARD', VALUE => 'RKCB'],
  ACBLsayC => [ CATEGORY => 'BASES', VALUE => 'SAYC'],
  ANYNTisGerber => [ CATEGORY => 'CONSTRUCTIVE', VALUE => 'Gerber'],
  FORTenT => [ CATEGORY => 'STRENGTHS', VALUE => 'strong',
    CATEGORY => 'DENOMINATIONS', VALUE => 'clubs'],
  GurrRRRRR => [ CATEGORY => 'NAME_LAST', VALUE => 'Gurr'],
  RubyLM => [ CATEGORY => 'LEVEL', VALUE => 'Ruby Life Master'],
  SaycBoy => [ CATEGORY => 'BASES', VALUE => 'SAYC'],
  SEForSAYC => [ CATEGORY => 'BASES', VALUE => 'SEF',
    CATEGORY => 'BASES', VALUE => 'SAYC'],
  SilverLM => [ CATEGORY => 'LEVEL', VALUE => 'Silver Life Master'],
  VillaReal => [ CATEGORY => 'NAME_LAST', VALUE => 'Villareal'],
  SmyRnA => [ CATEGORY => 'CITY', VALUE => 'Smyrna'],
  ShanghaiNTBridgeClub => [ CATEGORY => 'CITY', VALUE => 'Shanghai'],
  ShangHai => [ CATEGORY => 'CITY', VALUE => 'Shanghai'],
  playPrecisionwithIndianflag => [ CATEGORY => 'BASES', VALUE => 'Precision'],
  PreferPrecision => [ CATEGORY => 'BASES', VALUE => 'Precision'],
  playMich => [ CATEGORY => 'COMPETITIVE', VALUE => 'Michaels'],
  ecIvoN => [ CATEGORY => 'LEVEL', VALUE => 'Novice'],
  senoJ => [ CATEGORY => 'NAME_LAST', VALUE => 'Jones'],
  learningTrfs => [ CATEGORY => 'MISC', VALUE => 'Transfer'],
  yokBARON => [ CATEGORY => 'WORD', VALUE => 'no',
    CATEGORY => 'CONSTRUCTIVE', VALUE => 'Baron'],
  xyzSmol => [ CATEGORY => 'CONSTRUCTIVE', VALUE => 'XYZ NT',
    CATEGORY => 'CONSTRUCTIVE', VALUE => 'Smolen'],
  wlshPupt => [ CATEGORY => 'CONSTRUCTIVE', VALUE => 'Walsh',
    CATEGORY => 'CONSTRUCTIVE', VALUE => 'Puppet'],
  wjumpDEFstandard => [ CATEGORY => 'CONSTRUCTIVE', VALUE => 'Weak Jump'],
  withStandard => [ CATEGORY => 'CONSTRUCTIVE', VALUE => 'Standard'],
  withRange => [ CATEGORY => 'MISC', VALUE => 'Range'],
  withPL => [ CATEGORY => 'MISC', VALUE => 'Polish'],
  weaknegDBL => [ CATEGORY => 'STRENGTHS', VALUE => 'weak',
    CATEGORY => 'COMPETITIVE', VALUE => 'Negative Double'],
  wartLebensol => [ CATEGORY => 'COMPETITIVE', VALUE => 'Lebensohl'],
  vnobileD => [ CATEGORY => 'BASES', VALUE => 'Five Card Major',
    CATEGORY => 'DENOMINATIONS', VALUE => 'diamonds'],
  upHCP => [ CATEGORY => 'MISC', VALUE => 'plus',
    CATEGORY => 'MISC', VALUE => 'Points'],
  unJ => [ CATEGORY => 'MISC', VALUE => 'Unusual'],
  unusDONT => [ CATEGORY => 'COMPETITIVE', VALUE => 'Unusual NT',
    CATEGORY => 'COMPETITIVE', VALUE => 'DONT'],
  unuNTMichaels => [ CATEGORY => 'COMPETITIVE', VALUE => 'Unusual NT',
    CATEGORY => 'COMPETITIVE', VALUE => 'Michaels'],
  unNTneg => [ CATEGORY => 'COMPETITIVE', VALUE => 'Unusual NT',
    CATEGORY => 'MISC', VALUE => 'Negative'],
  unNTcue => [ CATEGORY => 'COMPETITIVE', VALUE => 'Unusual NT'],
  udcaJ => [ CATEGORY => 'CARDING', VALUE => 'UDCA',
    CATEGORY => 'MISC', VALUE => 'Jacoby'],
  MichaelRevbergen => [ CATEGORY => 'COMPETITIVE', VALUE => 'Michaels',
    CATEGORY => 'BERGEN', VALUE => 'Reverse Bergen'],
  CappOrDONTorMeckwell => [ CATEGORY => 'COMPETITIVE', VALUE => 'Cappelletti',
    CATEGORY => 'COMPETITIVE', VALUE => 'DONT',
    CATEGORY => 'COMPETITIVE', VALUE => 'Meckwell Against NT'],
  bergenCAPPA => [ CATEGORY => 'BERGEN', VALUE => 'Bergen',
    CATEGORY => 'COMPETITIVE', VALUE => 'Cappelletti'],
  ntBergSpl => [ CATEGORY => 'DENOMINATIONS', VALUE => 'notrump',
    CATEGORY => 'BERGEN', VALUE => 'Bergen',
    CATEGORY => 'CONSTRUCTIVE', VALUE => 'Splinter'],
  StaymnJby => [ CATEGORY => 'STAYMAN', VALUE => 'Stayman',
    CATEGORY => 'MISC', VALUE => 'Jacoby'],
  DruryLandyRoudi => [ CATEGORY => 'CONSTRUCTIVE', VALUE => 'Drury',
    CATEGORY => 'COMPETITIVE', VALUE => 'Landy',
    CATEGORY => 'CONSTRUCTIVE', VALUE => 'Roudinesco'],
  NTGamblTexas => [ CATEGORY => 'OPENINGS', VALUE => 'Gambling 3NT',
    CATEGORY => 'MISC', VALUE => 'Texas'],
  CappTruscott => [CATEGORY => 'COMPETITIVE', VALUE => 'Cappelletti',
    CATEGORY => 'MISC', VALUE => 'Truscott'],
  DruryTruscottJacobi => [ CATEGORY => 'CONSTRUCTIVE', VALUE => 'Drury',
    CATEGORY => 'MISC', VALUE => 'Truscott',
    CATEGORY => 'MISC', VALUE => 'Jacoby'],
  StaymanJ => [ CATEGORY => 'STAYMAN', VALUE => 'Stayman'],
  saycM => [ CATEGORY => 'BASES', VALUE => 'SAYC',
    CATEGORY => 'RANKS', VALUE => 'major'],
  SaycM => [ CATEGORY => 'BASES', VALUE => 'SAYC',
    CATEGORY => 'RANKS', VALUE => 'major'],
  DruryDia => [ CATEGORY => 'CONSTRUCTIVE', VALUE => 'Drury',
    CATEGORY => 'DENOMINATIONS', VALUE => 'diamonds'],
  suitGFJordan => [ CATEGORY => 'MISC', VALUE => 'Suit Game Forcing',
      CATEGORY => 'MISC', VALUE => 'Jordan'],
  SaycJacobysplinterminispl => [ 
    CATEGORY => 'BASES', VALUE => 'SAYC',
    CATEGORY => 'MISC', VALUE => 'Jacoby',
    CATEGORY => 'CONSTRUCTIVE', VALUE => 'Splinter',
    CATEGORY => 'CONSTRUCTIVE', VALUE => 'Minisplinter'],
  ntJK => [ CATEGORY => 'DENOMINATIONS', VALUE => 'notrump',
    CATEGORY => 'MISC', VALUE => 'Jacoby'],
  CappOgustSupport => [ CATEGORY => 'COMPETITIVE', VALUE => 'Cappelletti',
    CATEGORY => 'CONSTRUCTIVE', VALUE => 'Ogust',
      CATEGORY => 'MISC', VALUE => 'Support'],
  thMopen => [ CATEGORY => 'RANKS', VALUE => 'Ordinal Indicator'],
  thM => [ CATEGORY => 'RANKS', VALUE => 'Ordinal Indicator',
    CATEGORY => 'RANKS', VALUE => 'major'],
  saM => [CATEGORY => 'DENOMINATIONS', VALUE => 'notrump',
    CATEGORY => 'RANKS', VALUE => 'major'],
  NTForcMaj => [CATEGORY => 'DENOMINATIONS', VALUE => 'notrump'],
  GerberONTO => [ CATEGORY => 'CONSTRUCTIVE', VALUE => 'Gerber'],
  PrivateSAYC => [ CATEGORY => 'BASES', VALUE => 'SAYC'],
  GerberDef => [ CATEGORY => 'CONSTRUCTIVE', VALUE => 'Gerber',
    CATEGORY => 'CARDING', VALUE => 'Carding'],
  bergenD => [CATEGORY => 'BERGEN', VALUE => 'Bergen',
    CATEGORY => 'DENOMINATIONS', VALUE => 'diamonds'],
  BergenCapMcuebit => [CATEGORY => 'BERGEN', VALUE => 'Bergen',
    CATEGORY => 'COMPETITIVE', VALUE => 'Cappelletti'],
  ntSplintCueMichWjsMulti => [ CATEGORY => 'DENOMINATIONS', VALUE => 'notrump',
    CATEGORY => 'CONSTRUCTIVE', VALUE => 'Splinter',
    CATEGORY => 'COMPETITIVE', VALUE => 'Michaels Cuebid',
    CATEGORY => 'COMPETITIVE', VALUE => 'Weak Jump Shift',
    CATEGORY => 'MISC', VALUE => 'Multi'],
  preferredBergen => [CATEGORY => 'BERGEN', VALUE => 'Bergen'],
  druryWJSsup => [ CATEGORY => 'CONSTRUCTIVE', VALUE => 'Drury',
    CATEGORY => 'COMPETITIVE', VALUE => 'Weak Jump Shift',
    CATEGORY => 'MISC', VALUE => 'Support'],
  strongWhen => [ CATEGORY => 'STRENGTHS', VALUE => 'strong'],
  SAYCorACOL => [ CATEGORY => 'BASES', VALUE => 'SAYC',
    CATEGORY => 'BASES', VALUE => 'Acol'],
  SAYCorPREC => [ CATEGORY => 'BASES', VALUE => 'SAYC',
    CATEGORY => 'BASES', VALUE => 'Precision'],
  SAYCforNT => [ CATEGORY => 'BASES', VALUE => 'SAYC',
    CATEGORY => 'DENOMINATIONS', VALUE => 'notrump'],
  weakNTinvmi => [ CATEGORY => 'OPENINGS', VALUE => 'Weak NT',
    CATEGORY => 'CONSTRUCTIVE', VALUE => 'Inverted Minors'],
  NTJordanFlipFlopMichCappLebSuppXDrurySmithStdcrd => [
    CATEGORY => 'DENOMINATIONS', VALUE => 'notrump',
    CATEGORY => 'MISC', VALUE => 'Jordan',
    CATEGORY => 'COMPETITIVE', VALUE => 'Flip Flop',
    CATEGORY => 'COMPETITIVE', VALUE => 'Michaels Cuebid',
    CATEGORY => 'COMPETITIVE', VALUE => 'Cappelletti',
    CATEGORY => 'COMPETITIVE', VALUE => 'Lebensohl',
    CATEGORY => 'COMPETITIVE', VALUE => 'Support Double',
    CATEGORY => 'CONSTRUCTIVE', VALUE => 'Drury',
    CATEGORY => 'CARDING', VALUE => 'Smith Echo',
    CATEGORY => 'CARDING', VALUE => 'Standard Carding'],
  NTMultiJordanFlipFlopMichCappLebSuppX => [
    CATEGORY => 'DENOMINATIONS', VALUE => 'notrump',
    CATEGORY => 'OPENINGS', VALUE => '2D Multi',
    CATEGORY => 'MISC', VALUE => 'Jordan',
    CATEGORY => 'COMPETITIVE', VALUE => 'Flip Flop',
    CATEGORY => 'COMPETITIVE', VALUE => 'Michaels Cuebid',
    CATEGORY => 'COMPETITIVE', VALUE => 'Cappelletti',
    CATEGORY => 'COMPETITIVE', VALUE => 'Lebensohl',
    CATEGORY => 'COMPETITIVE', VALUE => 'Support Double'],
  SaycMichInvMinSmolenCappdont => [
    CATEGORY => 'BASES', VALUE => 'SAYC',
    CATEGORY => 'COMPETITIVE', VALUE => 'Michaels Cuebid',
    CATEGORY => 'CONSTRUCTIVE', VALUE => 'Inverted Minors',
    CATEGORY => 'CONSTRUCTIVE', VALUE => 'Smolen',
    CATEGORY => 'COMPETITIVE', VALUE => 'Cappelletti',
    CATEGORY => 'COMPETITIVE', VALUE => 'DONT'],
  StaymanSupers => [ CATEGORY => 'STAYMAN', VALUE => 'Stayman',
    CATEGORY => 'CONSTRUCTIVE', VALUE => 'Super Accepts'],
  DrurySmolenLebensohleUDCA => [
    CATEGORY => 'CONSTRUCTIVE', VALUE => 'Drury',
    CATEGORY => 'CONSTRUCTIVE', VALUE => 'Smolen',
    CATEGORY => 'COMPETITIVE', VALUE => 'Lebensohl',
    CATEGORY => 'CARDING', VALUE => 'UDCA'],
  CappDruryJacobyBergenMulti => [
    CATEGORY => 'COMPETITIVE', VALUE => 'Cappelletti',
    CATEGORY => 'CONSTRUCTIVE', VALUE => 'Drury',
    CATEGORY => 'MISC', VALUE => 'Jacoby',
    CATEGORY => 'BERGEN', VALUE => 'Bergen',
    CATEGORY => 'OPENINGS', VALUE => '2D Multi'],
  StaymanTransfersWeak => [ CATEGORY => 'STAYMAN', VALUE => 'Stayman',
    CATEGORY => 'MISC', VALUE => 'Transfer',
    CATEGORY => 'STRENGTHS', VALUE => 'weak'],
  StaymnTrsferBwd => [ CATEGORY => 'STAYMAN', VALUE => 'Stayman',
    CATEGORY => 'MISC', VALUE => 'Transfer',
    CATEGORY => 'BLACKWOOD', VALUE => 'Blackwood'],
  NTRBgnSpltr => [ CATEGORY => 'DENOMINATIONS', VALUE => 'notrump',
    CATEGORY => 'BERGEN', VALUE => 'Reverse Bergen',
    CATEGORY => 'CONSTRUCTIVE', VALUE => 'Splinter'],
  CappNO => [ CATEGORY => 'COMPETITIVE', VALUE => 'Cappelletti',
    CATEGORY => 'MISC', VALUE => 'no'],
  BergenTexasNegD => [ CATEGORY => 'BERGEN', VALUE => 'Bergen',
    CATEGORY => 'MISC', VALUE => 'Texas',
    CATEGORY => 'COMPETITIVE', VALUE => 'Negative Double'],
  druryOgustneg => [ CATEGORY => 'CONSTRUCTIVE', VALUE => 'Drury',
    CATEGORY => 'CONSTRUCTIVE', VALUE => 'Ogust',
    CATEGORY => 'MISC', VALUE => 'Negative'],
  KinsBergen => [ CATEGORY => 'MISC', VALUE => 'kings',
    CATEGORY => 'BERGEN', VALUE => 'Bergen'],
  transferM => [ CATEGORY => 'MISC', VALUE => 'Transfer',
    CATEGORY => 'RANKS', VALUE => 'major'],
  TransferM => [ CATEGORY => 'MISC', VALUE => 'Transfer',
    CATEGORY => 'RANKS', VALUE => 'major'],
  drurySOMA => [ CATEGORY => 'CONSTRUCTIVE', VALUE => 'Drury'],
  SAYCNegXWk => [ CATEGORY => 'BASES', VALUE => 'SAYC',
    CATEGORY => 'COMPETITIVE', VALUE => 'Negative Double',
    CATEGORY => 'STRENGTHS', VALUE => 'weak'],
  ntJacsplin => [ CATEGORY => 'DENOMINATIONS', VALUE => 'notrump',
    CATEGORY => 'MISC', VALUE => 'Jacoby',
    CATEGORY => 'CONSTRUCTIVE', VALUE => 'Splinter'],
  ntGF => [ CATEGORY => 'DENOMINATIONS', VALUE => 'notrump',
    CATEGORY => 'MISC', VALUE => 'Game Forcing'],
  SuitFor => [ CATEGORY => 'MISC', VALUE => 'Suit Forcing'],
  strongNTshortclub => [ CATEGORY => 'OPENINGS', VALUE => 'Strong NT',
    CATEGORY => 'OPENINGS', VALUE => 'Short Club'],
  strongUNT => [ CATEGORY => 'STRENGTHS', VALUE => 'strong',
    CATEGORY => 'COMPETITIVE', VALUE => 'Unusual NT'],
  thLds => [ CATEGORY => 'RANKS', VALUE => 'Ordinal Indicator',
    CATEGORY => 'MISC', VALUE => 'Lead'],
  NTFeatrNXthru => [ CATEGORY => 'DENOMINATIONS', VALUE => 'notrump',
    CATEGORY => 'MISC', VALUE => 'Feature',
    CATEGORY => 'COMPETITIVE', VALUE => 'Negative Double',
    CATEGORY => 'MISC', VALUE => 'through'],
  orStrong => [ CATEGORY => 'MISC', VALUE => 'or',
    CATEGORY => 'STRENGTHS', VALUE => 'strong'],
  noBergen => [ CATEGORY => 'MISC', VALUE => 'no',
    CATEGORY => 'BERGEN', VALUE => 'Bergen'],
  expertoPrivate => [ CATEGORY => 'LEVEL', VALUE => 'Expert'],
  KetncBergen => [ CATEGORY => 'BERGEN', VALUE => 'Bergen'],
  thBest => [ CATEGORY => 'RANKS', VALUE => 'Ordinal Indicator',
    CATEGORY => 'MISC', VALUE => 'Lead'],
  thBEST => [ CATEGORY => 'RANKS', VALUE => 'Ordinal Indicator',
    CATEGORY => 'MISC', VALUE => 'Lead'],
  TransferAlSplinterBergen  => [
    CATEGORY => 'MISC', VALUE => 'Transfer',
    CATEGORY => 'CONSTRUCTIVE', VALUE => 'Splinter',
    CATEGORY => 'BERGEN', VALUE => 'Bergen'],
  BergenMichaelsCappGambling => [
    CATEGORY => 'BERGEN', VALUE => 'Bergen',
    CATEGORY => 'COMPETITIVE', VALUE => 'Michaels Cuebid',
    CATEGORY => 'COMPETITIVE', VALUE => 'Cappelletti',
    CATEGORY => 'OPENINGS', VALUE => 'Gambling 3NT'],
  PrivateSLM => [ CATEGORY => 'LEVEL', VALUE => 'Silver Life Master'],

);

sub match
{
  my ($text, $splits) = @_;

  if (exists $FRAGMENTS{$text})
  {
    $splits = $FRAGMENTS{$text};
    return 1;
  }
  else
  {
    return 0;
  }
}

1;
