#!perl

package Caps::Names;

use v5.10;
use strict;
use warnings;
use utf8;
use open ':std', ':encoding(UTF-8)';

use Exporter;

our @ISA = qw(Exporter);
our @EXPORT = qw(split);

my %NAMES =
(
  AAlankBondo => [ CATEGORY => 'NAME_FIRST', VALUE => 'Alan', CATEGORY => 'NAME_INITIALS', VALUE => 'K.', CATEGORY => 'NAME_LAST', VALUE => 'Bondo' ],
  AFLindaY => [ CATEGORY => 'NAME_FIRST', VALUE => 'Lindy', CATEGORY => 'NAME_INITIALS', VALUE => 'Y.' ],
  AThanassiadIs => [ CATEGORY => 'NAME_LAST', VALUE => 'Athanassiadis' ],
  AWFdenHaring => [ CATEGORY => 'NAME_INITIALS', VALUE => 'A. W. F.', CATEGORY => 'NAME_PARTICLES', VALUE => 'den', CATEGORY => 'NAME_LAST', VALUE => 'Haring' ],
  AbdKader => [ CATEGORY => 'NAME_FIRST', VALUE => 'Abd', CATEGORY => 'NAME_LAST', VALUE => 'Kader' ],
  AbidiN => [ CATEGORY => 'NAME_LAST', VALUE => 'Abidi', CATEGORY => 'NAME_INITIALS', VALUE => 'N.' ],
  AchenK => [ CATEGORY => 'NAME_FIRST', VALUE => 'Achen', CATEGORY => 'NAME_INITIALS', VALUE => 'K.' ],
  AdiWijaya => [ CATEGORY => 'NAME_FIRST', VALUE => 'Adi', CATEGORY => 'NAME_LAST', VALUE => 'Wijaya' ],
  AdieSue => [ CATEGORY => 'NAME_FIRST', VALUE => 'Adie Sue' ],
  AhmetCan => [ CATEGORY => 'NAME_FIRST', VALUE => 'Ahmet', CATEGORY => 'NAME_LAST', VALUE => 'Can' ],
  AiLeuS => [ CATEGORY => 'NAME_FIRST', VALUE => 'Ai Leu', CATEGORY => 'NAME_INITIALS', VALUE => 'S.' ],
  AiQiuFu => [ CATEGORY => 'NAME_FIRST', VALUE => 'Ai Qiu', CATEGORY => 'NAME_LAST', VALUE => 'Fu' ],
  AiliHelena => [ CATEGORY => 'NAME_LAST', VALUE => 'Aili', CATEGORY => 'NAME_FIRST', VALUE => 'Helena' ],
  AlanChen => [ CATEGORY => 'NAME_FIRST', VALUE => 'Alan', CATEGORY => 'NAME_LAST', VALUE => 'Chen' ],
  AlanH => [ CATEGORY => 'NAME_FIRST', VALUE => 'Alan', CATEGORY => 'NAME_INITIALS', VALUE => 'H.' ],
  AlbertoDeSordi => [ CATEGORY => 'NAME_FIRST', VALUE => 'Alberto', CATEGORY => 'NAME_PARTICLES', VALUE => 'de', CATEGORY => 'NAME_LAST', VALUE => 'Sordi' ],
  AlenkaNikl => [ CATEGORY => 'NAME_FIRST', VALUE => 'Alenka', CATEGORY => 'NAME_LAST', VALUE => 'Nikl' ],
  AlexD => [ CATEGORY => 'NAME_FIRST', VALUE => 'Alex', CATEGORY => 'NAME_INITIALS', VALUE => 'D.' ],
  AlexPris => [ CATEGORY => 'NAME_FIRST', VALUE => 'Alex', CATEGORY => 'NAME_LAST', VALUE => 'Pris' ],
  AlexSveinson => [ CATEGORY => 'NAME_FIRST', VALUE => 'Alex', CATEGORY => 'NAME_LAST', VALUE => 'Sveinson' ],
  AlexandreLITVAK => [ CATEGORY => 'NAME_FIRST', VALUE => 'Alexandre', CATEGORY => 'NAME_LAST', VALUE => 'Litvak' ],
  AliHaydar => [ CATEGORY => 'NAME_FIRST', VALUE => 'Ali', CATEGORY => 'NAME_LAST', VALUE => 'Haydar' ],
  AliR => [ CATEGORY => 'NAME_FIRST', VALUE => 'Ali', CATEGORY => 'NAME_INITIALS', VALUE => 'R.' ],
  AliYAVUZ => [ CATEGORY => 'NAME_FIRST', VALUE => 'AliFIRST', CATEGORY => 'NAME_LAST', VALUE => 'Yavuz' ],
  AliYaþarÜnal  => [ CATEGORY => 'NAME_FIRST', VALUE => 'Ali Yaþar', CATEGORY => 'NAME_LAST', VALUE => 'Ünal' ],
  AliciaBeatriz => [ CATEGORY => 'NAME_FIRST', VALUE => 'Alicia Beatriz' ],
  AllenLevy => [ CATEGORY => 'NAME_FIRST', VALUE => 'Allen', CATEGORY => 'NAME_LAST', VALUE => 'Levy' ],
  AlpArslan => [ CATEGORY => 'NAME_FIRST', VALUE => 'Alp', CATEGORY => 'NAME_LAST', VALUE => 'Arslan' ],
  AlpEren => [ CATEGORY => 'NAME_FIRST', VALUE => 'Alp', CATEGORY => 'NAME_LAST', VALUE => 'Eren' ],
  AmisFRANCO => [ CATEGORY => 'NAME_FIRST', VALUE => 'Amis', CATEGORY => 'NAME_LAST', VALUE => 'Franco' ],
  AmyLin => [ CATEGORY => 'NAME_FIRST', VALUE => 'Amy', CATEGORY => 'NAME_LAST', VALUE => 'Lin' ],
  AmyZhao => [ CATEGORY => 'NAME_FIRST', VALUE => 'Amy', CATEGORY => 'NAME_LAST', VALUE => 'Zhao' ],
  AndersonDuplit => [ CATEGORY => 'NAME_FIRST', VALUE => 'Anderson', CATEGORY => 'NAME_LAST', VALUE => 'Duplit' ],
  AngElisabeth => [ CATEGORY => 'NAME_FIRST', VALUE => 'Elisabeth', CATEGORY => 'NAME_LAST', VALUE => 'Ang' ],
  AngelaRC => [ CATEGORY => 'NAME_FIRST', VALUE => 'Angela', CATEGORY => 'NAME_INITIALS', VALUE => 'R. C.' ],
  AniaAdas => [ CATEGORY => 'NAME_FIRST', VALUE => 'Ania', CATEGORY => 'NAME_LAST', VALUE => 'Adas' ],
  AnnLena => [ CATEGORY => 'NAME_FIRST', VALUE => 'Ann Lena' ],
  AnnMorton => [ CATEGORY => 'NAME_FIRST', VALUE => 'Ann', CATEGORY => 'NAME_LAST', VALUE => 'Morton' ],
  AnnaGailChapman => [ CATEGORY => 'NAME_FIRST', VALUE => 'Anna Gail', CATEGORY => 'NAME_LAST', VALUE => 'Chapman' ],
  AnnaMaria => [ CATEGORY => 'NAME_FIRST', VALUE => 'Anna Maria' ],
  AnnaOlsen => [ CATEGORY => 'NAME_FIRST', VALUE => 'Anna', CATEGORY => 'NAME_LAST', VALUE => 'Olsen' ],
  AnneB => [ CATEGORY => 'NAME_FIRST', VALUE => 'Anne', CATEGORY => 'NAME_INITIALS', VALUE => 'B.' ],
  AnneFreeman => [ CATEGORY => 'NAME_FIRST', VALUE => 'Anned', CATEGORY => 'NAME_LAST', VALUE => 'Freeman' ],
  AnneKristine => [ CATEGORY => 'NAME_FIRST', VALUE => 'Anne Kristine' ],
  AnneLiao => [ CATEGORY => 'NAME_FIRST', VALUE => 'Anne', CATEGORY => 'NAME_LAST', VALUE => 'Liao' ],
  AnneMaria => [ CATEGORY => 'NAME_FIRST', VALUE => 'Anne Maria' ],
  AnneMarie => [ CATEGORY => 'NAME_FIRST', VALUE => 'Anne Marie' ],
  AnneMette => [ CATEGORY => 'NAME_FIRST', VALUE => 'Anne Mette' ],
  AnneMieke => [ CATEGORY => 'NAME_FIRST', VALUE => 'Anne Mieke' ],
  AnneSophie => [ CATEGORY => 'NAME_FIRST', VALUE => 'Anne Sophie' ],
  AnnieDomhof => [ CATEGORY => 'NAME_FIRST', VALUE => 'Annie', CATEGORY => 'NAME_LAST', VALUE => 'Domhof' ],
  AnnieLaure => [ CATEGORY => 'NAME_FIRST', VALUE => 'Annie Laure' ],
  AnuggrahAffdal => [ CATEGORY => 'NAME_FIRST', VALUE => 'Affdal', CATEGORY => 'NAME_LAST', VALUE => 'Anuggrah' ],
  ArntO => [ CATEGORY => 'NAME_FIRST', VALUE => 'Arnt', CATEGORY => 'NAME_INITIALS', VALUE => 'O.' ],
  ArturK => [ CATEGORY => 'NAME_FIRST', VALUE => 'Artur', CATEGORY => 'NAME_INITIALS', VALUE => 'K' ],
  ArunPal => [ CATEGORY => 'NAME_FIRST', VALUE => 'Arun', CATEGORY => 'NAME_LAST', VALUE => 'Pal' ],
  AvishekDolui => [ CATEGORY => 'NAME_FIRST', VALUE => 'Avishek', CATEGORY => 'NAME_LAST', VALUE => 'Dolui' ],
  BaiLing => [ CATEGORY => 'NAME_FIRST', VALUE => 'Ling', CATEGORY => 'NAME_LAST', VALUE => 'Bai' ],
  BarbaraCameron => [ CATEGORY => 'NAME_FIRST', VALUE => 'Barbara', CATEGORY => 'NAME_LAST', VALUE => 'Cameron' ],
  BarbaraSopkin => [ CATEGORY => 'NAME_FIRST', VALUE => 'Barbara', CATEGORY => 'NAME_LAST', VALUE => 'Sopkin' ],
  BarbaraWeston => [ CATEGORY => 'NAME_FIRST', VALUE => 'Barbara', CATEGORY => 'NAME_LAST', VALUE => 'Weston' ],
  BartK => [ CATEGORY => 'NAME_FIRST', VALUE => 'Bart', CATEGORY => 'NAME_INITIALS', VALUE => 'K.' ],
  BasBolk => [ CATEGORY => 'NAME_FIRST', VALUE => 'Bas', CATEGORY => 'NAME_LAST', VALUE => 'Bolk' ],
  BayuSetyanto => [ CATEGORY => 'NAME_FIRST', VALUE => 'Bayu', CATEGORY => 'NAME_LAST', VALUE => 'Setyanto' ],
  BeeBee => [ CATEGORY => 'NAME_FIRST', VALUE => 'Bee Bee' ],
  BeeJay => [ CATEGORY => 'NAME_FIRST', VALUE => 'Bee Jay' ],
  BehrensRe => [ CATEGORY => 'NAME_FIRST', VALUE => 'Regina', CATEGORY => 'NAME_LAST', VALUE => 'Behrens' ],
  BenOrzeske => [ CATEGORY => 'NAME_FIRST', VALUE => 'BEN', CATEGORY => 'NAME_LAST', VALUE => 'Orzeske' ],
  BerkinElvan => [ CATEGORY => 'NAME_FIRST', VALUE => 'Berkin', CATEGORY => 'NAME_LAST', VALUE => 'Elvan' ],
  BernardK => [ CATEGORY => 'NAME_FIRST', VALUE => 'Bernard', CATEGORY => 'NAME_INITIALS', VALUE => 'K.' ],
  BethAnne => [ CATEGORY => 'NAME_FIRST', VALUE => 'Beth Anne' ],
  BetsyM => [ CATEGORY => 'NAME_FIRST', VALUE => 'Betsy', CATEGORY => 'NAME_INITIALS', VALUE => 'M.' ],
  BettyGYoung => [ CATEGORY => 'NAME_FIRST', VALUE => 'Betty', CATEGORY => 'NAME_INITIALS', VALUE => 'G.', CATEGORY => 'NAME_LAST', VALUE => 'Young' ],
  BettyJane => [ CATEGORY => 'NAME_FIRST', VALUE => 'Betty Jane' ],
  BillFair => [ CATEGORY => 'NAME_FIRST', VALUE => 'Bill', CATEGORY => 'NAME_LAST', VALUE => 'Fair' ],
  BillSmith => [ CATEGORY => 'NAME_FIRST', VALUE => 'Bill', CATEGORY => 'NAME_LAST', VALUE => 'Smith' ],
  BillyJack => [ CATEGORY => 'NAME_FIRST', VALUE => 'Billy Jack' ],
  BillyTsang => [ CATEGORY => 'NAME_FIRST', VALUE => 'Billy', CATEGORY => 'NAME_LAST', VALUE => 'Tsang' ],
  BirGÜN => [ CATEGORY => 'NAME_FIRST', VALUE => 'Birgün' ],
  BirGün => [ CATEGORY => 'NAME_FIRST', VALUE => 'Birgün' ],
  BismailC => [ CATEGORY => 'NAME_FIRST', VALUE => 'Ismail', CATEGORY => 'NAME_INITIALS', VALUE => 'C' ],
  BjornQuistgard => [ CATEGORY => 'NAME_FIRST', VALUE => 'Bjorn', CATEGORY => 'NAME_LAST', VALUE => 'Quistgard' ],
  BoYuanCheng => [ CATEGORY => 'NAME_FIRST', VALUE => 'Bo Yuan', CATEGORY => 'NAME_LAST', VALUE => 'Cheng' ],
  BobCrossley => [ CATEGORY => 'NAME_FIRST', VALUE => 'Bob', CATEGORY => 'NAME_LAST', VALUE => 'Crossley' ],
  BogdanB => [ CATEGORY => 'NAME_FIRST', VALUE => 'Bogdan', CATEGORY => 'NAME_INITIALS', VALUE => 'B.' ],
  BonnY => [ CATEGORY => 'NAME_FIRST', VALUE => 'Bonny' ],
  BonnieBond => [ CATEGORY => 'NAME_FIRST', VALUE => 'Bonnie', CATEGORY => 'NAME_LAST', VALUE => 'Bond' ],
  BromadJord => [ CATEGORY => 'NAME_FIRST', VALUE => 'Bromad', CATEGORY => 'NAME_LAST', VALUE => 'Jord' ],
  BruceLemle => [ CATEGORY => 'NAME_FIRST', VALUE => 'Bruce', CATEGORY => 'NAME_LAST', VALUE => 'Lemle' ],
  BrunoB => [ CATEGORY => 'NAME_FIRST', VALUE => 'Bruno', CATEGORY => 'NAME_INITIALS', VALUE => 'B.' ],
  BryanLee => [ CATEGORY => 'NAME_FIRST', VALUE => 'Bryan', CATEGORY => 'NAME_LAST', VALUE => 'Lee' ],
  CZvanDeursen => [ CATEGORY => 'NAME_INITIALS', VALUE => 'C. Z.', CATEGORY => 'NAME_PARTICLES', VALUE => 'van', CATEGORY => 'NAME_LAST', VALUE => 'Deursen' ],
  CahTlogosari => [ CATEGORY => 'NAME_FIRST', VALUE => 'Tlogosari', CATEGORY => 'NAME_LAST', VALUE => 'Cah' ],
  CalveteJaimes => [ CATEGORY => 'NAME_FIRST', VALUE => 'Calvete', CATEGORY => 'NAME_LAST', VALUE => 'Jaimes' ],
  CaoDinghong => [ CATEGORY => 'NAME_FIRST', VALUE => 'Dinghong', CATEGORY => 'NAME_LAST', VALUE => 'Cao' ],
  CarlosAlberto => [ CATEGORY => 'NAME_FIRST', VALUE => 'Carlos Alberto' ],
  CarmelBailey => [ CATEGORY => 'NAME_FIRST', VALUE => 'Carmel', CATEGORY => 'NAME_LAST', VALUE => 'Bailey' ],
  CaroIine => [ CATEGORY => 'NAME_FIRST', VALUE => 'Caroline' ],
  CarolB => [ CATEGORY => 'NAME_FIRST', VALUE => 'Carol', CATEGORY => 'NAME_INITIALS', VALUE => 'B.' ],
  CarolDevitt => [ CATEGORY => 'NAME_FIRST', VALUE => 'Carol', CATEGORY => 'NAME_LAST', VALUE => 'Devitt' ],
  CarolM => [ CATEGORY => 'NAME_FIRST', VALUE => 'Carol', CATEGORY => 'NAME_INITIALS', VALUE => 'M.' ],
  CarolPicot => [ CATEGORY => 'NAME_FIRST', VALUE => 'Carol', CATEGORY => 'NAME_LAST', VALUE => 'Picot' ],
  CasjB => [ CATEGORY => 'NAME_FIRST', VALUE => 'Casj', CATEGORY => 'NAME_INITIALS', VALUE => 'B.' ],
  CeciStone => [ CATEGORY => 'NAME_FIRST', VALUE => 'Ceci', CATEGORY => 'NAME_LAST', VALUE => 'Stone' ],
  ChadKimberly => [ CATEGORY => 'NAME_FIRST', VALUE => 'Chad Kimberly' ],
  ChandraShekhar => [ CATEGORY => 'NAME_FIRST', VALUE => 'Chandra', CATEGORY => 'NAME_LAST', VALUE => 'Shekhar' ],
  ChangJiang => [ CATEGORY => 'NAME_FIRST', VALUE => 'Jiang', CATEGORY => 'NAME_LAST', VALUE => 'Chang' ],
  CharlesPasco => [ CATEGORY => 'NAME_FIRST', VALUE => 'Charles', CATEGORY => 'NAME_LAST', VALUE => 'Pasco' ],
  CharlieC => [ CATEGORY => 'NAME_FIRST', VALUE => 'Charlie', CATEGORY => 'NAME_INITIALS', VALUE => 'C.' ],
  CharlotteT => [ CATEGORY => 'NAME_FIRST', VALUE => 'Charlotte', CATEGORY => 'NAME_INITIALS', VALUE => 'T.' ],
  CharlotteWolfe => [ CATEGORY => 'NAME_FIRST', VALUE => 'Charlotte', CATEGORY => 'NAME_LAST', VALUE => 'Wolfe' ],
  ChenChangXu => [ CATEGORY => 'NAME_FIRST', VALUE => 'Chang Xu', CATEGORY => 'NAME_LAST', VALUE => 'Chen' ],
  ChenRunhua => [ CATEGORY => 'NAME_FIRST', VALUE => 'Runhua', CATEGORY => 'NAME_LAST', VALUE => 'Chen' ],
  ChenXi => [ CATEGORY => 'NAME_FIRST', VALUE => 'Xi', CATEGORY => 'NAME_LAST', VALUE => 'Chen' ],
  ChengJun => [ CATEGORY => 'NAME_FIRST', VALUE => 'Jun', CATEGORY => 'NAME_LAST', VALUE => 'Cheng' ],
  ChengYing => [ CATEGORY => 'NAME_FIRST', VALUE => 'Ying', CATEGORY => 'NAME_LAST', VALUE => 'Cheng' ],
  ChiaraAngela => [ CATEGORY => 'NAME_FIRST', VALUE => 'Chiara Angela' ],
  ChrisWols => [ CATEGORY => 'NAME_FIRST', VALUE => 'Chris', CATEGORY => 'NAME_LAST', VALUE => 'Wols' ],
  ChristinaEagan => [ CATEGORY => 'NAME_FIRST', VALUE => 'Christina', CATEGORY => 'NAME_LAST', VALUE => 'Eagan' ],
  ChristinaGustavsson => [ CATEGORY => 'NAME_FIRST', VALUE => 'Christina', CATEGORY => 'NAME_LAST', VALUE => 'Gustavsson' ],
  ChuFa => [ CATEGORY => 'NAME_FIRST', VALUE => 'Chu Fa' ],
  ChuckStaben => [ CATEGORY => 'NAME_FIRST', VALUE => 'Chuck', CATEGORY => 'NAME_LAST', VALUE => 'Staben' ],
  ChunHong => [ CATEGORY => 'NAME_FIRST', VALUE => 'Chun', CATEGORY => 'NAME_LAST', VALUE => 'Hong' ],
  ClarissaO => [ CATEGORY => 'NAME_FIRST', VALUE => 'Clarissa', CATEGORY => 'NAME_INITIALS', VALUE => 'O.' ],
  ClaudeLeboeuf => [ CATEGORY => 'NAME_FIRST', VALUE => 'Claude', CATEGORY => 'NAME_LAST', VALUE => 'Leboeuf' ],
  ClaudeRousseau => [ CATEGORY => 'NAME_FIRST', VALUE => 'Claude', CATEGORY => 'NAME_LAST', VALUE => 'Rousseau' ],
  ClaudiaHansen => [ CATEGORY => 'NAME_FIRST', VALUE => 'Claudia', CATEGORY => 'NAME_LAST', VALUE => 'Hansen' ],
  CraigJones => [ CATEGORY => 'NAME_FIRST', VALUE => 'Craig', CATEGORY => 'NAME_LAST', VALUE => 'Jones' ],
  CumhuriyetL => [ CATEGORY => 'NAME_FIRST', VALUE => 'Cumhuriyet', CATEGORY => 'NAME_INITIALS', VALUE => 'L.' ],
  DTomTrottier => [ CATEGORY => 'NAME_INITIALS', VALUE => 'D.', CATEGORY => 'NAME_FIRST', VALUE => 'Tom', CATEGORY => 'NAME_LAST', VALUE => 'Trottier' ],
  DaisyKenedi => [ CATEGORY => 'NAME_FIRST', VALUE => 'Daisy', CATEGORY => 'NAME_LAST', VALUE => 'Kenedi' ],
  DanHu => [ CATEGORY => 'NAME_FIRST', VALUE => 'Dan', CATEGORY => 'NAME_LAST', VALUE => 'Hu' ],
  DanStoica => [ CATEGORY => 'NAME_FIRST', VALUE => 'Dan', CATEGORY => 'NAME_LAST', VALUE => 'Stoica' ],
  DanielaB => [ CATEGORY => 'NAME_FIRST', VALUE => 'Daniela', CATEGORY => 'NAME_INITIALS', VALUE => 'B.' ],
  DarkoSeremet => [ CATEGORY => 'NAME_FIRST', VALUE => 'Darko', CATEGORY => 'NAME_LAST', VALUE => 'Seremet' ],
  DateMasamune => [ CATEGORY => 'NAME_FIRST', VALUE => 'Date', CATEGORY => 'NAME_LAST', VALUE => 'Masamune' ],
  DaveGermaine => [ CATEGORY => 'NAME_FIRST', VALUE => 'Dave', CATEGORY => 'NAME_LAST', VALUE => 'Germaine' ],
  DeanAdams => [ CATEGORY => 'NAME_FIRST', VALUE => 'Dean', CATEGORY => 'NAME_LAST', VALUE => 'Adams' ],
  DeboraCampagnanoDomenech => [ CATEGORY => 'NAME_FIRST', VALUE => 'Debora', CATEGORY => 'NAME_LAST', VALUE => 'Campagnano Domenech' ],
  DeeAnn => [ CATEGORY => 'NAME_FIRST', VALUE => 'Dee Ann' ],
  DeeDee => [ CATEGORY => 'NAME_FIRST', VALUE => 'Dee Dee' ],
  DeeMiller => [ CATEGORY => 'NAME_FIRST', VALUE => 'Dee', CATEGORY => 'NAME_LAST', VALUE => 'Miller' ],
  DellaCroix => [ CATEGORY => 'NAME_PARTICLES', VALUE => 'della', CATEGORY => 'NAME_LAST', VALUE => 'Croix' ],
  DemirciogIu => [ CATEGORY => 'NAME_LAST', VALUE => 'Demircioglu' ],
  DenizWize => [ CATEGORY => 'NAME_FIRST', VALUE => 'Deniz', CATEGORY => 'NAME_LAST', VALUE => 'Wize' ],
  DennyHsu => [ CATEGORY => 'NAME_FIRST', VALUE => 'Denny', CATEGORY => 'NAME_LAST', VALUE => 'Hsu' ],
  DennyP => [ CATEGORY => 'NAME_FIRST', VALUE => 'Denny', CATEGORY => 'NAME_INITIALS', VALUE => 'P.' ],
  DeshpandeChandrashekharP => [ CATEGORY => 'NAME_FIRST', VALUE => 'Deshpande Chandrashekhar', CATEGORY => 'NAME_INITIALS', VALUE => 'P.' ],
  DianeHanoski => [ CATEGORY => 'NAME_FIRST', VALUE => 'Diane', CATEGORY => 'NAME_LAST', VALUE => 'Hanoski' ],
  DianeHyppa => [ CATEGORY => 'NAME_FIRST', VALUE => 'Diane', CATEGORY => 'NAME_LAST', VALUE => 'Hyppa' ],
  DickdeJoode => [ CATEGORY => 'NAME_FIRST', VALUE => 'Dick', CATEGORY => 'NAME_PARTICLES', VALUE => 'de', CATEGORY => 'NAME_LAST', VALUE => 'Joode' ],
  DingYu => [ CATEGORY => 'NAME_FIRST', VALUE => 'Yu', CATEGORY => 'NAME_LAST', VALUE => 'Ding' ],
  DirekDEFOS => [ CATEGORY => 'NAME_FIRST', VALUE => 'Direk', CATEGORY => 'NAME_LAST', VALUE => 'Defos' ],
  DirenGeziParki => [ CATEGORY => 'NAME_FIRST', VALUE => 'Diren Gezi', CATEGORY => 'NAME_LAST', VALUE => 'Parki' ],
  DirenKOBANE => [ CATEGORY => 'NAME_FIRST', VALUE => 'Diren', CATEGORY => 'NAME_LAST', VALUE => 'Kobane' ],
  DirkJan => [ CATEGORY => 'NAME_FIRST', VALUE => 'Dirk Jan' ],
  DirkJens => [ CATEGORY => 'NAME_FIRST', VALUE => 'Dirk Jens' ],
  DoloresSwale => [ CATEGORY => 'NAME_FIRST', VALUE => 'Dolores', CATEGORY => 'NAME_LAST', VALUE => 'Swale' ],
  DonHer => [ CATEGORY => 'NAME_FIRST', VALUE => 'Don', CATEGORY => 'NAME_LAST', VALUE => 'Her' ],
  DonK => [ CATEGORY => 'NAME_FIRST', VALUE => 'Don', CATEGORY => 'NAME_INITIALS', VALUE => 'K.' ],
  DonLorvig => [ CATEGORY => 'NAME_FIRST', VALUE => 'Don', CATEGORY => 'NAME_LAST', VALUE => 'Lorvig' ],
  DonQ => [ CATEGORY => 'NAME_FIRST', VALUE => 'Don', CATEGORY => 'NAME_INITIALS', VALUE => 'Q.' ],
  DongBowen => [ CATEGORY => 'NAME_FIRST', VALUE => 'Dong', CATEGORY => 'NAME_LAST', VALUE => 'Bowen' ],
  DongLinFeng => [ CATEGORY => 'NAME_FIRST', VALUE => 'Lin Feng', CATEGORY => 'NAME_LAST', VALUE => 'Dong' ],
  DonnaPerron => [ CATEGORY => 'NAME_FIRST', VALUE => 'Donna', CATEGORY => 'NAME_LAST', VALUE => 'Perron' ],
  DonnySL => [ CATEGORY => 'NAME_FIRST', VALUE => 'Donny', CATEGORY => 'NAME_INITIALS', VALUE => 'S. L.' ],
  DorisMcGinnis => [ CATEGORY => 'NAME_FIRST', VALUE => 'Doris', CATEGORY => 'NAME_LAST', VALUE => 'McGinnis' ],
  DubrannaMarieClaude => [ CATEGORY => 'NAME_FIRST', VALUE => 'Marie Claude', CATEGORY => 'NAME_LAST', VALUE => 'Dubranna' ],
  EGianCarlo => [ CATEGORY => 'NAME_FIRST', VALUE => 'Gian Carlo' ],
  EddiE => [ CATEGORY => 'NAME_FIRST', VALUE => 'Eddie' ],
  EddyHaskel => [ CATEGORY => 'NAME_FIRST', VALUE => 'Eddy', CATEGORY => 'NAME_LAST', VALUE => 'Haskel' ],
  EdithChang => [ CATEGORY => 'NAME_FIRST', VALUE => 'Edith', CATEGORY => 'NAME_LAST', VALUE => 'Chang' ],
  EdnaMae => [ CATEGORY => 'NAME_FIRST', VALUE => 'Edna Mae' ],
  EdwardFaicco => [ CATEGORY => 'NAME_FIRST', VALUE => 'Edward', CATEGORY => 'NAME_LAST', VALUE => 'Faicco' ],
  EfkanOrman => [ CATEGORY => 'NAME_FIRST', VALUE => 'Efkan', CATEGORY => 'NAME_LAST', VALUE => 'Orman' ],
  EgniNetoob => [ CATEGORY => 'NAME_FIRST', VALUE => 'Egni', CATEGORY => 'NAME_LAST', VALUE => 'Netoob' ],
  EijiNohara => [ CATEGORY => 'NAME_FIRST', VALUE => 'Eiji', CATEGORY => 'NAME_LAST', VALUE => 'Nohara' ],
  EleanorCannon => [ CATEGORY => 'NAME_FIRST', VALUE => 'Eleanor', CATEGORY => 'NAME_LAST', VALUE => 'Cannon' ],
  ElieJones => [ CATEGORY => 'NAME_FIRST', VALUE => 'Elie', CATEGORY => 'NAME_LAST', VALUE => 'Jones' ],
  ElkeS => [ CATEGORY => 'NAME_FIRST', VALUE => 'Elke', CATEGORY => 'NAME_INITIALS', VALUE => 'S.' ],
  ElkeSt => [ CATEGORY => 'NAME_FIRST', VALUE => 'Elke' ],
  ElkeWeber => [ CATEGORY => 'NAME_FIRST', VALUE => 'Elke', CATEGORY => 'NAME_LAST', VALUE => 'Weber' ],
  EllaGerner => [ CATEGORY => 'NAME_FIRST', VALUE => 'Ella', CATEGORY => 'NAME_LAST', VALUE => 'Gerner' ],
  EllySU => [ CATEGORY => 'NAME_FIRST', VALUE => 'Elly', CATEGORY => 'NAME_LAST', VALUE => 'SU' ],
  ElsMarie => [ CATEGORY => 'NAME_FIRST', VALUE => 'Els Marie' ],
  ElspethSc => [ CATEGORY => 'NAME_FIRST', VALUE => 'Elspeth', CATEGORY => 'NAME_INITIALS', VALUE => 'S.' ],
  EmileJ => [ CATEGORY => 'NAME_FIRST', VALUE => 'Emile', CATEGORY => 'NAME_INITIALS', VALUE => 'J.' ],
  EmilioRamirez => [ CATEGORY => 'NAME_FIRST', VALUE => 'Emilio', CATEGORY => 'NAME_LAST', VALUE => 'Ramirez' ],
  EmilyYoung => [ CATEGORY => 'NAME_FIRST', VALUE => 'Emily', CATEGORY => 'NAME_LAST', VALUE => 'Young' ],
  EmmA => [ CATEGORY => 'NAME_FIRST', VALUE => 'Emma' ],
  EmmyBem => [ CATEGORY => 'NAME_FIRST', VALUE => 'Emmy', CATEGORY => 'NAME_LAST', VALUE => 'Bem' ],
  ErdekEkinKitabevi => [ CATEGORY => 'NAME_FIRST', VALUE => 'Erdek Ekin', CATEGORY => 'NAME_LAST', VALUE => 'Kitabevi' ],
  ErikR => [ CATEGORY => 'NAME_FIRST', VALUE => 'Erik', CATEGORY => 'NAME_INITIALS', VALUE => 'R.' ],
  ErkanKarul => [ CATEGORY => 'NAME_FIRST', VALUE => 'Erkan', CATEGORY => 'NAME_LAST', VALUE => 'Karul' ],
  EspenL => [ CATEGORY => 'NAME_FIRST', VALUE => 'Espen', CATEGORY => 'NAME_INITIALS', VALUE => 'L.' ],
  EstherFabbricante => [ CATEGORY => 'NAME_FIRST', VALUE => 'Esther', CATEGORY => 'NAME_LAST', VALUE => 'Fabbricante' ],
  EverettHixson => [ CATEGORY => 'NAME_FIRST', VALUE => 'Everett', CATEGORY => 'NAME_LAST', VALUE => 'Hixson' ],
  EvgeniG => [ CATEGORY => 'NAME_FIRST', VALUE => 'Evgeni', CATEGORY => 'NAME_INITIALS', VALUE => 'G.' ],
  FTenBrook => [ CATEGORY => 'NAME_INITIALS', VALUE => 'F.', CATEGORY => 'NAME_PARTICLES', VALUE => 'ten', CATEGORY => 'NAME_LAST', VALUE => 'Brook' ],
  FanWY => [ CATEGORY => 'NAME_INITIALS', VALUE => 'W. Y.', CATEGORY => 'NAME_INITIALS', VALUE => 'Fan' ],
  FanZhen => [ CATEGORY => 'NAME_FIRST', VALUE => 'Zhen', CATEGORY => 'NAME_LAST', VALUE => 'Fan' ],
  FikithaSirap => [ CATEGORY => 'NAME_FIRST', VALUE => 'Fikitha', CATEGORY => 'NAME_LAST', VALUE => 'Sirap' ],
  FitzGerald => [ CATEGORY => 'NAME_LAST', VALUE => 'FitzGerald' ],
  FitzGibbon => [ CATEGORY => 'NAME_LAST', VALUE => 'FitzGibbon' ],
  FitzSimmons => [ CATEGORY => 'NAME_LAST', VALUE => 'FitzSimmons' ],
  FranMacCormack => [ CATEGORY => 'NAME_FIRST', VALUE => 'Fran', CATEGORY => 'NAME_LAST', VALUE => 'MacCormack' ],
  FranWeiner => [ CATEGORY => 'NAME_FIRST', VALUE => 'Fran', CATEGORY => 'NAME_LAST', VALUE => 'Weiner' ],
  FranciS => [ CATEGORY => 'NAME_FIRST', VALUE => 'Francis' ],
  FrankHawkins => [ CATEGORY => 'NAME_FIRST', VALUE => 'Frank', CATEGORY => 'NAME_LAST', VALUE => 'Hawkins' ],
  FransKox => [ CATEGORY => 'NAME_FIRST', VALUE => 'Frans', CATEGORY => 'NAME_LAST', VALUE => 'Kox' ],
  FredIlmoni => [ CATEGORY => 'NAME_FIRST', VALUE => 'Fred', CATEGORY => 'NAME_LAST', VALUE => 'Ilmoni' ],
  FredN => [ CATEGORY => 'NAME_FIRST', VALUE => 'Fred', CATEGORY => 'NAME_INITIALS', VALUE => 'N.' ],
  FridyTaconis => [ CATEGORY => 'NAME_FIRST', VALUE => 'Fridy', CATEGORY => 'NAME_LAST', VALUE => 'Taconis' ],
  FrinzRich => [ CATEGORY => 'NAME_FIRST', VALUE => 'Frinz', CATEGORY => 'NAME_LAST', VALUE => 'Rich' ],
  FuYanMing => [ CATEGORY => 'NAME_FIRST', VALUE => 'Yan Ming', CATEGORY => 'NAME_LAST', VALUE => 'Fu' ],
  GabriaL => [ CATEGORY => 'NAME_FIRST', VALUE => 'Gabria', CATEGORY => 'NAME_INITIALS', VALUE => 'L.' ],
  GailB => [ CATEGORY => 'NAME_FIRST', VALUE => 'Gail', CATEGORY => 'NAME_INITIALS', VALUE => 'B.' ],
  GailMiddleton => [ CATEGORY => 'NAME_FIRST', VALUE => 'Gail', CATEGORY => 'NAME_LAST', VALUE => 'Middleton' ],
  GaoGuangze => [ CATEGORY => 'NAME_FIRST', VALUE => 'Guangze', CATEGORY => 'NAME_LAST', VALUE => 'Gao' ],
  GaoGuijun => [ CATEGORY => 'NAME_FIRST', VALUE => 'Guijun', CATEGORY => 'NAME_LAST', VALUE => 'Gao' ],
  GaryCharness => [ CATEGORY => 'NAME_FIRST', VALUE => 'Gary', CATEGORY => 'NAME_LAST', VALUE => 'Charness' ],
  GaryK => [ CATEGORY => 'NAME_FIRST', VALUE => 'Gary', CATEGORY => 'NAME_INITIALS', VALUE => 'K.' ],
  GeirEnge => [ CATEGORY => 'NAME_FIRST', VALUE => 'Geir', CATEGORY => 'NAME_LAST', VALUE => 'Enge' ],
  GeoffL => [ CATEGORY => 'NAME_FIRST', VALUE => 'Geoff', CATEGORY => 'NAME_INITIALS', VALUE => 'L.' ],
  GeorgeG => [ CATEGORY => 'NAME_FIRST', VALUE => 'George', CATEGORY => 'NAME_INITIALS', VALUE => 'G.' ],
  GeorgeMcConkey => [ CATEGORY => 'NAME_FIRST', VALUE => 'George', CATEGORY => 'NAME_LAST', VALUE => 'McConkey' ],
  GianCarlo => [ CATEGORY => 'NAME_FIRST', VALUE => 'Gian Carlo' ],
  GianPaolo => [ CATEGORY => 'NAME_FIRST', VALUE => 'Gian Paolo' ],
  "GiovannaDell'Amico" => [ CATEGORY => 'NAME_FIRST', VALUE => 'Giovanna', CATEGORY => 'NAME_LAST', VALUE => "Dell'Amico" ],
  GiseleEmond => [ CATEGORY => 'NAME_FIRST', VALUE => 'Gisele', CATEGORY => 'NAME_LAST', VALUE => 'Emond' ],
  GoroStankov => [ CATEGORY => 'NAME_FIRST', VALUE => 'Goro', CATEGORY => 'NAME_LAST', VALUE => 'Stankov' ],
  GoudSmit => [ CATEGORY => 'NAME_FIRST', VALUE => 'Goud', CATEGORY => 'NAME_LAST', VALUE => 'Smit' ],
  GraziaP => [ CATEGORY => 'NAME_FIRST', VALUE => 'Grazia', CATEGORY => 'NAME_INITIALS', VALUE => 'P.' ],
  GrazielaT => [ CATEGORY => 'NAME_FIRST', VALUE => 'Graziela', CATEGORY => 'NAME_INITIALS', VALUE => 'T.' ],
  GregKayt => [ CATEGORY => 'NAME_FIRST', VALUE => 'Greg', CATEGORY => 'NAME_LAST', VALUE => 'Kayt' ],
  GregKyr => [ CATEGORY => 'NAME_FIRST', VALUE => 'Greg', CATEGORY => 'NAME_LAST', VALUE => 'Kyr' ],
  GunnarFjalar => [ CATEGORY => 'NAME_FIRST', VALUE => 'Gunnar', CATEGORY => 'NAME_LAST', VALUE => 'Fjalar' ],
  GuoZHong => [ CATEGORY => 'NAME_FIRST', VALUE => 'Guo', CATEGORY => 'NAME_INITIALS', VALUE => 'Z.', CATEGORY => 'NAME_LAST', VALUE => 'Hong' ],
  GuriAnn => [ CATEGORY => 'NAME_FIRST', VALUE => 'Guri Ann' ],
  HalukV => [ CATEGORY => 'NAME_FIRST', VALUE => 'Haluk', CATEGORY => 'NAME_INITIALS', VALUE => 'V.' ],
  HanneSchmidt => [ CATEGORY => 'NAME_FIRST', VALUE => 'Hanne', CATEGORY => 'NAME_LAST', VALUE => 'Schmidt' ],
  HanniBarckhausen => [ CATEGORY => 'NAME_FIRST', VALUE => 'Hanni', CATEGORY => 'NAME_LAST', VALUE => 'Barckhausen' ],
  HanniFrank => [ CATEGORY => 'NAME_FIRST', VALUE => 'Hanni', CATEGORY => 'NAME_LAST', VALUE => 'Frank' ],
  HansFriedrich => [ CATEGORY => 'NAME_FIRST', VALUE => 'Hans', CATEGORY => 'NAME_LAST', VALUE => 'Friedrich' ],
  HansR => [ CATEGORY => 'NAME_FIRST', VALUE => 'Hans', CATEGORY => 'NAME_INITIALS', VALUE => 'R.' ],
  HansW => [ CATEGORY => 'NAME_FIRST', VALUE => 'Hans', CATEGORY => 'NAME_INITIALS', VALUE => 'W.' ],
  HaroldJacobus => [ CATEGORY => 'NAME_FIRST', VALUE => 'Harold', CATEGORY => 'NAME_LAST', VALUE => 'Jacobus' ],
  HarryL => [ CATEGORY => 'NAME_FIRST', VALUE => 'Harry', CATEGORY => 'NAME_INITIALS', VALUE => 'L.' ],
  HarrySklar => [ CATEGORY => 'NAME_FIRST', VALUE => 'Harry', CATEGORY => 'NAME_LAST', VALUE => 'Sklar' ],
  HarryYang => [ CATEGORY => 'NAME_FIRST', VALUE => 'Harry', CATEGORY => 'NAME_LAST', VALUE => 'Yang' ],
  HasanUsta => [ CATEGORY => 'NAME_FIRST', VALUE => 'Hasan', CATEGORY => 'NAME_LAST', VALUE => 'Usta' ],
  HattoriHanzo => [ CATEGORY => 'NAME_FIRST', VALUE => 'Hattori', CATEGORY => 'NAME_LAST', VALUE => 'Hanzo' ],
  HedyZ => [ CATEGORY => 'NAME_FIRST', VALUE => 'Hedy', CATEGORY => 'NAME_INITIALS', VALUE => 'Z.' ],
  HeidiLapointe => [ CATEGORY => 'NAME_FIRST', VALUE => 'Heidi', CATEGORY => 'NAME_LAST', VALUE => 'Lapointe' ],
  HelenDSmith => [ CATEGORY => 'NAME_FIRST', VALUE => 'Helen', CATEGORY => 'NAME_INITIALS', VALUE => 'D.', CATEGORY => 'NAME_LAST', VALUE => 'Smith' ],
  HelenLewis => [ CATEGORY => 'NAME_FIRST', VALUE => 'Helen', CATEGORY => 'NAME_LAST', VALUE => 'Lewis' ],
  HelenToth => [ CATEGORY => 'NAME_FIRST', VALUE => 'Helen', CATEGORY => 'NAME_LAST', VALUE => 'Toth' ],
  HelgeWold => [ CATEGORY => 'NAME_FIRST', VALUE => 'Helge', CATEGORY => 'NAME_LAST', VALUE => 'Wold' ],
  HenkReumkens => [ CATEGORY => 'NAME_FIRST', VALUE => 'Henk', CATEGORY => 'NAME_LAST', VALUE => 'Reumkens' ],
  HenkS => [ CATEGORY => 'NAME_FIRST', VALUE => 'Henk', CATEGORY => 'NAME_INITIALS', VALUE => 'S.' ],
  HenriFranc => [ CATEGORY => 'NAME_FIRST', VALUE => 'Henri', CATEGORY => 'NAME_LAST', VALUE => 'Franc' ],
  HerMawan => [ CATEGORY => 'NAME_FIRST', VALUE => 'Her', CATEGORY => 'NAME_LAST', VALUE => 'Mawan' ],
  HicriTUNC => [ CATEGORY => 'NAME_FIRST', VALUE => 'Hicri', CATEGORY => 'NAME_LAST', VALUE => 'Tunc' ],
  HilmarKristensen => [ CATEGORY => 'NAME_FIRST', VALUE => 'Hilmar', CATEGORY => 'NAME_LAST', VALUE => 'Kristensen' ],
  HiroseSumire => [ CATEGORY => 'NAME_FIRST', VALUE => 'Hirose', CATEGORY => 'NAME_LAST', VALUE => 'Sumire' ],
  HongYunLei => [ CATEGORY => 'NAME_FIRST', VALUE => 'Yun Lei', CATEGORY => 'NAME_LAST', VALUE => 'Hong' ],
  HortLill => [ CATEGORY => 'NAME_FIRST', VALUE => 'Hort', CATEGORY => 'NAME_LAST', VALUE => 'Lill' ],
  HuaAn => [ CATEGORY => 'NAME_FIRST', VALUE => 'An', CATEGORY => 'NAME_LAST', VALUE => 'Hua' ],
  HuangLin => [ CATEGORY => 'NAME_FIRST', VALUE => 'Lin', CATEGORY => 'NAME_LAST', VALUE => 'Huang' ],
  HuangTu => [ CATEGORY => 'NAME_FIRST', VALUE => 'Tu', CATEGORY => 'NAME_LAST', VALUE => 'Huang' ],
  HuangWenJian => [ CATEGORY => 'NAME_FIRST', VALUE => 'Wen Jian', CATEGORY => 'NAME_LAST', VALUE => 'Huang' ],
  HvanEijk => [ CATEGORY => 'NAME_INITIALS', VALUE => 'H.', CATEGORY => 'NAME_PARTICLES', VALUE => 'van', CATEGORY => 'NAME_LAST', VALUE => 'Eijk' ],
  IJayJay => [ CATEGORY => 'NAME_INITIALS', VALUE => 'J. J.' ],
  IanJW => [ CATEGORY => 'NAME_FIRST', VALUE => 'Ian', CATEGORY => 'NAME_INITIALS', VALUE => 'J. W.' ],
  IdaLaReau => [ CATEGORY => 'NAME_FIRST', VALUE => 'Ida', CATEGORY => 'NAME_LAST', VALUE => 'LaReau' ],
  IlmoniFred => [ CATEGORY => 'NAME_FIRST', VALUE => 'Fred', CATEGORY => 'NAME_LAST', VALUE => 'Ilmoni' ],
  IlseG => [ CATEGORY => 'NAME_FIRST', VALUE => 'Ilse', CATEGORY => 'NAME_INITIALS', VALUE => 'G.' ],
  IrekSaturski => [ CATEGORY => 'NAME_FIRST', VALUE => 'Irek', CATEGORY => 'NAME_LAST', VALUE => 'Saturski' ],
  IreneThoerig => [ CATEGORY => 'NAME_FIRST', VALUE => 'Irene', CATEGORY => 'NAME_LAST', VALUE => 'Thoerig' ],
  IreneW => [ CATEGORY => 'NAME_FIRST', VALUE => 'Irene', CATEGORY => 'NAME_INITIALS', VALUE => 'W.' ],
  IrmaKoot => [ CATEGORY => 'NAME_FIRST', VALUE => 'Irma', CATEGORY => 'NAME_LAST', VALUE => 'Koot' ],
  IsaSmith => [ CATEGORY => 'NAME_FIRST', VALUE => 'Isa', CATEGORY => 'NAME_LAST', VALUE => 'Smith' ],
  JBabsG => [ CATEGORY => 'NAME_FIRST', VALUE => 'J. Babs', CATEGORY => 'NAME_INITIALS', VALUE => 'G.' ],
  JGabrialAde => [ CATEGORY => 'NAME_INITIALS', VALUE => 'J.', CATEGORY => 'NAME_FIRST', VALUE => 'Gabrial', CATEGORY => 'NAME_LAST', VALUE => 'Ade' ],
  JIangSu => [ CATEGORY => 'NAME_FIRST', VALUE => 'Su', CATEGORY => 'NAME_LAST', VALUE => 'Jiang' ],
  JUNzhANG => [ CATEGORY => 'NAME_FIRST', VALUE => 'Jun', CATEGORY => 'NAME_LAST', VALUE => 'Zhang' ],
  JaapLagcher => [ CATEGORY => 'NAME_FIRST', VALUE => 'Jaap', CATEGORY => 'NAME_LAST', VALUE => 'Lagcher' ],
  JacTimmermans => [ CATEGORY => 'NAME_FIRST', VALUE => 'Jac', CATEGORY => 'NAME_LAST', VALUE => 'Timmermans' ],
  JackColson => [ CATEGORY => 'NAME_FIRST', VALUE => 'Jack', CATEGORY => 'NAME_LAST', VALUE => 'Colson' ],
  JackomWalz => [ CATEGORY => 'NAME_FIRST', VALUE => 'Jackom', CATEGORY => 'NAME_LAST', VALUE => 'Walz' ],
  JacquesBrandt => [ CATEGORY => 'NAME_FIRST', VALUE => 'Jacques', CATEGORY => 'NAME_LAST', VALUE => 'Brandt' ],
  JamesBowman => [ CATEGORY => 'NAME_FIRST', VALUE => 'James', CATEGORY => 'NAME_LAST', VALUE => 'Bowman' ],
  JanEric => [ CATEGORY => 'NAME_FIRST', VALUE => 'Jan Eric' ],
  JanJenkins => [ CATEGORY => 'NAME_FIRST', VALUE => 'Jan', CATEGORY => 'NAME_LAST', VALUE => 'Jenkins' ],
  JanS => [ CATEGORY => 'NAME_FIRST', VALUE => 'Jan', CATEGORY => 'NAME_INITIALS', VALUE => 'S.' ],
  JanT => [ CATEGORY => 'NAME_FIRST', VALUE => 'Jan', CATEGORY => 'NAME_INITIALS', VALUE => 'T.' ],
  JanTijsen => [ CATEGORY => 'NAME_FIRST', VALUE => 'Jan', CATEGORY => 'NAME_LAST', VALUE => 'Tijsen' ],
  JandeF => [ CATEGORY => 'NAME_FIRST', VALUE => 'Jan', CATEGORY => 'NAME_PARTICLES', VALUE => 'de', CATEGORY => 'NAME_INITIALS', VALUE => 'F.' ],
  JaneA => [ CATEGORY => 'NAME_FIRST', VALUE => 'Jane', CATEGORY => 'NAME_INITIALS', VALUE => 'A.' ],
  JaneAnn => [ CATEGORY => 'NAME_FIRST', VALUE => 'Jane Ann' ],
  JaneS => [ CATEGORY => 'NAME_FIRST', VALUE => 'Jane', CATEGORY => 'NAME_INITIALS', VALUE => 'S.' ],
  JanetRose => [ CATEGORY => 'NAME_FIRST', VALUE => 'Janet Rose' ],
  JaniceTalada => [ CATEGORY => 'NAME_FIRST', VALUE => 'Janice', CATEGORY => 'NAME_LAST', VALUE => 'Talada' ],
  JanuszC => [ CATEGORY => 'NAME_FIRST', VALUE => 'Janusz', CATEGORY => 'NAME_INITIALS', VALUE => 'C.' ],
  JanuszR => [ CATEGORY => 'NAME_FIRST', VALUE => 'Janusz', CATEGORY => 'NAME_INITIALS', VALUE => 'R.' ],
  JaoZhang => [ CATEGORY => 'NAME_FIRST', VALUE => 'Jao', CATEGORY => 'NAME_LAST', VALUE => 'Zhang' ],
  JarleP => [ CATEGORY => 'NAME_FIRST', VALUE => 'Jarle', CATEGORY => 'NAME_INITIALS', VALUE => 'P.' ],
  JasLai => [ CATEGORY => 'NAME_FIRST', VALUE => 'Jas', CATEGORY => 'NAME_LAST', VALUE => 'Lai' ],
  JasonYip => [ CATEGORY => 'NAME_FIRST', VALUE => 'Jason', CATEGORY => 'NAME_LAST', VALUE => 'Yip' ],
  JayKrich => [ CATEGORY => 'NAME_FIRST', VALUE => 'Jay', CATEGORY => 'NAME_LAST', VALUE => 'Krich' ],
  JeanB => [ CATEGORY => 'NAME_FIRST', VALUE => 'Jean', CATEGORY => 'NAME_INITIALS', VALUE => 'B.' ],
  JeanClaude => [ CATEGORY => 'NAME_FIRST', VALUE => 'Jean Claude' ],
  JeanPaul => [ CATEGORY => 'NAME_FIRST', VALUE => 'Jean Paul' ],
  JenHatcher => [ CATEGORY => 'NAME_FIRST', VALUE => 'Jen', CATEGORY => 'NAME_LAST', VALUE => 'Hatcher' ],
  JeriR => [ CATEGORY => 'NAME_FIRST', VALUE => 'Jeri', CATEGORY => 'NAME_INITIALS', VALUE => 'R.' ],
  JerryLin => [ CATEGORY => 'NAME_FIRST', VALUE => 'Jerry', CATEGORY => 'NAME_LAST', VALUE => 'Lin' ],
  JerryPeterson => [ CATEGORY => 'NAME_FIRST', VALUE => 'Jerry', CATEGORY => 'NAME_LAST', VALUE => 'Peterson' ],
  JerryS => [ CATEGORY => 'NAME_FIRST', VALUE => 'Jerry', CATEGORY => 'NAME_INITIALS', VALUE => 'S.' ],
  JerzyJerzyJerzy => [ CATEGORY => 'NAME_FIRST', VALUE => 'Jerzy' ],
  "JerzyMarsza³kowski" => [ CATEGORY => 'NAME_FIRST', VALUE => 'Jerzy', CATEGORY => 'NAME_LAST', VALUE => 'Marszałkowski' ],
  JianLing => [ CATEGORY => 'NAME_FIRST', VALUE => 'Jian', CATEGORY => 'NAME_LAST', VALUE => 'Ling' ],
  JiangMingli => [ CATEGORY => 'NAME_FIRST', VALUE => 'Mingli', CATEGORY => 'NAME_LAST', VALUE => 'Jiang' ],
  JiangSY => [ CATEGORY => 'NAME_INITIALS', VALUE => 'S. Y.', CATEGORY => 'NAME_LAST', VALUE => 'Jiang' ],
  JiangYuchen => [ CATEGORY => 'NAME_FIRST', VALUE => 'Yuchen', CATEGORY => 'NAME_LAST', VALUE => 'Jiang' ],
  JiangYuxin => [ CATEGORY => 'NAME_FIRST', VALUE => 'Yuxin', CATEGORY => 'NAME_LAST', VALUE => 'Jiang' ],
  JimBartko => [ CATEGORY => 'NAME_FIRST', VALUE => 'Jim', CATEGORY => 'NAME_LAST', VALUE => 'Bartko' ],
  JimBull => [ CATEGORY => 'NAME_FIRST', VALUE => 'Jim', CATEGORY => 'NAME_LAST', VALUE => 'Bull' ],
  JimGe => [ CATEGORY => 'NAME_FIRST', VALUE => 'Jim', CATEGORY => 'NAME_LAST', VALUE => 'Ge' ],
  JimGero => [ CATEGORY => 'NAME_FIRST', VALUE => 'Jim', CATEGORY => 'NAME_LAST', VALUE => 'Gero' ],
  JimMcKinney => [ CATEGORY => 'NAME_FIRST', VALUE => 'Jim', CATEGORY => 'NAME_LAST', VALUE => 'McKinney' ],
  JimSC => [ CATEGORY => 'NAME_FIRST', VALUE => 'Jim', CATEGORY => 'NAME_INITIALS', VALUE => 'S. C.' ],
  JimmyLedger => [ CATEGORY => 'NAME_FIRST', VALUE => 'Jimmy', CATEGORY => 'NAME_LAST', VALUE => 'Ledger' ],
  JinayDhian => [ CATEGORY => 'NAME_FIRST', VALUE => 'Dhian', CATEGORY => 'NAME_LAST', VALUE => 'Jinay' ],
  JingWen => [ CATEGORY => 'NAME_FIRST', VALUE => 'Wen', CATEGORY => 'NAME_LAST', VALUE => 'Jing' ],
  JiunWen => [ CATEGORY => 'NAME_FIRST', VALUE => 'Wen', CATEGORY => 'NAME_LAST', VALUE => 'Jiun' ],
  JoanLeroux => [ CATEGORY => 'NAME_FIRST', VALUE => 'Joan', CATEGORY => 'NAME_LAST', VALUE => 'Leroux' ],
  JoannaTytko => [ CATEGORY => 'NAME_FIRST', VALUE => 'Joanna', CATEGORY => 'NAME_LAST', VALUE => 'Tytko' ],
  JoeAlex => [ CATEGORY => 'NAME_FIRST', VALUE => 'Joe Alex' ],
  JoeLiAnta => [ CATEGORY => 'NAME_FIRST', VALUE => 'Joe', CATEGORY => 'NAME_LAST', VALUE => 'LiAnta' ],
  JoeYork => [ CATEGORY => 'NAME_FIRST', VALUE => 'Joe', CATEGORY => 'NAME_LAST', VALUE => 'York' ],
  JoenDSlaven => [ CATEGORY => 'NAME_FIRST', VALUE => 'Joen', CATEGORY => 'NAME_INITIALS', VALUE => 'D.', CATEGORY => 'NAME_LAST', VALUE => 'Slaven' ],
  JohanneG => [ CATEGORY => 'NAME_FIRST', VALUE => 'Johanne', CATEGORY => 'NAME_INITIALS', VALUE => 'G.' ],
  JohnAsim => [ CATEGORY => 'NAME_FIRST', VALUE => 'John', CATEGORY => 'NAME_LAST', VALUE => 'Asim' ],
  JohnB => [ CATEGORY => 'NAME_FIRST', VALUE => 'John', CATEGORY => 'NAME_INITIALS', VALUE => 'B.' ],
  JohnBrown => [ CATEGORY => 'NAME_FIRST', VALUE => 'John', CATEGORY => 'NAME_LAST', VALUE => 'Brown' ],
  JohnDeYoe => [ CATEGORY => 'NAME_FIRST', VALUE => 'John', CATEGORY => 'NAME_PARTICLES', VALUE => 'de', CATEGORY => 'NAME_LAST', VALUE => 'Yoe' ],
  JohnJim => [ CATEGORY => 'NAME_FIRST', VALUE => 'John Jim' ],
  JonesHinton => [ CATEGORY => 'NAME_FIRST', VALUE => 'Jones', CATEGORY => 'NAME_LAST', VALUE => 'Hinton' ],
  JosV => [ CATEGORY => 'NAME_FIRST', VALUE => 'Jos', CATEGORY => 'NAME_INITIALS', VALUE => 'V.' ],
  JoseArcadio => [ CATEGORY => 'NAME_FIRST', VALUE => 'Jose', CATEGORY => 'NAME_LAST', VALUE => 'Arcadio' ],
  JoseMelo => [ CATEGORY => 'NAME_FIRST', VALUE => 'Jose', CATEGORY => 'NAME_LAST', VALUE => 'Melo' ],
  JosefP => [ CATEGORY => 'NAME_FIRST', VALUE => 'Josef', CATEGORY => 'NAME_INITIALS', VALUE => 'P.' ],
  JosephT => [ CATEGORY => 'NAME_FIRST', VALUE => 'Joseph', CATEGORY => 'NAME_INITIALS', VALUE => 'T.' ],
  JoviSmed => [ CATEGORY => 'NAME_FIRST', VALUE => 'Jovi', CATEGORY => 'NAME_LAST', VALUE => 'Smederevac' ],
  JuanEmilio => [ CATEGORY => 'NAME_FIRST', VALUE => 'Juan Emilio' ],
  JuanaM => [ CATEGORY => 'NAME_FIRST', VALUE => 'Juana', CATEGORY => 'NAME_INITIALS', VALUE => 'M.' ],
  JudiAnne => [ CATEGORY => 'NAME_FIRST', VALUE => 'Judi Anne' ],
  JudyGeralds => [ CATEGORY => 'NAME_FIRST', VALUE => 'Judy', CATEGORY => 'NAME_LAST', VALUE => 'Geralds' ],
  JudyJohnson => [ CATEGORY => 'NAME_FIRST', VALUE => 'Judy', CATEGORY => 'NAME_LAST', VALUE => 'Johnson' ],
  JudyL => [ CATEGORY => 'NAME_FIRST', VALUE => 'Judy', CATEGORY => 'NAME_INITIALS', VALUE => 'L.' ],
  JudyLion => [ CATEGORY => 'NAME_FIRST', VALUE => 'Judy', CATEGORY => 'NAME_LAST', VALUE => 'Lion' ],
  JuhaniH => [ CATEGORY => 'NAME_FIRST', VALUE => 'Juhani', CATEGORY => 'NAME_INITIALS', VALUE => 'H.' ],
  JulieAnn => [ CATEGORY => 'NAME_FIRST', VALUE => 'Julie Ann' ],
  JulieJean => [ CATEGORY => 'NAME_FIRST', VALUE => 'Julie Jean' ],
  JulietYi => [ CATEGORY => 'NAME_FIRST', VALUE => 'Juliet', CATEGORY => 'NAME_LAST', VALUE => 'Yi' ],
  JulietteVenard => [ CATEGORY => 'NAME_FIRST', VALUE => 'Juliette', CATEGORY => 'NAME_LAST', VALUE => 'Venard' ],
  JunGu => [ CATEGORY => 'NAME_FIRST', VALUE => 'Jun', CATEGORY => 'NAME_LAST', VALUE => 'Gu' ],
  JunJie => [ CATEGORY => 'NAME_FIRST', VALUE => 'Jun', CATEGORY => 'NAME_LAST', VALUE => 'Jie' ],
  JuneEvans => [ CATEGORY => 'NAME_FIRST', VALUE => 'June', CATEGORY => 'NAME_LAST', VALUE => 'Evans' ],
  JørgenNielsen => [ CATEGORY => 'NAME_FIRST', VALUE => 'Jørgen', CATEGORY => 'NAME_FIRST', VALUE => 'Nielsen' ],
  KaaN => [ CATEGORY => 'NAME_FIRST', VALUE => 'Kaan' ],
  KarelNab => [ CATEGORY => 'NAME_FIRST', VALUE => 'Karel', CATEGORY => 'NAME_LAST', VALUE => 'Nab' ],
  KarenPerling => [ CATEGORY => 'NAME_FIRST', VALUE => 'Karen', CATEGORY => 'NAME_LAST', VALUE => 'Perling' ],
  KarimG => [ CATEGORY => 'NAME_FIRST', VALUE => 'Karim', CATEGORY => 'NAME_INITIALS', VALUE => 'G.' ],
  KarlJohan => [ CATEGORY => 'NAME_FIRST', VALUE => 'Karl Johan' ],
  KathRowan => [ CATEGORY => 'NAME_FIRST', VALUE => 'Kath', CATEGORY => 'NAME_LAST', VALUE => 'Rowan' ],
  KatherineK => [ CATEGORY => 'NAME_FIRST', VALUE => 'Katherine', CATEGORY => 'NAME_INITIALS', VALUE => 'K.' ],
  KathleenFergus => [ CATEGORY => 'NAME_FIRST', VALUE => 'Kathleen', CATEGORY => 'NAME_LAST', VALUE => 'Fergus' ],
  KathyLockhart => [ CATEGORY => 'NAME_FIRST', VALUE => 'Kathy', CATEGORY => 'NAME_LAST', VALUE => 'Lockhart' ],
  KatyUzu => [ CATEGORY => 'NAME_FIRST', VALUE => 'Katy', CATEGORY => 'NAME_LAST', VALUE => 'Uzu' ],
  KautsarHilmi => [ CATEGORY => 'NAME_FIRST', VALUE => 'Kautsar Hilmi' ],
  KeesvanDijk => [ CATEGORY => 'NAME_FIRST', VALUE => 'Kees', CATEGORY => 'NAME_PARTICLES', VALUE => 'van', CATEGORY => 'NAME_LAST', VALUE => 'Dijk' ],
  KenL => [ CATEGORY => 'NAME_FIRST', VALUE => 'Ken', CATEGORY => 'NAME_INITIALS', VALUE => 'L.' ],
  KevinChen => [ CATEGORY => 'NAME_FIRST', VALUE => 'Kevin', CATEGORY => 'NAME_LAST', VALUE => 'Chen' ],
  KjellH => [ CATEGORY => 'NAME_FIRST', VALUE => 'Kjell', CATEGORY => 'NAME_INITIALS', VALUE => 'H.' ],
  KjellTore => [ CATEGORY => 'NAME_FIRST', VALUE => 'Kjell Tore' ],
  KkrzyS => [ CATEGORY => 'NAME_FIRST', VALUE => 'Krzysztof', CATEGORY => 'NAME_INITIALS', VALUE => 'S.' ],
  KlaraS => [ CATEGORY => 'NAME_FIRST', VALUE => 'Klara', CATEGORY => 'NAME_INITIALS', VALUE => 'S.' ],
  KorkMAYIS => [ CATEGORY => 'NAME_FIRST', VALUE => 'Kork', CATEGORY => 'NAME_LAST', VALUE => 'Mayis' ],
  KuangZP => [ CATEGORY => 'NAME_INITIALS', VALUE => 'Z. P.', CATEGORY => 'NAME_LAST', VALUE => 'Kuang' ],
  KuhChung => [ CATEGORY => 'NAME_FIRST', VALUE => 'Kuh', CATEGORY => 'NAME_LAST', VALUE => 'Chung' ],
  KurtCh => [ CATEGORY => 'NAME_FIRST', VALUE => 'Kurt', CATEGORY => 'NAME_INITIALS', VALUE => 'C.' ],
  KylieAnn => [ CATEGORY => 'NAME_FIRST', VALUE => 'Kylie Ann' ],
  LPauloAF => [ CATEGORY => 'NAME_FIRST', VALUE => 'Paulo', CATEGORY => 'NAME_INITIALS', VALUE => 'A. F.' ],
  LahirBatin => [ CATEGORY => 'NAME_FIRST', VALUE => 'Lahir Batin' ],
  LangHua => [ CATEGORY => 'NAME_FIRST', VALUE => 'Hua', CATEGORY => 'NAME_LAST', VALUE => 'Lang' ],
  LaoQi => [ CATEGORY => 'NAME_FIRST', VALUE => 'Qi', CATEGORY => 'NAME_LAST', VALUE => 'Lao' ],
  LarraineBallstadt => [ CATEGORY => 'NAME_FIRST', VALUE => 'Larraine', CATEGORY => 'NAME_LAST', VALUE => 'Ballstadt' ],
  LarryKing => [ CATEGORY => 'NAME_FIRST', VALUE => 'Larry', CATEGORY => 'NAME_LAST', VALUE => 'King' ],
  LarsGrevang => [ CATEGORY => 'NAME_FIRST', VALUE => 'Lars', CATEGORY => 'NAME_LAST', VALUE => 'Grevang' ],
  LauraHerring => [ CATEGORY => 'NAME_FIRST', VALUE => 'Laura', CATEGORY => 'NAME_LAST', VALUE => 'Herring' ],
  LauraLee => [ CATEGORY => 'NAME_FIRST', VALUE => 'Laura Lee' ],
  LaureB => [ CATEGORY => 'NAME_FIRST', VALUE => 'Laure', CATEGORY => 'NAME_INITIALS', VALUE => 'B.' ],
  LaviMaria => [ CATEGORY => 'NAME_FIRST', VALUE => 'Maria', CATEGORY => 'NAME_LAST', VALUE => 'Lavi' ],
  LeAnnMyers => [ CATEGORY => 'NAME_FIRST', VALUE => 'Le Ann', CATEGORY => 'NAME_LAST', VALUE => 'Myers' ],
  LeeAnn => [ CATEGORY => 'NAME_FIRST', VALUE => 'Lee Ann' ],
  LeeManYiu => [ CATEGORY => 'NAME_FIRST', VALUE => 'Man Yiu', CATEGORY => 'NAME_LAST', VALUE => 'Lee' ],
  LeeYiMing => [ CATEGORY => 'NAME_FIRST', VALUE => 'Yi Ming', CATEGORY => 'NAME_LAST', VALUE => 'Lee' ],
  LeeZoya => [ CATEGORY => 'NAME_FIRST', VALUE => 'Lee', CATEGORY => 'NAME_LAST', VALUE => 'Zoya' ],
  LenaReijinga => [ CATEGORY => 'NAME_FIRST', VALUE => 'Lena', CATEGORY => 'NAME_LAST', VALUE => 'Reijinga' ],
  LenoreBank => [ CATEGORY => 'NAME_FIRST', VALUE => 'Lenore', CATEGORY => 'NAME_LAST', VALUE => 'Bank' ],
  LeoN => [ CATEGORY => 'NAME_FIRST', VALUE => 'Leon' ],
  LesleeT => [ CATEGORY => 'NAME_FIRST', VALUE => 'Leslee', CATEGORY => 'NAME_INITIALS', VALUE => 'T.' ],
  LesleyMelton => [ CATEGORY => 'NAME_FIRST', VALUE => 'Lesley', CATEGORY => 'NAME_LAST', VALUE => 'Melton' ],
  LiZhengWen => [ CATEGORY => 'NAME_FIRST', VALUE => 'Wen', CATEGORY => 'NAME_LAST', VALUE => 'Li Zheng' ],
  LinaG => [ CATEGORY => 'NAME_FIRST', VALUE => 'Lina', CATEGORY => 'NAME_INITIALS', VALUE => 'G.' ],
  LindaBerg => [ CATEGORY => 'NAME_FIRST', VALUE => 'Linda', CATEGORY => 'NAME_LAST', VALUE => 'Berg' ],
  LindaForeman => [ CATEGORY => 'NAME_FIRST', VALUE => 'Linda', CATEGORY => 'NAME_LAST', VALUE => 'Foreman' ],
  LinnAurora => [ CATEGORY => 'NAME_FIRST', VALUE => 'Linn Aurora' ],
  LiseCaron => [ CATEGORY => 'NAME_FIRST', VALUE => 'Lise', CATEGORY => 'NAME_LAST', VALUE => 'Caron' ],
  LiseMontmarquette => [ CATEGORY => 'NAME_FIRST', VALUE => 'Lise', CATEGORY => 'NAME_LAST', VALUE => 'Montmarquette' ],
  LizAnn => [ CATEGORY => 'NAME_FIRST', VALUE => 'Liz Ann' ],
  LoisPresser => [ CATEGORY => 'NAME_FIRST', VALUE => 'Lois', CATEGORY => 'NAME_LAST', VALUE => 'Presser' ],
  LoisWitt => [ CATEGORY => 'NAME_FIRST', VALUE => 'Lois', CATEGORY => 'NAME_LAST', VALUE => 'Witt' ],
  LoiuiseGentry => [ CATEGORY => 'NAME_FIRST', VALUE => 'Loiuise', CATEGORY => 'NAME_LAST', VALUE => 'Gentry' ],
  LouAnn => [ CATEGORY => 'NAME_FIRST', VALUE => 'Lou Ann' ],
  LouJones => [ CATEGORY => 'NAME_FIRST', VALUE => 'Lou', CATEGORY => 'NAME_LAST', VALUE => 'Jones' ],
  LouieB => [ CATEGORY => 'NAME_FIRST', VALUE => 'Louie', CATEGORY => 'NAME_INITIALS', VALUE => 'B.' ],
  LouisBesters => [ CATEGORY => 'NAME_FIRST', VALUE => 'Louis', CATEGORY => 'NAME_LAST', VALUE => 'Besters' ],
  LouiseMarie => [ CATEGORY => 'NAME_FIRST', VALUE => 'Louise Marie' ],
  LoureiroCosta => [ CATEGORY => 'NAME_FIRST', VALUE => 'Loureiro', CATEGORY => 'NAME_LAST', VALUE => 'Costa' ],
  LuXueFeng => [ CATEGORY => 'NAME_FIRST', VALUE => 'Xue Feng', CATEGORY => 'NAME_LAST', VALUE => 'Lu' ],
  LucJ => [ CATEGORY => 'NAME_FIRST', VALUE => 'Luc', CATEGORY => 'NAME_INITIALS', VALUE => 'J.' ],
  LucianoC => [ CATEGORY => 'NAME_FIRST', VALUE => 'Luciano', CATEGORY => 'NAME_INITIALS', VALUE => 'C.' ],
  LucilleFortin => [ CATEGORY => 'NAME_FIRST', VALUE => 'Lucille', CATEGORY => 'NAME_LAST', VALUE => 'Fortin' ],
  LynetteMurray => [ CATEGORY => 'NAME_FIRST', VALUE => 'Lynette', CATEGORY => 'NAME_LAST', VALUE => 'Murray' ],
  LynnBurchett => [ CATEGORY => 'NAME_FIRST', VALUE => 'Lynn', CATEGORY => 'NAME_LAST', VALUE => 'Burchett' ],
  LyubomirN => [ CATEGORY => 'NAME_FIRST', VALUE => 'Lyubomir', CATEGORY => 'NAME_INITIALS', VALUE => 'N.' ],
  MBjoernL => [ CATEGORY => 'NAME_FIRST', VALUE => 'Bjoern', CATEGORY => 'NAME_INITIALS', VALUE => 'L.' ],
  MLanA => [ CATEGORY => 'NAME_FIRST', VALUE => 'Lana' ],
  MPauloC => [ CATEGORY => 'NAME_FIRST', VALUE => 'Paulo', CATEGORY => 'NAME_INITIALS', VALUE => 'C.' ],
  MabelAnnaAnderson => [ CATEGORY => 'NAME_FIRST', VALUE => 'Mabel Anna', CATEGORY => 'NAME_LAST', VALUE => 'Anderson' ],
  MacAlister => [ CATEGORY => 'NAME_LAST', VALUE => 'MacAlister' ],
  MacCabe => [ CATEGORY => 'NAME_LAST', VALUE => 'MacCabe' ],
  MacCallum => [ CATEGORY => 'NAME_LAST', VALUE => 'MacCallum' ],
  MacCormick => [ CATEGORY => 'NAME_LAST', VALUE => 'MacCormick' ],
  MacDonagh => [ CATEGORY => 'NAME_LAST', VALUE => 'MacDonagh' ],
  MacDonald => [ CATEGORY => 'NAME_LAST', VALUE => 'MacDonald' ],
  MacDougall => [ CATEGORY => 'NAME_LAST', VALUE => 'MacDougall' ],
  MacDowell => [ CATEGORY => 'NAME_LAST', VALUE => 'MacDowell' ],
  MacEacbern => [ CATEGORY => 'NAME_LAST', VALUE => 'MacEacbern' ],
  MacEachern => [ CATEGORY => 'NAME_LAST', VALUE => 'MacEachern' ],
  MacFadden => [ CATEGORY => 'NAME_LAST', VALUE => 'MacFadden' ],
  MacGregor => [ CATEGORY => 'NAME_LAST', VALUE => 'MacGregor' ],
  MacInnis => [ CATEGORY => 'NAME_LAST', VALUE => 'MacInnis' ],
  MacIntyre => [ CATEGORY => 'NAME_LAST', VALUE => 'MacIntyre' ],
  MacKay => [ CATEGORY => 'NAME_LAST', VALUE => 'MacKay' ],
  MacKenrod => [ CATEGORY => 'NAME_LAST', VALUE => 'MacKenrod' ],
  MacKenzie => [ CATEGORY => 'NAME_LAST', VALUE => 'MacKenzie' ],
  MacKinnon => [ CATEGORY => 'NAME_LAST', VALUE => 'MacKinnon' ],
  MacLaren => [ CATEGORY => 'NAME_LAST', VALUE => 'MacLaren' ],
  MacLean => [ CATEGORY => 'NAME_LAST', VALUE => 'MacLean' ],
  MacLeod => [ CATEGORY => 'NAME_LAST', VALUE => 'MacLeod' ],
  MacMillan => [ CATEGORY => 'NAME_LAST', VALUE => 'MacMillan' ],
  MacNeal => [ CATEGORY => 'NAME_LAST', VALUE => 'MacNeal' ],
  MacNeil => [ CATEGORY => 'NAME_LAST', VALUE => 'MacNeil' ],
  MacNutt => [ CATEGORY => 'NAME_LAST', VALUE => 'MacNutt' ],
  MacPhail => [ CATEGORY => 'NAME_LAST', VALUE => 'MacPhail' ],
  MacRae => [ CATEGORY => 'NAME_LAST', VALUE => 'MacRae' ],
  MacRitchie => [ CATEGORY => 'NAME_LAST', VALUE => 'MacRitchie' ],
  MacShane => [ CATEGORY => 'NAME_LAST', VALUE => 'MacShane' ],
  MaciejTarczyn => [ CATEGORY => 'NAME_FIRST', VALUE => 'Maciej', CATEGORY => 'NAME_LAST', VALUE => 'Tarczyn' ],
  MaeyEllenLutz => [ CATEGORY => 'NAME_FIRST', VALUE => 'Maey Ellen', CATEGORY => 'NAME_LAST', VALUE => 'Lutz' ],
  MaggyW => [ CATEGORY => 'NAME_FIRST', VALUE => 'Maggy', CATEGORY => 'NAME_INITIALS', VALUE => 'W.' ],
  MajBritt => [ CATEGORY => 'NAME_FIRST', VALUE => 'Maj Britt' ],
  MajLis => [ CATEGORY => 'NAME_FIRST', VALUE => 'Maj Lis' ],
  MajaKlein => [ CATEGORY => 'NAME_FIRST', VALUE => 'Maja', CATEGORY => 'NAME_LAST', VALUE => 'Klein' ],
  MarIna => [ CATEGORY => 'NAME_FIRST', VALUE => 'Marina' ],
  MarcelleMersereau => [ CATEGORY => 'NAME_FIRST', VALUE => 'Marcelle', CATEGORY => 'NAME_LAST', VALUE => 'Mersereau' ],
  MarciaGahring => [ CATEGORY => 'NAME_FIRST', VALUE => 'Marcia', CATEGORY => 'NAME_LAST', VALUE => 'Gahring' ],
  MarcinW => [ CATEGORY => 'NAME_FIRST', VALUE => 'Marcin', CATEGORY => 'NAME_INITIALS', VALUE => 'W.' ],
  MarcinWiacek => [ CATEGORY => 'NAME_FIRST', VALUE => 'Marcin', CATEGORY => 'NAME_LAST', VALUE => 'Wiacek' ],
  MarekBytof => [ CATEGORY => 'NAME_FIRST', VALUE => 'Marek', CATEGORY => 'NAME_LAST', VALUE => 'Bytof' ],
  MargaretQuigley => [ CATEGORY => 'NAME_FIRST', VALUE => 'Margaret', CATEGORY => 'NAME_LAST', VALUE => 'Quigley' ],
  MargaretaE => [ CATEGORY => 'NAME_FIRST', VALUE => 'Margareta', CATEGORY => 'NAME_INITIALS', VALUE => 'E.' ],
  MargeTownsend => [ CATEGORY => 'NAME_FIRST', VALUE => 'Marge', CATEGORY => 'NAME_LAST', VALUE => 'Townsend' ],
  MargitPedersen => [ CATEGORY => 'NAME_FIRST', VALUE => 'Margit', CATEGORY => 'NAME_LAST', VALUE => 'Pedersen' ],
  MariCarmen => [ CATEGORY => 'NAME_FIRST', VALUE => 'Mari Carmen' ],
  MariaAndonova => [ CATEGORY => 'NAME_FIRST', VALUE => 'Maria', CATEGORY => 'NAME_LAST', VALUE => 'Andonova' ],
  MariaChen => [ CATEGORY => 'NAME_FIRST', VALUE => 'Maria', CATEGORY => 'NAME_LAST', VALUE => 'Chen' ],
  MariaEugenia => [ CATEGORY => 'NAME_FIRST', VALUE => 'Maria Eugenia' ],
  MariaGrazia => [ CATEGORY => 'NAME_FIRST', VALUE => 'Maria Grazia' ],
  MariaJ => [ CATEGORY => 'NAME_FIRST', VALUE => 'Maria', CATEGORY => 'NAME_INITIALS', VALUE => 'J.' ],
  MariaN => [ CATEGORY => 'NAME_FIRST', VALUE => 'Maria', CATEGORY => 'NAME_INITIALS', VALUE => 'N.' ],
  MariaZak => [ CATEGORY => 'NAME_FIRST', VALUE => 'Maria', CATEGORY => 'NAME_LAST', VALUE => 'Zak' ],
  MarianVanstone => [ CATEGORY => 'NAME_FIRST', VALUE => 'Marian', CATEGORY => 'NAME_PARTICLES', VALUE => 'van', CATEGORY => 'NAME_LAST', VALUE => 'Stone' ],
  MarieAnne => [ CATEGORY => 'NAME_FIRST', VALUE => 'Marie Anne' ],
  MariePagano => [ CATEGORY => 'NAME_FIRST', VALUE => 'Marie', CATEGORY => 'NAME_LAST', VALUE => 'Pagano' ],
  MarieSybill => [ CATEGORY => 'NAME_FIRST', VALUE => 'Marie Sybill' ],
  MarilynC => [ CATEGORY => 'NAME_FIRST', VALUE => 'Marilyn', CATEGORY => 'NAME_INITIALS', VALUE => 'C.' ],
  MarilynKieffer => [ CATEGORY => 'NAME_FIRST', VALUE => 'Marilyn', CATEGORY => 'NAME_LAST', VALUE => 'Kieffer' ],
  MarisR => [ CATEGORY => 'NAME_FIRST', VALUE => 'Maris', CATEGORY => 'NAME_INITIALS', VALUE => 'R.' ],
  MariuszO => [ CATEGORY => 'NAME_FIRST', VALUE => 'Mariusz', CATEGORY => 'NAME_INITIALS', VALUE => 'O.' ],
  MarkKellett => [ CATEGORY => 'NAME_FIRST', VALUE => 'Mark', CATEGORY => 'NAME_LAST', VALUE => 'Kellett' ],
  MarkM => [ CATEGORY => 'NAME_FIRST', VALUE => 'Mark', CATEGORY => 'NAME_INITIALS', VALUE => 'M.' ],
  MaroulaI => [ CATEGORY => 'NAME_FIRST', VALUE => 'Maroula', CATEGORY => 'NAME_INITIALS', VALUE => 'I.' ],
  MartaA => [ CATEGORY => 'NAME_FIRST', VALUE => 'Marta', CATEGORY => 'NAME_INITIALS', VALUE => 'A.' ],
  MarthaBelle => [ CATEGORY => 'NAME_FIRST', VALUE => 'Martha Belle' ],
  MaryACruse => [ CATEGORY => 'NAME_FIRST', VALUE => 'Mary', CATEGORY => 'NAME_INITIALS', VALUE => 'A.', CATEGORY => 'NAME_LAST', VALUE => 'Cruse' ],
  MaryAnn => [ CATEGORY => 'NAME_FIRST', VALUE => 'Mary Ann' ],
  MaryAnne => [ CATEGORY => 'NAME_FIRST', VALUE => 'Mary Anne' ],
  MaryBeth => [ CATEGORY => 'NAME_FIRST', VALUE => 'Mary Beth' ],
  MaryBrown => [ CATEGORY => 'NAME_FIRST', VALUE => 'Mary', CATEGORY => 'NAME_LAST', VALUE => 'Brown' ],
  MaryEllen => [ CATEGORY => 'NAME_FIRST', VALUE => 'Mary Ellen' ],
  MaryEllenFranzoni => [ CATEGORY => 'NAME_FIRST', VALUE => 'Mary Ellen', CATEGORY => 'NAME_LAST', VALUE => 'Franzoni' ],
  MaryJo => [ CATEGORY => 'NAME_FIRST', VALUE => 'Mary Jo' ],
  MaryLau => [ CATEGORY => 'NAME_FIRST', VALUE => 'Mary Lau' ],
  MaryLee => [ CATEGORY => 'NAME_FIRST', VALUE => 'Mary Lee' ],
  MaryLou => [ CATEGORY => 'NAME_FIRST', VALUE => 'Mary Lou' ],
  "MaryO'Kelly" => [ CATEGORY => 'NAME_FIRST', VALUE => 'Mary', CATEGORY => 'NAME_LAST', VALUE => "O'Kelly" ],
  MarylouMarlow => [ CATEGORY => 'NAME_FIRST', VALUE => 'Marylou', CATEGORY => 'NAME_LAST', VALUE => 'Marlow' ],
  MaurizioV => [ CATEGORY => 'NAME_FIRST', VALUE => 'Maurizio', CATEGORY => 'NAME_INITIALS', VALUE => 'V.' ],
  MayE => [ CATEGORY => 'NAME_FIRST', VALUE => 'May', CATEGORY => 'NAME_INITIALS', VALUE => 'E.' ],
  MeltonDoxey => [ CATEGORY => 'NAME_FIRST', VALUE => 'Melton', CATEGORY => 'NAME_LAST', VALUE => 'Doxey' ],
  MenaBria => [ CATEGORY => 'NAME_FIRST', VALUE => 'Mena', CATEGORY => 'NAME_LAST', VALUE => 'Bria' ],
  MiaWalking => [ CATEGORY => 'NAME_FIRST', VALUE => 'Mia' ],
  MichaelH => [ CATEGORY => 'NAME_FIRST', VALUE => 'Michael', CATEGORY => 'NAME_INITIALS', VALUE => 'H.' ],
  MichaelLee => [ CATEGORY => 'NAME_FIRST', VALUE => 'Michael', CATEGORY => 'NAME_LAST', VALUE => 'Lee' ],
  MichaelP => [ CATEGORY => 'NAME_FIRST', VALUE => 'Michael', CATEGORY => 'NAME_INITIALS', VALUE => 'P.' ],
  MiekeHamelijnck => [ CATEGORY => 'NAME_FIRST', VALUE => 'Mieke', CATEGORY => 'NAME_LAST', VALUE => 'Hamelijnck' ],
  MimiK => [ CATEGORY => 'NAME_FIRST', VALUE => 'Mimi', CATEGORY => 'NAME_INITIALS', VALUE => 'K.' ],
  MoellerPoulsen => [ CATEGORY => 'NAME_FIRST', VALUE => 'Moeller', CATEGORY => 'NAME_LAST', VALUE => 'Poulsen' ],
  MonicS => [ CATEGORY => 'NAME_FIRST', VALUE => 'Monic', CATEGORY => 'NAME_INITIALS', VALUE => 'S.' ],
  MurieL => [ CATEGORY => 'NAME_FIRST', VALUE => 'Murie', CATEGORY => 'NAME_INITIALS', VALUE => 'L.' ],
  MustafaAcar => [ CATEGORY => 'NAME_FIRST', VALUE => 'Mustafa', CATEGORY => 'NAME_LAST', VALUE => 'Acar' ],
  MuthaGM => [ CATEGORY => 'NAME_FIRST', VALUE => 'Mutha', CATEGORY => 'NAME_INITIALS', VALUE => 'G. M.' ],
  MutiaraRK => [ CATEGORY => 'NAME_FIRST', VALUE => 'Mutiara', CATEGORY => 'NAME_INITIALS', VALUE => 'R. K.' ],
  MvanStraalen => [ CATEGORY => 'NAME_INITIALS', VALUE => 'M.', CATEGORY => 'NAME_PARTICLES', VALUE => 'van', CATEGORY => 'NAME_LAST', VALUE => 'Straalen' ],
  NareshKapila => [ CATEGORY => 'NAME_FIRST', VALUE => 'Naresh', CATEGORY => 'NAME_LAST', VALUE => 'Kapila' ],
  NeaBlomst => [ CATEGORY => 'NAME_FIRST', VALUE => 'Nea', CATEGORY => 'NAME_LAST', VALUE => 'Blomst' ],
  NelyTotova => [ CATEGORY => 'NAME_FIRST', VALUE => 'Nely', CATEGORY => 'NAME_LAST', VALUE => 'Totova' ],
  NeomiFriedman => [ CATEGORY => 'NAME_FIRST', VALUE => 'Neomi', CATEGORY => 'NAME_LAST', VALUE => 'Friedman' ],
  NicolettaB => [ CATEGORY => 'NAME_FIRST', VALUE => 'Nicoletta', CATEGORY => 'NAME_INITIALS', VALUE => 'B.' ],
  NihatEkinci => [ CATEGORY => 'NAME_FIRST', VALUE => 'Nihat', CATEGORY => 'NAME_LAST', VALUE => 'Ekinci' ],
  NormG => [ CATEGORY => 'NAME_FIRST', VALUE => 'Norm', CATEGORY => 'NAME_INITIALS', VALUE => 'G.' ],
  NormaRollins => [ CATEGORY => 'NAME_FIRST', VALUE => 'Norma', CATEGORY => 'NAME_LAST', VALUE => 'Rollins' ],
  NumanTeoman => [ CATEGORY => 'NAME_FIRST', VALUE => 'Numan', CATEGORY => 'NAME_LAST', VALUE => 'Teoman' ],
  NuraYS => [ CATEGORY => 'NAME_FIRST', VALUE => 'Nura', CATEGORY => 'NAME_INITIALS', VALUE => 'Y. S.' ],
  NémethTimea => [ CATEGORY => 'NAME_FIRST', VALUE => 'Timea', CATEGORY => 'NAME', VALUE => 'Németh' ],
  OBjoernL => [ CATEGORY => 'NAME_FIRST', VALUE => 'Bjoern', CATEGORY => 'NAME_INITIALS', VALUE => 'L.' ],
  OleJensen => [ CATEGORY => 'NAME_FIRST', VALUE => 'Ole', CATEGORY => 'NAME_LAST', VALUE => 'Jensen' ],
  OliverC => [ CATEGORY => 'NAME_FIRST', VALUE => 'Oliver', CATEGORY => 'NAME_INITIALS', VALUE => 'C.' ],
  OpalJoyce => [ CATEGORY => 'NAME_FIRST', VALUE => 'Opal', CATEGORY => 'NAME_LAST', VALUE => 'Joyce' ],
  OsmanCavit => [ CATEGORY => 'NAME_FIRST', VALUE => 'Osman', CATEGORY => 'NAME_LAST', VALUE => 'Cavit' ],
  PacoCanario => [ CATEGORY => 'NAME_FIRST', VALUE => 'Paco', CATEGORY => 'NAME_LAST', VALUE => 'Canario' ],
  PaddyLee => [ CATEGORY => 'NAME_FIRST', VALUE => 'Paddy', CATEGORY => 'NAME_LAST', VALUE => 'Lee' ],
  ParkI => [ CATEGORY => 'NAME_INITIALS', VALUE => 'I.', CATEGORY => 'NAME_LAST', VALUE => 'Park' ],
  PatN => [ CATEGORY => 'NAME_FIRST', VALUE => 'Pat', CATEGORY => 'NAME_INITIALS', VALUE => 'N.' ],
  PatricPilet => [ CATEGORY => 'NAME_FIRST', VALUE => 'Patric', CATEGORY => 'NAME_LAST', VALUE => 'Pilet' ],
  PatriciaJBarnett => [ CATEGORY => 'NAME_FIRST', VALUE => 'Patricia', CATEGORY => 'NAME_INITIALS', VALUE => 'J.', CATEGORY => 'NAME_LAST', VALUE => 'Barnett' ],
  PatrickS => [ CATEGORY => 'NAME_FIRST', VALUE => 'Patrick', CATEGORY => 'NAME_INITIALS', VALUE => 'S.' ],
  PaulRBartron => [ CATEGORY => 'NAME_FIRST', VALUE => 'Paul', CATEGORY => 'NAME_INITIALS', VALUE => 'R.', CATEGORY => 'NAME_LAST', VALUE => 'Bartron' ],
  PaulineLefkada => [ CATEGORY => 'NAME_FIRST', VALUE => 'Pauline', CATEGORY => 'NAME_LAST', VALUE => 'Lefkada' ],
  PedroMonteiro => [ CATEGORY => 'NAME_FIRST', VALUE => 'Pedro', CATEGORY => 'NAME_LAST', VALUE => 'Monteiro' ],
  PepBaas => [ CATEGORY => 'NAME_FIRST', VALUE => 'Pep', CATEGORY => 'NAME_LAST', VALUE => 'Baas' ],
  PerryShriner => [ CATEGORY => 'NAME_FIRST', VALUE => 'Perry', CATEGORY => 'NAME_LAST', VALUE => 'Shriner' ],
  PerryShrineron => [ CATEGORY => 'NAME_FIRST', VALUE => 'Perry', CATEGORY => 'NAME_LAST', VALUE => 'Shriner' ],
  PeterC => [ CATEGORY => 'NAME_FIRST', VALUE => 'Peter', CATEGORY => 'NAME_INITIALS', VALUE => 'C.' ],
  PhilT => [ CATEGORY => 'NAME_FIRST', VALUE => 'Phil', CATEGORY => 'NAME_INITIALS', VALUE => 'T.' ],
  PhyllisNoury => [ CATEGORY => 'NAME_FIRST', VALUE => 'Phyllis', CATEGORY => 'NAME_LAST', VALUE => 'Noury' ],
  PierSerafina => [ CATEGORY => 'NAME_FIRST', VALUE => 'Pier', CATEGORY => 'NAME_LAST', VALUE => 'Serafina' ],
  PiotrF => [ CATEGORY => 'NAME_FIRST', VALUE => 'Piotr', CATEGORY => 'NAME_INITIALS', VALUE => 'F.' ],
  PiotrMaz => [ CATEGORY => 'NAME_FIRST', VALUE => 'Piotr', CATEGORY => 'NAME_LAST', VALUE => 'Maz' ],
  PiotrQ => [ CATEGORY => 'NAME_FIRST', VALUE => 'Piotr', CATEGORY => 'NAME_INITIALS', VALUE => 'Q.' ],
  PlaraMahardika => [ CATEGORY => 'NAME_FIRST', VALUE => 'Plara', CATEGORY => 'NAME_LAST', VALUE => 'Mahardika' ],
  PradyumnaGorkhali => [ CATEGORY => 'NAME_FIRST', VALUE => 'Pradyumna', CATEGORY => 'NAME_LAST', VALUE => 'Gorkhali' ],
  PraneeT => [ CATEGORY => 'NAME_FIRST', VALUE => 'Praneet' ],
  PrehnMehlsen => [ CATEGORY => 'NAME_FIRST', VALUE => 'Prehn', CATEGORY => 'NAME_LAST', VALUE => 'Mehlsen' ],
  PrivateMikemansur => [ CATEGORY => 'NAME_FIRST', VALUE => 'Mike', CATEGORY => 'NAME_LAST', VALUE => 'Mansur' ],
  PrivateZhujianfen => [ CATEGORY => 'NAME_FIRST', VALUE => 'Jianfen', CATEGORY => 'NAME_LAST', VALUE => 'Zhu' ],
  PymAisbitt => [ CATEGORY => 'NAME_FIRST', VALUE => 'Pym', CATEGORY => 'NAME_LAST', VALUE => 'Aisbitt' ],
  QianRen => [ CATEGORY => 'NAME_FIRST', VALUE => 'Ren', CATEGORY => 'NAME_LAST', VALUE => 'Qian' ],
  QingDao => [ CATEGORY => 'NAME_FIRST', VALUE => 'Dao', CATEGORY => 'NAME_LAST', VALUE => 'Qing' ],
  QkrzyS => [ CATEGORY => 'NAME_FIRST', VALUE => 'Krzysztof', CATEGORY => 'NAME_INITIALS', VALUE => 'S.' ],
  RArrigoFranchi => [ CATEGORY => 'NAME_FIRST', VALUE => 'R. Arrigo', CATEGORY => 'NAME_LAST', VALUE => 'Franchi' ],
  RSebatiATAMAN => [ CATEGORY => 'NAME_FIRST', VALUE => 'Sebati', CATEGORY => 'NAME_LAST', VALUE => 'Ataman' ],
  RTheodorSadecky => [ CATEGORY => 'NAME_FIRST', VALUE => 'Theodor', CATEGORY => 'NAME_LAST', VALUE => 'Sadecky' ],
  RahelP => [ CATEGORY => 'NAME_FIRST', VALUE => 'Rahel', CATEGORY => 'NAME_INITIALS', VALUE => 'P.' ],
  RajaSekhar => [ CATEGORY => 'NAME_FIRST', VALUE => 'Raja', CATEGORY => 'NAME_LAST', VALUE => 'Sekhar' ],
  RamG => [ CATEGORY => 'NAME_FIRST', VALUE => 'Ram', CATEGORY => 'NAME_INITIALS', VALUE => 'G.' ],
  RamY => [ CATEGORY => 'NAME_FIRST', VALUE => 'Ram', CATEGORY => 'NAME_INITIALS', VALUE => 'Y.' ],
  RamazanBerk => [ CATEGORY => 'NAME_FIRST', VALUE => 'Ramazan', CATEGORY => 'NAME_LAST', VALUE => 'Berk' ],
  RannaRuutu => [ CATEGORY => 'NAME_FIRST', VALUE => 'Ranna', CATEGORY => 'NAME_LAST', VALUE => 'Ruutu' ],
  RashidRaman => [ CATEGORY => 'NAME_FIRST', VALUE => 'Rashid', CATEGORY => 'NAME_LAST', VALUE => 'Raman' ],
  RayHart => [ CATEGORY => 'NAME_FIRST', VALUE => 'Ray', CATEGORY => 'NAME_LAST', VALUE => 'Hart' ],
  RayYung => [ CATEGORY => 'NAME_FIRST', VALUE => 'Ray', CATEGORY => 'NAME_LAST', VALUE => 'Yung' ],
  RaymodChen => [ CATEGORY => 'NAME_FIRST', VALUE => 'Raymond', CATEGORY => 'NAME_LAST', VALUE => 'Chen' ],
  RenataDS => [ CATEGORY => 'NAME_FIRST', VALUE => 'Renata', CATEGORY => 'NAME_INITIALS', VALUE => 'D. S.' ],
  RenatoB => [ CATEGORY => 'NAME_FIRST', VALUE => 'Renato', CATEGORY => 'NAME_INITIALS', VALUE => 'B.' ],
  RichardL => [ CATEGORY => 'NAME_FIRST', VALUE => 'Richard', CATEGORY => 'NAME_INITIALS', VALUE => 'L.' ],
  RichardMortara => [ CATEGORY => 'NAME_FIRST', VALUE => 'Richard', CATEGORY => 'NAME_LAST', VALUE => 'Mortara' ],
  RobertChristy => [ CATEGORY => 'NAME_FIRST', VALUE => 'Robert', CATEGORY => 'NAME_LAST', VALUE => 'Christy' ],
  RobertMcCall => [ CATEGORY => 'NAME_FIRST', VALUE => 'Robert', CATEGORY => 'NAME_LAST', VALUE => 'McCall' ],
  RobertZ => [ CATEGORY => 'NAME_FIRST', VALUE => 'Robert', CATEGORY => 'NAME_INITIALS', VALUE => 'Z.' ],
  RogerHolm => [ CATEGORY => 'NAME_FIRST', VALUE => 'Roger', CATEGORY => 'NAME_LAST', VALUE => 'Holm' ],
  RogerPennell => [ CATEGORY => 'NAME_FIRST', VALUE => 'Roger', CATEGORY => 'NAME_LAST', VALUE => 'Pennell' ],
  RomekRyszawy => [ CATEGORY => 'NAME_FIRST', VALUE => 'Romek', CATEGORY => 'NAME_LAST', VALUE => 'Ryszawy' ],
  RonFrost => [ CATEGORY => 'NAME_FIRST', VALUE => 'Ron', CATEGORY => 'NAME_LAST', VALUE => 'Frost' ],
  RonKolkman => [ CATEGORY => 'NAME_FIRST', VALUE => 'Ron', CATEGORY => 'NAME_LAST', VALUE => 'Kolkman' ],
  RonaldFirst => [ CATEGORY => 'NAME_FIRST', VALUE => 'Ronald', CATEGORY => 'NAME_LAST', VALUE => 'First' ],
  RoniLynn => [ CATEGORY => 'NAME_FIRST', VALUE => 'Roni', CATEGORY => 'NAME_LAST', VALUE => 'Lynn' ],
  RonnieHorowitz => [ CATEGORY => 'NAME_FIRST', VALUE => 'Ronnie', CATEGORY => 'NAME_LAST', VALUE => 'Horowitz' ],
  RosaLee => [ CATEGORY => 'NAME_FIRST', VALUE => 'Rosa Lee' ],
  RoseAnne => [ CATEGORY => 'NAME_FIRST', VALUE => 'Rose Anne' ],
  RoseMarie => [ CATEGORY => 'NAME_FIRST', VALUE => 'Rose Marie' ],
  RoyG => [ CATEGORY => 'NAME_FIRST', VALUE => 'Roy', CATEGORY => 'NAME_INITIALS', VALUE => 'G.' ],
  RsaraH => [ CATEGORY => 'NAME_FIRST', VALUE => 'Sarah' ],
  RuiEsteves => [ CATEGORY => 'NAME_FIRST', VALUE => 'Rui', CATEGORY => 'NAME_LAST', VALUE => 'Esteves' ],
  RuthAllen => [ CATEGORY => 'NAME_FIRST', VALUE => 'Ruth Allen' ],
  RuthHamstra => [ CATEGORY => 'NAME_FIRST', VALUE => 'Ruth', CATEGORY => 'NAME_LAST', VALUE => 'Hamstra' ],
  RyanChen => [ CATEGORY => 'NAME_FIRST', VALUE => 'Ryan', CATEGORY => 'NAME_LAST', VALUE => 'Chen' ],
  RydenHolmqvist => [ CATEGORY => 'NAME_FIRST', VALUE => 'Ryden', CATEGORY => 'NAME_LAST', VALUE => 'Holmqvist' ],
  RöneEkmekçio  => [ CATEGORY => 'NAME_FIRST', VALUE => 'Röne', CATEGORY => 'NAME_LAST', VALUE => 'Ekmekçioglu' ],
  SallyL => [ CATEGORY => 'NAME_FIRST', VALUE => 'Sally', CATEGORY => 'NAME_INITIALS', VALUE => 'L.' ],
  SanKulPune => [ CATEGORY => 'NAME_FIRST', VALUE => 'San Kul', CATEGORY => 'NAME_LAST', VALUE => 'Pune' ],
  SandyRee => [ CATEGORY => 'NAME_FIRST', VALUE => 'Sandy', CATEGORY => 'NAME_LAST', VALUE => 'Ree' ],
  SaraB => [ CATEGORY => 'NAME_FIRST', VALUE => 'Sara', CATEGORY => 'NAME_INITIALS', VALUE => 'B.' ],
  SaraK => [ CATEGORY => 'NAME_FIRST', VALUE => 'Sara', CATEGORY => 'NAME_INITIALS', VALUE => 'K.' ],
  SatyaNarayanReddy => [ CATEGORY => 'NAME_FIRST', VALUE => 'Satya', CATEGORY => 'NAME_LAST', VALUE => 'Narayan Reddy' ],
  SauravM => [ CATEGORY => 'NAME_FIRST', VALUE => 'Saurav', CATEGORY => 'NAME_INITIALS', VALUE => 'M.' ],
  SebatiATAMAN => [ CATEGORY => 'NAME_FIRST', VALUE => 'Sebata', CATEGORY => 'NAME_LAST', VALUE => 'Ataman' ],
  SerkaN => [ CATEGORY => 'NAME_FIRST', VALUE => 'Serkan' ],
  ShaggyE => [ CATEGORY => 'NAME_FIRST', VALUE => 'Shaggy', CATEGORY => 'NAME_INITIALS', VALUE => 'E.' ],
  ShaoMin => [ CATEGORY => 'NAME_FIRST', VALUE => 'Min', CATEGORY => 'NAME_LAST', VALUE => 'Shao' ],
  SharonSwartzman => [ CATEGORY => 'NAME_FIRST', VALUE => 'Sharon', CATEGORY => 'NAME_LAST', VALUE => 'Swartzman' ],
  SheilaBegg => [ CATEGORY => 'NAME_FIRST', VALUE => 'Sheila', CATEGORY => 'NAME_LAST', VALUE => 'Begg' ],
  ShenXiang => [ CATEGORY => 'NAME_FIRST', VALUE => 'Xiang', CATEGORY => 'NAME_LAST', VALUE => 'Shen' ],
  SinanU => [ CATEGORY => 'NAME_FIRST', VALUE => 'Sinan', CATEGORY => 'NAME_INITIALS', VALUE => 'U.' ],
  SlawekK => [ CATEGORY => 'NAME_FIRST', VALUE => 'Slawek', CATEGORY => 'NAME_INITIALS', VALUE => 'K.' ],
  SlvanaCaramanno => [ CATEGORY => 'NAME_FIRST', VALUE => 'Slvana', CATEGORY => 'NAME_LAST', VALUE => 'Caramanno' ],
  SolveigFolkeryd => [ CATEGORY => 'NAME_FIRST', VALUE => 'Solveig', CATEGORY => 'NAME_LAST', VALUE => 'Folkeryd' ],
  SongQiao => [ CATEGORY => 'NAME_FIRST', VALUE => 'Qiao', CATEGORY => 'NAME_LAST', VALUE => 'Song' ],
  SreeKumar => [ CATEGORY => 'NAME_FIRST', VALUE => 'Sree', CATEGORY => 'NAME_LAST', VALUE => 'Kumar' ],
  StavracheMihail => [ CATEGORY => 'NAME_FIRST', VALUE => 'Mihail', CATEGORY => 'NAME_LAST', VALUE => 'Stavrache' ],
  SteinarN => [ CATEGORY => 'NAME_FIRST', VALUE => 'Steinar', CATEGORY => 'NAME_INITIALS', VALUE => 'N.' ],
  StephHD => [ CATEGORY => 'NAME_FIRST', VALUE => 'Steph', CATEGORY => 'NAME_INITIALS', VALUE => 'H. D.' ],
  StigHjalmar => [ CATEGORY => 'NAME_FIRST', VALUE => 'Stig Hjalmar' ],
  SueCorley => [ CATEGORY => 'NAME_FIRST', VALUE => 'Sue', CATEGORY => 'NAME_LAST', VALUE => 'Corley' ],
  SueMac => [ CATEGORY => 'NAME_FIRST', VALUE => 'Sue' ],
  SueSmith => [ CATEGORY => 'NAME_FIRST', VALUE => 'Sue', CATEGORY => 'NAME_LAST', VALUE => 'Smith' ],
  SusanMeyer => [ CATEGORY => 'NAME_FIRST', VALUE => 'Susan', CATEGORY => 'NAME_LAST', VALUE => 'Meyer' ],
  SusannaReisch => [ CATEGORY => 'NAME_FIRST', VALUE => 'Susanna', CATEGORY => 'NAME_LAST', VALUE => 'Reisch' ],
  SusanneBjerrum => [ CATEGORY => 'NAME_FIRST', VALUE => 'Susanne', CATEGORY => 'NAME_LAST', VALUE => 'Bjerrum' ],
  SusieF => [ CATEGORY => 'NAME_FIRST', VALUE => 'Susie', CATEGORY => 'NAME_INITIALS', VALUE => 'F.' ],
  SuzanneS => [ CATEGORY => 'NAME_FIRST', VALUE => 'Suzanne', CATEGORY => 'NAME_INITIALS', VALUE => 'S.' ],
  SuziA => [ CATEGORY => 'NAME_FIRST', VALUE => 'Suzi', CATEGORY => 'NAME_INITIALS', VALUE => 'A.' ],
  SverrirThorisson => [ CATEGORY => 'NAME_FIRST', VALUE => 'Sverrir', CATEGORY => 'NAME_LAST', VALUE => 'Thorisson' ],
  SylvieB => [ CATEGORY => 'NAME_FIRST', VALUE => 'Sylvie', CATEGORY => 'NAME_INITIALS', VALUE => 'B.' ],
  TacettinTurker => [ CATEGORY => 'NAME_FIRST', VALUE => 'Tacettin', CATEGORY => 'NAME_LAST', VALUE => '' ],
  TadekP => [ CATEGORY => 'NAME_FIRST', VALUE => 'Tadek', CATEGORY => 'NAME_INITIALS', VALUE => 'P.' ],
  TakisePolak => [ CATEGORY => 'NAME_FIRST', VALUE => 'Takise', CATEGORY => 'NAME_LAST', VALUE => 'Polak' ],
  TangXS => [ CATEGORY => 'NAME_FIRST', VALUE => 'Tang', CATEGORY => 'NAME_INITIALS', VALUE => 'X. S.' ],
  TaniaF => [ CATEGORY => 'NAME_FIRST', VALUE => 'Tania', CATEGORY => 'NAME_INITIALS', VALUE => 'F.' ],
  TanjaL => [ CATEGORY => 'NAME_FIRST', VALUE => 'Tanja', CATEGORY => 'NAME_INITIALS', VALUE => 'L.' ],
  TeeJay => [ CATEGORY => 'NAME_INITIALS', VALUE => 'T. J.' ],
  TeomanKoray => [ CATEGORY => 'NAME_FIRST', VALUE => 'Teoman', CATEGORY => 'NAME_LAST', VALUE => 'Koray' ],
  TerryJ => [ CATEGORY => 'NAME_FIRST', VALUE => 'Terry', CATEGORY => 'NAME_INITIALS', VALUE => 'J.' ],
  ThomasZhang => [ CATEGORY => 'NAME_FIRST', VALUE => 'Thomas', CATEGORY => 'NAME_LAST', VALUE => 'Zhang' ],
  ThosaphoL => [ CATEGORY => 'NAME_FIRST', VALUE => 'Thosapho', CATEGORY => 'NAME_INITIALS', VALUE => 'L.' ],
  TillyBarella => [ CATEGORY => 'NAME_FIRST', VALUE => 'Tilly', CATEGORY => 'NAME_LAST', VALUE => 'Barella' ],
  TimYang => [ CATEGORY => 'NAME_FIRST', VALUE => 'Tim', CATEGORY => 'NAME_LAST', VALUE => 'Yang' ],
  TodorNedelchev => [ CATEGORY => 'NAME_FIRST', VALUE => 'Todor', CATEGORY => 'NAME_LAST', VALUE => 'Nedelchev' ],
  TomB => [ CATEGORY => 'NAME_FIRST', VALUE => 'Tom', CATEGORY => 'NAME_INITIALS', VALUE => 'B.' ],
  TomTrottier => [ CATEGORY => 'NAME_FIRST', VALUE => 'Tom', CATEGORY => 'NAME_LAST', VALUE => 'Trottier' ],
  TomaszJ => [ CATEGORY => 'NAME_FIRST', VALUE => 'Tomasz', CATEGORY => 'NAME_INITIALS', VALUE => 'J.' ],
  TomekP => [ CATEGORY => 'NAME_FIRST', VALUE => 'Tomek', CATEGORY => 'NAME_INITIALS', VALUE => 'P.' ],
  TorbenSLind => [ CATEGORY => 'NAME_FIRST', VALUE => 'Torben', CATEGORY => 'NAME_INITIALS', VALUE => 'S.', CATEGORY => 'NAME_LAST', VALUE => 'Lind' ],
  TrishSmith => [ CATEGORY => 'NAME_FIRST', VALUE => 'Trish', CATEGORY => 'NAME_LAST', VALUE => 'Smith' ],
  TuranA => [ CATEGORY => 'NAME_FIRST', VALUE => 'Turan', CATEGORY => 'NAME_INITIALS', VALUE => 'A.' ],
  TurkumDiyene => [ CATEGORY => 'NAME_FIRST', VALUE => 'Turkum', CATEGORY => 'NAME_LAST', VALUE => 'Diyene' ],
  TusharKanti => [ CATEGORY => 'NAME_FIRST', VALUE => 'Tushar', CATEGORY => 'NAME_LAST', VALUE => 'Kanti' ],
  UllA => [ CATEGORY => 'NAME_FIRST', VALUE => 'Ulla' ],
  UllaBritt => [ CATEGORY => 'NAME_FIRST', VALUE => 'Ulla Britt' ],
  UllaGrundel => [ CATEGORY => 'NAME_FIRST', VALUE => 'Ulla', CATEGORY => 'NAME_LAST', VALUE => 'Grundel' ],
  UyGaR => [ CATEGORY => 'NAME_FIRST', VALUE => 'Uygar' ],
  VGianCarlo => [ CATEGORY => 'NAME_FIRST', VALUE => 'Gian Carlo' ],
  VSevdamYakar  => [ CATEGORY => 'NAME_FIRST', VALUE => 'Sevdam', CATEGORY => 'NAME_LAST', VALUE => 'Yakar' ],
  ValerieBIL => [ CATEGORY => 'NAME_FIRST', VALUE => 'Valerie' ],
  ValerieGamio => [ CATEGORY => 'NAME_FIRST', VALUE => 'Valerie', CATEGORY => 'NAME_LAST', VALUE => 'Gamio' ],
  VanDyke => [ CATEGORY => 'NAME_PARTICLES', VALUE => 'van', CATEGORY => 'NAME_LAST', VALUE => 'Dyke' ],
  VanHatten => [ CATEGORY => 'NAME_PARTICLES', VALUE => 'Van', CATEGORY => 'NAME_LAST', VALUE => 'Hatten' ],
  VanOchten => [ CATEGORY => 'NAME_PARTICLES', VALUE => 'Van', CATEGORY => 'NAME_LAST', VALUE => 'Ochten' ],
  VanOs => [ CATEGORY => 'NAME_PARTICLES', VALUE => 'Van', CATEGORY => 'NAME_LAST', VALUE => 'Os' ],
  VanSanten => [ CATEGORY => 'NAME_PARTICLES', VALUE => 'van', CATEGORY => 'NAME_LAST', VALUE => 'Santen' ],
  VanSnick => [ CATEGORY => 'NAME_PARTICLES', VALUE => 'van', CATEGORY => 'NAME_LAST', VALUE => 'Snick' ],
  VanSon => [ CATEGORY => 'NAME_PARTICLES', VALUE => 'van', CATEGORY => 'NAME_LAST', VALUE => 'Son' ],
  VanVark => [ CATEGORY => 'NAME_PARTICLES', VALUE => 'van', CATEGORY => 'NAME_LAST', VALUE => 'Vark' ],
  VanVreede => [ CATEGORY => 'NAME_PARTICLES', VALUE => 'Van', CATEGORY => 'NAME_LAST', VALUE => 'Vreede' ],
  VanWyck => [ CATEGORY => 'NAME_PARTICLES', VALUE => 'van', CATEGORY => 'NAME_LAST', VALUE => 'Wyck' ],
  VandeKerkhove => [ CATEGORY => 'NAME_PARTICLES', VALUE => 'van de', CATEGORY => 'NAME_LAST', VALUE => 'Kerkhove' ],
  VasilCholakov => [ CATEGORY => 'NAME_FIRST', VALUE => 'Vasil', CATEGORY => 'NAME_LAST', VALUE => 'Cholakov' ],
  VinayB => [ CATEGORY => 'NAME_FIRST', VALUE => 'Vinay', CATEGORY => 'NAME_INITIALS', VALUE => 'B.' ],
  VonDeylen => [ CATEGORY => 'NAME_PARTICLES', VALUE => 'von', CATEGORY => 'NAME_LAST', VALUE => 'Deylen' ],
  WAndrzejK => [ CATEGORY => 'NAME_FIRST', VALUE => 'Andrzej', CATEGORY => 'NAME_INITIALS', VALUE => 'K.' ],
  WaldemarMatyga => [ CATEGORY => 'NAME_FIRST', VALUE => 'Waldemar', CATEGORY => 'NAME_LAST', VALUE => 'Matyga' ],
  WalterB => [ CATEGORY => 'NAME_FIRST', VALUE => 'Walter', CATEGORY => 'NAME_INITIALS', VALUE => 'B.' ],
  WalterKerr => [ CATEGORY => 'NAME_FIRST', VALUE => 'Walter', CATEGORY => 'NAME_LAST', VALUE => 'Kerr' ],
  WangHao => [ CATEGORY => 'NAME_FIRST', VALUE => 'Hao', CATEGORY => 'NAME_LAST', VALUE => 'Wang' ],
  WangWei => [ CATEGORY => 'NAME_FIRST', VALUE => 'Wei', CATEGORY => 'NAME_LAST', VALUE => 'Wang' ],
  WangWenXue => [ CATEGORY => 'NAME_FIRST', VALUE => 'Wen Xue', CATEGORY => 'NAME_LAST', VALUE => 'Wang' ],
  WangYun => [ CATEGORY => 'NAME_FIRST', VALUE => 'Yun', CATEGORY => 'NAME_LAST', VALUE => 'Wang' ],
  WeishunTie => [ CATEGORY => 'NAME_FIRST', VALUE => 'Weishun', CATEGORY => 'NAME_LAST', VALUE => 'Tie' ],
  WilliamJ => [ CATEGORY => 'NAME_FIRST', VALUE => 'William', CATEGORY => 'NAME_INITIALS', VALUE => 'J.' ],
  WilliamLou => [ CATEGORY => 'NAME_FIRST', VALUE => 'William Lou' ],
  WilliamR => [ CATEGORY => 'NAME_FIRST', VALUE => 'William', CATEGORY => 'NAME_INITIALS', VALUE => 'R.' ],
  WingTakTo => [ CATEGORY => 'NAME_FIRST', VALUE => 'To', CATEGORY => 'NAME_LAST', VALUE => 'Wing Tak' ],
  WinsteD => [ CATEGORY => 'NAME_LAST', VALUE => 'Winsted' ],
  WojciechJablonski => [ CATEGORY => 'NAME_FIRST', VALUE => 'Wojciech', CATEGORY => 'NAME_LAST', VALUE => 'Jablonski' ],
  WojciechW => [ CATEGORY => 'NAME_FIRST', VALUE => 'Wojciech', CATEGORY => 'NAME_INITIALS', VALUE => 'W.' ],
  WuJiaoQi => [ CATEGORY => 'NAME_FIRST', VALUE => 'Jiao Qi', CATEGORY => 'NAME_LAST', VALUE => 'Wu' ],
  WuSongBai => [ CATEGORY => 'NAME_FIRST', VALUE => 'Song Bai', CATEGORY => 'NAME_LAST', VALUE => 'Wu' ],
  XiaLing => [ CATEGORY => 'NAME_FIRST', VALUE => 'Ling', CATEGORY => 'NAME_LAST', VALUE => 'Xia' ],
  XieSongmao => [ CATEGORY => 'NAME_FIRST', VALUE => 'Songmao', CATEGORY => 'NAME_LAST', VALUE => 'Xie' ],
  YAndrzeJ => [ CATEGORY => 'NAME_FIRST', VALUE => 'Andrzej' ],
  YanZ => [ CATEGORY => 'NAME_FIRST', VALUE => 'Yan', CATEGORY => 'NAME_INITIALS', VALUE => 'Z.' ],
  YasinHACIMUSALAR => [ CATEGORY => 'NAME_FIRST', VALUE => 'Yasin', CATEGORY => 'NAME_LAST', VALUE => 'Hacimusalar' ],
  YimanSong => [ CATEGORY => 'NAME_FIRST', VALUE => 'Song', CATEGORY => 'NAME_LAST', VALUE => 'Yiman' ],
  YingXiang => [ CATEGORY => 'NAME_FIRST', VALUE => 'Xiang', CATEGORY => 'NAME_LAST', VALUE => 'Ying' ],
  YngveN => [ CATEGORY => 'NAME_FIRST', VALUE => 'Yngve', CATEGORY => 'NAME_INITIALS', VALUE => 'N.' ],
  YohanesR => [ CATEGORY => 'NAME_FIRST', VALUE => 'Yohanes', CATEGORY => 'NAME_INITIALS', VALUE => 'R.' ],
  YongZhi => [ CATEGORY => 'NAME_FIRST', VALUE => 'Zhi', CATEGORY => 'NAME_LAST', VALUE => 'Yong' ],
  YuanQi => [ CATEGORY => 'NAME_FIRST', VALUE => 'Qi', CATEGORY => 'NAME_LAST', VALUE => 'Yuan' ],
  YucelTuzcuoglu => [ CATEGORY => 'NAME_FIRST', VALUE => 'Yucel', CATEGORY => 'NAME_LAST', VALUE => 'Tuzcuoglu' ],
  YunYun => [ CATEGORY => 'NAME_FIRST', VALUE => 'Yun Yun' ],
  YusufeliSevdam => [ CATEGORY => 'NAME_FIRST', VALUE => 'Yusufeli', CATEGORY => 'NAME_LAST', VALUE => 'Sevdam' ],
  YvonneMarjan => [ CATEGORY => 'NAME_FIRST', VALUE => 'Yvonne', CATEGORY => 'NAME_LAST', VALUE => 'Marjan' ],
  ZAdaM => [ CATEGORY => 'NAME_FIRST', VALUE => 'Adam' ],
  ZacKhaR => [ CATEGORY => 'NAME_FIRST', VALUE => 'Zackhar' ],
  ZamfiR => [ CATEGORY => 'NAME_FIRST', VALUE => 'Zamfir' ],
  ZekiKARA => [ CATEGORY => 'NAME_FIRST', VALUE => 'Zeki', CATEGORY => 'NAME_LAST', VALUE => 'Kara' ],
  ZeyneL => [ CATEGORY => 'NAME_FIRST', VALUE => 'Zeyne', CATEGORY => 'NAME_INITIALS', VALUE => 'L.' ],
  ZhangDS => [ CATEGORY => 'NAME_INITIALS', VALUE => 'D. S.', CATEGORY => 'NAME_LAST', VALUE => 'Zhang' ],
  ZhangFeng => [ CATEGORY => 'NAME_FIRST', VALUE => 'Feng', CATEGORY => 'NAME_LAST', VALUE => 'Zhang' ],
  ZhangZhou => [ CATEGORY => 'NAME_FIRST', VALUE => 'Zhou', CATEGORY => 'NAME_LAST', VALUE => 'Zhang' ],
  ZhengZhu => [ CATEGORY => 'NAME_FIRST', VALUE => 'Zhu', CATEGORY => 'NAME_LAST', VALUE => 'Zhong' ],
  ZhixiuChangsha => [ CATEGORY => 'NAME_FIRST', VALUE => 'Changsha', CATEGORY => 'NAME_LAST', VALUE => 'Zhixiu' ],
  ZiaMahmood => [ CATEGORY => 'NAME_FIRST', VALUE => 'Zia', CATEGORY => 'NAME_LAST', VALUE => 'Mahmood' ],
  aliceGiancarlo => [ CATEGORY => 'NAME_FIRST', VALUE => 'Alice', CATEGORY => 'NAME_LAST', VALUE => 'Giancarlo' ],
  andRE => [ CATEGORY => 'NAME_FIRST', VALUE => 'Andre' ],
  andrzejB => [ CATEGORY => 'NAME_FIRST', VALUE => 'Andrzej', CATEGORY => 'NAME_INITIALS', VALUE => 'B.' ],
  anitaHETKE => [ CATEGORY => 'NAME_FIRST', VALUE => 'Anita', CATEGORY => 'NAME_LAST', VALUE => 'Hetke' ],
  annieSalvenmoser => [ CATEGORY => 'NAME_FIRST', VALUE => 'Annie', CATEGORY => 'NAME_LAST', VALUE => 'Salvenmoser' ],
  antzoyLETA => [ CATEGORY => 'NAME_FIRST', VALUE => 'Antzoy', CATEGORY => 'NAME_LAST', VALUE => 'Leta' ],
  anuradhaJ => [ CATEGORY => 'NAME_FIRST', VALUE => 'Anuradha', CATEGORY => 'NAME_INITIALS', VALUE => 'J.' ],
  boleySonia => [ CATEGORY => 'NAME_FIRST', VALUE => 'Sonia', CATEGORY => 'NAME_LAST', VALUE => 'Boley' ],
  brendaSlaughter => [ CATEGORY => 'NAME_FIRST', VALUE => 'Brenda', CATEGORY => 'NAME_LAST', VALUE => 'Slaughter' ],
  capucineDubosquet => [ CATEGORY => 'NAME_FIRST', VALUE => 'Capucine', CATEGORY => 'NAME_LAST', VALUE => 'Dubosquet' ],
  carlinLarry => [ CATEGORY => 'NAME_FIRST', VALUE => 'Carlin', CATEGORY => 'NAME_LAST', VALUE => 'Larry' ],
  catherineOsickey => [ CATEGORY => 'NAME_FIRST', VALUE => 'Catherine', CATEGORY => 'NAME_LAST', VALUE => 'Osickey' ],
  claudiaU => [ CATEGORY => 'NAME_FIRST', VALUE => 'Claudia', CATEGORY => 'NAME_INITIALS', VALUE => 'U.' ],
  corinneCluzel => [ CATEGORY => 'NAME_FIRST', VALUE => 'Corinne', CATEGORY => 'NAME_LAST', VALUE => 'Cluzel' ],
  daSilva => [ CATEGORY => 'NAME_PARTICLES', VALUE => 'da', CATEGORY => 'NAME_LAST', VALUE => 'Silva' ],
  daniL => [ CATEGORY => 'NAME_FIRST', VALUE => 'Dani', CATEGORY => 'NAME_INITIALS', VALUE => 'L.' ],
  deBeauvais => [ CATEGORY => 'NAME_PARTICLES', VALUE => 'de', CATEGORY => 'NAME_LAST', VALUE => 'Beauvais' ],
  deBrillancourt => [ CATEGORY => 'NAME_PARTICLES', VALUE => 'de', CATEGORY => 'NAME_LAST', VALUE => 'Brillancourt' ],
  deJong => [ CATEGORY => 'NAME_PARTICLES', VALUE => 'de', CATEGORY => 'NAME_LAST', VALUE => 'Jong' ],
  deLanie => [ CATEGORY => 'NAME_PARTICLES', VALUE => 'de', CATEGORY => 'NAME_LAST', VALUE => 'Lanie' ],
  deMaine => [ CATEGORY => 'NAME_PARTICLES', VALUE => 'de', CATEGORY => 'NAME_LAST', VALUE => 'Maine' ],
  dePalo => [ CATEGORY => 'NAME_PARTICLES', VALUE => 'de', CATEGORY => 'NAME_LAST', VALUE => 'Palo' ],
  dellalPrivate => [ CATEGORY => 'NAME_LAST', VALUE => 'Dellal' ],
  dorisHetke => [ CATEGORY => 'NAME_FIRST', VALUE => 'Doris', CATEGORY => 'NAME_LAST', VALUE => 'Hetke' ],
  duPonT => [ CATEGORY => 'NAME_PARTICLES', VALUE => 'du', CATEGORY => 'NAME_LAST', VALUE => 'Punt' ],
  enTon => [ CATEGORY => 'NAME_PARTICLES', VALUE => 'en', CATEGORY => 'NAME_LAST', VALUE => 'Ton' ],
  ericplaySweden => [ CATEGORY => 'NAME_FIRST', VALUE => 'Eric' ],
  errandoneaPrivate => [ CATEGORY => 'NAME_LAST', VALUE => 'Errandonea' ],
  ffrankT => [ CATEGORY => 'NAME_FIRST', VALUE => 'Frank', CATEGORY => 'NAME_INITIALS', VALUE => 'T.' ],
  franK => [ CATEGORY => 'NAME_FIRST', VALUE => 'Frank' ],
  frenkielfrenkielPrivate => [ CATEGORY => 'NAME_LAST', VALUE => 'Frenkiel' ],
  garelG => [ CATEGORY => 'NAME_FIRST', VALUE => 'Garel', CATEGORY => 'NAME_INITIALS', VALUE => 'G.' ],
  garoufALIS => [ CATEGORY => 'NAME_LAST', VALUE => 'Garoufalis' ],
  garyGottlieb => [ CATEGORY => 'NAME_FIRST', VALUE => 'Gary', CATEGORY => 'NAME_LAST', VALUE => 'Gottlieb' ],
  geneK => [ CATEGORY => 'NAME_FIRST', VALUE => 'Gene', CATEGORY => 'NAME_INITIALS', VALUE => 'K.' ],
  grannyE => [ CATEGORY => 'NAME_FIRST', VALUE => 'Granny', CATEGORY => 'NAME_INITIALS', VALUE => 'E.' ],
  gshillabeerPrivate => [ CATEGORY => 'NAME_INITIALS', VALUE => 'G.', CATEGORY => 'NAME_LAST', VALUE => 'Shillabeer' ],
  gunnarssonHafsteinn => [ CATEGORY => 'NAME_FIRST', VALUE => 'Hafsteinn', CATEGORY => 'NAME_LAST', VALUE => 'Gunnarsson' ],
  hikmetK => [ CATEGORY => 'NAME_FIRST', VALUE => 'Hikmet', CATEGORY => 'NAME_INITIALS', VALUE => 'K.' ],
  hoBERMAN => [ CATEGORY => 'NAME_LAST', VALUE => 'Hoberman' ],
  jacobKkarni => [ CATEGORY => 'NAME_FIRST', VALUE => 'Jacob', CATEGORY => 'NAME_FIRST', VALUE => 'Kkarni' ],
  jacquelineBeauchemin => [ CATEGORY => 'NAME_FIRST', VALUE => 'Jacqueline', CATEGORY => 'NAME_LAST', VALUE => 'Beauchemin' ],
  janekROTARSKI => [ CATEGORY => 'NAME_FIRST', VALUE => 'Janek', CATEGORY => 'NAME_LAST', VALUE => 'Rotarski' ],
  jismailC => [ CATEGORY => 'NAME_FIRST', VALUE => 'Ismail', CATEGORY => 'NAME_INITIALS', VALUE => 'C.' ],
  joanGray => [ CATEGORY => 'NAME_FIRST', VALUE => 'Joan', CATEGORY => 'NAME_LAST', VALUE => 'Gray' ],
  johnDeMaria => [ CATEGORY => 'NAME_FIRST', VALUE => 'John', CATEGORY => 'NAME_LAST', VALUE => 'DeMaria' ],
  kathrynB => [ CATEGORY => 'NAME_FIRST', VALUE => 'Kathryn', CATEGORY => 'NAME_INITIALS', VALUE => 'B.' ],
  kismailC => [ CATEGORY => 'NAME_FIRST', VALUE => 'Ismail', CATEGORY => 'NAME_INITIALS', VALUE => 'C.' ],
  krzyS => [ CATEGORY => 'NAME_FIRST', VALUE => 'Krzysztof', CATEGORY => 'NAME_INITIALS', VALUE => 'S.' ],
  laRocq => [ CATEGORY => 'NAME_PARTICLES', VALUE => 'la', CATEGORY => 'NAME_LAST', VALUE => 'Rocq' ],
  labroJeanne => [ CATEGORY => 'NAME_FIRST', VALUE => 'Jeanne', CATEGORY => 'NAME_LAST', VALUE => 'Labro' ],
  laoChen => [ CATEGORY => 'NAME_FIRST', VALUE => 'Lao', CATEGORY => 'NAME_LAST', VALUE => 'Chen' ],
  larserikJ => [ CATEGORY => 'NAME_FIRST', VALUE => 'Lars Erik', CATEGORY => 'NAME_INITIALS', VALUE => 'J.' ],
  lauraR => [ CATEGORY => 'NAME_FIRST', VALUE => 'Laura', CATEGORY => 'NAME_INITIALS', VALUE => 'R.' ],
  liminCHEN => [ CATEGORY => 'NAME_FIRST', VALUE => 'Limin', CATEGORY => 'NAME_LAST', VALUE => 'Chen' ],
  lisaA => [ CATEGORY => 'NAME_FIRST', VALUE => 'Lisa', CATEGORY => 'NAME_INITIALS', VALUE => 'A.' ],
  lsStella => [ CATEGORY => 'NAME_FIRST', VALUE => 'Stella' ],
  lwmDekkers => [ CATEGORY => 'NAME_FIRST', VALUE => 'L. W. M.', CATEGORY => 'NAME_LAST', VALUE => 'Dekkers' ],
  margreethV => [ CATEGORY => 'NAME_FIRST', VALUE => 'Margreeth', CATEGORY => 'NAME_INITIALS', VALUE => 'V.' ],
  marioR => [ CATEGORY => 'NAME_FIRST', VALUE => 'Mario', CATEGORY => 'NAME_INITIALS', VALUE => 'R.' ],
  mariterenavaPrivate => [ CATEGORY => 'NAME_FIRST', VALUE => 'Maria Teresa', CATEGORY => 'NAME_LAST', VALUE => 'Nava' ],
  maryJ => [ CATEGORY => 'NAME_FIRST', VALUE => 'Mary', CATEGORY => 'NAME_INITIALS', VALUE => 'J.' ],
  mcCabe => [ CATEGORY => 'NAME_LAST', VALUE => 'McCabe' ],
  mcCahnn => [ CATEGORY => 'NAME_LAST', VALUE => 'McCahn' ],
  memedAli => [ CATEGORY => 'NAME_FIRST', VALUE => 'Memed', CATEGORY => 'NAME_LAST', VALUE => 'Ali' ],
  muraTCura => [ CATEGORY => 'NAME_FIRST', VALUE => 'Murat', CATEGORY => 'NAME_LAST', VALUE => 'Cura' ],
  mustafA => [ CATEGORY => 'NAME_FIRST', VALUE => 'Mustafa' ],
  nadinenickelPrivate => [ CATEGORY => 'NAME_FIRST', VALUE => 'Nadine', CATEGORY => 'NAME_LAST', VALUE => 'Nickel' ],
  neBOJsa => [ CATEGORY => 'NAME_FIRST', VALUE => 'Nebojsa' ],
  nicoleL => [ CATEGORY => 'NAME_FIRST', VALUE => 'Nicole', CATEGORY => 'NAME_INITIALS', VALUE => 'L.' ],
  nitraM => [ CATEGORY => 'NAME_FIRST', VALUE => 'Martin' ],
  nivlaC => [ CATEGORY => 'NAME_FIRST', VALUE => 'Calvin' ],
  nowyJ => [ CATEGORY => 'NAME_INITIALS', VALUE => 'J.', CATEGORY => 'NAME_LAST', VALUE => 'Nowy' ],
  odettwePrivate => [ CATEGORY => 'NAME_FIRST', VALUE => 'Odette' ],
  orhanAyhan => [ CATEGORY => 'NAME_FIRST', VALUE => 'Orhan', CATEGORY => 'NAME_LAST', VALUE => 'Ayhan' ],
  ozGul => [ CATEGORY => 'NAME_FIRST', VALUE => 'Özgül' ],
  safakD => [ CATEGORY => 'NAME_FIRST', VALUE => 'Safak', CATEGORY => 'NAME_INITIALS', VALUE => 'D.' ],
  samuelH => [ CATEGORY => 'NAME_FIRST', VALUE => 'Samuel', CATEGORY => 'NAME_INITIALS', VALUE => 'H.' ],
  sergeB => [ CATEGORY => 'NAME_FIRST', VALUE => 'Serge', CATEGORY => 'NAME_INITIALS', VALUE => 'B.' ],
  shulavaskevitchPrivate => [ CATEGORY => 'NAME_FIRST', VALUE => 'Shula', CATEGORY => 'NAME_LAST', VALUE => 'Vaskevitch' ],
  simonQi => [ CATEGORY => 'NAME_FIRST', VALUE => 'Simon', CATEGORY => 'NAME_LAST', VALUE => 'Qi' ],
  susAN => [ CATEGORY => 'NAME_FIRST', VALUE => 'Susan' ],
  susanS => [ CATEGORY => 'NAME_FIRST', VALUE => 'Susan', CATEGORY => 'NAME_INITIALS', VALUE => 'S.' ],
  tommyJoe => [ CATEGORY => 'NAME_FIRST', VALUE => 'Tommy Joe' ],
  viviM => [ CATEGORY => 'NAME_FIRST', VALUE => 'Vivi', CATEGORY => 'NAME_INITIALS', VALUE => 'M.' ],
  vonBeck => [ CATEGORY => 'NAME_PARTICLES', VALUE => 'von', CATEGORY => 'NAME_LAST', VALUE => 'Beck' ],
  wangH => [ CATEGORY => 'NAME_INITIALS', VALUE => 'H.', CATEGORY => 'NAME_INITIALS', VALUE => 'Wang' ],
  wictorRo => [ CATEGORY => 'NAME_FIRST', VALUE => 'Wictor' ],
  xiaozhenQ => [ CATEGORY => 'NAME_FIRST', VALUE => 'Xiaozhen', CATEGORY => 'NAME_INITIALS', VALUE => 'Q.' ],
  xoxoxoJoan => [ CATEGORY => 'NAME_FIRST', VALUE => 'Joan' ],
  yrraB => [ CATEGORY => 'NAME_FIRST', VALUE => 'Barry' ],
  zhouCQ => [ CATEGORY => 'NAME_INITIALS', VALUE => 'C. Q.', CATEGORY => 'NAME_LAST', VALUE => 'Zhou' ],
  ziutekS => [ CATEGORY => 'NAME_FIRST', VALUE => 'Ziutek', CATEGORY => 'NAME_INITIALS', VALUE => 'S.' ],
);

sub split
{
  my ($text, $splits) = @_;

  if (exists $NAMES{$text})
  {
    @$splits = @{$NAMES{$text}};
    return 1;
  }
  else
  {
    return 0;
  }
}

1;
