#!perl

package Caps::Names;

use v5.10;
use strict;
use warnings;
use utf8;
use open ':std', ':encoding(UTF-8)';

use Exporter;

our @ISA = qw(Exporter);
our @EXPORT = qw(split);

my %NAMES =
(
  'AbdKader' => [ NAME_FIRST => 'Abd', NAME_LAST => 'Kader'],
  'AbidiN' => [ NAME_LAST => 'Abidi', NAME_INITIALS => 'N.'],
  'AchenK' => [ NAME_FIRST => 'Achen', NAME_INITIALS => 'K.'],
  'AdieSue' => [ NAME_FIRST => 'Adie Sue'],
  'AhmetCan' => [ NAME_FIRST => 'Ahmet', NAME_LAST => 'Can'],
  'AiLeuS' => [ NAME_FIRST => 'Ai Leu', NAME_INITIALS => 'S.'],
  'AiQiuFu' => [ NAME_FIRST => 'Ai Qiu', NAME_LAST => 'Fu'],
  'AiliHelena' => [ NAME_LAST => 'Aili', NAME_FIRST => 'Helena'],
  'AlanChen' => [ NAME_FIRST => 'Alan', NAME_LAST => 'Chen'],
  'AlanH' => [ NAME_FIRST => 'Alan', NAME_INITIALS => 'H.'],
  'AlbertoDeSordi' => [ NAME_FIRST => 'Alberto', NAME_PARTICLES => 'de', NAME_LAST => 'Sordi'],
  'AlenkaNikl' => [ NAME_FIRST => 'Alenka', NAME_LAST => 'Nikl'],
  'AlexD' => [ NAME_FIRST => 'Alex', NAME_INITIALS => 'D.'],
  'AlexSveinson' => [ NAME_FIRST => 'Alex', NAME_LAST => 'Sveinson'],
  'AlexandreLITVAK' => [ NAME_FIRST => 'Alexandre', NAME_LAST => 'Litvak'],
  'AliHaydar' => [ NAME_FIRST => 'Ali', NAME_LAST => 'Haydar'],
  'AliR' => [ NAME_FIRST => 'Ali', NAME_INITIALS => 'R.'],
  'AliYAVUZ' => [ NAME_FIRST => 'AliFIRST', NAME_LAST => 'Yavuz'],
  'AliciaBeatriz' => [ NAME_FIRST => 'Alicia Beatriz'],
  'AllenLevy' => [ NAME_FIRST => 'Allen', NAME_LAST => 'Levy'],
  'AlpArslan' => [ NAME_FIRST => 'Alp', NAME_LAST => 'Arslan'],
  'AmisFRANCO' => [ NAME_FIRST => 'Amis', NAME_LAST => 'Franco'],
  'AmyLin' => [ NAME_FIRST => 'Amy', NAME_LAST => 'Lin'],
  'AmyZhao' => [ NAME_FIRST => 'Amy', NAME_LAST => 'Zhao'],
  'AngelaRC' => [ NAME_FIRST => 'Angela', NAME_INITIALS => 'R. C.'],
  'AniaAdas' => [ NAME_FIRST => 'Ania', NAME_LAST => 'Adas'],
  'AnnLena' => [ NAME_FIRST => 'Ann Lena'],
  'AnnMorton' => [ NAME_FIRST => 'Ann', NAME_LAST => 'Morton'],
  'AnnaGailChapman' => [ NAME_FIRST => 'Anna Gail', NAME_LAST => 'Chapman'],
  'AnnaMaria' => [ NAME_FIRST => 'Anna Maria'],
  'AnnaOlsen' => [ NAME_FIRST => 'Anna', NAME_LAST => 'Olsen'],
  'AnneB' => [ NAME_FIRST => 'Anne', NAME_INITIALS => 'B.'],
  'AnneFreeman' => [ NAME_FIRST => 'Anned', NAME_LAST => 'Freeman'],
  'AnneKristine' => [ NAME_FIRST => 'Anne Kristine'],
  'AnneLiao' => [ NAME_FIRST => 'Anne', NAME_LAST => 'Liao'],
  'AnneMaria' => [ NAME_FIRST => 'Anne Maria'],
  'AnneMarie' => [ NAME_FIRST => 'Anne Marie'],
  'AnneMette' => [ NAME_FIRST => 'Anne Mette'],
  'AnneMieke' => [ NAME_FIRST => 'Anne Mieke'],
  'AnneSophie' => [ NAME_FIRST => 'Anne Sophie'],
  'AnnieDomhof' => [ NAME_FIRST => 'Annie', NAME_LAST => 'Domhof'],
  'AnnieLaure' => [ NAME_FIRST => 'Annie Laure'],
  'BarbaraSopkin' => [ NAME_FIRST => 'Barbara', NAME_LAST => 'Sopkin'],
  'BarbaraWeston' => [ NAME_FIRST => 'Barbara', NAME_LAST => 'Weston'],
  'BerkinElvan' => [ NAME_FIRST => 'Berkin', NAME_LAST => 'Elvan'],
  'BethAnne' => [ NAME_FIRST => 'Beth Anne'],
  'BetsyM' => [ NAME_FIRST => 'Betsy', NAME_INITIALS => 'M.'],
  'BettyGYoung' => [ NAME_FIRST => 'Betty', NAME_INITIALS => 'G.', NAME_LAST => 'Young'],
  'BettyJane' => [ NAME_FIRST => 'Betty Jane'],
  'BillFair' => [ NAME_FIRST => 'Bill', NAME_LAST => 'Fair'],
  'BillSmith' => [ NAME_FIRST => 'Bill', NAME_LAST => 'Smith'],
  'BillyTsang' => [ NAME_FIRST => 'Billy', NAME_LAST => 'Tsang'],
  'BjornQuistgard' => [ NAME_FIRST => 'Bjorn', NAME_LAST => 'Quistgard'],
  'BoYuanCheng' => [ NAME_FIRST => 'Bo Yuan', NAME_LAST => 'Cheng'],
  'BobCrossley' => [ NAME_FIRST => 'Bob', NAME_LAST => 'Crossley'],
  'BogdanB' => [ NAME_FIRST => 'Bogdan', NAME_INITIALS => 'B.'],
  'BonnieBond' => [ NAME_FIRST => 'Bonnie', NAME_LAST => 'Bond'],
  'BruceLemle' => [ NAME_FIRST => 'Bruce', NAME_LAST => 'Lemle'],
  'BrunoB' => [ NAME_FIRST => 'Bruno', NAME_INITIALS => 'B.'],
  'BryanLee' => [ NAME_FIRST => 'Bryan', NAME_LAST => 'Lee'],
  'CZvanDeursen' => [ NAME_INITIALS => 'C. Z.', NAME_PARTICLES => 'van', NAME_LAST => 'Deursen'],
  'CarlosAlberto' => [ NAME_FIRST => 'Carlos Alberto'],
  'CarmelBailey' => [ NAME_FIRST => 'Carmel', NAME_LAST => 'Bailey'],
  'CarolB' => [ NAME_FIRST => 'Carol', NAME_INITIALS => 'B.'],
  'CarolDevitt' => [ NAME_FIRST => 'Carol', NAME_LAST => 'Devitt'],
  'CarolPicot' => [ NAME_FIRST => 'Carol', NAME_LAST => 'Picot'],
  'CasjB' => [ NAME_FIRST => 'Casj', NAME_INITIALS => 'B.'],
  'CeciStone' => [ NAME_FIRST => 'Ceci', NAME_LAST => 'Stone'],
  'CharlesPasco' => [ NAME_FIRST => 'Charles', NAME_LAST => 'Pasco'],
  'CharlieC' => [ NAME_FIRST => 'Charlie', NAME_INITIALS => 'C.'],
  'CharlotteT' => [ NAME_FIRST => 'Charlotte', NAME_INITIALS => 'T.'],
  'CharlotteWolfe' => [ NAME_FIRST => 'Charlotte', NAME_LAST => 'Wolfe'],
  'ChiaraAngela' => [ NAME_FIRST => 'Chiara Angela'],
  'ChrisWols' => [ NAME_FIRST => 'Chris', NAME_LAST => 'Wols'],
  'ChristinaEagan' => [ NAME_FIRST => 'Christina', NAME_LAST => 'Eagan'],
  'ChristinaGustavsson' => [ NAME_FIRST => 'Christina', NAME_LAST => 'Gustavsson'],
  'ChuckStaben' => [ NAME_FIRST => 'Chuck', NAME_LAST => 'Staben'],
  'ClarissaO' => [ NAME_FIRST => 'Clarissa', NAME_INITIALS => 'O.'],
  'ClaudeLeboeuf' => [ NAME_FIRST => 'Claude', NAME_LAST => 'Leboeuf'],
  'ClaudeRousseau' => [ NAME_FIRST => 'Claude', NAME_LAST => 'Rousseau'],
  'ClaudiaHansen' => [ NAME_FIRST => 'Claudia', NAME_LAST => 'Hansen'],
  'CraigJones' => [ NAME_FIRST => 'Craig', NAME_LAST => 'Jones'],
  'DTomTrottier' => [ NAME_INITIALS => 'D.', NAME_FIRST => 'Tom', NAME_LAST => 'Trottier'],
  'DaisyKenedi' => [ NAME_FIRST => 'Daisy', NAME_LAST => 'Kenedi'],
  'DanHu' => [ NAME_FIRST => 'Dan', NAME_LAST => 'Hu'],
  'DanStoica' => [ NAME_FIRST => 'Dan', NAME_LAST => 'Stoica'],
  'DarkoSeremet' => [ NAME_FIRST => 'Darko', NAME_LAST => 'Seremet'],
  'DateMasamune' => [ NAME_FIRST => 'Date', NAME_LAST => 'Masamune'],
  'DaveGermaine' => [ NAME_FIRST => 'Dave', NAME_LAST => 'Germaine'],
  'DeanAdams' => [ NAME_FIRST => 'Dean', NAME_LAST => 'Adams'],
  'DeboraCampagnanoDomenech' => [ NAME_FIRST => 'Debora', NAME_LAST => 'Campagnano Domenech'],
  'DeeMiller' => [ NAME_FIRST => 'Dee', NAME_LAST => 'Miller'],
  'DennyHsu' => [ NAME_FIRST => 'Denny', NAME_LAST => 'Hsu'],
  'DennyP' => [ NAME_FIRST => 'Denny', NAME_INITIALS => 'P.'],
  'DeshpandeChandrashekharP' => [ NAME_FIRST => 'Deshpande Chandrashekhar', NAME_INITIALS => 'P.'],
  'DianeHanoski' => [ NAME_FIRST => 'Diane', NAME_LAST => 'Hanoski'],
  'DianeHyppa' => [ NAME_FIRST => 'Diane', NAME_LAST => 'Hyppa'],
  'DickdeJoode' => [ NAME_FIRST => 'Dick', NAME_PARTICLES => 'de', NAME_LAST => 'Joode'],
  'DirekDEFOS' => [ NAME_FIRST => 'Direk', NAME_LAST => 'Defos'],
  'DirenGeziParki' => [ NAME_FIRST => 'Diren Gezi', NAME_LAST => 'Parki'],
  'DirenKOBANE' => [ NAME_FIRST => 'Diren', NAME_LAST => 'Kobane'],
  'DirkJan' => [ NAME_FIRST => 'Dirk Jan'],
  'DirkJens' => [ NAME_FIRST => 'Dirk Jens'],
  'DoloresSwale' => [ NAME_FIRST => 'Dolores', NAME_LAST => 'Swale'],
  'DonHer' => [ NAME_FIRST => 'Don', NAME_LAST => 'Her'],
  'DonK' => [ NAME_FIRST => 'Don', NAME_INITIALS => 'K.'],
  'DonLorvig' => [ NAME_FIRST => 'Don', NAME_LAST => 'Lorvig'],
  'DonQ' => [ NAME_FIRST => 'Don', NAME_INITIALS => 'Q.'],
  'DongBowen' => [ NAME_FIRST => 'Dong', NAME_LAST => 'Bowen'],
  'DonnaPerron' => [ NAME_FIRST => 'Donna', NAME_LAST => 'Perron'],
  'DorisMcGinnis' => [ NAME_FIRST => 'Doris', NAME_LAST => 'McGinnis'],
  'EddyHaskel' => [ NAME_FIRST => 'Eddy', NAME_LAST => 'Haskel'],
  'EdithChang' => [ NAME_FIRST => 'Edith', NAME_LAST => 'Chang'],
  'EdnaMae' => [ NAME_FIRST => 'Edna Mae'],
  'EdwardFaicco' => [ NAME_FIRST => 'Edward', NAME_LAST => 'Faicco'],
  'EfkanOrman' => [ NAME_FIRST => 'Efkan', NAME_LAST => 'Orman'],
  'EgniNetoob' => [ NAME_FIRST => 'Egni', NAME_LAST => 'Netoob'],
  'EijiNohara' => [ NAME_FIRST => 'Eiji', NAME_LAST => 'Nohara'],
  'EleanorCannon' => [ NAME_FIRST => 'Eleanor', NAME_LAST => 'Cannon'],
  'ElieJones' => [ NAME_FIRST => 'Elie', NAME_LAST => 'Jones'],
  'ElkeS' => [ NAME_FIRST => 'Elke', NAME_INITIALS => 'S.'],
  'ElkeSt' => [ NAME_FIRST => 'Elke'],
  'ElkeWeber' => [ NAME_FIRST => 'Elke', NAME_LAST => 'Weber'],
  'EllaGerner' => [ NAME_FIRST => 'Ella', NAME_LAST => 'Gerner'],
  'EllySU' => [ NAME_FIRST => 'Elly', NAME_LAST => 'SU'],
  'ElsMarie' => [ NAME_FIRST => 'Els Marie'],
  'EmilioRamirez' => [ NAME_FIRST => 'Emilio', NAME_LAST => 'Ramirez'],
  'EmilyYoung' => [ NAME_FIRST => 'Emily', NAME_LAST => 'Young'],
  'EmmyBem' => [ NAME_FIRST => 'Emmy', NAME_LAST => 'Bem'],
  'ErdekEkinKitabevi' => [ NAME_FIRST => 'Erdek Ekin', NAME_LAST => 'Kitabevi'],
  'ErikR' => [ NAME_FIRST => 'Erik', NAME_INITIALS => 'R.'],
  'ErkanKarul' => [ NAME_FIRST => 'Erkan', NAME_LAST => 'Karul'],
  'EspenL' => [ NAME_FIRST => 'Espen', NAME_INITIALS => 'L.'],
  'EstherFabbricante' => [ NAME_FIRST => 'Esther', NAME_LAST => 'Fabbricante'],
  'EverettHixson' => [ NAME_FIRST => 'Everett', NAME_LAST => 'Hixson'],
  'EvgeniG' => [ NAME_FIRST => 'Evgeni', NAME_INITIALS => 'G.'],
  'FitzGerald' => [ NAME_LAST => 'FitzGerald'],
  'FitzGibbon' => [ NAME_LAST => 'FitzGibbon'],
  'FitzSimmons' => [ NAME_LAST => 'FitzSimmons'],
  'FranMacCormack' => [ NAME_FIRST => 'Fran', NAME_LAST => 'MacCormack'],
  'FranWeiner' => [ NAME_FIRST => 'Fran', NAME_LAST => 'Weiner'],
  'FrankHawkins' => [ NAME_FIRST => 'Frank', NAME_LAST => 'Hawkins'],
  'FredIlmoni' => [ NAME_FIRST => 'Fred', NAME_LAST => 'Ilmoni'],
  'FridyTaconis' => [ NAME_FIRST => 'Fridy', NAME_LAST => 'Taconis'],
  'FrinzRich' => [ NAME_FIRST => 'Frinz', NAME_LAST => 'Rich'],
  'GabriaL' => [ NAME_FIRST => 'Gabria', NAME_INITIALS => 'L.'],
  'GailB' => [ NAME_FIRST => 'Gail', NAME_INITIALS => 'B.'],
  'GailMiddleton' => [ NAME_FIRST => 'Gail', NAME_LAST => 'Middleton'],
  'GaryK' => [ NAME_FIRST => 'Gary', NAME_INITIALS => 'K.'],
  'GeoffL' => [ NAME_FIRST => 'Geoff', NAME_INITIALS => 'L.'],
  'GeorgeG' => [ NAME_FIRST => 'George', NAME_INITIALS => 'G.'],
  'GeorgeMcConkey' => [ NAME_FIRST => 'George', NAME_LAST => 'McConkey'],
  'GianCarlo' => [ NAME_FIRST => 'Gian Carlo'],
  'GianPaolo' => [ NAME_FIRST => 'Gian Paolo'],
  'GiseleEmond' => [ NAME_FIRST => 'Gisele', NAME_LAST => 'Emond'],
  'GoroStankov' => [ NAME_FIRST => 'Goro', NAME_LAST => 'Stankov'],
  'GoudSmit' => [ NAME_FIRST => 'Goud', NAME_LAST => 'Smit'],
  'GregKayt' => [ NAME_FIRST => 'Greg', NAME_LAST => 'Kayt'],
  'GregKyr' => [ NAME_FIRST => 'Greg', NAME_LAST => 'Kyr'],
  'GunnarFjalar' => [ NAME_FIRST => 'Gunnar', NAME_LAST => 'Fjalar'],
  'HanneSchmidt' => [ NAME_FIRST => 'Hanne', NAME_LAST => 'Schmidt'],
  'HanniBarckhausen' => [ NAME_FIRST => 'Hanni', NAME_LAST => 'Barckhausen'],
  'HanniFrank' => [ NAME_FIRST => 'Hanni', NAME_LAST => 'Frank'],
  'HansFriedrich' => [ NAME_FIRST => 'Hans', NAME_LAST => 'Friedrich'],
  'HansR' => [ NAME_FIRST => 'Hans', NAME_INITIALS => 'R.'],
  'HansW' => [ NAME_FIRST => 'Hans', NAME_INITIALS => 'W.'],
  'HaroldJacobus' => [ NAME_FIRST => 'Harold', NAME_LAST => 'Jacobus'],
  'HarryL' => [ NAME_FIRST => 'Harry', NAME_INITIALS => 'L.'],
  'HarrySklar' => [ NAME_FIRST => 'Harry', NAME_LAST => 'Sklar'],
  'HarryYang' => [ NAME_FIRST => 'Harry', NAME_LAST => 'Yang'],
  'HattoriHanzo' => [ NAME_FIRST => 'Hattori', NAME_LAST => 'Hanzo'],
  'HedyZ' => [ NAME_FIRST => 'Hedy', NAME_INITIALS => 'Z.'],
  'HeidiLapointe' => [ NAME_FIRST => 'Heidi', NAME_LAST => 'Lapointe'],
  'HelenDSmith' => [ NAME_FIRST => 'Helen', NAME_INITIALS => 'D.', NAME_LAST => 'Smith'],
  'HelenLewis' => [ NAME_FIRST => 'Helen', NAME_LAST => 'Lewis'],
  'HelenToth' => [ NAME_FIRST => 'Helen', NAME_LAST => 'Toth'],
  'HelgeWold' => [ NAME_FIRST => 'Helge', NAME_LAST => 'Wold'],
  'HenkReumkens' => [ NAME_FIRST => 'Henk', NAME_LAST => 'Reumkens'],
  'HenkS' => [ NAME_FIRST => 'Henk', NAME_INITIALS => 'S.'],
  'HenriFranc' => [ NAME_FIRST => 'Henri', NAME_LAST => 'Franc'],
  'HerMawan' => [ NAME_FIRST => 'Her', NAME_LAST => 'Mawan'],
  'HilmarKristensen' => [ NAME_FIRST => 'Hilmar', NAME_LAST => 'Kristensen'],
  'HiroseSumire' => [ NAME_FIRST => 'Hirose', NAME_LAST => 'Sumire'],
  'HvanEijk' => [ NAME_INITIALS => 'H.', NAME_PARTICLES => 'van', NAME_LAST => 'Eijk'],
  'IanJW' => [ NAME_FIRST => 'Ian', NAME_INITIALS => 'J. W.'],
  'IdaLaReau' => [ NAME_FIRST => 'Ida', NAME_LAST => 'LaReau'],
  'IlseG' => [ NAME_FIRST => 'Ilse', NAME_INITIALS => 'G.'],
  'IrekSaturski' => [ NAME_FIRST => 'Irek', NAME_LAST => 'Saturski'],
  'IreneThoerig' => [ NAME_FIRST => 'Irene', NAME_LAST => 'Thoerig'],
  'IrmaKoot' => [ NAME_FIRST => 'Irma', NAME_LAST => 'Koot'],
  'IsaSmith' => [ NAME_FIRST => 'Isa', NAME_LAST => 'Smith'],
  'JBabsG' => [ NAME_FIRST => 'J. Babs', NAME_INITIALS => 'G.'],
  'JGabrialAde' => [ NAME_INITIALS => 'J.', NAME_FIRST => 'Gabrial', NAME_LAST => 'Ade'],
  'JaapLagcher' => [ NAME_FIRST => 'Jaap', NAME_LAST => 'Lagcher'],
  'JacTimmermans' => [ NAME_FIRST => 'Jac', NAME_LAST => 'Timmermans'],
  'JackColson' => [ NAME_FIRST => 'Jack', NAME_LAST => 'Colson'],
  'JackomWalz' => [ NAME_FIRST => 'Jackom', NAME_LAST => 'Walz'],
  'JacquesBrandt' => [ NAME_FIRST => 'Jacques', NAME_LAST => 'Brandt'],
  'JamesBowman' => [ NAME_FIRST => 'James', NAME_LAST => 'Bowman'],
  'JanEric' => [ NAME_FIRST => 'Jan Eric'],
  'JanJenkins' => [ NAME_FIRST => 'Jan', NAME_LAST => 'Jenkins'],
  'JanS' => [ NAME_FIRST => 'Jan', NAME_INITIALS => 'S.'],
  'JanT' => [ NAME_FIRST => 'Jan', NAME_INITIALS => 'T.'],
  'JanTijsen' => [ NAME_FIRST => 'Jan', NAME_LAST => 'Tijsen'],
  'JandeF' => [ NAME_FIRST => 'Jan', NAME_PARTICLES => 'de', NAME_INITIALS => 'F.'],
  'JaneA' => [ NAME_FIRST => 'Jane', NAME_INITIALS => 'A.'],
  'JaneAnn' => [ NAME_FIRST => 'Jane Ann'],
  'JaneS' => [ NAME_FIRST => 'Jane', NAME_INITIALS => 'S.'],
  'JanetRose' => [ NAME_FIRST => 'Janet Rose'],
  'JaniceTalada' => [ NAME_FIRST => 'Janice', NAME_LAST => 'Talada'],
  'JanuszC' => [ NAME_FIRST => 'Janusz', NAME_INITIALS => 'C.'],
  'JanuszR' => [ NAME_FIRST => 'Janusz', NAME_INITIALS => 'R.'],
  'JarleP' => [ NAME_FIRST => 'Jarle', NAME_INITIALS => 'P.'],
  'JasLai' => [ NAME_FIRST => 'Jas', NAME_LAST => 'Lai'],
  'JasonYip' => [ NAME_FIRST => 'Jason', NAME_LAST => 'Yip'],
  'JayKrich' => [ NAME_FIRST => 'Jay', NAME_LAST => 'Krich'],
  'JeanB' => [ NAME_FIRST => 'Jean', NAME_INITIALS => 'B.'],
  'JeanClaude' => [ NAME_FIRST => 'Jean Claude'],
  'JeanPaul' => [ NAME_FIRST => 'Jean Paul'],
  'JenHatcher' => [ NAME_FIRST => 'Jen', NAME_LAST => 'Hatcher'],
  'JeriR' => [ NAME_FIRST => 'Jeri', NAME_INITIALS => 'R.'],
  'JerryLin' => [ NAME_FIRST => 'Jerry', NAME_LAST => 'Lin'],
  'JerryPeterson' => [ NAME_FIRST => 'Jerry', NAME_LAST => 'Peterson'],
  'JerryS' => [ NAME_FIRST => 'Jerry', NAME_INITIALS => 'S.'],
  'JimBartko' => [ NAME_FIRST => 'Jim', NAME_LAST => 'Bartko'],
  'JimBull' => [ NAME_FIRST => 'Jim', NAME_LAST => 'Bull'],
  'JimGe' => [ NAME_FIRST => 'Jim', NAME_LAST => 'Ge'],
  'JimGero' => [ NAME_FIRST => 'Jim', NAME_LAST => 'Gero'],
  'JimMcKinney' => [ NAME_FIRST => 'Jim', NAME_LAST => 'McKinney'],
  'JimmyLedger' => [ NAME_FIRST => 'Jimmy', NAME_LAST => 'Ledger'],
  'JoanLeroux' => [ NAME_FIRST => 'Joan', NAME_LAST => 'Leroux'],
  'JoannaTytko' => [ NAME_FIRST => 'Joanna', NAME_LAST => 'Tytko'],
  'JoeAlex' => [ NAME_FIRST => 'Joe Alex'],
  'JoeYork' => [ NAME_FIRST => 'Joe', NAME_LAST => 'York'],
  'JohanneG' => [ NAME_FIRST => 'Johanne', NAME_INITIALS => 'G.'],
  'JohnAsim' => [ NAME_FIRST => 'John', NAME_LAST => 'Asim'],
  'JohnB' => [ NAME_FIRST => 'John', NAME_INITIALS => 'B.'],
  'JohnBrown' => [ NAME_FIRST => 'John', NAME_LAST => 'Brown'],
  'JohnDeYoe' => [ NAME_FIRST => 'John', NAME_PARTICLES => 'de', NAME_LAST => 'Yoe'],
  'JohnJim' => [ NAME_FIRST => 'John Jim'],
  'JonesHinton' => [ NAME_FIRST => 'Jones', NAME_LAST => 'Hinton'],
  'JosV' => [ NAME_FIRST => 'Jos', NAME_INITIALS => 'V.'],
  'JoseArcadio' => [ NAME_FIRST => 'Jose', NAME_LAST => 'Arcadio'],
  'JoseMelo' => [ NAME_FIRST => 'Jose', NAME_LAST => 'Melo'],
  'JosefP' => [ NAME_FIRST => 'Josef', NAME_INITIALS => 'P.'],
  'JuanEmilio' => [ NAME_FIRST => 'Juan Emilio'],
  'JuanaM' => [ NAME_FIRST => 'Juana', NAME_INITIALS => 'M.'],
  'JudiAnne' => [ NAME_FIRST => 'Judi Anne'],
  'JudyGeralds' => [ NAME_FIRST => 'Judy', NAME_LAST => 'Geralds'],
  'JudyJohnson' => [ NAME_FIRST => 'Judy', NAME_LAST => 'Johnson'],
  'JudyLion' => [ NAME_FIRST => 'Judy', NAME_LAST => 'Lion'],
  'JulieAnn' => [ NAME_FIRST => 'Julie Ann'],
  'JulieJean' => [ NAME_FIRST => 'Julie Jean'],
  'JulietYi' => [ NAME_FIRST => 'Juliet', NAME_LAST => 'Yi'],
  'JulietteVenard' => [ NAME_FIRST => 'Juliette', NAME_LAST => 'Venard'],
  'JuneEvans' => [ NAME_FIRST => 'June', NAME_LAST => 'Evans'],
  'KarelNab' => [ NAME_FIRST => 'Karel', NAME_LAST => 'Nab'],
  'KarenPerling' => [ NAME_FIRST => 'Karen', NAME_LAST => 'Perling'],
  'KarimG' => [ NAME_FIRST => 'Karim', NAME_INITIALS => 'G.'],
  'KarlJohan' => [ NAME_FIRST => 'Karl Johan'],
  'KathRowan' => [ NAME_FIRST => 'Kath', NAME_LAST => 'Rowan'],
  'KatherineK' => [ NAME_FIRST => 'Katherine', NAME_INITIALS => 'K.'],
  'KathleenFergus' => [ NAME_FIRST => 'Kathleen', NAME_LAST => 'Fergus'],
  'KathyLockhart' => [ NAME_FIRST => 'Kathy', NAME_LAST => 'Lockhart'],
  'KeesvanDijk' => [ NAME_FIRST => 'Kees', NAME_PARTICLES => 'van', NAME_LAST => 'Dijk'],
  'KjellH' => [ NAME_FIRST => 'Kjell', NAME_INITIALS => 'H.'],
  'KjellTore' => [ NAME_FIRST => 'Kjell Tore'],
  'KylieAnn' => [ NAME_FIRST => 'Kylie Ann'],
  'LarraineBallstadt' => [ NAME_FIRST => 'Larraine', NAME_LAST => 'Ballstadt'],
  'LarryKing' => [ NAME_FIRST => 'Larry', NAME_LAST => 'King'],
  'LarsGrevang' => [ NAME_FIRST => 'Lars', NAME_LAST => 'Grevang'],
  'LauraLee' => [ NAME_FIRST => 'Laura Lee'],
  'LaureB' => [ NAME_FIRST => 'Laure', NAME_INITIALS => 'B.'],
  'LeAnnMyers' => [ NAME_FIRST => 'Le Ann', NAME_LAST => 'Myers'],
  'LeeZoya' => [ NAME_FIRST => 'Lee', NAME_LAST => 'Zoya'],
  'LesleeT' => [ NAME_FIRST => 'Leslee', NAME_INITIALS => 'T.'],
  'LesleyMelton' => [ NAME_FIRST => 'Lesley', NAME_LAST => 'Melton'],
  'LinaG' => [ NAME_FIRST => 'Lina', NAME_INITIALS => 'G.'],
  'LindaBerg' => [ NAME_FIRST => 'Linda', NAME_LAST => 'Berg'],
  'LindaForeman' => [ NAME_FIRST => 'Linda', NAME_LAST => 'Foreman'],
  'LinnAurora' => [ NAME_FIRST => 'Linn Aurora'],
  'LiseCaron' => [ NAME_FIRST => 'Lise', NAME_LAST => 'Caron'],
  'LiseMontmarquette' => [ NAME_FIRST => 'Lise', NAME_LAST => 'Montmarquette'],
  'LizAnn' => [ NAME_FIRST => 'Liz Ann'],
  'LoisPresser' => [ NAME_FIRST => 'Lois', NAME_LAST => 'Presser'],
  'LoisWitt' => [ NAME_FIRST => 'Lois', NAME_LAST => 'Witt'],
  'LoiuiseGentry' => [ NAME_FIRST => 'Loiuise', NAME_LAST => 'Gentry'],
  'LouAnn' => [ NAME_FIRST => 'Lou Ann'],
  'LouJones' => [ NAME_FIRST => 'Lou', NAME_LAST => 'Jones'],
  'LouiseMarie' => [ NAME_FIRST => 'Louise Marie'],
  'LoureiroCosta' => [ NAME_FIRST => 'Loureiro', NAME_LAST => 'Costa'],
  'LucJ' => [ NAME_FIRST => 'Luc', NAME_INITIALS => 'J.'],
  'LucianoC' => [ NAME_FIRST => 'Luciano', NAME_INITIALS => 'C.'],
  'LucilleFortin' => [ NAME_FIRST => 'Lucille', NAME_LAST => 'Fortin'],
  'LynetteMurray' => [ NAME_FIRST => 'Lynette', NAME_LAST => 'Murray'],
  'LynnBurchett' => [ NAME_FIRST => 'Lynn', NAME_LAST => 'Burchett'],
  'MabelAnnaAnderson' => [ NAME_FIRST => 'Mabel Anna', NAME_LAST => 'Anderson'],
  'MacAlister' => [ NAME_LAST => 'MacAlister'],
  'MacCabe' => [ NAME_LAST => 'MacCabe'],
  'MacCallum' => [ NAME_LAST => 'MacCallum'],
  'MacCormick' => [ NAME_LAST => 'MacCormick'],
  'MacDonagh' => [ NAME_LAST => 'MacDonagh'],
  'MacDonald' => [ NAME_LAST => 'MacDonald'],
  'MacDougall' => [ NAME_LAST => 'MacDougall'],
  'MacDowell' => [ NAME_LAST => 'MacDowell'],
  'MacEacbern' => [ NAME_LAST => 'MacEacbern'],
  'MacEachern' => [ NAME_LAST => 'MacEachern'],
  'MacFadden' => [ NAME_LAST => 'MacFadden'],
  'MacGregor' => [ NAME_LAST => 'MacGregor'],
  'MacInnis' => [ NAME_LAST => 'MacInnis'],
  'MacIntyre' => [ NAME_LAST => 'MacIntyre'],
  'MacKay' => [ NAME_LAST => 'MacKay'],
  'MacKenrod' => [ NAME_LAST => 'MacKenrod'],
  'MacKenzie' => [ NAME_LAST => 'MacKenzie'],
  'MacKinnon' => [ NAME_LAST => 'MacKinnon'],
  'MacLaren' => [ NAME_LAST => 'MacLaren'],
  'MacLean' => [ NAME_LAST => 'MacLean'],
  'MacLeod' => [ NAME_LAST => 'MacLeod'],
  'MacMillan' => [ NAME_LAST => 'MacMillan'],
  'MacNeal' => [ NAME_LAST => 'MacNeal'],
  'MacNeil' => [ NAME_LAST => 'MacNeil'],
  'MacNutt' => [ NAME_LAST => 'MacNutt'],
  'MacPhail' => [ NAME_LAST => 'MacPhail'],
  'MacRae' => [ NAME_LAST => 'MacRae'],
  'MacRitchie' => [ NAME_LAST => 'MacRitchie'],
  'MacShane' => [ NAME_LAST => 'MacShane'],
  'MaeyEllenLutz' => [ NAME_FIRST => 'Maey Ellen', NAME_LAST => 'Lutz'],
  'MaggyW' => [ NAME_FIRST => 'Maggy', NAME_INITIALS => 'W.'],
  'MajBritt' => [ NAME_FIRST => 'Maj Britt'],
  'MarcelleMersereau' => [ NAME_FIRST => 'Marcelle', NAME_LAST => 'Mersereau'],
  'MarciaGahring' => [ NAME_FIRST => 'Marcia', NAME_LAST => 'Gahring'],
  'MarcinW' => [ NAME_FIRST => 'Marcin', NAME_INITIALS => 'W.'],
  'MarcinWiacek' => [ NAME_FIRST => 'Marcin', NAME_LAST => 'Wiacek'],
  'MargaretQuigley' => [ NAME_FIRST => 'Margaret', NAME_LAST => 'Quigley'],
  'MargaretaE' => [ NAME_FIRST => 'Margareta', NAME_INITIALS => 'E.'],
  'MargeTownsend' => [ NAME_FIRST => 'Marge', NAME_LAST => 'Townsend'],
  'MargitPedersen' => [ NAME_FIRST => 'Margit', NAME_LAST => 'Pedersen'],
  'MariCarmen' => [ NAME_FIRST => 'Mari Carmen'],
  'MariaAndonova' => [ NAME_FIRST => 'Maria', NAME_LAST => 'Andonova'],
  'MariaChen' => [ NAME_FIRST => 'Maria', NAME_LAST => 'Chen'],
  'MariaEugenia' => [ NAME_FIRST => 'Maria Eugenia'],
  'MariaGrazia' => [ NAME_FIRST => 'Maria Grazia'],
  'MariaJ' => [ NAME_FIRST => 'Maria', NAME_INITIALS => 'J.'],
  'MariaN' => [ NAME_FIRST => 'Maria', NAME_INITIALS => 'N.'],
  'MarieAnne' => [ NAME_FIRST => 'Marie Anne'],
  'MarieSybill' => [ NAME_FIRST => 'Marie Sybill'],
  'MarilynC' => [ NAME_FIRST => 'Marilyn', NAME_INITIALS => 'C.'],
  'MarilynKieffer' => [ NAME_FIRST => 'Marilyn', NAME_LAST => 'Kieffer'],
  'MarisR' => [ NAME_FIRST => 'Maris', NAME_INITIALS => 'R.'],
  'MariuszO' => [ NAME_FIRST => 'Mariusz', NAME_INITIALS => 'O.'],
  'MarkKellett' => [ NAME_FIRST => 'Mark', NAME_LAST => 'Kellett'],
  'MarkM' => [ NAME_FIRST => 'Mark', NAME_INITIALS => 'M.'],
  'MartaA' => [ NAME_FIRST => 'Marta', NAME_INITIALS => 'A.'],
  'MarthaBelle' => [ NAME_FIRST => 'Martha Belle'],
  'MaryAnn' => [ NAME_FIRST => 'Mary Ann'],
  'MaryAnne' => [ NAME_FIRST => 'Mary Anne'],
  'MaryBeth' => [ NAME_FIRST => 'Mary Beth'],
  'MaryBrown' => [ NAME_FIRST => 'Mary', NAME_LAST => 'Brown'],
  'MaryEllen' => [ NAME_FIRST => 'Mary Ellen'],
  'MaryEllenFranzoni' => [ NAME_FIRST => 'Mary Ellen', NAME_LAST => 'Franzoni'],
  'MaryJo' => [ NAME_FIRST => 'Mary Jo'],
  'MaryLau' => [ NAME_FIRST => 'Mary Lau'],
  'MaryLee' => [ NAME_FIRST => 'Mary Lee'],
  'MaryLou' => [ NAME_FIRST => 'Mary Lou'],
  'MaryO\'Kelly' => [ NAME_FIRST => 'Mary', NAME_LAST => 'O\'Kelly'],
  'MarylouMarlow' => [ NAME_FIRST => 'Marylou', NAME_LAST => 'Marlow'],
  'MurieL' => [ NAME_FIRST => 'Murie', NAME_INITIALS => 'L.'],
  'MustafaAcar' => [ NAME_FIRST => 'Mustafa', NAME_LAST => 'Acar'],
  'NareshKapila' => [ NAME_FIRST => 'Naresh', NAME_LAST => 'Kapila'],
  'NeomiFriedman' => [ NAME_FIRST => 'Neomi', NAME_LAST => 'Friedman'],
  'NicolettaB' => [ NAME_FIRST => 'Nicoletta', NAME_INITIALS => 'B.'],
  'NihatEkinci' => [ NAME_FIRST => 'Nihat', NAME_LAST => 'Ekinci'],
  'NormaRollins' => [ NAME_FIRST => 'Norma', NAME_LAST => 'Rollins'],
  'OleJensen' => [ NAME_FIRST => 'Ole', NAME_LAST => 'Jensen'],
  'OpalJoyce' => [ NAME_FIRST => 'Opal', NAME_LAST => 'Joyce'],
  'OsmanCavit' => [ NAME_FIRST => 'Osman', NAME_LAST => 'Cavit'],
  'PaddyLee' => [ NAME_FIRST => 'Paddy', NAME_LAST => 'Lee'],
  'PatricPilet' => [ NAME_FIRST => 'Patric', NAME_LAST => 'Pilet'],
  'PatriciaJBarnett' => [ NAME_FIRST => 'Patricia', NAME_INITIALS => 'J.', NAME_LAST => 'Barnett'],
  'PatrickS' => [ NAME_FIRST => 'Patrick', NAME_INITIALS => 'S.'],
  'PaulRBartron' => [ NAME_FIRST => 'Paul', NAME_INITIALS => 'R.', NAME_LAST => 'Bartron'],
  'PaulineLefkada' => [ NAME_FIRST => 'Pauline', NAME_LAST => 'Lefkada'],
  'PerryShriner' => [ NAME_FIRST => 'Perry', NAME_LAST => 'Shriner'],
  'PerryShrineron' => [ NAME_FIRST => 'Perry', NAME_LAST => 'Shriner'],
  'PeterC' => [ NAME_FIRST => 'Peter', NAME_INITIALS => 'C.'],
  'PierSerafina' => [ NAME_FIRST => 'Pier', NAME_LAST => 'Serafina'],
  'RArrigoFranchi' => [ NAME_FIRST => 'R. Arrigo', NAME_LAST => 'Franchi'],
  'RannaRuutu' => [ NAME_FIRST => 'Ranna', NAME_LAST => 'Ruutu'],
  'RashidRaman' => [ NAME_FIRST => 'Rashid', NAME_LAST => 'Raman'],
  'RayHart' => [ NAME_FIRST => 'Ray', NAME_LAST => 'Hart'],
  'RayYung' => [ NAME_FIRST => 'Ray', NAME_LAST => 'Yung'],
  'RaymodChen' => [ NAME_FIRST => 'Raymond', NAME_LAST => 'Chen'],
  'RichardL' => [ NAME_FIRST => 'Richard', NAME_INITIALS => 'L.'],
  'RichardMortara' => [ NAME_FIRST => 'Richard', NAME_LAST => 'Mortara'],
  'RobertMcCall' => [ NAME_FIRST => 'Robert', NAME_LAST => 'McCall'],
  'RogerHolm' => [ NAME_FIRST => 'Roger', NAME_LAST => 'Holm'],
  'RogerPennell' => [ NAME_FIRST => 'Roger', NAME_LAST => 'Pennell'],
  'RonFrost' => [ NAME_FIRST => 'Ron', NAME_LAST => 'Frost'],
  'RonKolkman' => [ NAME_FIRST => 'Ron', NAME_LAST => 'Kolkman'],
  'RonnieHorowitz' => [ NAME_FIRST => 'Ronnie', NAME_LAST => 'Horowitz'],
  'RosaLee' => [ NAME_FIRST => 'Rosa Lee'],
  'RoseAnne' => [ NAME_FIRST => 'Rose Anne'],
  'RoseMarie' => [ NAME_FIRST => 'Rose Marie'],
  'RuthAllen' => [ NAME_FIRST => 'Ruth Allen'],
  'RuthHamstra' => [ NAME_FIRST => 'Ruth', NAME_LAST => 'Hamstra'],
  'RyanChen' => [ NAME_FIRST => 'Ryan', NAME_LAST => 'Chen'],
  'RydenHolmqvist' => [ NAME_FIRST => 'Ryden', NAME_LAST => 'Holmqvist'],
  'SallyL' => [ NAME_FIRST => 'Sally', NAME_INITIALS => 'L.'],
  'SanKulPune' => [ NAME_FIRST => 'San Kul', NAME_LAST => 'Pune'],
  'SandyRee' => [ NAME_FIRST => 'Sandy', NAME_LAST => 'Ree'],
  'SaraB' => [ NAME_FIRST => 'Sara', NAME_INITIALS => 'B.'],
  'SaraK' => [ NAME_FIRST => 'Sara', NAME_INITIALS => 'K.'],
  'SharonSwartzman' => [ NAME_FIRST => 'Sharon', NAME_LAST => 'Swartzman'],
  'SheilaBegg' => [ NAME_FIRST => 'Sheila', NAME_LAST => 'Begg'],
  'SlvanaCaramanno' => [ NAME_FIRST => 'Slvana', NAME_LAST => 'Caramanno'],
  'SolveigFolkeryd' => [ NAME_FIRST => 'Solveig', NAME_LAST => 'Folkeryd'],
  'SreeKumar' => [ NAME_FIRST => 'Sree', NAME_LAST => 'Kumar'],
  'StigHjalmar' => [ NAME_FIRST => 'Stig Hjalmar'],
  'SueCorley' => [ NAME_FIRST => 'Sue', NAME_LAST => 'Corley'],
  'SueSmith' => [ NAME_FIRST => 'Sue', NAME_LAST => 'Smith'],
  'SusanMeyer' => [ NAME_FIRST => 'Susan', NAME_LAST => 'Meyer'],
  'SusannaReisch' => [ NAME_FIRST => 'Susanna', NAME_LAST => 'Reisch'],
  'SusanneBjerrum' => [ NAME_FIRST => 'Susanne', NAME_LAST => 'Bjerrum'],
  'SusieF' => [ NAME_FIRST => 'Susie', NAME_INITIALS => 'F.'],
  'SuziA' => [ NAME_FIRST => 'Suzi', NAME_INITIALS => 'A.'],
  'SverrirThorisson' => [ NAME_FIRST => 'Sverrir', NAME_LAST => 'Thorisson'],
  'SylvieB' => [ NAME_FIRST => 'Sylvie', NAME_INITIALS => 'B.'],
  'TillyBarella' => [ NAME_FIRST => 'Tilly', NAME_LAST => 'Barella'],
  'TodorNedelchev' => [ NAME_FIRST => 'Todor', NAME_LAST => 'Nedelchev'],
  'TorbenSLind' => [ NAME_FIRST => 'Torben', NAME_INITIALS => 'S.', NAME_LAST => 'Lind'],
  'TrishSmith' => [ NAME_FIRST => 'Trish', NAME_LAST => 'Smith'],
  'UllaBritt' => [ NAME_FIRST => 'Ulla Britt'],
  'UllaGrundel' => [ NAME_FIRST => 'Ulla', NAME_LAST => 'Grundel'],
  'ValerieGamio' => [ NAME_FIRST => 'Valerie', NAME_LAST => 'Gamio'],
  'VanDyke' => [ NAME_PARTICLES => 'van', NAME_LAST => 'Dyke'],
  'VanHatten' => [ NAME_PARTICLES => 'Van', NAME_LAST => 'Hatten'],
  'VanOchten' => [ NAME_PARTICLES => 'Van', NAME_LAST => 'Ochten'],
  'VanOs' => [ NAME_PARTICLES => 'Van', NAME_LAST => 'Os'],
  'VanVreede' => [ NAME_PARTICLES => 'Van', NAME_LAST => 'Vreede'],
  'VasilCholakov' => [ NAME_FIRST => 'Vasil', NAME_LAST => 'Cholakov'],
  'WalterKerr' => [ NAME_FIRST => 'Walter', NAME_LAST => 'Kerr'],
  'WilliamJ' => [ NAME_FIRST => 'William', NAME_INITIALS => 'J.'],
  'WilliamR' => [ NAME_FIRST => 'William', NAME_INITIALS => 'R.'],
  'WojciechJablonski' => [ NAME_FIRST => 'Wojciech', NAME_LAST => 'Jablonski'],
  'WojciechW' => [ NAME_FIRST => 'Wojciech', NAME_INITIALS => 'W.'],
  'YasinHACIMUSALAR' => [ NAME_FIRST => 'Yasin', NAME_LAST => 'Hacimusalar'],
  'YngveN' => [ NAME_FIRST => 'Yngve', NAME_INITIALS => 'N.'],
  'YohanesR' => [ NAME_FIRST => 'Yohanes', NAME_INITIALS => 'R.'],
  'YucelTuzcuoglu' => [ NAME_FIRST => 'Yucel', NAME_LAST => 'Tuzcuoglu'],
  'YvonneMarjan' => [ NAME_FIRST => 'Yvonne', NAME_LAST => 'Marjan'],
  'jacobKkarni' => [ NAME_FIRST => 'Jacob', NAME_FIRST => 'Kkarni'],
  'jacquelineBeauchemin' => [ NAME_FIRST => 'Jacqueline', NAME_LAST => 'Beauchemin'],
  'janekROTARSKI' => [ NAME_FIRST => 'Janek', NAME_LAST => 'Rotarski'],
  'kathrynB' => [ NAME_FIRST => 'Kathryn', NAME_INITIALS => 'B.'],
  'HortLill' => [ NAME_FIRST => 'Hort', NAME_LAST => 'Lill'],
  'WilliamLou' => [ NAME_FIRST => 'William Lou'],
  'AndersonDuplit' => [ NAME_FIRST => 'Anderson', NAME_LAST => 'Duplit'],
  'ChadKimberly' => [ NAME_FIRST => 'Chad Kimberly'],
  'JUNzhANG' => [ NAME_FIRST => 'Jun', NAME_LAST => 'Zhang'],
  'ZhangFeng' => [ NAME_FIRST => 'Feng', NAME_LAST => 'Zhang'],
  'WangWei' => [ NAME_FIRST => 'Wei', NAME_LAST => 'Wang'],
  'ChenXi' => [ NAME_FIRST => 'Xi', NAME_LAST => 'Chen'],
  'JoeLiAnta' => [ NAME_FIRST => 'Joe', NAME_LAST => 'LiAnta'],
  'CalveteJaimes' => [ NAME_FIRST => 'Calvete', NAME_LAST => 'Jaimes'],
  'ChandraShekhar' => [ NAME_FIRST => 'Chandra', NAME_LAST => 'Shekhar'],
  'ZhengZhu' => [ NAME_FIRST => 'Zhu', NAME_LAST => 'Zhong'],
  'YimanSong' => [ NAME_FIRST => 'Song', NAME_LAST => 'Yiman'],
  'ZhixiuChangsha' => [ NAME_FIRST => 'Changsha', NAME_LAST => 'Zhixiu'],
  'YingXiang' => [ NAME_FIRST => 'Xiang', NAME_LAST => 'Ying'],
  'BromadJord' => [ NAME_FIRST => 'Bromad', NAME_LAST => 'Jord'],
  'WangWenXue' => [ NAME_FIRST => 'Wen Xue', NAME_LAST => 'Wang'],
  'FuYanMing' => [ NAME_FIRST => 'Yan Ming', NAME_LAST => 'Fu'],
  'HongYunLei' => [ NAME_FIRST => 'Yun Lei', NAME_LAST => 'Hong'],
  'DongLinFeng' => [ NAME_FIRST => 'Lin Feng', NAME_LAST => 'Dong'],
  'LuXueFeng' => [ NAME_FIRST => 'Xue Feng', NAME_LAST => 'Lu'],
  'HuangWenJian' => [ NAME_FIRST => 'Wen Jian', NAME_LAST => 'Huang'],
  'ZhangZhou' => [ NAME_FIRST => 'Zhou', NAME_LAST => 'Zhang'],
  'YongZhi' => [ NAME_FIRST => 'Zhi', NAME_LAST => 'Yong'],
  'WangYun' => [ NAME_FIRST => 'Yun', NAME_LAST => 'Wang'],
  'RajaSekhar' => [ NAME_FIRST => 'Raja', NAME_LAST => 'Sekhar'],
  'LeeYiMing' => [ NAME_FIRST => 'Yi Ming', NAME_LAST => 'Lee'],
  'JianLing' => [ NAME_FIRST => 'Jian', NAME_LAST => 'Ling'],
  'JiangYuchen' => [ NAME_FIRST => 'Yuchen', NAME_LAST => 'Jiang'],
  'JiangYuxin' => [ NAME_FIRST => 'Yuxin', NAME_LAST => 'Jiang'],
  'JinayDhian' => [ NAME_FIRST => 'Dhian', NAME_LAST => 'Jinay'],
  'JingWen' => [ NAME_FIRST => 'Wen', NAME_LAST => 'Jing'],
  'JiunWen' => [ NAME_FIRST => 'Wen', NAME_LAST => 'Jiun'],
  'JiangSY' => [ NAME_INITIALS => 'S. Y.', NAME_LAST => 'Jiang'],
  'JIangSu' => [ NAME_FIRST => 'Su', NAME_LAST => 'Jiang'],
  'GuoZHong' => [ NAME_FIRST => 'Guo', NAME_INITIALS => 'Z.', NAME_LAST => 'Hong'],
  'GaoGuangze' => [ NAME_FIRST => 'Guangze', NAME_LAST => 'Gao'],
  'GaoGuijun' => [ NAME_FIRST => 'Guijun', NAME_LAST => 'Gao'],
  'CaoDinghong' => [ NAME_FIRST => 'Dinghong', NAME_LAST => 'Cao'],
  'ChenRunhua' => [ NAME_FIRST => 'Runhua', NAME_LAST => 'Chen'],
  'ChengYing' => [ NAME_FIRST => 'Ying', NAME_LAST => 'Cheng'],
  'IlmoniFred' => [ NAME_FIRST => 'Fred', NAME_LAST => 'Ilmoni'],
  'HalukV' => [ NAME_FIRST => 'Haluk', NAME_INITIALS => 'V.'],
  'KautsarHilmi' => [ NAME_FIRST => 'Kautsar Hilmi'],
  'CahTlogosari' => [ NAME_FIRST => 'Tlogosari', NAME_LAST => 'Cah'],
  'BaiLing' => [ NAME_FIRST => 'Ling', NAME_LAST => 'Bai'],
  'DemirciogIu' => [ NAME_LAST => 'Demircioglu'],
  'HuaAn' => [ NAME_FIRST => 'An', NAME_LAST => 'Hua'],
  'HuangTu' => [ NAME_FIRST => 'Tu', NAME_LAST => 'Huang'],
  'WeishunTie' => [ NAME_FIRST => 'Weishun', NAME_LAST => 'Tie'],
  'LiZhengWen' => [ NAME_FIRST => 'Wen', NAME_LAST => 'Li Zheng'],
  'KkrzyS' => [ NAME_FIRST => 'Krzysztof', NAME_INITIALS => 'S.'],
  'JunGu' => [ NAME_FIRST => 'Jun', NAME_LAST => 'Gu'],
  'JunJie' => [ NAME_FIRST => 'Jun', NAME_LAST => 'Jie'],
  'JaoZhang' => [ NAME_FIRST => 'Jao', NAME_LAST => 'Zhang'],
  'DingYu' => [ NAME_FIRST => 'Yu', NAME_LAST => 'Ding'],
  'ChunHong' => [ NAME_FIRST => 'Chun', NAME_LAST => 'Hong'],
  'ChangJiang' => [ NAME_FIRST => 'Jiang', NAME_LAST => 'Chang'],
  'GuriAnn' => [ NAME_FIRST => 'Guri Ann'],
  'nicoleL' => [ NAME_FIRST => 'Nicole', NAME_INITIALS => 'L.'],
  'JimSC' => [ NAME_FIRST => 'Jim', NAME_INITIALS => 'S. C.'],
  'BartK' => [ NAME_FIRST => 'Bart', NAME_INITIALS => 'K.'],
  'OliverC' => [ NAME_FIRST => 'Oliver', NAME_INITIALS => 'C.'],
  'TomaszJ' => [ NAME_FIRST => 'Tomasz', NAME_INITIALS => 'J.'],
  'StephHD' => [ NAME_FIRST => 'Steph', NAME_INITIALS => 'H. D.'],
  'JosephT' => [ NAME_FIRST => 'Joseph', NAME_INITIALS => 'T.'],
  'CumhuriyetL' => [ NAME_FIRST => 'Cumhuriyet', NAME_INITIALS => 'L.'],
  'ziutekS' => [ NAME_FIRST => 'Ziutek', NAME_INITIALS => 'S.'],
  'geneK' => [ NAME_FIRST => 'Gene', NAME_INITIALS => 'K.'],
  'WalterB' => [ NAME_FIRST => 'Walter', NAME_INITIALS => 'B.'],
  'TomB' => [ NAME_FIRST => 'Tom', NAME_INITIALS => 'B.'],
  'SauravM' => [ NAME_FIRST => 'Saurav', NAME_INITIALS => 'M.'],
  'LyubomirN' => [ NAME_FIRST => 'Lyubomir', NAME_INITIALS => 'N.'],
  'LouieB' => [ NAME_FIRST => 'Louie', NAME_INITIALS => 'B.'],
  'JudyL' => [ NAME_FIRST => 'Judy', NAME_INITIALS => 'L.'],
  'DonnySL' => [ NAME_FIRST => 'Donny', NAME_INITIALS => 'S. L.'],
  'DanielaB' => [ NAME_FIRST => 'Daniela', NAME_INITIALS => 'B.'],
  'CarolM' => [ NAME_FIRST => 'Carol', NAME_INITIALS => 'M.'],
  'ArntO' => [ NAME_FIRST => 'Arnt', NAME_INITIALS => 'O.'],
  'wangH' => [ NAME_INITIALS => 'H.', NAME_INITIALS => 'Wang'],
  'susanS' => [ NAME_FIRST => 'Susan', NAME_INITIALS => 'S.'],
  'samuelH' => [ NAME_FIRST => 'Samuel', NAME_INITIALS => 'H.'],
  'nowyJ' => [ NAME_INITIALS => 'J.', NAME_LAST => 'Nowy'],
  'maryJ' => [ NAME_FIRST => 'Mary', NAME_INITIALS => 'J.'],
  'lisaA' => [ NAME_FIRST => 'Lisa', NAME_INITIALS => 'A.'],
  'lauraR' => [ NAME_FIRST => 'Laura', NAME_INITIALS => 'R.'],
  'larserikJ' => [ NAME_FIRST => 'Lars Erik', NAME_INITIALS => 'J.'],
  'krzyS' => [ NAME_FIRST => 'Krzysztof', NAME_INITIALS => 'S.'],
  'kismailC' => [ NAME_FIRST => 'Ismail', NAME_INITIALS => 'C.'],
  'jismailC' => [ NAME_FIRST => 'Ismail', NAME_INITIALS => 'C.'],
  'hikmetK' => [ NAME_FIRST => 'Hikmet', NAME_INITIALS => 'K.'],
  'grannyE' => [ NAME_FIRST => 'Granny', NAME_INITIALS => 'E.'],
  'garelG' => [ NAME_FIRST => 'Garel', NAME_INITIALS => 'G.'],
  'daniL' => [ NAME_FIRST => 'Dani', NAME_INITIALS => 'L.'],
  'claudiaU' => [ NAME_FIRST => 'Claudia', NAME_INITIALS => 'U.'],
  'andrzejB' => [ NAME_FIRST => 'Andrzej', NAME_INITIALS => 'B.'],
  'ZeyneL' => [ NAME_FIRST => 'Zeyne', NAME_INITIALS => 'L.'],
  'ZAdaM' => [ NAME_FIRST => 'Adam'],
  'YanZ' => [ NAME_FIRST => 'Yan', NAME_INITIALS => 'Z.'],
  'WAndrzejK' => [ NAME_FIRST => 'Andrzej', NAME_INITIALS => 'K.'],
  'VinayB' => [ NAME_FIRST => 'Vinay', NAME_INITIALS => 'B.'],
  'TuranA' => [ NAME_FIRST => 'Turan', NAME_INITIALS => 'A.'],
  'TomekP' => [ NAME_FIRST => 'Tomek', NAME_INITIALS => 'P.'],
  'ThosaphoL' => [ NAME_FIRST => 'Thosapho', NAME_INITIALS => 'L.'],
  'TerryJ' => [ NAME_FIRST => 'Terry', NAME_INITIALS => 'J.'],
  'TaniaF' => [ NAME_FIRST => 'Tania', NAME_INITIALS => 'F.'],
  'TangXS' => [ NAME_FIRST => 'Tang', NAME_INITIALS => 'X. S.'],
  'TadekP' => [ NAME_FIRST => 'Tadek', NAME_INITIALS => 'P.'],
  'SuzanneS' => [ NAME_FIRST => 'Suzanne', NAME_INITIALS => 'S.'],
  'SteinarN' => [ NAME_FIRST => 'Steinar', NAME_INITIALS => 'N.'],
  'SinanU' => [ NAME_FIRST => 'Sinan', NAME_INITIALS => 'U.'],
  'ShaggyE' => [ NAME_FIRST => 'Shaggy', NAME_INITIALS => 'E.'],
  'RobertZ' => [ NAME_FIRST => 'Robert', NAME_INITIALS => 'Z.'],
  'RamY' => [ NAME_FIRST => 'Ram', NAME_INITIALS => 'Y.'],
  'RamG' => [ NAME_FIRST => 'Ram', NAME_INITIALS => 'G.'],
  'RahelP' => [ NAME_FIRST => 'Rahel', NAME_INITIALS => 'P.'],
  'QkrzyS' => [ NAME_FIRST => 'Krzysztof', NAME_INITIALS => 'S.'],
  'PiotrQ' => [ NAME_FIRST => 'Piotr', NAME_INITIALS => 'Q.'],
  'PiotrF' => [ NAME_FIRST => 'Piotr', NAME_INITIALS => 'F.'],
  'PhilT' => [ NAME_FIRST => 'Phil', NAME_INITIALS => 'T.'],
  'PatN' => [ NAME_FIRST => 'Pat', NAME_INITIALS => 'N.'],
  'ParkI' => [ NAME_INITIALS => 'I.', NAME_LAST => 'Park'],
  'NormG' => [ NAME_FIRST => 'Norm', NAME_INITIALS => 'G.'],
  'MonicS' => [ NAME_FIRST => 'Monic', NAME_INITIALS => 'S.'],
  'MimiK' => [ NAME_FIRST => 'Mimi', NAME_INITIALS => 'K.'],
  'MichaelP' => [ NAME_FIRST => 'Michael', NAME_INITIALS => 'P.'],
  'MichaelH' => [ NAME_FIRST => 'Michael', NAME_INITIALS => 'H.'],
  'MayE' => [ NAME_FIRST => 'May', NAME_INITIALS => 'E.'],
  'IreneW' => [ NAME_FIRST => 'Irene', NAME_INITIALS => 'W.'],
  'KlaraS' => [ NAME_FIRST => 'Klara', NAME_INITIALS => 'S.'],
  'KenL' => [ NAME_FIRST => 'Ken', NAME_INITIALS => 'L.'],
  'GrazielaT' => [ NAME_FIRST => 'Graziela', NAME_INITIALS => 'T.'],
  'GraziaP' => [ NAME_FIRST => 'Grazia', NAME_INITIALS => 'P.'],
  'LeeAnn' => [ NAME_FIRST => 'Lee Ann'],
  'susAN' => [ NAME_FIRST => 'Susan'],
  'mustafA' => [ NAME_FIRST => 'Mustafa'],
  'YAndrzeJ' => [ NAME_FIRST => 'Andrzej'],
  'DeeDee' => [ NAME_FIRST => 'Dee Dee'],
  'DeeAnn' => [ NAME_FIRST => 'Dee Ann'],
  'MarIna' => [ NAME_FIRST => 'Marina'],
  'MajLis' => [ NAME_FIRST => 'Maj Lis'],
  'CaroIine' => [ NAME_FIRST => 'Caroline'],
  'BeeJay' => [ NAME_FIRST => 'Bee Jay'],
  'BeeBee' => [ NAME_FIRST => 'Bee Bee'],
  'FranciS' => [ NAME_FIRST => 'Francis'],
  'BirGün' => [ NAME_FIRST => 'Birgün'],
  'BirGÜN' => [ NAME_FIRST => 'Birgün'],
  'joanGray' => [ NAME_FIRST => 'Joan', NAME_LAST => 'Gray'],
  'garyGottlieb' => [ NAME_FIRST => 'Gary', NAME_LAST => 'Gottlieb'],
  'WaldemarMatyga' => [ NAME_FIRST => 'Waldemar', NAME_LAST => 'Matyga'],
  'TomTrottier' => [ NAME_FIRST => 'Tom', NAME_LAST => 'Trottier'],
  'PrehnMehlsen' => [ NAME_FIRST => 'Prehn', NAME_LAST => 'Mehlsen'],
  'MaciejTarczyn' => [ NAME_FIRST => 'Maciej', NAME_LAST => 'Tarczyn'],
  'LauraHerring' => [ NAME_FIRST => 'Laura', NAME_LAST => 'Herring'],
  'JørgenNielsen' => [ NAME_FIRST => 'Jørgen', NAME_FIRST => 'Nielsen'],
  'GaryCharness' => [ NAME_FIRST => 'Gary', NAME_LAST => 'Charness'],
  'dorisHetke' => [ NAME_FIRST => 'Doris', NAME_LAST => 'Hetke'],
  'corinneCluzel' => [ NAME_FIRST => 'Corinne', NAME_LAST => 'Cluzel'],
  'catherineOsickey' => [ NAME_FIRST => 'Catherine', NAME_LAST => 'Osickey'],
  'carlinLarry' => [ NAME_FIRST => 'Carlin', NAME_LAST => 'Larry'],
  'brendaSlaughter' => [ NAME_FIRST => 'Brenda', NAME_LAST => 'Slaughter'],
  'boleySonia' => [ NAME_FIRST => 'Sonia', NAME_LAST => 'Boley'],
  'annieSalvenmoser' => [ NAME_FIRST => 'Annie', NAME_LAST => 'Salvenmoser'],
  'anitaHETKE' => [ NAME_FIRST => 'Anita', NAME_LAST => 'Hetke'],
  'aliceGiancarlo' => [ NAME_FIRST => 'Alice', NAME_LAST => 'Giancarlo'],
  'ZiaMahmood' => [ NAME_FIRST => 'Zia', NAME_LAST => 'Mahmood'],
  'MoellerPoulsen' => [ NAME_FIRST => 'Moeller', NAME_LAST => 'Poulsen'],
  'BasBolk' => [ NAME_FIRST => 'Bas', NAME_LAST => 'Bolk'],
  'LouisBesters' => [ NAME_FIRST => 'Louis', NAME_LAST => 'Besters'],
  'LenoreBank' => [ NAME_FIRST => 'Lenore', NAME_LAST => 'Bank'],
  'LenaReijinga' => [ NAME_FIRST => 'Lena', NAME_LAST => 'Reijinga'],
  'TeomanKoray' => [ NAME_FIRST => 'Teoman', NAME_LAST => 'Koray'],
  'KevinChen' => [ NAME_FIRST => 'Kevin', NAME_LAST => 'Chen'],
  'JoviSmed' => [ NAME_FIRST => 'Jovi', NAME_LAST => 'Smederevac'],
  'BarbaraCameron' => [ NAME_FIRST => 'Barbara', NAME_LAST => 'Cameron'],
  'TimYang' => [ NAME_FIRST => 'Tim', NAME_LAST => 'Yang'],
  'ThomasZhang' => [ NAME_FIRST => 'Thomas', NAME_LAST => 'Zhang'],
  'StavracheMihail' => [ NAME_FIRST => 'Mihail', NAME_LAST => 'Stavrache'],
  'AlexPris' => [ NAME_FIRST => 'Alex', NAME_LAST => 'Pris'],
  'PhyllisNoury' => [ NAME_FIRST => 'Phyllis', NAME_LAST => 'Noury'],
  'PepBaas' => [ NAME_FIRST => 'Pep', NAME_LAST => 'Baas'],
  'PedroMonteiro' => [ NAME_FIRST => 'Pedro', NAME_LAST => 'Monteiro'],
  'NémethTimea' => [ NAME_FIRST => 'Timea', NAME => 'Németh'],
  'NelyTotova' => [ NAME_FIRST => 'Nely', NAME_LAST => 'Totova'],
  'NeaBlomst' => [ NAME_FIRST => 'Nea', NAME_LAST => 'Blomst'],
  'MiekeHamelijnck' => [ NAME_FIRST => 'Mieke', NAME_LAST => 'Hamelijnck'],
  'MichaelLee' => [ NAME_FIRST => 'Michael', NAME_LAST => 'Lee'],
  'MariePagano' => [ NAME_FIRST => 'Marie', NAME_LAST => 'Pagano'],
  'MariaZak' => [ NAME_FIRST => 'Maria', NAME_LAST => 'Zak'],
  'MarekBytof' => [ NAME_FIRST => 'Marek', NAME_LAST => 'Bytof'],
  'MajaKlein' => [ NAME_FIRST => 'Maja', NAME_LAST => 'Klein'],
  'VanSanten' => [ NAME_PARTICLES => 'van', NAME_LAST => 'Santen'],
  'dePalo' => [ NAME_PARTICLES => 'de', NAME_LAST => 'Palo'],
  'deBeauvais' => [ NAME_PARTICLES => 'de', NAME_LAST => 'Beauvais'],
  'VonDeylen' => [ NAME_PARTICLES => 'von', NAME_LAST => 'Deylen'],
  'VanWyck' => [ NAME_PARTICLES => 'van', NAME_LAST => 'Wyck'],
  'VanVark' => [ NAME_PARTICLES => 'van', NAME_LAST => 'Vark'],
  'vonBeck' => [ NAME_PARTICLES => 'von', NAME_LAST => 'Beck'],
  'VandeKerkhove' => [ NAME_PARTICLES => 'van de', NAME_LAST => 'Kerkhove'],
  'VanSon' => [ NAME_PARTICLES => 'van', NAME_LAST => 'Son'],
  'VanSnick' => [ NAME_PARTICLES => 'van', NAME_LAST => 'Snick'],
  'deBrillancourt' => [ NAME_PARTICLES => 'de', NAME_LAST => 'Brillancourt'],
  'duPonT' => [ NAME_PARTICLES => 'du', NAME_LAST => 'Punt'],
  'deMaine' => [ NAME_PARTICLES => 'de', NAME_LAST => 'Maine'],
  'deLanie' => [ NAME_PARTICLES => 'de', NAME_LAST => 'Lanie'],
  'deJong' => [ NAME_PARTICLES => 'de', NAME_LAST => 'Jong'],
  'daSilva' => [ NAME_PARTICLES => 'da', NAME_LAST => 'Silva'],
  'DellaCroix' => [ NAME_PARTICLES => 'della', NAME_LAST => 'Croix'],
  'laRocq' => [ NAME_PARTICLES => 'la', NAME_LAST => 'Rocq'],
  'garoufALIS' => [ NAME_LAST => 'Garoufalis'],
  'EmmA' => [ NAME_FIRST => 'Emma'],
  'yrraB' => [ NAME_FIRST => 'Barry'],
  'BonnY' => [ NAME_FIRST => 'Bonny'],
  'LeoN' => [ NAME_FIRST => 'Leon'],
  'KatyUzu' => [ NAME_FIRST => 'Katy', NAME_LAST => 'Uzu'],
  'SebatiATAMAN' => [ NAME_FIRST => 'Sebata', NAME_LAST => 'Ataman'],
  'antzoyLETA' => [ NAME_FIRST => 'Antzoy', NAME_LAST => 'Leta'],
  'AngElisabeth' => [ NAME_FIRST => 'Elisabeth', NAME_LAST => 'Ang'],
  'tommyJoe' => [ NAME_FIRST => 'Tommy Joe'],
  'muraTCura' => [ NAME_FIRST => 'Murat', NAME_LAST => 'Cura'],
  'memedAli' => [ NAME_FIRST => 'Memed', NAME_LAST => 'Ali'],
  'mcCahnn' => [ NAME_LAST => 'McCahn'],
  'mcCabe' => [ NAME_LAST => 'McCabe'],
  'lwmDekkers' => [ NAME_FIRST => 'L. W. M.', NAME_LAST => 'Dekkers'],
  'labroJeanne' => [ NAME_FIRST => 'Jeanne', NAME_LAST => 'Labro'],
  'johnDeMaria' => [ NAME_FIRST => 'John', NAME_LAST => 'DeMaria'],
  'gunnarssonHafsteinn' => [ NAME_FIRST => 'Hafsteinn', NAME_LAST => 'Gunnarsson'],
  'QingDao' => [ NAME_FIRST => 'Dao', NAME_LAST => 'Qing'],
  'WangHao' => [ NAME_FIRST => 'Hao', NAME_LAST => 'Wang'],
  'HuangLin' => [ NAME_FIRST => 'Lin', NAME_LAST => 'Huang'],
  'ChengJun' => [ NAME_FIRST => 'Jun', NAME_LAST => 'Cheng'],
  'YuanQi' => [ NAME_FIRST => 'Qi', NAME_LAST => 'Yuan'],
  'JiangMingli' => [ NAME_FIRST => 'Mingli', NAME_LAST => 'Jiang'],
  'ZhangDS' => [ NAME_INITIALS => 'D. S.', NAME_LAST => 'Zhang'],
  'ShenXiang' => [ NAME_FIRST => 'Xiang', NAME_LAST => 'Shen'],
  'QianRen' => [ NAME_FIRST => 'Ren', NAME_LAST => 'Qian'],
  'LaoQi' => [ NAME_FIRST => 'Qi', NAME_LAST => 'Lao'],
  'LangHua' => [ NAME_FIRST => 'Hua', NAME_LAST => 'Lang'],
  'KuhChung' => [ NAME_FIRST => 'Kuh', NAME_LAST => 'Chung'],
  'KuangZP' => [ NAME_INITIALS => 'Z. P.', NAME_LAST => 'Kuang'],
  'FanZhen' => [ NAME_FIRST => 'Zhen', NAME_LAST => 'Fan'],
  'HasanUsta' => [ NAME_FIRST => 'Hasan', NAME_LAST => 'Usta'],
  'TurkumDiyene' => [ NAME_FIRST => 'Turkum', NAME_LAST => 'Diyene'],
  'AlpEren' => [ NAME_FIRST => 'Alp', NAME_LAST => 'Eren'],
  'ZekiKARA' => [ NAME_FIRST => 'Zeki', NAME_LAST => 'Kara'],
  'GeirEnge' => [ NAME_FIRST => 'Geir', NAME_LAST => 'Enge'],
  'PlaraMahardika' => [ NAME_FIRST => 'Plara', NAME_LAST => 'Mahardika'],
  'TusharKanti' => [ NAME_FIRST => 'Tushar', NAME_LAST => 'Kanti'],
  'RuiEsteves' => [ NAME_FIRST => 'Rui', NAME_LAST => 'Esteves'],
  'RobertChristy' => [ NAME_FIRST => 'Robert', NAME_LAST => 'Christy'],
  'RSebatiATAMAN' => [ NAME_FIRST => 'Sebati', NAME_LAST => 'Ataman'],
  'PymAisbitt' => [ NAME_FIRST => 'Pym', NAME_LAST => 'Aisbitt'],
  'AvishekDolui' => [ NAME_FIRST => 'Avishek', NAME_LAST => 'Dolui'],
  'ArunPal' => [ NAME_FIRST => 'Arun', NAME_LAST => 'Pal'],
  'AdiWijaya' => [ NAME_FIRST => 'Adi', NAME_LAST => 'Wijaya'],
  'RoniLynn' => [ NAME_FIRST => 'Roni', NAME_LAST => 'Lynn'],
  'MaryACruse' => [ NAME_FIRST => 'Mary', NAME_INITIALS => 'A.', NAME_LAST => 'Cruse'],
  'AWFdenHaring' => [ NAME_INITIALS => 'A. W. F.', NAME_PARTICLES => 'den', NAME_LAST => 'Haring'],
  'PiotrMaz' => [ NAME_FIRST => 'Piotr', NAME_LAST => 'Maz'],
  'MarianVanstone' => [ NAME_FIRST => 'Marian', NAME_PARTICLES => 'van', NAME_LAST => 'Stone'],
  'FTenBrook' => [ NAME_INITIALS => 'F.', NAME_PARTICLES => 'ten', NAME_LAST => 'Brook'],
  'DubrannaMarieClaude' => [ NAME_FIRST => 'Marie Claude', NAME_LAST => 'Dubranna'],
  'BenOrzeske' => [ NAME_FIRST => 'BEN', NAME_LAST => 'Orzeske'],
  'BehrensRe' => [ NAME_FIRST => 'Regina', NAME_LAST => 'Behrens'],
  'ZamfiR' => [ NAME_FIRST => 'Zamfir'],
  'ZacKhaR' => [ NAME_FIRST => 'Zackhar'],
  'UllA' => [ NAME_FIRST => 'Ulla'],
  'VGianCarlo' => [ NAME_FIRST => 'Gian Carlo'],
  'MLanA' => [ NAME_FIRST => 'Lana'],
  'EddiE' => [ NAME_FIRST => 'Eddie'],
  'EGianCarlo' => [ NAME_FIRST => 'Gian Carlo'],
  'BillyJack' => [ NAME_FIRST => 'Billy Jack'],
  'SlawekK' => [ NAME_FIRST => 'Slawek', NAME_INITIALS => 'K.'],
  'MaurizioV' => [ NAME_FIRST => 'Maurizio', NAME_INITIALS => 'V.'],
  'MaroulaI' => [ NAME_FIRST => 'Maroula', NAME_INITIALS => 'I.'],
  'MBjoernL' => [ NAME_FIRST => 'Bjoern', NAME_INITIALS => 'L.'],
  'OBjoernL' => [ NAME_FIRST => 'Bjoern', NAME_INITIALS => 'L.'],
  'LPauloAF' => [ NAME_FIRST => 'Paulo', NAME_INITIALS => 'A. F.'],
  'RenatoB' => [ NAME_FIRST => 'Renato', NAME_INITIALS => 'B.'],
  'RenataDS' => [ NAME_FIRST => 'Renata', NAME_INITIALS => 'D. S.'],
  'FanWY' => [ NAME_INITIALS => 'W. Y.', NAME_INITIALS => 'Fan'],
  'BismailC' => [ NAME_FIRST => 'Ismail', NAME_INITIALS => 'C'],
  'ArturK' => [ NAME_FIRST => 'Artur', NAME_INITIALS => 'K'],
  'RTheodorSadecky' => [ NAME_FIRST => 'Theodor', NAME_LAST => 'Sadecky'],
  'PraneeT' => [ NAME_FIRST => 'Praneet'],
  'MPauloC' => [ NAME_FIRST => 'Paulo', NAME_INITIALS => 'C.'],
  'IJayJay' => [ NAME_INITIALS => 'J. J.'],
  'PradyumnaGorkhali' => [NAME_FIRST => 'Pradyumna', NAME_LAST => 'Gorkhali'],
  'KorkMAYIS' => [NAME_FIRST => 'Kork', NAME_LAST => 'Mayis'],
  'JoenDSlaven' => [NAME_FIRST => 'Joen', NAME_INITIALS => 'D.', NAME_LAST => 'Slaven'],
  'JerzyJerzyJerzy' => [ NAME_FIRST => 'Jerzy'],
  'HicriTUNC' => [NAME_FIRST => 'Hicri', NAME_LAST => 'Tunc'],
  'YunYun' => [ NAME_FIRST => 'Yun Yun'],
  'ChenChangXu' => [ NAME_FIRST => 'Chang Xu', NAME_LAST => 'Chen'],
  'LeeManYiu' => [ NAME_FIRST => 'Man Yiu', NAME_LAST => 'Lee'],
  'XieSongmao' => [ NAME_FIRST => 'Songmao', NAME_LAST => 'Xie'],
  'XiaLing' => [ NAME_FIRST => 'Ling', NAME_LAST => 'Xia'],
  'WuSongBai' => [ NAME_FIRST => 'Song Bai', NAME_LAST => 'Wu'],
  'WuJiaoQi' => [ NAME_FIRST => 'Jiao Qi', NAME_LAST => 'Wu'],
  'WingTakTo' => [ NAME_FIRST => 'To', NAME_LAST => 'Wing Tak'],
  'SongQiao' => [ NAME_FIRST => 'Qiao', NAME_LAST => 'Song'],
  'ShaoMin' => [ NAME_FIRST => 'Min', NAME_LAST => 'Shao'],
  'AThanassiadIs' => [ NAME_LAST => 'Athanassiadis'],
  'AAlankBondo' => [ NAME_FIRST => 'Alan', NAME_INITIALS => 'K.', NAME_LAST => 'Bondo'],
  'TeeJay' => [ NAME_INITIALS => 'T. J.'],
  'SueMac' => [ NAME_FIRST => 'Sue'],
  'RsaraH' => [ NAME_FIRST => 'Sarah'],
  'WinsteD' => [ NAME_LAST => 'Winsted'],
  'GiovannaDell\'Amico' => [ NAME_FIRST => 'Giovanna', NAME_LAST => 'Dell\'Amico'],
  'BernardK' => [ NAME_FIRST => 'Bernard', NAME_INITIALS => 'K.'],
  'MvanStraalen' => [NAME_INITIALS => 'M.', NAME_PARTICLES => 'van', NAME_LAST => 'Straalen'],
  'anuradhaJ' => [ NAME_FIRST => 'Anuradha', NAME_INITIALS => 'J.'],
  'LaviMaria' => [ NAME_FIRST => 'Maria', NAME_LAST => 'Lavi'],
  'LahirBatin' => [ NAME_FIRST => 'Lahir Batin'],
  'MutiaraRK' => [ NAME_FIRST => 'Mutiara', NAME_INITIALS => 'R. K.'],
  'MuthaGM' => [ NAME_FIRST => 'Mutha', NAME_INITIALS => 'G. M.'],
  'ffrankT' => [ NAME_FIRST => 'Frank', NAME_INITIALS => 'T.'],
  'YusufeliSevdam' => [ NAME_FIRST => 'Yusufeli', NAME_LAST => 'Sevdam'],
  'SatyaNarayanReddy' => [ NAME_FIRST => 'Satya', NAME_LAST => 'Narayan Reddy'],
  'RamazanBerk' => [ NAME_FIRST => 'Ramazan', NAME_LAST => 'Berk'],
  'FikithaSirap' => [ NAME_FIRST => 'Fikitha', NAME_LAST => 'Sirap'],
  'RomekRyszawy' => [ NAME_FIRST => 'Romek', NAME_LAST => 'Ryszawy'],
  'BayuSetyanto' => [ NAME_FIRST => 'Bayu', NAME_LAST => 'Setyanto'],
  'AliYaþarÜnal ' => [ NAME_FIRST => 'Ali Yaþar', NAME_LAST => 'Ünal'],
  'VSevdamYakar ' => [ NAME_FIRST => 'Sevdam', NAME_LAST => 'Yakar'],
  'FransKox' => [ NAME_FIRST => 'Frans', NAME_LAST => 'Kox'],
  'RöneEkmekçio ' => [ NAME_FIRST => 'Röne', NAME_LAST => 'Ekmekçioglu'],
  'TacettinTurker' => [ NAME_FIRST => 'Tacettin', NAME_LAST => ''],
  'JerzyMarsza³kowski' => [NAME_FIRST => 'Jerzy', NAME_LAST => 'Marszałkowski'],
  'AnuggrahAffdal' => [NAME_FIRST => 'Affdal', NAME_LAST => 'Anuggrah'],
  'KurtCh' => [NAME_FIRST => 'Kurt', NAME_INITIALS => 'C.'],
  'ElspethSc' => [NAME_FIRST => 'Elspeth', NAME_INITIALS => 'S.'],
  'TakisePolak' => [NAME_FIRST => 'Takise', NAME_LAST => 'Polak'],
  'orhanAyhan' => [NAME_FIRST => 'Orhan', NAME_LAST => 'Ayhan'],
  'PacoCanario' => [NAME_FIRST => 'Paco', NAME_LAST => 'Canario'],
  'MenaBria' => [NAME_FIRST => 'Mena', NAME_LAST => 'Bria'],
  'NumanTeoman' => [NAME_FIRST => 'Numan', NAME_LAST => 'Teoman'],
  'MeltonDoxey' => [NAME_FIRST => 'Melton', NAME_LAST => 'Doxey'],
  'nivlaC' => [NAME_FIRST => 'Calvin'],
  'nitraM' => [NAME_FIRST => 'Martin'],
  'enTon' => [NAME_PARTICLES => 'en', NAME_LAST => 'Ton'],
  'ozGul' => [NAME_FIRST => 'Özgül'],
  'safakD' => [NAME_FIRST => 'Safak', NAME_INITIALS => 'D.'],
  'FredN' => [NAME_FIRST => 'Fred', NAME_INITIALS => 'N.'],
  'DenizWize' => [NAME_FIRST => 'Deniz', NAME_LAST => 'Wize'],
  'AFLindaY' => [NAME_FIRST => 'Lindy', NAME_INITIALS => 'Y.'],
  'ChuFa' => [NAME_FIRST => 'Chu Fa'],
  'KaaN' => [NAME_FIRST => 'Kaan'],
  'UyGaR' => [NAME_FIRST => 'Uygar'],
  'MiaWalking' => [NAME_FIRST => 'Mia'],
  'SerkaN' => [NAME_FIRST => 'Serkan'],
  'laoChen' => [NAME_FIRST => 'Lao', NAME_LAST => 'Chen'],
  'neBOJsa' => [NAME_FIRST => 'Nebojsa'],
  'capucineDubosquet' => [NAME_FIRST => 'Capucine', NAME_LAST => 'Dubosquet'],
  'andRE' => [NAME_FIRST => 'Andre'],
  'zhouCQ' => [NAME_INITIALS => 'C. Q.', NAME_LAST => 'Zhou'],
  'simonQi' => [NAME_FIRST => 'Simon', NAME_LAST => 'Qi'],
  'sergeB' => [NAME_FIRST => 'Serge', NAME_INITIALS => 'B.'],
  'margreethV' => [NAME_FIRST => 'Margreeth', NAME_INITIALS => 'V.'],
  'marioR' => [NAME_FIRST => 'Mario', NAME_INITIALS => 'R.'],
  'liminCHEN' => [NAME_FIRST => 'Limin', NAME_LAST => 'Chen'],
  'ericplaySweden' => [NAME_FIRST => 'Eric'],
  'ValerieBIL' => [NAME_FIRST => 'Valerie'],
  'NuraYS' => [NAME_FIRST => 'Nura', NAME_INITIALS => 'Y. S.'],
  'viviM' => [NAME_FIRST => 'Vivi', NAME_INITIALS => 'M.'],
  'RonaldFirst' => [NAME_FIRST => 'Ronald', NAME_LAST => 'First'],
  'TanjaL' => [NAME_FIRST => 'Tanja', NAME_INITIALS => 'L.'],
  'RoyG' => [NAME_FIRST => 'Roy', NAME_INITIALS => 'G.'],
  'JuhaniH' => [NAME_FIRST => 'Juhani', NAME_INITIALS => 'H.'],
  'hoBERMAN' => [NAME_LAST => 'Hoberman'],
  'lsStella' => [NAME_FIRST => 'Stella'],
  'EmileJ' => [NAME_FIRST => 'Emile', NAME_INITIALS => 'J.'],
  'franK' => [NAME_FIRST => 'Frank'],
  'xoxoxoJoan' => [NAME_FIRST => 'Joan'],
  'xiaozhenQ' => [NAME_FIRST => 'Xiaozhen', NAME_INITIALS => 'Q.'],
  'wictorRo' => [NAME_FIRST => 'Wictor'],
  'shulavaskevitchPrivate' => [NAME_FIRST => 'Shula', NAME_LAST => 'Vaskevitch'],
  'PrivateMikemansur' => [NAME_FIRST => 'Mike', NAME_LAST => 'Mansur'],
  'PrivateZhujianfen' => [NAME_FIRST => 'Jianfen', NAME_LAST => 'Zhu'],
  'frenkielfrenkielPrivate' => [NAME_LAST => 'Frenkiel'],
  'nadinenickelPrivate' => [NAME_FIRST => 'Nadine', NAME_LAST => 'Nickel'],
  'mariterenavaPrivate' => [NAME_FIRST => 'Maria Teresa', NAME_LAST => 'Nava'],
  'odettwePrivate' => [NAME_FIRST => 'Odette'],
  'gshillabeerPrivate' => [NAME_INITIALS => 'G.', NAME_LAST => 'Shillabeer'],
  'errandoneaPrivate' => [NAME_LAST => 'Errandonea'],
  'dellalPrivate' => [NAME_LAST => 'Dellal'],
);

sub split
{
  my ($text, $splits) = @_;

  if (exists $NAMES{$text})
  {
    $splits = $NAMES{$text};
    return 1;
  }
  else
  {
    return 0;
  }
}

1;
