# SUITDATA_FILE = "suitdata100.csv"
SUITDATA_FILE = "suitdata.csv"

BRIDGE_TRICKS = 13
NUM_POS = 4
NUM_VUL = 4

NUM_TOPS = 6

NUM_DIST = 560
NUM_SUITS = 512
NUM_VAR = NUM_DIST + NUM_SUITS
NUM_DOMINANCES = 864

MAX_STRENGTH = 30
STRENGTH_STEP = 0.01
NUM_STRENGTH_STEPS = int(MAX_STRENGTH / STRENGTH_STEP)
