#!perl

use strict;
use warnings;
use v5.10;
use utf8;
use open ':std', ':encoding(UTF-8)';

package Tags::Bases;

our @ISA = qw(Exporter);
our @EXPORT = qw(set_hashes);

my @MULTI_WORDS =
(
  '5-Card Majors',
  'Benjamin ACOL',
  'Dutch ACOL',
  'Forum D',
  'Meckwell Precision',
  'New Zealand Acol',
  'New Zealand Precision',
  'Power ACOL',
  'Standard American',
  'Standard French',
  'Standard Italia',
  'Swiss ACOL',
  'Two Over One',
  'UK ACOL',
);

my %MULTI_TYPOS =
(
  '5-Card Majors' => [
    '1 h/s= 5card',
    '1 h/s - major five',
    '12 13 5card open',
    '12p+ open 5card maj',
    '12 pts 5 cards',
    '12p opening, 5card majer',
    '13/15 5card suits one of suit',
    '13+pts (12 with exceptional case) 5 card major',
    '13points yo open 5cardmajor',
    '13 to open 5cards major',
    '1h-sp 5card',
    '1h/1s 5crd',
    '1h,1s 5card',
    '1hs-13hcp 5crd',
    '1h en 1 sp = 5card',
    '1he, sp- 5card',
    '1s/1h11-15(5carde)',
    '1s,1h 5cards',
    '2std american5card majors',
    '5card m',
    '5card ma opning',
    '5card mag',
    '5card mager',
    '5card magor suits open w 12hpc',
    '5card maio',
    '5card maj',
    '5card major',
    '5card major..opening 11+',
    '5card major a la francaise natural',
    '5card major opening only',
    '5card majors',
    '5card majors 12-16',
    '5card majr',
    '5card man',
    '5card mjr',
    '5card mjrs',
    '5card mayo',
    '5card op',
    '5card open',
    '5cards m',
    '5cards maj',
    '5cards major',
    '5cards meij',
    '5cards op',
    '5crd hoog',
    '5crd mag open',
    '5crd maj',
    '5crd major',
    '5crd major 12+',
    '5crd major with fnt',
    '5crd majors',
    '5crds major',
    '5crd mj',
    '5 c ma',
    '5 c maj',
    '5 c major',
    '5 c mj',
    '5 c openg',
    '5 ca major',
    '5 card Major',
    '5 card m',
    '5 card ma',
    '5 card mager',
    '5 card maj',
    '5 card major',
    '5 card major 12h',
    '5 card major opening',
    '5 card major to open',
    '5 card majors',
    '5 card majs',
    '5 card mayo',
    '5 card mayor',
    '5 cards',
    '5 cards 12 pc',
    '5 cards mag',
    '5 cards maj',
    '5 cards major',
    '5 cards majors',
    '5 cards open in major',
    '5 cards opening',
    '5 carts mar',
    '5 cd maj',
    '5 cd maj opener',
    '5 cd majors',
    '5 cds majors',
    '5 cm',
    '5 cr major',
    '5 crd high',
    '5 crd m 13+',
    '5 crd major',
    '5 crd mjrs',
    '5 crd open',
    '5 li',
    '5 maj',
    'always open 5 carts',
    'five c major',
    'five card major',
    'five card major open',
    'five card major to open',
    'five card majors',
    'five h & S',
    'five hart an sp',
    'five majo',
    'five major',
    'five majors',
    'h/s5cards',
    'in op.5 card maj',
    'm 5',
    'm major five',
    'maj 5',
    'maj 5e',
    'maj. 5ème',
    'major 5card',
    'major 5cards 13-19pc',
    'major 5cards start with (10:12)',
    'majors 5card open',
    'mayor 5',
    'naturel 5 card',
    'op12-21 5card in mayer and spades first',
    'open 5 card majors',
    'open 11 pnts. 5card mjrs',
    'open 12-15.5card mayer',
    'open 12 PC 5 cards in suit',
    'open 12 points-5card majors',
    '0pen 5card.mayor',
    'open 5card majors',
    'open w/5card major and 11-15 pts',
    'open with 5cards',
    'standart 5 mj'],
  'Benjamin ACOL' => [
    'acol (rev-benji)',
    'acol (std. engl,benji',
    'acol; benji',
    'beji acol',
    'ben.acol',
    'benj acl',
    'benj acol',
    'benjamin acol',
    'benjaminised acol',
    'benji acol',
    'benji in acol',
    'benji,acol',
    'benji-acol',
    'benji)acol',
    'benji-acol',
    'benji/acol',
    'benjie acol',
    'benjmen acol',
    'benjmn acol',
    'benjy acol',
    'benz acol'],
  'Dutch ACOL' => [
    '4 card dutch acol',
    'acol dutch',
    'acol systeem',
    'acol van 4',
    'acol(dutch)',
    'basic dutch acol',
    'dutch) acol',
    'nl acol',
    'standaard acol',
    'standaard dutch acol'],
  'Forum D' => [
    'forum d+',
    'forum d plus'],
  'Meckwell Precision' => [
    'mechwell prevision'],
  'New Zealand Acol' => ['acol in nz', 'nz acol'],
  'New Zealand Precision' => ['nz precision' ],
  'Power ACOL' => [
    'power acol/ron kinger'],
  'Precision' => [
    'basic precision',
    'berkman precision w/ xfer positives',
    'bulgarian precision',
    'chinese precision modified',
    'control precision',
    'easy going precision',
    'lancia precision',
    'mod.precision',
    'mod. precision',
    'mod precision',
    'modified precision',
    'oldfashion precision',
    'oliver clarke precision',
    'olivers precision',
    'per precision today',
    'poren precision',
    'power precision (sontag)',
    'prazision (special system)',
    'precision(berkowitz)',
    'precision(forum)',
    'precision(goren/wei)',
    'precision(mod)',
    'precision(simplified)',
    'precision-full',
    'precision (goren)',
    'precision (oliver c style)',
    'precision (only classic - wei)',
    'precision bg',
    'precision cl',
    'precision club',
    'precision club 16+',
    'precision club cc. wei',
    'precision italy',
    'precision milano',
    'precision sistem',
    'precision system',
    'precision wei',
    'precision with trans',
    'relay precision',
    'simple precision',
    'super-precision',
    'super precision',
    'transfer precision',
    'trèfle de précision',
    'wei precision',
    "wei's precision original"],
  'SAYC' => [
    'acbl yellow card',
    'full sayc',
    'sayc (standard american yellow card)',
    'sayc basic',
    'sayc klasik',
    'simple sayc',
    'standard american yellow card basic',
    'standard sayc',
    'std american yellow',
    'stdam yellow card',
    'yellow card'],
  'Standard French' => [
    'french 5 cart major',
    'french standard',
    'french std',
    'le sef',
    'le sef+',
    'le sef classiqjue',
    'nouveau sef',
    's e f',
    'seffff',
    'sefmeil mineure',
    'sef 2006',
    'sef au complet',
    'sef basic',
    'sef francais',
    'sef (french system)',
    'simple sef',
    'un peu sef'],
  'Standard Italia' => [
    'advanced italian standard',
    'bbo standard italia',
    'bbo standard italy',
    'italian standard',
    'italy standard',
    'naturale lungo corto standard italian',
    'naturale standar italia',
    'naturale standard italia',
    'sistema naturale italiano',
    'sistema naturale standard italia',
    'sistema standard b.b.o. italia',
    'sistema standard italia',
    'stand italia',
    'stand.italia',
    'stand.italy',
    'stand:b b o italia',
    'standad italia',
    'standar italia',
    'standard bbo italia',
    'standard bboitalia',
    'standard italian',
    'standard italian natural',
    'standard italiano',
    'standard italiano 2010',
    'standard italy'],
  'Two Over One' => [
    '2/1',
    '2/1 always fg',
    '2/1 fm',
    '2/1 full',
    '2/1 game f',
    '2/1 game force',
    '2/1 game forcing',
    '2/1 gf',
    '2/1 hardy',
    '2/1 max hardy',
    '2/1 mf',
    '2/1 stand',
    '2/1 system',
    '2/1(hardy)',
    '2/1(max hardy)',
    '2/1forcing',
    '2/1gf',
    '2/1system by mike lawrence',
    '2 over 1'],
  'UK ACOL' => [
    '4 card major acol',
    '4 open acol',
    'acol 4cr',
    'acol 4 card',
    'acol (std eng)',
    'acol basic',
    'acol syst',
    'acol system',
    'acol uk',
    'acol(4c)',
    'acol-style',
    'basic acol',
    'basic uk acol',
    'basis acol',
    'english acol',
    'manchester acol',
    'mod. acol',
    'mod.acol',
    'mod acol',
    'no acol',
    'st eng mod acol',
    'standard acol',
    'standard engl acol',
    'standard english acol',
    'standard uk acol',
    'std eng acol',
    'std english acol',
    'std uk acol',
    'stnd eng acol',
    'tournament acol (bird)',
    'u.k acol',
    'uk standard acol',
    'uk std acol',
    'uk-style acol',
    'uk acol'],
);

my @SINGLE_WORDS = qw(
  Precision
  SAYC
);

my %SINGLE_TYPOS =
(
  '5-Card Majors' => [
    '5cardm', 
    '5cardmaj', 
    '5cardmajor', 
    '5crd',
    'maj5card',
    'mjrsfive'],
  Precision => [
    'orpricision',
    'percision',
    'precision2005',
    'presicion'],
  SAYC => [
    'sayac',
    'stdam'],
  'Standard French' => [
    'sef', 
    'sef12'],
  'Two Over One' => [
    '2over1'],
  'UK ACOL' => ['acol'],
);


sub set_hashes
{
  my ($method, $key) = @_;

  $method->(\@MULTI_WORDS, \%MULTI_TYPOS,
    \@SINGLE_WORDS, \%SINGLE_TYPOS, $key);
}

1;
