#!perl

use strict;
use warnings;
use v5.10;
use utf8;
use open ':std', ':encoding(UTF-8)';

package Tags::Carding;

our @ISA = qw(Exporter);
our @EXPORT = qw(set_hashes);

my @MULTI_WORDS =
(
  'even-odd',
  'high-low',
  'Italian Discards',
  'Italian Signals',
  'Smith Echo',
);

my %MULTI_TYPOS =
(
  'even-odd' => [
    'compte en pair-impair',
    'def en pair impair',
    'déf. italien',
    'defausse pair/impair',
    'défausse pair/impair',
    'déf pair/impair',
    'entame p/impair',
    'entame pairimpair',
    'entame pair impair',
    'even/odd',
    'e/u',
    'p/impair par tout',
    'p/impair coul/sa',
    'pair-impair',
    'pair-impair à l\'entame',
    'pair/ impair',
    'pair/impair',
    'pair/impair en def',
    'pair/impair en déf',
    'pair/impair partout',
    'pair/impair strict',
    'pair/impairet',
    'pair / impair',
    'pair /impair',
    'pair imp',
    'pair impair',
    'Pair impair ã la couleur',
    'pair impair coul',
    'pair impair coul/sa',
    'pair impaire',
    'pair impair en defausse',
    'pair impair en toute circonstance',
    'pair impair si utile',
    'pair impair strict',
    'paire impaire',
    'par impair',
    'sign pair-impair',
    'tout en pair impair',
    'tout pair-impair'],
  'high-low' => [
    'discards high /encour',
    'encourige with high',
    'enc-high',
    'h/l eve',
    'high- low',
    'high-l',
    'high-low',
    'high-low=equ',
    'high-low = even number',
    'high-low=even',
    'high-low=even card',
    'high-low =eve',
    'high-low encourage or even card',
    'high-low for 2-4 card',
    'high+',
    'high.lo',
    'high.enc',
    'high/lo',
    'high/law',
    'high/low',
    'high/low =even',
    'high/low discards',
    'high/low= even',
    'high/low=even',
    'high/low=even card',
    'high/low = even or go on',
    'high/low discards',
    'high/low even',
    'high=encourage',
    'high: enccourage',
    'high -low',
    'high = encourage',
    'high / low',
    'high card en',
    'high card enc',
    'high card encourage',
    'high card i like it',
    'high card positiv',
    'high cards positive',
    'high discard en',
    'high e',
    'high en',
    'high enc',
    'high encour',
    'high encourage',
    'high encourang',
    'high enq',
    'high low',
    'high low discards',
    'high low even',
    'high low for enc/even',
    'high interest',
    'high interested',
    'high is on, low is off',
    'high po',
    'high pos',
    'high to encourage',
    'hight-en',
    'hight/low-doubl',
    'hight/low doubl',
    'hight cal',
    'lead high low',
    'low/high odd',
    'low-high when odd',
    'low not interested',
    'marks high/low',
    'sign high-low',
    'signal >high encouraging',
    'signalling is high- low for attit./quant',
    'std carding high'],
  'Italian Discards' => [
    '1 def italiene',
    '1 defausse italienne',
    '1 déf ital',
    '1 déf. italien',
    '1. disc italian',
    '1. disc. italian',
    '1. discard italian',
    '1. discart italian',
    '1.disc card italy',
    '1.discard italian',
    '1def ital à la couleur',
    '1def italienne partout',
    '1déf ital',
    '1e def ital',
    '1e def ital,rub',
    '1e defausse italienne',
    '1ere def ital',
    '1ere def ital à coul',
    '1ere defausse italienne',
    '1ere défausse italienne',
    '1ere sef ital ptout',
    '1st disc italian',
    '1st discard italian',
    '1st ital disc',
    '1st ital défausse',
    '1st italian d',
    '1° def italienne',
    '1°déf ital.coul',
    '1ère déf coul ital',
    '1ère déf ital',
    '1ère défausse italienne',
    '1ére def ital',
    'appel/déf italien',
    'd ital coul',
    'de ital à la couleur',
    'def & entame ital',
    'def et appel ital',
    'def ital',
    'def ital a la color',
    'def ital à la couleur',
    'def italian',
    'def italien',
    'def italienne',
    'def italienne partout',
    'def tout italien',
    'def. italian',
    'def.italien',
    'def.italienne',
    'defau ital cou',
    'defau itali',
    'defause ital',
    'defauss italie coul',
    'defauss italie couleur',
    'defausse ital',
    'defausse itali',
    'defausse italien',
    'defausse italienne',
    'defausse tout italie',
    'defense italiene simple',
    'deff ital',
    'defos ital',
    'descarte italiano',
    'dicard ital',
    'disc italian',
    'disc. - italian',
    'disc.italian',
    'discard ital',
    'discard italia',
    'discard italian',
    'discard italian, udca',
    'discard italian/colour',
    'discard: ital',
    'discarding: italian',
    'discards italian',
    'discart italian',
    'display italian',
    'déf ital',
    'déf italien',
    'déf italiennne',
    'déf. ital',
    'déf. ital. partout',
    'déf.italie',
    'déf: tout ital',
    'défausse italien',
    'défausse italienne',
    'défausse italienne tout le temps',
    'défausse tout italien',
    'défausses ital',
    'défausses tt italien',
    'défense italienne',
    'déff italien',
    'eka sakaus italialainen',
    'ere def ital',
    'first disc italian',
    'first disc. italian',
    'first discard italian',
    'first discard: italian',
    'first italian',
    'flanc italien',
    'i défausse italienne',
    'it coul',
    'ital a coulor',
    'ital color',
    'ital coul',
    'ital couleur',
    'ital dis',
    'ital disc',
    'ital discard',
    'ital par',
    'ital partt',
    'ital pos',
    'ital-cou',
    'ital-coul',
    'ital-parité',
    'ital. coul',
    'ital.cast/enc',
    'ital.coul',
    'ital.french ( o/e',
    'ital.à l\'atout',
    'ital/cou',
    'italian (o/e)',
    'italian (odd encouraging, even mckinny) discards',
    'italian colour',
    'italian d/cards',
    'italian dc',
    'italian def',
    'italian def-o/e',
    'italian defence',
    'italian defense',
    'italian defense vs slam',
    'italian descard',
    'italian di',
    'italian dic',
    'italian dicards',
    'italian dis',
    'italian disc',
    'italian discar',
    'italian discard',
    'italian discard (odd and even',
    'italian discardig',
    'italian discarding',
    'italian discards',
    'italian discards, leb (also after double',
    'italian discart',
    'italian discd',
    'italian dsc',
    'italian dscrd',
    'italian first discard',
    'italian roman def',
    'italian sign+disc',
    'italian when color',
    'italian(color)',
    'italian(roman)',
    'italian, discards',
    'italian/roman defense (o/e)',
    'italian/roman disc',
    'italiano def',
    'italien a la couleur',
    'italien coul',
    'italien couleur',
    'italien partout',
    'italien partout et toujours',
    'italien sa & couleur',
    'italien à coul',
    'italien à la couleur',
    'italienne partout',
    'italienne à la couleur',
    'le compte et 1iere défausse italienne',
    'odd-even (italian) discards',
    'odd-even and italian discard',
    'prem déf ital',
    'sa ital',
    'tout ital collante',
    'tout itali',
    'tout italien',
    'tout italien en def',
    'tout italien( défausse,entame, en servant'],
  'Italian Signals' => [
    'ap ital coul',
    'ap ital. à coul',
    'apel italien',
    'app italiens',
    'appel ital',
    'appel ital ',
    'appel italian',
    'appel italien',
    'appel italien couleur',
    'appels italiens partout',
    'call italian',
    'crdg italian',
    'ital appel',
    'ital sygnals',
    'ital mark',
    'ital. ma',
    'ital.mark',
    'italian appeal',
    'italian appel',
    'italian call',
    'italian cardi',
    'italian cardihg',
    'italian carding',
    'italian crd',
    'italian mar',
    'italian o/e',
    'italian o/e=ulik styrke',
    'italian signal',
    'italian signal and attitude',
    'italian signaling',
    'italian signals',
    'italian signals on defense',
    'italian signing',
    'italian/ st carding',
    'italy count',
    'l\'italienne:pair/impair',
    'mark. ital',
    'markieren= ital',
    'sign ital',
    'sign italian on lead',
    'signal italian',
    'signal: italian(odd favorit colour,even lavinthal',
    'signs- italian',
    'stand. carding:italian',
    'std cdg.italian'],
  'Lavinthal' => [
    '1ere défausse italienne',
    '1st disc.lav nt/color',
    '1è defausse lavinthal (partout)',
    '1ère défausse tjrs lavinthal',
    'def lav a sa',
    'def lav asa',
    'def lav sa',
    'def lav à sa',
    'def lav',
    'def lavent à cl et sa',
    'def lavent',
    'def lavinthal',
    'def lev a sa',
    'def lev à sa',
    'def levanthal',
    'def levint',
    'def levintal à sa',
    'def levinthal',
    'defausse laventhal',
    'defausse lavin',
    'defausse lavint partout',
    'defausse lavinthal partout',
    'defausse lavinthal',
    'defausse lev a sa',
    'defausse leventhal a sa',
    'defausse leventhal au sa',
    'defausse levinbthal',
    'defausse levinthal',
    'defausse tout leventhal',
    'deff levinthal',
    'defosse levinthal',
    'descards lavinthal',
    'descarte lavinthal en st',
    'discard lavin',
    'déf lav',
    'déf lavental',
    'déf lavinthal',
    'déf lev partout',
    'déf lev à sa',
    'déf levent à sa',
    'déf levinthal',
    'déf tt levinthal',
    'déf. lavint',
    'déf. levinthal',
    'déf.levin',
    'défausse lavinthal généralisé',
    'défausse lavinthal',
    'défausse levinthal',
    'défausse tjrs lavinthal',
    'défausses: leventhal à sa',
    'first lavinthal',
    'im sa lavin',
    'in sa lavinthal',
    'lav all',
    'lav at nt',
    'lav carding',
    'lav disc vs nt',
    'lav disc',
    'lav discar',
    'lav discard',
    'lav discards',
    'lav en sa',
    'lav nt',
    'lav partout',
    'lav sa',
    'lav st',
    'lav à sa',
    'lav(nt',
    'lav(nt)',
    'lav-dis',
    'lav-nt',
    'lav. disc',
    'lav. à sa',
    'lav.nt',
    'lav.thal',
    'lav/it',
    'lav/nt',
    'lav1st',
    'lavanthal a sa',
    'lavent sa',
    'lavental a sa',
    'laventhal a sa',
    'laventhal dis',
    'laventhal discard',
    'laventhal discards',
    'laventhal s.a',
    'laventhal sa',
    'laventhal à nt',
    'laventhal à sa',
    'laventhal àsa',
    'lavi disc',
    'lavi discards',
    'lavi.nt',
    'lavin at nt',
    'lavin dis',
    'lavin disc',
    'lavin discarding',
    'lavin in nt',
    'lavin sa',
    'lavin à sa',
    'lavin(sa)',
    'lavin. discs',
    'lavingthal sign',
    'lavint sa',
    'lavint sig',
    'lavint à sa',
    'lavintal nt',
    'lavintal sa',
    'lavintal à sa',
    'lavinth sa',
    'lavinth.mark',
    'lavinthal a sa',
    'lavinthal against nt',
    'lavinthal against s',
    'lavinthal carding',
    'lavinthal di',
    'lavinthal disc only vs nt',
    'lavinthal disc',
    'lavinthal discards',
    'lavinthal discards. attitude',
    'lavinthal in nt',
    'lavinthal nt',
    'lavinthal on nt',
    'lavinthal partout',
    'lavinthal sa',
    'lavinthal signals',
    'lavinthal à nt',
    'lavinthal à sa et àla couleur',
    'lavinthal à sa',
    'lavinthal-nt',
    'lavithal, low-high=even',
    'lavn/n',
    'lavtl sa',
    'leur levin sa',
    'lev a sa',
    'lev en sa',
    'lev nt',
    'lev partout',
    'lev sa',
    'lev à nt',
    'lev à sa',
    'lev',
    'lev-sa',
    'lev. nt',
    'lev. sa',
    'lev. à sa',
    'lev.partout',
    'lev.sa',
    'lev/sa',
    'levan a sa',
    'levan sa',
    'levanthal à sa',
    'leven sa',
    'leven àsa',
    'levent a sa',
    'levent nt',
    'levent sa',
    'levent à sa',
    'levent. gén',
    'levent.à s.a',
    'levent;sa',
    'levental discards',
    'levental partout',
    'levental à sa',
    'leventh nt',
    'leventhal a sa',
    'leventhal for nt',
    'leventhal sa',
    'leventhal à sa',
    'leventhal',
    'levi a sa',
    'levin a nt',
    'levin a sa',
    'levin at nt',
    'levin n',
    'levin sa',
    'levin à sa',
    'levin.sa',
    'levinbthal/sa',
    'levint nt',
    'levint partout',
    'levint sa',
    'levint à nt',
    'levint à sa',
    'levint',
    'levint. à s',
    'levintal asa',
    'levintal sa',
    'levintal à sa',
    'levintal à sana',
    'levinth s.a',
    'levinth.partout',
    'levinthal a sa',
    'levinthal at nt',
    'levinthal couleur + sa',
    'levinthal defos',
    'levinthal nt',
    'levinthal partout',
    'levinthal sa et couleur',
    'levinthal sa',
    'levinthal à la couleur et à s.a',
    'levinthal à sa',
    'levinthal à sa',
    'levinthal(nt)',
    'levithal nt',
    'levnthl à sa',
    'levnthl àsa',
    'levt/sa et coul',
    'levtl sa',
    'lv en sa',
    'lv/nt',
    'lvat ss atout',
    'lve:co',
    'lvnt disc',
    'markierung lavinthal',
    'n=lavintal',
    'ni lav',
    'no lav',
    'no lavinthal',
    'nt: lav',
    'pas de lavintal',
    'pas leventhal',
    'sa lav',
    'sa:lavinthal',
    'tendance lev',
    'tendence lavinthal',
    'tout laventhal',
    'tout lavin thal',
    'tout levintal',
    'tout levinthal',
    'té tout lavinthal',
    'vs nt discards: lav'],
  'Smith Echo' => [
    '(rev)smith echo',
    'ap sur as',
    'appel de smith',
    'echo de smith classique',
    'echo smith',
    'echo/smith',
    'ect - echo de smith à Sa',
    'r smith',
    'r-smith',
    'rev eco smith',
    'rev smith',
    'rev smith echo',
    'rev smith pr',
    'rev. smith',
    'rev. smith in nt',
    'rev.smith',
    'rev.smith echo',
    'reverse smith',
    'reverse smith echo',
    'reverse smith echoes vs. nt only',
    'reverse smith w/ nt',
    'smith echo',
    'smit echo',
    'smith (hi=e)',
    'smith (high',
    'smith call',
    'smith ech vs nt',
    'smith echo (small enc)',
    'smith echo p',
    'smith echo small',
    'smith echo vs nt',
    'smith eco',
    'smith high card',
    'smith low',
    'smith low echo',
    'smith peter',
    'smith peters',
    'smith peters signal',
    'smith r',
    'smith rev',
    'smith sign',
    'smith signal',
    'smith signals',
    'smith v nt',
    'smith&echo',
    'smith(rev)',
    'smith-low',
    'smith.echo',
    'smith/suits',
    'ud smith'],
  UDCA => [
    'upside dow',
    'upside down',
    'upside down at',
    'upside down attitud',
    'upside down attitude',
    'upside down cardin',
    'upside down count & attitude',
    'upside down count and attitude',
    'upside down count&att',
    'upside down ct&att',
    'upside down signals',
    'upside-dow',
    'upside-down',
    'upside-down everything',
    'upsidedown signals'],
);

my @SINGLE_WORDS = qw(
  Lavinthal
  MUD
  UDCA
);

my %SINGLE_TYPOS =
(
  'even-odd' => ['pairimpair'],
  'high-low' => ['highenc'],
  Lavinthal => [
    'lav',
    'lavantal',
    'lave',
    'laven',
    'lavent',
    'lavental',
    'lavi',
    'lavient',
    'lavin',
    'lavinl',
    'lavinsa',
    'lavint',
    'lavinta',
    'lavintahl',
    'lavintal',
    'lavintall',
    'lavinth',
    'lavinthall',
    'lavinthalsa',
    'lavintl',
    'lavital',
    'lavnt',
    'lavnthl',
    'lavntl',
    'lavsa',
    'lavthl',
    'lavtl',
    'lev',
    'levan',
    'levantal',
    'leven',
    'levent',
    'levental',
    'leventhal',
    'levi',
    'levin',
    'levintal',
    'levinth',
    'levinthal',
    'levsa',
    'levtsa',
    'lvtal'],
  'Smith Echo' => [
    'smit',
    'smith',
    'smithechorev',
    'smiths'],
  UDCA => [
    'upsi',
    'upsidedown'],
);


sub set_hashes
{
  my ($method, $key) = @_;

  $method->(\@MULTI_WORDS, \%MULTI_TYPOS,
    \@SINGLE_WORDS, \%SINGLE_TYPOS, $key);
}

1;
