#!perl

use strict;
use warnings;
use v5.10;
use utf8;
use open ':std', ':encoding(UTF-8)';

package Tags::Constructive;

our @ISA = qw(Exporter);
our @EXPORT = qw(set_hashes);

my @MULTI_WORDS =
(
  'Fourth Suit Forcing',
  'Inverted Minors',
  'Kokish Game Try',
  'Limit Raise',
  'Mini-Splinter',
  'Negative Double',
  'New Minor Forcing',
  'Weak Jump Shift',
);

my %MULTI_TYPOS =
(
  'Fourth Suit Forcing' => [
    '4 sgf',
    '4th suit force'],
  Josephine => [
    'josephin 5nt'],
  'Inverted Minors' => [
    'inv-min',
    'inv. minor',
    'inv min',
    'inv mnr',
    'inv ms',
    'inv.m'],
  'Kokish Game Try' => [
    'kokish hsgt',
    'kokish trial bids',
    'kokish trials',
    'kokish game tries',
    'kokish rebids'],
  'Limit Raise' => [
    '10-11 limt rais',
    '10/11 limit raise',
    '1x-3x lim',
    '3 over 1 = limit rai',
    '8LTC limit rais',
    'ask re limit raises',
    'cue=limit+',
    'cue>limitraise',
    '(major) limit raise',
    'lim.r',
    'lim/r',
    'lim.raise',
    'lim. raise',
    'lim r',
    'lim rai',
    'lim rais',
    'lim raise',
    'lim raises',
    'lim rs',
    'limit-bids',
    'limit bid',
    'limit bid with 10-12 points & 3 of partners major',
    'limit bids',
    'limit bids 11-15 tp',
    'limit bids majo',
    'limit cue',
    'limit in major',
    'limit jump in declaarer\'s suit (10-12 pts)',
    'limit major raise',
    'limit major raises',
    'limit r',
    'limit race',
    'limit rai',
    'limit raiases',
    'limit rais',
    'limit raise 10-11',
    'limit raise 10-12pts',
    'limit raise in major',
    'limit raise with 3nt',
    'limit raise with ten poin',
    'limit raises',
    'limit raises major',
    'limit raises over major and minor opening',
    'limit raiziz',
    'limit rase',
    'limit reis',
    'limit rise',
    'limit rs',
    'limited raise',
    'limited raised in major',
    'limraise10-11',
    'limt rais',
    'limt raise',
    'limt raises',
    'lmt rais',
    'major limit raises',
    'minor limit rais',
    'no lim raise',
    'qbid limrs',
    'salto limitado',
    'saltos limitados',
    ],
  'Negative Double' => [
    'ktr neg do 3s',
    'neg.dbl up to 2 sp',
    'negdoub',
    'ngtf dbl',

    'dbls. neg.4h',
    'doblo neg',
    'doblo negativo',
    'neg 2 sp',
    'neg 3s',
    'neg d',
    'neg db>3h',
    'neg dbl',
    'neg dbl 3sp',
    'neg dbl to 3 sp',
    'neg dbl-4d',
    'neg dbls',
    'neg do 3 pik',
    'neg do 3pik',
    'neg dou',
    'neg doub',
    'neg doub to 3 level',
    'neg doub up 2sp',
    'neg doubles',
    'neg dub',
    'neg dub to 2 sp',
    'neg x',
    'neg x 4d',
    'neg x thru 3sp',
    'neg x to 2s',
    'neg x-3s',
    'neg*',
    'neg,doub',
    'neg.dble',
    'neg-dbl',
    'neg. dbl',
    'neg. dobles',
    'neg. doub. till 4d',
    'neg. x 3s',
    'neg.d',
    'neg.dbls',
    'neg.dobl',
    'neg.x',
    'neg.x 2sp',
    'negX to 4h',
    'negatif x',
    'negativ dbl',
    'negativ double',
    'negativ x',
    'negative dbl',
    'negative doub',
    'negative double',
    'negative double up to 4 h',
    'negative x',
    'negdbl-3s',
    'negt gb',
    'x-neg'],
  'New Minor Forcing' => [
    'n.m.f',
    '2 way new minor',
    '2-way new minor forcing',
    'n, new min. f',
    'ne new minor fo',
    'new mi',
    'new min',
    'new min chk',
    'new min f',
    'new min foc',
    'new min for',
    'new min forc',
    'new min forc 1 rd',
    'new min forcing',
    'new min fors',
    'new min frc',
    'new min gf',
    'new min suit for',
    'new min, forc',
    'new min. for',
    'new min. forcing 2 way',
    'new min.forc',
    'new miner',
    'new miner forc',
    'new miner forcing',
    'new miner fors',
    'new minerforcind',
    'new minf',
    'new minnor',
    'new minnor forcing',
    'new mino',
    'new minor',
    'new minor =force',
    'new minor f',
    'new minor f',
    'new minor fc',
    'new minor fcng',
    'new minor fo',
    'new minor for',
    'new minor forc',
    'new minor forc ing',
    'new minor force',
    'new minor force-mod',
    'new minor force=invite+',
    'new minor forci',
    'new minor forcin',
    'new minor forcing',
    'new minor forcing one round',
    'new minor forcingfor 1 rd',
    'new minor forcng',
    'new minor forsing',
    'new minor forxing',
    'new minor frc',
    'new minor frce',
    'new minor suit',
    'new minor suit forcing',
    'new minor= f1',
    'new minorforcing',
    'new minors',
    'new minors forcing',
    'new minot forcing',
    'new minr forcing',
    'new minr frc',
    'new minr frcing',
    'new minör',
    'new minör forc',
    'nu minor forc',
    'two way new minor forci'],
  Puppet => [
    '2nt puppet',
    '5 card puppet',
    'modified puppet',
    'pup/2nt',
    'puppet (2nt',
    'puppet(2nt',
    'puppet(3c',
    'puppet/2nt'],
  Splinter => [
    'no splint',
    'splinter bids',
    'splinter jump'],
  Transfer => [
    'all transefs',
    'no transfer', 
    'no transfers',
    'tr.f',
    'tr.fer'],
  'Weak Jump Shift' => [
    'all jump shifts weak',
    'weak jump shift',
    'weak jump shift overcalls',
    'weak jump shifts',
    'weak jump shifts always',
    'weak jumpshifts',
    'weal jump shift',
    'wk jump shift',
    'wk jump shifts',
    'wkjumpshift2-6pts'],
);

my @SINGLE_WORDS = qw(
  Josephine
  Namyats
  Puppet
  Splinter
  Transfer 
);

my %SINGLE_TYPOS =
(
  'Fourth Suit Forcing' => [
    '4sxf'],
  Josephine => [
    'josep',
    'josephin',
    'josephine',
    'josepsin'],
  'Limit Raise' => ['limra', 'limitraise', 'limitraisecue',
    'limitraises', 'limrsq'],
  'Kokish Game Try' => [
    'kokishgametry'],
  'Mini-Splinter' => [
    'minispl'],
  Namyats => [
    'namats',
    'namia',
    'namiyat',
    'namy',
    'namyant',
    'namyas',
    'namyat',
    'namynt',
    'namyt',
    'namyts'],
  'Negative Double' => [
    'negatiefx',
    'negatifdbl',
    'negatifx',
    'negatinex',
    'negatived',
    'negativedb',
    'negativex',
    'negativx',
    'negatvex',
    'negatvx',
    'negax',
    'negd',
    'negdb',
    'negdbi',
    'negdbl',
    'negdble',
    'negdbls',
    'negdlbs',
    'negdoub',
    'negdouble',
    'negfb',
    'negtx',
    'negx',
    'negx\'s',
    'negxs',
    'negxx',
    'negxxx',
    'ngdbl',
    'ngtx',
    'ngx'],
  'New Minor Forcing' => [
    'newmf',
    'nmf'],
  Puppet => [
    'pup',
    'pupet',
    'pupett',
    'pupp',
    'puppet',
    'puppet2nt',
    'puppett',
    'puppit',
    'puppt',
    'pupt'],
  Splinter => [
    'spli',
    'splider',
    'splin',
    'splinder',
    'spliner',
    'spliners',
    'splinr',
    'splint',
    'splintera',
    'splinters',
    'splintery',
    'splintr',
    'splintrs',
    'splints',
    'splintters',
    'split',
    'spliter'],
  Transfer => [
    'notransfer',
    'tansf',
    'tansfer',
    'tarnsfer',
    'tfer',
    'tfr',
    'tfrs',
    'traf',
    'tran',
    'tranf',
    'tranfer',
    'tranfers',
    'trans',
    'transef', 
    'transefs', 
    'transefer',
    'transer',
    'transers',
    'transf',
    'transfe',
    'transfeer', 
    'transfer',
    'transfere',
    'transfers',
    'transfert',
    'transferts',
    'transfery',
    'transffer',
    'transfor',
    'transfr',
    'transfrer',
    'transfres',
    'transfs',
    'transter',
    'transv',
    'tranx',
    'trasf',
    'trasfer',
    'trasfers',
    'trensfer',
    'trf',
    'trfer',
    'trfers',
    'trfr',
    'trfrs',
    'trfs',
    'trnf',
    'trnfer',
    'trnfr',
    'trnfs',
    'trns',
    'trnsf',
    'trnsfer',
    'trnsfert',
    'trnsf', 
    'trnsfr',
    'trnsfrs',
    'trnsfs',
    'trqnsders',
    'trs',
    'trsf',
    'trsfers',
    'trsfr',
    'trsfrs',
    'trsrs',
    'trx',
    'trxfs',
    'tsf',
    'tsfr',
    'tsfrs',
    'txfer',
    'xfer', 
    'xfers'],
  'Weak Jump Shift' => [
    'weakjumpshift',
    'wjs',
    'wkjumpshift',
    'wkjumpshifts'],
);


sub set_hashes
{
  my ($method, $key) = @_;

  $method->(\@MULTI_WORDS, \%MULTI_TYPOS,
    \@SINGLE_WORDS, \%SINGLE_TYPOS, $key);
}

1;
