#!perl

# These are conventions that are names after people, places etc.

use strict;
use warnings;
use v5.10;
use utf8;
use open ':std', ':encoding(UTF-8)';

package Tags::Conventions;

our @ISA = qw(Exporter);
our @EXPORT = qw(set_hashes);

my @MULTI_WORDS =
(
);

my %MULTI_TYPOS =
(
  Bergen => [
    '2sas fit(bergen)',
    'berg rais',
    'bergan raises',
    'bergen/j-2nt',
    'bergen - hebung',
    'bergen.inv',
    'bergen inv',
    'bergen j2nt',
    'bergen jumps',
    'bergen races',
    'bergen rai',
    'bergen raise',
    'bergen raises',
    'inv bergen',
    'mod-bergen raises',
    'no bergen',
    'r-berg',
    'r bergen',
    're bergen',
    'rev.berg',
    'rev berg',
    'rev-bergen',
    'rev.bergen',
    'rev bergen',
    'rev bergen raises',
    'reverse bergen',
    'saltos bergen',
    'v.m.bergen',
    ],
  Blackwood => [
    '4sa azen vragen',
    'b\'wood',
    'bkwd',
    'blackood',
    'blackwd',
    'blackwod',
    'blacw',
    'blacwood',
    'blak',
    'blck',
    'blckw',
    'blckwood',
    'blk',
    'blkwood',
    'blwd',
    'bwd',
    '4nt asking',
    '4nt=ace ask',
    '4nt>0-4, 1,2,3',
    'bl acwood',
    '4 nt ace',
    '4nt ask',
    '4nt ask a',
    '4nt asking for aces',
    '4nt:04,1,2,3, aces',

    '4abl.wood',
    '4nt ask 4 aces',
    '7 cardblack wood',
    'b wood',
    'balck wood',
    'bl .wood',
    'bl 5 cles',
    'blac wood', 
    'black wood', 
    'black- wood',
    'black-wood',
    'black.wood',
    'black/kc',
    'blackfoot wood',
    'blak kwood',
    'blak wood',
    'blak-wood',
    'blalk wood',
    'bleack wood',
    'blk wood',
    'blk.wood',
    'blk -woods',
    'bllacki wood',
    'b.wood',
    'b-wood', 
    'b/wood', 
    'b /wood', 
    'bk wood',
    'bkw en clés',
    'bl. wood', 
    'bl.wood', 
    'bl-wood', 
    'bl/wood', 
    'bl wood',
    'bolak wood',
    'bulk wood',
    'bw 5 cles',
    'bw 5 clés',
    'flac wood',
    'reg.blwd',
    'rkcb/wood'], 
  Drury => [
    '(rev) drury',
    '2 drury',
    '2d drury',
    '2t(drury',
    '2way drury',
    '2way dury',
    'drury 2d podlimit',
    'drury fit',
    'drury fitté',
    'drury inv',
    'inv. drury',
    'no drury',
    'po drury i pro 2 karo z dolem',
    're-drury', 
    're.drury',
    'rev.dury',
    'rev. drury',
    'rev drury',
    'reverse_drury',
    'reverse drury',
    'rew drury',
    ],
  Gazzilli => [
    'gazilli(meckstroth)',
    'mini-gazzilli'],
  Ghestem => ['mod ghestem'],
  Jacoby => [
    'jacob 2nt',
    'jacobys 2nt'],
  'Kokish' => [
    '2c kokish',
    'controls w kokish',
    'kok over 2c',
    'kokich/2c',
    'kokish gf',
    'kokish in 2 c',
    'kokish mod',
    'kokish r',
    'kokish relay',
    'kokish relay 2hneg',
    'kokish resp'],
  Landy => [
    'landy sournois'],
  Lebensohl => [
    'no leben'],
  Michaels => [
    'mich cub',
    'mich cuebid',
    'mich préc',
    'mich\'s',
    'mich.c',
    'mich.cue',
    'mich.cuebid',
    'mich.prec',
    'michael\'s cue bid',
    'michael\'s cue',
    'michael\'s cuebid',
    'michael\'s',
    'michael`s',
    'michael´s',
    'michaels unusual nt'],
  Muiderberg => [
    "m'berg",
    '2 s h bicol',
    '2c o 2p deb 5/5 min',
    '2 heart - 5 h 4 unknown minor weak, 2 spades - 5 sp 4 unknown minor weak',
    '2h 5+ and any 5+, 2s 5+ and 5+ c or d',
    '2h-2sp 55 weak',
    '2h/2sp=h/sp+m',
    '2m weak 5+5',
    '2 h s weak5-5',
    '2 h-2sp 5+5 card max.10 pts',
    '2 h/s weak double colour',
    '2h/s weak (5+5)',
    '2h/s weak 5+4 lower',
    '2h=5h+5other, 2s=5s+5c or 5d',
    '2he/sp weak 5-5',
    '2 h -sp 5+5',
    '2 h,2 sp weak(5+5)',
    '2 h,s 5-5 weak',

    '2hs=7-11p 5+h/s and 5+ lower suit',
    '2hs(6-10,5-5)',
    '2h/s 5+4m 7-10',
    '2h en 2s=muiderberg',
    '2s/h 5 m+4+m',
    '2ha en 2sch .muiderberg',
    '2harten en 2schoppen is muiderberg',
    '2hs muider',
    '2m muid',
    '2sch/hart muiderberg',
    '2sp-h muideberg',
    '2 h/s muid',
    '5+5 (muidbrg) weak',
    'dutch 2 (muiden',
    'dutch 2 (muiderberg)',
    'mod. muiderberg',
    'muid berg',
    'muiderberg 2h/s'],
  Ogust => ['ogust responses'],
  Roudinesco => [
    'check back (roudy)',
    'constant roudi',
    'le roudi',
    'le roudy',
    'pas de roudi',
    'roudi 2012',
    'roudi 3 rep',
    'roudi 3paliers',
    'roudi 3r',
    'roudi 4 re',
    'roudi 4 paliers',
    'roudi (3paliers)',
    'roudi ( cbs)',
    'roudi cheback',
    'roudi checkback',
    'roudi check back',
    'roudi check back staym',
    'roudi chkbk',
    'roudi const',
    'roudi constant',
    'roudi classique',
    'roudi fixe',
    'roudi mod',
    'roudinesco const',
    'roudy check back stay',
    'roudy-constant',
    'roudy constant',
    'roudy cst'],
  Rubensohl => [
    'le rub',
    'le rubenshol',
    'ni ruben',
    'partout rubens',
    'r\'rub',
    'rub 2nt',
    'ruben adv',
    'rubenhsol a sa',
    'rubens adv',
    'rubens advances',
    'rubens lol',
    'rubens tout',
    'rubensol à sa',
    'sa rub',
    'à sa ruben'],
  Rusinow => [
    'discard rusinov',
    'russinov leads'],
  Stayman => [
    'majorst.man',
    's-man',
    's.man',
    's/man',
    'st man',
    'st-man',
    'st. man',
    'st.man',
    'st/man',
    'staiman',
    'stamen',
    'stamn',
    'stav man',
    'stay man',
    'stay men',
    'stay-man',
    'stayma',
    'staymani',
    'staymanm',
    'staymann',
    'staymann/',
    'staymans',
    'staymen',
    'stayment',
    'staymn',
    'staymon',
    'stehman',
    'steiman',
    'steman',
    'steym',
    'steyman',
    'steymen',
    'stm',
    'stman',
    'stmn',
    'sty man',
    'sty-man',
    'stym',
    'styman',
    'stymas',
    'stymen',
    'stymmn',
    'stymn',
    'styn',
    'styrman'],
  # Apparently in France this is also used for 2-level transfers
  Texas => [
    '3c tex na kara',
    '4-trx texas',
    'Inter en texas sur 1sa(x=t,t=c',
    'all texas',
    'barrages en texas',
    'barrages en texas de 2k à 3sa',
    'barrages nv en texas',
    'def contr 1 sa entte posi en texas',
    'en 2e: texas',
    'encheres au niveau de 3 sont texas',
    'grande texas',
    'intervention en texas sur 1sa',
    'le texas majeur',
    'no tex',
    'no texas',
    'ouv au niveau de trois texas',
    'ouv de barrage au niveau de 3 en texas',
    'piccola &grande texas',
    'piccola texas senza interferenze grande texas',
    'piccole e grandi texas',
    'red texas',
    'reponse texas sur un !c',
    'sa texas',
    'sa-texas',
    'south african texas',
    'su 1sa texas anche in intervento',
    'sur 1sa int en texas',
    'sydaf texas',
    'tayman texas mm',
    'tex 4wa tns',
    'tex en maj',
    'tex k a 2sa',
    'tex m',
    'tex m et m',
    'tex maj/min',
    'tex min',
    'tex na d 2nt',
    'tex na d 3c',
    'tex na wszystko',
    'tex sudafr',
    'tex tr',
    'tex transf',
    'tex trf',
    'tex trs',
    'tex trsfrs',
    'tex x nob',
    'tex xfers',
    'tex. trans',
    'tex.trsf',
    'texas ( 2sa = texas k)',
    'texas (transfer)',
    'texas 4 w trnsf',
    'texas 6cm',
    'texas K pour co',
    'texas ad 1s',
    'texas all',
    'texas and texas minors',
    'texas après 1nt',
    'texas complete',
    'texas en 2nd sur sa',
    'texas en majeur',
    'texas et en mineure',
    'texas in noble',
    'texas k 2sa',
    'texas k=2 sa et modul',
    'texas m',
    'texas m et m',
    'texas m, m',
    'texas mag',
    'texas maj',
    'texas maj / min (2sa p.r k)',
    'texas maj and min',
    'texas maj et min',
    'texas maj min',
    'texas maj.min',
    'texas maje mi pres',
    'texas majeur et mineur',
    'texas meme en min',
    'texas mi',
    'texas mineure interesse',
    'texas minor maj',
    'texas mjr, texas min',
    'texas mm',
    'texas na kara 3C',
    'texas nt',
    'texas per c/p',
    'texas per i nobili',
    'texas per le maggiori',
    'texas per maggiori',
    'texas per nobili',
    'texas solo maggiori',
    'texas su 1sa',
    'texas su un sa',
    'texas sur 1sa de l adv',
    'texas sur ouv adverse de 1sa',
    'texas sur ouverture adverse en 1sa',
    'texas t',
    'texas tambièn para los menores',
    'texas tr',
    'texas tran',
    'texas tranf',
    'texas trans',
    'texas transf',
    'texas transfer',
    'texas transfer all suit',
    'texas transfers',
    'texas transfs',
    'texas trasnfers',
    'texas trf',
    'texas trns',
    'texas ts',
    'texas xf',
    'texas xfers',
    'texas( transfer)',
    'texas(transfer',
    'texas(transfer)',
    'texas(transft)',
    'texs tran.f nt',
    'texus t',
    'tout texas',
    'tout transfert en tex',
    'trans texas',
    'transf.texas',
    'transfer tex',
    'transfer texas',
    'transfer texas after1sa opening',
    'transfer y texas',
    'transfers maj.-min texas',
    'trasfer texas',
    'trnsfr texas',
    'trsf texas',
    'ts les texas',
    'ts texas',
    'tutte le texas'],
  Voidwood => [
    'v.wood', 
    'v wood', 
    'void wood', 
    'void-wood',
    'void_wood',
    'woid-vood',
    'woid wood',
    'woit wood',
    'woýd wood'],
  Walsh => [
    't-walsh',
    'walsh(1c)',
    'walsh rebids',
    'walsh relay',
    'walsh respones',
    'walsh tfr'],
  Wilkosz => [
    '2d wilkosz'],
  Woolsey => [
    's/ sa woolsey',
    'woolsey/1sa',
    'woolsey/ 1sa'],
);

my @SINGLE_WORDS = qw(
  Baron Bergen Blackwood
  Crowhurst
  Drury
  Fantunes Fishbein
  Hamilton
  Jacoby
  Gazzilli Gerber Ghestem Goren
  Jassem Jordan
  Kokish
  Landy Lavinthal Lebensohl Lightner
  Michaels Muiderberg
  Ogust
  Roudinesco Rubensohl Rusinow
  Smolen Stayman Stenberg
  Texas Truscott
  Voidwood
  Walsh Wilkosz Woolsey
);

my %SINGLE_TYPOS =
(
  Bergen => [
    'berg', 
    'bergan', 
    'berge', 
    'bergenr', 
    'bergenraises', 
    'berger', 
    'bergin', 
    'bergn', 
    'bergrais', 
    'berguen', 
    'brgn',
    'rberg'],
  Blackwood => [
    '2wood',
    'bkw',
    'bkwd',
    'blckwd',
    'blcw',
    'blcwd',
    'blac',
    'blachw',
    'black', 
    'blacwood', 
    'blkwd',
    'bw5', 
    'bw5cles', 
    'bwood',
    'rkblackwood'], 
  Drury => [
    '2wdrury', 
    '2wrdrury', 
    '2wydrury', 
    'drrury', 
    'drry',
    'druri',
    'durrury',
    'rdrury', 
    'revdrury', 
    'rvrsdrury'],
  Gazzilli => [
    'gazilli'],
  Gerber => [
    'garber', 
    'gb', 
    'ger', 
    'gerb',
    'grber'],
  Ghestem => [
    'gest', 
    'gestam', 
    'gestem', 
    'gestheim',
    'gesthem', 
    'ghest', 
    'ghestam'],
  Jacoby => [
    '2ntjac',
    'jac2n',
    'jac2nt',
    'jacb',
    'jacby',
    'jaccoby',
    'jackoby',
    'jacnt',
    'jaco',
    'jacob',
    'jacobby',
    'jacobe',
    'jacobie',
    'jacobs',
    'jacoby2n',
    'jacoby2nt',
    'jacobynt',
    'jacopy',
    'jac', 
    'jacobi', 
    'jacobytransfer',
    'jakoby'],
  'Kokish' => [
    'kok',
    'koki',
    'kokis',
    'kokich',
    'kokshi'],
  Landy => ['landi'],
  Lavinthal => [
    'lev', 
    'leventhal'],
  Lebensohl => [
    'lebansohl',
    'lebb',
    'leben',
    'lebenbsol',
    'lebenhol',
    'lebenhsol',
    'lebens',
    'lebenschi',
    'lebensh',
    'lebenshl',
    'lebensholl',
    'lebensl',
    'lebensol',
    'lebensolh',
    'lebenson',
    'lebenzol',
    'lebesohl',
    'lebh',
    'lebhensol',
    'lebhl',
    'lebl',
    'lebn',
    'lebns',
    'lebnshl',
    'lebnsl',
    'lebnsol',
    'lebon',
    'lebonsohl',
    'lebonsol',
    'lebs',
    'lebsh',
    'lebshl',
    'lebshol',
    'lebsl',
    'lebsohl',
    'lebsol',
    'leb',
    'lebenshol'],
  Michaels => [
    'mcb',
    'mchl',
    'mchls',
    'micaels',
    'mich',
    'micha0',
    'michales',
    'michals',
    'michcb',
    'michcue',
    'micheals',
    'michel',
    'michels',
    'michl',
    'michls',
    'michs',
    'mickaels',
    'mickprec',
    'mikels',
    'mkls',

    'mic', 
    'michael', 
    'mick', 
    'mickael', 
    'micheal', 
    'mikael'],
  Muiderberg => [
    'muid',
    'muidb',
    'muidbe',
    'muideberg',
    'muideburg',
    'muidenb',
    'muidenberg',
    'muider',
    'muider2',
    'muiderb',
    'muiderbe',
    'muiderber',
    'muiderberg',
    'muiderbg',
    'muidrbg'],
  Ogust => [
    'oogust',
    'ougust'],
  Roudinesco => [
    'roud',
    'roudi',
    'roudicomplet',
    'roudiconst',
    'roudy'],
  Rubensohl => [
    'rub',
    'rubadv',
    'rube',
    'ruben',
    'rubenholl',
    'rubenhsol',
    'rubens',
    'rubensh',
    'rubenshohl',
    'rubenshol',
    'rubensholl',
    'rubenshotl',
    'rubenso',
    'rubensohl',
    'rubensohll',
    'rubensol',
    'rubesohl',
    'rubh',
    'rubhen',
    'rubhensol',
    'rubin',
    'rubinsohl',
    'rubinsolh',
    'rubn',
    'rubsol'],
  Smolen => [
    'smln',
    'smol', 
    'smole', 
    'smoln',
    'smollen'],
  Stayman => [
    'sayman', 
    'staman',
    'stay', 
    'staym',
    'steaman',
    'stymns'], 
  Stenberg => [
    'stenb'],
  Texas => [
    'teksas',
    'tex',
    'texa',
    'texasc',
    'texases',
    'texasisé',
    'texasmineur',
    'texass',
    'texastransfer',
    'texastransfers',
    'texastrfs',
    'texasy',
    'texasy1nt',
    'texs',
    'texsa',
    'texsas',
    'texsmm',
    'textr',
    'texus'],
  Voidwood => ['wwood'],
  Walsh => [
    'wal', 
    'walch', 
    'wallsh', 
    'wals',
    'wlsh'],
  Wilkosz => ['wilk'],
  Woolsey => [
    'wool', 
    'wools', 
    'woolsee', 
    'woolsy', 
    'woosley'],
);


sub set_hashes
{
  my ($method, $key) = @_;

  $method->(\@MULTI_WORDS, \%MULTI_TYPOS,
    \@SINGLE_WORDS, \%SINGLE_TYPOS, $key);
}

1;
