#!perl

package Connections::Matrix;

use v5.10;
use strict;
use warnings;
use utf8;
use open ':std', ':encoding(UTF-8)';


our @ISA = qw(Exporter);
our @EXPORT = qw(set_matrix);

use lib '..';
use Whole;


my %COUNTRY_TO_REGION =
(
  Australia => ['australian central territory', 'new south wales',
    'northern territory', 'queensland', 'south australia', 
    'tasmania', 'victoria', 'western australia'],
  Austria => ['oberloiben', 'wachau'],
  Belarus => ['druts'],
  Brazil => ['rio de janeiro state'],
  China => ['anhui', 'gansu', 'guangdong', 'guangxi',
    'guizhou', 'hainan', 'haixing', 'hebei', 'hubei', 'hunan', 'jiangsu',
    'jilin', 'liaoning', 'pearl river', 'ren shou', 'shanxi', 
    'sichuan', 'tianya', 'tinglin', 'wujin', 'yongjia',
    'yunnan', 'zhejiang'],
  Denmark => ['bornholm', 'fjends', 'midtsjælland', 'sydvest'],
  France => ['corsica', 'new caledonia'],
  Greece => ['rhodes'],
  Iceland => ['eyjafjallajokull'],
  Hungary => ['hegyvidék'],
  Italy => ['olona'],
  India => ['bihar', 'ganges', 'goa', 'gujarat', 'jharkhand',
    'karnataka', 'kerala', 'madhya pradesh', 'maharashtra',
    'punjab', 'rajasthan', 'rajputana', 'tamil nadu', 'uttar pradesh', 
    'uttarakhand', 'west bengal'],
  Indonesia => ['aceh', 'bali', 'banten', 'bekasi regency', 'belitung',
    'bengkayang', 'bisma semarang', 'boeven digoel', 'bogor regency', 
    'bone bolango', 'bungo', 'central celebes', 'central java', 
    'central sulawesi', 'cianjur regency', 'east borneo', 'east jakarta', 
    'east java', 'east kalimantan', 'gabungan malaku', 'garut regency', 
    'gorontalo', 'java bali', 'kawanua', 'kayong',
    'kedungwaru', 'kepri', 'kepulauan riau', 'kutai kartanegara', 
    'lampung', 'lebak', 'lombok', 'maluku', 'minahasa',
    'north minahasa', 'north celebes', 'north sulawesi',
    'north sumatra',
    'nusa tenggara barat', 'nusantara', 'papua', 'porong', 'sintang',
    'south celebes', 'south east celebes', 'south jakarta',
    'south kalimantan', 'south sulawesi', 'south sumatra', 'tambun',
    'west borneo', 'west java', 'west kalimantan', 
    'west nusa tenggara', 'west sumatra'],
  Iraq => ['akkad'],
  Italy => ['liguria', 'olona', 'val di magra'],
  Japan => ['kansai', 'kanto'],
  Mexico => ['jalisco'],
  'New Zealand' => ['central districts', 'otago', 'southland', 'waikato'],
  Norway => ['agder', 'buskerud', 'haugaland', 'hedmark', 'hordaland',
    'midt trøndelag', 'mjøsa', 'møre romsdal', 'nord trøndelag',
    'nord-norge omegn', 'nordafjells', 'rogaland', 'rosfjord', 'salten', 
    'telemark', 'troms og ofoten', 'vest agder', 'vest finnmark', 
    'østfold follo'],
  Pakistan => ['sindh'],
  Poland => ['lower silesia', 'pomerania', 'silesia', 'slask'],
  Portugal => ['madeira', 'norte ilhas'],
  Russia => ['siberia'],
  Scotland => ['ayrshire'],
  Serbia => ['vojvodina'],
  'South Africa' => ['central gauteng', 'eastern cape', 'gauteng',
    'kwazulu natal', 'northern gauteng', 'western province'],
  'South Korea' => ['silla'],
  Spain => ['catalonia'],
  Sweden => ['norrland', 'norrorts', 'skåne', 'south sweden'],
  Taiwan => ['west district'],
  Thailand => ['krabi', 'nakhon nayok', 'ratchaburi', 'samut prakan', 
    'samut sakhon', 'suphan buri'],
  Turkey => ['aegean sea', 'akdeniz', 'cappadocia', 'central anatolia', 
    'datca yarimada', 'dersým', 'dogu akdeniz', 'hatay',
    'marmara', 'muallim', 'munzur', 'mysia', 'orontes', 'sakarya', 
    'tigris', 'tuncelý'],
  USA => ['district of columbia', 'florida', 'missouri'],
  Zimbabwe => ['matopos']
);


my %COUNTRY_TO_CITY =
(
  Argentina => ['buenos aires', 'mar del plata', 'san luis'],
  Australia => [
    'adelaide', 'brisbane', 'cairns', 'canberra',
    'melbourne', 'perth', 'sydney'],
  Austria => ['mautern', 'vienna'],
  Belarus => ['minsk'],
  Belgium => ['antwerpen', 'bruges', 'brussels', 'gent', 'leuven',
    'ostend'],
  Brazil => ['assis', 'belo horizonte', 'brasilia', 'buzios',
    'pelotas', 'rio de janeiro', 'são paulo'],
  Bulgaria => ['asenovec', 'asenovgrad', 'balchik', 'chepelare',
    'cherven briag', 'dimitrovgrad', 'dobrich', 'karlovo', 'kesten', 
    'kyustendil', 'la marina', 'pelotas', 'pernik', 'pleven', 
    'plovdiv', 'popovo', 'preslav', 'shumen', 'sofia', 
    'stara zagora', 'varna', 'vraca', 'yambol'],
  Canada => ['vancouver'],
  Chile => ['paimado', 'santiago', 'temuco'],
  China => [
    'beijing', 'changzhou', 'chengdu', 'chongqing', 'dalian', 'dongguan',
    'guangdong', 'guangzhou', 'hangzhou', 'jiamusi', 'jianshe', 'jiangsu',
    'jinchang', 'jincheng', 'jinjiang', 'jiujiang', 'kunshan', 'lanzhou',
    'liushu', 'meilin qingcheng', 'nanchang', 'nanchong', 'nanning', 
    'ningbo', 'panzhihua', 'qingdao', 'sanya', 'shanghai', 'shaoguan', 
    'shenyang', 'shenzhen', 'shijiazhuang', 'suzhou', 'taicang', 
    'taihu lake', 'taizhou', 'tianjin', 'wuhan', 'wuxi', 'xin zhu', 
    'xian', 'xiantao', 'xinyi', 'yanshi', 'yizhuang', 'yuquan', 
    'zhaoqing', 'zhong jian', 'zhongshan', 'zhuzhou', 'zigong'],
  Colombia => ['bogotá', 'medellin'],
  'Costa Rica' => ['heledia'],
  Croatia => ['opatija', 'pula', 'rijeka', 'samobor', 'split', 'zagreb'],
  Cyprus => ['nicosia'],
  'Czech Republic' => ['havirov', 'nové město', 'prague', 'radkov'],
  Denmark => [
    'aabenraa', 'aalborg', 'ballerup', 'copenhagen', 'esbjerg',
    'greve strand', 'haderslev', 'herning', 'hillerød', 'hornbæk', 
    'kalundborg', 'morud', 'næstved', 'odense', 'ravnkilde', 'rødovre', 
    'slagelse', 'stoholm', 'søborg', 'vejle', 'åkirkeby', 'århus'],
  Ecuador => ['guayaquil'],
  Egypt => ['al-rabwa', 'alexandria', 'cairo', 'el-maadi', 'giza'],
  England => ['altrincham', 'bath', 'brighton', 'canterbury', 'coventry',
    'eastbourne', 'lincoln', 'london', 'manchester', 'oxford',
    'petersfield', 'worcester'],
  Estonia => ['derpt', 'otepää', 'pärnu', 'rakvere', 'sindi', 'tallinn'],
  Finland => ['hanko', 'helsinki', 'lappeenranta', 'kuopio', 'vasa'],
  France => [
    'aix en provence', 'annecy', 'antony', 'bergues', 'biarritz',
    'bordeaux', 'caen', 'chaville', 'clichy', 'courseulles-sur-mer', 
    'deauville', 'garches', 'le bouscat', 'lille', 'lyon', 'marseille', 
    'massy', 'montpellier', 'nancy', 'nice', 'paris', 'pau', 'reims', 
    'rennes', 'toulouse', 'tours', 'val de seine'],
  Germany => ['aachen', 'augsburg', 'bamberg', 'berlin', 'bielefeld', 
    'bonn', 'bremen',
    'burghausen', 'darmstadt', 'düsseldorf', 'essen', 'frankfurt', 
    'hamburg', 'hannover', 'karlsruhe', 'ketsch', 'kiel', 'köln', 
    'leverkusen', 'mannheim', 'munich', 'nürnberg', 'oldenburg',
    'potsdam', 'rieneck', 'saarbrücken', 'schwäbisch hall', 'stuttgart'],
  Greece => ['athens', 'nea moudania', 'thessaloniki'],
  'Hong Kong' => ['Hong Kong City'],
  Hungary => ['balaton', 'balatonföldvár', 'budapest', 'debrecen',
    'gyor', 'miskolc', 'nagykanizsa', 'pecs', 'siofok', 'szeged'],
  Iceland => ['reykjavik'],
  India => ['agresar',
    'ahmedabad', 'allahabad', 'ambon', 'bangalore', 'bansi',
    'bhilwara', 'bhubaneshwar', 'bikaner', 'chennai', 'dombivli', 
    'hyderabad', 'indore', 'jaipur', 'kalyani', 'kanpur', 'kashi', 
    'kolkata', 'kota', 'mardin', 'mitra vihar', 'mulund', 
    'mumbai', 'nagpur', 'nashik', 'noida', 'pune', 'puri', 'pushkar', 
    'sukma', 'udaipur', 'varanasi'],
  Indonesia => [ 
    'airmadidi', 'balikpapan', 'banda aceh', 'bandar lampung', 'bandung',
    'banjarmasin', 'batam', 'batu', 'bengkalis', 'bengkulu', 'bitung', 
    'blitar', 'bogor', 'boven digoel', 'cimahi', 'cirebon', 'delhi', 
    'depok', 'gresik', 'grogol', 'hatay', 'jakarta', 'jember', 
    'karimun', 'kediri', 'kedungwaru', 'kinali', 'klabat', 
    'kota bandung', 'kota bekasi', 'kota bogor', 'kota mataram', 
    'kudus', 'langkat', 'lhokseumawe', 'lumajang',
    'magetan', 'makassar', 'malang', 'manado', 'mandobo bodi', 'manna',
    'martapura', 'medan', 'moradabad', 'muara bungo', 'padang', 
    'palembang', 'palu', 'pariaman', 'pekanbaru', 'penajam', 
    'pontianak', 'samarinda', 'secunderabad', 'semarang', 
    'semburat jingga', 'serang', 'seulawah agam', 'siddha eden lakeville', 
    'sidoarjo', 'sleman', 'solok', 'sukomoro', 'sumedang',
    'surabaya', 'tambun',
    'tanjung pinang', 'tarakan', 'thane', 'thanjavur', 'tomohon', 
    'yogyakarta'],
  Iraq => ['baghdad'],
  Israel => ['tel aviv'],
  Italy => [
    'bologna', 'cannareggio', 'catania', 'cuneo', 'firenze', 'genoa', 
    'la spezia', 'lecco', 'lodi', 'milan', 'monticiano', 'napoli', 
    'padova', 'palermo', 'pesaro', 'pescara', 'pisa', 
    'reggio calabria', 'reggio emilia', 'rimini', 'romana', 'rome', 
    'salerno', 'san giorgio del sannio', 'senigallia', 'siena', 
    'torino', 'trieste', 'varese', 'venice', 'verona', 
    'villa fabbriche'],
  Japan => ['takayama', 'tokyo', 'yokohama'],
  Jordan => ['amman'],
  Kazakhstan => ['aral'],
  Latvia => ['liepaja', 'riga'],
  Lebanon => ['beirut'],
  Lithuania => ['alytus', 'vilnius'],
  Malaysia => ['kuala lumpur'],
  Mexico => ['perula'],
  Monaco => ['monte carlo'],
  Morocco => ['casablanca', 'marrakech'],
  Netherlands => ['amsterdam', 'delft', 'enschede', 'groningen',
    'leiden', 'maastricht', 'nijmegen', 'rotterdam', 'the hague', 
    'utrecht'],
  'New Zealand' => ['auckland', 'wellington'],
  'North Macedonia' => ['gevgelija', 'skopje'],
  'Northern Ireland' => ['ballymena'],
  Norway => [
    'arendal', 'bergen', 'bodø', 'brandbu', 'drammen', 'farsund', 
    'flekkefjord', 'fosnavåg', 'førde', 'gudbrandsdal', 
    'gjøvik og vardal', 
    'hamar', 'harstad', 'huldretråkket', 'jessheim', 'kirkeby', 
    'kolbotn', 'kristiansand', 'kverndalen', 'kølabånn', 'lom',
    'mo i rana', 'namsos', 'narvik', 'nærbø', 'nøtterøy', 'ogndal', 
    'olrud', 'oslo', 'moss', 'ottadalen', 'sandefjord', 'sarpsborg', 
    'singsås', 'ski', 'skien', 'sortland', 'stavanger', 'steinkjer', 
    'sunndalsøra', 'sørreisa', 'trondheim', 'tromsø', 'vestfold', 
    'vestvågøy', 'vikersund', 'vorden', 'ørland', 'østerdal', 
    'ålesund', 'åsane'],
  Peru => ['ayacucho', 'lima'],
  Poland => ['bielsko-biala', 'boleslawiec', 'bydgoszcz', 'bytom', 
    'chelmno', 'elblag', 'gdansk', 'gdynia', 'gniezno', 'gorzow', 
    'kalisz', 'katowice', 'kielce', 'kornik', 'krakow', 'leszno', 
    'lodz', 'lojdy', 'lowicz', 'lublin', 'mragowo', 'nysa', 
    'olsztyn', 'ozarow', 'poznan', 'pulawy', 'rzeszow', 
    'silesia gliwice', 'skawina', 'slawa', 'sopot', 'szczyrk', 
    'tarnów', 'warsaw', 'wisla', 'wroclaw', 'wronie', 'zyrardow'],
  Portugal => ['cascais', 'estoril', 'lisbon', 'porto'],
  Qatar => ['doha'],
  Romania => ['braila', 'brasov', 'bucharest', 'cluj', 'deva', 'iasi',
    'oltenita', 'piatra neamt', 'sibiu', 'targoviste', 'timisoara'],
  Russia => ['lokotok', 'moscow', 'russia-pan', 'saint petersburg'],
  Scotland => ['edinburgh', 'glasgow'],
  Serbia => ['belgrade', 'beograd', 'jagodina', 'niš', 'novi sad', 
    'pancevo', 'vrnjacka banja'],
  Singapore => ['singapore city'],
  Slovakia => ['kosice', 'michalovce'],
  Slovenia => ['ljubljana'],
  Spain => ['barcelona', 'begues', 'cuenca', 'las palmas', 'madrid', 
    'marbella', 'palma', 'sabadell'],
  'South Africa' => ['durban'],
  Sweden => [
    'bromölla', 'fredrikstad', 'gnesta', 'göteborg', 'harplinge', 
    'leksand', 'lerum', 'lindesberg', 'linköping', 'malmö', 'näsby', 
    'norrbyskär', 'norrøna', 'stockholm', 'storsjöbygden', 'stureby', 
    'skara', 'snåsa', 'täby', 'täfteå', 'tofta', 'uddevalla',
    'umeå', 'uppsala', 'varberg', 
    'västervik', 'västerås', 'örebro', 'överum'],
  Switzerland => ['la chaux-de-fonds', 'nyon', 'zürich'],
  Taiwan => ['changhua', 'chiayi', 'hsinchu', 'jiangyou', 'kaohsiung',
    'keelung', 'miaoli', 'taichung', 'tainan', 'taoyuan', 'taipei city', 
    'new taipei city'],
  Thailand => ['bangkok', 'chumphon', 'pattaya', 'rayong', 'udon thani'],
  Tunisia => ['hammamet'],
  Turkmenistan => ['bereket'],
  Turkey => ['adalar', 'adana', 'adapazan', 'akhisar', 'aladag', 'ankara', 
    'antalya', 'atakum', 'aydin', 'ayvalik', 'balikesir', 'batman', 
    'bodrum', 'burdur', 'bursa', 'canakkale', 'cerkezkoy', 
    'cesme', 'corlu', 'datca', 'denizli', 'diyarbakir', 'edirne', 
    'erzurum', 'eskisehir', 'fethiye', 'foca', 'gaziantep zeugma', 
    'gelibolu', 'geyve', 'gölcük', 'hendek', 'iskenderun', 'isparta', 
    'istanbul', 'izmir', 'kadirli', 'karsiyaka', 'kastamonu', 'kayseri', 
    'kirklarelý', 'kirsehir', 'kocaeli', 'konya', 'koycegiz', 
    'kusadasi', 'kütahya', 'luleburgaz', 'malatya', 'manisa', 
    'mersin', 'midyat', 'milas', 'muðla', 'nazilli', 'nilüfer',
    'orhangazi', 'pamukkale', 'samsun', 'seferihisar', 'sivas', 
    'söke', 'taskopru', 'tekýrdag', 'tire', 'tonya', 'usak', 'van', 
    'yarýmca', 'yatagan', 'yedi eylul'],
  Ukraine => ['kiev'],
  'United Arab Emirates' => ['sharjah'],
  USA => ['atlanta', 'berkeley', 'chapel hill', 'chicago', 
    'evanston', 'ithaca', 'kansas city', 'new york city', 
    'philadelphia', 'st louis', 'stanford', 'urbana-champaign', 
    'waltham'],
  Venezuela => ['caracas']
);


my %CITY_TO_LOCALITY =
(
  Aladag => ['küp'],
  Ankara => ['çayyolu', 'kardelen', 'sansar'],
  Antalya => ['muratpasa'],
  Aydin => ['bozdogan'],
  Balchik => ['albena'],
  Beijing => ['shihua', 'yizhuang', 'yuquan'],
  Bodrum => ['gundogan', 'yalikavak'],
  Brasov => ['poiana brasov'],
  Brussels => ['uccle'],
  'Buenos Aires' => ['recoleta'],
  Bursa => ['yenisehir', 'yildirim'],
  Cairo => ['maadi'],
  'Courseulles-sur-Mer' => ['courseulles'],
  Deauville => ['barrière'],
  Denizli => ['akçeşme'],
  Eskisehir => ['viþnelik'],
  Frankfurt => ['freidorf'],
  Gevgelija => ['mrzenci'],
  Guangzhou => ['zhujiang'],
  Hamar => ['ridabu'],
  Hatay => ['karaçay'],
  'Hong Kong City' => ['fukien'],
  Istanbul => ['atakoy', 'bahce', 'bahcesehir', 'bayrampaþa',
    'bogazici', 'bormali', 'esenkent', 'fatih', 'fatih karagümrük',
    'göktürk', 'kadikoy', 'kartal', 'kocamustafapasa', 
    'kucukcekmece', 'pasham', 'polonezkoy', 'sancaktar', 'suralaya'],
  Izmir => ['balcova', 'bornova', 'buca', 'ege',
    'konak', 'narlidere', 'sirinyer'],
  Jakarta => ['makaliwe', 'senayan'],
  Jember => ['arjasa'],
  Kolkata => ['nagbagan'],
  Katowice => ['slaska'],
  Kayseri => ['pinarbasi'],
  Kocaeli => ['yarimca'],
  Krakow => ['korwin'],
  Lappeenranta => ['lappee'],
  London => ['chelsea', 'chislehurst'],
  Lublin => ['sarniak'],
  Lyon => ['brotteaux'],
  Magetan => ['sukomoro'],
  Makassar => ['losari'],
  Manado => ['leilem', 'manahasa'],
  Medan => ['cemara', 'simal'],
  Mersin => ['meski'],
  Monticiano => ['piloni'],
  Mumbai => ['borivli'],
  Nancy => ['jarville'],
  Nicosia => ['katok'],
  Niš => ['niski'],
  'Nové Město' => ['radkov'],
  Oslo => ['gardermoen'],
  Paris => ['palaiseau', 'saint honoré'],
  Pattaya => ['jomtien'],
  Pleven => ['kaylaka'],
  Poznan => ['wroble'],
  Pune => ['amanora'],
  Rome => ['olgiata', 'parioli'],
  Sabadell => ['sabadel'],
  Sanya => ['tianya'],
  'São Paulo' => ['unaós'],
  Semarang => ['poncol'],
  Shanghai => ['pudong', 'qiaoxie', 'yangpu'],
  'Singapore City' => ['tengah'],
  Sofia => ['lozenets', 'serdika', 'sredec'],
  'Stara Zagora' => ['beroe'],
  Sumedang => ['wadas'],
  Tallinn => ['männiku'],
  Tekýrdag => ['suleymanpasa'],
  'The Hague' => ['buitenhof'],
  Tianjin => ['huochetou'],
  Thessaloniki => ['lemvourgeio' ],
  Tokyo => ['narita'],
  Toulouse => ['baragnon'],
  Trondheim => ['heimdal'],
  Varberg => ['varbergshus'],
  Varna => ['avren'],
  Warsaw => ['bieniewo'],
  Wroclaw => ['wratislavia'],
  Wuxi => ['taihu'],
);


my %CITY_TO_UNIVERSITY =
(
  Airmadidi => ['Airmadidi Senior High School'],
  Ankara => ['Ankara University', 'Bilkent University',
    'Middle East Technical University'],
  Antalya => ['Akdeniz University', 'Antalya Halk Egitim'],
  Antwerp => ['Karel de Grote'],
  Bandung => ['Telkom University', 'Institut Teknologi Bandung'],
  Batu => ['batusida senior high school'],
  Beijing => ['Ren Da Fu Zhong', 'china central university of business'],
  Bengkulu => ['bengkulu senior high school'],
  Berkeley => ['University of California at Berkeley'],
  Bogor => ['bogor senior high school'],
  Budapest => ['Budapest University'],
  Changhua => ['Chien Kuo Senior High School'],
  'Chapel Hill' => ['University of North Carolina'],
  Chiayi => ['National Chung Cheng University'],
  Chicago => ['University of Chicago'],
  Depok => ['gunadarma university'],
  Edirne => ['Trakya University'],
  Eskisehir => ['Anadolu University', 'Osmangazi University'],
  Evanston => ['Northwestern University'],
  Gdansk => ['University of Gdansk'],
  Gresik => ['Universitas Muhammadiyah Gresik'],
  Grogol => ['Duta Bangsa College'],
  Hamburg => ['UBC Hamburg'],
  Hsinchu => ['Chung Hua University',
    'National Chiao Tung University',
    'National Tsing Hua University'],
  Istanbul => ['ITÜ Vakfi', 'Koc University', 
    'Yildiz Technical University', 'Marmara University'],
  Ithaca => ['Cornell University'],
  Izmir => ['Ege University'],
  Jakarta => ['Gunadurma', 'ITS IKOMA', 
    'Kusuma Bangsa', 'Nahdlatul Ulama Alumni', 
    'Sekolah Tinggi Ilmu Statistik', 'Sekolah Tinggi Teknologi'],
  Jember => ['University of Jember', 'Jember Senior High School'],
  Jiangsu => ['Jiangsu Tianyi'],
  Kediri => ['kediri senior high school'],
  Kedungwaru => ['kedungwaru senior high school'],
  Keelung => ['National Taiwan Ocean University'],
  Kirsehir => ['Kirsehir Republic Primary School'],
  Kocaeli => ['Kocaeli University'],
  Konya => ['Selçuk University'],
  Krakow => ['AGH Krakow'],
  Langkat => ['Langkat Senior High School'],
  Leuven => ['KU Leuven'],
  Lumajang => ['lumajang senior high school'],
  Magetan => ['magetan senior high school'],
  Makassar => ['Makassar University'],
  Malang => ['Brawijaya University'],
  Manado => ['Manado State University', 'Sam Ratulangi University'],
  Medan => ['Universitas Sumatera Utara'],
  Mersin => ['Tarsus American College'],
  Miaoli => ['Miaoli Senior High School'],
  'New Taipei City' => ['Fu Jen Catholic University'],
  'New York City' => ['Columbia University'],
  Nijmegen => ['radboud university'],
  Padang => ['Andalas University', 'University of Bung Hatta'],
  Paris => ['Paris ECE'],
  Paris => ['École Polytechnique', 'Paris ECE'],
  Palembang => ['Universitas Sriwijaya'],
  Pekanbaru => ['Riau University', 'Universitas Riau Bridge Club'],
  Pontianak => ['University of Tanjungpura'],
  Porto => ['University of Porto'],
  Potsdam => ['Universität Potsdam'],
  Rijeka => ['University of Rijeka'],
  Semarang => ['Diponegoro University'],
  Shenyang => ['Shenyang Ligong'],
  Stanford => ['Stanford University'],
  Sukomoro => ['sukomoro senior high school'],
  Surabaya => ['University of Airlangga', 'University of Surabaya',
    'Surabaya Senior High School'],
  Taichung => ['Chung Hwa Medical and Pharmaceutical University',
    'National Chung Hsing University'],
  'Taipei City' => ['National Chengchi University',
    'National Taiwan Normal University',
    'National Taiwan University',
    'Soochow University'],
  Targoviste => ['Valahia University'],
  Taoyuan => ['Chang Gung University'],
  Umeå => ['Umeå University'],
  'Urbana-Champaign' => ['University of Illinois'],
  Waltham => ['Brandeis'],
  Warsaw => ['University of Warsaw', 'Warsaw University of Technology'],
  Wroclaw => ['University of Wroclaw',
    'Wroclaw University of Science and Technology'],
  Yogyakarta => ['Universitas Gadjah Mada'],
  Zagreb => ['Croatia University', 'Zagreb University'],
);


my %CITY_TO_CLUB =
(
  Aachen => ['Aachener BC'],
  Aalborg => ['BK Nord'],
  Adana => ['Adana BSB'],
  Adapazan => ['Adapazan Briç SK'],
  Akhisar => ['Akhisar BS'],
  Aladag => ['küp bsk'],
  Alexandria => ['alexandria sporting club'],
  Amsterdam => ['Trifolium', 'Witte Huis', 'BC Modalfa'],
  Ankara => ['Ankara Kontrat', 'Ankara Sistematik', 'Baþkent Sekans BSK',
    'BH Koru BK', 'Jeofizik', 'Çayyolu BK'],
  Annecy => ['annecy bc'],
  Antalya => ['Antalya BSK', 'Antalya Tabip Odasi', 'Muratpasa Club'],
  Antony => ['Antony BC'],
  Arendal => ['Arendals BK'],
  Asenovgrad => ['BK Asenovgrad'],
  Atakum => ['Atakum Club'],
  Augsburg => ['Augsburg Augusta'],
  Aydin => ['Aydin 1923 BBSK', 'bozdogan club'],
  Balikesir => ['Balikesir BSK'],
  Ballerup => ['Ballerup BC'],
  Bamberg => ['BC Bamberger Reiter'],
  Bandung => ['EIBC Bandung'],
  Bangkok => ['Bangkok Bridge Club', 'RBSC Polo Club'],
  Barcelona => ['BCN Almirall', 'Bridge House', 'Bridge Turó',
    'BC Barcelona'],
  Batam => ['BP Batam'],
  Batman => ['Batman Genclik'],
  Beijing => ['Beijing Baxi Football', 'SPG Club'],
  Beirut => ['Hamra Club'],
  Belgrade => ['Crvena Zvezda'],
  Bengkalis => ['Bengkalis PT BSP'],
  Beograd => ['btbk'],
  Bergen => ['Bergen Akademiske', 'Åsane BK'],
  Berlin => ['BC 52 Berlin'],
  Bhubaneshwar => ['Odisha Secretariat Recreation Club'],
  Bielefeld => ['BC Bielefeld'],
  'Bielsko-Biala' => ['Bielski Klub Brydżowy GOK cards'],
  Bodrum => ['Bodrum BSK', 'Yalikavak SK'],
  Bodø => ['Bodø BK Lyn'],
  Bologna => ['Bridge Bologna'],
  Bonn => ['BC Bonn'],
  Braila => ['BC Braila'],
  Brasov => ['BC Brasov'],
  Bremen => ['BC Bremen'],
  Brussels => ['Brussels Bridge Club'],
  Bucharest => ['ATU Bucharest'],
  Budapest => ['Bajnok Bridzs Egyesület'],
  'Buenos Aires' => ['Harlequins BC'],
  Burdur => ['Bucak Bel.'],
  Burghausen => ['bc burghausen'],
  Bursa => ['BSB Kurek Ihtisas', 'Nilüfer Bld. BSK', 'BC Tofas',
    'Yildirimspor', 'Bursa BSK'],
  Bytom => ['BUKS Bytom'],
  Caen => ['Caen BC'],
  Cairo => ['El Ahly', 'El-Karma', 'El Shams Club', 'Wadi Degla'],
  Canakkale => ['Canakkale Tarim'],
  Cannareggio => ['Circolo del Bridge Cannareggio'],
  Cerkezkoy => ['Cerkezkoy SK'],
  Chennai => ['Madras Gymkhana Club', 'Alumni Club Chennai'],
  'Cherven Briag' => ['SK Karo'],
  Cimahi => ['GB Cimahi'],
  Clichy => ['BC Clichy'],
  'Czech-Pan' => ['jzd'],
  Copenhagen => ['One Eyed Jacks'],
  Corlu => ['corlu yildiz'],
  'Courseulles-sur-Mer' => ['BC Courseulles'],
  Darmstadt => ['BC Darmstadt Alert'],
  Datca => ['Datca SK'],
  Debrecen => ['Debrecen DEAC'],
  Delhi => ['Delhi Gymkhana Club'],
  Denizli => ['Akceþme Spor'],
  Deva => ['BC Deva'],
  Diyarbakir => ['Diyarbakýr Sur BSK', 'Dýcle Gençlýk'],
  Doha => ['Shemokh Club'],
  Dombivli => ['Dombivli BC'],
  Drammen => ['Drammen Arbeiderparti'],
  Edirne => ['Edirne GSK'],
  Enschede => ['Drienerlo'],
  Erzurum => ['Cedýt Ilica Sports'],
  Eskisehir => ['Anadolu Bridge Club', 'Eskisehir Adalar', 
    'Eskisehir Baðlar', 'Eskisehir Sports', 'Visnelik Club'],
  Essen => ['Essen 86'],
  Fethiye => ['Fethiye BSK'],
  Firenze => ['Circolo del Bridge Firenze'],
  Flekkefjord => ['Flekkefjord BK'],
  Foca => ['Foca Club'],
  Fosnavåg => ['Fosnavåg BK'],
  Frankfurt => ['Frankfurter TBC'],
  Førde => ['Førde BK'],
  Garches => ['BC Garches'],
  Geyve => ['Geyve Sports'],
  Giza => ['El Rabwa Club', 'Rabwa Club'],
  'Gjøvik og Vardal' => ['Gjøvik og Vardal BK'],
  Gölcük => ['Gölcük Club'],
  Göteborg => ['BK Everfresh', 'BK Lyx'],
  Groningen => ['BC de Zeerob', 'Hok Studiecentrum'],
  Guangdong => ['Guangdong Club'],
  Haderslev => ['Haderslev BC'],
  Hamar => ['Hamar BK'],
  Hamburg => ['Hanseatic Hamburg BC'],
  Hannover => ['BTSC Hannover'],
  Harplinge => ['Harplinge BK'],
  Harstad => ['Harstad S&B', 'bk2000'],
  Havirov => ['Dorost Havirov'],
  Hendek => ['Hendek Kazimiye'],
  Herning => ['Herning BK'],
  Hillerød => ['Hillerød BK'],
  'Hong Kong City' => ['Fukien Athletic Club'],
  Hornbæk => ['Hornbæk BK'],
  Hyderabad => ['Deccan Club',
    'jubilee hills international centre'],
  Iasi => ['BC Iasi'],
  'Indonesia-Pan' => ['Balai Pelaksanaan Jalan Nasional',
    'Bridge Tunas Cahaya', 'EIBC', 'Gala Tawa Bridge Club'],
  Iskenderun => ['Iskenderun IHS'],
  Isparta => ['Isparta Club'],
  Istanbul => ['ABK', 'Altinay SK', 'Atakoy BSK', 'Atletik Basket', 
    'Avrasya SK', 'Bahcesehir Club', 'Bakýrköy Briç SK', 
    'bayrampaþa Club', 'Besiktas', 'Bogazici BSK', 'Camlica Sports', 
    'Corlu Avrasya', 'Fatih Karagümrük SK', 'Fenerbahce', 'Galata', 
    'Galatasaray', 'Göktürk SK', 'GSD Club', 'Heybeliada SK', 
    'Hosgoru', 'Istanbul Sports', 'Kadikoy BSK', 'Kartal Club', 
    'Kocamustafapasa SK', 'Kucukcekmece BK', 'Majör Boğaziçi', 
    'Major Hosgoru', 'Sancaktar GSK', 'Slem Bric SK', 'Vefa SK'], 
  Izmir => ['Altay SK', 'Arkas SK', 'Bornova BSK', 'Buca Belediye',
    'Buca Sports', 'Goztepe Hilal SK', 'Izmir BSB', 'Sirinyer Sports', 
    'Ege Club', 'Karsiyaka BSK', 'Narlidere Club', 'Cimentas Club', 
    'Konak Club'],
  Jakarta => ['Bhinneka Bridge Club', 'Gabrial University of Indonesia', 
    'Jakarta BBG', 'Pelatnas', 'Siwo Persatuan Wartawan Indonesia', 
    'Pertamina BC', 'EIBC Jakarta'],
  Jessheim => ['jessheim bk'],
  Kaohsiung => ['Kao Hsiung Club'],
  Karlsruhe => ['Karlsruher BSC', 'karlsruher'],
  Karsiyaka => ['Karsiyaka BSK'],
  Kastamonu => ['Kastamonu BSK'],
  Ketsch => ['BC Ketsch'],
  Kiel => ['BC Kiel'],
  Kinali => ['MBC Kinali'],
  Kirklarelý => ['Kirklarelý BSK'],
  Kocaeli => ['Kocaeli BSSK', 'Yarimca SK'],
  Kolkata => ['Hindusthan Club', 'calcutta cricket & football club',
    'Calcutta Bridge Club', 'Nagbagan Card Club'],
  Kornik => ['OAZA Kornik'],
  Kota => ['Kota Club'],
  Koycegiz => ['Koycegiz BSK'],
  Köln => ['Köln Lindenthal BC'],
  Krakow => ['Cracovia 1906'],
  Kristiansand => ['Kristiansand BK'],
  'Kuala Lumpur' => ['Royal Selangor Club'],
  Kunshan => ['Kunshan Qiaoxie'],
  Kusadasi => ['Kusadasi BSK'],
  'La Spezia' => ['Spezia'],
  Lecco => ['Resegone LC'],
  Leksand => ['DBK Dalom'],
  Leverkusen => ['Nachteulen Leverkusen'],
  Lille => ['BC de Lille'],
  Lindesberg => ['Lindesbergs BS'],
  Linköping => ['Smedstadens BK'],
  Lisbon => ['Armando and Viviane Gonçalves Pereira',
    'Benfica', 'Clube de Bridge dos Engenheiros',
    'Núcleo De Bridge Do Círculo', 'Sporting Lisbon'],
  Lodi => ['Fanfulla'],
  Lom => ['Øvre Ottadalen'],
  London => ['TGR', 'Royal Air Force Club'],
  Luleburgaz => ['LÜKSAD'],
  Lyon => ['BC Brotteaux'],
  Makassar => ['Makassar Utama'],
  Malatya => ['Malatya Yildiz Dogu', 'Malatyagücü', 'Malatya BSK'],
  Malmö => ['Malmö BK Scania'],
  Manado => ['CFT Bridge', 'Sekolah Bridge Tonaas Wangko',
    'Swara Kita BS'],
  Manisa => ['Manisa BSK', 'Vestel SK'],
  Manna => ['Manna Bridge Club'],
  Mannheim => ['BC Alert Mannheim', 'BC Universität Mannheim'],
  Marseille => ['Ocean BC'],
  Massy => ['BC Massy'],
  Mersin => ['Mersin Club', 'Meski Club'],
  Midyat => ['Midyat Club'],
  Milan => ['BC Milano', 'Milan CPK Milanowek'],
  Milas => ['Milas Club'],
  Miskolc => ['miskolc deac'],
  'Mo i Rana' => ['Mo'],
  Moradabad => ['KDI Moradabad'],
  Moscow => ['Avalanche BC'],
  Moss => ['Moss BK'],
  Mragowo => ['Mragowia'],
  Munich => ['bc münchen'],
  Muðla => ['Muðla GSK'],
  Mumbai => ['ABA Mumbai', 'Matunga', 'Otters Club', 
    'The West End Mumbai', 'WCG Mumbai', 'Bombay Gymkhana Club',
    'willingdon sports club', 'Borivli Sports Club'],
  Namsos => ['Namsos BK'],
  Nanchong => ['Shou Chuang'],
  Nancy => ['Nancy Jarville BC'],
  Napoli => ['Circolo Nautico Posillipo'],
  Narvik => ['Narvik BS'],
  Nashik => ['NDBAC Nashik'],
  Nazilli => ['Nazilli BBSK'],
  Näsby => ['Näsby BS'],
  Nice => ['Colonial BC'],
  Nilüfer => ['nilüfer bld. bsk', 'yildirimspor'],
  Niš => ['nbk', 'niski bridge club'],
  Noida => ['Avi Club Noida'],
  Norrøna => ['BK Norrøna'],
  'Novi Sad' => ['NS-1'],
  Nürnberg => ['Nürnberg Museum'],
  Nærbø => ['Nærbø BK'],
  Næstved => ['Næstved BK'],
  Nøtterøy => ['Nøtterøy BK'],
  Odense => ['BK 1936', 'Odense BK'],
  Ogndal => ['Ogndal BK'],
  Oldenburg => ['bc oldenburg'],
  Oltenita => ['Phoenix Oltenita'],
  Orhangazi => ['orhangazi sk'],
  Oslo => ['Hoppklubbene', 'OBK Kløverknekt', 'Solli', 'Top Bridge BC'],
  Ozarow => ['Centrum Kultury i Sportu Oze'],
  Örebro => ['Örebridgen'],
  Padang => ['Agriculture Bridge Club', 'Semen Padang'],
  Padova => ['Padova Bridge SS'],
  Palermo => ['Circolo del Tennis Palermo'],
  Pamukkale => ['Pamukkale SK'],
  Palu => ['Maesa Palu'],
  Paris => ['Paris Sud', 'BC Saint Honoré', 'Paris Bridge',
    'Friedland BC'],
  Pattaya => ['Pattaya BC'],
  Pärnu => ['Pärnu BK', 'Jomtien Bridge Club'],
  Pekanbaru => ['Rumah Sakit Umum Daerah Pekanbaru', 'Laksamana BSP'],
  Pescara => ['Pescara Bridge'],
  Pontianak => ['Fakultas Teknik Bridge Club Universitas Tanjungpura'],
  Porto => ['Dragao', 'Porto Club'],
  Poznan => ['RAL Poznan'],
  Prague => ['Acol Praha', 'Zmrzlina'],
  'Reggio Calabria' => ['Circolo del Bridge N. Ditto Reggio Calabria'],
  Radkov => ['ksb radkov'],
  'Reggio Emilia' => ['ASD Reggio Emilia'],
  Rennes => ['BC Rennais'],
  Reykjavik => ['Grant Thornton', 'Vestri'],
  Rieneck => ['Kultcamp Rieneck'],
  Romana => ['Romana Bridge'],
  Rome => ['Tennis Club Parioli', 'Star Bridge Roma', 
    'SSD Angelini Bridge', 'Nuovo Bridge Insieme', 'ASD Tennis Roma'],
  Rotterdam => ['bc de lombard'],
  'Russia-Pan' => ['BC Real'],
  Rødovre => ['Rødovre BK'],
  Saarbrücken => ['BC Saarbrücken 1984'],
  Salerno => ['asb salerno'],
  Samsun => ['Samsun BK'], 
  'San Luis' => ['Salmun BC'],
  Sarpsborg => ['Østfold og Follo'],
  'Schwäbisch Hall' => ['BC Schwäbisch Hall'],
  Seferihisar => ['Seferihisar Municipality'],
  Shanghai => ['Qi Zhong Club', 'Qizhong', 'Pudong Club'],
  Shaoguan => ['Shaoguan BA'],
  Sharjah => ['Sharja Club'],
  Singsås => ['Singsås BK'],
  Sivas => ['Sivasspor'],
  Skara => ['skara bs'],
  Skawina => ['centrum kultury i sportu skawina'],
  Ski => ['Ski BK'],
  Slagelse => ['BK 83 Slagelse'],
  Sofia => ['Bonsist', 'Quantum BC'],
  Solok => ['ebc solok'],
  Sortland => ['sortland bk'],
  Söke => ['söke bsk'],
  Stavanger => ['stavanger bk'],
  Steinkjer => ['Steinkjer BK'],
  Stockholm => ['BC Herkules', 'BK Lavec Smile', 'Lavec', 'S:t Erik'],
  Stoholm => ['Fjends BK'],
  Storsjöbygden => ['Storsjöbygdens BK'],
  Stuttgart => ['bc stuttgart'],
  Sunndalsøra => ['Sunndalsøra BK'],
  Suzhou => ['suzhou qiaoxie'],
  Søborg => ['Blakset Klubberne'],
  Sørreisa => ['Sørreisa BK'],
  Taskopru => ['taskopru club'],
  Täby => ['Norrorts Bridge', 'Täby BK'],
  Tekýrdag => ['Cerkezkoy Dinamik BSK', 'Kapakli Sýte', 'Tekirdað Club',
    'Suleymanpasa Club'],
  'Tel Aviv' => ['ASA University of Tel Aviv'],
  Tire => ['Tire BSK'],
  Tomohon => ['Gereja Masehi Injili di Minahasa'],
  Tonya => ['Tonyaspor'],
  Torino => ['Torino Allegra'],
  Toulouse => ['Bridge Académie Toulouse', 'Toulouse BC',
    'Baragnon BC'],
  Tours => ['Cercle Tourangeau'],
  Trieste => ['bc trieste'],
  Tromsø => ['Tromsø BK'],
  Trondheim => ['Studentenes BK', 'Heimdal BK'],
  Udaipur => ['field club udaipur'],
  Umeå => ['BK Björken'],
  Uppsala => ['BK Fyris Skalman', 'BK Svanslös Skalman', 
    'Uppsalabridgen'],
  Usak => ['Usak SK'],
  Utrecht => ['BC Star', 'Bridgeclub Oog', 'NDC Den Hommel'],
  Van => ['Van Bric SK'],
  Vasa => ['vasa bk'],
  Västerås => ['ABB BK', 'Västeråsbridgen', 'Top Bridge BC'],
  Vejle => ['Klør 10 Vejle'],
  Venice => ['Circolo del Bridge Venezia'],
  Vestvågøy => ['Vestvågøy SK'],
  Vikersund => ['vikersund bk'],
  'Villa Fabbriche' => ['ASD Villa Fabbriche'],
  Vorden => ["'t Onstein"],
  Vraca => ['Botev'],
  Warsaw => ['Auguri Warsaw', 'Spojnia', 'Unia'],
  Wroclaw => ['Ruch AZS', 'Ruch SA'],
  Yatagan => ['Yatagan SK'],
  Zagreb => ['Locomotiva'],
  'Zhong Jian' => ['Zhong Jian Club'],
  Zürich => ['Zurich Enge'],
  Zyrardow => ['ck zyrardow'],
  Åkirkeby => ['Åkirkeby BK'],
  Ålesund => ['BK Grand', 'Møre og Romsdal'],
  Århus => ['akademisk bridgeklub', 'Århus BK'],
  Åsane => ['Åsane BK']
);

my %COUNTRY_TO_SPONSOR =
(
  Australia => ['Derofe', 'Penline'],
  Austria => ['Lupo Veloce'],
  Belarus => ['MB-Transit'],
  Belgium => ['belisol'],
  Bermuda => ['Orbis Investment Management'],
  Brazil => ['Rio-Sampa'],
  Bulgaria => ['Chateau Rossenovo', 'Gillette', 'Impress', 'Malkia', 
    'Mech-Ok', 'Sevtopolis', 'Struma', 'Unicat', 'Velbazhd',
    'Velbujd', 'Vinex Preslav', 'Vito'],
  Chile => ['fullbridge'],
  China => ['Beibao', 'Beidike', 'Beijing Capital', 'Beijing Cartoon', 
    'Beijing Dazhong', 'Beijing Evertrust', 'Beijing Huayuan', 
    'Beijing Hull Technology', 'Beijing Jinghua', 'Beijing Lawyers', 
    'Beijing Liuhe', 'Beijing Longxin', 'Beijing Railway Bureau', 
    'Beijing ShouChuang', 'Beijing Trinergy', 'Beijing Wan Jia', 
    'Beijing Yue Ze', 'Beijing Yindi', 'Bnerg', 'Cai Fu Zheng Quan',
    'Changyu', 'China Evertrust', 'China Finance', 'China Global Times',
    'China National Petroleum Corporation', 'China Ping An',
    'China Renshou', 'China Resources', 'China Trinergy', 
    'Chinese Hailian', 'Chuanmei', 'Copia', 'Dalian Dichan', 'Datang', 
    'Dian Zi Cheng', 'Dianwang', 'Dongfeng', 'Dongfang Tairong', 
    'Evertrust', 'Fanhua Jituan', 'Geely Automobile', 'Gong Hang Jin Ying', 
    'Guangdong Huachu Chemicals', 'Guangzhou Hongmian',
    'Guangzhou Huachu Chemicals', 'Guangzhou Pearl River',
    'Guiyuang Bank', 'Haerbin Bingxue', 'Hai Long', 'Hainan Shichuang',
    'Hainan Window', 'Hangzhou Jinjiang', 'Heilongjiang Tea',
    'Heng Yuan Xiang', 'Hengsha Haijiu', 'Hengsha Ke Ji', 'HNA',
    'Hong Zhu', 'Hongyu', 'Huachu', 'Huangshi Qixing', 'Huayuan', 
    'Hubei Dongfeng', 'Hubei Yihua', 'Hunan Tou Zhan', 'Jetox',
    'Jiang You', 'Jiegao', 'Jilin Dingyuan', 'Jin Rong', 'Jin Jing', 
    'Jinfan', 'Jing Tie', 'Kuncheng Group', 'LCG', 'Lianbo', 
    'Lianzhong Shi Jie', 'Longjiangfu', 'Lu Cheng', 'Lu Ning Coal', 
    'Lv Hua', 'Mai Zi Fu Shi', 'Mei Kuang', 'Meilin Qing Cheng', 
    'Nanfang Dianwang', 'Nanguang Power', 'Nanning Yalun', 'Nanyuan', 
    'Nong Fa Hang', 'Nongken', 'Norco', 'Oly-Star', 'Pan China Group',
    'PD Real Estate', 
    'PD Times', 'PD Transnational', 'Pan China Construction', 'Pufa',
    'Qiaoyou', 'Qingnian Qiche', 'Red Cotton', 'Ruyi', 'SAIC VW',
    'San Yutian', 'Sanya Jiguan', 'Sanya Tianze', 'Shan Hai', 
    'Shanghai Automobile', 'Shanghai Changyu', 'Shanghai Financial', 
    'Shanghai Gaohe', 
    'Shanghai Jiahua', 'Shanghai Jinchang', 'Shanghai Ling Mu', 
    'Shanghai Municipal Engineering Group', 'Shanghai Qiche', 
    'Shanghai Qihao', 'Shanghai Qi Zhong', 'Shanghai Weiyu', 
    'Shanghai Zhongfu', 'Shanxi Luning', 'Shanxi Qinlian', 'Shen Jiu', 
    'Sheng Tao Sha', 'Sheng Yu Tian', 'Sheng Yuan', 
    'Shenzhen Electronic City', 'Shenzhen Lanpu', 'Shenzhen Nangang', 
    'Shenzhen Ping An', 'Shenzhen Qiayao', 'Shenzhen Topone Car', 
    'Shi He Dong Li', 'Shi You', 'Shichuang', 'Shiji Changda', 
    'Shouchuang', 'Sichuan Dahe', 'Sunchime Cartoon', 'Sunchime Fund', 
    'Sung Tao', 'Suzhou Youtong', 'SY Sheng Yutain', 'TianJin JS2',
    'Tielu Jixie', 'Tin Fok', 'Tsingtao', 'Wuhan Dongfang', 
    'Xiamen Xiashun', 'Xiao Ying', 'Yalu Group', 'Yibin China Resources', 
    'Yi Tong', 'Yuetao', 'Yufeng Electric', 'Yunnan Dikuang Resources', 
    'Yunnan Tongya', 'Zhaoeng', 'Zhe Da Wang Xin', 'zhejiang huamen',
    'Zhejiang Jingfan', 
    'Zhejiang Jinjian', 'Zhejiang Xinxiang', 'Zhenjiang Hanbang', 
    'Zhong Guo Ren Bao', 'Zhong Liang Y LW', 'Zhong Yuan', 'Zhonghai', 
    'Zhongshan Jiegao', 'Zhongtong Jiangsu', 'Zhu Jiang'],
  Croatia => ['Atlantic Trade', 'Mireo', 'Termoavion'],
  Denmark => ['Nordfyns Finans', 'Team Audita', 'Team PharmaService',
    'XP Digital'],
  England => ['Pharon', 'Red Bull'],
  Estonia => ['Baltic Express', 'Druva', 'Eksprompt', 'Kilogrupp',
    'Pealinn', 'Printerikeskus', 'Raam', 'Unibet', 'Viru Valge',
    'Z-Tech'],
  Finland => ['Näkösoppi', 'Nordic Security'],
  France => ['BridgePlus', 'Cap Gemini', 'Funbridge', 'Jet Immo', 
    'Multicoms', 'Société Générale'],
  Germany => ['Allianz', 'Paulaner'],
  Greece => ['Tzilis'],
  'Hong Kong' => ['AIA', 'Hong Kong Vico', 'JP Morgan', 'L&Y Law',
    'Phoenix TV', 'Wellwise'],
  Hungary => ['Ecosoft', 'Elastron', 'GAMAX', 'Interface', 
    'Nimbusz', 'Visoft'],
  Iceland => ['101 Fasteignasala', 'Actavis',
    'Breki Jarðverk', 'Bridgefélag Reykjavíkur', 'Bústólpi ehf', 
    'Eimskip', 'Enorma', 'ESSO', 'Ferðaskrifstofa Vesturlands', 
    'Fisk Seafood', 'Garðar & Vélar', 'Garðs Apotek', 'Gevalia', 'GSE', 
    'Haustak', 'HF Verðbréf', 'Hreint ehf', 'Iceland Express', 'Kvika',
    'Lögfræðiskrifstofa Islands', 'Lögfræðistofa Bjarna', 'Lyfjaver',
    'Málning hf', 'Morgunblaðið', 'Myndform', 'Ráðgjöf', 'Sagaplast',
    'Skeljungur', 'Skinney-Þinganes', 'Sölufélag Garðyrkjumanna',
    'Sparisjóður', 'Sparisjóður Keflavik', 'Sparisjóður Norðfjörður',
    'Sparisjóður Siglufjarðar', 'SR Group', 'VBS Fjárfestingarbanki hf.',
    'Vidbot ehf', 'Vinabær', 'Virnet', 'VÍS', 'Tryggingamiðstöðin',
    'Wise'],
  India => ['Accenture', 'Andromeda Baroda', 'APRA Clothing', 'Avia',
    'Bajaj', 'Bangur Cement', 'Baroda Bank', 'BridgeYes.com', 'Cable',
    'Central Secretariat', 'Chennai Online', 'Constellation',
    'Cosmos', 'Dhampur Sugar', 'Eden Realty Kolkata', 'eDOT Goa',
    'Enterprise', 'Godfrey Phillips', 'HCL', 'India Glycols', 
    'Indian Medical', 'Indian Oil', 'Indian Overseas Bank',
    'Indian Railways', 'Interkala', 'Jain Group', 'Kaushik Hyderabad', 
    'KH Power', "Kini's Bangalore", "Kini's Goa", 'Kosmos Delhi', 
    'Krishnapatnam Port',
    'Manyavar', 'Mayur Renergy', 'NALCO', 'Navachaitanya', 'Navayuga', 
    'Nest Inn', 'OCI Copper', 'Poddar Developers', 'Poddar Housing', 
    'Quik Tea', 'Ryan Express', 'Ryka', 'SD Associates', 'SD Enterprises',
    'Shree Cement', 'Shree Radhey', 'Smart Max', 'Srenniw', 'SSDA', 
    'Tata Consulting Services', 'Taste of Goa', 'Team Secure', 'Tekser', 
    'Tolani Shipping Ltd', 'Trambak Rubber', 'Tricon Infotech', 
    'TTK Healthcare', 'TVS Tread', 'UTI Bank', 'Wellknit'],
  Indonesia => ['Abadi Adimulia', 'Adaro Energy', 'Aerospace', 
    'Agsar Paints', 'Aklindo', 'Asindo', 'Asindo Prima', 
    'Bank Indonesia', 'Bank Mandiri', 'Bank Negara Indonesia', 
    'Bank Tabungan Negara', 'Bengkalis PT', 'Cempaka', 'Dauna Winaza',
    'Djarum', 'Djarum Black', 'Electric Center', 'Elektrik P3B',
    'Elektrika', 'Geo BSP', 'Geo Kideco', 'Geo Pertamina', 'Geo Timah', 
    'Geo Vale', 'Geologi', 'Geologi Banpu', 'Geoportal Kutai Kartanegara', 
    'Harke', 'Indoarsip', 'Intan', 'Inteligent', 'Indonesian Power',
    'Jasa Marga Jakarta', 'Kideko', 'Kombi Tondano', 'Makus', 
    'Mandiri Minahasa', 'Mitra Buana', 'Mutiara Energy', 'OICO Maesa',
    'P2TEL', 'Palma Karya Mandiri', 'Penajam PU', 'Perbankan Jatim',
    'Pertagas', 'Pertamina', 'Petroconas', 'PU Bitung', 'PU Minsel',
    'PU Sulut', 'Perusahaan Listrik Negara', 'Pimara', 'PLN Fortuga',
    'PLN Suluttenggo', 'PT Bayu Buana Gemilang', 'PT Bumi Siak Pusako',
    'Samadhan Academy', 'Sarunta Waya', 'Sehati',
    'Semangat Baru Makassar', 'Semen Gresik', 'Siwik Holiday Mragowo',
    'Siwik Intertrade', 'Syabas Energy', 'Telkom',
    'Telkom Groovia', 'Telkom IndiSchool', 'Telkom Indonesia',
    'Telkom Jabar', 'Telkom Jakarta', 'Telkom Speedy', 'Telkom UseeTV',
    'Telkom@wifi.id', 'Timah', 'TJ Jabung Brt', 'Tridaya', 'Videocon'],
  Italy => ['Argento', 'Bozzetto Azzurro', 'Carlo Bossi', 
    'Fantoni Vacations', 'Generali', 'Lavazza', 'Rosa dei Venti', 
    'Spasso Food'],
  Japan => ['Akebono', 'Hana', 'IMAX', 'monbu japanese ministry', 
    'NEC', 'Shimuzu'],
  Latvia => ['Laima', 'Pexis', 'Rigainvites.lv'],
  Lithuania => ['Garsu Pasaulis'],
  Malaysia => ['Likom', 'UMW'],
  Netherlands => ['Aquatrans', 'Arboned', 'Continental',
    'ING Bank', 'Melchemie', 'Modalfa', 'Ravebo', 
    'Twentebelt', 'VVE Beheer'],
  Norway => ['ABAX', 'Advisor Revisjon Norge', 'Astro A/S',
    'Bridge i Norge', 'Bridgemagasiner.no', 'FX Securities',
    'konkurs.no', 'Nortemp', 'Polarman Regnskap', 'Ragn Sells',
    'Tannlege Kvaran', 'Viego Regnskap'],
  Pakistan => ['Candyland', 'Century Insurance', 'Data Steel',
    'Kayseria', 'Solox'],
  Poland => ['A-Media Sieradz', 'Abnegat', 'AJ Diament', 
    'Alfa-Compensa Gdynia', 'Apreo Logistic Poland', 'Asko-Tech',
    'bridge24.pl', 'Budimex',
    'Chemikartel', 'Chlodnia', 'COMAL', 'Computerland', 'CONNECTOR',
    'Construction Kielce', 'CONSUS', 'Consus Carbon', 'Consus Oil',
    'Darles Santerm', 'Dermika', 'Dobre Zegary', 'domwaluty.pl',
    'E-Service',
    'Effcontrol', 'Eko-Al', 'Elektrociepl', 'Elektromonta¯',
    'Euro Agro', 'Energetyk', 'Falck Medical', 'Forta', 'forumbridge.pl',
    'Gomad', 'Honesta', 'Hotel Senator', 'Interbud Plock', 'Kadimex',
    'Kancelaria', 'Klika Murcki', 'KONKRET Chelmno', 'Konstanta',
    'Kurt-Royce', 'Lacznosc', 'Latteria TS Rzepin', 'Mega-Tech',
    'Nazwa', 'Nefka', 'Niewiem', 'NOTUS', 'Petro', 'POLFA', 'Ponar Unia',
    'Powszechna Kasa Oszczędności Bank Polski', 'Praterm', 
    'Prestige Development', 'Prokom', 'Relpol', 'Radex', 'Samsung', 
    'SAPW Poland', 'Signity', 'SPS Construction', 'Stalgast', 'Sygnity', 
    'Synergia Lublin', 'TAM Dabrowa', 'Termika', 'Termochem', 'Topeko', 
    'Unia Leszno', 'Unia Winkhaus', 'Unia Sygnitas', 'Vyceska', 
    'zagraj.pl', 'Zolza'],
  Romania => ['Logi Smart', 'Pharma Plus', 'Pro Consul', 
    'Samtronic Constanta'],
  Russia => ['Gazprom', 'Lukomorie', 'Moscow Sunday Times',
    'Russian Sunday Times', 'Staryi Master'],
  Serbia => ['Novi Kod'],
  Singapore => ['Saniva', 'Tyco', 'YOU Singapore'],
  Slovenia => ['Triglav Osiguranje'],
  Sweden => ['artotec', 'Bokadirekt SE', 'Brink Plast',
    'BridgeBertheau.com', 'Frissan', 'Hotell Strand', 'Konga-Väster',
    'Lag os', 'Junibacken', 'Ronke Camping', 'San-Sac', 'Scania',
    'Scania Bridgekonsul', 'Scandic', 'Stiga', 'Synective',
    'Transearly'],
  Switzerland => ['sportaccord'],
  Taiwan => ['Fatek', 'San Chen', 'Yeh Bros'],
  Thailand => ['Bangkok Bank', 'Metropolitan Electricity Authority',
    'See Fah/Thai', 'Thai Oil'],
  Turkey => ['Akaylar', 'Alfa Romeo', 'Aliaga Kyme', 'Altinay',
    'Ant Teknik', 'Arkas', 'Arma', 'Ayýntab', 'Balcova Termal', 'Baykar',
    'Caretta International', 'Cimentas', 'Dama Kupa', 'Denizgucu',
    'DISKI', 'Doga Naturale', 'Dostlar', 'Fora Lastik', 'Genkad',
    'Gözgöz', 'IBM', 'Inci Ayakkabi', 'Kare Dam', 'Magpa-Grup',
    'Maksoy-Deniz', 'Meditepe Tip', 'Ozyuva', 'Pusula',
    'Sanliurfa Tarim', 'Solakoglu', 'Son Dakika', 'Statu Denizcilik',
    'Tundem'],
  USA => ['Bridge Winners', 'PRI Investment']
);

my %COUNTRY_TO_NATIONALITY =
(
  Argentina => ['argentinian'],
  Australia => ['australian'],
  Austria => ['austrian'],
  Belarus => ['belarusian'],
  Belgium => ['belgian'],
  Bolivia => ['bolivian'],
  Brazil => ['brazilian'],
  Bulgaria => ['bulgarian'],
  Canada => ['canadian'],
  Chile => ['chilean'],
  Croatia => ['croatian'],
  'Czech Republic' => ['czech'],
  Egypt => ['egyptian'],
  England => ['english'],
  Estonia => ['estonian'],
  'Faroe Islands' => ['faroese'],
  Finland => ['finnish'],
  France => ['french'],
  Germany => ['german'],
  Greece =>['greek'],
  Hungary => ['hungarian'],
  Iceland => ['icelandic'],
  India => ['indian'],
  Indonesia => ['indonesian'],
  Ireland => ['irish'],
  Israel => ['israeli'],
  Italy => ['italian'],
  Japan => ['japanese'],
  Latvia => ['latvian'],
  Lebanon => ['lebanese'],
  Lithuania => ['lithuanian'],
  Netherlands => ['dutch'],
  Norway => ['norwegian'],
  Poland => ['polish'],
  Portugal => ['portuguese'],
  Romania => ['romanian'],
  Scotland => ['scottish'],
  Serbia => ['serbian'],
  'South Africa' => ['south african'],
  Spain => ['spanish'],
  Sweden => ['swedish'],
  Taiwan => ['taiwanese'],
  Turkey => ['turkish'],
  Tunisia => ['tunisian'],
  Wales => ['welsh']
);


sub set_matrix
{
  my ($whole) = @_;
  $whole->set_matrix_link(\%COUNTRY_TO_REGION, 'COUNTRY', 'REGION');
  $whole->set_matrix_link(\%COUNTRY_TO_CITY, 'COUNTRY', 'CITY');
  $whole->set_matrix_link(\%CITY_TO_LOCALITY, 'CITY', 'LOCALITY');
  $whole->set_matrix_link(\%CITY_TO_UNIVERSITY, 'CITY', 'UNIVERSITY');
  $whole->set_matrix_link(\%CITY_TO_CLUB, 'CITY', 'CLUB');
  $whole->set_matrix_link(\%COUNTRY_TO_SPONSOR, 'COUNTRY', 'SPONSOR');
  $whole->set_matrix_link(\%COUNTRY_TO_NATIONALITY, 
    'COUNTRY', 'NATIONALITY');
}


sub get_city_club_list
{
  my ($city) = @_;
  return undef unless exists $CITY_TO_CLUB{$city};
  return $CITY_TO_CLUB{$city};
}


1;
