#!perl

package Connections::Matrix;

use v5.10;
use strict;
use warnings;
use utf8;
use open ':std', ':encoding(UTF-8)';


our @ISA = qw(Exporter);
our @EXPORT = qw(set_matrix);

use lib '..';
use Whole;


my %COUNTRY_TO_REGION =
(
  Afghanistan => ['badakhshan'],
  Argentina => ['patagonia'],
  Australia => ['australian central territory', 'new south wales',
    'northern territory', 'queensland', 'south australia', 
    'tasmania', 'victoria', 'western australia'],
  Austria => ['oberloiben', 'wachau'],
  Bangladesh => ['pirojpur'],
  Belarus => ['druts'],
  Brazil => ['bahia', 'comandatuba', 'rio de janeiro state'],
  Bulgaria => ['dobruja', 'pirin', 'rusenski lom', 'south bulgaria'],
  Canada => ['british columbia', 'manitoba', 'new brunswick',
    'nova scotia', 'ontario', 'saskatchewan', 'vancouver island'],
  China => ['anhui', 'chengmai', 'feixiang', 'fujian', 'gansu', 
    'guangdong', 'guangxi', 'guizhou', 'hainan', 'haixing', 'hebei', 
    'heilongjiang', 'henan', 'huabei', 'hubei', 'hunan', 'jiangsu', 
    'jiangxi', 'jilin', 'liaoning', 'pearl river', 'pudong', 'pufa',
    'qiantang', 'ren shou', 'shandong', 'shanxi', 'sichuan', 
    'suzhou taihu', 'tianya', 'tinglin', 'wujin', 'xizang', 'xinjiang', 
    'yongjia', 'yongjiang', 'yunnan', 'zhejiang', 'zhongshan'],
  Denmark => ['bogø', 'bornholm', 'fjends', 'fyn',
    'midtsjælland', 'sydvest'],
  Ecuador => ['galapagos]',
  England => ['aberdeenshire', 'cornwall', 'hampshire', 'suffork', 
    'yorkshire'],
  Finland => ['åland Islands'],
  France => ['ardennes', 'auvergne', 'aveyron', 'camargue', 'cantal', 
    'charente', 'chartreuse', 'corsica', 'franche-comté', 'herault', 
    'languedoc', 'loire', 'marne', 'normandy', 'occitanie', 'provence', 
    'pyrenees', 'quercy', 'riviera', 'yonne'],
  Germany => ['bayern', 'thüringen'],
  Greece => ['corfu', 'crete', 'paros', 'rhodes', 'santorini',
    'thassos'],
  Iceland => ['eyjafjallajokull', 'kaldbakur'],
  Iraq => ['mesopotamia'],
  Hungary => ['hegyvidék'],
  India => ['andhra pradesh', 'bihar', 'bengal', 'ganges', 'goa', 
    'gujarat', 'haryana', 'himachal pradesh', 'jharkhand', 
    'karnataka', 'kerala', 'madhya pradesh', 'maharashtra', 'malwa', 
    'national capital region', 'odisha', 'punjab', 'rajasthan', 
    'rajputana', 'sahyadri', 'tamil nadu', 'telengana', 'tonk state', 
    'uttar pradesh', 'uttarakhand', 'west bengal'],
  Indonesia => ['aceh', 'badung', 'bali', 'bangka belitung', 'banten', 
    'belitung', 'bengkayang', 'bisma semarang', 'boeven digoel', 
    'bone bolango', 'borneo', 'bungo', 'central celebes', 
    'central java', 'central sulawesi', 'east borneo', 'east jakarta', 
    'east java', 'east kalimantan', 'east nusa tenggara', 
    'gabungan malaku', 'gorontalo', 'indragiri hulu', 'java',
    'java bali', 'kabupaten bekasi', 'kabupaten blitar', 
    'kabupaten bogor', 'kabupaten cianjur', 'kabupaten garut', 
    'kabupaten gresik', 'kabupaten jember', 'kabupaten karawang', 
    'kabupaten kepulauan talaud', 'kabupaten ketapang', 
    'kabupaten kudus', 'kabupaten langkat', 'kabupaten lumajang', 
    'kabupaten minahasa', 'kabupaten nganjuk', 'kabupaten pacitan', 
    'kabupaten palu', 'kabupaten pamekasan', 'kabupaten pasuruan', 
    'kabupaten pessel', 'kabupaten sidoarjo', 'kabupaten sijunjung', 
    'kabupaten solok', 'kabupaten tabalong', 'kapuas hulu', 'kawanua', 
    'kayong utara', 
    'kedungwaru', 'kepri', 'kepulauan riau', 'kepulauan seribu', 
    'kotawaringin timur', 'kubu raya', 'kutai kartanegara', 
    'kutai timur', 'lampung', 'lebak', 'lombok', 'mount mahawu',
    'maluku', 'minahasa', 'minang', 'natuna', 'ngawi', 'north minahasa', 
    'north celebes', 'north sulawesi', 'north sumatra', 
    'nusa tenggara barat', 'nusantara', 'papua', 'porong', 'sambas', 
    'sanggau', 'sintang', 'sitaro', 'south celebes', 
    'south east celebes', 'south jakarta', 'south kalimantan', 
    'south sulawesi', 'south sumatra', 'southeast sulawesi', 
    'sulawesi', 'sumatra', 'tala', 'tambun', 'tanah laut', 
    'west borneo', 'west java', 'west kalimantan', 
    'west nusa tenggara', 'west sulawesi', 'west sumatra'],
  Iran => ['khuzestan'],
  Iraq => ['akkad'],
  Israel => ['arunachava', 'negev'],
  Italy => ['lake como', 'lake garda', 'liguria', 'olona', 'piemonte',
    'sardinia', 'sicily', 'trentino', 'tuscany', 'val di magra', 
    'valsugana'],
  Japan => ['fuji', 'kansai', 'kanto', 'wakayama'],
  Lithuania => ['suvalkija'],
  Mexico => ['jalisco'],
  Netherlands => ['gelderland', 'overijssel'],
  'New Zealand' => ['central districts', 'northland',
    'otago', 'southland', 'waikato'],
  Norway => ['agder', 'aurland', 'buskerud', 'flakstad', 'finnmark',
    'frøya', 'haugaland', 'hedmark', 'hordaland', 'innlandet',
    'lofoten og vesterålen', 'midt trøndelag', 'mjøsa', 'møre romsdal', 
    'nord trøndelag', 'nord-norge omegn', 'nordafjells', 
    'nordland', 'northern norway', 'ringvassøy', 'rogaland', 
    'rosfjord', 'salten', 'sørlandet', 'sør-trøndelag', 'telemark', 
    'troms og ofoten', 'trøndelag', 'vest agder', 'vest finnmark', 
    'vestland', 'østfold follo'],
  Pakistan => ['sindh', 'tharparkar', 'wielkopolska'],
  Peru => ['altiplano'],
  Poland => ['biala podlaska', 'lower silesia', 'mazovia', 'pomerania', 
    'silesia', 'slask'. 'warminsko-mazurskie'],
  Portugal => ['algarve', 'azores', 'bairrada', 'madeira', 'norte ilhas'],
  Romania => ['transylvania'],
  Russia => ['pasha', 'siberia'],
  Scotland => ['ayrshire', 'speyside'],
  Serbia => ['vojvodina'],
  'South Africa' => ['central gauteng', 'eastern cape', 'gauteng',
    'kwazulu natal', 'northern gauteng', 'transvaal',
    'western province'],
  'South Korea' => ['silla'],
  Spain => ['andalusia', 'bizkaia', 'canary islands', 'catalonia', 
    'gran canaria', 'iberia', 'mallorca', 'menorca', 'rioja', 'tenerife'],
  Sweden => ['blekinge', 'norrland', 'jämtland', 'norrorts', 'skåne', 
    'småland', 'south sweden'],
  Switzerland => ['sallière', 'schwyz', 'wyssa'],
  Taiwan => ['west district'],
  Tanzania => ['kilimanjaro'],
  Thailand => ['amnat charoen', 'benchamas', 'buriram', 'khon kaen', 
    'krabi', 'maha sarakham', 'nakhon nayok', 'nakhon pathom', 
    'nakhon sawan', 'nakhon si thammarat', 'narathiwat', 'phatthalung',
    'prachinburi', 'ratchaburi', 'samut prakan', 'samut sakhon', 
    'sa kaeo', 'si sa ket', 'suphan buri'],
  Turkey => ['aegean sea', 'akdeniz', 'anatolia', 'ararat', 'bolu',
    'çankiri', 'cappadocia', 'central anatolia', 'cukurova', 
    'datca yarimada', 'dersim', 'dobruca', 'dogu akdeniz', 'hatay', 
    'hemshin', 'iskele', 'karadeniz', 'karadon', 'karimata', 
    'kizil', 'kurdistan', 'manle', 'marmara', 'misya', 'muallim', 
    'munzur', 'mysia', 'narman', 'north cyprus', 'orontes', 
    'park firtina', 'rize', 'sakarya', 'saros', 'thrace', 'tigris', 
    'tunceli', 'uludag', 'uzungol', 'yozgat'],
  'United Kingdom' => ['gibraltar'],
  USA => ['alabama', 'alaska', 'arizona', 'arkansas', 'california', 
    'colorado', 'connecticut', 'district of columbia', 'florida', 
    'guam', 'hawaii', 'idaho', 'illinois', 'indiana', 'iowa', 
    'kansas', 'kentucky', 'louisiana', 'maine', 'maryland', 
    'massachusetts', 'maui', 'michigan', 'minnesota', 'mississippi', 
    'missouri', 'montana', 'nebraska', 'nevada', 'new hampshire',
    'new jersey', 'new york', 'north carolina', 'north dakota', 
    'ohio', 'oklahoma', 'oregon', 'pennsylvania', 'rhode island',
    'smoky mountains', 'south carolina', 'south dakota', 'tennessee', 
    'texas', 'utah', 'washington', 'wisconsin', 'wyoming'],
  Zimbabwe => ['matopos']
);


my %COUNTRY_TO_CITY =
(
  Algeria => ['relizane'],
  Andorra => ['meritxell'],
  Argentina => ['buenos aires', 'mar del plata', 'san luis'],
  Armenia => ['yerevan'],
  Australia => [
    'adelaide', 'banora point', 'brisbane', 'broadbeach', 'cairns', 
    'canberra', 'gold coast', 'hobart', 'melbourne', 
    'moonee ponds', 'perth', 'sydney', 'tweed heads'],
  Austria => ['graz', 'lambach', 'mautern', 'vienna'],
  Bangladesh => ['dhaka'],
  Belarus => ['minsk'],
  Belgium => ['antwerpen', 'bruges', 'brussels', 'charleroi',
    'gent', 'leuven', 'liège', 'ostend', 'waterloo'],
  Brazil => ['assis', 'belo horizonte', 'brasilia', 'buzios',
    'curitiba', 'florianopolis', 'pelotas', 'rio claro', 
    'rio de janeiro', 'são paulo'],
  Bulgaria => ['asenovec', 'asenovgrad', 'balchik', 'bansko', 'belene',
    'burgas', 'chavdar', 'chelopech', 'chepelare', 'cherven briag', 
    'dimitrovgrad', 'dobrich', 'doki', 'harmanli', 
    'haskovski mineralni bani', 'haskovo', 'jermen', 'karlovo', 
    'kavarna', 'kazanlak', 'kesten', 'kiten', 'kitka', 'kyustendil', 
    'la marina', 'lovech', 'momchilgrad', 'omurtag', 'panagyurishte', 
    'parvomay', 'pazardjik', 'pelotas', 'pernik', 'petrelik', 'pleven', 
    'pliska', 'plovdiv', 'popovo', 'preslav', 'priboi', 'primorsko', 
    'rakovski', 'razgrad', 'ruen', 'ruse', 'sevtopolis', 'shumen', 
    'silistra', 'slavyanovo', 'sliven', 'simeonovgrad', 'smolyan', 
    'sofia', 'sozopol', 'stara zagora', 'svilengrad', 'svishtov', 
    'varna', 'veliko tarnovo', 'velingrad', 'vraca', 'yambol', 
    'zavet'],
  Canada => ['calgary', 'cranbrook', 'edmonton', 'montreal',
    'new westminster', 'ottawa', 'quebec', 'smithers', 'toronto', 
    'vancouver', 'winnipeg'],
  Chile => ['paimado', 'santiago', 'talagante', 'temuco', 'vina del mar'],
  China => [
    'baimao', 'beihai', 'beijing', 'changzhou', 'chengdu', 'chongqing', 
    'dalian', 'dongguan', 'foshan', 'fuzhou', 'guangdong', 'guangzhou', 
    'guoxing', 'haikou', 'hangzhou', 'hebi', "huai'an", 'huayin', 
    'jiamusi', 'jiangyin', 'jianshe', 'jiangsu', 'jinchang', 
    'jincheng', 'jinjiang', 'jiujiang', 'jixiexiang', 'kunming',
    'kunshan', 'lanzhou', 'liandui', 'liushu', 
    'lufeng', 'mian yang', 'meilin qingcheng', 'nanchang', 'nanchong', 
    'nanjing', 'nanning', 'nantong', 'neijiang', 'ningbo', 'panzhihua', 
    'qingdao', 'rugao', 'ruian', 'sanya', 'shanghai', 'shangrao', 
    'shaoguan', 'shenyang', 'shenzhen', 'shijiazhuang', 'shouguang',
    'suqian', 'suzhou', 'taicang', 'taihu lake', 'taiyuan', 'taizhou', 
    'tianjin', 'wanzhou', 'wuhan', 'wuxi', 'wuzhishan', 'xin zhu', 
    'xiamen', 'xian', 'xiantao', 'xingdong', 'xinyi', 'xuzhou', 
    'yancheng', 'yangzhong', 'yangzhong shi', 'yanshi', 'yantai', 
    'yingshan', 'yizhuang', 'yuquan', 'yuzhou', 'zhaoqing', 
    'zhenjiang', 'zhong jian', 'zhongshan', 'zhuzhou', 'zigong', 
    'zigui'],
  Colombia => ['bogotá', 'cali', 'medellin'],
  'Costa Rica' => ['heledia'],
  Croatia => ['dubrovnik', 'kraljevica', 'opatija', 'pula', 'rijeka', 
    'samobor', 'split', 'zagreb'],
  Cyprus => ['larnaca', 'nicosia', 'protaras'],
  'Czech Republic' => ['havirov', 'nové město', 'prague', 'radkov'],
  Denmark => [
    'aabenraa', 'aalborg', 'asminderød', 'ballerup', 'copenhagen', 
    'esbjerg', 'farum', 'greve strand', 'haderslev', 'herning', 
    'hillerød', 'hjørring', 'hobro', 'hornbæk', 'horsens',
    'kalundborg', 'køge', 'morsø', 'morud', 'nuuk', 'nykøbing', 
    'næstved', 'odense', 'randers', 'ravnkilde', 'roskilde', 
    'rødovre', 'rønne', 'slagelse', 'stoholm', 'svendborg', 
    'svinninge', 'søborg', 'vejle', 'vodskov', 'viborg', 'åkirkeby', 
    'århus'],
  Ecuador => ['guayaquil'],
  Egypt => ['al-rabwa', 'alexandria', 'cairo', 'el-maadi', 'giza'],
  England => ['altrincham', 'bath', 'bedford', 'brighton', 'bristol',
    'canterbury', 
    'coventry', 'eastbourne', 'lincoln', 'liverpool', 'london', 
    'loughborough',
    'manchester', 'nottingham', 'oxford', 'petersfield', 
    'warwick',
    'wimbledon', 'wolverhampton', 'worcester'],
  Estonia => ['derpt', 'otepää', 'pärnu', 'rakvere', 'sindi', 
    'tallinn'],
  Finland => ['hanko', 'helsinki', 'kajaani', 'lappeenranta', 'kuopio', 
    'oulu', 'pieksämäki', 'puutalo', 'salo', 'turku', 'vadsø', 
    'vasa'],
  France => ['ainhoa', 'aix en provence', 'angers', 'annecy', 'antibes', 
    'antony', 'aubagne', 'avignon', 'beaulieu-sur-mer', 'bergues', 
    'biarritz', 'blois', "bois-d'amont", 'bordeaux', 'caen', 'calais', 
    'cannel', 'cassel', 'castres', 'chartres', 'chaville', 'clichy', 
    'colmar', 'courseulles-sur-mer', 'dambron', 'deauville', 
    'decazeville', 'dijon', 'felletin', 'fussey', 'garches', 
    'grande-motte', 'grenoble', 'hurepoix', 'issans', 
    'la baule-escoublac', 'la rochelle', 'le bouscat', 'lille', 'lyon', 
    'maillé', 'marseille', 'massy', 'meursac', 
    'montélimar', 'montpellier', 'mulhouse', 'nancy', 
    'nantes', 'nice', 'nimes', 'orly', 'paris', 'pau', 'perpignan', 
    'plumergat', 'poitiers', 'reims', 'rennes', 'royan', 'saint-aubin', 
    'saint-gelais', 'saint-ours', 'seine-et-marne', 'strasbourg', 
    "tain l'hermitage", 'thoisy', 'toulon', 
    'toulouse', 'tours', 'val de seine', 
    'valenciennes', 'vence', 'versailles', 'villeurbanne'],
  'French Polynesia' => ['bora bora'],
  Georgia => ['batumi', 'tbilisi'],
  Germany => ['aachen', 'augsburg', 'bad griesbach', 'bamberg', 'berlin', 
    'bielefeld', 'bochum', 'bonn', 'böblingen', 'bremen', 'burghausen', 
    'darmstadt', 'dortmund', 'düsseldorf', 'essen', 'frankfurt', 
    'freiburg', 'fritzlar', 'gütersloh', 'hamburg', 'hanau', 'hannover', 
    'heikendorf', 'karlsruhe', 'kassel', 'ketsch', 'kiel', 'kleve', 
    'köln', 'leipzig', 'leverkusen', 'lübeck', 'mainz', 'mannheim', 
    'munich', 'neuruppin', 'niedernhausen', 'nürnberg', 'oldenburg', 
    'osnabrück', 'potsdam', 'rieneck', 'saarbrücken', 
    'schwäbisch hall', 'stuttgart', 'tübingen', 'waldsolms', 
    'wetzlar', 'wiesbaden'],
  Greece => ['athens', 'larissa', 'nea moudania', 'piraeus',
    'telmessos', 'thessaloniki', 'xanthi'],
  Haiti => ['leogane'],
  'Hong Kong' => ['Hong Kong City', 'Sheung Wan'],
  Hungary => ['balaton', 'balatonföldvár', 'budapest', 'csapi',
    'debrecen', 'gyor', 'miskolc', 'nagykanizsa', 'pecs', 'siofok', 
    'szeged'],
  Iceland => ['kópavogur', 'reykjavik', 'selfoss', 'siglufjordur'], 
  India => ['agresar',
    'ahmedabad', 'allahabad', 'ambon', 'bagodi', 'balarampur', 
    'bangalore', 'bansi', 'bhatpara', 'bhilwara', 'bhimavaram',
    'bhubaneswar', 'bikaner', 'chandigarh', 'changsha', 'chennai', 
    'coimbatore', 'dinhata', 'dombivli', 'durgapur', 'gudivada', 
    'hyderabad', 'indore', 'jaipur', 'kalyani', 'kanha', 'kanpur', 
    'kashi', 'kolkata', 'kota', 'ludhiana', 'mardin', 'mitra vihar', 
    'mulund', 'mumbai', 'mysore', 'nagari', 'nagpur', 'nashik', 
    'noida', 'panaji', 'pune', 'puri', 'pushkar', 'shimla', 'solapur', 
    'sukma', 'udaipur', 'varanasi', 'vishakhapatanam'],
  Indonesia => [ 
    'airmadidi', 'bakauheni', 'balikpapan', 'banda aceh', 
    'bandar lampung', 'bandung', 'banjarmasin', 'batam', 'batu', 
    'batununggal', 'bekasi', 'bengkalis', 'bengkulu', 'bitung', 
    'blitar', 'bogor', 'boven digoel', 'burdwan', 'calangute',
    'cimahi', 'cirebon', 'coimbatore', 'comandatuba', 'delhi', 'depok', 
    'dharmasraya', 'gresik', 'grobogan', 'grogol', 'hatay', 
    'indramayu', 'jakarta', 'jambi', 'jember', 'kabupaten bandung barat', 
    'karimun', 'kediri', 'kedungwaru', 'kharagpur', 'kinali', 
    'klabat', 'kota bandung', 'kota bekasi', 'kota bogor', 
    'kota mataram', 'kubu raya', 'kudus', 'landak', 'langkat', 
    'lhokseumawe', 'limboto', 'lumajang', 'magetan', 'makassar', 
    'malang', 'manado', 'mandobo bodi', 'manna', 'martapura', 
    'medan', 'melawi', 'moradabad', 'muara bungo', 'nganjuk', 'pacitan', 
    'padang', 'palangka raya', 'palembang', 'palu', 'pariaman', 
    'pasuruan', 'patna', 'pekanbaru', 'pemangkat', 'penajam', 
    'pontianak', 'probolinggo', 'riau', 'samarinda', 'sampit', 
    'sawahlunto', 'secunderabad', 'semarang', 'semburat jingga', 
    'serang', 'seulawah agam', 'siddha eden lakeville', 'sidoarjo', 
    'singaraja', 'singkawang', 'sleman', 'solo', 'solok', 
    'south tangerang', 'sukomoro', 'sumedang', 'surabaya', 'tambun', 
    'tangerang', 'tanjung pinang', 'tarakan', 'tasikmalaya', 'thane', 
    'thanjavur', 'tomohon', 'yogyakarta'],
  Iran => ['persepolis', 'shiraz'],
  Iraq => ['baghdad'],
  Ireland => ['dublin', 'galway', 'waterford'],
  Israel => ['jerusalem', 'netanya', 'tel aviv'],
  Italy => ['arezzo', 'bevagna', 'birolo', 'bologna', 'buonconvento', 
    'cagliari', 'cannareggio', 'catania', 'cuneo', 'fernetti', 
    'firenze', 'genoa', 'la spezia', 'lake iseo', 'lecco', 'livorno', 
    'lodi', 'marcelli', 'milan', 
    'monticiano', 'napoli', 'oderzo', 'padova', 'palermo', 'pesaro', 
    'pescara', 'piedimonte', 'pisa', 'pompeii', 'rastignano', 
    'reggio calabria', 'reggio emilia', 'rimini', 'romana', 'rome', 
    'salerno', 'salsomaggiore', 'san giorgio del sannio', 
    'san remo', 'san servolo', 
    'sansepolcro', 'savona', 'senigallia', 'siena', 'tonara',
    'torino', 'treviso', 'trieste', 'varese', 'venice', 'verona', 
    'viareggio', 'villa fabbriche', 'viterbo'],
  'Ivory Coast' => ['yamoussoukro'],
  Japan => ['hiroshima', 'kaisei', 'kyoto', 'osaka', 'sendai', 
    'setagaya', 'takayama', 'toshima', 'tokyo', 'yokohama'],
  Jordan => ['amman', 'aqaba'],
  Kazakhstan => ['aral', 'turkistan'],
  Kenya => ['mombasa'],
  Latvia => ['jurmala', 'liepaja', 'riga', 'sigulda'],
  Lebanon => ['aley', 'beirut'],
  Libya => ['tripoli'],
  Liechtenstein => ['vaduz'],
  Lithuania => ['alytus', 'marijampolė', 'vilnius'],
  Malaysia => ['kuala lumpur'],
  Mali => ['timbuktu'],
  Mexico => ['perula', 'san miguel', 'tijuana'],
  Moldova => ['chisinau'],
  Monaco => ['monte carlo'],
  Morocco => ['casablanca', 'marrakech', 'rabat'],
  Netherlands => ['amsterdam', 'arnhem', 'delft', 'den haag',
    'enschede', 'groningen', 'leiden', 'maastricht', 'nijmegen', 
    'pijnacker', 'rotterdam', "'s-hertogenbosch", 'the hague', 
    'tilburg', 'utrecht', 'veldhoven'],
  'New Caledonia' => ['nouméa'],
  'New Zealand' => ['auckland', 'christchurch', 'portobello',
    'wellington'],
  'North Macedonia' => ['gevgelija', 'skopje'],
  'Northern Ireland' => ['belfast', 'ballymena'],
  Norway => [
    'alta', 'arendal', 'askim', 'bergen', 'bodø', 'brandbu', 'brevik',
    'bø', 'drammen', 'drøbak', 'elverum', 'farsund', 'fauske', 
    'flekkefjord', 'fosnavåg', 'førde', 'galleberg', 'gudbrandsdal', 
    'gjøvik og vardal', 'hamar', 'harstad', 'huldretråkket', 'jessheim', 
    'kirkeby', 'klepp', 'kolbotn', 'kongsberg', 'konnerud', 'kragerø', 
    'kristiansand', 'kverndalen', 'kølabånn', 'lakselv', 'larvik', 
    'lillehammer', 'lom', 'lyngdal', 'mo i rana', 'moss', 'namsos', 
    'narvik', 'nesodden', 'notodden', 'nærbø', 'nærøysund', 'nøtterøy', 
    'olrud', 'oslo', 'ottadalen', 'rubbestadneset', 'sandefjord', 
    'sarpsborg', 'singsås', 'skarvemellen', 'ski', 'skien', 'sogndal', 
    'solvorn', 'sortland', 'stavanger', 'steinkjer', 'stokke', 
    'strømmen', 'sunndalsøra', 'sømna', 'sørreisa', 'sørvoll', 
    'trondheim', 'tromsø', 'verdal', 'vestfold', 'vestvågøy', 
    'vik i sogn', 'vikersund', 'vorden', 'våge', 'vålerenga', 
    'ørland', 'østerdal', 'ålesund', 'åsane'],
  Pakistan => ['lahore'],
  Paraguay => ['assunçao'],
  Palestine =>['gaza', 'khan yunis'],
  Peru => ['ayacucho', 'lima', 'pisco'],
  Philippines => ['manila'],
  Poland => ['bartoszyce', 'bialystok', 'bielsko-biala', 'boleslawiec', 
    'braniewo', 'bydgoszcz', 'bytom', 'chelmno', 'dabrowka', 
    'doliny narwi', 'elblag', 'gajaki', 'gdansk', 'gdynia', 'gizycko',
    'gliwice', 'gniezno', 'gorzow wielkopolski', 'grodkow', 
    'hrubieszow', 'inowroclaw', 'jastrowie', 'jaworzno', 'kalisz', 
    'katowice', 'kedzierzyn', 'kielce', 'kolobrzeg', 'kornik', 
    'koszalin', 'krakow', 'krosno odrzanskie', 'krzywanice', 
    'kutno', 'lebork', 'lesno', 'leszno', 'lidzbark warmiński', 
    'lodz', 'lojdy', 'lomza', 'lowicz', 'lubin', 'lublin', 'lubomino', 
    'michalowo', 'mragowo', 'nowa sol', 'nysa', 'odmet', 'olsztyn', 
    'opole', 'orneta', 'ostrowiec', 'ozarow', 'plock', 'poznan', 
    'przemysl', 'pulawy', 'pyrzyce', 'rozanka', 'rzepin', 'rzeszow', 
    'szczecin', 'siedlce', 'sieradz', 'silesia gliwice', 'skawina', 
    'slawa', 'sopot', 'starachowice', 'stargard', 'suwalki', 
    'szczecinek', 'szczyrk', 'sztum', 'tarnów', 'tarnobrzeg', 'tczew', 
    'torun', 'walbryzch', 'warsaw', 'wisla', 'wroclaw', 'wronie', 
    'zawady', 'zegrze', 'zielona gora', 'zyrardow'],
  Portugal => ['alcobaça', 'baleal island', 'barlinek', 'cascais', 
    'coimbra', 'estoril', 'evora', 'funchal', 'lisbon', 'miramar', 
    'ponta delgada', 'porto', 'são vicente', 'vilamoura'],
  'Puerto Rico' => ['san juan'],
  Qatar => ['doha'],
  Romania => ['alba iulia', 'bistrita', 'botosani', 'braila', 
    'brasov', 'bucharest', 'cluj', 'cluj-napoca', 'craiova', 
    'csíkszereda', 'deva', 'dorohoi', 'hunedoara', 'iasi', 'lugoj',
    'miercurea ciuc', 'oltenita', 'oradea', 'piatra neamt', 
    'radauti', 'sibiu', 'sighisoara', 'suceava', 'targoviste', 
    'timisoara', 'valcea'],
  Russia => ['kabardey', 'kostroma', 'krasnodar', 'lokotok', 'moscow', 
    'novosibirsk', 'rostov-on-don', 'russia-pan', 'saint petersburg', 
    'tula', 'yekaterinburg'],
  Rwanda => ['kigali'],
  'San Marino' => ['san marino city'],
  'Saudi Arabia' => ['riyadh']
  Scotland => ['aberdeen', 'dunfermlin', 'edinburgh', 'glasgow', 
    'peebles', 'stirling'],
  Serbia => ['belgrade', 'beograd', 'jagodina', 'niš', 'novi sad', 
    'pancevo', 'sombor', 'vrnjacka banja'],
  Singapore => ['singapore city'],
  Slovakia => ['kosice', 'michalovce'],
  Slovenia => ['ljubljana', 'ptuj', 'zuzenberk'],
  'South Africa' => ['cape town'],
  Spain => ['alicante', 'altea', 'barcelona', 'begues', 'bilbao',
    'cadiz', 'cambrils', 'cuenca', 'las palmas', 'linares', 'madrid', 
    'malaga', 'marbella', 'montoro', 'palencia', 'palma', 'pervera', 
    'sabadell', 'san sebastian', 'saragossa', 'tarragona',
    'toledo', 'valencia'],
  'South Africa' => ['durban', 'gqeberha', 'johannesburg', 'piggs peak',
    'polokwane'],
  'South Korea' => ['seoul'],
  Sweden => [
    'borlänge', 'bromölla', 'fredrikstad', 'gävle', 'gnesta', 
    'göteborg', 'harplinge', 'hedemora', 'helsingborg', 'karlstad',
    'kista', 'konga', 'leksand', 'lerum', 'lindesberg', 'linköping', 
    'ludvikabygden', 'malmö', 'näsby', 'norrbyskär', 'norrøna', 
    'ronneby', 'rottneros', 'smedstad', 'stockholm', 'storsjöbygden', 
    'stureby', 'skara', 'snåsa', 'täby', 'täfteå', 'tofta', 'uddevalla', 
    'ulricehamn', 'umeå', 'underberg', 'uppsala', 'varberg', 
    'västervik', 'västerås', 'örebro', 'överum'],
  Switzerland => ['basel', 'geneva', 'la chaux-de-fonds', 
    'lausanne', 'luzern', 'nyon', 'zürich'],
  Taiwan => ['changhua', 'chiayi', 'hsinchu', 'huwei', 'jiangyou', 
    'kaohsiung', 'keelung', 'miaoli', 'taichung', 'tainan', 'taoyuan', 
    'taipei city', 'new taipei city'],
  Thailand => ['bangkok', 'buri ram', 'chiang rai', 'chumphon', 
    'hat tai', 'kamphaeng phet', 'kanchanaburi', 'khon kaen', 
    'maha sarakham', 'nonthaburi', 'pattaya', 'phitsanulok', 'phuket', 
    'rayong', 'songkhla', 'trang', 'udon thani', 'yasothon'],
  Tunisia => ['hammamet','tabarka'],
  Turkmenistan => ['bereket'],
  Turkey => ['adak', 'adakli', 'adalar', 'adana', 'adapazan', 
    'adiyaman', 'afyonkarahisar', 'agadir', 'akcakoca', 'akhisar', 
    'aksaray', 'akyaka', 'akyazi', 'aladag', 'alanya', 'aliaga', 
    'altinoluk', 'altinova', 'amasya', 'amed', 'ankara', 'antakya', 
    'antalya', 'ardesen', 'artvin', 'assos', 'atakum', 'atasehir', 
    'aydin', 'ayvalik', 'ayvansaray', 
    'babaeski', 'babayagmur', 'baglarbasi', 'bakirköy', 'balikesir', 
    'bandirma', 'batikent', 'batman', 'bayramiç', 'bergule', 'besiktas', 
    'beyoglu', 'bilecik', 'bismil', 'bodrum', 'bolu', 'bormali', 
    'bornova', 'bozüyük', 'bulancak', 'burdur', 'burhaniye', 'bursa', 
    'buyukada', 
    'canakkale', 'cankaya', 'cankiri', 'catalca', 'çaycuma', 'caykara', 
    'cerkezkoy', 'cesme', 'cide', 'cigli', 'cildir', 'civril', 
    'corlu', 'corum',
    'dalaman', 'datca', 'degirmendere', 'denizli', 'devrek', 
    'dikili', 'divrigi', 'diyarbakir', 'dörtyol', 'düzce', 
    'edirne', 'edremit', 'egemen', 'egirdir', 'elazig', 'elmadag', 
    'emirdag', 'ephesus', 'erdek', 'eregli', 'ergene', 'eryaman', 
    'erzinkan', 'erzurum', 'esenler', 'eskisehir', 
    'fethiye', 'foca', 
    'gaziemir', 'gaziantep zeugma', 'gazipasa', 'gebze', 'gelibolu', 
    'geyve', 'giresun', 'göksun', 'gölcük', 'gümüshane', 'gümüşlük', 
    'hani', 'hayrabolu', 'hemsin', 'hendek', 
    'incesu', 'iskenderun', 'isparta', 'istanbul', 'izmir', 'iznik',
    'juliopolis',
    'kadirli', 'kahramanmaras', 'karabük', 'karacasu', 'karaman', 
    'karasu', 'karsiyaka', 'kartal', 'kastamonu', 'kavakdibi', 
    'kayseri', 'kemalpasa', 'kesap', 'kirikcan', 'kirklareli', 
    'kirsehir', 'kiziltepe', 'kocaeli', 'konya', 'korfez', 
    'koycegiz', 'kucukbakkalkoy', 'kusadasi', 'kuzguncuk', 
    'küçükçekmece', 'kütahya', 
    'laodikya', 'livane', 'luleburgaz', 
    'malatya', 'malkara', 'manavgat', 'manisa', 'marmara', 'mersin', 
    'midyat', 'milas', 'mordogan', 'mudanya', 'muðla', 'myndon', 
    'narlidere', 'nazilli', 'nebakan', 'nevsehir', 'niksar',
    'nilüfer', 'nusaybin', 
    'ordu', 'orhangazi', 'osmanyie',
    'pamukkale', 'pazar', 'pelitli', 'phokai', 'pitane', 
    'rize',
    'safranbolu', 'samsun', 'sanliura', 'sariyer', 'sarp-hopa', 
    'seferihisar', 'sile', 'silifke', 'silivri', 'simav', 
    'sinop', 'sirnak', 'sivas', 'smyrna', 'söke', 'sürmene',
    'taskopru', 'tatvan', 'tavsanli', 'tekkekoy', 'tekýrdag', 
    'terzialan', 'tire', 'tonya', 'trabzon', 'tralles', 'tunceli',
    'turgutlu', 'turunc', 
    'urla', 'usak', 'uzunköprü', 
    'van', 
    'yalikavak', 'yalova', 'yarimca', 'yarimada', 'yatagan', 'yaykin', 
    'yedi eylul', 
    'zonguldak'],
  Ukraine => ['berdyczow', 'bilhorod-dnistrovskyi', 'kiev', 'odessa', 
    'ternopil'],
  'United Arab Emirates' => ['dubai', 'sharjah'],
  Uruguay => ['punta del este'],
  USA => ['akron', 'anaheim', 'atlanta', 'berkeley', 'boston', 
    'brooklyn', 'buffalo', 'carlsbad', 'champaign', 'chapel hill', 
    'charlottesville', 'chicago', 'claremont', 'corpus christia', 
    'corvallis', 'costa mesa', 'cupertino', 'daytona', 'denver', 
    'detroit', 'durham', 'englewood', 'evanston', 'evansville', 
    'frankfort', 'fremont', 'gainesville', 'galveston', 'garden ridge', 
    'georgetown', 'glendale', 'harvard', 'honolulu', 'houston', 
    'indianapolis', 'ithaca', 'kansas city', 'largo', 'las vegas', 
    'little rock', 'long island', 'los angeles', 'memphis', 'miami', 
    'milpitas', 'nashville', 'new orleans', 'new york city', 
    'niagara falls', 'north garden', 'ocala', 'omaha', 'orlando', 
    'palo alto', 'pasadena', 'pensacola', 'philadelphia', 'phoenix', 
    'pittsburgh', 'portland', 'redmond', 'reno', 'richmond', 
    'riverside', 'rochester', 'saint louis', 'salt lake city', 
    'san antonio', 'san diego', 'san francisco', 'san jose', 
    'santa clara', 'scottsdale', 'seattle', 'spartanburg', 'stanford', 
    'stockton', 'tacoma', 'tampa', 'texarkana', 'torrance', 'tucson', 
    'tulsa', 'urbana-champaign', 'waltham', 'wichita', 
    'williamsburg', 'woburn'],
  Venezuela => ['caracas'],
  Vietnam => ['saigon'],
  Wales => ['newport'],
);


my %CITY_TO_LOCALITY =
(
  Airmadidi => ['raewaya hills'],
  Aladag => ['küp'],
  Ankara => ['balgat', 'çayyolu', 'kardelen', 'sansar', 'ulus'],
  Antalya => ['muratpasa'],
  Aydin => ['bozdogan'],
  Balchik => ['albena'],
  Beijing => ['shihua', 'yizhuang', 'yuquan'],
  Bhatpara => ['nagbagan'],
  Bodrum => ['gundogan', 'yalikavak'],
  Bogor => ['lawang salapan'],
  Brasov => ['poiana brasov'],
  Brussels => ['uccle'],
  'Buenos Aires' => ['recoleta'],
  Buonconvento => ['bellagatta'],
  Bursa => ['yenisehir', 'yildirim'],
  Cairo => ['maadi'],
  Civril =>['civyork'],
  'Courseulles-sur-Mer' => ['courseulles'],
  Deauville => ['barrière'],
  Denizli => ['akçeşme'],
  Edremit => ['akcay'],
  Eskisehir => ['viþnelik'],
  Frankfurt => ['freidorf'],
  Gevgelija => ['mrzenci'],
  Guangzhou => ['zhujiang'],
  Haikou => ['Wuyuanhe'],
  Hamar => ['ridabu'],
  Hani => ['kirim'],
  Hatay => ['karaçay'],
  'Hong Kong City' => ['fukien'],
  Honolulu => ['waikiki'],
  Istanbul => ['atakoy', 'bahce', 'bahcesehir', 'bayrampaþa',
    'bogazici', 'bormali', 'bosphorus', 'esenkent', 'fatih', 
    'fatih karagümrük', 'göktürk', 'incirli', 'kadikoy', 'kartal', 
    'khalkedon', 'kocamustafapasa', 'kucukcekmece', 'kurtulus', 
    'pasham', 'polonezkoy', 'sancaktar', 'suralaya', 'vefa'],
  Izmir => ['balcova', 'bornova', 'buca', 'ege',
    'konak', 'narlidere', 'sirinyer'],
  Jakarta => ['makaliwe', 'senayan'],
  Jember => ['arjasa'],
  Jerusalem => ['mescid-i aksa'],
  Kolkata => ['nagbagan'],
  Katowice => ['slaska'],
  Kayseri => ['pinarbasi'],
  Kocaeli => ['yarimca'],
  Kolkata => ['cossipore'],
  Krakow => ['korwin'],
  Bakauheni => ['siger lampung'],
  Lappeenranta => ['lappee'],
  Lisbon => ['estrela'],
  London => ['chelsea', 'chislehurst'],
  Lublin => ['sarniak'],
  Lyon => ['brotteaux'],
  Magetan => ['sukomoro'],
  Makassar => ['losari'],
  Malmö => ['seved'],
  Manado => ['leilem', 'manahasa', 'wenang'],
  Medan => ['cemara', 'simal'],
  Mersin => ['meski'],
  Monticiano => ['piloni'],
  Mumbai => ['borivli'],
  Nancy => ['jarville'],
  Narlidere => ['narbel'],
  Nicosia => ['katok'],
  Niš => ['niski'],
  'Nové Město' => ['radkov'],
  Nusaybin => ['gunebakan'],
  Oslo => ['gardermoen'],
  'Palangka Raya' => ['isen mulang'],
  Paris => ['monceau', 'palaiseau', 'saint honoré', 'yvelines'],
  Pattaya => ['jomtien'],
  Pleven => ['kaylaka'],
  Poznan => ['tama', 'wroble'],
  Pune => ['amanora', 'hirabaug'],
  Rome => ['olgiata', 'parioli'],
  Sabadell => ['sabadel'],
  Santiago => ['vitacura'],
  Sanya => ['tianya'],
  'São Paulo' => ['unaós'],
  Semarang => ['poncol'],
  Shanghai => ['pudong', 'qiaoxie', 'changning', 
    'puzhong', 'yangpu'],
  Shenzhen => ['nanshan'],
  'Sheung Wan' => ['ko shing'],
  'Singapore City' => ['tengah'],
  Sofia => ['lozenets', 'serdika', 'sredec'],
  'South Tangerang' => ['pato'],
  'Stara Zagora' => ['beroe'],
  Sumedang => ['wadas'],
  Suqian => ['zaohe'],
  Suzhou => ['wujiang'],
  Taizhou => ['gaogang'],
  Tallinn => ['männiku'],
  Tekýrdag => ['suleymanpasa'],
  'The Hague' => ['buitenhof'],
  Tianjin => ['huochetou'],
  Thessaloniki => ['lemvourgeio' ],
  Tokyo => ['narita'],
  Toulouse => ['baragnon'],
  Trondheim => ['heimdal'],
  Urla => ['cesmealti'],
  Varberg => ['varbergshus'],
  Varna => ['avren'],
  Warsaw => ['bieniewo'],
  Wolverhampton => ['wightwick'],
  Wroclaw => ['wratislavia'],
  Wuxi => ['taihu'],
  Yuzhou => ['gucheng'],
  Zagreb => ['fijanova'],
);


my %CITY_TO_UNIVERSITY =
(
  Airmadidi => ['Airmadidi Senior High School'],
  Ankara => ['Ankara University', 'Bilkent University',
    'Middle East Technical University'],
  Antalya => ['Akdeniz University', 'Antalya Halk Egitim'],
  Antwerp => ['Karel de Grote'],
  Atlanta => ['Georgia Tech'],
  Bandung => ['Telkom University', 'Institut Teknologi Bandung',
    'University of Padjajaran'],
  Bangkok => [
    'assumption business administration college',
    'chulalongkorn university',
    "King Mongkut's Institute of Technology Ladkrabang",
    "King Mongkut's University of Technology North Bangkok",
    "King Mongkut's University of Technology Thonburi",
    'kasetsart university'],
  Batu => ['batusida senior high school'],
  Beijing => ['renmin university high school',
    'china central university of business'],
  Bengkulu => ['bengkulu senior high school'],
  Berkeley => ['University of California at Berkeley'],
  Bhubaneswar => ['Navajyoti College'],
  Bogor => ['bogor senior high school'],
  Brussels => ['bruxelles university'],
  Budapest => ['Budapest University',
    'Eötvös Loránd University'],
  Catania => ['university of catania'],
  Changhua => ['Chien Kuo Senior High School'],
  'Chapel Hill' => ['University of North Carolina'],
  Chiayi => ['National Chung Cheng University'],
  Chicago => ['University of Chicago'],
  Claremont => ['harvey mudd college'],
  Craiova => ['university of craiova'],
  Depok => ['gunadarma university'],
  Edirne => ['Trakya University'],
  Eskisehir => ['Anadolu University', 'Osmangazi University'],
  Evanston => ['Northwestern University'],
  Fuzhou => ['Fuzhou University'],
  Gdansk => ['University of Gdansk'],
  Gresik => ['Universitas Muhammadiyah Gresik'],
  Grogol => ['Duta Bangsa College'],
  Guangzhou => ['guangzhou keji'],
  Hamburg => ['UBC Hamburg'],
  'Hat Tai' => ['Prince of Songkla University'],
  Hsinchu => ['Chung Hua University',
    'National Chiao Tung University',
    'National Tsing Hua University'],
  Huwei => ['National Formosa University'],
  Istanbul => ['Istanbul University', 'ITÜ Vakfi', 'Koc University', 
    'Yildiz Technical University', 'Marmara University'],
  Ithaca => ['Cornell University'],
  Izmir => ['Ege University'],
  Jakarta => ['Gunadurma', 'ITS IKOMA', 
    'Kusuma Bangsa', 'Nahdlatul Ulama Alumni', 
    'Sekolah Tinggi Ilmu Statistik', 'Sekolah Tinggi Teknologi'],
  Jember => [
    'University of Jember', 
    'Jember Senior High School',
    'Politeknik Negeri Jember'],
  Jiangsu => ['Jiangsu Tianyi'],
  Kaisei => ['kaisei high school'],
  Kediri => ['kediri senior high school'],
  Kedungwaru => ['kedungwaru senior high school'],
  Keelung => ['National Taiwan Ocean University'],
  'Khon Kaen' => ['Khon Kaen University'],
  Kirsehir => ['Kirsehir Republic Primary School'],
  Kleve => ['rhein-waal university'],
  Kocaeli => ['Kocaeli University'],
  Konya => ['Selçuk University'],
  Krakow => ['AGH Krakow'],
  Kyoto => ['Kyoto University'],
  Langkat => ['Langkat Senior High School'],
  Leuven => ['KU Leuven'],
  Lumajang => ['lumajang senior high school'],
  Magetan => ['magetan senior high school'],
  Makassar => ['Makassar University'],
  Malang => ['Brawijaya University',
    'Politeknik Negeri Malang',
    'Universitas Merdeka Malang',
    'University of Muhammadiyah Malang',
    'Universitas Negeri Malang'],
  Manado => ['Manado State University', 'Sam Ratulangi University'],
  Medan => ['Universitas Sumatera Utara'],
  Mersin => ['Tarsus American College'],
  Miaoli => ['Miaoli Senior High School'],
  Nanchang => ['nanchang university'],
  'New Taipei City' => ['Fu Jen Catholic University'],
  'New York City' => ['Columbia University'],
  Nijmegen => ['radboud university'],
  Osaka => ['osaka university'],
  Padang => ['Andalas University', 'University of Bung Hatta'],
  Paris => ['École Polytechnique', 'Paris ECE',
    'Paris-Sud University',
    'Paris Université Club'],
  Palembang => ['Universitas Sriwijaya'],
  Pattaya => ['thammasat university'],
  Pekanbaru => ['Riau University', 'Universitas Riau Bridge Club'],
  Pittsburgh => ['carnegie mellon university'],
  Pontianak => ['University of Tanjungpura'],
  Porto => ['University of Porto'],
  Potsdam => ['Universität Potsdam'],
  Prague => ['Charles University'],
  Rijeka => ['University of Rijeka'],
  Roskilde => ['tu midtsjælland'],
  Semarang => ['Diponegoro University',
    'Universitas Katolik Soegijapranata'],
  Sendai => ['Tohoku University'],
  Shanghai => ['fudan university'],
  Shenyang => ['Shenyang Ligong'],
  Shenzhen => ['shangbu primary school'],
  Shijiazhuang => ['hebei normal university'],
  Singaraja => ['Universitas Pendidikan Ganesha'],
  Songkhla => ['Rajamangala University of Technology Srivijaya'],
  Stanford => ['Stanford University'],
  Sukomoro => ['sukomoro senior high school'],
  Surabaya => [
    'University of Airlangga', 
    'University of Surabaya',
    'Surabaya Senior High School',
    'Wijaya Kusuma University'],
  Taichung => ['Chung Hwa Medical and Pharmaceutical University',
    'National Chung Hsing University'],
  'Taipei City' => ['National Chengchi University',
    'High School of National Taiwan Normal University',
    'Minglun High School',
    'National Taiwan Normal University',
    'National Taiwan University',
    'National Yang Ming Chiao Tung University',
    'Soochow University'],
  Targoviste => ['Valahia University'],
  Taoyuan => ['Chang Gung University'],
  Tianjin => ['tianjin normal university'],
  Tilburg => ['tilburg university'],
  Tokyo => ['Tokyo University'],
  Toshima => ['gakushuin university'],
  Trondheim => ['Høgskolen i Sør-Trøndelag'],
  Tübingen => ['Tübingen University'],
  'Udon Thani' => ['Udon Thani Rajabhat University'],
  Umeå => ['Umeå University'],
  'Urbana-Champaign' => ['University of Illinois'],
  Vienna => ['wien university'],
  Waltham => ['Brandeis'],
  Warsaw => ['University of Warsaw', 'Warsaw University of Technology',
    'Kozminski University'],
  Wroclaw => ['University of Wroclaw',
    'Wroclaw University of Science and Technology'],
  Wuhan => ['Huazhong University of Science and Technology'],
  Xuzhou => ['Xuzhou Institute of Technology'],
  Yogyakarta => ['Universitas Gadjah Mada'],
  Zagreb => ['Croatia University', 'Zagreb University'],
);


my %CITY_TO_CLUB =
(
  Aachen => ['Aachener BC'],
  Aalborg => ['BK Nord'],
  Adalar => ['adalar sk'],
  Adana => ['Adana BSB'],
  Adapazan => ['Adapazan Briç SK'],
  Akhisar => ['Akhisar BS'],
  Aladag => ['küp bsk'],
  Alexandria => ['alexandria sporting club'],
  Aliaga => ['aliaga bsk'],
  Alta => ['alta bk'],
  Altea => ['altea bridge'],
  Altinova => ['altinova sk'],
  Amed => ['amed sportif'],
  Amman => ['jordan club', 'king hussein club', 'arab club'],
  Amsterdam => ['Trifolium', 'Witte Huis', 'BC Modalfa'],
  Ankara => ['7 Eylül SK', 'Anka BK', 'Ankara Kontrat', 'Ankara RBB', 
    'Ankara Sistematik', 'Auram BSKD', 'Baþkent Sekans BSK', 
    'BH Koru BK', 'Çayyolu BK', 'Genclerbirligi SK', 'Jeofizik', 
    'Jeohidro', 'Sitespor'],
  Annecy => ['annecy bc'],
  Antakya => ['Antakya BSK'],
  Antalya => ['Antalya BSK', 'Antalya Tabip Odasi', 'Muratpasa Club'],
  Antony => ['Antony BC'],
  Aqaba => ['Orthodoxi BC'],
  Arendal => ['Arendals BK'],
  Asenovgrad => ['BK Asenovgrad'],
  Askim => ['bk missklikk'],
  Atakum => ['Atakum Club'],
  Atasehir => ['Atasehir BK'],
  Athens => ['bc athens'],
  Augsburg => ['Augsburg Augusta'],
  Aydin => ['Aydin 1923 BBSK', 'bozdogan club',
    'Aydin Idman Yurdu'],
  Babaeski => ['babaeski bsk'],
  'Baleal Island' => ['cb baleal'],
  Balikesir => ['Balikesir BSK'],
  Ballerup => ['Ballerup BC'],
  Bamberg => ['BC Bamberger Reiter'],
  Bandung => ['EIBC Bandung', 'Ganesha Bridge Club',
    'Gabungan Bridge Bandung', 'Dauna Winazza'],
  Bangkok => ['Bangkok Bridge Club', 'RBSC Polo Club'],
  Barcelona => ['BCN Almirall', 'Bridge House', 'Bridge Turó',
    'BC Barcelona'],
  Barlinek => ['szlem barlinek'],
  Batam => ['BP Batam'],
  Batikent => ['batikent bk'],
  Batman => ['Batman Genclik'],
  Beijing => ['Beijing Baxi Football', 'SPG Club'],
  Beirut => ['Lebanon Club', 'Hamra Club'],
  Belgrade => ['Crvena Zvezda'],
  Bengkalis => ['Bengkalis PT BSP'],
  Beograd => ['btbk'],
  Bergen => ['Bergen Akademiske', 'Åsane BK'],
  Berlin => ['BC 52 Berlin'],
  Beyoglu => ['ulusal folklor gskd'],
  Bhubaneswar => ['Odisha Secretariat Recreation Club'],
  Bialystok => ['ac pajace', 'hetman bialystok', 'kontri bialystok'],
  Bielefeld => ['BC Bielefeld'],
  'Bielsko-Biala' => ['Bielski Klub Brydżowy GOK cards'],
  Bodrum => ['Bodrum BSK', 'Yalikavak SK'],
  Bodø => ['Bodø BK Lyn'],
  Bologna => ['Bridge Bologna'],
  Bonn => ['BC Bonn'],
  Böblingen => ['bc karo 10 böblingen'],
  Braila => ['BC Braila'],
  Brasov => ['BC Brasov'],
  Bremen => ['BC Bremen'],
  Brevik => ['Brevik BK'],
  Brussels => ['Brussels Bridge Club', 'UAE Club'],
  Bucharest => ['ATU Bucharest', 'Contra Club'],
  Budapest => ['Bajnok Bridzs Egyesület'],
  'Buenos Aires' => ['Harlequins BC'],
  Buffalo => ['bridge center of buffalo'],
  Burdur => ['Bucak Bel.'],
  Burghausen => ['bc burghausen'],
  Bursa => [
    'BC Tofas',
    'BSB Kurek Ihtisas', 
    'Bursa BSK',
    'Nilüfer Bld. BSK', 
    'Yenisehir BSK',
    'Yildirimspor'], 
  Bytom => ['BUKS Bytom'],
  Bø => ['midt-telemark bk'],
  Caen => ['Caen BC'],
  Cairo => ['El Ahly', 'El-Karma', 'El Shams Club', 'Wadi Degla'],
  Canakkale => ['Canakkale Tarim'],
  Cannareggio => ['Circolo del Bridge Cannareggio'],
  Cerkezkoy => ['Cerkezkoy SK'],
  Chelmno => ['Konkret Kasztelan'],
  Chelopech => ['bc chelopech'],
  Chennai => ['Madras Gymkhana Club', 'Alumni Club Chennai'],
  'Cherven Briag' => ['SK Karo'],
  Cimahi => ['GB Cimahi'],
  Clichy => ['BC Clichy'],
  Coimbra => ['clube de tiro & sport'],
  'Czech-Pan' => ['jzd'],
  Copenhagen => ['One Eyed Jacks', 'Studenterforeningen',
    'Young Sharks'],
  Corlu => ['corlu yildiz'],
  'Courseulles-sur-Mer' => ['BC Courseulles'],
  Dabrowka => ['dabrowka wzbs'],
  Dalaman => ['dalaman sk'],
  Darmstadt => ['BC Darmstadt Alert'],
  Datca => ['Datca SK'],
  Deauville => ['bc deauville'],
  Debrecen => ['Debrecen DEAC'],
  Delhi => ['Delhi Gymkhana Club'],
  Denizli => ['Akceþme Spor'],
  Deva => ['BC Deva'],
  Devrek => ['devrek bk'],
  Diyarbakir => ['Diyarbakýr Sur BSK', 'Dýcle Gençlýk'],
  Doha => ['Shemokh Club'],
  Dombivli => ['Dombivli BC'],
  Dortmund => ['btc dortmund'],
  'Dörtyol' => ['Dörtyol SK'],
  Drammen => ['Drammen Arbeiderparti'],
  Dubai => ['4 Jacks', 'Dubai Bridge Club'],
  Edirne => ['Edirne GSK'],
  Elblag => ['esbs elblag'],
  Elmadag => ['Elmadag BSK'],
  Enschede => ['Drienerlo'],
  Ergene => ['ergene gsk'],
  Erzurum => ['Cedýt Ilica Sports'],
  Esbjerg => ['Spar K'],
  Eskisehir => ['Anadolu Bridge Club', 'Eskisehir Adalar', 
    'Eskisehir Baðlar', 'Eskisehir Sports', 'Visnelik Club'],
  Essen => ['Essen 86'],
  Farsund => ['lyngdal/farsund'],
  Fethiye => ['Fethiye BSK'],
  Firenze => ['Circolo del Bridge Firenze'],
  Flekkefjord => ['Flekkefjord BK'],
  Foca => ['Foca Club'],
  Fosnavåg => ['Fosnavåg BK'],
  Frankfurt => ['Frankfurter TBC'],
  Freiburg => ['abc freiburg'],
  Fritzlar => ['Yarborough Fritzlar'],
  Førde => ['Førde BK'],
  Garches => ['BC Garches'],
  'Gaziantep Zeugma' => ['zeugma sk'],
  Gdansk => ['szlem gdansk'],
  Geneva => ['bridge contact club'],
  Geyve => ['Geyve Sports'],
  Giresun => ['Yesilgiresun SK'],
  Giza => [
    'El Rabwa Club', 
    'Rabwa Club',
    'Shooting Club'],
  'Gjøvik og Vardal' => ['Gjøvik og Vardal BK'],
  Gölcük => ['Gölcük Club'],
  Göteborg => ['BK Everfresh', 'BK Lyx'],
  Groningen => ['BC de Zeerob', 'Hok Studiecentrum'],
  Guangdong => ['Guangdong Club'],
  Gudbrandsdal => ['Gudbrandsdal BK'],
  'Gümüşlük' => ['Gümüşlük SK'],
  Haderslev => ['Haderslev BC'],
  Hamar => ['Hamar BK'],
  Hamburg => ['Hanseatic Hamburg BC'],
  Hannover => ['BTSC Hannover'],
  Harmanli => ['bk hebros'],
  Harplinge => ['Harplinge BK'],
  Harstad => ['Harstad S&B', 'bk2000'],
  Havirov => ['Dorost Havirov', 'Banik Havirov'],
  Hebi => ['jinshuo club'],
  Hedemora => ['hedemora kingen'],
  Heikendorf => ['Bridge am Grün'],
  Hendek => ['Hendek Kazimiye'],
  Herning => ['Herning BK'],
  Hillerød => ['Hillerød BK'],
  'Hong Kong City' => ['Fukien Athletic Club'],
  Hornbæk => ['Hornbæk BK'],
  Hyderabad => ['Deccan Club',
    'jubilee hills international centre'],
  Iasi => ['BC Iasi'],
  'Indonesia-Pan' => ['Balai Pelaksanaan Jalan Nasional',
    'Bridge Tunas Cahaya', 'EIBC', 'Gala Tawa Bridge Club'],
  Iskenderun => ['Iskenderun IHS'],
  Isparta => ['Isparta Club'],
  Istanbul => ['ABK', 'Altinay SK', 'Atakoy BSK', 'Atletik Basket', 
    'Avrasya SK', 'Bahcesehir Club', 'Bakýrköy Briç SK', 
    'bayrampaþa Club', 'Besiktas', 'Bogazici BSK', 'Büyük Kulüp',
    'Camlica Sports', 'Corlu Avrasya', 'Dizdar BSK', 'Ekol BSK', 
    'Fatih Karagümrük SK', 'Fenerbahce', 'Galata', 'Galatasaray', 
    'Göktürk SK', 'GSD Club', 'Heybeliada SK', 
    'Hidropaks Gebze Tayfun SK', 'Hosgoru', 'IBM SK', 'Incirli SKD', 
    'Istanbul Sports', 'Kadikoy BSK', 'Karadeniz SK', 'Kartal Club', 
    'Kocamustafapasa SK', 'Kucukcekmece BK', 'Kurtulus SK', 
    'Majör Boğaziçi', 'Major Hosgoru', 'Sancaktar GSK', 
    'Slem Bric SK', 'Vefa SK', 'Yildirim YSK'], 
  Izmir => ['Altay SK', 'Arkas SK', 'Bornova BSK', 'Buca Belediye',
    'Buca Sports', 'Can Can SK', 'Goztepe Hilal SK', 'Izmir BSB', 
    'Sirinyer Sports', 'Ege Club', 'Karsiyaka BSK', 'Narlidere Club', 
    'Cimentas Club', 'Konak Club', 'Tunaras SK'],
  Jaipur => ['Jaipur Club'],
  Jakarta => [
    'Alunand BC',
    'Bhinneka Bridge Club', 
    'Gabrial University of Indonesia', 
    'IKA ITS',
    'Jakarta BBG', 
    'Kerukunan Keluarga Kawanua',
    'KPPM',
    'MBC Mampang',
    'Pelatda DKI',
    'Pelatnas', 
    'Siwo Persatuan Wartawan Indonesia', 
    'Pertamina BC', 
    'EIBC Jakarta'],
  Jessheim => ['jessheim bk', 'ullensaker kisa'],
  Kadirli => ['Kadirli Akil Oyunlari Merkezi'],
  Kaohsiung => ['Kao Hsiung Club'],
  Karlsruhe => ['Karlsruher BSC', 'karlsruher'],
  Karsiyaka => ['Karsiyaka BSK', 'BASEK BK'],
  Kastamonu => ['Kastamonu BSK'],
  Kemalpasa => ['kemalpasa club'],
  Ketsch => ['BC Ketsch'],
  'Khan Yunis' => ['qadesia club'],
  Kiel => ['BC Kiel'],
  Kinali => ['MBC Kinali'],
  Kirklarelý => ['Kirklarelý BSK'],
  Kiten => ['slynce'],
  Klepp => ['klepp bk'],
  Kocaeli => ['Kocaeli BSSK', 'Yarimca SK'],
  Kolkata => ['Hindusthan Club', 'calcutta cricket & football club',
    'Calcutta Bridge Club', 'Nagbagan Card Club'],
  Konga => ['konga bk'],
  Kongsberg => ['Sølvknekt BK'],
  Konnerud => ['konnerud bk'],
  Konya => ['konya bk'],
  Kornik => ['OAZA Kornik'],
  Kosice => ['legia kosice'],
  Koszalin => ['kontra koszalin'],
  Kota => ['Kota Club'],
  Koycegiz => ['Koycegiz BSK'],
  Köln => ['Köln Lindenthal BC', 'Makkabi Köln'],
  Kragerø => ['Kragerø BK'],
  Krakow => ['Cracovia 1906'],
  Kristiansand => ['Kristiansand BK'],
  'Kuala Lumpur' => ['Royal Selangor Club'],
  Kucukbakkalkoy => ['Kucukbakkalkoy SK'],
  Kunshan => ['Kunshan Qiaoxie'],
  Kusadasi => ['Kusadasi BSK'],
  Kutno => ['KDK Kutno'],
  'La Baule-Escoublac' => ["BC de la Côte d'Amour"],
  'La Spezia' => ['Spezia'],
  Laodikya => ['laodikya sk'],
  Larvik => ['fram larvik', 'larvik og horten bk'],
  Lausanne => ['cercle de la cité'],
  Lecco => ['Resegone LC'],
  Leiden => ['Pelikaanhof All Stars'],
  Leipzig => ['bc leipzig'],
  Leksand => ['DBK Dalom'],
  Leverkusen => ['Nachteulen Leverkusen'],
  'Lidzbark Warmiński' => ['Osir Lidzbark Warmiński'],
  Lille => ['BC de Lille'],
  Lindesberg => ['Lindesbergs BS'],
  Linköping => ['Smedstadens BK'],
  Lisbon => ['Armando and Viviane Gonçalves Pereira',
    'Benfica', 'Círculo Português de Bridge',
    'Clube de Bridge dos Engenheiros',
    'Lisbon Bridge Association',
    'Núcleo De Bridge Do Círculo', 'Sporting Lisbon'],
  Lodi => ['Fanfulla'],
  Lom => ['Øvre Ottadalen'],
  London => [
    'Royal Air Force Club',
    'TGR', 
    'Young Chelsea Bridge Club'],
  Ludvikabygden => ['Ludvikabygdens BK'],
  Luleburgaz => ['LÜKSAD', 'Luleburgaz SK'],
  Lyon => ['BC Brotteaux', 'Blue BC'],
  Funchal => ['associação de bridge da madeira'],
  Makassar => ['Makassar Utama'],
  Malatya => ['Altin Kayisi BSK', 'Malatya Yildiz Dogu', 
    'Malatyagücü', 'Malatya BSK'],
  Malmö => ['Malmö BK Scania'],
  Manado => [
    'CFT Bridge', 
    'Manado Convention Center',
    'Sekolah Bridge Tonaas Wangko',
    'Swara Kita BS'],
  Manisa => ['Manisa BSK', 'Vestel SK'],
  Manna => ['Manna Bridge Club'],
  Mannheim => ['BC Alert Mannheim', 'BC Universität Mannheim'],
  'Marijampolė' => ['bc sudovia'],
  Marseille => ['Ocean BC'],
  Massy => ['BC Massy'],
  Mersin => ['Kuvayi Milliye', 'Icel Sports', 'Mersin Club', 
    'Meski Club'],
  Michalowo => ['pab michalowo'],
  Midyat => ['Midyat Club'],
  Milan => ['BC Milano', 'Milan CPK Milanowek',
    'Canottieri Olona'],
  Milas => ['Milas Club'],
  Miramar => ['sport clube alberto sousa'],
  Miskolc => ['miskolc deac'],
  'Mo i Rana' => ['Båsmo BK', 'Mo'],
  Moradabad => ['KDI Moradabad'],
  Moscow => ['Avalanche BC'],
  Moss => ['Moss BK'],
  Mragowo => ['Mragowia'],
  Munich => ['bc münchen', 'bc münchen-ottobrunn',
    'münchen sanzatu'],
  Mudanya => ['mudanya gsk'],
  Muðla => ['Muðla GSK'],
  Mumbai => ['ABA Mumbai', 'Matunga', 'Otters Club', 
    'The West End Mumbai', 'WCG Mumbai', 'Bombay Gymkhana Club',
    'willingdon sports club', 'Borivli Sports Club'],
  Nagari => ['nagari club'],
  Namsos => ['Namsos BK'],
  Nanchong => ['Shou Chuang'],
  Nancy => ['Nancy Jarville BC'],
  Napoli => ['Circolo Nautico Posillipo', 'Palcan Bridge ASD'],
  Narvik => ['Narvik BS'],
  Nashik => ['NDBAC Nashik'],
  Nazilli => ['Nazilli BBSK'],
  Näsby => ['Näsby BS'],
  Nesodden => ['nesodden bk'],
  Nganjuk => ['albc nganjuk'],
  Nice => ['Colonial BC'],
  Nilüfer => ['nilüfer bld. bsk', 'yildirimspor'],
  Niš => ['nbk', 'niski bridge club'],
  Noida => ['Avi Club Noida'],
  Norrøna => ['BK Norrøna'],
  'Novi Sad' => ['NS-1'],
  Nürnberg => ['Nürnberg Museum'],
  Nærbø => ['Nærbø BK'],
  Næstved => ['Næstved BK'],
  Nøtterøy => ['Nøtterøy BK'],
  Odense => ['BK 1936', 'Odense BK'],
  Ogndal => ['Ogndal BK'],
  Oldenburg => ['bc oldenburg'],
  Oltenita => ['Phoenix Oltenita'],
  Ordu => ['Ordu BSK'],
  Orhangazi => ['orhangazi sk'],
  Oslo => [
    'Bridgekameratene',
    'Hoppklubbene', 
    'Juniorklubben',
    'OBK Kløverknekt', 
    'Solli', 
    'Top Bridge BC'],
  Osnabrück => ['bc osnabrück'],
  Ozarow => ['Centrum Kultury i Sportu Oze'],
  Örebro => ['Örebridgen'],
  Överum => ['överum bk'],
  Padang => ['Agriculture Bridge Club', 'Semen Padang',
    'Karimata BC'],
  Padova => ['Padova Bridge SS'],
  Palermo => ['Bridge Addaura', 'Circolo del Tennis Palermo'],
  Pamukkale => ['Pamukkale SK'],
  Palu => ['Maesa Palu'],
  Paris => ["BC Djeun's", 'Paris Sud', 'BC Saint Honoré', 
    'Paris Bridge', 'Paris Country Club', 'Friedland BC'],
  Pattaya => ['Pattaya BC'],
  Pärnu => ['Pärnu BK', 'Jomtien Bridge Club'],
  Pazar => ['pazar sk'],
  Pekanbaru => ['Rumah Sakit Umum Daerah Pekanbaru', 'Laksamana BSP'],
  Pelitli => ['Pelitli SK'],
  Pescara => ['Pescara Bridge'],
  Pisa => ['ASB Pisa'],
  Plovdiv => ['alert plovdiv'],
  'Ponta Delgada' => ['CB São Miguel'],
  Pontianak => ['Fakultas Teknik Bridge Club Universitas Tanjungpura'],
  Porto => ['Dragao', 'Porto Club',
    'Centro Desportivo Universitário do Porto'],
  Poznan => ['Nauka Brydza', 'RAL Poznan'],
  Prague => ['Acol Praha', 'Zmrzlina'],
  Radkov => ['ksb radkov'],
  Rakovski => ['sekirovo'],
  Rayong => ['payoon bridge'],
  'Reggio Calabria' => ['Circolo del Bridge N. Ditto Reggio Calabria'],
  'Reggio Emilia' => ['ASD Reggio Emilia'],
  Rennes => ['BC Rennais'],
  Reykjavik => ['Grant Thornton', 'Vestri'],
  Rieneck => ['Kultcamp Rieneck'],
  Romana => ['Romana Bridge'],
  Rome => ['Tennis Club Parioli', 'Star Bridge Roma', 
    'SSD Angelini Bridge', 'Nuovo Bridge Insieme', 'ASD Tennis Roma',
     "universita' del bridge"],
  Rotterdam => ['bc de lombard'],
  Rozanka => ['sps eko rozanka'],
  Rubbestadneset => ['rubbestadneset bk'],
  'Russia-Pan' => ['BC Real'],
  Rødovre => ['Rødovre BK'],
  Saarbrücken => ['BC Saarbrücken 1984'],
  Salerno => ['asb salerno'],
  Samsun => ['Polýsgücü', 'Samsun BK'], 
  'San Luis' => ['Salmun BC'],
  'Santa Clara' => ['silicon valley youth bridge'],
  'São Vicente' => ['Clube Naval São Vicente'],
  Sariyer => ['Sariyer BSK'],
  Sarpsborg => ['Østfold og Follo'],
  'Schwäbisch Hall' => ['BC Schwäbisch Hall'],
  Seferihisar => ['Seferihisar Municipality'],
  'Seine-et-Marne' => ['bc les templiers'],
  Semarang => ['mustang semarang'],
  Senigallia => ['senigallia club'],
  Shanghai => ['Qi Zhong Club', 'Qizhong', 'Pudong Club'],
  Shaoguan => ['Shaoguan BA'],
  Sharjah => ['Sharja Club'],
  Sidoarjo => ['sidoarjo bc'],
  Sieradz => ['piast mosir sieradz'],
  Sigulda => ['bk sigulda'],
  'Silesia Gliwice' => ['tb silesia gliwice'],
  Silifke => ['silifke sk'],
  Singsås => ['Singsås BK'],
  Sivas => ['Sivasspor'],
  Skara => ['skara bs'],
  Skawina => ['centrum kultury i sportu skawina'],
  Ski => ['Ski BK'],
  Slagelse => ['BK 83 Slagelse'],
  Smedstad => ['st eskil'],
  Smolyan => ['bk smolyan'],
  Sofia => ['BC Lozenets', 'Bonsist', 'Levski Sofia', 'Quantum BC'],
  Solok => ['ebc solok'],
  Sortland => ['sortland bk'],
  Söke => ['söke bsk'],
  Stavanger => ['stavanger bk'],
  Steinkjer => ['Steinkjer BK'],
  Stockholm => ['BC Herkules', 'BK Lavec Smile', 'Lavec', 
    'Nya Bridgeskolan', 'S:t Erik'],
  Stoholm => ['Fjends BK'],
  Storsjöbygden => ['Storsjöbygdens BK'],
  Stuttgart => ['bc stuttgart'],
  Sunndalsøra => ['Sunndalsøra BK'],
  Surabaya => ['tss surabaya'],
  Suzhou => ['suzhou qiaoxie'],
  Szczecinek => ['ks tecza'],
  Søborg => ['Blakset Klubberne'],
  Sørreisa => ['Sørreisa BK'],
  Taiyuan => ['shanxi club'],
  Tallinn => ['Estonian Sports Association'],
  Tasikmalaya => ['gabungan bridge kota tasikmalaya'],
  Taskopru => ['taskopru club'],
  Täby => ['Norrorts Bridge', 'Täby BK', 'BK Alert Täby'],
  Tczew => ['sdk tczew'],
  Tekýrdag => ['Cerkezkoy Dinamik BSK', 'Kapakli Sýte', 'Tekirdað Club',
    'Suleymanpasa Club'],
  'Tel Aviv' => ['ASA University of Tel Aviv'],
  Tire => ['Tire BSK'],
  Tomohon => [
    'BC Tomohon',
    'Gereja Masehi Injili di Minahasa',
    'Pria/Kaum Bapa Sinode MMIM'],
  Tonya => ['Tonyaspor'],
  Torino => ['Torino Allegra'],
  Toulouse => ['Bridge Académie Toulouse', 'Toulouse BC',
    'Baragnon BC'],
  Tours => ['Cercle Tourangeau'],
  Trabzon => [
    'trabzon club', 
    'idman ocagi sk',
    'yeni pelitli sk'],
  Trieste => ['bc trieste'],
  Tromsø => ['Tromsø BK'],
  Trondheim => ['Studentenes BK', 'Heimdal BK'],
  Udaipur => ['field club udaipur'],
  Umeå => ['BK Björken'],
  Underberg => ['underberg bc'],
  Uppsala => ['BK Fyris Skalman', 'BK Svanslös Skalman', 
    'Uppsalabridgen'],
  Usak => ['Usak SK'],
  Utrecht => ['BC Star', 'Bridgeclub Oog', 'NDC Den Hommel'],
  Uzunköprü => ['uzunköprü sk'],
  Van => ['Van Bric SK'],
  Varna => ['Aso Pika', 'BC Varna', 'Cherno More'],
  Vasa => ['vasa bk'],
  Västerås => ['ABB BK', 'Västeråsbridgen', 'Top Bridge BC'],
  Vejle => ['Klør 10 Vejle', 'Storeslemmen'],
  Venice => ['Circolo del Bridge Venezia', 'bi veneto'],
  Vestvågøy => ['Vestvågøy SK'],
  Vikersund => ['vikersund bk'],
  'Villa Fabbriche' => ['ASD Villa Fabbriche'],
  Villeurbanne => ['m le bridge'],
  Vorden => ["'t Onstein"],
  Vraca => ['Botev'],
  Waldsolms => ['bv waldsolms'],
  Warsaw => ['Akademia Brydza', 'Auguri Warsaw', 'Spojnia', 'Unia',
    'Wawa Brydz'],
  Wiesbaden => ['1. wiesbadener bc'],
  Wroclaw => ['AZS Wratislawia', 'Ruch AZS', 'Ruch SA'],
  Yatagan => ['Yatagan SK', 'Sinan Folklor Juniors SK'],
  Zagreb => ['BC Dr. Jurica Tomljenovic', 'Locomotiva'],
  'Zhong Jian' => ['Zhong Jian Club'],
  Zonguldak => ['zonguldak bsk'],
  Zürich => ['Zurich Enge'],
  Zyrardow => ['ck zyrardow'],
  Åkirkeby => ['Åkirkeby BK'],
  Ålesund => ['BK Grand', 'Møre og Romsdal'],
  Århus => ['akademisk bridgeklub', 'Århus BK'],
  Åsane => ['Åsane BK']
);

my %COUNTRY_TO_SPONSOR =
(
  Argentina => ['Burladero', 'Conex'],
  Australia => [
    'Derofe', 
    'Penline',
    'Tony Bemrose Insurance Brokers'],
  Austria => ['Lupo Veloce'],
  Belarus => ['MB-Transit'],
  Belgium => ['belisol'],
  Bermuda => ['Orbis Investment Management'],
  Brazil => ['Rio-Sampa'],
  Bulgaria => ['Avest', 'Chateau Rossenovo', 'Dedo', 'Feniks',
    'Gillette', 'Impress', 'Kone', 'Krik', 'Kufari', 'Malkia', 
    'Mech-Ok', 'Merkurii', 'Moreto', 'Parvomay Tomato', 'Perelik', 
    'Pliska XO', 'Panatop', 'Sevtopolis', 'Shivachi', 'Struma', 
    'Unicat', 'Velbazhd', 'Velbujd', 'Versai', 'Villa Yustina', 
    'Vinex Preslav', 'Vito', 'Zagorka'],
  Canada => ['wellwise'],
  Chile => ['fullbridge', 'ximo'],
  China => ['Aershan Haishen', 'Anhui Ankai Di Qing', 
    'Baoji Jucheng Electric', 'Beibao', 'Beidike', 'Beijing Capital', 
    'Beijing Cartoon', 'Beijing Century', 'Beijing Construction', 
    'Beijing Dazhong', 'Beijing Evertrust', 
    'Beijing Huayuan', 'Beijing Hull Technology', 'Beijing Jinghua', 
    'Beijing Lawyers', 'Beijing Liuhe', 'Beijing Longxin', 
    'Beijing Railway Bureau', 'Beijing ShouChuang', 
    'Beijing Tianzhixing', 'Beijing Trinergy', 'Beijing Wan Jia', 
    'BeiJing Xiaoganju', 'BeiJing Xiaojungan', 'Beijing Yue Ze', 
    'Beijing Yindi', 'Bihuali', 'Bnerg', 'Cai Fu Zheng Quan',
    'Changyu', 'Chengdu Zhongtai', 'China Evertrust', 'China Finance', 
    'China Global Times', 'China National Petroleum Corporation', 
    'China Ping An', 'China Renshou', 'China Resources', 
    'China State Construction Engineering',
    'China Trinergy', 'Chinese Hailian', 'Chongqing Jianke', 
    'Chongqing Jinjian', 'Chongqing Shangyou', 'Chuanmei', 'Copia', 
    'Dalian Dichan', 'Dalian Aoxin', 'Datang', 
    'Dian Zi Cheng', 'Dianwang', 'Dongfeng', 'Dongfang Tairong', 
    'Dragon Sports', 'Eurocentres', 'Evertrust', 'Fanhua Jituan', 
    'GaoSuDa', 'Geely Automobile', 'Gong Hang Jin Ying', 'Guowang',
    'Guangdong Huachu Chemicals', 'Guangxi Tianhu', 
    'Guangzhou Hongmian', 'Guangzhou Huachu Chemicals', 
    'Guangzhou Mingjian', 'Guangzhou Pearl River', 'Guiyuang Bank', 
    'Guiyuang Xinshiji', 'Guizhou Bangda', 'Guizhou Xinshiji', 
    'Guowang', 'Haerbin Bingxue', 'Hai Long', 'Hainan Air', 
    'Hainan Shichuang', 'Hainan Window', 'Haining Ziwei', 
    'Haiyang Ruixiang', 'Hangzhou Jinjiang', 'Haoxin',
    'Heilongjiang Tea', 'Heng Yuan Xiang', 'Hengsha Haijiu', 
    'Hengsha Ke Ji', 'Hengzhou Group', 'HNA', 'Ho-Hsing', 'Hong Zhu', 
    'Hongyu', 'Huabin Aoruijin', 'Huabin Zhiyun', 'Huachu', 
    'Huangshi Qixing', 'Huayuan', 'Huaye', 'Hubei Bank', 
    'Hubei Dongfeng', 'Hubei Yihua', 'Hubei Xiqing', 'Hunan Mingkai', 
    'Hunan Tou Zhan', 'Jetox', 'Jiang You', 'Jiangsu Jiaotong', 
    'Jiangsu Jingling', 'Jiangyin Faersheng', 
    'Jiangyin Zhigao', 'Jiangxi Hengkang', 'Jiegao', 'Jilin Dingyuan', 
    'Jin Rong', 'Jin Jing', 'Jinfan', 'Jingchen Jituan', 
    'jinsheng development', 'Jinshi', 'Jing Tie', 'JL Car', 
    'Kuncheng Group', 'Kunhua', 'LCG', 'Lianbo', 'Lianhua Keji', 
    'Lianzhong Shi Jie', 'Longjiangfu', 'Lu Cheng', 'Lu Ning Coal', 
    'Lv Hua', 'Mai Zi Fu Shi', 'Mei Kuang', 'Meilin Qing Cheng', 
    'Mengxilan', 'Mingxin Jituan', 'Nanfang Dianwang', 'Nangang Power', 
    'Nanjing XingGuang',
    'Nanjing Zhaohe', 'Nanning Yalun', 'Nanyuan', 'Nong Fa Hang', 
    'Nongken', 'Norco', 'Nuo Hui Jian Kang', 'Oly-Star', 
    'Org Reignwood', 'Pan China Group', 'PD Real Estate', 'PD Times', 
    'PD Transnational', 'Pan China Construction', 'Pufa',
    'Qianli Guangda', 'Qiaoyou', 'Qinjia', 'QingLong KeJi',
    'Qingnian Qiche', 'Quanzhou Fengda', 'Red Cotton', 'Ruyi', 
    'SAIC VW', 'San Yutian', 'Sanya Haihe', 'Sanya Jiguan', 
    'Sanya Tianze', 'Shan Hai', 'Shanghai Automobile', 
    'Shanghai Changyu', 'Shanghai Chenyi', 'Shanghai Financial', 
    'Shanghai Gaohe', 'Shanghai Jiahua', 'Shanghai Jinchang', 
    'Shanghai Jingfan', 'Shanghai Ling Mu', 'Shanghai Lvcheng',
    'Shanghai Media and Entertainment Group', 'Shanghai Qiche', 
    'Shanghai Qihao', 'Shanghai Qi Zhong', 'Shanghai Weiyu', 
    'Shanghai Yitong', 'Shanghai Zhongfu', 'Shanxi Luning', 
    'Shanxi Qinlian', 'Shen Jiu', 'Sheng He Wan', 'Sheng Tao Sha', 
    'Sheng Yu Tian', 'Sheng Yuan', 'Shengheng', 'Shenha Qiaoyou',
    'Shenzhen Electronic City', 'Shenzhen Huabei',
    'Shenzhen Lanpu', 'Shenzhen Nangang', 'Shenzhen Ping An', 
    'Shenzhen Qiayao', 'Shenzhen Qiyuan', 'Shenzhen Topone Car', 
    'Shi He Dong Li', 'Shi You', 'Shichuang', 'Shiji Changda', 
    'Shouchuang', 'Sichuan Dahe', 'Sifute', 'Siji Changda',
    'Suiyi', 'Sunchime Cartoon', 'Sunchime Fund', 'Sung Tao', 
    'Suzhou Youtong', 'SY Sheng Yutain', 'Synrey', 'TianJin JS2',
    'Tielu Jixie', 'Tin Fok', 'Tsingtao', 'Wuhan Dongfang', 
    'Wujiang Feixiang', "Xia'er Xili", 'Xiamen Xiashun', 
    'Xianfeng Guoji', 'Xiao Ying', 'Xin He Jin Tai', 
    'Yalu Group', 'Yanjin Puzi', 'Yibin China Resources', 
    'Yi Tong', 'Yuetao', 'YJ Health', 'Yufeng Electric', 
    'Yunnan Dikuang Resources', 'Yunnan Qiaoxie', 'Yunnan Tongya', 
    'Zhai Meng Yi Dao', 'Zhaoeng', 'Zhe Da Wang Xin', 'zhejiang huamen',
    'Zhejiang Jingfan', 'Zhejiang Jinjian', 'Zhejiang Qintang',
    'Zhejiang Xinxiang', 'Zhenjiang Hanbang', 'Zhenjiang Jingjiang', 
    'Zhiyijia', 'Zhong Guo Ren Bao', 'Zhong Liang Y LW', 'Zhong Yuan', 
    'Zhonghai', 'Zhongshan Jiegao', 'Zhongtong Jiangsu', 'Zhu Jiang'],
  Croatia => ['Atlantic Trade', 'Mireo', 'Plovac Ploski',
    'Stanicic Software', 'Termoavion'],
  Denmark => ['Dagensbridge.dk', 'Dancon', 'Nescafe Gold', 
    'Nordfyns Finans', 'Team Audita', 'Team PharmaService', 
    'Vepidan', 'XP Digital'],
  England => ['Intobridge.com', 'Pharon', 'Red Bull'],
  Estonia => ['Baltic Express', 'Druva', 'Eksprompt', 'Kilogrupp',
    'Pealinn', 'Printerikeskus', 'Raam', 'Unibet', 'Viru Valge',
    'Z-Tech'],
  Finland => ['Iso Karhu', 'Näkösoppi', 'Nordic Security'],
  France => ['BridgePlus', 'Cap Gemini', 'Funbridge', 'Jet Immo', 
    'Multicoms', 'Société Générale'],
  Germany => ['Allianz', 'Holzhauer IT-Service', 'Paulaner'],
  Greece => ['Kale Park', 'Tzilis'],
  'Hong Kong' => ['AIA', 'Avia Financial', 'CCH Power', 
    'Gao Feng', 'Hong Kong Vico', 'JP Morgan', 'K.W. Tam', 'L&Y Law',
    'Maoyuan', 'Phoenix TV', 'Stonehill Capital', 'Wellwise'],
  Hungary => ['Aromo', 'Ecosoft', 'Elastron', 'GAMAX', 'Interface', 
    'Nimbusz', 'Palatinus SRB', 'Visoft'],
  Iceland => ['101 Fasteignasala', 'Actavis', 'Betri Ferðir',
    'Betri Frakkar',
    'Breki Jarðverk', 'Bridgefélag Reykjavíkur', 'Bústólpi ehf', 
    'Eimskip', 'Enorma', 'ESSO', 'Ferðafélag Rangæinga',
    'Ferðaskrifstofa Vesturlands', 'Fisk Seafood', 'Frettabladid', 
    'Gaflarar', 'Garðar & Vélar', 'Garðs Apotek', 'Gevalia', 'GSE', 
    'Haustak', 'HF Verðbréf', 'Hótel Hamar', 'Hótel Norðurljós', 
    'Hreint ehf', 'Iceland Express', 'Info Capital', 
    'Íslenskur Landbúnaður', 'Isokarhu', 'Jáverk', 'Kabinetti', 
    'Kemi', 'Kjaran ehf', 'Kjörís','Kollgáta Arkitektúr', 'Kvika', 
    'Lekta ehf', 'Logoflex', 'Lögfræðiskrifstofa Islands', 
    'Lögfræðistofa Bjarna', 'Lyfjaver', 'Málning hf', 
    'Morgunblaðið', 'Myllan', 'Myndform', 
    'Myvatn Hotel', 'Ráðgjöf', 'Sagaplast', 'Set ehf', 'Skeljungur', 
    'Skinney-Þinganes', 'Sölufélag Garðyrkjumanna', 'Sparisjóður', 
    'Sparisjóður Keflavik', 'Sparisjóður Norðfjörður', 
    'Sparisjóður Siglufjarðar', 'SR Group', 'Tick Cad',
    'Trygginga Miðstöðin', 'VBS Fjárfestingarbanki hf.', 'Vélasalan', 
    'Vidbot ehf', 'Vinabær', 'Virnet', 'VÍS', 'Vopnabræður', 'Wise'],
  India => ['Abakash', 'Accenture', 'Andromeda Baroda', 'APRA Clothing', 
    'Avia', 'Bajaj', 'Balarampur Chini', 'Bangur Cement', 'Baroda Bank', 
    'Bhabha Atomic Research Centre',
    'BridgeYes.com', 'Cable', 'Central Secretariat', 'Chennai Online', 
    'Cola King', 'Constellation', 'Cosmos', 'Dhampur Sugar', 'Divitas', 
    'Easy Bridge', 'Eden Realty Kolkata', 'eDOT Goa', 'Enterprise', 
    'Fenesta', 'Godfrey Phillips', 'HCL', 'Hridaan', 'ICSA Groups', 
    'Indian Chain', 'India Glycols', 'Indian Medical', 'Indian Oil', 
    'Indian Overseas Bank', 'Indian Railways', 'Indica', 'Integra',
    'Interkala', 'Jain Group', 'JK White Cement', 'Kaushik Hyderabad', 
    'KH Power', 
    "Kini's Bangalore", 'Kosmos Delhi', 'Krishnapatnam Port', 
    'Manushka', 'Manzoya Casual', 'Mayur Renergy', 'Mitratani', 
    'Moltek', 'NALCO', 'Navachaitanya', 'Navayuga', 'Nest Inn', 
    'OCI Copper', 'Paywell', 'Phoenix Mills', 'Poddar Developers', 
    'Poddar Housing', 'Pravaha', 'Prayas', 'Pro3Max', 'Quik Tea', 
    'RIKS', 'RRAJ', 'RSCS', 'Ryan Express', 'Ryka', 'Sarla Fibers', 
    'SD Associates', 'SD Enterprises', 'SD Traders', 'Shree Cement', 
    'Shree Radhey', 'Smart Max', 'Sol da Caparica', 'Srenniw', 'SSDA', 
    'Tata Consulting Services', 'Taste of Goa', 'Team Secure', 
    'Tekser', 'Tolani Shipping Ltd', 'Trambak Rubber', 
    'Tricon Infotech', 'TTK Healthcare', 'TVS Mobility', 'TVS Tread', 
    'UTI Bank', 'Wellknit'],
  Indonesia => ['Abadi Adimulia', 'Abadi Jaya', 'Adaro Energy', 
    'Aerospace', 'Agsar Paints', 'Aklindo', 'Alunand Limboto', 'Apical',
    'Asindo', 'Asindo Prima', 'Bank Indonesia', 'Bank Mandiri', 
    'Bank Nagari', 'Bank Negara Indonesia', 'Bank Tabungan Negara', 
    'Bapenda Manado', 'Bayu Kencana', 'Buleleng Dewata', 'Cempaka', 
    'Climanusa', 'Djarum', 'Djarum Black', 'Djarum Bold', 
    'Electric Center', 'Elektrik P3B', 'Elektrika', 'Famika',
    'Geo BSP', 'Geo Kideco', 'Geo Pertamina', 'Geo Timah', 'Geo Vale', 
    'Geologi', 'Geologi Banpu', 'Geoportal Kutai Kartanegara', 
    'Harke', 'HCI Indonesia', 'Indoarsip', 'Intan', 'Inteligent', 
    'Indonesian Power', 'Jasa Marga Jakarta', 
    'Karunia Baja Persada', 'Kedai Lae', 'Kideko', 'Kombi Tondano', 
    'LAPI Laboratories', 'LMI Tomohon', 'Makus', 'Manado Berkat', 
    'Manado Cerdas', 'Mandiri Minahasa', 'Mega Bara Mandiri', 
    'Metaforsa', 'Mitra Buana', 'Mutiara Energy', 'OICO Maesa', 
    'P2TEL', 'Palma Karya Mandiri', 'Penajam PU', 
    'Perbankan Jatim', 'Pertagas', 'Pertamina', 'Pessel',
    'Petroconas', 'PGN Jakarta', 'PU Bitung', 
    'PU Minsel', 'PU Sulut', 'Perusahaan Listrik Negara', 'Pimara', 
    'PLN Fortuga', 'PLN Suluttenggo', 'PT Bayu Buana Gemilang', 
    'PT Bumi Siak Pusako', 'RSUD Mandau', 'Samadhan Academy', 
    'Sarunta Waya', 'sawahlunto berkah', 'Sehati', 
    'Semangat Baru Makassar', 'Semen Gresik', 'Siwik Holiday Mragowo',
    'Siwik Intertrade', 'Syabas Energy', 'Telkom',
    'Telkom Groovia', 'Telkom IndiBiz', 'Telkom IndiHome',
    'Telkom IndiSchool', 'Telkom Indonesia', 'Telkom Jabar', 
    'Telkom Jakarta', 'Telkom Speedy', 'Telkom UseeTV',
    'Telkom@wifi.id', 'TGBC Indibiz', 'Timah', 'TJ Jabung Brt', 
    'Tridaya', 'Triputra', 'Videocon', 'Wenang Sintesa'],
  Italy => ['Alphavision', 'Apullum', 'Argento', 'Bozzetto Azzurro', 
    'Carlo Bossi', 'Dalli Cardillo', 'Fantoni Vacations', 'Generali', 
    'Horsa', 'Il Bridge', 'Lavazza', 'Rosa dei Venti', 'Spasso Food'],
  Japan => ['Akebono', 'Hana', 'IMAX', 'monbu japanese ministry', 
    'NEC', 'Shimuzu', 'Yenova'],
  Latvia => ['Laima', 'Pexis', 'Rigainvites.lv'],
  Lithuania => ['Bridgescanner', 'Garsu Pasaulis'],
  Malaysia => ['Likom', 'UMW'],
  Netherlands => ['Agriport', 'Aquatrans', 'Arboned', 'Continental',
    'Delfts Brouw', 'Forbo', 'Hanabi', 'Hommeles', 'ING Bank', 
    'Melchemie', 'Modalfa', 'Ravebo', 'TotZo',
    'Twentebelt', 'VVE Beheer'],
  Norway => ['ABAX', 'Advisor Revisjon Norge', 'Askim Turn og Lakk',
    'Astro A/S', 'Baluba', 'Bridge i Norge', 'Bridgemagasiner.no', 
    'ECF Holding', 'Elf Holding', 'Fossen Eiendom', 'FX Securities',
    'konkurs.no', 'Malermester Mathisen', 'Nortemp', 
    'Polarman Regnskap', 'Ragn Sells', 'SLG Skeidar', 'Svartisen.com', 
    'Tannlege Kvaran', 'Viego Regnskap', 'Worldbridgetour.com'],
  Pakistan => ['Candyland', 'Century Insurance', 'Data Steel',
    'Kayseria', 'Solox'],
  Philippines => ['phe philippines'],
  Poland => ['A-Media Sieradz', 'Abnegat', 'Agena Development',
    'Agilero', 'AJ Diament', 'Alfa-Compensa Gdynia', 
    'Apreo Logistic Poland', 'Asko-Tech', 'bridge24.pl', 
    'Bridge for Fun', 'Bridge for Business', 'Budimex', 'Byk',
    'Byle Co', 'Chemikartel', 'Chlodnia', 'COMAL', 'Computerland', 
    'CONNECTOR', 'Construction Kielce', 'CONSUS', 'Consus Carbon', 
    'Consus Oil', 'Darles Santerm', 'Dermika', 'Diebold Nixdorf Krakow',
    'Dobre Zegary', 'domwaluty.pl', 'E-Service', 'Effcontrol', 
    'Eko-Al', 'Elektrociepl', 'Elektromontaz', 'Eskom IT',
    'Euro Agro', 'Energetyk', 'Falck Medical', 'Faxtel', 'Forta', 
    'forumbridge.pl', 'Gomad', 'Honesta', 'Hotel Senator', 
    'Icentis', 'Ilanka', 'Interbud Plock', 'Intryga', 'JWMP',
    'Kadimex', 'Kancelaria', 'Klika Murcki', 'KONKRET Chelmno', 
    'Konstanta', 'Kurt-Royce', 'Lacznosc', 'Latteria TS Rzepin', 
    'Loluda', 'Magma Zawiercie', 'Mega-Tech', 'Nazwa', 'Nefka', 
    'Niewiem', 'NOTUS', 'Parytet', 'Pasta z Bobra', 'Pellon', 'Petro', 
    'POLFA', 'Ponar Unia', 'Powszechna Kasa Oszczędności Bank Polski', 
    'Praterm', 'Prestige Development', 'Prokom', 'Relanium', 'Relpol', 
    'Radex', 'RTU', 'Samsung', 
    'SAPW Poland', 'Signity', 'Skobud', 'SPS Construction', 
    'Stalgast', 'Stokrotka', 'Sygnity', 'Synergia Ilanka', 
    'Synergia Lublin', 'Syntex', 'TAM Dabrowa', 'Techbud Elblag', 
    'Termika', 'Termochem', 'Topeko', 'Unia Leszno', 'Unia Winkhaus', 
    'Unia Sygnitas', 'Value Media', 'Vyceska', 'zagraj.pl', 
    'Zolza', 'Zweryfikuj Firme'],
  Portugal => ['kempinski', 'mikadinho'],
  Romania => ['Logi Smart', 'Pharma Plus', 'Pro Consul', 
    'Samtronic Constanta'],
  Russia => ['Gazprom', 'Lukomorie', 'Moscow Sunday Times',
    'Russian Sunday Times', 'Staryi Master',
    'stroiprodukt kraich'],
  Serbia => ['Novi Kod'],
  Singapore => ['Genscript', 'Saniva', 'Sing Phil', 'Tyco', 
    'YOU Singapore'],
  Slovenia => ['Triglav Osiguranje'],
  Spain => ['Abbatte'],
  Sweden => ['artotec', 'Balcom', 'Bokadirekt SE', 'Brink Plast',
    'BridgeBertheau.com', 'Cuebids.com', 'Frissan', 'Hotell Strand', 
    'Konga-Väster', 'Lag os', 'Junibacken', 'NOJS', 'Ronke Camping', 
    'San-Sac', 'Scania', 'Scania Bridgekonsul', 'Scandic', 
    'Spintop Ventures', 'Stiga', 'Synective', 'Transearly'],
  Switzerland => ['sportaccord'],
  Taiwan => ['Fatek', 'Mega Giant', 'San Chen', 'Yeh Bros'],
  Thailand => ['Bangkok Bank', 'Metropolitan Electricity Authority',
    'See Fah/Thai', 'Tangerang Raya', 'Thai Oil'],
  Turkey => ['Adalilar', 'Adas', 'Akaylar', 'Alfa Romeo', 'Aliaga Kyme', 
    'Altinay', 'Anka Jeotermal', 'Ant Teknik', 'Arkas', 'Arma', 
    'Atilgan', 'Atlas Profil', 'Avixa', 'Ayibal', 'Ayýntab', 
    'Balcova Termal', 'Baykar', 'Beluga', 'Bumu', 'Cabbar',
    'Caretta International', 'Cimentas', 'Creazone', 'Cumhuriyet OOSK', 
    'Dama Kupa', 'Delta TV', 'Denizgucu', 'Dentgroup Nisantasi', 'DISKI', 
    'Doga Naturale', 'Dostlar', 'Efonla', 'Ekin Maden', 'Elif', 'Fado', 
    'Fora Lastik', 'Forsa Yatcilik', 'Genkad', 'Gözgöz', 'Hafa', 
    'HECEM', 'HEDEF', 'Hotanto', 'IBM', 'Ilgar', 'Inci Ayakkabi', 
    'Invento', 'Irzi', 'Karasu Mermer', 'Kare Dam', 'Kent Spor', 
    'Kirmizi Beyaz', 'KIS Sigorta', 'Konveks', 'Kulyar', 'Kurtiniadis', 
    'Macakizi', 'Magpa-Grup', 'Makrikoy', 'Maksoy-Deniz', 'Mavi Akdeniz', 
    'Meditepe Tip', 'Mega Bekasi Hypermall', 'Melita', 'Mýla', 'Nakkas', 
    'Odak Göz', 'Onko', 'Optimed', 'Ozyuva', 'Özbuğday', 'Prowin', 
    'Pusula', 'RCC', 'RUA', 'Sanliurfa Tarim', 'Shubuo', 'Solakoglu', 
    'Son Dakika', 'Statu Denizcilik', 'Statu Gemi Kiralama', 
    'Tans Coffee', 'Torunlar Gayrimenkul', 'Tundem', 'Turkish Power', 
    'Uras', 'Yade', 'Yelkovan', 'Yesilgiresun', 'Zerya'],
  USA => ['Bridge Winners', 'PRI Investment']
);

my %COUNTRY_TO_NATIONALITY =
(
  Argentina => ['argentinian'],
  Australia => ['australian'],
  Austria => ['austrian'],
  Belarus => ['belarusian'],
  Belgium => ['belgian'],
  Bolivia => ['bolivian'],
  Brazil => ['brazilian'],
  Bulgaria => ['bulgarian'],
  Canada => ['canadian'],
  Chile => ['chilean'],
  Croatia => ['croatian'],
  Cuba => => ['cuban'],
  'Czech Republic' => ['czech'],
  Egypt => ['egyptian'],
  England => ['english'],
  Estonia => ['estonian'],
  'Faroe Islands' => ['faroese'],
  Finland => ['finnish'],
  France => ['french'],
  Germany => ['german'],
  Greece =>['greek'],
  Hungary => ['hungarian'],
  Iceland => ['icelandic'],
  India => ['indian'],
  Indonesia => ['indonesian'],
  Ireland => ['irish'],
  Israel => ['israeli'],
  Italy => ['italian'],
  Japan => ['japanese'],
  Latvia => ['latvian'],
  Lebanon => ['lebanese'],
  Lithuania => ['lithuanian'],
  Netherlands => ['dutch'],
  Norway => ['norwegian'],
  Poland => ['polish'],
  Portugal => ['portuguese'],
  Romania => ['romanian'],
  Scotland => ['scottish'],
  Serbia => ['serbian'],
  'South Africa' => ['south african'],
  Spain => ['spanish'],
  Sweden => ['swedish'],
  Taiwan => ['taiwanese'],
  Turkey => ['turkish'],
  Tunisia => ['tunisian'],
  Wales => ['welsh']
);


sub set_matrix
{
  my ($whole) = @_;
  $whole->set_matrix_link(\%COUNTRY_TO_REGION, 'COUNTRY', 'REGION');
  $whole->set_matrix_link(\%COUNTRY_TO_CITY, 'COUNTRY', 'CITY');
  $whole->set_matrix_link(\%CITY_TO_LOCALITY, 'CITY', 'LOCALITY');
  $whole->set_matrix_link(\%CITY_TO_UNIVERSITY, 'CITY', 'UNIVERSITY');
  $whole->set_matrix_link(\%CITY_TO_CLUB, 'CITY', 'CLUB');
  $whole->set_matrix_link(\%COUNTRY_TO_SPONSOR, 'COUNTRY', 'SPONSOR');
  $whole->set_matrix_link(\%COUNTRY_TO_NATIONALITY, 
    'COUNTRY', 'NATIONALITY');
}


sub get_city_club_list
{
  my ($city) = @_;
  return undef unless exists $CITY_TO_CLUB{$city};
  return $CITY_TO_CLUB{$city};
}


1;
