#!perl

package Connections::Matrix;

use v5.10;
use strict;
use warnings;
use utf8;
use open ':std', ':encoding(UTF-8)';


our @ISA = qw(Exporter);
our @EXPORT = qw(set_matrix);

use lib '..';
use Whole;


my %COUNTRY_TO_REGION =
(
  Australia => ['australian central territory', 'new south wales',
    'northern territory', 'queensland', 'south australia', 
    'tasmania', 'victoria', 'western australia'],
  Austria => ['oberloiben', 'wachau'],
  Belarus => ['druts'],
  Brazil => ['rio de janeiro state'],
  Bulgaria => ['south bulgaria'],
  China => ['anhui', 'feixiang', 'gansu', 'guangdong', 'guangxi',
    'guizhou', 'hainan', 'haixing', 'hebei', 'henan', 'huabei', 
    'hubei', 'hunan', 
    'jiangsu', 'jiangxi', 'jilin', 'liaoning', 'pearl river', 
    'qiantang', 'ren shou', 'shandong', 'shanxi', 'sichuan', 'tianya', 
    'tinglin', 'wujin', 'xinjiang', 'yongjia', 'yongjiang',
    'yunnan', 'zhejiang'],
  Denmark => ['bornholm', 'fjends', 'midtsjælland', 'sydvest'],
  France => ['corsica', 'new caledonia'],
  Greece => ['crete', 'rhodes'],
  Iceland => ['eyjafjallajokull'],
  Hungary => ['hegyvidék'],
  India => ['andhra pradesh', 'bihar', 'ganges', 'goa', 'gujarat', 
    'jharkhand', 'karnataka', 'kerala', 'madhya pradesh', 'maharashtra',
    'punjab', 'rajasthan', 'rajputana', 'tamil nadu', 'telengana',
    'tonk state', 'uttar pradesh', 'uttarakhand', 'west bengal'],
  Indonesia => ['aceh', 'badung', 'bali', 'bangka belitung', 'banten', 
    'belitung', 'bengkayang', 'bisma semarang', 'boeven digoel', 
    'bone bolango', 'borneo', 'bungo', 'central celebes', 
    'central java', 'central sulawesi', 'east borneo', 
    'east jakarta', 'east java', 'east kalimantan', 
    'east nusa tenggara', 'gabungan malaku', 'gorontalo', 
    'indragiri hulu', 'java bali', 'kabupaten bekasi', 
    'kabupaten blitar', 'kabupaten bogor', 'kabupaten cianjur', 
    'kabupaten garut', 'kabupaten gresik', 
    'kabupaten jember', 'kabupaten karawang', 
    'kabupaten kepulauan talaud', 'kabupaten ketapang', 
    'kabupaten kudus', 'kabupaten langkat', 'kabupaten lumajang', 
    'kabupaten minahasa', 'kabupaten nganjuk', 'kabupaten pacitan', 
    'kabupaten palu', 'kabupaten pamekasan', 'kabupaten pasuruan', 
    'kabupaten pessel', 'kabupaten sidoarjo', 'kabupaten sijunjung', 
    'kabupaten solok', 'kapuas hulu',
    'kawanua', 'kayong utara', 'kedungwaru', 'kepri', 'kepulauan riau', 
    'kepulauan seribu', 'kotawaringin timur',
    'kutai kartanegara', 'lampung', 'lebak', 'lombok', 'maluku', 
    'minahasa', 'minang', 'natuna', 'north minahasa', 'north celebes', 
    'north sulawesi',
    'north sumatra', 'nusa tenggara barat', 'nusantara', 'papua', 
    'porong', 'sintang', 'south celebes', 'south east celebes', 
    'south jakarta', 'south kalimantan', 'south sulawesi', 
    'south sumatra', 'southeast sulawesi', 'tambun', 'tanah laut',
    'west borneo', 
    'west java', 
    'west kalimantan', 'west nusa tenggara', 
    'west sulawesi', 'west sumatra'],
  Iraq => ['akkad'],
  Italy => ['liguria', 'olona', 'val di magra'],
  Japan => ['kansai', 'kanto'],
  Lithuania => ['suvalkija'],
  Mexico => ['jalisco'],
  'New Zealand' => ['central districts', 'northland',
    'otago', 'southland', 'waikato'],
  Norway => ['agder', 'buskerud', 'fylke innlandet', 'haugaland', 
    'hedmark', 'hordaland', 'lofoten og vesterålen', 'midt trøndelag', 
    'mjøsa', 'møre romsdal', 'nord trøndelag', 'nord-norge omegn', 
    'nordafjells', 'northern norway', 'rogaland', 'rosfjord', 
    'salten', 'sør-trøndelag', 'telemark', 'troms og ofoten', 
    'vest agder', 'vest finnmark', 'østfold follo'],
  Pakistan => ['sindh'],
  Poland => ['lower silesia', 'pomerania', 'silesia', 'slask'],
  Portugal => ['bairrada', 'madeira', 'norte ilhas'],
  Russia => ['siberia'],
  Scotland => ['ayrshire'],
  Serbia => ['vojvodina'],
  'South Africa' => ['central gauteng', 'eastern cape', 'gauteng',
    'kwazulu natal', 'northern gauteng', 'western province'],
  'South Korea' => ['silla'],
  Spain => ['catalonia', 'iberia'],
  Sweden => ['norrland', 'norrorts', 'skåne', 'south sweden'],
  Taiwan => ['west district'],
  Thailand => ['amnat charoen', 'khon kaen', 'krabi', 'nakhon nayok', 
    'nakhon pathom', 'nakhon sawan', 'nakhon si thammarat',
    'prachinburi',
    'ratchaburi', 'samut prakan', 'samut sakhon', 'si sa ket', 
    'sa kaeo', 'suphan buri'],
  Turkey => ['aegean sea', 'akdeniz', 'cappadocia', 'central anatolia', 
    'datca yarimada', 'dersým', 'dogu akdeniz', 'hatay', 'karadeniz',
    'marmara', 'muallim', 'munzur', 'mysia', 'orontes', 
    'park firtina', 'sakarya', 'thrace', 'tigris', 'tuncelý'],
  USA => ['district of columbia', 'florida', 'missouri'],
  Zimbabwe => ['matopos']
);


my %COUNTRY_TO_CITY =
(
  Argentina => ['buenos aires', 'mar del plata', 'san luis'],
  Australia => [
    'adelaide', 'banora point', 'brisbane', 'broadbeach', 'cairns', 
    'canberra', 'gold coast', 'melbourne', 'perth', 'sydney', 
    'tweed heads'],
  Austria => ['mautern', 'vienna'],
  Belarus => ['minsk'],
  Belgium => ['antwerpen', 'bruges', 'brussels', 'gent', 'leuven',
    'ostend'],
  Brazil => ['assis', 'belo horizonte', 'brasilia', 'buzios',
    'pelotas', 'rio de janeiro', 'são paulo'],
  Bulgaria => ['asenovec', 'asenovgrad', 'balchik', 'chelopech',
    'chepelare',
    'cherven briag', 'dimitrovgrad', 'dobrich', 
    'haskovski mineralni bani', 'haskovo', 'karlovo', 'kesten', 
    'kyustendil', 'la marina', 'pelotas', 'pernik', 'pleven', 
    'plovdiv', 'popovo', 'preslav', 'shumen', 'smolyan', 'sofia', 
    'stara zagora', 'varna', 'vraca', 'yambol', 'zavet'],
  Canada => ['vancouver'],
  Chile => ['paimado', 'santiago', 'temuco'],
  China => [
    'beihai', 'beijing', 'changzhou', 'chengdu', 'chongqing', 'dalian', 
    'dongguan', 'fuzhou', 'guangdong', 'guangzhou', 'haikou',
    'hangzhou', 'hebi', 'jiamusi', 'jianshe', 'jiangsu', 'jinchang', 
    'jincheng', 'jinjiang', 'jiujiang', 'jixiexiang', 'kunshan', 
    'lanzhou', 'liushu', 'lufeng', 'mian yang', 'meilin qingcheng', 
    'nanchang', 'nanchong', 'nanjing', 'nanning', 'neijiang', 
    'ningbo', 'panzhihua', 'qingdao', 'ruian', 'sanya', 'shanghai', 
    'shangrao', 'shaoguan', 'shenyang', 'shenzhen', 'shijiazhuang', 
    'suqian', 'suzhou', 'taicang', 'taihu lake', 'taiyuan', 'taizhou', 
    'tianjin', 'wanzhou', 'wuhan', 'wuxi', 'xin zhu', 'xiamen', 
    'xian', 'xiantao', 'xinyi', 'xuzhou', 'yanshi', 'yantai', 
    'yizhuang', 'yuquan', 'yuzhou', 'zhaoqing', 'zhenjiang',
    'zhong jian', 'zhongshan', 'zhuzhou', 'zigong'],
  Colombia => ['bogotá', 'medellin'],
  'Costa Rica' => ['heledia'],
  Croatia => ['dubrovnik', 'kraljevica', 'opatija', 'pula', 'rijeka', 
    'samobor', 'split', 'zagreb'],
  Cyprus => ['larnaca', 'nicosia', 'protaras'],
  'Czech Republic' => ['havirov', 'nové město', 'prague', 'radkov'],
  Denmark => [
    'aabenraa', 'aalborg', 'asminderød', 'ballerup', 'copenhagen', 
    'esbjerg', 'greve strand', 'haderslev', 'herning', 'hillerød', 
    'hobro', 'hornbæk', 'kalundborg', 'køge', 'morud', 'næstved', 
    'odense', 'ravnkilde', 'roskilde', 'rødovre', 'slagelse', 
    'stoholm', 'svendborg', 'søborg', 'vejle', 'åkirkeby', 'århus'],
  Ecuador => ['guayaquil'],
  Egypt => ['al-rabwa', 'alexandria', 'cairo', 'el-maadi', 'giza'],
  England => ['altrincham', 'bath', 'brighton', 'canterbury', 'coventry',
    'eastbourne', 'lincoln', 'london', 'manchester', 'oxford',
    'petersfield', 'worcester'],
  Estonia => ['derpt', 'otepää', 'pärnu', 'rakvere', 'sindi', 'tallinn'],
  Finland => ['hanko', 'helsinki', 'lappeenranta', 'kuopio', 
    'puutalo', 'salo', 'vadsø', 'vasa'],
  France => [
    'aix en provence', 'annecy', 'antony', 'bergues', 'biarritz',
    'bordeaux', 'caen', 'chaville', 'clichy', 'courseulles-sur-mer', 
    'deauville', 'garches', 'la baule-escoublac', 'le bouscat', 
    'lille', 'lyon', 'marseille', 
    'massy', 'montpellier', 'nancy', 'nice', 'paris', 'pau', 'reims', 
    'rennes', 'seine-et-marne', 'thoisy', 'toulouse', 'tours', 
    'val de seine'],
  Germany => ['aachen', 'augsburg', 'bad griesbach', 'bamberg', 'berlin', 
    'bielefeld', 'bonn', 'böblingen', 'bremen', 'burghausen', 
    'darmstadt', 'dortmund', 'düsseldorf', 'essen', 'frankfurt', 
    'freiburg', 'fritzlar', 'hamburg', 'hannover', 'heikendorf', 
    'karlsruhe', 'kassel', 'ketsch', 'kiel', 'kleve', 'köln', 
    'leipzig', 'leverkusen', 'mannheim', 'munich', 'niedernhausen', 
    'nürnberg', 'oldenburg', 'osnabrück', 'potsdam', 'rieneck', 
    'saarbrücken', 'schwäbisch hall', 'stuttgart', 'tübingen', 
    'waldsolms', 'wetzlar', 'wiesbaden'],
  Greece => ['athens', 'nea moudania', 'telmessos', 'thessaloniki'],
  'Hong Kong' => ['Hong Kong City'],
  Hungary => ['balaton', 'balatonföldvár', 'budapest', 'debrecen',
    'gyor', 'miskolc', 'nagykanizsa', 'pecs', 'siofok', 'szeged'],
  Iceland => ['kópavogur', 'reykjavik', 'selfoss'],
  India => ['agresar',
    'ahmedabad', 'allahabad', 'ambon', 'balarampur', 'bangalore', 
    'bansi', 'bhilwara', 'bhubaneshwar', 'bikaner', 'chennai', 
    'dombivli', 
    'hyderabad', 'indore', 'jaipur', 'kalyani', 'kanpur', 'kashi', 
    'kolkata', 'kota', 'mardin', 'mitra vihar', 'mulund', 
    'mumbai', 'nagari', 'nagpur', 'nashik', 'noida', 'pune', 'puri', 
    'pushkar', 'sukma', 'udaipur', 'varanasi'],
  Indonesia => [ 
    'airmadidi', 'balikpapan', 'banda aceh', 'bandar lampung', 'bandung',
    'banjarmasin', 'batam', 'batu', 'bekasi', 'bengkalis', 'bengkulu', 
    'bitung', 'blitar', 'bogor', 'boven digoel', 'cimahi', 'cirebon', 
    'delhi', 'depok', 'gresik', 'grogol', 'hatay', 'jakarta', 'jambi',
    'jember', 
    'karimun', 'kediri', 'kedungwaru', 'kinali', 'klabat', 
    'kota bandung', 'kota bekasi', 'kota bogor', 'kota mataram', 
    'kudus', 'langkat', 'lhokseumawe', 'lumajang',
    'magetan', 'makassar', 'malang', 'manado', 'mandobo bodi', 'manna',
    'martapura', 'medan', 'moradabad', 'muara bungo', 'nganjuk',
    'padang', 
    'palangka raya', 'palembang', 'palu', 'pariaman', 'pasuruan',
    'pekanbaru', 
    'penajam', 'pontianak', 'probolinggo', 'riau', 
    'samarinda', 'sampit', 'sawahlunto',
    'secunderabad', 'semarang', 'semburat jingga', 'serang', 
    'seulawah agam', 'siddha eden lakeville', 'sidoarjo', 
    'south tangerang', 'sleman', 'solok', 'sukomoro', 
    'sumedang', 'surabaya', 'tambun', 'tangerang',
    'tanjung pinang', 'tarakan', 'tasikmalaya',
    'thane', 'thanjavur', 'tomohon', 'yogyakarta'],
  Iraq => ['baghdad'],
  Ireland => ['galway'],
  Israel => ['tel aviv'],
  Italy => [
    'bologna', 'cannareggio', 'catania', 'cuneo', 'firenze', 'genoa', 
    'la spezia', 'lecco', 'lodi', 'milan', 'monticiano', 'napoli', 
    'padova', 'palermo', 'pesaro', 'pescara', 'pisa', 'rastignano',
    'reggio calabria', 'reggio emilia', 'rimini', 'romana', 'rome', 
    'salerno', 'salsomaggiore', 'san giorgio del sannio', 
    'san servolo', 'senigallia', 
    'siena', 'torino', 'trieste', 'varese', 'venice', 'verona', 
    'viareggio', 'villa fabbriche'],
  Japan => ['kaisei', 'kyoto', 'osaka', 'sendai', 'takayama', 
    'toshima', 'tokyo', 'yokohama'],
  Jordan => ['amman', 'aqaba'],
  Kazakhstan => ['aral'],
  Latvia => ['jurmala', 'liepaja', 'riga', 'sigulda'],
  Lebanon => ['beirut'],
  Lithuania => ['alytus', 'marijampolė', 'vilnius'],
  Malaysia => ['kuala lumpur'],
  Mexico => ['perula'],
  Monaco => ['monte carlo'],
  Morocco => ['casablanca', 'marrakech'],
  Netherlands => ['amsterdam', 'delft', 'enschede', 'groningen',
    'leiden', 'maastricht', 'nijmegen', 'rotterdam', 
    "'s-hertogenbosch", 'the hague', 'tilburg', 'utrecht'],
  'New Zealand' => ['auckland', 'wellington'],
  'North Macedonia' => ['gevgelija', 'skopje'],
  'Northern Ireland' => ['belfast', 'ballymena'],
  Norway => [
    'alta', 'arendal', 'askim', 'bergen', 'bodø', 'brandbu', 'brevik',
    'bø', 'drammen', 'farsund', 'flekkefjord', 'fosnavåg', 'førde', 
    'gudbrandsdal', 'gjøvik og vardal', 'hamar', 'harstad', 
    'huldretråkket', 'jessheim', 'kirkeby', 'klepp', 'kolbotn', 
    'kongsberg', 'konnerud', 'kragerø', 'kristiansand', 'kverndalen', 
    'kølabånn', 'larvik', 'lom', 'mo i rana', 'moss', 'namsos', 
    'narvik', 'nesodden', 'nærbø', 'nøtterøy', 'ogndal', 'olrud', 
    'oslo', 'ottadalen', 'rubbestadneset', 'sandefjord', 'sarpsborg', 
    'singsås', 'ski', 'skien', 'sortland', 'stavanger', 'steinkjer', 
    'sunndalsøra', 'sømna', 'sørreisa', 'trondheim', 'tromsø', 'verdal', 
    'vestfold', 'vestvågøy', 'vikersund', 'vorden', 'ørland', 
    'østerdal', 'ålesund', 'åsane'],
  Palestine =>['khan yunis'],
  Peru => ['ayacucho', 'lima'],
  Philippines => ['manila'],
  Poland => ['bialystok', 'bielsko-biala', 'boleslawiec', 'bydgoszcz', 
    'bytom', 'chelmno', 'dabrowka', 'doliny narwi', 'elblag', 'gdansk', 
    'gdynia', 'gniezno', 'gorzow', 'kalisz', 'katowice', 'kielce', 
    'kornik', 'koszalin', 'krakow', 'kutno', 'leszno', 'lodz', 
    'lojdy', 'lomza', 'lowicz', 'lublin', 'michalowo', 'mragowo', 
    'nysa', 'odmet', 'olsztyn', 'opole', 'ozarow', 'plock', 
    'poznan', 'pulawy', 'rzepin', 'rzeszow', 'sieradz',
    'silesia gliwice', 'skawina', 'slawa', 'sopot', 'stargard', 
    'szczecinek', 'szczyrk', 'tarnów', 'tarnobrzeg', 'tczew', 
    'warsaw', 'wisla', 'wroclaw', 'wronie', 'zegrze', 'zyrardow'],
  Portugal => ['alcobaça', 'baleal island', 'barlinek', 'cascais', 
    'coimbra', 'estoril', 'funchal', 'lisbon', 'miramar', 
    'ponta delgada', 'porto', 'são vicente'],
  Qatar => ['doha'],
  Romania => ['alba iulia', 'braila', 'brasov', 'bucharest', 'cluj', 
    'craiova', 'deva', 'iasi', 'miercurea ciuc', 'oltenita', 
    'piatra neamt', 'sibiu', 'targoviste', 'timisoara'],
  Russia => ['lokotok', 'moscow', 'russia-pan', 'saint petersburg',
    'tula'],
  'San Marino' => ['san marino city'],
  Scotland => ['edinburgh', 'glasgow', 'peebles', 'stirling'],
  Serbia => ['belgrade', 'beograd', 'jagodina', 'niš', 'novi sad', 
    'pancevo', 'vrnjacka banja'],
  Singapore => ['singapore city'],
  Slovakia => ['kosice', 'michalovce'],
  Slovenia => ['ljubljana', 'ptuj'],
  Spain => ['altea', 'barcelona', 'begues', 'cuenca', 'las palmas', 
    'madrid', 'marbella', 'palma', 'sabadell'],
  'South Africa' => ['durban', 'piggs peak'],
  Sweden => [
    'bromölla', 'fredrikstad', 'gävle', 'gnesta', 'göteborg', 
    'harplinge', 
    'hedemora', 'konga', 'leksand', 'lerum', 'lindesberg', 'linköping', 
    'ludvikabygden', 'malmö', 
    'näsby', 'norrbyskär', 'norrøna', 'rottneros', 'smedstad',
    'stockholm', 
    'storsjöbygden', 'stureby', 'skara', 'snåsa', 'täby', 'täfteå', 
    'tofta', 'uddevalla', 'umeå', 'underberg', 'uppsala', 'varberg', 
    'västervik', 'västerås', 'örebro', 'överum'],
  Switzerland => ['la chaux-de-fonds', 'lausanne', 'luzern',
    'nyon', 'zürich'],
  Taiwan => ['changhua', 'chiayi', 'hsinchu', 'jiangyou', 'kaohsiung',
    'keelung', 'miaoli', 'taichung', 'tainan', 'taoyuan', 'taipei city', 
    'new taipei city'],
  Thailand => ['bangkok', 'buri ram', 'chumphon', 'kamphaeng phet',
    'pattaya', 'rayong', 'udon thani'],
  Tunisia => ['hammamet'],
  Turkmenistan => ['bereket'],
  Turkey => ['adalar', 'adana', 'adapazan', 'akhisar', 'aladag', 
    'aliaga', 'altinova', 'ankara', 'antakya', 'antalya', 'atakum', 
    'atasehir', 'aydin', 'ayvalik', 'babaeski', 'balikesir', 
    'batikent', 'batman', 'beyoglu', 'bodrum', 'burdur', 'bursa', 
    'canakkale', 'cankaya', 'cerkezkoy', 'cesme', 'corlu', 'dalaman', 
    'datca', 'denizli', 'devrek', 'diyarbakir', 'dörtyol', 'edirne', 
    'elmadag', 'eregli', 'ergene', 'erzurum', 'eskisehir', 
    'fethiye', 'foca', 'gaziantep zeugma', 'gelibolu', 'geyve', 
    'giresun', 'gölcük', 'gümüşlük',
    'hendek', 'iskenderun', 'isparta', 'istanbul', 'izmir', 
    'kadirli', 'karsiyaka', 'kastamonu', 'kayseri', 'kemalpasa',
    'kirklarelý', 'kirsehir', 'kocaeli', 'konya', 'korfez', 'koycegiz', 
    'kusadasi', 'kütahya', 'laodikya', 'luleburgaz', 'malatya', 'manisa', 
    'mersin', 'midyat', 'milas', 'mudanya', 'muðla', 'narlidere',
    'nazilli', 'nilüfer', 'ordu', 'orhangazi', 'pamukkale', 'pazar',
    'samsun', 'sariyer', 'seferihisar', 'silifke', 'sivas', 
    'söke', 'taskopru', 'tekýrdag', 'tire', 'tonya', 'trabzon',
    'usak', 'Uzunköprü', 'van', 
    'yarýmca', 'yatagan', 'yedi eylul', 'zonguldak'],
  Ukraine => ['kiev'],
  'United Arab Emirates' => ['dubai', 'sharjah'],
  USA => ['atlanta', 'berkeley', 'buffalo', 'chapel hill', 'chicago', 
    'claremont', 'evanston', 'ithaca', 'kansas city', 'las vegas', 
    'new york city', 'philadelphia', 'pittsburgh', 'salt lake city', 
    'st louis', 'stanford', 'urbana-champaign', 'waltham'],
  Venezuela => ['caracas'],
  Wales => ['newport'],
);


my %CITY_TO_LOCALITY =
(
  Airmadidi => ['raewaya hills'],
  Aladag => ['küp'],
  Ankara => ['çayyolu', 'kardelen', 'sansar'],
  Antalya => ['muratpasa'],
  Aydin => ['bozdogan'],
  Balchik => ['albena'],
  Beijing => ['shihua', 'yizhuang', 'yuquan'],
  Bodrum => ['gundogan', 'yalikavak'],
  Bogor => ['lawang salapan'],
  Brasov => ['poiana brasov'],
  Brussels => ['uccle'],
  'Buenos Aires' => ['recoleta'],
  Bursa => ['yenisehir', 'yildirim'],
  Cairo => ['maadi'],
  'Courseulles-sur-Mer' => ['courseulles'],
  Deauville => ['barrière'],
  Denizli => ['akçeşme'],
  Eskisehir => ['viþnelik'],
  Frankfurt => ['freidorf'],
  Gevgelija => ['mrzenci'],
  Guangzhou => ['zhujiang'],
  Haikou => ['Wuyuanhe'],
  Hamar => ['ridabu'],
  Hatay => ['karaçay'],
  'Hong Kong City' => ['fukien'],
  Istanbul => ['atakoy', 'bahce', 'bahcesehir', 'bayrampaþa',
    'bogazici', 'bormali', 'esenkent', 'fatih', 'fatih karagümrük',
    'göktürk', 'incirli', 'kadikoy', 'kartal', 'kocamustafapasa', 
    'kucukcekmece', 'kurtulus', 'pasham', 'polonezkoy', 'sancaktar', 
    'suralaya'],
  Izmir => ['balcova', 'bornova', 'buca', 'ege',
    'konak', 'narlidere', 'sirinyer'],
  Jakarta => ['makaliwe', 'senayan'],
  Jember => ['arjasa'],
  Kolkata => ['nagbagan'],
  Katowice => ['slaska'],
  Kayseri => ['pinarbasi'],
  Kocaeli => ['yarimca'],
  Krakow => ['korwin'],
  Lappeenranta => ['lappee'],
  London => ['chelsea', 'chislehurst'],
  Lublin => ['sarniak'],
  Lyon => ['brotteaux'],
  Magetan => ['sukomoro'],
  Makassar => ['losari'],
  Manado => ['leilem', 'manahasa', 'wenang'],
  Medan => ['cemara', 'simal'],
  Mersin => ['meski'],
  Monticiano => ['piloni'],
  Mumbai => ['borivli'],
  Nancy => ['jarville'],
  Nicosia => ['katok'],
  Niš => ['niski'],
  'Nové Město' => ['radkov'],
  Oslo => ['gardermoen'],
  'Palangka Raya' => ['isen mulang'],
  Paris => ['palaiseau', 'saint honoré', 'yvelines'],
  Pattaya => ['jomtien'],
  Pleven => ['kaylaka'],
  Poznan => ['wroble'],
  Pune => ['amanora', 'hirabaug'],
  Rome => ['olgiata', 'parioli'],
  Sabadell => ['sabadel'],
  Sanya => ['tianya'],
  'São Paulo' => ['unaós'],
  Semarang => ['poncol'],
  Shanghai => ['pudong', 'qiaoxie', 'changning', 
    'puzhong', 'yangpu'],
  Shenzhen => ['nanshan'],
  'Singapore City' => ['tengah'],
  Sofia => ['lozenets', 'serdika', 'sredec'],
  'Stara Zagora' => ['beroe'],
  Sumedang => ['wadas'],
  Suqian => ['zaohe'],
  Suzhou => ['wujiang'],
  Tallinn => ['männiku'],
  Tekýrdag => ['suleymanpasa'],
  'The Hague' => ['buitenhof'],
  Tianjin => ['huochetou'],
  Thessaloniki => ['lemvourgeio' ],
  Tokyo => ['narita'],
  Toulouse => ['baragnon'],
  Trondheim => ['heimdal'],
  Varberg => ['varbergshus'],
  Varna => ['avren'],
  Warsaw => ['bieniewo'],
  Wroclaw => ['wratislavia'],
  Wuxi => ['taihu'],
  Yuzhou => ['gucheng'],
);


my %CITY_TO_UNIVERSITY =
(
  Airmadidi => ['Airmadidi Senior High School'],
  Ankara => ['Ankara University', 'Bilkent University',
    'Middle East Technical University'],
  Antalya => ['Akdeniz University', 'Antalya Halk Egitim'],
  Antwerp => ['Karel de Grote'],
  Atlanta => ['Georgia Tech'],
  Bandung => ['Telkom University', 'Institut Teknologi Bandung',
    'University of Padjajaran'],
  Bangkok => ['kasetsart university'],
  Batu => ['batusida senior high school'],
  Beijing => ['renmin university high school',
    'china central university of business'],
  Bengkulu => ['bengkulu senior high school'],
  Berkeley => ['University of California at Berkeley'],
  Bogor => ['bogor senior high school'],
  Budapest => ['Budapest University'],
  Catania => ['university of catania'],
  Changhua => ['Chien Kuo Senior High School'],
  'Chapel Hill' => ['University of North Carolina'],
  Chiayi => ['National Chung Cheng University'],
  Chicago => ['University of Chicago'],
  Claremont => ['harvey mudd college'],
  Craiova => ['university of craiova'],
  Depok => ['gunadarma university'],
  Edirne => ['Trakya University'],
  Eskisehir => ['Anadolu University', 'Osmangazi University'],
  Evanston => ['Northwestern University'],
  Fuzhou => ['Fuzhou University'],
  Gdansk => ['University of Gdansk'],
  Gresik => ['Universitas Muhammadiyah Gresik'],
  Grogol => ['Duta Bangsa College'],
  Guangzhou => ['guangzhou keji'],
  Hamburg => ['UBC Hamburg'],
  Hsinchu => ['Chung Hua University',
    'National Chiao Tung University',
    'National Tsing Hua University'],
  Istanbul => ['Istanbul University', 'ITÜ Vakfi', 'Koc University', 
    'Yildiz Technical University', 'Marmara University'],
  Ithaca => ['Cornell University'],
  Izmir => ['Ege University'],
  Jakarta => ['Gunadurma', 'ITS IKOMA', 
    'Kusuma Bangsa', 'Nahdlatul Ulama Alumni', 
    'Sekolah Tinggi Ilmu Statistik', 'Sekolah Tinggi Teknologi'],
  Jember => ['University of Jember', 'Jember Senior High School'],
  Jiangsu => ['Jiangsu Tianyi'],
  Kaisei => ['kaisei high school'],
  Kediri => ['kediri senior high school'],
  Kedungwaru => ['kedungwaru senior high school'],
  Keelung => ['National Taiwan Ocean University'],
  Kirsehir => ['Kirsehir Republic Primary School'],
  Kleve => ['rhein-waal university'],
  Kocaeli => ['Kocaeli University'],
  Konya => ['Selçuk University'],
  Krakow => ['AGH Krakow'],
  Kyoto => ['Kyoto University'],
  Langkat => ['Langkat Senior High School'],
  Leuven => ['KU Leuven'],
  Lumajang => ['lumajang senior high school'],
  Magetan => ['magetan senior high school'],
  Makassar => ['Makassar University'],
  Malang => ['Brawijaya University',
    'Universitas Merdeka Malang',
    'University of Muhammadiyah Malang',
    'Universitas Negeri Malang'],
  Manado => ['Manado State University', 'Sam Ratulangi University'],
  Medan => ['Universitas Sumatera Utara'],
  Mersin => ['Tarsus American College'],
  Miaoli => ['Miaoli Senior High School'],
  Nanchang => ['nanchang university'],
  'New Taipei City' => ['Fu Jen Catholic University'],
  'New York City' => ['Columbia University'],
  Nijmegen => ['radboud university'],
  Osaka => ['osaka university'],
  Padang => ['Andalas University', 'University of Bung Hatta'],
  Paris => ['École Polytechnique', 'Paris ECE',
    'Paris-Sud University'],
  Palembang => ['Universitas Sriwijaya'],
  Pattaya => ['thammasat university'],
  Pekanbaru => ['Riau University', 'Universitas Riau Bridge Club'],
  Pittsburgh => ['carnegie mellon university'],
  Pontianak => ['University of Tanjungpura'],
  Porto => ['University of Porto'],
  Potsdam => ['Universität Potsdam'],
  Prague => ['Charles University'],
  Rijeka => ['University of Rijeka'],
  Roskilde => ['tu midtsjælland'],
  Semarang => ['Diponegoro University',
    'Universitas Katolik Soegijapranata'],
  Sendai => ['Tohoku University'],
  Shanghai => ['fudan university'],
  Shenyang => ['Shenyang Ligong'],
  Shenzhen => ['shangbu primary school'],
  Shijiazhuang => ['hebei normal university'],
  Stanford => ['Stanford University'],
  Sukomoro => ['sukomoro senior high school'],
  Surabaya => [
    'University of Airlangga', 
    'University of Surabaya',
    'Surabaya Senior High School',
    'Wijaya Kusuma University'],
  Taichung => ['Chung Hwa Medical and Pharmaceutical University',
    'National Chung Hsing University'],
  'Taipei City' => ['National Chengchi University',
    'National Taiwan Normal University',
    'National Taiwan University',
    'National Yang Ming Chiao Tung University',
    'Soochow University'],
  Targoviste => ['Valahia University'],
  Taoyuan => ['Chang Gung University'],
  Tianjin => ['tianjin normal university'],
  Tilburg => ['tilburg university'],
  Tokyo => ['Tokyo University'],
  Toshima => ['gakushuin university'],
  Trondheim => ['Høgskolen i Sør-Trøndelag'],
  Tübingen => ['Tübingen University'],
  Umeå => ['Umeå University'],
  'Urbana-Champaign' => ['University of Illinois'],
  Waltham => ['Brandeis'],
  Warsaw => ['University of Warsaw', 'Warsaw University of Technology',
    'Kozminski University'],
  Wroclaw => ['University of Wroclaw',
    'Wroclaw University of Science and Technology'],
  Wuhan => ['Huazhong University of Science and Technology'],
  Xuzhou => ['Xuzhou Institute of Technology'],
  Yogyakarta => ['Universitas Gadjah Mada'],
  Zagreb => ['Croatia University', 'Zagreb University'],
);


my %CITY_TO_CLUB =
(
  Aachen => ['Aachener BC'],
  Aalborg => ['BK Nord'],
  Adana => ['Adana BSB'],
  Adapazan => ['Adapazan Briç SK'],
  Akhisar => ['Akhisar BS'],
  Aladag => ['küp bsk'],
  Alexandria => ['alexandria sporting club'],
  Aliaga => ['aliaga bsk'],
  Alta => ['alta bk'],
  Altea => ['altea bridge'],
  Altinova => ['altinova sk'],
  Amman => ['king hussein club'],
  Amsterdam => ['Trifolium', 'Witte Huis', 'BC Modalfa'],
  Ankara => ['7 Eylül SK', 'Anka BK', 'Ankara Kontrat', 'Ankara RBB', 
    'Ankara Sistematik', 'Auram BSKD', 'Baþkent Sekans BSK', 
    'BH Koru BK', 'Çayyolu BK', 'Genclerbirligi SK', 'Jeofizik', 
    'Sitespor'],
  Annecy => ['annecy bc'],
  Antakya => ['Antakya BSK'],
  Antalya => ['Antalya BSK', 'Antalya Tabip Odasi', 'Muratpasa Club'],
  Antony => ['Antony BC'],
  Aqaba => ['Orthodoxi BC'],
  Arendal => ['Arendals BK'],
  Asenovgrad => ['BK Asenovgrad'],
  Askim => ['bk missklikk'],
  Atakum => ['Atakum Club'],
  Atasehir => ['Atasehir BK'],
  Augsburg => ['Augsburg Augusta'],
  Aydin => ['Aydin 1923 BBSK', 'bozdogan club',
    'Aydin Idman Yurdu'],
  Babaeski => ['babaeski bsk'],
  'Baleal Island' => ['cb baleal'],
  Balikesir => ['Balikesir BSK'],
  Ballerup => ['Ballerup BC'],
  Bamberg => ['BC Bamberger Reiter'],
  Bandung => ['EIBC Bandung', 'Ganesha Bridge Club',
    'Gabungan Bridge Bandung'],
  Bangkok => ['Bangkok Bridge Club', 'RBSC Polo Club'],
  Barcelona => ['BCN Almirall', 'Bridge House', 'Bridge Turó',
    'BC Barcelona'],
  Barlinek => ['szlem barlinek'],
  Batam => ['BP Batam'],
  Batikent => ['batikent bk'],
  Batman => ['Batman Genclik'],
  Beijing => ['Beijing Baxi Football', 'SPG Club'],
  Beirut => ['Hamra Club'],
  Belgrade => ['Crvena Zvezda'],
  Bengkalis => ['Bengkalis PT BSP'],
  Beograd => ['btbk'],
  Bergen => ['Bergen Akademiske', 'Åsane BK'],
  Berlin => ['BC 52 Berlin'],
  Beyoglu => ['ulusal folklor gskd'],
  Bhubaneshwar => ['Odisha Secretariat Recreation Club'],
  Bialystok => ['ac pajace'],
  Bielefeld => ['BC Bielefeld'],
  'Bielsko-Biala' => ['Bielski Klub Brydżowy GOK cards'],
  Bodrum => ['Bodrum BSK', 'Yalikavak SK'],
  Bodø => ['Bodø BK Lyn'],
  Bologna => ['Bridge Bologna'],
  Bonn => ['BC Bonn'],
  Böblingen => ['bc karo 10 böblingen'],
  Braila => ['BC Braila'],
  Brasov => ['BC Brasov'],
  Bremen => ['BC Bremen'],
  Brevik => ['Brevik BK'],
  Brussels => ['Brussels Bridge Club', 'UAE Club'],
  Bucharest => ['ATU Bucharest'],
  Budapest => ['Bajnok Bridzs Egyesület'],
  'Buenos Aires' => ['Harlequins BC'],
  Buffalo => ['bridge center of buffalo'],
  Burdur => ['Bucak Bel.'],
  Burghausen => ['bc burghausen'],
  Bursa => ['BSB Kurek Ihtisas', 'Nilüfer Bld. BSK', 'BC Tofas',
    'Yildirimspor', 'Bursa BSK'],
  Bytom => ['BUKS Bytom'],
  Bø => ['midt-telemark bk'],
  Caen => ['Caen BC'],
  Cairo => ['El Ahly', 'El-Karma', 'El Shams Club', 'Wadi Degla'],
  Canakkale => ['Canakkale Tarim'],
  Cannareggio => ['Circolo del Bridge Cannareggio'],
  Cerkezkoy => ['Cerkezkoy SK'],
  Chelopech => ['bc chelopech'],
  Chennai => ['Madras Gymkhana Club', 'Alumni Club Chennai'],
  'Cherven Briag' => ['SK Karo'],
  Cimahi => ['GB Cimahi'],
  Clichy => ['BC Clichy'],
  Coimbra => ['clube de tiro & sport'],
  'Czech-Pan' => ['jzd'],
  Copenhagen => ['One Eyed Jacks', 'Young Sharks'],
  Corlu => ['corlu yildiz'],
  'Courseulles-sur-Mer' => ['BC Courseulles'],
  Dabrowka => ['dabrowka wzbs'],
  Dalaman => ['dalaman sk'],
  Darmstadt => ['BC Darmstadt Alert'],
  Datca => ['Datca SK'],
  Debrecen => ['Debrecen DEAC'],
  Delhi => ['Delhi Gymkhana Club'],
  Denizli => ['Akceþme Spor'],
  Deva => ['BC Deva'],
  Devrek => ['devrek bk'],
  Diyarbakir => ['Diyarbakýr Sur BSK', 'Dýcle Gençlýk'],
  Doha => ['Shemokh Club'],
  Dombivli => ['Dombivli BC'],
  Dortmund => ['btc dortmund'],
  'Dörtyol' => ['Dörtyol SK'],
  Drammen => ['Drammen Arbeiderparti'],
  Dubai => ['4 Jacks'],
  Edirne => ['Edirne GSK'],
  Elblag => ['esbs elblag'],
  Elmadag => ['Elmadag BSK'],
  Enschede => ['Drienerlo'],
  Ergene => ['ergene gsk'],
  Erzurum => ['Cedýt Ilica Sports'],
  Esbjerg => ['Spar K'],
  Eskisehir => ['Anadolu Bridge Club', 'Eskisehir Adalar', 
    'Eskisehir Baðlar', 'Eskisehir Sports', 'Visnelik Club'],
  Essen => ['Essen 86'],
  Farsund => ['lyngdal/farsund'],
  Fethiye => ['Fethiye BSK'],
  Firenze => ['Circolo del Bridge Firenze'],
  Flekkefjord => ['Flekkefjord BK'],
  Foca => ['Foca Club'],
  Fosnavåg => ['Fosnavåg BK'],
  Frankfurt => ['Frankfurter TBC'],
  Freiburg => ['abc freiburg'],
  Fritzlar => ['Yarborough Fritzlar'],
  Førde => ['Førde BK'],
  Garches => ['BC Garches'],
  Gdansk => ['szlem gdansk'],
  Geyve => ['Geyve Sports'],
  Giresun => ['Yesilgiresun SK'],
  Giza => [
    'El Rabwa Club', 
    'Rabwa Club',
    'Shooting Club'],
  'Gjøvik og Vardal' => ['Gjøvik og Vardal BK'],
  Gölcük => ['Gölcük Club'],
  Göteborg => ['BK Everfresh', 'BK Lyx'],
  Groningen => ['BC de Zeerob', 'Hok Studiecentrum'],
  Guangdong => ['Guangdong Club'],
  'Gümüşlük' => ['Gümüşlük SK'],
  Haderslev => ['Haderslev BC'],
  Hamar => ['Hamar BK'],
  Hamburg => ['Hanseatic Hamburg BC'],
  Hannover => ['BTSC Hannover'],
  Harplinge => ['Harplinge BK'],
  Harstad => ['Harstad S&B', 'bk2000'],
  Havirov => ['Dorost Havirov', 'Banik Havirov'],
  Hebi => ['jinshuo club'],
  Hedemora => ['hedemora kingen'],
  Heikendorf => ['Bridge am Grün'],
  Hendek => ['Hendek Kazimiye'],
  Herning => ['Herning BK'],
  Hillerød => ['Hillerød BK'],
  'Hong Kong City' => ['Fukien Athletic Club'],
  Hornbæk => ['Hornbæk BK'],
  Hyderabad => ['Deccan Club',
    'jubilee hills international centre'],
  Iasi => ['BC Iasi'],
  'Indonesia-Pan' => ['Balai Pelaksanaan Jalan Nasional',
    'Bridge Tunas Cahaya', 'EIBC', 'Gala Tawa Bridge Club'],
  Iskenderun => ['Iskenderun IHS'],
  Isparta => ['Isparta Club'],
  Istanbul => ['ABK', 'Altinay SK', 'Atakoy BSK', 'Atletik Basket', 
    'Avrasya SK', 'Bahcesehir Club', 'Bakýrköy Briç SK', 
    'bayrampaþa Club', 'Besiktas', 'Bogazici BSK', 'Büyük Kulüp',
    'Camlica Sports', 'Corlu Avrasya', 'Ekol BSK', 'Fatih Karagümrük SK', 
    'Fenerbahce', 'Galata', 'Galatasaray', 'Göktürk SK', 
    'GSD Club', 'Heybeliada SK', 'Hidropaks Gebze Tayfun SK', 
    'Hosgoru', 'Incirli SKD', 'Istanbul Sports', 
    'Kadikoy BSK', 'Kartal Club', 'Kocamustafapasa SK', 
    'Kucukcekmece BK', 'Kurtulus SK', 'Majör Boğaziçi', 
    'Major Hosgoru', 'Sancaktar GSK', 'Slem Bric SK', 'Vefa SK',
    'Yildirim YSK'], 
  Izmir => ['Altay SK', 'Arkas SK', 'Bornova BSK', 'Buca Belediye',
    'Buca Sports', 'Goztepe Hilal SK', 'Izmir BSB', 'Sirinyer Sports', 
    'Ege Club', 'Karsiyaka BSK', 'Narlidere Club', 'Cimentas Club', 
    'Konak Club'],
  Jaipur => ['Jaipur Club'],
  Jakarta => [
    'Bhinneka Bridge Club', 
    'Gabrial University of Indonesia', 
    'IKA ITS',
    'Jakarta BBG', 
    'KPPM',
    'MBC Mampang',
    'Pelatda DKI',
    'Pelatnas', 
    'Siwo Persatuan Wartawan Indonesia', 
    'Pertamina BC', 
    'EIBC Jakarta'],
  Jessheim => ['jessheim bk'],
  Kaohsiung => ['Kao Hsiung Club'],
  Karlsruhe => ['Karlsruher BSC', 'karlsruher'],
  Karsiyaka => ['Karsiyaka BSK', 'BASEK BK'],
  Kastamonu => ['Kastamonu BSK'],
  Kemalpasa => ['kemalpasa club'],
  Ketsch => ['BC Ketsch'],
  'Khan Yunis' => ['qadesia club'],
  Kiel => ['BC Kiel'],
  Kinali => ['MBC Kinali'],
  Kirklarelý => ['Kirklarelý BSK'],
  Klepp => ['klepp bk'],
  Kocaeli => ['Kocaeli BSSK', 'Yarimca SK'],
  Kolkata => ['Hindusthan Club', 'calcutta cricket & football club',
    'Calcutta Bridge Club', 'Nagbagan Card Club'],
  Konga => ['konga bk'],
  Kongsberg => ['Sølvknekt BK'],
  Konnerud => ['konnerud bk'],
  Konya => ['konya bk'],
  Kornik => ['OAZA Kornik'],
  Kosice => ['legia kosice'],
  Kota => ['Kota Club'],
  Koycegiz => ['Koycegiz BSK'],
  Köln => ['Köln Lindenthal BC', 'Makkabi Köln'],
  Kragerø => ['Kragerø BK'],
  Krakow => ['Cracovia 1906'],
  Kristiansand => ['Kristiansand BK'],
  'Kuala Lumpur' => ['Royal Selangor Club'],
  Kunshan => ['Kunshan Qiaoxie'],
  Kusadasi => ['Kusadasi BSK'],
  Kutno => ['KDK Kutno'],
  'La Baule-Escoublac' => ["BC de la Côte d'Amour"],
  'La Spezia' => ['Spezia'],
  Laodikya => ['laodikya sk'],
  Larvik => ['fram larvik', 'larvik og horten bk'],
  Lausanne => ['cercle de la cité'],
  Lecco => ['Resegone LC'],
  Leipzig => ['bc leipzig'],
  Leksand => ['DBK Dalom'],
  Leverkusen => ['Nachteulen Leverkusen'],
  Lille => ['BC de Lille'],
  Lindesberg => ['Lindesbergs BS'],
  Linköping => ['Smedstadens BK'],
  Lisbon => ['Armando and Viviane Gonçalves Pereira',
    'Benfica', 'Círculo Português de Bridge',
    'Clube de Bridge dos Engenheiros',
    'Lisbon Bridge Association',
    'Núcleo De Bridge Do Círculo', 'Sporting Lisbon'],
  Lodi => ['Fanfulla'],
  Lom => ['Øvre Ottadalen'],
  London => [
    'Royal Air Force Club',
    'TGR', 
    'Young Chelsea Bridge Club'],
  Ludvikabygden => ['Ludvikabygdens BK'],
  Luleburgaz => ['LÜKSAD', 'Luleburgaz SK'],
  Lyon => ['BC Brotteaux'],
  Funchal => ['associação de bridge da madeira'],
  Makassar => ['Makassar Utama'],
  Malatya => ['Altin Kayisi BSK', 'Malatya Yildiz Dogu', 
    'Malatyagücü', 'Malatya BSK'],
  Malmö => ['Malmö BK Scania'],
  Manado => ['CFT Bridge', 'Sekolah Bridge Tonaas Wangko',
    'Swara Kita BS'],
  Manisa => ['Manisa BSK', 'Vestel SK'],
  Manna => ['Manna Bridge Club'],
  Mannheim => ['BC Alert Mannheim', 'BC Universität Mannheim'],
  'Marijampolė' => ['bc sudovia'],
  Marseille => ['Ocean BC'],
  Massy => ['BC Massy'],
  Mersin => ['Icel Sports', 'Mersin Club', 'Meski Club'],
  Michalowo => ['pab michalowo'],
  Midyat => ['Midyat Club'],
  Milan => ['BC Milano', 'Milan CPK Milanowek',
    'Canottieri Olona'],
  Milas => ['Milas Club'],
  Miramar => ['sport clube alberto sousa'],
  Miskolc => ['miskolc deac'],
  'Mo i Rana' => ['Båsmo BK', 'Mo'],
  Moradabad => ['KDI Moradabad'],
  Moscow => ['Avalanche BC'],
  Moss => ['Moss BK'],
  Mragowo => ['Mragowia'],
  Munich => ['bc münchen', 'bc münchen-ottobrunn',
    'münchen sanzatu'],
  Mudanya => ['mudanya gsk'],
  Muðla => ['Muðla GSK'],
  Mumbai => ['ABA Mumbai', 'Matunga', 'Otters Club', 
    'The West End Mumbai', 'WCG Mumbai', 'Bombay Gymkhana Club',
    'willingdon sports club', 'Borivli Sports Club'],
  Nagari => ['nagari club'],
  Namsos => ['Namsos BK'],
  Nanchong => ['Shou Chuang'],
  Nancy => ['Nancy Jarville BC'],
  Napoli => ['Circolo Nautico Posillipo', 'Palcan Bridge ASD'],
  Narvik => ['Narvik BS'],
  Nashik => ['NDBAC Nashik'],
  Nazilli => ['Nazilli BBSK'],
  Näsby => ['Näsby BS'],
  Nesodden => ['nesodden bk'],
  Nganjuk => ['albc nganjuk'],
  Nice => ['Colonial BC'],
  Nilüfer => ['nilüfer bld. bsk', 'yildirimspor'],
  Niš => ['nbk', 'niski bridge club'],
  Noida => ['Avi Club Noida'],
  Norrøna => ['BK Norrøna'],
  'Novi Sad' => ['NS-1'],
  Nürnberg => ['Nürnberg Museum'],
  Nærbø => ['Nærbø BK'],
  Næstved => ['Næstved BK'],
  Nøtterøy => ['Nøtterøy BK'],
  Odense => ['BK 1936', 'Odense BK'],
  Ogndal => ['Ogndal BK'],
  Oldenburg => ['bc oldenburg'],
  Oltenita => ['Phoenix Oltenita'],
  Ordu => ['Ordu BSK'],
  Orhangazi => ['orhangazi sk'],
  Oslo => [
    'Bridgekameratene',
    'Hoppklubbene', 
    'Juniorklubben',
    'OBK Kløverknekt', 
    'Solli', 
    'Top Bridge BC'],
  Osnabrück => ['bc osnabrück'],
  Ozarow => ['Centrum Kultury i Sportu Oze'],
  Örebro => ['Örebridgen'],
  Överum => ['överum bk'],
  Padang => ['Agriculture Bridge Club', 'Semen Padang',
    'Karimata BC'],
  Padova => ['Padova Bridge SS'],
  Palermo => ['Bridge Addaura', 'Circolo del Tennis Palermo'],
  Pamukkale => ['Pamukkale SK'],
  Palu => ['Maesa Palu'],
  Paris => ["BC Djeun's", 'Paris Sud', 'BC Saint Honoré', 
    'Paris Bridge', 'Friedland BC'],
  Pattaya => ['Pattaya BC'],
  Pärnu => ['Pärnu BK', 'Jomtien Bridge Club'],
  Pazar => ['pazar sk'],
  Pekanbaru => ['Rumah Sakit Umum Daerah Pekanbaru', 'Laksamana BSP'],
  Pescara => ['Pescara Bridge'],
  'Ponta Delgada' => ['CB São Miguel'],
  Pontianak => ['Fakultas Teknik Bridge Club Universitas Tanjungpura'],
  Porto => ['Dragao', 'Porto Club',
    'Centro Desportivo Universitário do Porto'],
  Poznan => ['RAL Poznan'],
  Prague => ['Acol Praha', 'Zmrzlina'],
  Radkov => ['ksb radkov'],
  Rayong => ['payoon bridge'],
  'Reggio Calabria' => ['Circolo del Bridge N. Ditto Reggio Calabria'],
  'Reggio Emilia' => ['ASD Reggio Emilia'],
  Rennes => ['BC Rennais'],
  Reykjavik => ['Grant Thornton', 'Vestri'],
  Rieneck => ['Kultcamp Rieneck'],
  Romana => ['Romana Bridge'],
  Rome => ['Tennis Club Parioli', 'Star Bridge Roma', 
    'SSD Angelini Bridge', 'Nuovo Bridge Insieme', 'ASD Tennis Roma',
     "universita' del bridge"],
  Rotterdam => ['bc de lombard'],
  Rubbestadneset => ['rubbestadneset bk'],
  'Russia-Pan' => ['BC Real'],
  Rødovre => ['Rødovre BK'],
  Saarbrücken => ['BC Saarbrücken 1984'],
  Salerno => ['asb salerno'],
  Samsun => ['Polýsgücü', 'Samsun BK'], 
  'San Luis' => ['Salmun BC'],
  'São Vicente' => ['Clube Naval São Vicente'],
  Sariyer => ['Sariyer BSK'],
  Sarpsborg => ['Østfold og Follo'],
  'Schwäbisch Hall' => ['BC Schwäbisch Hall'],
  Seferihisar => ['Seferihisar Municipality'],
  'Seine-et-Marne' => ['bc les templiers'],
  Semarang => ['mustang semarang'],
  Shanghai => ['Qi Zhong Club', 'Qizhong', 'Pudong Club'],
  Shaoguan => ['Shaoguan BA'],
  Sharjah => ['Sharja Club'],
  Sieradz => ['piast mosir sieradz'],
  Sigulda => ['bk sigulda'],
  'Silesia Gliwice' => ['tb silesia gliwice'],
  Silifke => ['silifke sk'],
  Singsås => ['Singsås BK'],
  Sivas => ['Sivasspor'],
  Skara => ['skara bs'],
  Skawina => ['centrum kultury i sportu skawina'],
  Ski => ['Ski BK'],
  Slagelse => ['BK 83 Slagelse'],
  Smedstad => ['st eskil'],
  Smolyan => ['bk smolyan'],
  Sofia => ['BC Lozenets', 'Bonsist', 'Levski Sofia', 'Quantum BC'],
  Solok => ['ebc solok'],
  Sortland => ['sortland bk'],
  Söke => ['söke bsk'],
  Stavanger => ['stavanger bk'],
  Steinkjer => ['Steinkjer BK'],
  Stockholm => ['BC Herkules', 'BK Lavec Smile', 'Lavec', 
    'Nya Bridgeskolan', 'S:t Erik'],
  Stoholm => ['Fjends BK'],
  Storsjöbygden => ['Storsjöbygdens BK'],
  Stuttgart => ['bc stuttgart'],
  Sunndalsøra => ['Sunndalsøra BK'],
  Surabaya => ['tss surabaya'],
  Suzhou => ['suzhou qiaoxie'],
  Szczecinek => ['ks tecza'],
  Søborg => ['Blakset Klubberne'],
  Sørreisa => ['Sørreisa BK'],
  Taiyuan => ['shanxi club'],
  Taskopru => ['taskopru club'],
  Täby => ['Norrorts Bridge', 'Täby BK'],
  Tczew => ['sdk tczew'],
  Tekýrdag => ['Cerkezkoy Dinamik BSK', 'Kapakli Sýte', 'Tekirdað Club',
    'Suleymanpasa Club'],
  'Tel Aviv' => ['ASA University of Tel Aviv'],
  Tire => ['Tire BSK'],
  Tomohon => ['Gereja Masehi Injili di Minahasa',
    'Pria/Kaum Bapa Sinode MMIM'],
  Tonya => ['Tonyaspor'],
  Torino => ['Torino Allegra'],
  Toulouse => ['Bridge Académie Toulouse', 'Toulouse BC',
    'Baragnon BC'],
  Tours => ['Cercle Tourangeau'],
  Trabzon => ['trabzon club', 'idman ocagi sk',
    'yeni pelitli sk'],
  Trieste => ['bc trieste'],
  Tromsø => ['Tromsø BK'],
  Trondheim => ['Studentenes BK', 'Heimdal BK'],
  Udaipur => ['field club udaipur'],
  Umeå => ['BK Björken'],
  Underberg => ['underberg bc'],
  Uppsala => ['BK Fyris Skalman', 'BK Svanslös Skalman', 
    'Uppsalabridgen'],
  Usak => ['Usak SK'],
  Utrecht => ['BC Star', 'Bridgeclub Oog', 'NDC Den Hommel'],
  Uzunköprü => ['uzunköprü sk'],
  Van => ['Van Bric SK'],
  Varna => ['Aso Pika', 'BC Varna'],
  Vasa => ['vasa bk'],
  Västerås => ['ABB BK', 'Västeråsbridgen', 'Top Bridge BC'],
  Vejle => ['Klør 10 Vejle', 'Storeslemmen'],
  Venice => ['Circolo del Bridge Venezia'],
  Vestvågøy => ['Vestvågøy SK'],
  Vikersund => ['vikersund bk'],
  'Villa Fabbriche' => ['ASD Villa Fabbriche'],
  Vorden => ["'t Onstein"],
  Vraca => ['Botev'],
  Waldsolms => ['bv waldsolms'],
  Warsaw => ['Akademia Brydza', 'Auguri Warsaw', 'Spojnia', 'Unia',
    'Wawa Brydz'],
  Wiesbaden => ['1. wiesbadener bc'],
  Wroclaw => ['AZS Wratislawia', 'Ruch AZS', 'Ruch SA'],
  Yatagan => ['Yatagan SK'],
  Zagreb => ['Locomotiva'],
  'Zhong Jian' => ['Zhong Jian Club'],
  Zonguldak => ['zonguldak bsk'],
  Zürich => ['Zurich Enge'],
  Zyrardow => ['ck zyrardow'],
  Åkirkeby => ['Åkirkeby BK'],
  Ålesund => ['BK Grand', 'Møre og Romsdal'],
  Århus => ['akademisk bridgeklub', 'Århus BK'],
  Åsane => ['Åsane BK']
);

my %COUNTRY_TO_SPONSOR =
(
  Australia => ['Derofe', 'Penline'],
  Austria => ['Lupo Veloce'],
  Belarus => ['MB-Transit'],
  Belgium => ['belisol'],
  Bermuda => ['Orbis Investment Management'],
  Brazil => ['Rio-Sampa'],
  Bulgaria => ['Chateau Rossenovo', 'Gillette', 'Impress', 'Malkia', 
    'Mech-Ok', 'Parvomay Tomato', 'Pliska XO', 'Sevtopolis', 'Struma', 
    'Unicat', 'Velbazhd', 'Velbujd', 'Villa Yustina', 'Vinex Preslav', 
    'Vito'],
  Canada => ['wellwise'],
  Chile => ['fullbridge'],
  China => ['Aershan Haishen', 'Beibao', 'Beidike', 'Beijing Capital', 
    'Beijing Cartoon', 'Beijing Century', 'Beijing Construction',
    'Beijing Dazhong', 'Beijing Evertrust', 'Beijing Huayuan', 
    'Beijing Hull Technology', 'Beijing Jinghua', 'Beijing Lawyers', 
    'Beijing Liuhe', 'Beijing Longxin', 'Beijing Railway Bureau', 
    'Beijing ShouChuang', 'beijing Tianzhixing', 'Beijing Trinergy', 
    'Beijing Wan Jia', 'BeiJing Xiaoganju', 'BeiJing Xiaojungan',
    'Beijing Yue Ze', 'Beijing Yindi', 'Bnerg', 'Cai Fu Zheng Quan',
    'Changyu', 'Chengdu Zhongtai', 'China Evertrust', 'China Finance', 
    'China Global Times', 'China National Petroleum Corporation', 
    'China Ping An', 'China Renshou', 'China Resources', 
    'China Trinergy', 'Chinese Hailian', 'Chongqing Jianke', 
    'Chongqing Jinjian', 'Chongqing Shangyou', 'Chuanmei', 'Copia', 
    'Dalian Dichan', 'Dalian Aoxin', 'Datang', 
    'Dian Zi Cheng', 'Dianwang', 'Dongfeng', 'Dongfang Tairong', 
    'Dragon Sports', 'Evertrust', 'Fanhua Jituan', 
    'GaoSuDa', 'Geely Automobile', 'Gong Hang Jin Ying', 'Guowang',
    'Guangdong Huachu Chemicals', 'Guangxi Tianhu', 
    'Guangzhou Hongmian', 'Guangzhou Huachu Chemicals', 
    'Guangzhou Mingjian', 'Guangzhou Pearl River', 'Guiyuang Bank', 
    'Guizhou Bangda', 'Guowang', 'Haerbin Bingxue', 'Hai Long', 
    'Hainan Air', 'Hainan Shichuang', 'Hainan Window', 
    'Haining Ziwei',
    'Haiyang Ruixiang', 'Hangzhou Jinjiang', 'Haoxin',
    'Heilongjiang Tea', 'Heng Yuan Xiang', 'Hengsha Haijiu', 
    'Hengsha Ke Ji', 'Hengzhou Group', 'HNA', 'Ho-Hsing', 'Hong Zhu', 
    'Hongyu', 'Huabin Aoruijin', 'Huachu', 'Huangshi Qixing', 
    'Huayuan', 'Hubei Bank', 'Hubei Dongfeng', 'Hubei Yihua', 
    'Hunan Mingkai', 'Hunan Tou Zhan', 'Jetox', 'Jiang You', 
    'Jiangxi Hengkang', 'Jiegao', 'Jilin Dingyuan', 'Jin Rong', 
    'Jin Jing', 'Jinfan', 'jinsheng development', 'Jinshi', 
    'Jing Tie', 'Kuncheng Group', 'Kunhua', 'LCG', 'Lianbo', 
    'Lianhua Keji', 'Lianzhong Shi Jie', 'Longjiangfu', 'Lu Cheng', 
    'Lu Ning Coal', 'Lv Hua', 'Mai Zi Fu Shi', 'Mei Kuang', 
    'Meilin Qing Cheng', 'Mingxin Jituan', 'Nanfang Dianwang', 
    'Nangang Power', 'Nanning Yalun', 'Nanyuan', 'Nong Fa Hang', 
    'Nongken', 'Norco', 'Nuo Hui Jian Kang', 'Oly-Star', 
    'Pan China Group', 'PD Real Estate', 'PD Times', 
    'PD Transnational', 'Pan China Construction', 'Pufa',
    'Qianli Guangda', 'Qiaoyou', 'Qinjia', 'QingLong KeJi',
    'Qingnian Qiche', 'Red Cotton', 'Ruyi', 'SAIC VW',
    'San Yutian', 'Sanya Haihe', 'Sanya Jiguan', 'Sanya Tianze', 
    'Shan Hai', 'Shanghai Automobile', 'Shanghai Changyu', 
    'Shanghai Chenyi', 'Shanghai Financial', 'Shanghai Gaohe', 
    'Shanghai Jiahua', 'Shanghai Jinchang', 'Shanghai Jingfan',
    'Shanghai Ling Mu', 
    'Shanghai Media and Entertainment Group', 'Shanghai Qiche', 
    'Shanghai Qihao', 'Shanghai Qi Zhong', 'Shanghai Weiyu', 
    'Shanghai Yitong', 'Shanghai Zhongfu', 'Shanxi Luning', 
    'Shanxi Qinlian', 'Shen Jiu', 'Sheng He Wan', 'Sheng Tao Sha', 
    'Sheng Yu Tian', 'Sheng Yuan', 'Shengheng', 'Shenha Qiaoyou',
    'Shenzhen Electronic City', 'Shenzhen Huabei',
    'Shenzhen Lanpu', 'Shenzhen Nangang', 'Shenzhen Ping An', 
    'Shenzhen Qiayao', 'Shenzhen Qiyuan', 'Shenzhen Topone Car', 
    'Shi He Dong Li', 'Shi You', 'Shichuang', 'Shiji Changda', 
    'Shouchuang', 'Sichuan Dahe', 'Sifute', 'Siji Changda',
    'Sunchime Cartoon', 'Sunchime Fund', 'Sung Tao', 
    'Suzhou Youtong', 'SY Sheng Yutain', 'Synrey', 'TianJin JS2',
    'Tielu Jixie', 'Tin Fok', 'Tsingtao', 'Wuhan Dongfang', 
    'Xiamen Xiashun', 'Xiao Ying', 'Xin He Jin Tai', 
    'Yalu Group', 'Yanjin Puzi', 'Yibin China Resources', 
    'Yi Tong', 'Yuetao', 'YJ Health', 'Yufeng Electric', 
    'Yunnan Dikuang Resources', 'Yunnan Tongya', 'Zhai Meng Yi Dao',
    'Zhaoeng', 'Zhe Da Wang Xin', 'zhejiang huamen',
    'Zhejiang Jingfan', 'Zhejiang Jinjian', 'Zhejiang Xinxiang', 
    'Zhenjiang Hanbang', 'Zhenjiang Jingjiang', 'Zhong Guo Ren Bao', 
    'Zhong Liang Y LW', 'Zhong Yuan', 'Zhonghai', 'Zhongshan Jiegao', 
    'Zhongtong Jiangsu', 'Zhu Jiang'],
  Croatia => ['Atlantic Trade', 'Mireo', 'Plovac Ploski',
    'Stanicic Software', 'Termoavion'],
  Denmark => ['Dagensbridge.dk', 'Nescafe Gold', 'Nordfyns Finans', 
    'Team Audita', 'Team PharmaService', 'XP Digital'],
  England => ['Intobridge.com', 'Pharon', 'Red Bull'],
  Estonia => ['Baltic Express', 'Druva', 'Eksprompt', 'Kilogrupp',
    'Pealinn', 'Printerikeskus', 'Raam', 'Unibet', 'Viru Valge',
    'Z-Tech'],
  Finland => ['Iso Karhu', 'Näkösoppi', 'Nordic Security'],
  France => ['BridgePlus', 'Cap Gemini', 'Funbridge', 'Jet Immo', 
    'Multicoms', 'Société Générale'],
  Germany => ['Allianz', 'Holzhauer IT-Service', 'Paulaner'],
  Greece => ['Kale Park', 'Tzilis'],
  'Hong Kong' => ['AIA', 'Avia Financial', 'CCH Power', 
    'Hong Kong Vico', 'JP Morgan', 'K.W. Tam', 'L&Y Law',
    'Phoenix TV', 'Stonehill Capital', 'Wellwise'],
  Hungary => ['Ecosoft', 'Elastron', 'GAMAX', 'Interface', 
    'Nimbusz', 'Visoft'],
  Iceland => ['101 Fasteignasala', 'Actavis', 'Betri Ferðir',
    'Betri Frakkar',
    'Breki Jarðverk', 'Bridgefélag Reykjavíkur', 'Bústólpi ehf', 
    'Eimskip', 'Enorma', 'ESSO', 'Ferðaskrifstofa Vesturlands', 
    'Fisk Seafood', 'Garðar & Vélar', 'Garðs Apotek', 'Gevalia', 
    'GSE', 'Haustak', 'HF Verðbréf', 'Hótel Hamar', 
    'Hótel Norðurljós', 'Hreint ehf', 'Iceland Express', 
    'Info Capital', 'Íslenskur Landbúnaður', 'Kjaran ehf', 
    'Kollgáta Arkitektúr', 
    'Kvika', 'Lekta ehf', 
    'Lögfræðiskrifstofa Islands', 'Lögfræðistofa Bjarna', 
    'Lyfjaver', 'Málning hf', 'Morgunblaðið', 'Myndform', 
    'Myvatn Hotel', 'Ráðgjöf', 'Sagaplast', 'Skeljungur', 
    'Skinney-Þinganes', 'Sölufélag Garðyrkjumanna', 'Sparisjóður', 
    'Sparisjóður Keflavik', 'Sparisjóður Norðfjörður', 
    'Sparisjóður Siglufjarðar', 'SR Group', 'VBS Fjárfestingarbanki hf.',
    'Vidbot ehf', 'Vinabær', 'Virnet', 'VÍS', 'Tick Cad',
    'Tryggingamiðstöðin', 'Wise'],
  India => ['Accenture', 'Andromeda Baroda', 'APRA Clothing', 'Avia',
    'Bajaj', 'Balarampur Chini', 'Bangur Cement', 'Baroda Bank', 
    'BridgeYes.com', 'Cable',
    'Central Secretariat', 'Chennai Online', 'Constellation',
    'Cosmos', 'Dhampur Sugar', 'Easy Bridge', 'Eden Realty Kolkata', 
    'eDOT Goa', 'Enterprise', 'Godfrey Phillips', 'HCL', 
    'ICSA Groups', 'Indian Chain', 'India Glycols', 'Indian Medical', 
    'Indian Oil', 'Indian Overseas Bank', 'Indian Railways', 
    'Interkala', 'Jain Group', 'Kaushik Hyderabad', 
    'KH Power', "Kini's Bangalore", 'Kosmos Delhi', 
    'Krishnapatnam Port', 'Manzoya Casual', 'Mayur Renergy', 
    'Mitratani', 'NALCO', 'Navachaitanya', 'Navayuga', 'Nest Inn', 
    'OCI Copper', 'Phoenix Mills',
    'Poddar Developers', 'Poddar Housing', 'Quik Tea', 
    'Ryan Express', 'Ryka', 'Sarla Fibers', 'SD Associates', 
    'SD Enterprises', 'SD Traders', 'Shree Cement', 
    'Shree Radhey', 'Smart Max', 'Sol da Caparica', 'Srenniw', 'SSDA', 
    'Tata Consulting Services', 'Taste of Goa', 'Team Secure', 
    'Tekser', 'Tolani Shipping Ltd', 'Trambak Rubber', 
    'Tricon Infotech', 'TTK Healthcare', 'TVS Mobility', 'TVS Tread', 
    'UTI Bank', 'Wellknit'],
  Indonesia => ['Abadi Adimulia', 'Adaro Energy', 'Aerospace', 
    'Agsar Paints', 'Aklindo', 'Alunand Limboto', 'Apical',
    'Asindo', 
    'Asindo Prima', 'Bank Indonesia', 'Bank Mandiri', 'Bank Nagari',
    'Bank Negara Indonesia', 'Bank Tabungan Negara', 
    'Bapenda Manado',
    'Bayu Kencana', 'Buleleng Dewata', 'Cempaka', 'Dauna Winaza',
    'Djarum', 'Djarum Black', 'Djarum Bold', 'Electric Center', 
    'Elektrik P3B',
    'Elektrika', 'Geo BSP', 'Geo Kideco', 'Geo Pertamina', 'Geo Timah', 
    'Geo Vale', 'Geologi', 'Geologi Banpu', 'Geoportal Kutai Kartanegara', 
    'Harke', 'Indoarsip', 'Intan', 'Inteligent', 'Indonesian Power',
    'Jasa Marga Jakarta', 'Kedai Lae', 'Kideko', 'Kombi Tondano', 
    'LAPI Laboratories', 'Makus', 'Manado Cerdas', 'Mandiri Minahasa', 
    'Metaforsa', 'Mitra Buana', 'Mutiara Energy', 'OICO Maesa',
    'P2TEL', 'Palma Karya Mandiri', 'Penajam PU', 'Perbankan Jatim',
    'Pertagas', 'Pertamina', 'Petroconas', 'PGN Jakarta', 'PU Bitung', 
    'PU Minsel',
    'PU Sulut', 'Perusahaan Listrik Negara', 'Pimara', 'PLN Fortuga',
    'PLN Suluttenggo', 'PT Bayu Buana Gemilang', 'PT Bumi Siak Pusako',
    'RSUD Mandau',
    'Samadhan Academy', 'Sarunta Waya', 'sawahlunto berkah', 'Sehati',
    'Semangat Baru Makassar', 'Semen Gresik', 'Sinode GMIM',
    'Siwik Holiday Mragowo',
    'Siwik Intertrade', 'Syabas Energy', 'Telkom',
    'Telkom Groovia', 'Telkom IndiBiz', 'Telkom IndiHome',
    'Telkom IndiSchool', 'Telkom Indonesia', 'Telkom Jabar', 
    'Telkom Jakarta', 'Telkom Speedy', 'Telkom UseeTV',
    'Telkom@wifi.id', 'TGBC Indibiz',
    'Timah', 'TJ Jabung Brt', 'Tridaya', 'Videocon'],
  Italy => ['Apullum', 'Argento', 'Bozzetto Azzurro', 'Carlo Bossi', 
    'Dalli Cardillo', 'Fantoni Vacations', 'Generali', 'Horsa',
    'Il Bridge', 'Lavazza', 'Rosa dei Venti', 'Spasso Food'],
  Japan => ['Akebono', 'Hana', 'IMAX', 'monbu japanese ministry', 
    'NEC', 'Shimuzu'],
  Latvia => ['Laima', 'Pexis', 'Rigainvites.lv'],
  Lithuania => ['Bridgescanner', 'Garsu Pasaulis'],
  Malaysia => ['Likom', 'UMW'],
  Netherlands => ['Aquatrans', 'Arboned', 'Continental',
    'Delfts Brouw', 'Forbo', 'ING Bank', 'Melchemie', 'Modalfa', 
    'Ravebo', 'Twentebelt', 'VVE Beheer'],
  Norway => ['ABAX', 'Advisor Revisjon Norge', 'Askim Turn og Lakk',
    'Astro A/S', 'Bridge i Norge', 'Bridgemagasiner.no', 
    'ECF Holding', 'Elf Holding', 'Fossen Eiendom', 'FX Securities',
    'konkurs.no', 'Malermester Mathisen', 'Nortemp', 
    'Polarman Regnskap', 'Ragn Sells', 'SLG Skeidar', 'Svartisen.com', 
    'Tannlege Kvaran', 'Viego Regnskap', 'Worldbridgetour.com'],
  Pakistan => ['Candyland', 'Century Insurance', 'Data Steel',
    'Kayseria', 'Solox'],
  Poland => ['A-Media Sieradz', 'Abnegat', 'Agena Development',
    'AJ Diament', 'Alfa-Compensa Gdynia', 'Apreo Logistic Poland', 
    'Asko-Tech', 'bridge24.pl', 'Bridge for Fun', 'Bridge for Business', 
    'Budimex', 'Byle Co',
    'Chemikartel', 'Chlodnia', 'COMAL', 'Computerland', 'CONNECTOR',
    'Construction Kielce', 'CONSUS', 'Consus Carbon', 'Consus Oil',
    'Darles Santerm', 'Dermika', 'Diebold Nixdorf Krakow',
    'Dobre Zegary', 'domwaluty.pl', 'E-Service', 'Effcontrol', 
    'Eko-Al', 'Elektrociepl', 'Elektromonta¯', 'Eskom IT',
    'Euro Agro', 'Energetyk', 'Falck Medical', 'Forta', 
    'forumbridge.pl', 'Gomad', 'Honesta', 'Hotel Senator', 
    'Interbud Plock', 'Kadimex', 'Kancelaria', 'Klika Murcki', 
    'KONKRET Chelmno', 'Konstanta', 'Kurt-Royce', 'Lacznosc', 
    'Latteria TS Rzepin', 'Mega-Tech', 'Nazwa', 'Nefka', 'Niewiem', 
    'NOTUS', 'Pasta z Bobra', 'Petro', 'POLFA', 'Ponar Unia', 
    'Powszechna Kasa Oszczędności Bank Polski', 'Praterm', 
    'Prestige Development', 'Prokom', 'Relpol', 'Radex', 'Samsung', 
    'SAPW Poland', 'Signity', 'Skobud', 'SPS Construction', 
    'Stalgast', 'Stokrotka', 'Sygnity', 
    'Synergia Ilanka', 'Synergia Lublin', 'Syntex', 'TAM Dabrowa', 
    'Techbud Elblag', 'Termika', 'Termochem', 'Topeko', 
    'Unia Leszno', 'Unia Winkhaus', 'Unia Sygnitas', 'Value Media', 
    'Vyceska', 'zagraj.pl', 'Zolza', 'Zweryfikuj Firme'],
  Romania => ['Logi Smart', 'Pharma Plus', 'Pro Consul', 
    'Samtronic Constanta'],
  Russia => ['Gazprom', 'Lukomorie', 'Moscow Sunday Times',
    'Russian Sunday Times', 'Staryi Master',
    'stroiprodukt kraich'],
  Serbia => ['Novi Kod'],
  Singapore => ['Saniva', 'Sing Phil', 'Tyco', 'YOU Singapore'],
  Slovenia => ['Triglav Osiguranje'],
  Sweden => ['artotec', 'Bokadirekt SE', 'Brink Plast',
    'BridgeBertheau.com', 'Cuebids.com', 'Frissan', 'Hotell Strand', 
    'Konga-Väster', 'Lag os', 'Junibacken', 'Ronke Camping', 'San-Sac', 
    'Scania', 'Scania Bridgekonsul', 'Scandic', 'Spintop Ventures',
    'Stiga', 'Synective', 'Transearly'],
  Switzerland => ['sportaccord'],
  Taiwan => ['Fatek', 'Mega Giant', 'San Chen', 'Yeh Bros'],
  Thailand => ['Bangkok Bank', 'Metropolitan Electricity Authority',
    'See Fah/Thai', 'Tangerang Raya', 'Thai Oil'],
  Turkey => ['Akaylar', 'Alfa Romeo', 'Aliaga Kyme', 'Altinay',
    'Ant Teknik', 'Arkas', 'Arma', 'Atlas Profil', 'Ayýntab', 
    'Balcova Termal', 'Baykar', 'Caretta International', 
    'Cimentas', 'Cumhuriyet OOSK', 'Dama Kupa', 'Delta TV',
    'Denizgucu', 'Dentgroup Nisantasi', 'DISKI', 'Doga Naturale', 
    'Dostlar', 'Ekin Maden', 'Fora Lastik', 'Forsa Yatcilik', 
    'Genkad', 'Gözgöz', 'IBM', 'Inci Ayakkabi', 'Karasu Mermer', 
    'Kare Dam', 'Kirmizi Beyaz', 'KIS Sigorta', 'Magpa-Grup', 
    'Maksoy-Deniz', 'Meditepe Tip', 'Mega Bekasi Hypermall', 
    'Odak Göz', 'Ozyuva', 'Pusula', 'Sanliurfa Tarim', 'Solakoglu', 
    'Son Dakika', 'Statu Denizcilik', 'Statu Gemi Kiralama', 
    'Tundem', 'Turkish Power'],
  USA => ['Bridge Winners', 'PRI Investment']
);

my %COUNTRY_TO_NATIONALITY =
(
  Argentina => ['argentinian'],
  Australia => ['australian'],
  Austria => ['austrian'],
  Belarus => ['belarusian'],
  Belgium => ['belgian'],
  Bolivia => ['bolivian'],
  Brazil => ['brazilian'],
  Bulgaria => ['bulgarian'],
  Canada => ['canadian'],
  Chile => ['chilean'],
  Croatia => ['croatian'],
  Cuba => => ['cuban'],
  'Czech Republic' => ['czech'],
  Egypt => ['egyptian'],
  England => ['english'],
  Estonia => ['estonian'],
  'Faroe Islands' => ['faroese'],
  Finland => ['finnish'],
  France => ['french'],
  Germany => ['german'],
  Greece =>['greek'],
  Hungary => ['hungarian'],
  Iceland => ['icelandic'],
  India => ['indian'],
  Indonesia => ['indonesian'],
  Ireland => ['irish'],
  Israel => ['israeli'],
  Italy => ['italian'],
  Japan => ['japanese'],
  Latvia => ['latvian'],
  Lebanon => ['lebanese'],
  Lithuania => ['lithuanian'],
  Netherlands => ['dutch'],
  Norway => ['norwegian'],
  Poland => ['polish'],
  Portugal => ['portuguese'],
  Romania => ['romanian'],
  Scotland => ['scottish'],
  Serbia => ['serbian'],
  'South Africa' => ['south african'],
  Spain => ['spanish'],
  Sweden => ['swedish'],
  Taiwan => ['taiwanese'],
  Turkey => ['turkish'],
  Tunisia => ['tunisian'],
  Wales => ['welsh']
);


sub set_matrix
{
  my ($whole) = @_;
  $whole->set_matrix_link(\%COUNTRY_TO_REGION, 'COUNTRY', 'REGION');
  $whole->set_matrix_link(\%COUNTRY_TO_CITY, 'COUNTRY', 'CITY');
  $whole->set_matrix_link(\%CITY_TO_LOCALITY, 'CITY', 'LOCALITY');
  $whole->set_matrix_link(\%CITY_TO_UNIVERSITY, 'CITY', 'UNIVERSITY');
  $whole->set_matrix_link(\%CITY_TO_CLUB, 'CITY', 'CLUB');
  $whole->set_matrix_link(\%COUNTRY_TO_SPONSOR, 'COUNTRY', 'SPONSOR');
  $whole->set_matrix_link(\%COUNTRY_TO_NATIONALITY, 
    'COUNTRY', 'NATIONALITY');
}


sub get_city_club_list
{
  my ($city) = @_;
  return undef unless exists $CITY_TO_CLUB{$city};
  return $CITY_TO_CLUB{$city};
}


1;
