#!perl

# Last names that appear between the first and last words in
# the EBL file.  It is assumed that the first and last words are
# capitalized correctly to cut down on the length of the list.

package LastMid;

use strict;
use warnings;
use v5.10;
use Exporter 'import';

our @EXPORT = qw(@LAST_MID_NAMES);

use utf8;

our @LAST_MID_NAMES =
qw(
  AASAND ABATE ABI ABOU ABREU AGUADO AIT AJI ALBERTI ALMEIDA ALTMANN 
  ALVARADO ALVARES ALVAREZ AMMENDOLIA ANAVI ANCHISI ANDERSON ANDRADE 
  ANG ARAUJO ARGAYNE ARMIJO ARREAGA ARREAGE ASHAK ASPLUND ATTARD 
  AVILES AZZALI 

  BACCHI BAJOS BALLERINO BALLI BANG BAPTISTA BARCOS BARDEN BARONE 
  BARRERA BARROS BASELGA BASHEER BATALLA BATZIA BAUCK BAYRAK BEIRAO 
  BELLERIO BELLIS BELLOCQ BELLUSSI BELRHITI BEMMEL BENATAR BENDER 
  BENSBY BERG BETTENCOURT BETTI BILDE BJOERBEKK BO BONADIES BONANOMI 
  BONNY BORDALLO BORSARELLI BOSCARO BOU BREDIUS BRENDERFORD BRENNA 
  BRITO BRIX BROEKSTEEG BRORHOLT BRUGNONI BRUM BRUN BRYDE BUELENS 
  BUENO BUI BULLARD BUUS 

  CABANNE CADI CALVO CAMARGO CANALI CANDUCCI CANER CANESSA CAPBERN 
  CAPELLI CAPION CARINI CARME CASALE CASTELLO CASTRO CATASTINI 
  CATTANEO CESARI CESATI CHACON CHAMACHERIL CHAMORRO CHAN CHAVES 
  CHERIF CHIN CHINDEMI CILLEBORG CIVIDIN CLASSEN COLOMBO COLONNA COOK 
  CORREA CORREIRA CORSICO COSIGNANI COSSU COSTA COUTINHO CREDAZZI 
  CRIADO CRISAFULLI CROCI CUBILLO CUERVO CUEVA 

  D'ANDREA D'AVE D'OREY DAL DALDOUL DALEMARK DAM DARNISA DASH 
  DELLADIO DELPIANO DENEGRI DIAZ DIEZ DIMITROV DOBREVA DONG DOUER 
  DRINOVEC DUQUE DWYER DYBVIK 

  ECK EDWARDS ELDON ERICH ERTBJERG ESCOBAR 

  FABBRI FAHMY FANTONI FARHANI FARINA FERGUSON FERLAZZO FERNANDES 
  FERNANDEZ FIGUEIRA FINCHELTUB FLORIN FOLLIERO FOO FRANCES FRANCISCI 
  FUN FUNG 

  GAMIO GANDINI GARCIA GARRIGOU GARRONE GATT GERMANETTI GIACCHINI 
  GLAZER GOETZ GOLDFARB GOLFARELLI GOMES GOMEZ GONCALVES GONZALES 
  GONZALEZ GRASHOLT GRAYSON GUANG GULDBRAND GUPPU 

  HALD HAM HAMADEH HANSEN HARALDSDOTTIR HARLAND HAYMAN HELAL HELDAL 
  HELLENBERG HERNANDEZ HERRERA HINZ HJORTH HOEL HOLM HOLMEN HOLTZ HUC 
  HVIDBERG 

  IN INDHU ISRAEL ISRAELI IVANES 

  JANSE JARAMILLO JEITZ JELLOULI JIMENEZ JONES JUCHIMOWICZ JUHL JUL 
  JUST JUUL 

  KAELIN KAI KEE KEITH KERLERO KIRK KIRKEGAARD KLIBI KOCH KOFOED 
  KONDAKCI KORDY KORRE KRAFT KRAGH KROGH KRUSE KUMAR KUREK KURTOGLU 

  LA'O LAM LAMA LANZOTTI LAUGE LECIS LEMAITRE LEVY LI LIAQUAT LINDAAS 
  LINTRUP LOENBERG LOPES LOPEZ LORENTE LOSCHI LOURDES LOURES LOVEJI 
  LUCA LUND LUO LUZ LYBECH LYNGE 

  MAGALHAES MARANI MARCHESE MARITI MARSH MARTHEN MARTINEZ MATEO MATHE 
  MAURY MAZE MAZZADI MEJIA MELLADO MENDES MENDOZA MEW MICALI MIER 
  MILESI MIQUELEZ MOELLER MOHD MOLLER MONTEIRO MONTES MORCK MOREIRA 
  MOUSTAFA MUSCAT 

  NAAS NAYER NEGRIN NIELSEN NIKOLOV NOEL NOERHAVE NORMAN NYHEIM 
  NYVANG 

  OLIVEIRA 

  PABIS PAES PALANCA PALMA PAOLI PARASIAN PAULI PAZ PELAEZ PENNINO 
  PEREIRA PEREZ PERSIVALE PHAM PINTO POLI POLIMENI POMARES PONCE 
  PORTANTI PORTO POWELL PRASETYO PRATO PUIG 

  QUERAN 

  RAHTJEN RAIKO RAMIREZ RANDLE RASK RASMUSSEN RAULUND REDDY REIMER 
  REY REYES RIBEYRO RICCI RICHARD ROBERT ROCABERT ROCHA ROGVU ROLD 
  ROSELL ROSEN ROUANET ROZPIDE RUMOR RUSSO RUZ 

  SAAID SAINTE SAINZ SALAZAR SANCHEZ SANCHO SANTOS SATHYAMANGALAM 
  SCHENK SCHMIDT SCHNETZER SEABRA SEGURA SELLAN SEQUI SERCY SERRANO 
  SEVERIN SGOLOMBIS SHAHIDUL SHAMS SHAUQ SHLESINGER SIANIPAR SILVA 
  SILVERMAN SIMON SKAK SKAUG SKOGLY SMADILO SOLLI SOUSA SPINOLA 
  STAMATOV STAUGAARD STEEN STEIGER STEWART STRAND STRANDE SUAREZ 
  SUNGUR SYDNEY 

  T'KINT TAN TANEV TEKTURK THEISS THITTAI THRANE THUNBO TIRTA TJON 
  TOCCO TORKELSEN TORNBERG TRAN TROELS TRONCHETTI TURLETTI TUTTOBENE 
  TVEDEN 

  UD URIBE USBER 

  VADUMANGUDI VAGN VAISBICH VALENTI VALENZUELA VARGAS VEEL VELANDO 
  VERDI VERMEHREN VIGORELLI VILA VILBORG VILLE VINBERG VIVARELLI VYDT 

  WAN WANG WEI WEISS WHEATLEY WICKBE WILLE WINGAARD WONG 

  XIAO 

  YEH 

  ZACK ZAIDENBERG ZAMMIT ZAMORA ZEDDA ZUNIGA
);

1;
